local region = {}
  region.cmd = "fly cs"
  region.name = "嵩山"
  region.id = "cs"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd;s;s;s"
      region.rooms[1].name = "太室阙"
      region.rooms[1].zone = "北京|嵩山"
      region.rooms[1].id = 1080
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 1079
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 1385
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "east|north|west"
      region.rooms[1].desc = "    嵩山古称方外，又称崇山，为五岳中的中岳，由太室少室二山沿绵而成。汉武帝时称 \"嵩高\" ，取自诗经 \"嵩岳维高，峻极于天\" ，道教以之为第六小洞天。阕高丈余，南面刻 \"中岳太室阳城\" 六字，篆文古朴，苍劲有力。向西就是去少室山少林寺的路。向北一里许便是中岳庙了。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd;s;s"
      region.rooms[2].name = "天中阁"
      region.rooms[2].zone = "嵩山"
      region.rooms[2].id = 1385
      region.rooms[2].links = {}
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 1080
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 1386
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "south|north"
      region.rooms[2].desc = "    天中阁是中岳庙的大门，原称黄中阁。庙内有古柏三百余株，金石碑碣百余座。庙前石翁仲，雕制古朴。南面是嵩山的出口太室阙。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd;s"
      region.rooms[3].name = "崇圣门"
      region.rooms[3].zone = "嵩山"
      region.rooms[3].id = 1386
      region.rooms[3].links = {}
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 1385
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 1387
          region.rooms[3].links.n.con = ""
      region.rooms[3].exits = "south|north"
      region.rooms[3].desc = "    崇圣门前古神库有四座镇库铁人，高达丈许，振臂握拳，怒目挺胸，身姿雄健。向北就是中岳庙最大的殿宇中岳大殿了。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd"
      region.rooms[4].name = "中岳大殿"
      region.rooms[4].zone = "嵩山"
      region.rooms[4].id = 1387
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 1386
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.nu = {}
          region.rooms[4].links.nu.to = 1388
          region.rooms[4].links.nu.con = ""
      region.rooms[4].exits = "south|northup"
      region.rooms[4].desc = "    大殿面阔九间，进深五间，重檐庑殿式屋顶，座落在七尺高的台基上，气势雄伟。大殿中供奉岳神天中王。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly cs;sd;sd;sd;sd;sd;d;sw"
      region.rooms[5].name = "山道"
      region.rooms[5].zone = "嵩山"
      region.rooms[5].id = 1388
      region.rooms[5].links = {}
        region.rooms[5].links.ne = {}
          region.rooms[5].links.ne.to = 1407
          region.rooms[5].links.ne.con = ""
        region.rooms[5].links.nw = {}
          region.rooms[5].links.nw.to = 1389
          region.rooms[5].links.nw.con = ""
        region.rooms[5].links.sd = {}
          region.rooms[5].links.sd.to = 1387
          region.rooms[5].links.sd.con = ""
      region.rooms[5].exits = "northwest|southdown|northeast"
      region.rooms[5].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。左边通往启母石，右手是芦岩瀑布。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly cs;sd;sd;sd;sd;sd;d;sw;nw"
      region.rooms[6].name = "启母石"
      region.rooms[6].zone = "嵩山"
      region.rooms[6].id = 1389
      region.rooms[6].links = {}
        region.rooms[6].links.nu = {}
          region.rooms[6].links.nu.to = 1391
          region.rooms[6].links.nu.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 1390
          region.rooms[6].links.w.con = ""
        region.rooms[6].links.se = {}
          region.rooms[6].links.se.to = 1388
          region.rooms[6].links.se.con = ""
      region.rooms[6].exits = "northup|southeast|west"
      region.rooms[6].desc = "    这里有一壁三丈巨石当道。相传大禹治水时要打通辕擐山，大禹化熊扒挖不止。禹妻涂山氏送饭时不慎撞破，失惊而逃，到此化石。其时涂山已有身孕，大禹追及唤子，巨石北裂一口，夏启呱呱落地。巨石因此唤作启母石。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly cs;sd;sd;sd;sd;sd;d;sw;nw;w"
      region.rooms[7].name = "启母阙"
      region.rooms[7].zone = "嵩山"
      region.rooms[7].id = 1390
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 1389
          region.rooms[7].links.e.con = ""
      region.rooms[7].exits = "east"
      region.rooms[7].desc = "    启母阙在嵩山南麓万岁峰下，是汉代启母庙前的神道阙，和太室阙同为中岳汉三阙之一。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly cs;sd;sd;sd;sd;sd;d;sw;nw;nu"
      region.rooms[8].name = "山道"
      region.rooms[8].zone = "嵩山"
      region.rooms[8].id = 1391
      region.rooms[8].links = {}
        region.rooms[8].links.sd = {}
          region.rooms[8].links.sd.to = 1389
          region.rooms[8].links.sd.con = ""
        region.rooms[8].links.nu = {}
          region.rooms[8].links.nu.to = 1392
          region.rooms[8].links.nu.con = ""
      region.rooms[8].exits = "northup|southdown"
      region.rooms[8].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly cs;sd;sd;sd;sd;sw;sd;se;sd;se"
      region.rooms[9].name = "嵩阳书院"
      region.rooms[9].zone = "嵩山"
      region.rooms[9].id = 1392
      region.rooms[9].links = {}
        region.rooms[9].links.sd = {}
          region.rooms[9].links.sd.to = 1391
          region.rooms[9].links.sd.con = ""
        region.rooms[9].links.nw = {}
          region.rooms[9].links.nw.to = 1393
          region.rooms[9].links.nw.con = ""
      region.rooms[9].exits = "northwest|southdown"
      region.rooms[9].desc = "    这里原是嵩阳寺。现在文化昌明，就改成了嵩阳书院，和睢阳书院，岳麓书院，白鹿书院合称天下 \"四大书院\" 。北宋程颢程颐曾在此讲学。院内有古柏三株，汉武帝巡游至此，册封为大将军，二将军，三将军。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly cs;sd;sd;sd;sd;sw;sd;se;sd"
      region.rooms[10].name = "山道"
      region.rooms[10].zone = "嵩山"
      region.rooms[10].id = 1393
      region.rooms[10].links = {}
        region.rooms[10].links.nu = {}
          region.rooms[10].links.nu.to = 1394
          region.rooms[10].links.nu.con = ""
        region.rooms[10].links.se = {}
          region.rooms[10].links.se.to = 1392
          region.rooms[10].links.se.con = ""
      region.rooms[10].exits = "southeast|northup"
      region.rooms[10].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly cs;sd;sd;sd;sd;sw;sd;se"
      region.rooms[11].name = "嵩岳寺"
      region.rooms[11].zone = "嵩山"
      region.rooms[11].id = 1394
      region.rooms[11].links = {}
        region.rooms[11].links.nw = {}
          region.rooms[11].links.nw.to = 1396
          region.rooms[11].links.nw.con = ""
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 1395
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.sd = {}
          region.rooms[11].links.sd.to = 1393
          region.rooms[11].links.sd.con = ""
      region.rooms[11].exits = "northwest|southdown|west"
      region.rooms[11].desc = "    这里原是北魏离宫。孝明帝舍为佛院，至隋方有今名，寺围阔大，僧舍连云。院内风动旌扬，松摇竹乱，别有一般清静。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly cs;sd;sd;sd;sd;sw;sd;se;w"
      region.rooms[12].name = "嵩岳寺塔"
      region.rooms[12].zone = "嵩山"
      region.rooms[12].id = 1395
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 1394
          region.rooms[12].links.e.con = ""
      region.rooms[12].exits = "east"
      region.rooms[12].desc = "    嵩岳寺塔为密檐式砖塔，高达十余丈，外廓十二面，内室八方四门，十五层密檐塔刹向上收紧，优美绝伦。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly cs;sd;sd;sd;sd;sw;sd"
      region.rooms[13].name = "山道"
      region.rooms[13].zone = "嵩山"
      region.rooms[13].id = 1396
      region.rooms[13].links = {}
        region.rooms[13].links.nu = {}
          region.rooms[13].links.nu.to = 1397
          region.rooms[13].links.nu.con = ""
        region.rooms[13].links.se = {}
          region.rooms[13].links.se.to = 1394
          region.rooms[13].links.se.con = ""
      region.rooms[13].exits = "southeast|northup"
      region.rooms[13].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly cs;sd;sd;sd;sd;sw"
      region.rooms[14].name = "法王寺"
      region.rooms[14].zone = "嵩山"
      region.rooms[14].id = 1397
      region.rooms[14].links = {}
        region.rooms[14].links.nu = {}
          region.rooms[14].links.nu.to = 1399
          region.rooms[14].links.nu.con = ""
        region.rooms[14].links.ne = {}
          region.rooms[14].links.ne.to = 1400
          region.rooms[14].links.ne.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 1398
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.sd = {}
          region.rooms[14].links.sd.to = 1396
          region.rooms[14].links.sd.con = ""
      region.rooms[14].exits = "northup|southdown|northeast|west"
      region.rooms[14].desc = "    法王寺在嵩山玉柱峰下，隐约于茂密松林中，此地素有 \"嵩山第一胜地\" 之称。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly cs;sd;sd;sd;sd;sw;w"
      region.rooms[15].name = "月台"
      region.rooms[15].zone = "嵩山"
      region.rooms[15].id = 1398
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 1397
          region.rooms[15].links.e.con = ""
      region.rooms[15].exits = "east"
      region.rooms[15].desc = "    这里是法王寺的月台。从月台东望，太室山峦高耸入云，寺东有双峰插云，中间阙如。因名 \"嵩门\" 。中秋佳节，明月自峰中升起，正当嵩门之中，银光洒满山谷，这就是登封八景之一的 \"嵩门待月\" 。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly cs;sd;sd;sd;sd;sw;nu"
      region.rooms[16].name = "塔院"
      region.rooms[16].zone = "嵩山"
      region.rooms[16].id = 1399
      region.rooms[16].links = {}
        region.rooms[16].links.sd = {}
          region.rooms[16].links.sd.to = 1397
          region.rooms[16].links.sd.con = ""
      region.rooms[16].exits = "southdown"
      region.rooms[16].desc = "    法王寺北山坡上，是法王寺塔院。院内有十五层密檐方塔，高近二十丈，造型优美。院内其它三座单檐墓塔，亦玲珑秀丽。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly cs;sd;sd;sd;sd"
      region.rooms[17].name = "山道"
      region.rooms[17].zone = "嵩山"
      region.rooms[17].id = 1400
      region.rooms[17].links = {}
        region.rooms[17].links.nu = {}
          region.rooms[17].links.nu.to = 1401
          region.rooms[17].links.nu.con = ""
        region.rooms[17].links.sw = {}
          region.rooms[17].links.sw.to = 1397
          region.rooms[17].links.sw.con = ""
        region.rooms[17].links.sd = {}
          region.rooms[17].links.sd.to = 1406
          region.rooms[17].links.sd.con = ""
      region.rooms[17].exits = "northup|southdown|southwest"
      region.rooms[17].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly cs;sd;sd;sd"
      region.rooms[18].name = "朝天门"
      region.rooms[18].zone = "嵩山"
      region.rooms[18].id = 1401
      region.rooms[18].links = {}
        region.rooms[18].links.sd = {}
          region.rooms[18].links.sd.to = 1400
          region.rooms[18].links.sd.con = ""
        region.rooms[18].links.nu = {}
          region.rooms[18].links.nu.to = 1402
          region.rooms[18].links.nu.con = ""
      region.rooms[18].exits = "northup|southdown"
      region.rooms[18].desc = "    陡见双峰中断，天然出现一个门户，疾风从断绝处吹出，云雾随风扑面而至，这里就是朝天门了。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly cs;sd;sd"
      region.rooms[19].name = "山道"
      region.rooms[19].zone = "嵩山"
      region.rooms[19].id = 1402
      region.rooms[19].links = {}
        region.rooms[19].links.sd = {}
          region.rooms[19].links.sd.to = 1401
          region.rooms[19].links.sd.con = ""
        region.rooms[19].links.nu = {}
          region.rooms[19].links.nu.to = 1403
          region.rooms[19].links.nu.con = ""
      region.rooms[19].exits = "northup|southdown"
      region.rooms[19].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。上面就是嵩山峻极禅院。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly cs;sd"
      region.rooms[20].name = "峻极禅院山门"
      region.rooms[20].zone = "嵩山"
      region.rooms[20].id = 1403
      region.rooms[20].links = {}
        region.rooms[20].links.nu = {}
          region.rooms[20].links.nu.to = 1404
          region.rooms[20].links.nu.con = ""
        region.rooms[20].links.sd = {}
          region.rooms[20].links.sd.to = 1402
          region.rooms[20].links.sd.con = ""
        region.rooms[20].links.wu = {}
          region.rooms[20].links.wu.to = 1405
          region.rooms[20].links.wu.con = ""
      region.rooms[20].exits = "westup|northup|southdown"
      region.rooms[20].desc = "    嵩山绝顶，古称 \"峻极\" 。这里是本是佛教大寺，但百年来却已成为嵩山派掌门人的住所。西上可以到达封禅台。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly cs"
      region.rooms[21].name = "峻极禅院"
      region.rooms[21].zone = "嵩山"
      region.rooms[21].id = 1404
      region.rooms[21].links = {}
        region.rooms[21].links.sd = {}
          region.rooms[21].links.sd.to = 1403
          region.rooms[21].links.sd.con = ""
      region.rooms[21].exits = "southdown"
      region.rooms[21].desc = "    峻极禅院处嵩山绝顶，院中古柏森森，殿上并无佛像。院宇辽阔，可容千人。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly cs;sd;wu"
      region.rooms[22].name = "封禅台"
      region.rooms[22].zone = "嵩山"
      region.rooms[22].id = 1405
      region.rooms[22].links = {}
        region.rooms[22].links.ed = {}
          region.rooms[22].links.ed.to = 1403
          region.rooms[22].links.ed.con = ""
      region.rooms[22].exits = "eastdown"
      region.rooms[22].desc = "    峻极封禅台由大麻石所建，每块大石都凿得极是平整。地势甚为宽阔。这里独立天心，万峰在下，云开日朗，纤翳不生。极目北望，可遥见成皋玉门，黄河有如一线，西向隐隐见到洛阳伊阙，东南都是叠叠重山。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly cs;sd;sd;sd;sd;sd"
      region.rooms[23].name = "铁梁峡"
      region.rooms[23].zone = "嵩山"
      region.rooms[23].id = 1406
      region.rooms[23].links = {}
        region.rooms[23].links.nu = {}
          region.rooms[23].links.nu.to = 1400
          region.rooms[23].links.nu.con = ""
        region.rooms[23].links.d = {}
          region.rooms[23].links.d.to = 1407
          region.rooms[23].links.d.con = ""
      region.rooms[23].exits = "northup|down"
      region.rooms[23].desc = "    由此上山，山路越发险竣。铁梁峡右侧尽是怪石，而左边则为万仞深谷，渺不见底。隔着峡谷，青冈峰环抱青冈坪，向上是主峰的山路。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly cs;sd;sd;sd;sd;sd;d"
      region.rooms[24].name = "芦岩瀑布"
      region.rooms[24].zone = "嵩山"
      region.rooms[24].id = 1407
      region.rooms[24].links = {}
        region.rooms[24].links.u = {}
          region.rooms[24].links.u.to = 1406
          region.rooms[24].links.u.con = ""
        region.rooms[24].links.sw = {}
          region.rooms[24].links.sw.to = 1388
          region.rooms[24].links.sw.con = ""
      region.rooms[24].exits = "up|southwest"
      region.rooms[24].desc = "    忽听水声如雷，峭壁上两条玉龙直挂下来，双瀑并泄，屈曲回旋，飞跃奔逸，水花映日，淡淡冕生。    瀑布一侧有一小小芦岩寺，瀑布斜过就是胜观峰。瀑布之侧有路可上。"
  region.center = 1404

return region
