local region = {}
  region.cmd = "fly fs"
  region.name = "佛山"
  region.id = "fs"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly fs;n;e;e;e;e;e;ne;ne;ne"
      region.rooms[1].name = "林间道"
      region.rooms[1].zone = "泉州|佛山"
      region.rooms[1].id = 401
      region.rooms[1].desc = "    这里是一条林间小道，在树丛中蜿蜒。东面就是泉州城的西门吊桥，向西南可达岭南广东。"
      region.rooms[1].exits = "east|southwest"
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 400
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.sw = {}
          region.rooms[1].links.sw.to = 402
          region.rooms[1].links.sw.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly fs;n;e;e;e;e;e;ne;ne"
      region.rooms[2].name = "林间道"
      region.rooms[2].zone = "佛山"
      region.rooms[2].id = 402
      region.rooms[2].desc = "    这里是一条林间小道，在树丛中蜿蜒。进入福建省境了，闽西山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[2].exits = "northeast|southwest"
      region.rooms[2].links = {}
        region.rooms[2].links.ne = {}
          region.rooms[2].links.ne.to = 401
          region.rooms[2].links.ne.con = ""
        region.rooms[2].links.sw = {}
          region.rooms[2].links.sw.to = 403
          region.rooms[2].links.sw.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly fs;n;e;e;e;e;e;ne"
      region.rooms[3].name = "林间道"
      region.rooms[3].zone = "佛山"
      region.rooms[3].id = 403
      region.rooms[3].desc = "    这里是一条林间小道，在树丛中蜿蜒。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[3].exits = "northeast|southwest"
      region.rooms[3].links = {}
        region.rooms[3].links.ne = {}
          region.rooms[3].links.ne.to = 402
          region.rooms[3].links.ne.con = ""
        region.rooms[3].links.sw = {}
          region.rooms[3].links.sw.to = 404
          region.rooms[3].links.sw.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly fs;n;e;e;e;e;e"
      region.rooms[4].name = "林间道"
      region.rooms[4].zone = "佛山"
      region.rooms[4].id = 404
      region.rooms[4].desc = "    这里是一条林间小道，在树丛中蜿蜒。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[4].exits = "southeast|northeast|west"
      region.rooms[4].links = {}
        region.rooms[4].links.ne = {}
          region.rooms[4].links.ne.to = 403
          region.rooms[4].links.ne.con = ""
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 406
          region.rooms[4].links.w.con = ""
        region.rooms[4].links.se = {}
          region.rooms[4].links.se.to = 405
          region.rooms[4].links.se.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly fs;n;e;e;e;e;e;se"
      region.rooms[5].name = "林间道"
      region.rooms[5].zone = "佛山"
      region.rooms[5].id = 405
      region.rooms[5].desc = "    这里是一条林间小道，在树丛中蜿蜒。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[5].exits = "northwest"
      region.rooms[5].links = {}
        region.rooms[5].links.nw = {}
          region.rooms[5].links.nw.to = 404
          region.rooms[5].links.nw.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly fs;n;e;e;e;e"
      region.rooms[6].name = "林间道"
      region.rooms[6].zone = "佛山"
      region.rooms[6].id = 406
      region.rooms[6].desc = "    这里是一条林间小道，在树丛中蜿蜒。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[6].exits = "east|west"
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 404
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 407
          region.rooms[6].links.w.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly fs;n;e;e;e"
      region.rooms[7].name = "林间道"
      region.rooms[7].zone = "佛山"
      region.rooms[7].id = 407
      region.rooms[7].desc = "    这里是一条林间小道，在树丛中蜿蜒。西面是岭南重镇佛山，东边通向福建泉州。"
      region.rooms[7].exits = "east|west"
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 406
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 408
          region.rooms[7].links.w.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly fs;n;e;e"
      region.rooms[8].name = "佛山东门"
      region.rooms[8].zone = "佛山"
      region.rooms[8].id = 408
      region.rooms[8].desc = "    这里是佛山镇的东门。再往东走就要离开佛山，去往福建了。西面一条东西向的大街是佛山镇的主要街道。"
      region.rooms[8].exits = "east|west"
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 407
          region.rooms[8].links.e.con = ""
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 409
          region.rooms[8].links.w.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly fs;n;e"
      region.rooms[9].name = "佛山镇街"
      region.rooms[9].zone = "佛山"
      region.rooms[9].id = 409
      region.rooms[9].desc = "    佛山镇街东西相连。东边是镇东门，南面一堵高墙，墙后便是凤天南开的“英雄典当”。"
      region.rooms[9].exits = "south|north|east|west"
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 408
          region.rooms[9].links.e.con = ""
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 411
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 412
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 410
          region.rooms[9].links.n.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly fs;n;e;n"
      region.rooms[10].name = "南海凤第"
      region.rooms[10].zone = "佛山"
      region.rooms[10].id = 410
      region.rooms[10].desc = "    只见一座白墙黑瓦的大宅第，门上悬着一面大匾，写着“南海凤第”四个大字。那宅第一连五进，气象宏伟。"
      region.rooms[10].exits = "south"
      region.rooms[10].links = {}
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 409
          region.rooms[10].links.s.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly fs;n;e;s"
      region.rooms[11].name = "英雄典当"
      region.rooms[11].zone = "佛山"
      region.rooms[11].id = 411
      region.rooms[11].desc = "    当铺里一张高高的柜台，柜台后面坐着当铺的朝奉。这家当铺是凤老爷所开，十多年来从没人来闹过事，朝奉也就很放心。柜台上挂着一个木牌子(paizi)。"
      region.rooms[11].exits = "north"
      region.rooms[11].links = {}
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 409
          region.rooms[11].links.n.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly fs;n"
      region.rooms[12].name = "佛山镇街"
      region.rooms[12].zone = "佛山"
      region.rooms[12].id = 412
      region.rooms[12].desc = "    凤家在佛山是首屈一指的大户，凤家的家丁常牵着狼狗鱼肉乡里。一般的百姓只好忍辱偷生。一条大街横亘东西。路南一家三开间门面的大酒楼，招牌上写着“英雄楼”三个金漆大字，两边敞着窗户，酒楼里刀杓乱响，酒肉香气阵阵喷出。路北有家烧饼油条铺，里面传出阵阵油烟香气。"
      region.rooms[12].exits = "south|east|north|west"
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 409
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 414
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 417
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 413
          region.rooms[12].links.n.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly fs;n;n"
      region.rooms[13].name = "烧饼油条铺"
      region.rooms[13].zone = "佛山"
      region.rooms[13].id = 413
      region.rooms[13].desc = "    这家烧饼油条铺是新开张的。铺面不大，正中央摆了一个大炸锅和一个烤炉。"
      region.rooms[13].exits = "south"
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 412
          region.rooms[13].links.s.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly fs"
      region.rooms[14].name = "英雄楼"
      region.rooms[14].zone = "佛山"
      region.rooms[14].id = 414
      region.rooms[14].desc = "    酒楼里桌椅洁净。座中客人衣饰豪奢，十九是富商大贾。佛山地处交通要地，来这吃饭的人还真不少。"
      region.rooms[14].exits = "up|south|north"
      region.rooms[14].links = {}
        region.rooms[14].links.u = {}
          region.rooms[14].links.u.to = 416
          region.rooms[14].links.u.con = ""
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 415
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 412
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly fs;s"
      region.rooms[15].name = "马厩"
      region.rooms[15].zone = "佛山"
      region.rooms[15].id = 415
      region.rooms[15].desc = "    这是佛山镇的马厩，常年供应新鲜草料。这里民风淳朴，马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净，一直伺候到客人上路。马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。    马厩中堆放著几堆草料，正中有一口泔槽。"
      region.rooms[15].exits = "north"
      region.rooms[15].links = {}
        region.rooms[15].links.n = {}
          region.rooms[15].links.n.to = 414
          region.rooms[15].links.n.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly fs;u"
      region.rooms[16].name = "英雄楼"
      region.rooms[16].zone = "佛山"
      region.rooms[16].id = 416
      region.rooms[16].desc = "    酒楼里桌椅洁净。座中客人衣饰豪奢，十九是富商大贾。这里可以俯瞰佛山镇全景。"
      region.rooms[16].exits = "down"
      region.rooms[16].links = {}
        region.rooms[16].links.d = {}
          region.rooms[16].links.d.to = 414
          region.rooms[16].links.d.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly fs;n;w"
      region.rooms[17].name = "佛山镇街"
      region.rooms[17].zone = "佛山"
      region.rooms[17].id = 417
      region.rooms[17].desc = "    佛山自古与朱仙、景德、汉口并称天下四大镇，端的是民丰物阜，市廛繁华。一条大街横亘东西。南边是南门，通往南海。北边出北门跨南岭可达中原。"
      region.rooms[17].exits = "south|east|north|west"
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 412
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 418
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 425
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 424
          region.rooms[17].links.n.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly fs;n;w;s"
      region.rooms[18].name = "佛山南门"
      region.rooms[18].zone = "佛山"
      region.rooms[18].id = 418
      region.rooms[18].desc = "    这里是佛山镇的南门。出南门向南，就到达南海之滨了。北面一条东西向的大街是佛山镇的主要街道。"
      region.rooms[18].exits = "south|north"
      region.rooms[18].links = {}
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 419
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 417
          region.rooms[18].links.n.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly fs;n;w;s;s"
      region.rooms[19].name = "平原小路"
      region.rooms[19].zone = "佛山"
      region.rooms[19].id = 419
      region.rooms[19].desc = "    你走在珠江三角洲的平原小路上。此处向称鱼米之乡，有花果之都美誉，物产丰饶，民风淳朴。"
      region.rooms[19].exits = "south|north"
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 420
          region.rooms[19].links.s.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 418
          region.rooms[19].links.n.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly fs;n;w;s;s;s"
      region.rooms[20].name = "南海渔村"
      region.rooms[20].zone = "佛山"
      region.rooms[20].id = 420
      region.rooms[20].desc = "    这是南海沿岸的偏僻小村，稀稀落落的几户人家。空地上晾着几顶渔网。南面就是波涛浩淼的南海了。向西走好象还有个渔港。东面是小村的沙滩晒网场。"
      region.rooms[20].exits = "east|north|west"
      region.rooms[20].links = {}
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 421
          region.rooms[20].links.e.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 423
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 419
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly fs;n;w;s;s;s;e"
      region.rooms[21].name = "渔村晒网场"
      region.rooms[21].zone = "佛山"
      region.rooms[21].id = 421
      region.rooms[21].desc = "    小村不大，却有个好大的晒网场。几个小孩在场中无忧地玩耍，声音喧闹。靠南海边上，有个渔夫面向大海，悠然垂钓。"
      region.rooms[21].exits = "north|west"
      region.rooms[21].links = {}
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 420
          region.rooms[21].links.w.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 422
          region.rooms[21].links.n.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly fs;n;w;s;s;s;e;n"
      region.rooms[22].name = "渔村小屋"
      region.rooms[22].zone = "佛山"
      region.rooms[22].id = 422
      region.rooms[22].desc = "    小村的渔民小屋十分简陋，几乎没什么家当，壁上挂满了早用旧了的渔具。大概大人都出海了，只有一个小孩在屋里，看到你进来一脸惊惶。"
      region.rooms[22].exits = "south"
      region.rooms[22].links = {}
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 421
          region.rooms[22].links.s.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly fs;n;w;s;s;s;w"
      region.rooms[23].name = "渔港"
      region.rooms[23].zone = "佛山"
      region.rooms[23].id = 423
      region.rooms[23].desc = "    这里是个小小渔港。南面海面漂浮着几艘小船，抬眼望，海天相连，无边无际。海鸥掠过浪尖，悠悠翩然。"
      region.rooms[23].exits = "east"
      region.rooms[23].links = {}
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 420
          region.rooms[23].links.e.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly fs;n;w;n"
      region.rooms[24].name = "佛山北门"
      region.rooms[24].zone = "佛山"
      region.rooms[24].id = 424
      region.rooms[24].desc = "    这里是佛山镇的北门。出北门向北，翻过南岭可达中原。南面一条东西向的大街是佛山镇的主要街道。"
      region.rooms[24].exits = "south|north"
      region.rooms[24].links = {}
        region.rooms[24].links.s = {}
          region.rooms[24].links.s.to = 417
          region.rooms[24].links.s.con = ""
        region.rooms[24].links.n = {}
          region.rooms[24].links.n.to = 439
          region.rooms[24].links.n.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly fs;n;w;w"
      region.rooms[25].name = "佛山镇街"
      region.rooms[25].zone = "佛山"
      region.rooms[25].id = 425
      region.rooms[25].desc = "    佛山镇街道横亘东西。南边有一座破败的庙宇，里面是一家赌场，大门上写着“英雄会馆”四个大字。"
      region.rooms[25].exits = "south|east|west"
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 417
          region.rooms[25].links.e.con = ""
        region.rooms[25].links.s = {}
          region.rooms[25].links.s.to = 426
          region.rooms[25].links.s.con = ""
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 427
          region.rooms[25].links.w.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly fs;n;w;w;s"
      region.rooms[26].name = "英雄会馆"
      region.rooms[26].zone = "佛山"
      region.rooms[26].id = 426
      region.rooms[26].desc = "    英雄会馆也是凤老爷的家业。来这里赌钱的，都是有能耐有来头的。赌场里围着黑压压的一群人，正在掷(gamble)骰子押大小。门边立着一个牌子(paizi)。"
      region.rooms[26].exits = "north"
      region.rooms[26].links = {}
        region.rooms[26].links.n = {}
          region.rooms[26].links.n.to = 425
          region.rooms[26].links.n.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly fs;n;w;w;w"
      region.rooms[27].name = "佛山镇街"
      region.rooms[27].zone = "佛山"
      region.rooms[27].id = 427
      region.rooms[27].desc = "    佛山镇街道平整。西面是镇西门，北面有一座北帝庙，建构宏伟，好大一座神祠。"
      region.rooms[27].exits = "east|north|west"
      region.rooms[27].links = {}
        region.rooms[27].links.e = {}
          region.rooms[27].links.e.to = 425
          region.rooms[27].links.e.con = ""
        region.rooms[27].links.w = {}
          region.rooms[27].links.w.to = 429
          region.rooms[27].links.w.con = ""
        region.rooms[27].links.n = {}
          region.rooms[27].links.n.to = 428
          region.rooms[27].links.n.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly fs;n;w;w;w;n"
      region.rooms[28].name = "北帝庙"
      region.rooms[28].zone = "佛山"
      region.rooms[28].id = 428
      region.rooms[28].desc = "    北帝庙坐北朝南。院子中一个大水塘，塘中石龟石蛇，昂然盘踞。大殿神像石板上血迹殷然。北帝神像立于大殿正中。"
      region.rooms[28].exits = "south"
      region.rooms[28].links = {}
        region.rooms[28].links.s = {}
          region.rooms[28].links.s.to = 427
          region.rooms[28].links.s.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly fs;n;w;w;w;w"
      region.rooms[29].name = "佛山西门"
      region.rooms[29].zone = "佛山"
      region.rooms[29].id = 429
      region.rooms[29].desc = "    这里是佛山镇的西门。岭南以西经由广西可至大理。东面一条东西向的大街是佛山镇的主要街道。"
      region.rooms[29].exits = "east|west"
      region.rooms[29].links = {}
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 427
          region.rooms[29].links.e.con = ""
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 430
          region.rooms[29].links.w.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly fs;n;w;w;w;w;w"
      region.rooms[30].name = "林间道"
      region.rooms[30].zone = "佛山"
      region.rooms[30].id = 430
      region.rooms[30].desc = "    这里是一条林间小道，在树丛中蜿蜒。东面是岭南重镇佛山，西边通向广西。"
      region.rooms[30].exits = "east|west"
      region.rooms[30].links = {}
        region.rooms[30].links.e = {}
          region.rooms[30].links.e.to = 429
          region.rooms[30].links.e.con = ""
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 431
          region.rooms[30].links.w.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly fs;n;w;w;w;w;w;w"
      region.rooms[31].name = "林间道"
      region.rooms[31].zone = "佛山"
      region.rooms[31].id = 431
      region.rooms[31].desc = "    这里是一条林间小道，在树丛中蜿蜒。这里是广西了。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[31].exits = "east|west"
      region.rooms[31].links = {}
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 430
          region.rooms[31].links.e.con = ""
        region.rooms[31].links.w = {}
          region.rooms[31].links.w.to = 432
          region.rooms[31].links.w.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly fs;n;w;w;w;w;w;w;w"
      region.rooms[32].name = "林间道"
      region.rooms[32].zone = "佛山"
      region.rooms[32].id = 432
      region.rooms[32].desc = "    这里是一条林间小道，在树丛中蜿蜒。这里是广西了。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[32].exits = "northwest|east"
      region.rooms[32].links = {}
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 431
          region.rooms[32].links.e.con = ""
        region.rooms[32].links.nw = {}
          region.rooms[32].links.nw.to = 433
          region.rooms[32].links.nw.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly fs;n;w;w;w;w;w;w;w;nw"
      region.rooms[33].name = "林间道"
      region.rooms[33].zone = "佛山"
      region.rooms[33].id = 433
      region.rooms[33].desc = "    这里是一条林间小道，在树丛中蜿蜒。这里是广西了。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[33].exits = "southeast|southwest"
      region.rooms[33].links = {}
        region.rooms[33].links.se = {}
          region.rooms[33].links.se.to = 432
          region.rooms[33].links.se.con = ""
        region.rooms[33].links.sw = {}
          region.rooms[33].links.sw.to = 434
          region.rooms[33].links.sw.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly fs;n;w;w;w;w;w;w;w;nw;sw"
      region.rooms[34].name = "林间道"
      region.rooms[34].zone = "佛山"
      region.rooms[34].id = 434
      region.rooms[34].desc = "    这里是一条林间小道，在树丛中蜿蜒。这里是广西了。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[34].exits = "northeast|west"
      region.rooms[34].links = {}
        region.rooms[34].links.ne = {}
          region.rooms[34].links.ne.to = 433
          region.rooms[34].links.ne.con = ""
        region.rooms[34].links.w = {}
          region.rooms[34].links.w.to = 435
          region.rooms[34].links.w.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly fs;n;w;w;w;w;w;w;w;nw;sw;w"
      region.rooms[35].name = "林间道"
      region.rooms[35].zone = "佛山"
      region.rooms[35].id = 435
      region.rooms[35].desc = "    这里是一条林间小道，在树丛中蜿蜒。这里是广西了。岭南山林茂密，多产毒虫，各位行路要十分小心。"
      region.rooms[35].exits = "east|west"
      region.rooms[35].links = {}
        region.rooms[35].links.e = {}
          region.rooms[35].links.e.to = 434
          region.rooms[35].links.e.con = ""
        region.rooms[35].links.w = {}
          region.rooms[35].links.w.to = 436
          region.rooms[35].links.w.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly fs;n;w;w;w;w;w;w;w;nw;sw;w;w"
      region.rooms[36].name = "林间道"
      region.rooms[36].zone = "佛山"
      region.rooms[36].id = 436
      region.rooms[36].desc = "    这里是一条林间小道，在树丛中蜿蜒。这里向东是广西。向西北走就是大理国的地界了。"
      region.rooms[36].exits = "east|northwest"
      region.rooms[36].links = {}
        region.rooms[36].links.e = {}
          region.rooms[36].links.e.to = 435
          region.rooms[36].links.e.con = ""
        region.rooms[36].links.nw = {}
          region.rooms[36].links.nw.to = 437
          region.rooms[36].links.nw.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly fs;n;w;w;w;w;w;w;w;nw;sw;w;w;nw"
      region.rooms[37].name = "黄土路"
      region.rooms[37].zone = "佛山"
      region.rooms[37].id = 437
      region.rooms[37].desc = "    这里是大理境内，你走在一条黄土大路上，行人多是本地的摆夷族人。也间或有些中原打扮的人事走动，此路北面通向官道，向西北有路通往大理城的南门，东行可达广东佛山。"
      region.rooms[37].exits = "northwest|southeast"
      region.rooms[37].links = {}
        region.rooms[37].links.nw = {}
          region.rooms[37].links.nw.to = 438
          region.rooms[37].links.nw.con = ""
        region.rooms[37].links.se = {}
          region.rooms[37].links.se.to = 436
          region.rooms[37].links.se.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly fs;n;w;w;w;w;w;w;w;nw;sw;w;w;nw;nw"
      region.rooms[38].name = "双鹤桥"
      region.rooms[38].zone = "佛山|大理"
      region.rooms[38].id = 438
      region.rooms[38].links = {}
        region.rooms[38].links.n = {}
          region.rooms[38].links.n.to = 488
          region.rooms[38].links.n.con = ""
        region.rooms[38].links.w = {}
          region.rooms[38].links.w.to = 487
          region.rooms[38].links.w.con = ""
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 463
          region.rooms[38].links.s.con = ""
        region.rooms[38].links.se = {}
          region.rooms[38].links.se.to = 437
          region.rooms[38].links.se.con = ""
      region.rooms[38].exits = "south|north|southeast|west"
      region.rooms[38].desc = "    这是一个岔路口，北边是座青石拱桥名叫双鹤桥，此桥跨在绿玉溪上，桥北即是大理城，由此南去是通往南方的喜州、龙口等城镇的官道，东去的岔路通往广西，沿绿玉溪南岸西行可达五华楼。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly fs;n;w;n;n"
      region.rooms[39].name = "南岭山口"
      region.rooms[39].zone = "佛山|衡阳"
      region.rooms[39].id = 439
      region.rooms[39].desc = "    这里是南岭的一个山口。南面就是佛山了，北面是横亘湖南广东的五岭。这里地气炎热，百物速生快长，口音也远异中原了。"
      region.rooms[39].exits = "south|northup"
      region.rooms[39].links = {}
        region.rooms[39].links.s = {}
          region.rooms[39].links.s.to = 424
          region.rooms[39].links.s.con = ""
        region.rooms[39].links.nu = {}
          region.rooms[39].links.nu.to = 440
          region.rooms[39].links.nu.con = ""
  region.center = 414
return region