local region = {}
  region.cmd = "fly wm;e;s;s;s;s;s;e;e;e;e;se"
  region.name = "归云庄1"
  region.id = "gyz1"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;nw"
      region.rooms[1].name = "密林"
      region.rooms[1].zone = "扬州|归云庄1"
      region.rooms[1].id = 63
      region.rooms[1].links = {}
        region.rooms[1].links.se = {}
          region.rooms[1].links.se.to = 2618
          region.rooms[1].links.se.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 62
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 80
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "north|southeast|west"
      region.rooms[1].desc = "    扬州郊外的茂密树林，阴森可怖。抬头不见天日。这里也是扬州命案发生最多的地方。鸟兽蛇虫游荡不穷。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;w;sw;w;nw"
      region.rooms[2].name = "青石大道"
      region.rooms[2].zone = "扬州|武当山|归云庄1"
      region.rooms[2].id = 65
      region.rooms[2].links = {}
        region.rooms[2].links.se = {}
          region.rooms[2].links.se.to = 2626
          region.rooms[2].links.se.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 66
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 64
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "south|north|southeast"
      region.rooms[2].desc = "    你走在一条青石大道上，北边隐约可见到扬州城的城墙。此处往东南望去，可以看到一个市镇。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;se;e;s;ne"
      region.rooms[3].name = "山路"
      region.rooms[3].zone = "苏州|归云庄1"
      region.rooms[3].id = 159
      region.rooms[3].links = {}
        region.rooms[3].links.sw = {}
          region.rooms[3].links.sw.to = 2622
          region.rooms[3].links.sw.con = ""
        region.rooms[3].links.se = {}
          region.rooms[3].links.se.to = 146
          region.rooms[3].links.se.con = ""
      region.rooms[3].exits = "southeast|southwest"
      region.rooms[3].desc = "    这里是一片农田。不远处有一些村庄，炊烟袅袅升起。村庄周围是一块块的田地，田里有一些正在耕作的农人。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se"
      region.rooms[4].name = "树林"
      region.rooms[4].zone = "归云庄1"
      region.rooms[4].id = 2618
      region.rooms[4].links = {}
        region.rooms[4].links.nw = {}
          region.rooms[4].links.nw.to = 63
          region.rooms[4].links.nw.con = ""
        region.rooms[4].links.se = {}
          region.rooms[4].links.se.to = 2619
          region.rooms[4].links.se.con = ""
      region.rooms[4].exits = "northwest|southeast"
      region.rooms[4].desc = "    树林里光线暗淡，只能听见头顶上传来一些鸟儿的啼鸣。偶而从茂密的叶间透过的一线光伴着落叶在飞舞。朽木腐烂的气味和身後传来野兽的啸声使人不觉犹豫了前进的脚步。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se"
      region.rooms[5].name = "树林"
      region.rooms[5].zone = "归云庄1"
      region.rooms[5].id = 2619
      region.rooms[5].links = {}
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 2624
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.nw = {}
          region.rooms[5].links.nw.to = 2618
          region.rooms[5].links.nw.con = ""
        region.rooms[5].links.se = {}
          region.rooms[5].links.se.to = 2620
          region.rooms[5].links.se.con = ""
      region.rooms[5].exits = "northwest|southeast|west"
      region.rooms[5].desc = "    树林里光线暗淡，只能听见头顶上传来一些鸟儿的啼鸣。偶而从茂密的叶间透过的一线光伴着落叶在飞舞。朽木腐烂的气味和身後传来野兽的啸声使人不觉犹豫了前进的脚步。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;se"
      region.rooms[6].name = "树林"
      region.rooms[6].zone = "归云庄1"
      region.rooms[6].id = 2620
      region.rooms[6].links = {}
        region.rooms[6].links.nw = {}
          region.rooms[6].links.nw.to = 2619
          region.rooms[6].links.nw.con = ""
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 2621
          region.rooms[6].links.e.con = ""
      region.rooms[6].exits = "northwest|east"
      region.rooms[6].desc = "    树林里光线暗淡，只能听见头顶上传来一些鸟儿的啼鸣。偶而从茂密的叶间透过的一线光伴着落叶在飞舞。朽木腐烂的气味和身後传来野兽的啸声使人不觉犹豫了前进的脚步。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;se;e"
      region.rooms[7].name = "树林"
      region.rooms[7].zone = "归云庄1"
      region.rooms[7].id = 2621
      region.rooms[7].links = {}
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 2620
          region.rooms[7].links.w.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 2622
          region.rooms[7].links.s.con = ""
      region.rooms[7].exits = "south|west"
      region.rooms[7].desc = "    树林里光线暗淡，只能听见头顶上传来一些鸟儿的啼鸣。偶而从茂密的叶间透过的一线光伴着落叶在飞舞。朽木腐烂的气味和身後传来野兽的啸声使人不觉犹豫了前进的脚步。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;se;e;s"
      region.rooms[8].name = "山路"
      region.rooms[8].zone = "归云庄1"
      region.rooms[8].id = 2622
      region.rooms[8].links = {}
        region.rooms[8].links.ne = {}
          region.rooms[8].links.ne.to = 159
          region.rooms[8].links.ne.con = ""
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 2623
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 2621
          region.rooms[8].links.n.con = ""
      region.rooms[8].exits = "south|north|northeast"
      region.rooms[8].desc = "    这里是一片农田。不远处有一些村庄，炊烟袅袅升起。村庄周围是一块块的田地，田里有一些正在耕作的农人。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;se;e;s;s"
      region.rooms[9].name = "太湖"
      region.rooms[9].zone = "归云庄1"
      region.rooms[9].id = 2623
      region.rooms[9].links = {}
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 2622
          region.rooms[9].links.n.con = ""
      region.rooms[9].exits = "north"
      region.rooms[9].desc = "    太湖古称五湖，襟带三州，周行五百里，东南之水皆归于此。其时但见长天无波，放眼皆碧，七十二峰苍翠挺立于三万六千顷波涛之中，不觉令人心怀大畅。由此登船可前往太湖之中的归云庄。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;w"
      region.rooms[10].name = "树林"
      region.rooms[10].zone = "归云庄1"
      region.rooms[10].id = 2624
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 2619
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.sw = {}
          region.rooms[10].links.sw.to = 2625
          region.rooms[10].links.sw.con = ""
      region.rooms[10].exits = "east|southwest"
      region.rooms[10].desc = "    树林里光线暗淡，只能听见头顶上传来一些鸟儿的啼鸣。偶而从茂密的叶间透过的一线光伴着落叶在飞舞。朽木腐烂的气味和身後传来野兽的啸声使人不觉犹豫了前进的脚步。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;w;sw"
      region.rooms[11].name = "田地"
      region.rooms[11].zone = "归云庄1"
      region.rooms[11].id = 2625
      region.rooms[11].links = {}
        region.rooms[11].links.ne = {}
          region.rooms[11].links.ne.to = 2624
          region.rooms[11].links.ne.con = ""
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 2626
          region.rooms[11].links.w.con = ""
      region.rooms[11].exits = "northeast|west"
      region.rooms[11].desc = "    这里是一片农田。不远处有一些村庄，炊烟袅袅升起。村庄周围是一块块的田地，很有次序的排成一个个井字，田里有一些正在耕作的农人，过路人贪近路也可以从田间井字分割的小径穿过。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;w;sw;w"
      region.rooms[12].name = "宜兴"
      region.rooms[12].zone = "归云庄1"
      region.rooms[12].id = 2626
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 2625
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 2627
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.nw = {}
          region.rooms[12].links.nw.to = 65
          region.rooms[12].links.nw.con = ""
      region.rooms[12].exits = "south|northwest|east"
      region.rooms[12].desc = "    这儿便是天下闻名的陶都，青山绿水之间掩映着一堆堆紫砂陶坯，另有一番景色。向东行，不远处就是太湖边。南方便是湖州府了。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly wm;e;s;s;s;s;s;e;e;e;e;se;se;w;sw;w;s"
      region.rooms[13].name = "南浔镇"
      region.rooms[13].zone = "归云庄1"
      region.rooms[13].id = 2627
      region.rooms[13].links = {}
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 2626
          region.rooms[13].links.n.con = ""
      region.rooms[13].exits = "north"
      region.rooms[13].desc = "    湖州府自来文风甚盛，历代才士辈出，梁时将中国字分为平上去入四声的沈约，元代书画皆臻极品的赵孟兆都是湖州人氏。当地又以产笔著名，湖州之笔，徽州之墨，宣城之纸，肇庆端溪之砚，文房四宝，天下驰名。南浔镇虽是湖州府的一个镇，却比寻常州县还大，镇上富户极多，著名的富室大族之中有一家姓庄。"
  region.center = 2618
return region