local region = {}
  region.cmd = "fly ws1;w;w;w;w;w;s;s;s;s;s;s;se;ne;e;e;eu;su"
  region.name = "华山村1"
  region.id = "hsc1"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly ws1;w;w;w;w;w;s;s;s;s;s;s;se;ne;e;e;eu;su"
      region.rooms[1].name = "中条山密林"
      region.rooms[1].zone = "华山村|华山村1"
      region.rooms[1].id = 2385
      region.rooms[1].desc = "    山路越来越小，周围茂密森林里和脚下的茅草封住了路，上不见天光，后不见归路(road)，你简直绝望了。"
      region.rooms[1].exits = "northdown"
      region.rooms[1].links = {}
        region.rooms[1].links["use fire;zuan"] = {}
          region.rooms[1].links["use fire;zuan"].to = 2698
          region.rooms[1].links["use fire;zuan"].con = "c:fire"
        region.rooms[1].links.nd = {}
          region.rooms[1].links.nd.to = 2384
          region.rooms[1].links.nd.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly ws1;w;w;w;w;w;s;s;s;s;s;s;se;ne;e;e;eu;su;[c:fire]use fire;zuan"
      region.rooms[2].name = "树林外"
      region.rooms[2].zone = "华山村1"
      region.rooms[2].id = 2698
      region.rooms[2].links = {}
        region.rooms[2].links.enter = {}
          region.rooms[2].links.enter.to = 2385
          region.rooms[2].links.enter.con = ""
        region.rooms[2].links.wu = {}
          region.rooms[2].links.wu.to = 2699
          region.rooms[2].links.wu.con = ""
      region.rooms[2].exits = "westup|enter"
      region.rooms[2].desc = "    树林外，赫然站着一个汉子，在阴森森的林子边上，凭添一股煞气。西上是登山的路，东边就进入森林了。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly ws1;w;w;w;w;w;s;s;s;s;s;s;se;ne;e;e;eu;su;[c:fire]use fire;zuan;wu"
      region.rooms[3].name = "峭壁"
      region.rooms[3].zone = "华山村1"
      region.rooms[3].id = 2699
      region.rooms[3].links = {}
        region.rooms[3].links.ed = {}
          region.rooms[3].links.ed.to = 2698
          region.rooms[3].links.ed.con = ""
        region.rooms[3].links.su = {}
          region.rooms[3].links.su.to = 2700
          region.rooms[3].links.su.con = ""
      region.rooms[3].exits = "eastdown|southup"
      region.rooms[3].desc = "    你走在峭壁边的小路上。一侧是密密的丛林，外侧却是极深的陡壁。山风凛冽，几乎要把你刮落崖去。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly ws1;w;w;w;w;w;s;s;s;s;s;s;se;ne;e;e;eu;su;[c:fire]use fire;zuan;wu;su"
      region.rooms[4].name = "山谷"
      region.rooms[4].zone = "华山村1"
      region.rooms[4].id = 2700
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 2701
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.nd = {}
          region.rooms[4].links.nd.to = 2699
          region.rooms[4].links.nd.con = ""
      region.rooms[4].exits = "south|northdown"
      region.rooms[4].desc = "    这里是中条山的一个隐秘山谷。四周是高可及天的山峰，云深林密，一径小溪潺潺流过，溅入坡下塘中。溪畔有一汉子舞剑正酣。不打扰的为妙。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly ws1;w;w;w;w;w;s;s;s;s;s;s;se;ne;e;e;eu;su;[c:fire]use fire;zuan;wu;su;s"
      region.rooms[5].name = "山间平地"
      region.rooms[5].zone = "华山村1"
      region.rooms[5].id = 2701
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 2702
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 2700
          region.rooms[5].links.n.con = ""
      region.rooms[5].exits = "east|north"
      region.rooms[5].desc = "    你走在中条山山间平地上。靠东山壁上有一小屋。传闻当年华山玉女峰剑气两宗大对决，中计败北的剑宗弟子大多隐匿中条山。难道就是这里？林中冷风轻吹门响。很失意的感觉。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly ws1;w;w;w;w;w;s;s;s;s;s;s;se;ne;e;e;eu;su;[c:fire]use fire;zuan;wu;su;s;e"
      region.rooms[6].name = "林间小屋"
      region.rooms[6].zone = "华山村1"
      region.rooms[6].id = 2702
      region.rooms[6].links = {}
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 2701
          region.rooms[6].links.w.con = ""
      region.rooms[6].exits = "west"
      region.rooms[6].desc = "    这里就是华山剑宗的的根本之地。二十五年来，剑宗弟子卧薪尝胆，只是为了夺回华山门派掌门，为此，付出了极大牺牲。    屋里陈设极为简陋。这么多年来一直没有长久隐匿的念头使得剑宗弟子能忍辱负重，只待重开生天。"
  region.center = 2385
return region