local region = {}
  region.cmd = "fly kl"
  region.name = "昆仑山"
  region.id = "kl"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;sd;ed;e;e;se"
      region.rooms[1].name = "昆仑山下"
      region.rooms[1].zone = "明教|昆仑山"
      region.rooms[1].id = 1899
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 1918
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 1898
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.nw = {}
          region.rooms[1].links.nw.to = 1954
          region.rooms[1].links.nw.con = ""
      region.rooms[1].exits = "northwest|east|west"
      region.rooms[1].desc = "    这里是千里昆仑的东麓，远望苍天浩浩，白云悠悠。东方沃野千里，楚天辽阔；西面高山巍巍，迤逦万里。叱咤武林八百年的明教就座落在这群山之中。明教----是多少武林豪杰所向往的地方，在那里，有无数生死相许的好兄弟，无论是正是邪。就在这西方的群山之后，等待着你去谱写又一曲武林传奇。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly kl"
      region.rooms[2].name = "大广场"
      region.rooms[2].zone = "昆仑山"
      region.rooms[2].id = 1927
      region.rooms[2].desc = "    这里是一个平平开阔的大广场，广场上有昆仑派的弟子在习武，前面不远处是个巨大的石屏风，后面就是昆仑派的前厅了，西面和东面仍然是广场。"
      region.rooms[2].exits = "south|east|north|west"
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 1928
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 1929
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 1930
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 1955
          region.rooms[2].links.n.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly kl;e"
      region.rooms[3].name = "广场东"
      region.rooms[3].zone = "昆仑山"
      region.rooms[3].id = 1928
      region.rooms[3].desc = "    这里是一个平平开阔的大广场，广场上有昆仑派的弟子在习武，西面是仍然是广场，东面过去就是悬崖了，南面是下山的路。"
      region.rooms[3].exits = "west|southwest"
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 1927
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.sw = {}
          region.rooms[3].links.sw.to = 1930
          region.rooms[3].links.sw.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly kl;w"
      region.rooms[4].name = "广场西"
      region.rooms[4].zone = "昆仑山"
      region.rooms[4].id = 1929
      region.rooms[4].desc = "    这里是一个平平开阔的大广场，广场上有昆仑派的弟子在习武，东面是仍然是广场，西面过去就是悬崖了，南面是下山的路。"
      region.rooms[4].exits = "east|southeast"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 1927
          region.rooms[4].links.e.con = ""
        region.rooms[4].links.se = {}
          region.rooms[4].links.se.to = 1930
          region.rooms[4].links.se.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly kl;s"
      region.rooms[5].name = "石阶路"
      region.rooms[5].zone = "昆仑山"
      region.rooms[5].id = 1930
      region.rooms[5].desc = "    走过盘山路，就是一段很平整的石阶山路。前面传来刀剑相碰的声音，快到了，你不由得加快了脚步，远远望去，似乎是个大广场，围着不少人在练武。"
      region.rooms[5].exits = "northwest|north|southdown|northeast"
      region.rooms[5].links = {}
        region.rooms[5].links.ne = {}
          region.rooms[5].links.ne.to = 1928
          region.rooms[5].links.ne.con = ""
        region.rooms[5].links.nw = {}
          region.rooms[5].links.nw.to = 1929
          region.rooms[5].links.nw.con = ""
        region.rooms[5].links.sd = {}
          region.rooms[5].links.sd.to = 1931
          region.rooms[5].links.sd.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 1927
          region.rooms[5].links.n.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly kl;s;sd"
      region.rooms[6].name = "盘山路"
      region.rooms[6].zone = "昆仑山"
      region.rooms[6].id = 1931
      region.rooms[6].desc = "    这是一条盘山的路，山间穿来鸟鸣兽叫，路面似乎已很久没有修整了，显得有些破旧，但是从遗留的痕迹依稀可以看出当年的辉煌。南面是山下，北面山上是昆仑派的所在。"
      region.rooms[6].exits = "northup|southdown"
      region.rooms[6].links = {}
        region.rooms[6].links.nu = {}
          region.rooms[6].links.nu.to = 1930
          region.rooms[6].links.nu.con = ""
        region.rooms[6].links.sd = {}
          region.rooms[6].links.sd.to = 1932
          region.rooms[6].links.sd.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly kl;s;sd;sd"
      region.rooms[7].name = "盘山路"
      region.rooms[7].zone = "昆仑山"
      region.rooms[7].id = 1932
      region.rooms[7].desc = "    这是一条盘山的路，路边花草满地，路面似乎很久没有修整了，显得有些破旧，但是从遗留的痕迹依稀可以看出当年的辉煌。南面是山下，北面山上是昆仑派的所在。"
      region.rooms[7].exits = "northup|southdown"
      region.rooms[7].links = {}
        region.rooms[7].links.nu = {}
          region.rooms[7].links.nu.to = 1931
          region.rooms[7].links.nu.con = ""
        region.rooms[7].links.sd = {}
          region.rooms[7].links.sd.to = 1933
          region.rooms[7].links.sd.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly kl;s;sd;sd;sd"
      region.rooms[8].name = "昆仑山路"
      region.rooms[8].zone = "昆仑山"
      region.rooms[8].id = 1933
      region.rooms[8].desc = "    这里已经是昆仑派的地方了，路边花草满地，虽然是寒冬，这里却仍然生机勃勃，到处传来鸟兽的叫声，前面山上就是昆仑派的居所了，下面是来的时候的山门。"
      region.rooms[8].exits = "northup|westdown"
      region.rooms[8].links = {}
        region.rooms[8].links.nu = {}
          region.rooms[8].links.nu.to = 1932
          region.rooms[8].links.nu.con = ""
        region.rooms[8].links.wd = {}
          region.rooms[8].links.wd.to = 1934
          region.rooms[8].links.wd.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly kl;s;sd;sd;sd;wd"
      region.rooms[9].name = "昆仑派山门"
      region.rooms[9].zone = "昆仑山"
      region.rooms[9].id = 1934
      region.rooms[9].desc = "    你一路走来，饱受大风黄沙之苦，渐渐树木多了起来，不时可听见枝叶中传来的鸟鸣，路边草丛偶尔也能发现一些开着的野花。到得这里，已是绿树红花，十分茂盛，你万万没想到深山中却有如此所在，精神大为一振。前面是一座山门，写着“昆仑派”三个大字。"
      region.rooms[9].exits = "eastup|southdown"
      region.rooms[9].links = {}
        region.rooms[9].links.sd = {}
          region.rooms[9].links.sd.to = 1935
          region.rooms[9].links.sd.con = ""
        region.rooms[9].links.eu = {}
          region.rooms[9].links.eu.to = 1933
          region.rooms[9].links.eu.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly kl;s;sd;sd;sd;wd;sd"
      region.rooms[10].name = "昆仑山麓"
      region.rooms[10].zone = "昆仑山"
      region.rooms[10].id = 1935
      region.rooms[10].desc = "    整个昆仑山脉雪山连绵，冰河垂悬。远望昆仑，有如横卧云彩间的银色玉龙。每年春天以后，冰雪融化，汇成了一股股清澈溪流，流入长江，黄河。"
      region.rooms[10].exits = "east|northup"
      region.rooms[10].links = {}
        region.rooms[10].links.nu = {}
          region.rooms[10].links.nu.to = 1934
          region.rooms[10].links.nu.con = ""
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 1936
          region.rooms[10].links.e.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly kl;s;sd;sd;sd;wd;sd;e"
      region.rooms[11].name = "昆仑山垭口"
      region.rooms[11].zone = "昆仑山"
      region.rooms[11].id = 1936
      region.rooms[11].desc = "    这是位于两山之间的一个小山口。只见昆仑山脉绵延千里，群山复叠，山上树木并不多，不时露出光秃秃的山面和石头，山腰以上均为冰雪覆盖，冰峰雄峙，高插云霄。"
      region.rooms[11].exits = "southeast|west"
      region.rooms[11].links = {}
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 1935
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.se = {}
          region.rooms[11].links.se.to = 1937
          region.rooms[11].links.se.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly kl;s;sd;sd;sd;wd;sd;e;se"
      region.rooms[12].name = "可可西里山"
      region.rooms[12].zone = "昆仑山"
      region.rooms[12].id = 1937
      region.rooms[12].desc = "    可可西里山又称可可稀立山，蒙古语为“青山”的意思。西起木孜塔格峰，东接巴颜喀拉山，山势平缓，冻土广布，高处少永久性积雪与冰川。除北侧有淡水湖钦马湖外，其余南北星罗棋布的湖泊均为咸水湖。草木稀疏，人烟极少。"
      region.rooms[12].exits = "north|northwest|east"
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 1939
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.nw = {}
          region.rooms[12].links.nw.to = 1936
          region.rooms[12].links.nw.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 1938
          region.rooms[12].links.n.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;n"
      region.rooms[13].name = "雪地"
      region.rooms[13].zone = "昆仑山"
      region.rooms[13].id = 1938
      region.rooms[13].desc = "    雪地中央有个大雪堆，这大雪堆是农家积柴的草堆。这天寒地冻的隆冬严寒里，尸体不会腐臭，天上有一头兀鹰在空中盘旋了几个圈子，寻找机会以便飞下来啄食。"
      region.rooms[13].exits = "south"
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 1937
          region.rooms[13].links.s.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e"
      region.rooms[14].name = "巴颜喀拉山"
      region.rooms[14].zone = "昆仑山"
      region.rooms[14].id = 1939
      region.rooms[14].desc = "    这巴颜喀拉山山势低平，西接昆仑山垭口，又与通天河支流德曲相隔，沼泽遍布。在山脚放眼望去，随处可见一处处沼泽草甸，乃是放牧各类牲畜的好地方。远处散布着一顶顶牧民的蒙古包。"
      region.rooms[14].exits = "northwest|southdown|west"
      region.rooms[14].links = {}
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 1937
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.nw = {}
          region.rooms[14].links.nw.to = 1940
          region.rooms[14].links.nw.con = ""
        region.rooms[14].links.sd = {}
          region.rooms[14].links.sd.to = 1951
          region.rooms[14].links.sd.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw"
      region.rooms[15].name = "山路"
      region.rooms[15].zone = "昆仑山"
      region.rooms[15].id = 1940
      region.rooms[15].desc = "    这是一条昆仑山上到处可见的山路。只是这里已到处可见梅树，梅花盛开时到处一片火红，花香飘溢。"
      region.rooms[15].exits = "westup|southeast"
      region.rooms[15].links = {}
        region.rooms[15].links.se = {}
          region.rooms[15].links.se.to = 1939
          region.rooms[15].links.se.con = ""
        region.rooms[15].links.wu = {}
          region.rooms[15].links.wu.to = 1941
          region.rooms[15].links.wu.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu"
      region.rooms[16].name = "山路"
      region.rooms[16].zone = "昆仑山"
      region.rooms[16].id = 1941
      region.rooms[16].desc = "    这是一条昆仑山上到处可见的山路。只是这里已到处可见梅树，梅花盛开时到处一片火红，花香飘溢。西边是红梅山庄。"
      region.rooms[16].exits = "westup|eastdown"
      region.rooms[16].links = {}
        region.rooms[16].links.ed = {}
          region.rooms[16].links.ed.to = 1940
          region.rooms[16].links.ed.con = ""
        region.rooms[16].links.wu = {}
          region.rooms[16].links.wu.to = 1942
          region.rooms[16].links.wu.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu"
      region.rooms[17].name = "红梅庄门"
      region.rooms[17].zone = "昆仑山"
      region.rooms[17].id = 1942
      region.rooms[17].desc = "    这是一座颇大的庄子。一眼看去就知道此间主人是当地的富豪，在昆仑山中有这么大的一座山庄确实非常少见。相传，此间主人也是武林中人，所以路过之人也不敢随意的进入，当以江湖之礼求见。"
      region.rooms[17].exits = "north|eastdown|westdown"
      region.rooms[17].links = {}
        region.rooms[17].links.ed = {}
          region.rooms[17].links.ed.to = 1941
          region.rooms[17].links.ed.con = ""
        region.rooms[17].links.wd = {}
          region.rooms[17].links.wd.to = 1947
          region.rooms[17].links.wd.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 1943
          region.rooms[17].links.n.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu;n"
      region.rooms[18].name = "山庄大厅"
      region.rooms[18].zone = "昆仑山"
      region.rooms[18].id = 1943
      region.rooms[18].desc = "    这里是山庄会客之所，大厅之中坐着此间庄主。每逢年节，就有许多仆在此等侯，希望主人能赏一些银子。厅子两旁放置着许多椅子和茶机，是供客人座的。这里虽然远离中原，但来此之客却是当真不少。厅中壁上挂着一大副猛虎之图。这里有几个童仆来回的侍侯着。"
      region.rooms[18].exits = "south|east|north"
      region.rooms[18].links = {}
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 1944
          region.rooms[18].links.e.con = ""
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 1942
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 1946
          region.rooms[18].links.n.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu;n;e"
      region.rooms[19].name = "后院"
      region.rooms[19].zone = "昆仑山"
      region.rooms[19].id = 1944
      region.rooms[19].desc = "    这里是山庄的后院。此庄号称“红梅”，当有应有其根源。院子里就长着许多梅树。每逢春天梅花盛开之时，到处一片火红，分外美丽，梅花飘香更是令人心旷神怡。北边是“灵獒宫”。"
      region.rooms[19].exits = "north|west"
      region.rooms[19].links = {}
        region.rooms[19].links.w = {}
          region.rooms[19].links.w.to = 1943
          region.rooms[19].links.w.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 1945
          region.rooms[19].links.n.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu;n;e;n"
      region.rooms[20].name = "灵獒宫"
      region.rooms[20].zone = "昆仑山"
      region.rooms[20].id = 1945
      region.rooms[20].desc = "    你来到一座大厅之外，只见厅上扁额上写着“灵獒宫”三个血红大字。一进厅，你便吃了一惊，但见三十余头雄健猛恶的大犬，分成三排蹲在地上，一个身穿白孤裘的女郎坐在一张虎皮椅上，她手执皮鞭，正在指挥恶犬咬人。南边是一个大院子。"
      region.rooms[20].exits = "south"
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 1944
          region.rooms[20].links.s.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu;n;n"
      region.rooms[21].name = "暖阁"
      region.rooms[21].zone = "昆仑山"
      region.rooms[21].id = 1946
      region.rooms[21].desc = "    昆仑山中一向极为寒冷，但在此暖阁之中却温暖如春，可又不见何处生着炭火，此间取暖方法当真巧妙无比。阁中陈设辉煌灿烂，榻上椅上都铺着锦缎软垫，极是富丽豪华。南边是大厅。"
      region.rooms[21].exits = "south"
      region.rooms[21].links = {}
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 1943
          region.rooms[21].links.s.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu;wd"
      region.rooms[22].name = "山溪边"
      region.rooms[22].zone = "昆仑山"
      region.rooms[22].id = 1947
      region.rooms[22].desc = "    这里是一条小溪。昆仑山终年积雪，在烈日照射下，部分冰雪融化成水，而汇成小溪，溪水向下而流，不知其流向何方。往西而上是一个大丛林。"
      region.rooms[22].exits = "westup|eastup"
      region.rooms[22].links = {}
        region.rooms[22].links.eu = {}
          region.rooms[22].links.eu.to = 1942
          region.rooms[22].links.eu.con = ""
        region.rooms[22].links.wu = {}
          region.rooms[22].links.wu.to = 1948
          region.rooms[22].links.wu.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu;wd;wu"
      region.rooms[23].name = "雪山丛林"
      region.rooms[23].zone = "昆仑山"
      region.rooms[23].id = 1948
      region.rooms[23].desc = "    这是一个很大的丛林，树木枝叶上挂满了冰雪，雪白的一大片，奇美无比。丛林向山上延伸，直至山顶。在丛林中微露出一条小道，依稀可认，你走在小道上，雪地中留下一行长长的足印。"
      region.rooms[23].exits = "eastdown|northup"
      region.rooms[23].links = {}
        region.rooms[23].links.ed = {}
          region.rooms[23].links.ed.to = 1947
          region.rooms[23].links.ed.con = ""
        region.rooms[23].links.nu = {}
          region.rooms[23].links.nu.to = 1949
          region.rooms[23].links.nu.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu;wd;wu;nu"
      region.rooms[24].name = "雪山丛林"
      region.rooms[24].zone = "昆仑山"
      region.rooms[24].id = 1949
      region.rooms[24].desc = "    这是一个很大的丛林，树木枝叶上挂满了冰雪，雪白的一大片，奇美无比。丛林向山上延伸，直至山顶。在丛林中微露出一条小道，依稀可认，你走在小道上，雪地中留下一行长长的足印。"
      region.rooms[24].exits = "westup|southdown"
      region.rooms[24].links = {}
        region.rooms[24].links.sd = {}
          region.rooms[24].links.sd.to = 1948
          region.rooms[24].links.sd.con = ""
        region.rooms[24].links.wu = {}
          region.rooms[24].links.wu.to = 1950
          region.rooms[24].links.wu.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;nw;wu;wu;wd;wu;nu;wu"
      region.rooms[25].name = "悬崖"
      region.rooms[25].zone = "昆仑山"
      region.rooms[25].id = 1950
      region.rooms[25].desc = "    你来到悬崖之上，突然在对而传来几声狼嗥，甚是凄厉可怖。只见对面几只大灰狼仰起头，向着你张牙舞爪的嗥叫，想是要食之果腹，只是之间有一条深不见底的万丈峡谷，无法过来。"
      region.rooms[25].exits = "eastdown"
      region.rooms[25].links = {}
        region.rooms[25].links.ed = {}
          region.rooms[25].links.ed.to = 1949
          region.rooms[25].links.ed.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;sd"
      region.rooms[26].name = "西域山路"
      region.rooms[26].zone = "昆仑山"
      region.rooms[26].id = 1951
      region.rooms[26].desc = "    渐行渐西，天气一天冷似一天，西域昆仑派势力雄强，沿途倒并无什么强盗，只是黄沙扑面，寒风透骨，却也着实难熬。"
      region.rooms[26].exits = "eastdown|northup"
      region.rooms[26].links = {}
        region.rooms[26].links.nu = {}
          region.rooms[26].links.nu.to = 1939
          region.rooms[26].links.nu.con = ""
        region.rooms[26].links.ed = {}
          region.rooms[26].links.ed.to = 1952
          region.rooms[26].links.ed.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;sd;ed"
      region.rooms[27].name = "西域山路"
      region.rooms[27].zone = "昆仑山"
      region.rooms[27].id = 1952
      region.rooms[27].desc = "    渐行渐西，天气一天冷似一天，西域昆仑派势力雄强，沿途倒并无什么强盗，只是黄沙扑面，寒风透骨，却也着实难熬。"
      region.rooms[27].exits = "westup|east"
      region.rooms[27].links = {}
        region.rooms[27].links.e = {}
          region.rooms[27].links.e.to = 1953
          region.rooms[27].links.e.con = ""
        region.rooms[27].links.wu = {}
          region.rooms[27].links.wu.to = 1951
          region.rooms[27].links.wu.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;sd;ed;e"
      region.rooms[28].name = "西域山路"
      region.rooms[28].zone = "昆仑山"
      region.rooms[28].id = 1953
      region.rooms[28].desc = "    渐行渐西，天气一天冷似一天，西域昆仑派势力雄强，沿途倒并无什么强盗，只是黄沙扑面，寒风透骨，却也着实难熬。"
      region.rooms[28].exits = "east|west"
      region.rooms[28].links = {}
        region.rooms[28].links.w = {}
          region.rooms[28].links.w.to = 1952
          region.rooms[28].links.w.con = ""
        region.rooms[28].links.e = {}
          region.rooms[28].links.e.to = 1954
          region.rooms[28].links.e.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly kl;s;sd;sd;sd;wd;sd;e;se;e;sd;ed;e;e"
      region.rooms[29].name = "镇远桥"
      region.rooms[29].zone = "昆仑山"
      region.rooms[29].id = 1954
      region.rooms[29].desc = "    这座桥号称“天下黄河第一桥”，气势极为雄伟，扼守西域，东往中原。黄河水从桥底倾泻而过，轰隆作响。桥侧有一处小洞（dong）。"
      region.rooms[29].exits = "southeast|west"
      region.rooms[29].links = {}
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 1953
          region.rooms[29].links.w.con = ""
        region.rooms[29].links.se = {}
          region.rooms[29].links.se.to = 1899
          region.rooms[29].links.se.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly kl;n"
      region.rooms[30].name = "石屏风"
      region.rooms[30].zone = "昆仑山"
      region.rooms[30].id = 1955
      region.rooms[30].desc = "    这是一个巨大的屏风，用昆仑山特产的汗白玉雕成，屏风上的图案是昆仑派的师祖昆仑三圣何足道挑战少林的风姿，英姿挺拔，颇有一派宗师之象。屏风后面就是昆仑派的前厅了。"
      region.rooms[30].exits = "south|north"
      region.rooms[30].links = {}
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 1927
          region.rooms[30].links.s.con = ""
        region.rooms[30].links.n = {}
          region.rooms[30].links.n.to = 1956
          region.rooms[30].links.n.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly kl;n;n"
      region.rooms[31].name = "前厅"
      region.rooms[31].zone = "昆仑山"
      region.rooms[31].id = 1956
      region.rooms[31].desc = "    这里是座大厅，高檐大瓦，十分的简朴而壮阔，厅内摆几张高背方椅，一张八仙桌，看来是接待客人的地方，西面和东面也是客厅，供客人歇息，北面一条长廊通向后面。"
      region.rooms[31].exits = "south|east|north|west"
      region.rooms[31].links = {}
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 1957
          region.rooms[31].links.e.con = ""
        region.rooms[31].links.s = {}
          region.rooms[31].links.s.to = 1955
          region.rooms[31].links.s.con = ""
        region.rooms[31].links.w = {}
          region.rooms[31].links.w.to = 1960
          region.rooms[31].links.w.con = ""
        region.rooms[31].links.n = {}
          region.rooms[31].links.n.to = 1963
          region.rooms[31].links.n.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly kl;n;n;e"
      region.rooms[32].name = "东长廊"
      region.rooms[32].zone = "昆仑山"
      region.rooms[32].id = 1957
      region.rooms[32].desc = "    这是一条长廊，连接前厅和客房，不断看见各种打扮的江湖人士走过，看过廊外，是一片青色的树林，幽静雅致，只听见不断传来的鸟鸣声。"
      region.rooms[32].exits = "east|west"
      region.rooms[32].links = {}
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 1956
          region.rooms[32].links.w.con = ""
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 1958
          region.rooms[32].links.e.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly kl;n;n;e;e"
      region.rooms[33].name = "东外廊"
      region.rooms[33].zone = "昆仑山"
      region.rooms[33].id = 1958
      region.rooms[33].desc = "    这是一条长廊，连接前厅和客房，不断看见各种打扮的江湖人士走过，看过廊外，是一片青色的树林，幽静雅致，只听见不断传来的鸟鸣声。"
      region.rooms[33].exits = "east|west"
      region.rooms[33].links = {}
        region.rooms[33].links.w = {}
          region.rooms[33].links.w.to = 1957
          region.rooms[33].links.w.con = ""
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 1959
          region.rooms[33].links.e.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly kl;n;n;e;e;e"
      region.rooms[34].name = "客餐厅"
      region.rooms[34].zone = "昆仑山"
      region.rooms[34].id = 1959
      region.rooms[34].desc = "    这里是待客餐厅，里面简单，只有一些椅子和桌子，桌子上摆着些茶和点心供客人食用。不少江湖人士不远千里来到这里，往往先到这里歇息片刻，恢复一下。"
      region.rooms[34].exits = "west"
      region.rooms[34].links = {}
        region.rooms[34].links.w = {}
          region.rooms[34].links.w.to = 1958
          region.rooms[34].links.w.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly kl;n;n;w"
      region.rooms[35].name = "西长廊"
      region.rooms[35].zone = "昆仑山"
      region.rooms[35].id = 1960
      region.rooms[35].desc = "    这是一条长廊，连接前厅和客房，不断看见各种打扮的江湖人士走过，看过廊外，是一片青色的树林，幽静雅致，只听见不断传来的鸟鸣声。"
      region.rooms[35].exits = "east|west"
      region.rooms[35].links = {}
        region.rooms[35].links.e = {}
          region.rooms[35].links.e.to = 1956
          region.rooms[35].links.e.con = ""
        region.rooms[35].links.w = {}
          region.rooms[35].links.w.to = 1961
          region.rooms[35].links.w.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly kl;n;n;w;w"
      region.rooms[36].name = "西外廊"
      region.rooms[36].zone = "昆仑山"
      region.rooms[36].id = 1961
      region.rooms[36].desc = "    这是一条长廊，连接前厅和客房，不断看见各种打扮的江湖人士走过，看过廊外，是一片青色的树林，幽静雅致，只听见不断传来的鸟鸣声。"
      region.rooms[36].exits = "east|west"
      region.rooms[36].links = {}
        region.rooms[36].links.e = {}
          region.rooms[36].links.e.to = 1960
          region.rooms[36].links.e.con = ""
        region.rooms[36].links.w = {}
          region.rooms[36].links.w.to = 1962
          region.rooms[36].links.w.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly kl;n;n;w;w;w"
      region.rooms[37].name = "客卧厅"
      region.rooms[37].zone = "昆仑山"
      region.rooms[37].id = 1962
      region.rooms[37].desc = "    这里是待客休息厅，里面简单，只有几张床，供疲惫的客人歇息，屋子里烤着火，暖烘烘的。"
      region.rooms[37].exits = "east"
      region.rooms[37].links = {}
        region.rooms[37].links.e = {}
          region.rooms[37].links.e.to = 1961
          region.rooms[37].links.e.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly kl;n;n;n"
      region.rooms[38].name = "石板路"
      region.rooms[38].zone = "昆仑山"
      region.rooms[38].id = 1963
      region.rooms[38].desc = "    这是一条铺的十分平整的石板路，路面打扫的干干净净，北面过去是个花园，传来阵阵花香。"
      region.rooms[38].exits = "south|north"
      region.rooms[38].links = {}
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 1956
          region.rooms[38].links.s.con = ""
        region.rooms[38].links.n = {}
          region.rooms[38].links.n.to = 1964
          region.rooms[38].links.n.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly kl;n;n;n;n"
      region.rooms[39].name = "花园"
      region.rooms[39].zone = "昆仑山"
      region.rooms[39].id = 1964
      region.rooms[39].desc = "    这里是昆仑派的花园。廊边花木扶疏，竹影参差，山泉急湍，竟然富有江南园林的情趣。西面是静修室。"
      region.rooms[39].exits = "south|east|north|west"
      region.rooms[39].links = {}
        region.rooms[39].links.e = {}
          region.rooms[39].links.e.to = 1965
          region.rooms[39].links.e.con = ""
        region.rooms[39].links.s = {}
          region.rooms[39].links.s.to = 1963
          region.rooms[39].links.s.con = ""
        region.rooms[39].links.w = {}
          region.rooms[39].links.w.to = 1966
          region.rooms[39].links.w.con = ""
        region.rooms[39].links.n = {}
          region.rooms[39].links.n.to = 1967
          region.rooms[39].links.n.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly kl;n;n;n;n;e"
      region.rooms[40].name = "练武场"
      region.rooms[40].zone = "昆仑山"
      region.rooms[40].id = 1965
      region.rooms[40].desc = "    这里是练武场，昆仑派的很多弟子在这里练习武功，在练武场的一角，有一个专门用来练武的梅花桩(zhuang)，许多弟子都围在这里练习腿功。"
      region.rooms[40].exits = "west"
      region.rooms[40].links = {}
        region.rooms[40].links.w = {}
          region.rooms[40].links.w.to = 1964
          region.rooms[40].links.w.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly kl;n;n;n;n;w"
      region.rooms[41].name = "静修室"
      region.rooms[41].zone = "昆仑山"
      region.rooms[41].id = 1966
      region.rooms[41].desc = "    这里是静修室，地下顺序地放着几个蒲团，正中烧着几柱香，轻烟袅袅升起。几位昆仑派弟子正盘膝坐在上面打坐静修。"
      region.rooms[41].exits = "east"
      region.rooms[41].links = {}
        region.rooms[41].links.e = {}
          region.rooms[41].links.e.to = 1964
          region.rooms[41].links.e.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly kl;n;n;n;n;n"
      region.rooms[42].name = "九曲廊"
      region.rooms[42].zone = "昆仑山"
      region.rooms[42].id = 1967
      region.rooms[42].desc = "    九曲廊前后共有九进，曲曲折折地盘旋在水面。一路穿花度柳，抚石依泉，落花浮荡，水色溶溶。两边垂柳杂着桃杏，藤蔓绕柱。白石为栏，飞楼插空，转折处皆由小亭相接。"
      region.rooms[42].exits = "south|north|east|west"
      region.rooms[42].links = {}
        region.rooms[42].links.e = {}
          region.rooms[42].links.e.to = 1968
          region.rooms[42].links.e.con = ""
        region.rooms[42].links.s = {}
          region.rooms[42].links.s.to = 1964
          region.rooms[42].links.s.con = ""
        region.rooms[42].links.w = {}
          region.rooms[42].links.w.to = 1969
          region.rooms[42].links.w.con = ""
        region.rooms[42].links.n = {}
          region.rooms[42].links.n.to = 1975
          region.rooms[42].links.n.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly kl;n;n;n;n;n;e"
      region.rooms[43].name = "九曲廊"
      region.rooms[43].zone = "昆仑山"
      region.rooms[43].id = 1968
      region.rooms[43].desc = "    九曲廊前后共有九进，曲曲折折地盘旋在水面。一路穿花度柳，抚石依泉，落花浮荡，水色溶溶。两边垂柳杂着桃杏，藤蔓绕柱。白石为栏，飞楼插空，转折处皆由小亭相接。"
      region.rooms[43].exits = "north|southeast|west"
      region.rooms[43].links = {}
        region.rooms[43].links.w = {}
          region.rooms[43].links.w.to = 1967
          region.rooms[43].links.w.con = ""
        region.rooms[43].links.n = {}
          region.rooms[43].links.n.to = 1974
          region.rooms[43].links.n.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly kl;n;n;n;n;n;w"
      region.rooms[44].name = "九曲廊"
      region.rooms[44].zone = "昆仑山"
      region.rooms[44].id = 1969
      region.rooms[44].desc = "    九曲廊前后共有九进，曲曲折折地盘旋在水面。一路穿花度柳，抚石依泉，落花浮荡，水色溶溶。两边垂柳杂着桃杏，藤蔓绕柱。白石为栏，飞楼插空，转折处皆由小亭相接。"
      region.rooms[44].exits = "east|north|southwest"
      region.rooms[44].links = {}
        region.rooms[44].links.e = {}
          region.rooms[44].links.e.to = 1967
          region.rooms[44].links.e.con = ""
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 1970
          region.rooms[44].links.n.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly kl;n;n;n;n;n;w;n"
      region.rooms[45].name = "九曲廊"
      region.rooms[45].zone = "昆仑山"
      region.rooms[45].id = 1970
      region.rooms[45].desc = "    九曲廊前后共有九进，曲曲折折地盘旋在水面。一路穿花度柳，抚石依泉，落花浮荡，水色溶溶。两边垂柳杂着桃杏，藤蔓绕柱。白石为栏，飞楼插空，转折处皆由小亭相接。"
      region.rooms[45].exits = "south|north|east|west"
      region.rooms[45].links = {}
        region.rooms[45].links.e = {}
          region.rooms[45].links.e.to = 1975
          region.rooms[45].links.e.con = ""
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 1969
          region.rooms[45].links.s.con = ""
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 1971
          region.rooms[45].links.n.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly kl;n;n;n;n;n;w;n;n"
      region.rooms[46].name = "九曲廊"
      region.rooms[46].zone = "昆仑山"
      region.rooms[46].id = 1971
      region.rooms[46].desc = "    九曲廊前后共有九进，曲曲折折地盘旋在水面。一路穿花度柳，抚石依泉，落花浮荡，水色溶溶。两边垂柳杂着桃杏，藤蔓绕柱。白石为栏，飞楼插空，转折处皆由小亭相接。"
      region.rooms[46].exits = "south|east|northwest"
      region.rooms[46].links = {}
        region.rooms[46].links.e = {}
          region.rooms[46].links.e.to = 1972
          region.rooms[46].links.e.con = ""
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 1970
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.nw = {}
          region.rooms[46].links.nw.to = 1977
          region.rooms[46].links.nw.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly kl;n;n;n;n;n;n;n"
      region.rooms[47].name = "九曲廊"
      region.rooms[47].zone = "昆仑山"
      region.rooms[47].id = 1972
      region.rooms[47].desc = "    九曲廊前后共有九进，曲曲折折地盘旋在水面。一路穿花度柳，抚石依泉，落花浮荡，水色溶溶。两边垂柳杂着桃杏，藤蔓绕柱。白石为栏，飞楼插空，转折处皆由小亭相接。"
      region.rooms[47].exits = "south|east|north|northwest|northeast|west"
      region.rooms[47].links = {}
        region.rooms[47].links.ne = {}
          region.rooms[47].links.ne.to = 1979
          region.rooms[47].links.ne.con = ""
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 1975
          region.rooms[47].links.s.con = ""
        region.rooms[47].links.e = {}
          region.rooms[47].links.e.to = 1973
          region.rooms[47].links.e.con = ""
        region.rooms[47].links.w = {}
          region.rooms[47].links.w.to = 1971
          region.rooms[47].links.w.con = ""
        region.rooms[47].links.nw = {}
          region.rooms[47].links.nw.to = 1980
          region.rooms[47].links.nw.con = ""
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 1978
          region.rooms[47].links.n.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "fly kl;n;n;n;n;n;e;n;n"
      region.rooms[48].name = "九曲廊"
      region.rooms[48].zone = "昆仑山"
      region.rooms[48].id = 1973
      region.rooms[48].desc = "    九曲廊前后共有九进，曲曲折折地盘旋在水面。一路穿花度柳，抚石依泉，落花浮荡，水色溶溶。两边垂柳杂着桃杏，藤蔓绕柱。白石为栏，飞楼插空，转折处皆由小亭相接。"
      region.rooms[48].exits = "south|northeast|west"
      region.rooms[48].links = {}
        region.rooms[48].links.ne = {}
          region.rooms[48].links.ne.to = 1976
          region.rooms[48].links.ne.con = ""
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 1974
          region.rooms[48].links.s.con = ""
        region.rooms[48].links.w = {}
          region.rooms[48].links.w.to = 1972
          region.rooms[48].links.w.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly kl;n;n;n;n;n;e;n"
      region.rooms[49].name = "九曲廊"
      region.rooms[49].zone = "昆仑山"
      region.rooms[49].id = 1974
      region.rooms[49].desc = "    九曲廊前后共有九进，曲曲折折地盘旋在水面。一路穿花度柳，抚石依泉，落花浮荡，水色溶溶。两边垂柳杂着桃杏，藤蔓绕柱。白石为栏，飞楼插空，转折处皆由小亭相接。"
      region.rooms[49].exits = "south|north|east|west"
      region.rooms[49].links = {}
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 1975
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 1968
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.n = {}
          region.rooms[49].links.n.to = 1973
          region.rooms[49].links.n.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly kl;n;n;n;n;n;n"
      region.rooms[50].name = "三圣堂"
      region.rooms[50].zone = "昆仑山"
      region.rooms[50].id = 1975
      region.rooms[50].desc = "    昆仑三圣堂乃“昆仑三圣”何足道所建，原为了修身养性，读书练功。随着昆仑派日益壮大，名声远播，这里便成了昆仑派聚众议事，接待各路江湖英雄的地方。“昆仑三圣”也只好另觅安静所在了。"
      region.rooms[50].exits = "south|north|east|west"
      region.rooms[50].links = {}
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 1974
          region.rooms[50].links.e.con = ""
        region.rooms[50].links.s = {}
          region.rooms[50].links.s.to = 1967
          region.rooms[50].links.s.con = ""
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 1970
          region.rooms[50].links.w.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 1972
          region.rooms[50].links.n.con = ""
    region.rooms[51] = {}
      region.rooms[51].path = "fly kl;n;n;n;n;n;e;n;n;ne"
      region.rooms[51].name = "练功房"
      region.rooms[51].zone = "昆仑山"
      region.rooms[51].id = 1976
      region.rooms[51].desc = "    这里是练功房，地下凌乱地放着几个蒲团，摆满了大刀长剑、沙袋绑腿等，是昆仑弟子日常练功的地方。"
      region.rooms[51].exits = "southwest"
      region.rooms[51].links = {}
        region.rooms[51].links.sw = {}
          region.rooms[51].links.sw.to = 1973
          region.rooms[51].links.sw.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "fly kl;n;n;n;n;n;w;n;n;nw"
      region.rooms[52].name = "药房"
      region.rooms[52].zone = "昆仑山"
      region.rooms[52].id = 1977
      region.rooms[52].desc = "    这里是昆仑派的药房，房间里弥漫着浓浓的药香，房间内排满了装满各类药材的大药柜，每个药柜都有上百个装药的抽屉贴满了各类药名。西边是一个巨大红杉木柜，柜上贴着方丈印的封条。一位年轻女子正来回忙碌着指点众执役称量药品，熬药煎汤。"
      region.rooms[52].exits = "southeast"
      region.rooms[52].links = {}
        region.rooms[52].links.se = {}
          region.rooms[52].links.se.to = 1971
          region.rooms[52].links.se.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "fly kl;n;n;n;n;n;n;n;n"
      region.rooms[53].name = "后厅"
      region.rooms[53].zone = "昆仑山"
      region.rooms[53].id = 1978
      region.rooms[53].desc = "    这里是后客厅，里面简单，只有几张软榻，供疲惫的客人歇息，屋子里烤着火，暖烘烘的。"
      region.rooms[53].exits = "south|east|north|west"
      region.rooms[53].links = {}
        region.rooms[53].links.e = {}
          region.rooms[53].links.e.to = 1979
          region.rooms[53].links.e.con = ""
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 1980
          region.rooms[53].links.w.con = ""
        region.rooms[53].links.s = {}
          region.rooms[53].links.s.to = 1972
          region.rooms[53].links.s.con = ""
        region.rooms[53].links.n = {}
          region.rooms[53].links.n.to = 1982
          region.rooms[53].links.n.con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "fly kl;n;n;n;n;n;n;n;ne"
      region.rooms[54].name = "假山"
      region.rooms[54].zone = "昆仑山"
      region.rooms[54].id = 1979
      region.rooms[54].desc = "    穿过了九曲廊就到了这里，黄色的山拔地而起，山峰俊俏，山间古柏，山顶小亭，山中还有小院、石桥、石室等，气势磅礴。为江南山石中所少见。"
      region.rooms[54].exits = "northwest|east|west|southwest"
      region.rooms[54].links = {}
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 1981
          region.rooms[54].links.e.con = ""
        region.rooms[54].links.sw = {}
          region.rooms[54].links.sw.to = 1972
          region.rooms[54].links.sw.con = ""
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 1978
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.nw = {}
          region.rooms[54].links.nw.to = 1982
          region.rooms[54].links.nw.con = ""
    region.rooms[55] = {}
      region.rooms[55].path = "fly kl;n;n;n;n;n;n;n;nw"
      region.rooms[55].name = "凉亭"
      region.rooms[55].zone = "昆仑山"
      region.rooms[55].id = 1980
      region.rooms[55].desc = "    这是湖中的一个小亭子，从这望去，可以看到整个湖面的景色，令人心旷神怡。阵阵凉风吹来，好一片江南春色，令人忘了这里是西域绝顶。"
      region.rooms[55].exits = "east|southeast|northeast|west"
      region.rooms[55].links = {}
        region.rooms[55].links.ne = {}
          region.rooms[55].links.ne.to = 1982
          region.rooms[55].links.ne.con = ""
        region.rooms[55].links.e = {}
          region.rooms[55].links.e.to = 1978
          region.rooms[55].links.e.con = ""
        region.rooms[55].links.w = {}
          region.rooms[55].links.w.to = 1983
          region.rooms[55].links.w.con = ""
        region.rooms[55].links.se = {}
          region.rooms[55].links.se.to = 1972
          region.rooms[55].links.se.con = ""
    region.rooms[56] = {}
      region.rooms[56].path = "fly kl;n;n;n;n;n;n;n;ne;e"
      region.rooms[56].name = "棋室"
      region.rooms[56].zone = "昆仑山"
      region.rooms[56].id = 1981
      region.rooms[56].desc = "    昆仑三圣以“琴”、“棋”、“剑”著称，奕棋是每个昆仑弟子入门必修的功课。此处是昆仑派的棋室，供昆仑弟子磨练棋艺使用。"
      region.rooms[56].exits = "west"
      region.rooms[56].links = {}
        region.rooms[56].links.w = {}
          region.rooms[56].links.w.to = 1979
          region.rooms[56].links.w.con = ""
    region.rooms[57] = {}
      region.rooms[57].path = "fly kl;n;n;n;n;n;n;n;ne;nw"
      region.rooms[57].name = "后花园"
      region.rooms[57].zone = "昆仑山"
      region.rooms[57].id = 1982
      region.rooms[57].desc = "    这里是昆仑派的后花园。园内有方池，缘池是座假山。廊边花木扶疏，竹影参差，山泉急湍，竟然富有江南园林的情趣。西面是昆仑派的侧门。"
      region.rooms[57].exits = "south|north|east|southeast|west|southwest"
      region.rooms[57].links = {}
        region.rooms[57].links.s = {}
          region.rooms[57].links.s.to = 1978
          region.rooms[57].links.s.con = ""
        region.rooms[57].links.se = {}
          region.rooms[57].links.se.to = 1979
          region.rooms[57].links.se.con = ""
        region.rooms[57].links.e = {}
          region.rooms[57].links.e.to = 1985
          region.rooms[57].links.e.con = ""
        region.rooms[57].links.sw = {}
          region.rooms[57].links.sw.to = 1980
          region.rooms[57].links.sw.con = ""
        region.rooms[57].links.w = {}
          region.rooms[57].links.w.to = 1984
          region.rooms[57].links.w.con = ""
        region.rooms[57].links.n = {}
          region.rooms[57].links.n.to = 1988
          region.rooms[57].links.n.con = ""
    region.rooms[58] = {}
      region.rooms[58].path = "fly kl;n;n;n;n;n;n;n;nw;w"
      region.rooms[58].name = "琴室"
      region.rooms[58].zone = "昆仑山"
      region.rooms[58].id = 1983
      region.rooms[58].desc = "    昆仑三圣以“琴”、“棋”、“剑”著称，奕棋是每个昆仑弟子入门必修的功课。此处是昆仑派的琴室，供昆仑弟子磨练琴艺使用。"
      region.rooms[58].exits = "east"
      region.rooms[58].links = {}
        region.rooms[58].links.e = {}
          region.rooms[58].links.e.to = 1980
          region.rooms[58].links.e.con = ""
    region.rooms[59] = {}
      region.rooms[59].path = "fly kl;n;n;n;n;n;n;n;ne;nw;w"
      region.rooms[59].name = "侧门"
      region.rooms[59].zone = "昆仑山"
      region.rooms[59].id = 1984
      region.rooms[59].desc = "    绕过三圣堂的后花园，经过一条曲曲折折的花径，又穿入许多厅堂之中。但见屋宇连绵，门户复叠，到了昆仑派的侧门。"
      region.rooms[59].exits = "east"
      region.rooms[59].links = {}
        region.rooms[59].links.e = {}
          region.rooms[59].links.e.to = 1982
          region.rooms[59].links.e.con = ""
    region.rooms[60] = {}
      region.rooms[60].path = "fly kl;n;n;n;n;n;n;n;ne;nw;e"
      region.rooms[60].name = "花圃"
      region.rooms[60].zone = "昆仑山"
      region.rooms[60].id = 1985
      region.rooms[60].desc = "    这里是一个小花圃，种满了各种西域奇花异草，中原难得一见。"
      region.rooms[60].exits = "north|west"
      region.rooms[60].links = {}
        region.rooms[60].links.w = {}
          region.rooms[60].links.w.to = 1982
          region.rooms[60].links.w.con = ""
        region.rooms[60].links.n = {}
          region.rooms[60].links.n.to = 1986
          region.rooms[60].links.n.con = ""
    region.rooms[61] = {}
      region.rooms[61].path = "fly kl;n;n;n;n;n;n;n;ne;nw;e;n"
      region.rooms[61].name = "铁琴居"
      region.rooms[61].zone = "昆仑山"
      region.rooms[61].id = 1986
      region.rooms[61].desc = "    这儿便是“铁琴先生”何太冲的居处。房间陈设颇为精巧，物品与中土所见别是不同。几个昆仑派弟子守在这里，个个深有忧色。东边通往卧室。"
      region.rooms[61].exits = "south|east"
      region.rooms[61].links = {}
        region.rooms[61].links.s = {}
          region.rooms[61].links.s.to = 1985
          region.rooms[61].links.s.con = ""
        region.rooms[61].links.e = {}
          region.rooms[61].links.e.to = 1987
          region.rooms[61].links.e.con = ""
    region.rooms[62] = {}
      region.rooms[62].path = "fly kl;n;n;n;n;n;n;n;ne;nw;e;n;e"
      region.rooms[62].name = "卧室"
      region.rooms[62].zone = "昆仑山"
      region.rooms[62].id = 1987
      region.rooms[62].desc = "    这里是何太冲最宠爱的第五小妾五姑的卧房。刚一进房，扑鼻便是一股药气，里面还能闻到一股十分古怪的气息，过了片刻，更觉得这气息忽浓忽淡，甚是奇特。床上躺着一个人，这人面向帐里，喘气甚急，象是扯着风箱。窗子(window)都是紧紧关着。"
      region.rooms[62].exits = "west"
      region.rooms[62].links = {}
        region.rooms[62].links.w = {}
          region.rooms[62].links.w.to = 1986
          region.rooms[62].links.w.con = ""
    region.rooms[63] = {}
      region.rooms[63].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n"
      region.rooms[63].name = "云杉林"
      region.rooms[63].zone = "昆仑山"
      region.rooms[63].id = 1988
      region.rooms[63].desc = "    这是一片蜿蜒无尽的翠绿的树林，密密的云杉像撑天的巨伞，重重叠叠的枝丫，只漏下斑斑点点细碎的日影。林子十分幽静，连鸟雀也少飞来，只偶尔能听到远处的几声鸟鸣。"
      region.rooms[63].exits = "south|north|east|west"
      region.rooms[63].links = {}
        region.rooms[63].links.e = {}
          region.rooms[63].links.e.to = 1989
          region.rooms[63].links.e.con = ""
        region.rooms[63].links.w = {}
          region.rooms[63].links.w.to = 1993
          region.rooms[63].links.w.con = ""
        region.rooms[63].links.s = {}
          region.rooms[63].links.s.to = 1992
          region.rooms[63].links.s.con = ""
        region.rooms[63].links.n = {}
          region.rooms[63].links.n.to = 1982
          region.rooms[63].links.n.con = ""
    region.rooms[64] = {}
      region.rooms[64].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;e"
      region.rooms[64].name = "云杉林"
      region.rooms[64].zone = "昆仑山"
      region.rooms[64].id = 1989
      region.rooms[64].desc = "    这是一片蜿蜒无尽的翠绿的树林，密密的云杉像撑天的巨伞，重重叠叠的枝丫，只漏下斑斑点点细碎的日影。林子十分幽静，连鸟雀也少飞来，只偶尔能听到远处的几声鸟鸣。"
      region.rooms[64].exits = "south|east|north|west"
      region.rooms[64].links = {}
        region.rooms[64].links.e = {}
          region.rooms[64].links.e.to = 1988
          region.rooms[64].links.e.con = ""
        region.rooms[64].links.s = {}
          region.rooms[64].links.s.to = 1990
          region.rooms[64].links.s.con = ""
        region.rooms[64].links.w = {}
          region.rooms[64].links.w.to = 1993
          region.rooms[64].links.w.con = ""
        region.rooms[64].links.n = {}
          region.rooms[64].links.n.to = 1989
          region.rooms[64].links.n.con = ""
    region.rooms[65] = {}
      region.rooms[65].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;e;s"
      region.rooms[65].name = "云杉林"
      region.rooms[65].zone = "昆仑山"
      region.rooms[65].id = 1990
      region.rooms[65].desc = "    这是一片蜿蜒无尽的翠绿的树林，密密的云杉像撑天的巨伞，重重叠叠的枝丫，只漏下斑斑点点细碎的日影。林子十分幽静，连鸟雀也少飞来，只偶尔能听到远处的几声鸟鸣。"
      region.rooms[65].exits = "south|east|north|west"
      region.rooms[65].links = {}
        region.rooms[65].links.e = {}
          region.rooms[65].links.e.to = 1990
          region.rooms[65].links.e.con = ""
        region.rooms[65].links.w = {}
          region.rooms[65].links.w.to = 1991
          region.rooms[65].links.w.con = ""
        region.rooms[65].links.s = {}
          region.rooms[65].links.s.to = 1997
          region.rooms[65].links.s.con = ""
        region.rooms[65].links.n = {}
          region.rooms[65].links.n.to = 1989
          region.rooms[65].links.n.con = ""
    region.rooms[66] = {}
      region.rooms[66].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;e;s;w"
      region.rooms[66].name = "云杉林"
      region.rooms[66].zone = "昆仑山"
      region.rooms[66].id = 1991
      region.rooms[66].desc = "    这是一片蜿蜒无尽的翠绿的树林，密密的云杉像撑天的巨伞，重重叠叠的枝丫，只漏下斑斑点点细碎的日影。林子十分幽静，连鸟雀也少飞来，只偶尔能听到远处的几声鸟鸣。"
      region.rooms[66].exits = "south|north|east|west"
      region.rooms[66].links = {}
        region.rooms[66].links.e = {}
          region.rooms[66].links.e.to = 1998
          region.rooms[66].links.e.con = ""
        region.rooms[66].links.s = {}
          region.rooms[66].links.s.to = 1992
          region.rooms[66].links.s.con = ""
        region.rooms[66].links.w = {}
          region.rooms[66].links.w.to = 1990
          region.rooms[66].links.w.con = ""
        region.rooms[66].links.n = {}
          region.rooms[66].links.n.to = 1993
          region.rooms[66].links.n.con = ""
    region.rooms[67] = {}
      region.rooms[67].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;s"
      region.rooms[67].name = "云杉林"
      region.rooms[67].zone = "昆仑山"
      region.rooms[67].id = 1992
      region.rooms[67].desc = "    这是一片蜿蜒无尽的翠绿的树林，密密的云杉像撑天的巨伞，重重叠叠的枝丫，只漏下斑斑点点细碎的日影。林子十分幽静，连鸟雀也少飞来，只偶尔能听到远处的几声鸟鸣。"
      region.rooms[67].exits = "south|north|east|west"
      region.rooms[67].links = {}
        region.rooms[67].links.e = {}
          region.rooms[67].links.e.to = 1989
          region.rooms[67].links.e.con = ""
        region.rooms[67].links.w = {}
          region.rooms[67].links.w.to = 1988
          region.rooms[67].links.w.con = ""
        region.rooms[67].links.s = {}
          region.rooms[67].links.s.to = 1993
          region.rooms[67].links.s.con = ""
        region.rooms[67].links.n = {}
          region.rooms[67].links.n.to = 1993
          region.rooms[67].links.n.con = ""
    region.rooms[68] = {}
      region.rooms[68].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;w"
      region.rooms[68].name = "云杉林"
      region.rooms[68].zone = "昆仑山"
      region.rooms[68].id = 1993
      region.rooms[68].desc = "    这是一片蜿蜒无尽的翠绿的树林，密密的云杉像撑天的巨伞，重重叠叠的枝丫，只漏下斑斑点点细碎的日影。林子十分幽静，连鸟雀也少飞来，只偶尔能听到远处的几声鸟鸣。"
      region.rooms[68].exits = "south|east|north|west"
      region.rooms[68].links = {}
        region.rooms[68].links.e = {}
          region.rooms[68].links.e.to = 1988
          region.rooms[68].links.e.con = ""
        region.rooms[68].links.w = {}
          region.rooms[68].links.w.to = 1990
          region.rooms[68].links.w.con = ""
        region.rooms[68].links.s = {}
          region.rooms[68].links.s.to = 1988
          region.rooms[68].links.s.con = ""
        region.rooms[68].links.n = {}
          region.rooms[68].links.n.to = 1994
          region.rooms[68].links.n.con = ""
    region.rooms[69] = {}
      region.rooms[69].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;w;n"
      region.rooms[69].name = "后院"
      region.rooms[69].zone = "昆仑山"
      region.rooms[69].id = 1994
      region.rooms[69].desc = "    由于这里一向少有人来，渐渐被人忘记，也就很久没有被打扫过了。落叶满地，踩上去软绵绵的。墙壁已有些残破，檐下结满了蜘蛛网，角落里的一扇小门因为日晒雨淋，开始朽烂。"
      region.rooms[69].exits = "south"
      region.rooms[69].links = {}
        region.rooms[69].links.s = {}
          region.rooms[69].links.s.to = 1993
          region.rooms[69].links.s.con = ""
        region.rooms[69].links["open door;out"] = {}
          region.rooms[69].links["open door;out"].to = 1995
          region.rooms[69].links["open door;out"].con = ""
    region.rooms[70] = {}
      region.rooms[70].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;w;n;open door;out"
      region.rooms[70].name = "扶峰山"
      region.rooms[70].zone = "昆仑山"
      region.rooms[70].id = 1995
      region.rooms[70].desc = "    扶峰山极高且十分陡峭，山腰以上尽没入茫茫云海中，峰顶终年积雪，山腰以下却是郁郁苍苍，林木茂密，花团锦簇，春意烂漫。"
      region.rooms[70].exits = "enter|northeast"
      region.rooms[70].links = {}
        region.rooms[70].links.ne = {}
          region.rooms[70].links.ne.to = 1996
          region.rooms[70].links.ne.con = ""
        region.rooms[70].links.enter = {}
          region.rooms[70].links.enter.to = 1994
          region.rooms[70].links.enter.con = ""
        region.rooms[70].links.climb = {}
          region.rooms[70].links.climb.to = 2050
          region.rooms[70].links.climb.con = ""
    region.rooms[71] = {}
      region.rooms[71].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;w;n;open door;out;ne"
      region.rooms[71].name = "白牛岭"
      region.rooms[71].zone = "昆仑山"
      region.rooms[71].id = 1996
      region.rooms[71].desc = "    这座山岭因终年覆盖白雪，且形状远望犹如一头正在吃草的牛而得名。这里寒风呼啸，凛冽刺骨，你不禁打了个寒颤。山顶有一处平地，放有一块青色的巨石(stone)。"
      region.rooms[71].exits = "southwest"
      region.rooms[71].links = {}
        region.rooms[71].links.sw = {}
          region.rooms[71].links.sw.to = 1995
          region.rooms[71].links.sw.con = ""
    region.rooms[72] = {}
      region.rooms[72].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;e;s;s"
      region.rooms[72].name = "葱岭谷"
      region.rooms[72].zone = "昆仑山"
      region.rooms[72].id = 1997
      region.rooms[72].desc = "    你的眼前突然为之一亮，只见一条象被一刀劈开的峡谷岩石间，高山的雪水泻落到千丈以下的山涧里去，溅起的密密的飞沫激起一种惊心动魄的震憾。就在这深山野谷的溪流边，却长满了各种各样的花草树木，春天繁花开遍峡谷秋天果实压满山腰，人迹罕至，正是鸟兽们(bird)的乐园。"
      region.rooms[72].exits = "out"
      region.rooms[72].links = {}
        region.rooms[72].links.n = {}
          region.rooms[72].links.n.to = 1990
          region.rooms[72].links.n.con = ""
        region.rooms[72].links.out = {}
          region.rooms[72].links.out.to = 1992
          region.rooms[72].links.out.con = ""
    region.rooms[73] = {}
      region.rooms[73].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;e;s;w;e"
      region.rooms[73].name = "苦寒楼一层"
      region.rooms[73].zone = "昆仑山"
      region.rooms[73].id = 1998
      region.rooms[73].desc = "    这里是苦寒楼的底层。苦寒楼结构简单，四周为浓密的云杉包围。取名自“梅花香自苦寒来”之意，乃是昆仑派前辈为了激励后进昆仑派弟子而建的，往上看，长长的木楼梯盘绕而上，似乎永无尽头。青砖地相当洁净，看来经常有人打扫。四面墙上的壁画(bihua) 都是前辈们留下武功图谱。"
      region.rooms[73].exits = "up|out"
      region.rooms[73].links = {}
        region.rooms[73].links.u = {}
          region.rooms[73].links.u.to = 1999
          region.rooms[73].links.u.con = ""
        region.rooms[73].links.w = {}
          region.rooms[73].links.w.to = 1991
          region.rooms[73].links.w.con = ""
        region.rooms[73].links.out = {}
          region.rooms[73].links.out.to = 2001
          region.rooms[73].links.out.con = ""
    region.rooms[74] = {}
      region.rooms[74].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;e;s;w;e;u"
      region.rooms[74].name = "苦寒楼二层"
      region.rooms[74].zone = "昆仑山"
      region.rooms[74].id = 1999
      region.rooms[74].desc = "    每个楼层上都铺设了结实的木楼板，八角形的墙身上则开了四扇大窗。四周墙壁贴着昆仑派历代掌门和高手的画像，并有专门的文字记载着他们的事迹。从这里往外眺望，只能看到围绕塔周的密密匝匝的云杉林，正是通过这种忍饥耐寒，清心寡欲的办法以求得对武学孜孜不倦的追求。"
      region.rooms[74].exits = "up|down"
      region.rooms[74].links = {}
        region.rooms[74].links.u = {}
          region.rooms[74].links.u.to = 2000
          region.rooms[74].links.u.con = ""
        region.rooms[74].links.d = {}
          region.rooms[74].links.d.to = 1998
          region.rooms[74].links.d.con = ""
    region.rooms[75] = {}
      region.rooms[75].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;e;s;w;e;u;u"
      region.rooms[75].name = "苦寒楼三层"
      region.rooms[75].zone = "昆仑山"
      region.rooms[75].id = 2000
      region.rooms[75].desc = "    很快就到了苦寒楼顶层。这里可以看到山门以及北边的诸多昆仑山峰，四周的杉林随风摇摆，发出“哗哗哗”的声音。山风夹着隐隐寒气，远处的景色单调而苍凉，你心里顿时生出一种莫名寂寞的感觉。房间里的布置十分简单。往外看，有个很大的红木窗台(out)。"
      region.rooms[75].exits = "down"
      region.rooms[75].links = {}
        region.rooms[75].links.d = {}
          region.rooms[75].links.d.to = 1999
          region.rooms[75].links.d.con = ""
        region.rooms[75].links.out = {}
          region.rooms[75].links.out.to = 1994
          region.rooms[75].links.out.con = ""
    region.rooms[76] = {}
      region.rooms[76].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;e;s;w;e;out"
      region.rooms[76].name = "苦寒楼"
      region.rooms[76].zone = "昆仑山"
      region.rooms[76].id = 2001
      region.rooms[76].desc = "    这里是昆仑派的苦寒楼，取名自“梅花香自苦寒来”之意，乃是昆仑派前辈为了激励后进昆仑派弟子而建的，是昆仑弟子静修之所。"
      region.rooms[76].exits = "north|enter"
      region.rooms[76].links = {}
        region.rooms[76].links.enter = {}
          region.rooms[76].links.enter.to = 1998
          region.rooms[76].links.enter.con = ""
        region.rooms[76].links.n = {}
          region.rooms[76].links.n.to = 1993
          region.rooms[76].links.n.con = ""
    region.rooms[77] = {}
      region.rooms[77].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;w;n;open door;out;climb"
      region.rooms[77].name = "三圣坳"
      region.rooms[77].zone = "昆仑山"
      region.rooms[77].id = 2050
      region.rooms[77].links = {}
        region.rooms[77].links.n = {}
          region.rooms[77].links.n.to = 2051
          region.rooms[77].links.n.con = ""
        region.rooms[77].links.d = {}
          region.rooms[77].links.d.to = 1995
          region.rooms[77].links.d.con = ""
      region.rooms[77].exits = "north|down"
      region.rooms[77].desc = "    但见遍地绿草如锦，到处果树香花。原来那三圣坳四周都是插天高山，挡住了寒气。昆仑派历代掌门人曾花了极大力气整顿这个山坳，派遣弟子东至江南，西至天竺，搬移奇花异树前来种植。忽听得山坳后隐隐传出一阵琴声，你好奇心起，便循声寻去。"
    region.rooms[78] = {}
      region.rooms[78].path = "fly kl;n;n;n;n;n;n;n;ne;nw;n;w;n;open door;out;climb;n"
      region.rooms[78].name = "惊神峰"
      region.rooms[78].zone = "昆仑山"
      region.rooms[78].id = 2051
      region.rooms[78].links = {}
        region.rooms[78].links.s = {}
          region.rooms[78].links.s.to = 2050
          region.rooms[78].links.s.con = ""
      region.rooms[78].exits = "south"
      region.rooms[78].desc = "    折而向北，过了一岭，只见古柏三把百余章，皆挺直端秀，凌霄托根树旁，作花柏顶，灿若云荼。走出十余丈，只听得琴声之中杂有无数鸟语，细细听来，琴声竟似和鸟语互相应答，间间关关，宛转啼鸣。只见三株大松树下一个白衣男子背向而坐，膝上放着一张焦尾琴，整自弹奏。他身周树木上停满了鸟雀，黄莺，杜鹃，喜鹊，八哥，还有许多不知其名的，和琴声或一问一答，或齐声和唱。"
  region.center = 1927
return region