local region = {}
  region.cmd = "fly mj"
  region.name = "Ã÷½Ì"
  region.id = "mj"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly mj"
      region.rooms[1].name = "Ã÷½Ì´óµî"
      region.rooms[1].zone = "Ã÷½Ì"
      region.rooms[1].id = 1830
      region.rooms[1].links = {}
        region.rooms[1].links.enter = {}
          region.rooms[1].links.enter.to = 1831
          region.rooms[1].links.enter.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 1832
          region.rooms[1].links.s.con = ""
      region.rooms[1].exits = "south|enter"
      region.rooms[1].desc = "    ×ß½øÕâÀï£¬Í»¸ĞÒ»ÕóËàÄÂÖ®Òâ£¬´óµîÖĞÊ®·Ö¿Õ¿õ£¬µî¶¥¸ßĞü°ËÕµ½ğµÆ£¬Á½ÅÔÊÇ¾«×³Åå½£ÎäÊ¿½£ÆøÉ­ÑÏ±ÆÈË¡£ÕıÖĞÉèÒ»±¦×ù£¬Ç°ÓĞÒ»µñ»¨Ì´Ä¾°¸£¬°¸Í·ÉÏ¹©×ÅÃ÷½ÌÊ¥»ğÁî¡£±¦×ùºóÁ¢ÓĞÒ»ÉÈÓñÆÁ£¬ÆÁÖĞËù»­ÕıÊÇÃ÷½ÌÊ¥»ğÍ¼£¬ÁÒÑæÖ±±ÆÈÕÔÂ¡£ó´Áú±¦×ùÉÏ¶Ë×øÒ»ÈË£¬×Å²¼ÒÂ¶øÏÔ¸ß¹ó£¬º¬Ğ¦²»Å­¶ø×ÔÍş£¬ÕıÊÇÃ÷½Ì½ÌÖ÷ÕÅÎŞ¼É¡£"
    region.rooms[2] = {}
      region.rooms[2].path = "fly mj;enter"
      region.rooms[2].name = "Ã÷½ÌÄÚÊÒ"
      region.rooms[2].zone = "Ã÷½Ì"
      region.rooms[2].id = 1831
      region.rooms[2].links = {}
        region.rooms[2].links.out = {}
          region.rooms[2].links.out.to = 1830
          region.rooms[2].links.out.con = ""
      region.rooms[2].exits = "out"
      region.rooms[2].desc = "    ÕâÀïÊÇÃ÷½ÌÄÚÊÒ¡£Ğ¡Ğ¡×ÀÇ°µÄ´°Íâ£¬Íû³öÈ¥ÊÇÁ¬ÃàÍòÀïµÄÎ¡Î¡À¥ÂØ¡£´°èùÃÅÉÈ¾ùµñÖÆµÃÃÀÂØÃÀÛ¼£¬¾«ÇÉÒì³£×ÀÇ°×ø×ÅÒ»¸öÁÁÀöÅ®º¢£¬ÄãÕ§Ò»¼û¾ªÒìËıµÄÃÀÃ²£¬²»½ûÇáÇá½Ğ³öÉùÀ´¡£"
    region.rooms[3] = {}
      region.rooms[3].path = "fly mj;s"
      region.rooms[3].name = "Ã÷½ÌÇ°µî"
      region.rooms[3].zone = "Ã÷½Ì"
      region.rooms[3].id = 1832
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 1833
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.sd = {}
          region.rooms[3].links.sd.to = 1835
          region.rooms[3].links.sd.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 1834
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 1830
          region.rooms[3].links.n.con = ""
      region.rooms[3].exits = "north|east|southdown|west"
      region.rooms[3].desc = "    ÄãÀ´µ½ÕâÀï£¬·ÅÑÛ´°ÍâÍûÈ¥£¬ÂşÂşÀ¥ÂØÑ©É½£¬¾§Ó¨ÌŞÍ¸£¬²ÔÌìºÆºÆ£¬°×ÔÆÓÆÓÆ¡£¶«·½ÎÖÒ°Ç§Àï£¬³şÌìÁÉÀ«£»Î÷Ãæ¸ßÉ½Î¡Î¡£¬åÆåÎÍòÀï¡£ÕâÀï¾ÍÊÇß³ßåÎäÁÖ°Ë°ÙÄêµÄÃ÷½Ì×Ü¶æµÄÇ°µî¡£"
    region.rooms[4] = {}
      region.rooms[4].path = "fly mj;s;e"
      region.rooms[4].name = "Ã÷½Ì¶«²àµî"
      region.rooms[4].zone = "Ã÷½Ì"
      region.rooms[4].id = 1833
      region.rooms[4].links = {}
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 1832
          region.rooms[4].links.w.con = ""
      region.rooms[4].exits = "west"
      region.rooms[4].desc = "    ÕâÀïÊÇ¶«²àµî£¬ÊÇ½Ó´ıÀ´±öµÄµØ·½¡£µîÄÚ°Ú×Å¼¸ÕÅ×À×Ó£¬×ÀÅÔÎ§·ÅÊı°ÑÒÎ×Ó¡£Ç½ÉÏĞü×Å¼¸·ù×Ö»­£¬Ç½±ßÒ»ÅÅÊé¼Ü£¬¼ÜÉÏ°ÚÂúÊé¼®¡£´°ÍâÊÇÃ£Ã£À¥ÂØÑ©É½£¬Ñ©·åÑÓÃà¡£"
    region.rooms[5] = {}
      region.rooms[5].path = "fly mj;s;w"
      region.rooms[5].name = "Ã÷½ÌÎ÷²àµî"
      region.rooms[5].zone = "Ã÷½Ì"
      region.rooms[5].id = 1834
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 1832
          region.rooms[5].links.e.con = ""
      region.rooms[5].exits = "east"
      region.rooms[5].desc = "    ÕâÀïÊÇÎ÷²àµî£¬ÊÇ½Ó´ıÀ´±öµÄµØ·½¡£µîÄÚ°Ú×Å¼¸ÕÅ×À×Ó£¬×ÀÅÔÎ§·ÅÊı°ÑÒÎ×Ó¡£Ç½ÉÏĞü×Å¼¸ÕÅÓ²¹­£¬ÉõÊÇĞÛ×³£¬ÅÔ±ß¶Ñ×ÅÒ»¶ÑÓğ¼ı¡£´°ÍâÊÇÃ£Ã£À¥ÂØÑ©É½£¬Ñ©·åÑÓÃà¡£"
    region.rooms[6] = {}
      region.rooms[6].path = "fly mj;s;sd"
      region.rooms[6].name = "´óÔº"
      region.rooms[6].zone = "Ã÷½Ì"
      region.rooms[6].id = 1835
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 1836
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 1838
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 1837
          region.rooms[6].links.w.con = ""
        region.rooms[6].links.nu = {}
          region.rooms[6].links.nu.to = 1832
          region.rooms[6].links.nu.con = ""
      region.rooms[6].exits = "south|east|northup|west"
      region.rooms[6].desc = "    Äã×ß½øÁËÃ÷½Ì×Ü¶æ¹ã³¡£¬È´·¢ÏÖÕâÀïÈËÉù¶¦·Ğ£¬ÎåÉ¢ÈËÈº¾ÛÓÚ´Ë£¬¿´À´ÓĞÒªÊÂ·¢ÉúÁË¡£À´Íù½ÌÖÚ´Ò´ÒÃ¦Ã¦¡£¹ã³¡×óÊ×ÊÇ½ÌÖÚ·¹ÌÃ£»ÓÒÊ×¾ÍÊÇ½ÌÖÚÎÅÖ®±äÉ«µÄĞÌÌÃ¡£ÏòÉÏ×ß¾ÍÊÇ¹âÃ÷¶¥Ã÷½Ì×Ü¶æÁË¡£"
    region.rooms[7] = {}
      region.rooms[7].path = "fly mj;s;sd;e"
      region.rooms[7].name = "ĞÌÌÃ"
      region.rooms[7].zone = "Ã÷½Ì"
      region.rooms[7].id = 1836
      region.rooms[7].links = {}
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 1835
          region.rooms[7].links.w.con = ""
      region.rooms[7].exits = "west"
      region.rooms[7].desc = "    Õû¸öĞÌÌÃÃÅ»§½ô±Õ£¬ÃÜ²»Í¸·ç¡£¼´±ãÊÇÔÚ°×Öç£¬Ò²ÓÌÈçºÚÒ¹Ò»°ã£¬Ã¿¸ô¼¸²½µÄÇ½ÉÏ£¬µãÈ¼×Å¼¸Ö¦Å£ÓÍ¾ŞÖò¡£ÖĞ¼äÊÇÒ»¸ö´ó»ğÅè£¬ÁÒÑæÌÚÌÚ¡£ÏÂ·½°Ú×ÅÒ»ÅÅÅÅÀÓÌú¡¢Ë®Å£Æ¤±Ş¡¢´©¿×Öñ°å¼°ÀÇÑÀ°ôµÈĞÌ¾ß¡£ËÄÖÜÕ¾ÂúÁËÊÖ³Ö±øÈĞµÄÖ´·¨½ÌÖÚ¡£ËûÃÇÕıÓÃÀä¿áµÄÑÛÉñ´òÁ¿×ÅÄã£¬ÁîÄã²»½û»ëÉí¶ßàÂÆğÀ´¡£    ÀäÇ«Ö´ÕÆÃ÷½ÌĞÌÌÃ¡£"
    region.rooms[8] = {}
      region.rooms[8].path = "fly mj;s;sd;w"
      region.rooms[8].name = "Ã÷½Ì·¹ÌÃ"
      region.rooms[8].zone = "Ã÷½Ì"
      region.rooms[8].id = 1837
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 1835
          region.rooms[8].links.e.con = ""
      region.rooms[8].exits = "east"
      region.rooms[8].desc = "    ÕâÀï±ãÊÇÃ÷½ÌµÄ·¹ÌÃ¡£°ÚÂúÁË³¤³¤µÄ²Í×ÀºÍ³¤µÊ£¬¼¸Î»ÄêÇá½ÌÖÚÕıÀ´»ØÃ¦Âµ×Å²¼ÖÃ¡£×ÀÉÏ°ÚÁË¼¸Åè¶¹¸¯£¬»¨Éú£¬Çà²ËÒÔ¼°´óÓã£¬´óÈâ£¬¼¦£¬¾ÆµÈÃÀÎ¶Ê³¡£¶«±ßµÄ×ßÀÈÍ¨Ïò¹ã³¡¡£"
    region.rooms[9] = {}
      region.rooms[9].path = "fly mj;s;sd;s"
      region.rooms[9].name = "ÌìÎ¢ÌÃ"
      region.rooms[9].zone = "Ã÷½Ì"
      region.rooms[9].id = 1838
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 1839
          region.rooms[9].links.e.con = ""
        region.rooms[9].links.sd = {}
          region.rooms[9].links.sd.to = 1841
          region.rooms[9].links.sd.con = ""
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 1840
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 1835
          region.rooms[9].links.n.con = ""
      region.rooms[9].exits = "north|east|southdown|west"
      region.rooms[9].desc = "    ÕâÀï¾ÍÊÇÃ÷½ÌµÄÌìÎ¢ÌÃ£¬ÌÃÖ÷¾ÍÊÇÍşÃûÔ¶²¨µÄÒóÒ°Íõ¡£ËûÊÇ°×Ã¼Ó¥ÍõµÄ¶À×ÓºÍ½ÌÖ÷ÕÅÎŞ¼ÉµÄ¾Ë¾Ë¡£ÌÃÄÚ³ÂÉèÏÊÀöÉİ»ª£¬ÏÔÈ»ÉõÊÇĞËÍú£¬ÍùÀ´½ÌÖÚ½ø½ø³ö³ö£¬¿´ËûÃÇ¸÷Ö´±øÈĞ£¬ËÆºõÊÇÊØ×Ü¶æµÄÎÀÊ¿¡£"
    region.rooms[10] = {}
      region.rooms[10].path = "fly mj;s;sd;s;e"
      region.rooms[10].name = "ÌìÊĞÌÃ"
      region.rooms[10].zone = "Ã÷½Ì"
      region.rooms[10].id = 1839
      region.rooms[10].links = {}
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 1838
          region.rooms[10].links.w.con = ""
      region.rooms[10].exits = "west"
      region.rooms[10].desc = "    ÄãÒ»½øÈëÃ÷½ÌµÄÌìÊĞÌÃ£¬¶ÙÊ±¸Ğµ½Ò»¹ÄËàÉ±Ö®Æø¡£½ÌÖÚ³öÈë¶¼Ê®·ÖĞ¡ĞÄ£¬Î©¿Ö¾ª¶¯ÁË×øÔÚÓÍÄ¾×ÀºóµÄÌÃÖ÷ÀîÌìÔ«¡£¼ûÄã½øÀ´ÀîÌìÔ«Ì§ÑÛ¿´ÁË¿´Äã£¬Ò»ÕÅºÜÈáºÍµÄÁ³È´Á¢ÂíÈÃÄãĞÄ¾ªÈâÌø¡£"
    region.rooms[11] = {}
      region.rooms[11].path = "fly mj;s;sd;s;w"
      region.rooms[11].name = "×ÏÎ¢ÌÃ"
      region.rooms[11].zone = "Ã÷½Ì"
      region.rooms[11].id = 1840
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 1838
          region.rooms[11].links.e.con = ""
      region.rooms[11].exits = "east"
      region.rooms[11].desc = "    ÕâÀï¾ÍÊÇÃ÷½ÌµÄ×ÏÎ¢ÌÃ£¬ÌÃÉÏµÄ´óØÒÉÏ \"×ÏÎ¢¹áÈÕ\" ËÄ×Ö²¢²»ÒòÌÃÖ÷ÒóËØËØÔçÊÅ¶øÓĞË¿ºÁ¼õÉ«¡£ÌÃÖĞ³ÂÉèÒ»ÈçÍùÎô¡£"
    region.rooms[12] = {}
      region.rooms[12].path = "fly mj;s;sd;s;sd"
      region.rooms[12].name = "Õ»µÀ"
      region.rooms[12].zone = "Ã÷½Ì"
      region.rooms[12].id = 1841
      region.rooms[12].links = {}
        region.rooms[12].links.nu = {}
          region.rooms[12].links.nu.to = 1838
          region.rooms[12].links.nu.con = ""
        region.rooms[12].links.sd = {}
          region.rooms[12].links.sd.to = 1842
          region.rooms[12].links.sd.con = ""
      region.rooms[12].exits = "northup|southdown"
      region.rooms[12].desc = "    ÕâÀïÊÇÍ¨ÍùÃ÷½ÌµÄÕ»µÀ£¬½ÅÏÂÃ¯ÁÖÉúÔÆ£¬¼«Æä¼èÏÕ¡£    Ô¶Ô¶¿´µ½ÉÏÍ·¾ÍÊÇÃ÷½ÌÄÚÈıÌÃÃÀÂØÃÀÛ¼µÄ·ÉéÜ»­¶°ÁË¡£"
    region.rooms[13] = {}
      region.rooms[13].path = "fly mj;s;sd;s;sd;sd"
      region.rooms[13].name = "Õ»µÀ"
      region.rooms[13].zone = "Ã÷½Ì"
      region.rooms[13].id = 1842
      region.rooms[13].links = {}
        region.rooms[13].links.nu = {}
          region.rooms[13].links.nu.to = 1841
          region.rooms[13].links.nu.con = ""
        region.rooms[13].links.sd = {}
          region.rooms[13].links.sd.to = 1843
          region.rooms[13].links.sd.con = ""
      region.rooms[13].exits = "northup|southdown"
      region.rooms[13].desc = "    ÕâÀïÊÇÍ¨ÍùÃ÷½ÌµÄÕ»µÀ£¬½ÅÏÂÃ¯ÁÖÉúÔÆ£¬¼«Æä¼èÏÕ¡£"
    region.rooms[14] = {}
      region.rooms[14].path = "fly mj;s;sd;s;sd;sd;sd"
      region.rooms[14].name = "ÁÒ»ğÆìºóÃÅ"
      region.rooms[14].zone = "Ã÷½Ì"
      region.rooms[14].id = 1843
      region.rooms[14].links = {}
        region.rooms[14].links.nu = {}
          region.rooms[14].links.nu.to = 1842
          region.rooms[14].links.nu.con = ""
        region.rooms[14].links.sd = {}
          region.rooms[14].links.sd.to = 1844
          region.rooms[14].links.sd.con = ""
      region.rooms[14].exits = "northup|southdown"
      region.rooms[14].desc = "    ÕâÀï¾ÍÊÇÁÒ»ğÆìµÄºóÃÅ£¬ºóÃæ¾ÍÊÇÃ÷½Ì×Ü¶æËùÔÚ£¬ÃÅÓîĞù´ó£¬½ÌÖÚ³öÈë·×·×¡£ÓÉÓÚµØ´¦½ôÒª£¬ÕâÀïµÄ¹Ø·ÀÒ²ºÜÑÏÃÜ¡£"
    region.rooms[15] = {}
      region.rooms[15].path = "fly mj;s;sd;s;sd;sd;sd;sd"
      region.rooms[15].name = "´óÔº"
      region.rooms[15].zone = "Ã÷½Ì"
      region.rooms[15].id = 1844
      region.rooms[15].links = {}
        region.rooms[15].links.enter = {}
          region.rooms[15].links.enter.to = 1847
          region.rooms[15].links.enter.con = ""
        region.rooms[15].links.out = {}
          region.rooms[15].links.out.to = 1848
          region.rooms[15].links.out.con = ""
        region.rooms[15].links.nu = {}
          region.rooms[15].links.nu.to = 1843
          region.rooms[15].links.nu.con = ""
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 1846
          region.rooms[15].links.w.con = ""
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 1845
          region.rooms[15].links.e.con = ""
      region.rooms[15].exits = "east|enter|northup|out|west"
      region.rooms[15].desc = "    Äã×ß½øÁËÁÒ»ğÆìµÄ´óÔº£¬È´·¢ÏÖÕâÀïÈËÉù¶¦·Ğ£¬ÁÒ»ğ½ÌÖÚÓĞµÄÔÚ°á»ğÒ©£¬ÓĞµÄÔÚÁ¶Ê¯ÓÍ£¬ÕæÊÇÈÈ»ğ³¯Ìì¡£Ôº×Ó×óÊ×¿ÉÄÜÊÇÁ·Îä³¡£¬ÒşÔ¼´«À´´ò¶·Éù£»ÓÒÊ×ÊÇÒ»×ù´óÌü£¬ÏóÊÇÁÒ»ğÆìµÄÒé»á³¡Ëù¡£ÏòÉÏ×ß¾ÍÊÇ¹âÃ÷¶¥Ã÷½Ì×Ü¶æÁË¡£"
    region.rooms[16] = {}
      region.rooms[16].path = "fly mj;s;sd;s;sd;sd;sd;sd;e"
      region.rooms[16].name = "ÁÒ»ğÆì´óÌü"
      region.rooms[16].zone = "Ã÷½Ì"
      region.rooms[16].id = 1845
      region.rooms[16].links = {}
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 1844
          region.rooms[16].links.w.con = ""
      region.rooms[16].exits = "west"
      region.rooms[16].desc = "    ÕâÀïÊÇÁÒ»ğÆìµÄ´óÌü£¬ÌüÖĞºìÆìÕĞÕ¹£¬µ¶Ç¹Ó³Ñª£¬½ÌÖÚç­ÒÂ³àÃ±£¬ÍÅÍÅÓµ×¡ÁÒ»ğÆìÕÆÆìÊ¹ĞÁÈ»¡£"
    region.rooms[17] = {}
      region.rooms[17].path = "fly mj;s;sd;s;sd;sd;sd;sd;w"
      region.rooms[17].name = "Á·Îä³¡"
      region.rooms[17].zone = "Ã÷½Ì"
      region.rooms[17].id = 1846
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 1844
          region.rooms[17].links.e.con = ""
      region.rooms[17].exits = "east"
      region.rooms[17].desc = "    ×ß½øÁËÁÒ»ğÆìµÄÁ·Îä³¡£¬·¢ÏÖÁ·ÎäµÄ½ÌÖÚÃÇ²¢²»ÊÇÔÚÏà»¥ÇĞ´èÎä¹¦£¬¶øÊÇ´©´÷×ÅÌØÖÆµÄ·À»ğ»¤¾ß£¬ÔÚÑ§Ï°Ê¹ÓÃ»ğ¾ßºÍÃé×¼¡£»ğ¾ßÖĞÅç³ö÷îºÚµÄÔ­ÓÍ£¬¼û»ğ¼´È¼£¬ÍşÁ¦ÎŞ±È¡£"
    region.rooms[18] = {}
      region.rooms[18].path = "fly mj;s;sd;s;sd;sd;sd;sd;enter"
      region.rooms[18].name = "Ò½¾Ó"
      region.rooms[18].zone = "Ã÷½Ì"
      region.rooms[18].id = 1847
      region.rooms[18].links = {}
        region.rooms[18].links.out = {}
          region.rooms[18].links.out.to = 1844
          region.rooms[18].links.out.con = ""
      region.rooms[18].exits = "out"
      region.rooms[18].desc = "    Äã×ß½øÁËÁÒ»ğÆìµÄ´óÔººó½ø£¬ÕâÀïÊÇ¸öºÜÄş¾²µÄĞ¡Îİ¡£ËÄÖÜ°ÚÁË²»ÉÙÒ½Ñ§µä¼®£¬»¹ÓĞºÜ¶àÉ¢Âä¶Ñ·ÅµÄ¸à¡¢Íè¡¢É¢µÈ¡£Ò»¸öÀÏÍ·ÔÚ´Ë´ô´ô³öÉñ£¬ËÆºõÓĞÎŞÏŞĞÄÊÂ¡£"
    region.rooms[19] = {}
      region.rooms[19].path = "fly mj;s;sd;s;sd;sd;sd;sd;out"
      region.rooms[19].name = "ÁÒ»ğÆì´óÃÅ"
      region.rooms[19].zone = "Ã÷½Ì"
      region.rooms[19].id = 1848
      region.rooms[19].links = {}
        region.rooms[19].links.enter = {}
          region.rooms[19].links.enter.to = 1844
          region.rooms[19].links.enter.con = ""
        region.rooms[19].links.sd = {}
          region.rooms[19].links.sd.to = 1849
          region.rooms[19].links.sd.con = ""
      region.rooms[19].exits = "enter|southdown"
      region.rooms[19].desc = "    ÕâÀïÊÇÃ÷½ÌÁÒ»ğÆìµÄ´óÃÅ£¬×¯ÑÏ¹ÅÆÓ£¬ÃÅÇ°¶Ô²åËÄÃæÏâºì·ÉÁúÆì¡£½ğÉ«ÃÅ¶¤¿ÛÔÚ»ğÆáºìÃÅÉÏ£¬·ÖÍâ¾«Éñ¡£Ò²ÊÇÍ¨ÍùÃ÷½Ì×Ü¶æµÄ±Ø¾­Ö®µØ¡£ËùÒÔÀ´ÍùµÄÈËÒ²ÌØ±ğ¶à¡£"
    region.rooms[20] = {}
      region.rooms[20].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd"
      region.rooms[20].name = "ÁÒ»ğÆìÅÆ·»"
      region.rooms[20].zone = "Ã÷½Ì"
      region.rooms[20].id = 1849
      region.rooms[20].links = {}
        region.rooms[20].links.ne = {}
          region.rooms[20].links.ne.to = 1850
          region.rooms[20].links.ne.con = ""
        region.rooms[20].links.sd = {}
          region.rooms[20].links.sd.to = 1889
          region.rooms[20].links.sd.con = ""
        region.rooms[20].links.nw = {}
          region.rooms[20].links.nw.to = 1870
          region.rooms[20].links.nw.con = ""
        region.rooms[20].links.nu = {}
          region.rooms[20].links.nu.to = 1848
          region.rooms[20].links.nu.con = ""
      region.rooms[20].exits = "northwest|northup|southdown|northeast"
      region.rooms[20].desc = "    ÕâÀïÊÇÀ¥ÂØÉ½ÄÏÂ´µÄÒ»Æ¬¿ªÀ«µØ£¬ËÄÖÜÉ½ÑÂ»·±§£¬ÇàÄ¾ÕÚÌì£¬Õı¶ÔÂ·ÖĞµÄÊÇÒ»×ù´óºìÅÆ·»¡£´©¹ıÅÆ·»£¬ÊÇÒ»Æ¬ºì×©ºìÍß£¬±é²åÏâºìÍÅÁúÆì£¬Â·±ßÆëÆëÕ¾Á¢Á½ÅÅ½ÌÖÚ£¬Õû¸öÉ½¹ÈÖĞºÃËÆÁÒÑæÕôÌÚ£¬ºìÎí±éÒ°£¬ÊµÔÚÊÇ½­ºşÖĞÒ»°ãÃÅÅÉËùÃ»ÓĞµÄ×³¹Û¾°Ïó¡£ÓÉ´ËÏò¶«±±ÕÛ×ª£¬´óÂ·Ö±Í¨Èñ½ğÆì£»ÓÉ´ËÏòÎ÷±±¶øĞĞ£¬ÔòÎª¾ŞÄ¾Æì¡£ÈıÆì³Ğê÷½Ç¶¦Á¢Ö®ÊÆ£¬ÒÔ¹®¹ÌÃ÷½ÌÍâÎ§¡£"
    region.rooms[21] = {}
      region.rooms[21].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne"
      region.rooms[21].name = "ÇàÊ¯´óµÀ"
      region.rooms[21].zone = "Ã÷½Ì"
      region.rooms[21].id = 1850
      region.rooms[21].links = {}
        region.rooms[21].links.ne = {}
          region.rooms[21].links.ne.to = 1851
          region.rooms[21].links.ne.con = ""
        region.rooms[21].links.sw = {}
          region.rooms[21].links.sw.to = 1849
          region.rooms[21].links.sw.con = ""
      region.rooms[21].exits = "northeast|southwest"
      region.rooms[21].desc = "    ÕâÀïÊÇÍ¨ÍùÈñ½ğÆìµÄ´óµÀ¡£µÀÂ·¿ªÀ«£¬´ó¸Å¿ÉÈİÊ®ÈË²¢¼ç¶øĞĞ¡£Ïà´«Èñ½ğÆìÊÇÃ÷½ÌÎåÆìÖĞ³ÉÁ¢×îÔç£¬¹æÄ£×îÎªºêÎ°µÄ¡£°ÙÄêÀ´ÈË²Å±²³ö£¬³ıÁËÊØ»¤Ã÷½ÌÍâÎ§£¬»¹¸ºÔğÃ÷½ÌÖĞËùÓĞ±øÆ÷ºÍ»¤¾ßµÄ´òÔì¡£"
    region.rooms[22] = {}
      region.rooms[22].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne"
      region.rooms[22].name = "ÇàÊ¯´óµÀ"
      region.rooms[22].zone = "Ã÷½Ì"
      region.rooms[22].id = 1851
      region.rooms[22].links = {}
        region.rooms[22].links.ne = {}
          region.rooms[22].links.ne.to = 1852
          region.rooms[22].links.ne.con = ""
        region.rooms[22].links.sw = {}
          region.rooms[22].links.sw.to = 1850
          region.rooms[22].links.sw.con = ""
      region.rooms[22].exits = "northeast|southwest"
      region.rooms[22].desc = "    ÕâÀï´óµÀÆ½Ì¹£¬µØÊÆ¿ªÀ«£¬Á½ÅÔÊ÷ÁÖÖĞÄñÓï»¨Ïã£¬Ò»Æ¬ºÍÆ½°²ÏéµÄÆø·Õ¡£´ËÊ±ÓÖÓĞË­ÄÜÏëµ½£¬ÕâÌõ´óµÀÉÏÈöÏÂ¹ı¶àÉÙ½­ºşÖĞÈËµÄÑª£¬ÕâÆ¬ÁÖÖĞÓÖÂñÓĞ¶àÉÙ²ÒËÀÓÚÎäÁÖÕù¶·µÄÔ©»êµÄ¹Ç¡£Ô¶´¦£¬ÒşÔ¼´«À´¶£¶£ßËßËµÄ´òÌúÉù£¬Å¼¶ûÄÜÈÃÈË×·ÒäÆğµ¶¸êÌúÂíµÄÉ³³¡¾°Ïó¡£"
    region.rooms[23] = {}
      region.rooms[23].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne"
      region.rooms[23].name = "ÇàÊ¯´óµÀ"
      region.rooms[23].zone = "Ã÷½Ì"
      region.rooms[23].id = 1852
      region.rooms[23].links = {}
        region.rooms[23].links.sw = {}
          region.rooms[23].links.sw.to = 1851
          region.rooms[23].links.sw.con = ""
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 1853
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.nw = {}
          region.rooms[23].links.nw.to = 1860
          region.rooms[23].links.nw.con = ""
      region.rooms[23].exits = "northwest|west|southwest"
      region.rooms[23].desc = "    ´óÂ·ÒÑ¾­ÑÓÉìµ½ÁË¾¡Í·£¬Î÷Ê×·½ÏòÒ»×ùÃÅÂ¥¸ßËÊ£¬ÃÅÇ°ÓĞÊ®¼¸¸ö½ğÒÂÈËÍù·µÑ²Âß£¬ÆøÊÆÉ­ÑÏ¡£ÃÅÂ¥Á½ÅÔ²¢²åÏâ½ğÇàÁúÆì£¬Ó­·çÕĞÕ¹£¬ÁÒÁÒÉúÍş¡£ºìÉ«´óÃÅ½ô±Õ£¬²»Ê±ÓĞ½ÌÖÚ´Ó²àĞ¡ÃÅ½ø³ö£¬Ò²±»ÅÌ²éµÃ½ô¡£ÏòÎ÷±±¶øĞĞ£¬ÊÇÈ¥ºéË®ÆìµÄÂ·£¬¶øÎ÷ÄÏ·½ÏòÔòÍ¨ÍùÁÒ»ğÆì¡£"
    region.rooms[24] = {}
      region.rooms[24].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;w"
      region.rooms[24].name = "²àÃÅ"
      region.rooms[24].zone = "Ã÷½Ì"
      region.rooms[24].id = 1853
      region.rooms[24].links = {}
        region.rooms[24].links.e = {}
          region.rooms[24].links.e.to = 1852
          region.rooms[24].links.e.con = ""
        region.rooms[24].links.enter = {}
          region.rooms[24].links.enter.to = 1854
          region.rooms[24].links.enter.con = ""
      region.rooms[24].exits = "east|enter"
      region.rooms[24].desc = "    ÕâÊÇÈñ½ğÆìµÄÒ»¸ö²àÃÅ£¬´ó¸ÅÖ»ÈİµÃÏÂÒ»¸öÈË½ø³ö£¬Ã¿¸ö½ÌÖÚµ½´Ë£¬¶¼±ØĞë³öÊ¾Ò»ÕÅÑüÅÆ£¬²Å¿É½øÈë¡£"
    region.rooms[25] = {}
      region.rooms[25].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;w;enter"
      region.rooms[25].name = "´óÔº"
      region.rooms[25].zone = "Ã÷½Ì"
      region.rooms[25].id = 1854
      region.rooms[25].links = {}
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 1859
          region.rooms[25].links.n.con = ""
        region.rooms[25].links.s = {}
          region.rooms[25].links.s.to = 1858
          region.rooms[25].links.s.con = ""
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 1855
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.out = {}
          region.rooms[25].links.out.to = 1853
          region.rooms[25].links.out.con = ""
      region.rooms[25].exits = "south|north|out|west"
      region.rooms[25].desc = "    Äã×ß½øÁËÈñ½ğÆìµÄ´óÔº£¬È´·¢ÏÖÕâÀïÈËÓ°Ï¡Êè£¬ËäÌı¼û¶£¶£ßËßËµÄ´òÌúÉù£¬È´¼û²»µ½´òÌúÆÌ£¬ÄÇÉùÒôËÆºõÊÇ´ÓÉîÔ¶µÄµØÏÂ´«À´µÄ¡£ÏòÎ÷×ß£¬¾ÍÒª½øÈëÃÅÂ¥ÁË¡£Ôº×Ó×óÊ×¿ÉÄÜÊÇÁ·Îä³¡£¬ÒşÔ¼´«À´´ò¶·Éù£»ÓÒÊ×ÊÇÒ»×ù´óÌü£¬ÏóÊÇÈñ½ğÆìµÄÒé»á³¡Ëù¡£"
    region.rooms[26] = {}
      region.rooms[26].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;w;enter;w"
      region.rooms[26].name = "ÃÅÂ¥Ò»²ã"
      region.rooms[26].zone = "Ã÷½Ì"
      region.rooms[26].id = 1855
      region.rooms[26].links = {}
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 1854
          region.rooms[26].links.e.con = ""
        region.rooms[26].links.u = {}
          region.rooms[26].links.u.to = 1856
          region.rooms[26].links.u.con = ""
      region.rooms[26].exits = "up|east"
      region.rooms[26].desc = "    ÕâÀïÊÇÒ»¼ä´óÊ¯ÊÒ£¬Ê¯ÊÒËÄÖÜÕûÆëµÄÂëÖÃ×Å±øÆ÷¼Ü£¬Ê®°Ë°ã±øÆ÷ÑùÑù¾ãÈ«¡£¼¸¸ö½ÌÖÚÔÚÊÒÖĞÑ²Âß£¬ºÃÏóÊÇÊØ»¤±øÆ÷µÄ¡£ÓÒÃæÓĞÒ»ÌõÊ¯ÌİÖ±Í¨Â¥ÉÏ¡£"
    region.rooms[27] = {}
      region.rooms[27].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;w;enter;w;u"
      region.rooms[27].name = "ÃÅÂ¥¶ş²ã"
      region.rooms[27].zone = "Ã÷½Ì"
      region.rooms[27].id = 1856
      region.rooms[27].links = {}
        region.rooms[27].links.u = {}
          region.rooms[27].links.u.to = 1857
          region.rooms[27].links.u.con = ""
        region.rooms[27].links.d = {}
          region.rooms[27].links.d.to = 1855
          region.rooms[27].links.d.con = ""
      region.rooms[27].exits = "up|down"
      region.rooms[27].desc = "    ÕâÀïÊÇÒ»¼ä´óÊ¯ÊÒ£¬´ÓÊ¯´°ÏòÍâ¿´È¥£¬Õû¸öÔºÂäÒ»ÀÀÎŞÓà£¬ÕâÀïÕıÊÇÒ»´¦Ò×ÊØÄÑ¹¦µÄ½ôÒª¹Ø°¯¡£ÓÒÃæÓĞÒ»ÌõÊ¯ÌİÖ±Í¨Â¥ÉÏ¡£"
    region.rooms[28] = {}
      region.rooms[28].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;w;enter;w;u;u"
      region.rooms[28].name = "ÃÅÂ¥Èı²ã"
      region.rooms[28].zone = "Ã÷½Ì"
      region.rooms[28].id = 1857
      region.rooms[28].links = {}
        region.rooms[28].links.d = {}
          region.rooms[28].links.d.to = 1856
          region.rooms[28].links.d.con = ""
      region.rooms[28].exits = "down"
      region.rooms[28].desc = "    ÕâÀïÊÇÒ»¼ä´óÊ¯ÊÒ£¬ÖĞÑë°Ú·Å×ÅÊ¯×À(zhuo)Ê¯ÒÎ(chair)£¬Ê¯×ÀÉÏ¿ÌÓĞ×İºá½»´íµÄÍ¼°¸£¬×ĞÏ¸¿´£¬Ô­À´ÊÇÒ»Æå¾Ö£¬ÆåÅÌÉÏÁ½ºÚ(heizi)¡¢Ò»°×(bai zi)£¬Õı¸Ã°×·½Âä×ÓÁË¡£È´²»Öª¶ÔŞÄµÄÆåÊ¿ÎªºÎÃ»ÓĞÏÂÍê¡£"
    region.rooms[29] = {}
      region.rooms[29].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;w;enter;s"
      region.rooms[29].name = "Á·Îä³¡"
      region.rooms[29].zone = "Ã÷½Ì"
      region.rooms[29].id = 1858
      region.rooms[29].links = {}
        region.rooms[29].links.n = {}
          region.rooms[29].links.n.to = 1854
          region.rooms[29].links.n.con = ""
      region.rooms[29].exits = "north"
      region.rooms[29].desc = "    ×ß½øÁËÈñ½ğÆìµÄÁ·Îä³¡£¬·¢ÏÖÕâÀïÓĞĞ©Ææ¹Ö¡£Á·ÎäµÄ½ÌÖÚÃÇ²¢²»ÊÇÔÚÏà»¥ÇĞ´è£¬¶øÊÇ´©´÷×ÅÌØÖÆµÄ»¤¾ß£¬Í¬Ò»¼ÜÆæ¹ÖµÄ×°ÖÃ´ò¶·¡£×°ÖÃ´Ó²»ÒÆ¿ªÔ­µØ£¬Ö»ÊÇËüËÆºõ¾ß±¸ÓÃ²»ÍêµÄ¸÷ÖÖ±øÆ÷£¬½ø¹¥ÆğÀ´Ë¿ºÁ²»ÈõÓÚ½­ºşºÃÊÖ¡£"
    region.rooms[30] = {}
      region.rooms[30].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;w;enter;n"
      region.rooms[30].name = "Èñ½ğÆì´óÌü"
      region.rooms[30].zone = "Ã÷½Ì"
      region.rooms[30].id = 1859
      region.rooms[30].links = {}
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 1854
          region.rooms[30].links.s.con = ""
      region.rooms[30].exits = "south"
      region.rooms[30].desc = "    ÕâÊÇÈñ½ğÆìµÄ´óÌü£¬ËäÈ»¶¼ÊÇÁ·ÎäÖ®ÈË£¬ÕâÀïÈ´²¼ÖÃµÃ¹ÅÉ«¹ÅÏã£¬ÏÔ³öÈñ½ğÆìµÄÓëÖÚ²»Í¬¡£´óÌüÕıÃæ¸ßĞüÒ»¿éÅÆØÒ£¬ÉÏÊéËÄ¸öÌÌ½ğ´ó×Ö¡°ÈñÆø½ğ·ç¡±£¬Ò»°Ù¶şÊ®ÄêÇ°£¬Ã÷½ÌÓëÀ´·¸µÄÃÉ¹Å¾ü¶ÓÒ»³¡÷éÕ½£¬Èñ½ğÆìÁ¦ÊØĞşÌìÑÂ£¬ËÀÕß°Ë¡¢¾Å£¬½ÌÖ÷Ç×Êé´ËØÒÒÔÀø½ÌÖÚ£¬Èñ½ğÆìÒÔ´ËÎªÎåÆìÖ®Ê×¡£ÌüÖĞÑë°ÚÓĞ²è¼¸£¬Èñ½ğÆìÕÆÆìÊ¹×¯ï£Õı½ó¶ø×ø£¬ÕıÔÚ¶ÁÒ»±¾Êé¾í¡£"
    region.rooms[31] = {}
      region.rooms[31].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw"
      region.rooms[31].name = "É½Â·"
      region.rooms[31].zone = "Ã÷½Ì"
      region.rooms[31].id = 1860
      region.rooms[31].links = {}
        region.rooms[31].links.nw = {}
          region.rooms[31].links.nw.to = 1861
          region.rooms[31].links.nw.con = ""
        region.rooms[31].links.se = {}
          region.rooms[31].links.se.to = 1852
          region.rooms[31].links.se.con = ""
      region.rooms[31].exits = "northwest|southeast"
      region.rooms[31].desc = "    ÕâÀïÊÇÒ»ÌõºÜÆÕÍ¨µÄÉ½Â·£¬Â·±ßµÄÊ÷ÁÖÃÜ¼¯£¬·¼²İÁ÷Ïã£¬²İ´ÔÖĞĞÇĞÇµãµãµØµã×º×ÅÒ»Ğ©°×É«Ò°»¨£¬Ò»¹ÉÇåÈª¶£¶£ßËßËµØÏòÉ½ÏÂÁ÷ÌÊ£¬Ô¶´¦´«À´ÕóÕóË®Éù£¬ÎªÕâÉ½¹È¶¸ÔöÁË¼¸·ÖÆøÊÆ¡£"
    region.rooms[32] = {}
      region.rooms[32].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw"
      region.rooms[32].name = "É½Â·"
      region.rooms[32].zone = "Ã÷½Ì"
      region.rooms[32].id = 1861
      region.rooms[32].links = {}
        region.rooms[32].links.n = {}
          region.rooms[32].links.n.to = 1863
          region.rooms[32].links.n.con = ""
        region.rooms[32].links.nw = {}
          region.rooms[32].links.nw.to = 1862
          region.rooms[32].links.nw.con = ""
        region.rooms[32].links.se = {}
          region.rooms[32].links.se.to = 1860
          region.rooms[32].links.se.con = ""
      region.rooms[32].exits = "north|northwest|southeast"
      region.rooms[32].desc = "    ÕâÀïµØÊÆºÜ¶¸ÇÍ£¬Ïò±±ÊÇÒ»ÌõÁ¬ÃàÊıÊ®ÀïµÄÉ½¹È£¬ÏòÄÏ×ß£¬ÔòÊÇÈ¥Ã÷½ÌÈñ½ğÆì·½ÏòµÄÂ·¡£Â·Á½ÅÔ·äÎèµûÓ°£¬É½»¨ÀÃÂş£¬ºÃÒ»ÅÉÒ°µØ·ç¹â¡£µ«¾ÍÔÚÄÇ´ÔÁÖÉî´¦£¬µü´äÖ®ÖĞ£¬ÓÖÈÃÈË²»¾õ¸ĞÊÜµ½Ò»ÕóÏôÉªµÄº®Òâ¡£"
    region.rooms[33] = {}
      region.rooms[33].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw;nw"
      region.rooms[33].name = "É½Â·"
      region.rooms[33].zone = "Ã÷½Ì"
      region.rooms[33].id = 1862
      region.rooms[33].links = {}
        region.rooms[33].links.se = {}
          region.rooms[33].links.se.to = 1861
          region.rooms[33].links.se.con = ""
      region.rooms[33].exits = "southeast"
      region.rooms[33].desc = "    ÕâÀï¿ì½Ó½ü¹ÈµÍÁË£¬µ«±±ÃæÆÙ²¼µ²×¡ÁËÈ¥Â·¡£ÆÙ²¼ÈçÒ»Æ¥ÒøÁ·±¼Á÷¶øÏÂ£¬ÇãĞºÔÚÒ»ÉîÌ¶Ö®ÖĞ£¬Ë®ÉùºäÃù£¬Á±ÎíÖ±ÉÏÖØÏö¡£Á½ÅÔÉ½Ê¯¸ßËÊ£¬¶¸±Ú¶ÏÑÂ£¬ÏóÊÇÈË¹¤Åü¾Í¶ø³É¡£ÉîÌ¶Ç°µÄÇàÊ¯±»Ä¥µÃï­ÁÁ£¬ºÃÏó×ÜÓĞÈËÔÚÕâÀïÀ´Íù¡£"
    region.rooms[34] = {}
      region.rooms[34].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw;n"
      region.rooms[34].name = "É½Â·"
      region.rooms[34].zone = "Ã÷½Ì"
      region.rooms[34].id = 1863
      region.rooms[34].links = {}
        region.rooms[34].links.s = {}
          region.rooms[34].links.s.to = 1861
          region.rooms[34].links.s.con = ""
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 1864
          region.rooms[34].links.n.con = ""
      region.rooms[34].exits = "south|north"
      region.rooms[34].desc = "    É½Â·µ½ÕâÀïËÆºõ±äµÃ¿íÀ«ÁËĞ©¡£ÇåĞÂµÄÉ½·çÆËÃæ¶øÀ´£¬ÁîÈË¾«Éñ¶ÙÎªÒ»Ë¬¡£Ô¶´¦´«À´äÈäÈË®Éù£¬½¥ĞĞ½¥Ô¶¡£É½±ÚÉÏ¹ÒÂúÁËºñÃÜµÄÌÙÂÜ£¬Ëæ·çÇáÇáÒ¡ß®¡£"
    region.rooms[35] = {}
      region.rooms[35].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw;n;n"
      region.rooms[35].name = "É½Â·"
      region.rooms[35].zone = "Ã÷½Ì"
      region.rooms[35].id = 1864
      region.rooms[35].links = {}
        region.rooms[35].links.s = {}
          region.rooms[35].links.s.to = 1863
          region.rooms[35].links.s.con = ""
        region.rooms[35].links.n = {}
          region.rooms[35].links.n.to = 1865
          region.rooms[35].links.n.con = ""
      region.rooms[35].exits = "south|north"
      region.rooms[35].desc = "    Ë®ÉùÔ½À´Ô½´ó£¬É½¼ä³äÂúÁËÅ¨Å¨µÄË®Æø¡£É½Â·ÉÏ£¬¶ÏÁÑµÄÉ½Ï¶ÖĞ£¬¶¼Á÷³öÒ»µÀµÀÏ¸Ï¸µÄÈªË®£¬»ã³ÉÒ»¹É³Î±ÌµÄĞ¡Ïª£¬ÏòÉ½ÏÂòêÑÑÁ÷È¥¡£ÖÜÎ§ÂÌÒâµ´Ñú£¬ÄñÓïğĞÉù£¬ÈçÖÃÉíÏÉ¾³¡£"
    region.rooms[36] = {}
      region.rooms[36].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw;n;n;n"
      region.rooms[36].name = "É½Â·"
      region.rooms[36].zone = "Ã÷½Ì"
      region.rooms[36].id = 1865
      region.rooms[36].links = {}
        region.rooms[36].links.s = {}
          region.rooms[36].links.s.to = 1864
          region.rooms[36].links.s.con = ""
        region.rooms[36].links.n = {}
          region.rooms[36].links.n.to = 1866
          region.rooms[36].links.n.con = ""
      region.rooms[36].exits = "south|north"
      region.rooms[36].desc = "    Ò»¹Ò¾Ş´óµÄÆÙ²¼°×Áú³öÏö°ãºáÔ½É½¼ä£¬Ë®ÆøÒÑÅ¨µÃ·Â·ğ¿ÉÒÔµÎÏÂË®Öé¶ùÀ´¡£É½ÂÍ¼äÉıÆğ±¡±¡µÄÇàÎí£¬Äı¾Û²»É¢¡£»©»©µÄË®ÉùÕğ¶úÓûÁû¡£"
    region.rooms[37] = {}
      region.rooms[37].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw;n;n;n;n"
      region.rooms[37].name = "É½Â·"
      region.rooms[37].zone = "Ã÷½Ì"
      region.rooms[37].id = 1866
      region.rooms[37].links = {}
        region.rooms[37].links.s = {}
          region.rooms[37].links.s.to = 1865
          region.rooms[37].links.s.con = ""
        region.rooms[37].links.n = {}
          region.rooms[37].links.n.to = 1867
          region.rooms[37].links.n.con = ""
      region.rooms[37].exits = "south|north"
      region.rooms[37].desc = "    ÕâÀïÊÇÆÙ²¼ÉÏ·½Ò»µÀÕ­Õ­µÄÉ½Áº£¬»ëÈ»Ìì³É¡£Ê¯ÁºÉÏÃæÈË¹¤Ôä³öÒ»¸ñ¸ñ½×Ìİ¡£±ßÉÏ¶¤ÁË¼¸¿ÃÄ¾×®£¬ÈÆÉÏ´Ö³¤µÄÂéÉş×÷Îª·öÊÖ¡£ÆÙ²¼ÔÚ½ÅÏÂ±¼ÌÚ¶ø¹ı£¬É½½ÅÏÂ»ã³ÉÒ»¸öÉîÌ¶¡£"
    region.rooms[38] = {}
      region.rooms[38].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw;n;n;n;n;n"
      region.rooms[38].name = "ºéË®Æì´óÃÅ"
      region.rooms[38].zone = "Ã÷½Ì"
      region.rooms[38].id = 1867
      region.rooms[38].links = {}
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 1866
          region.rooms[38].links.s.con = ""
        region.rooms[38].links.enter = {}
          region.rooms[38].links.enter.to = 1868
          region.rooms[38].links.enter.con = ""
      region.rooms[38].exits = "south|enter"
      region.rooms[38].desc = "    ÕâÀïÊÇÃ÷½ÌºéË®ÆìµÄ´óÃÅ, ×¯ÑÏ¹ÅÆÓ, ÃÅÇ°¶Ô²åËÄÃæÏâÀ¶ó´ÁúÆìÃÅÇ°Ë®Éùäıäı, È´ÊÇÒ»ÌõË®Á÷´ÓÃÅÏÂÁ÷³ö, ÕıÊÇÆÙ²¼µÄÉÏÔ´,Ô­À´, Õû¸öºéË®Æì¾Í½¨ÖşÔÚÕâÌõĞ¡ºÓÖ®ÉÏ."
    region.rooms[39] = {}
      region.rooms[39].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw;n;n;n;n;n;enter"
      region.rooms[39].name = "ºéË®Æì³¤ÀÈ"
      region.rooms[39].zone = "Ã÷½Ì"
      region.rooms[39].id = 1868
      region.rooms[39].links = {}
        region.rooms[39].links.n = {}
          region.rooms[39].links.n.to = 1869
          region.rooms[39].links.n.con = ""
        region.rooms[39].links.out = {}
          region.rooms[39].links.out.to = 1867
          region.rooms[39].links.out.con = ""
      region.rooms[39].exits = "north|out"
      region.rooms[39].desc = "    ÄãÕı×ßÔÚÒ»Ìõ³¤ÀÈÖ®ÉÏ, ³¤ÀÈòêÑÑÇúÕÛ, Á½ÅÔÊÇÈç»­¾°Ïó. Ğ¡ºÓ´ÓÀÈÏÂ¾²¾²Á÷ÌÊ, ºÓÃæÖ®ÉÏÆ®¸¡×Åµ­µ­µÄÇáÑÌ, ÈçÎíÈçÉ´.µ«ºÓÃæÉÏÓÖ¾²µÃÈÃÈËÆæ¹Ö, ËÆºõÃ»ÓĞÒ»µãÉúÆø."
    region.rooms[40] = {}
      region.rooms[40].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;ne;ne;ne;nw;nw;n;n;n;n;n;enter;n"
      region.rooms[40].name = "ºéË®Æì´óÌü"
      region.rooms[40].zone = "Ã÷½Ì"
      region.rooms[40].id = 1869
      region.rooms[40].links = {}
        region.rooms[40].links.s = {}
          region.rooms[40].links.s.to = 1868
          region.rooms[40].links.s.con = ""
      region.rooms[40].exits = "south"
      region.rooms[40].desc = "    ÕâÀïÊÇºéË®ÆìµÄ´óÌü£¬ÌüÖĞËÄ±ÚÆáÄ«£¬Á¬×À°¸Ì¨ÒÎ¾ãÎªºÚÉ«£¬Ç¹Ò·ºÚÓ§£¬½£´¹ĞşËë£¬²¼ÖÃµÃÀäÄ®É­ÑÏ¡£ÌüÖĞÑë°ÚÓĞ²è¼¸£¬ºéË®ÆìÕÆÆìÊ¹ÌÆÑóÕı½ó¶ø×ø£¬Ãæ´øÉ±Æø¡£"
    region.rooms[41] = {}
      region.rooms[41].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw"
      region.rooms[41].name = "ÇàÊ¯´óµÀ"
      region.rooms[41].zone = "Ã÷½Ì"
      region.rooms[41].id = 1870
      region.rooms[41].links = {}
        region.rooms[41].links.nw = {}
          region.rooms[41].links.nw.to = 1871
          region.rooms[41].links.nw.con = ""
        region.rooms[41].links.se = {}
          region.rooms[41].links.se.to = 1849
          region.rooms[41].links.se.con = ""
      region.rooms[41].exits = "northwest|southeast"
      region.rooms[41].desc = "    ÕâÀïÊÇÍ¨Íù¾ŞÄ¾ÆìµÄ´óµÀ¡£µÀÂ·¿ªÀ«£¬´ó¸Å¿ÉÈİÊ®ÈË²¢¼ç¶øĞĞ¡£ÏÖÔÚ¾ŞÄ¾ÆìÊÇÃ÷½ÌÎåÆìÖĞÈËÊı×î¶à£¬»ú¹Ø¹¹Öş×îÔÓµÄ¡£³ıÁËÊØ»¤Ã÷½ÌÍâÎ§£¬»¹¸ºÔğÃ÷½ÌÖĞËùÓĞ·¿ÎİºÍÕ»ÇÅµÄ½¨Ôì¡£"
    region.rooms[42] = {}
      region.rooms[42].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw"
      region.rooms[42].name = "ÇàÊ¯´óµÀ"
      region.rooms[42].zone = "Ã÷½Ì"
      region.rooms[42].id = 1871
      region.rooms[42].links = {}
        region.rooms[42].links.nw = {}
          region.rooms[42].links.nw.to = 1872
          region.rooms[42].links.nw.con = ""
        region.rooms[42].links.se = {}
          region.rooms[42].links.se.to = 1870
          region.rooms[42].links.se.con = ""
      region.rooms[42].exits = "northwest|southeast"
      region.rooms[42].desc = "    ÕâÀï´óµÀÆ½Ì¹£¬µØÊÆ¿ªÀ«£¬Á½ÅÔÊ÷ÁÖÖĞÄñÓï»¨Ïã£¬Ò»Æ¬ºÍÆ½°²ÏéµÄÆø·Õ¡£´ËÊ±ÓÖÓĞË­ÄÜÏëµ½£¬ÕâÌõ´óµÀÉÏÈöÏÂ¹ı¶àÉÙ½­ºşÖĞÈËµÄÑª£¬ÕâÆ¬ÁÖÖĞÓÖÂñÓĞ¶àÉÙ²ÒËÀÓÚÎäÁÖÕù¶·µÄÔ©»êµÄ¹Ç¡£Ô¶´¦£¬ÒşÔ¼´«À´¶£¶£ßËßËµÄ·¥Ä¾Éù£¬Å¼¶ûÄÜÈÃÈË×·ÒäÆğµ¶¸êÌúÂíµÄÉ³³¡¾°Ïó¡£"
    region.rooms[43] = {}
      region.rooms[43].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw"
      region.rooms[43].name = "ÇàÊ¯´óµÀ"
      region.rooms[43].zone = "Ã÷½Ì"
      region.rooms[43].id = 1872
      region.rooms[43].links = {}
        region.rooms[43].links.e = {}
          region.rooms[43].links.e.to = 1873
          region.rooms[43].links.e.con = ""
        region.rooms[43].links.ne = {}
          region.rooms[43].links.ne.to = 1874
          region.rooms[43].links.ne.con = ""
        region.rooms[43].links.se = {}
          region.rooms[43].links.se.to = 1871
          region.rooms[43].links.se.con = ""
      region.rooms[43].exits = "east|southeast|northeast"
      region.rooms[43].desc = "    ´óÂ·ÒÑ¾­ÑÓÉìµ½ÁË¾¡Í·£¬Î÷Ê×·½ÏòÒ»×ùÃÅÂ¥¸ßËÊ£¬ÃÅÇ°ÓĞÊ®¼¸¸ö½ğÒÂÈËÍù·µÑ²Âß£¬ÆøÊÆÉ­ÑÏ¡£ÃÅÂ¥Á½ÅÔ²¢²åÏâ½ğÇàÁúÆì£¬Ó­·çÕĞÕ¹£¬ÁÒÁÒÉúÍş¡£ºìÉ«´óÃÅ½ô±Õ£¬²»Ê±ÓĞ½ÌÖÚ´Ó²àĞ¡ÃÅ½ø³ö£¬Ò²±»ÅÌ²éµÃ½ô¡£ÏòÎ÷±±¶øĞĞ£¬ÊÇÈ¥ºéË®ÆìµÄÂ·£¬¶øÎ÷ÄÏ·½ÏòÔòÍ¨ÍùÁÒ»ğÆì¡£"
    region.rooms[44] = {}
      region.rooms[44].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;e"
      region.rooms[44].name = "¾ŞÄ¾Æì´óÃÅ"
      region.rooms[44].zone = "Ã÷½Ì"
      region.rooms[44].id = 1873
      region.rooms[44].links = {}
        region.rooms[44].links.w = {}
          region.rooms[44].links.w.to = 1872
          region.rooms[44].links.w.con = ""
        region.rooms[44].links.enter = {}
          region.rooms[44].links.enter.to = 1882
          region.rooms[44].links.enter.con = ""
      region.rooms[44].exits = "enter|west"
      region.rooms[44].desc = "    ÕâÀïÊÇÃ÷½Ì¾ŞÄ¾ÆìµÄ´óÃÅ£¬×¯ÑÏ¹ÅÆÓ£¬ÃÅÇ°¶Ô²åËÄÃæÏâÂÌÓÎÁúÆì¡£±ÌÂÌµÄ´óÃÅ³¨¿ª×Å£¬ËÆºõ¿´²»³öÓĞºÎÉè·À¡£´ÓÃÅÀïÍû½øÈ¥£¬Ö»ÓĞÒ»Æ¬²Ô´äµÄÊ÷ÁÖ¡£"
    region.rooms[45] = {}
      region.rooms[45].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;ne"
      region.rooms[45].name = "É½Â·"
      region.rooms[45].zone = "Ã÷½Ì"
      region.rooms[45].id = 1874
      region.rooms[45].links = {}
        region.rooms[45].links.ne = {}
          region.rooms[45].links.ne.to = 1875
          region.rooms[45].links.ne.con = ""
        region.rooms[45].links.sw = {}
          region.rooms[45].links.sw.to = 1872
          region.rooms[45].links.sw.con = ""
      region.rooms[45].exits = "northeast|southwest"
      region.rooms[45].desc = "    ÕâÀïÊÇÒ»ÌõºÜÆÕÍ¨µÄÉ½Â·£¬Â·±ßµÄÊ÷ÁÖÃÜ¼¯£¬·¼²İÁ÷Ïã£¬²İ´ÔÖĞĞÇĞÇµãµãµØµã×º×ÅÒ»Ğ©°×É«Ò°»¨£¬Â·ÃæÒ²Ô½À´Ô½¸ÉÔï£¬Ô¶´¦¿É¼ûÕóÕó³¾ÍÁ·ÉÑï£¬ÎªÕâÉ½¹È¶¸ÔöÁË¼¸·ÖÉúÆø¡£"
    region.rooms[46] = {}
      region.rooms[46].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;ne;ne"
      region.rooms[46].name = "É½Â·"
      region.rooms[46].zone = "Ã÷½Ì"
      region.rooms[46].id = 1875
      region.rooms[46].links = {}
        region.rooms[46].links.nd = {}
          region.rooms[46].links.nd.to = 1876
          region.rooms[46].links.nd.con = ""
        region.rooms[46].links.sw = {}
          region.rooms[46].links.sw.to = 1874
          region.rooms[46].links.sw.con = ""
      region.rooms[46].exits = "northdown|southwest"
      region.rooms[46].desc = "    ÕâÀïÊÇÒ»ÌõºÜÆÕÍ¨µÄÉ½Â·£¬Â·±ßµÄÊ÷ÁÖÃÜ¼¯£¬·¼²İÁ÷Ïã£¬²İ´ÔÖĞĞÇĞÇµãµãµØµã×º×ÅÒ»Ğ©°×É«Ò°»¨£¬½¥ĞĞ½¥µÍ£¬Á½±ß²İÄ¾Ã¯Ê¢£¬´¦¸ßÑÂÏÂ£¬ÌìÉ«½¥Òõ¡£"
    region.rooms[47] = {}
      region.rooms[47].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;ne;ne;nd"
      region.rooms[47].name = "É½Â·"
      region.rooms[47].zone = "Ã÷½Ì"
      region.rooms[47].id = 1876
      region.rooms[47].links = {}
        region.rooms[47].links.enter = {}
          region.rooms[47].links.enter.to = 1877
          region.rooms[47].links.enter.con = ""
        region.rooms[47].links.su = {}
          region.rooms[47].links.su.to = 1875
          region.rooms[47].links.su.con = ""
      region.rooms[47].exits = "enter|southup"
      region.rooms[47].desc = "    É½Â·ÑÚÔÚÍÁ²ãÏÂ£¬Ç°ÃæËÆºõÃ»ÓĞÂ·ÁË¡£ÂúÉ½Ê÷ÁÖÃÜ¼¯£¬Ñ»ÄñÈº¼¯£¬ÁÖÖĞÑÌÎíÆ®µ´£¬²»ÖªËùÖ®¡£"
    region.rooms[48] = {}
      region.rooms[48].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;ne;ne;nd;enter"
      region.rooms[48].name = "É½¶´"
      region.rooms[48].zone = "Ã÷½Ì"
      region.rooms[48].id = 1877
      region.rooms[48].links = {}
        region.rooms[48].links.n = {}
          region.rooms[48].links.n.to = 1878
          region.rooms[48].links.n.con = ""
        region.rooms[48].links.out = {}
          region.rooms[48].links.out.to = 1876
          region.rooms[48].links.out.con = ""
      region.rooms[48].exits = "north|out"
      region.rooms[48].desc = "    É½¶´ÖĞËÆºõÉî²»¿É²â£¬¶´±ÚÉÏµã×Å¼¸ÕµËÉÃ÷£¬ÕÕµÃ¶´ÄÚÒ»ÅÉ¹âÁÁ¡£¶´ÄÚËäÈ»¸Ğµ½Ê®·Ö³±Êª£¬¿É¶´±Ú¸ÉÔï¼áÊµ£¬´óÒìÆ½³£¡£"
    region.rooms[49] = {}
      region.rooms[49].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;ne;ne;nd;enter;n"
      region.rooms[49].name = "É½¶´"
      region.rooms[49].zone = "Ã÷½Ì"
      region.rooms[49].id = 1878
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 1879
          region.rooms[49].links.e.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 1877
          region.rooms[49].links.s.con = ""
      region.rooms[49].exits = "south|east"
      region.rooms[49].desc = "    É½¶´ÖĞËÆºõÉî²»¿É²â£¬¶´±ÚÉÏµã×Å¼¸ÕµËÉÃ÷£¬ÕÕµÃ¶´ÄÚÒ»ÅÉ¹âÁÁ¡£¶´ÄÚËäÈ»¸Ğµ½Ê®·Ö³±Êª£¬¿É¶´±Ú¸ÉÔï¼áÊµ£¬´óÒìÆ½³£¡£"
    region.rooms[50] = {}
      region.rooms[50].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;ne;ne;nd;enter;n;e"
      region.rooms[50].name = "É½¶´"
      region.rooms[50].zone = "Ã÷½Ì"
      region.rooms[50].id = 1879
      region.rooms[50].links = {}
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 1878
          region.rooms[50].links.w.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 1880
          region.rooms[50].links.n.con = ""
      region.rooms[50].exits = "north|west"
      region.rooms[50].desc = "    É½¶´ÖĞËÆºõÉî²»¿É²â£¬¶´±ÚÉÏµã×Å¼¸ÕµËÉÃ÷£¬ÕÕµÃ¶´ÄÚÒ»ÅÉ¹âÁÁ¡£¶´ÄÚËäÈ»¸Ğµ½Ê®·Ö³±Êª£¬¿É¶´±Ú¸ÉÔï¼áÊµ£¬´óÒìÆ½³£¡£"
    region.rooms[51] = {}
      region.rooms[51].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;ne;ne;nd;enter;n;e;n"
      region.rooms[51].name = "ºñÍÁÆìÃÅ"
      region.rooms[51].zone = "Ã÷½Ì"
      region.rooms[51].id = 1880
      region.rooms[51].links = {}
        region.rooms[51].links.s = {}
          region.rooms[51].links.s.to = 1879
          region.rooms[51].links.s.con = ""
        region.rooms[51].links.enter = {}
          region.rooms[51].links.enter.to = 1881
          region.rooms[51].links.enter.con = ""
      region.rooms[51].exits = "south|enter"
      region.rooms[51].desc = "    ÕâÊÇºñÍÁÆìµÄ¶´ÃÅ£¬ÃÅ¶´Àï½ø½ø³ö³öµÄºñÍÁÆìÖÚ£¬ÉíÉÏ¹ÒÂúÁËÇÂ£¬²ù£¬¶Ìµ¶£¬Ë­Ò²²»ÀíÄã¡£ÃÅ±ßÁ½Ãæ¶Ì¸ËÏâ»Æ±ß·ÉÁúÆì£¬Ğå×ÅºñÍÁ¶ş×Ö¡£"
    region.rooms[52] = {}
      region.rooms[52].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;ne;ne;nd;enter;n;e;n;enter"
      region.rooms[52].name = "ºñÍÁÆì´óÌü"
      region.rooms[52].zone = "Ã÷½Ì"
      region.rooms[52].id = 1881
      region.rooms[52].links = {}
        region.rooms[52].links.out = {}
          region.rooms[52].links.out.to = 1880
          region.rooms[52].links.out.con = ""
      region.rooms[52].exits = "out"
      region.rooms[52].desc = "    ÕâÀïÊÇºñÍÁÆìµÄ´óÌü£¬ÌüÖĞµ¶Ç¹ÈçÁÖ£¬»ÆÆìÕĞÕ¹£¬½ÌÖÚ´©×ÅÌú¼×¸Ö¿ø£¬Ñü¼ä±ğ×ÅÇÂ²ù´¸×ê£¬Ò»¸ö¸ö¾«Éñ¶¶ËÓ¡£ÕıÖĞ¶Ë×ø×Å¸ö°«¶Õºº×Ó£¬¾ÍÊÇºñÍÁÆìÕÆÆìÊ¹ÑÕÔ«¡£"
    region.rooms[53] = {}
      region.rooms[53].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;e;enter"
      region.rooms[53].name = "¾ŞÄ¾ÆìÊ÷ÁÖ"
      region.rooms[53].zone = "Ã÷½Ì"
      region.rooms[53].id = 1882
      region.rooms[53].links = {}
        region.rooms[53].links.s = {}
          region.rooms[53].links.s.to = 1882
          region.rooms[53].links.s.con = ""
        region.rooms[53].links.out = {}
          region.rooms[53].links.out.to = 1873
          region.rooms[53].links.out.con = ""
        region.rooms[53].links.e = {}
          region.rooms[53].links.e.to = 1882
          region.rooms[53].links.e.con = ""
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 1882
          region.rooms[53].links.w.con = ""
        region.rooms[53].links.n = {}
          region.rooms[53].links.n.to = 1883
          region.rooms[53].links.n.con = ""
      region.rooms[53].exits = "south|north|east|out|west"
      region.rooms[53].desc = "    ÄãÑÛÇ°ÖèÈ»Ò»°µ£¬ëüëÊÖĞ£¬Ö»¼û×óÓÒÇ°ºó£¬µ½´¦¶¼ÊÇÆÌÌì¸ÇµØµÄ²»ÖªÃûµÄ¾ŞÊ÷£¬ºÃÏóËÉ°Ø£¬ÓÖËÆÀäÉ¼£¬´ØÔÚÒ»Æğ£¬ÃÜÊµµÄÖ¦Ò¶ÏóÒ»ÅîÅî¾ŞÉ¡°ãÉìÏòÌì¿Õ£¬ÕÚÌì±ÎÈÕ¡£ÄãËÆºõÃÔÊ§ÁË·½Ïò£¬ÏóÃ»Í·²ÔÓ¬°ãµ½´¦ÂÒ´³¡£"
    region.rooms[54] = {}
      region.rooms[54].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;e;enter;n"
      region.rooms[54].name = "¾ŞÄ¾ÆìÊ÷ÁÖ"
      region.rooms[54].zone = "Ã÷½Ì"
      region.rooms[54].id = 1883
      region.rooms[54].links = {}
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 1883
          region.rooms[54].links.e.con = ""
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 1883
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.s = {}
          region.rooms[54].links.s.to = 1883
          region.rooms[54].links.s.con = ""
        region.rooms[54].links.n = {}
          region.rooms[54].links.n.to = 1884
          region.rooms[54].links.n.con = ""
      region.rooms[54].exits = "south|north|east|west"
      region.rooms[54].desc = "    ÄãÑÛÇ°ÖèÈ»Ò»°µ£¬ëüëÊÖĞ£¬Ö»¼û×óÓÒÇ°ºó£¬µ½´¦¶¼ÊÇÆÌÌì¸ÇµØµÄ²»ÖªÃûµÄ¾ŞÊ÷£¬ºÃÏóËÉ°Ø£¬ÓÖËÆÀäÉ¼£¬´ØÔÚÒ»Æğ£¬ÃÜÊµµÄÖ¦Ò¶ÏóÒ»ÅîÅî¾ŞÉ¡°ãÉìÏòÌì¿Õ£¬ÕÚÌì±ÎÈÕ¡£ÄãËÆºõÃÔÊ§ÁË·½Ïò£¬ÏóÃ»Í·²ÔÓ¬°ãµ½´¦ÂÒ´³¡£"
    region.rooms[55] = {}
      region.rooms[55].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;e;enter;n;n"
      region.rooms[55].name = "¾ŞÄ¾ÆìÊ÷ÁÖ"
      region.rooms[55].zone = "Ã÷½Ì"
      region.rooms[55].id = 1884
      region.rooms[55].links = {}
        region.rooms[55].links.e = {}
          region.rooms[55].links.e.to = 1885
          region.rooms[55].links.e.con = ""
        region.rooms[55].links.w = {}
          region.rooms[55].links.w.to = 1884
          region.rooms[55].links.w.con = ""
        region.rooms[55].links.s = {}
          region.rooms[55].links.s.to = 1884
          region.rooms[55].links.s.con = ""
        region.rooms[55].links.n = {}
          region.rooms[55].links.n.to = 1884
          region.rooms[55].links.n.con = ""
      region.rooms[55].exits = "south|north|east|west"
      region.rooms[55].desc = "    ÄãÑÛÇ°ÖèÈ»Ò»°µ£¬ëüëÊÖĞ£¬Ö»¼û×óÓÒÇ°ºó£¬µ½´¦¶¼ÊÇÆÌÌì¸ÇµØµÄ²»ÖªÃûµÄ¾ŞÊ÷£¬ºÃÏóËÉ°Ø£¬ÓÖËÆÀäÉ¼£¬´ØÔÚÒ»Æğ£¬ÃÜÊµµÄÖ¦Ò¶ÏóÒ»ÅîÅî¾ŞÉ¡°ãÉìÏòÌì¿Õ£¬ÕÚÌì±ÎÈÕ¡£ÄãËÆºõÃÔÊ§ÁË·½Ïò£¬ÏóÃ»Í·²ÔÓ¬°ãµ½´¦ÂÒ´³¡£"
    region.rooms[56] = {}
      region.rooms[56].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;e;enter;n;n;e"
      region.rooms[56].name = "¾ŞÄ¾ÆìÊ÷ÁÖ"
      region.rooms[56].zone = "Ã÷½Ì"
      region.rooms[56].id = 1885
      region.rooms[56].links = {}
        region.rooms[56].links.e = {}
          region.rooms[56].links.e.to = 1885
          region.rooms[56].links.e.con = ""
        region.rooms[56].links.s = {}
          region.rooms[56].links.s.to = 1885
          region.rooms[56].links.s.con = ""
        region.rooms[56].links.w = {}
          region.rooms[56].links.w.to = 1885
          region.rooms[56].links.w.con = ""
        region.rooms[56].links.n = {}
          region.rooms[56].links.n.to = 1886
          region.rooms[56].links.n.con = ""
      region.rooms[56].exits = "south|north|east|west"
      region.rooms[56].desc = "    ÄãÑÛÇ°ÖèÈ»Ò»°µ£¬ëüëÊÖĞ£¬Ö»¼û×óÓÒÇ°ºó£¬µ½´¦¶¼ÊÇÆÌÌì¸ÇµØµÄ²»ÖªÃûµÄ¾ŞÊ÷£¬ºÃÏóËÉ°Ø£¬ÓÖËÆÀäÉ¼£¬´ØÔÚÒ»Æğ£¬ÃÜÊµµÄÖ¦Ò¶ÏóÒ»ÅîÅî¾ŞÉ¡°ãÉìÏòÌì¿Õ£¬ÕÚÌì±ÎÈÕ¡£ÄãËÆºõÃÔÊ§ÁË·½Ïò£¬ÏóÃ»Í·²ÔÓ¬°ãµ½´¦ÂÒ´³¡£"
    region.rooms[57] = {}
      region.rooms[57].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;e;enter;n;n;e;n"
      region.rooms[57].name = "¾ŞÄ¾ÆìÊ÷ÁÖ"
      region.rooms[57].zone = "Ã÷½Ì"
      region.rooms[57].id = 1886
      region.rooms[57].links = {}
        region.rooms[57].links.e = {}
          region.rooms[57].links.e.to = 1886
          region.rooms[57].links.e.con = ""
        region.rooms[57].links.w = {}
          region.rooms[57].links.w.to = 1887
          region.rooms[57].links.w.con = ""
        region.rooms[57].links.s = {}
          region.rooms[57].links.s.to = 1886
          region.rooms[57].links.s.con = ""
        region.rooms[57].links.n = {}
          region.rooms[57].links.n.to = 1886
          region.rooms[57].links.n.con = ""
      region.rooms[57].exits = "south|north|east|west"
      region.rooms[57].desc = "    ÄãÑÛÇ°ÖèÈ»Ò»°µ£¬ëüëÊÖĞ£¬Ö»¼û×óÓÒÇ°ºó£¬µ½´¦¶¼ÊÇÆÌÌì¸ÇµØµÄ²»ÖªÃûµÄ¾ŞÊ÷£¬ºÃÏóËÉ°Ø£¬ÓÖËÆÀäÉ¼£¬´ØÔÚÒ»Æğ£¬ÃÜÊµµÄÖ¦Ò¶ÏóÒ»ÅîÅî¾ŞÉ¡°ãÉìÏòÌì¿Õ£¬ÕÚÌì±ÎÈÕ¡£ÄãËÆºõÃÔÊ§ÁË·½Ïò£¬ÏóÃ»Í·²ÔÓ¬°ãµ½´¦ÂÒ´³¡£"
    region.rooms[58] = {}
      region.rooms[58].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;e;enter;n;n;e;n;w"
      region.rooms[58].name = "¾ŞÄ¾ÆìÊ÷ÁÖ"
      region.rooms[58].zone = "Ã÷½Ì"
      region.rooms[58].id = 1887
      region.rooms[58].links = {}
        region.rooms[58].links.e = {}
          region.rooms[58].links.e.to = 1887
          region.rooms[58].links.e.con = ""
        region.rooms[58].links.w = {}
          region.rooms[58].links.w.to = 1888
          region.rooms[58].links.w.con = ""
        region.rooms[58].links.s = {}
          region.rooms[58].links.s.to = 1887
          region.rooms[58].links.s.con = ""
        region.rooms[58].links.n = {}
          region.rooms[58].links.n.to = 1887
          region.rooms[58].links.n.con = ""
      region.rooms[58].exits = "south|north|east|west"
      region.rooms[58].desc = "    ÄãÑÛÇ°ÖèÈ»Ò»°µ£¬ëüëÊÖĞ£¬Ö»¼û×óÓÒÇ°ºó£¬µ½´¦¶¼ÊÇÆÌÌì¸ÇµØµÄ²»ÖªÃûµÄ¾ŞÊ÷£¬ºÃÏóËÉ°Ø£¬ÓÖËÆÀäÉ¼£¬´ØÔÚÒ»Æğ£¬ÃÜÊµµÄÖ¦Ò¶ÏóÒ»ÅîÅî¾ŞÉ¡°ãÉìÏòÌì¿Õ£¬ÕÚÌì±ÎÈÕ¡£ÄãËÆºõÃÔÊ§ÁË·½Ïò£¬ÏóÃ»Í·²ÔÓ¬°ãµ½´¦ÂÒ´³¡£"
    region.rooms[59] = {}
      region.rooms[59].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;nw;nw;nw;e;enter;n;n;e;n;w;w"
      region.rooms[59].name = "¾ŞÄ¾Æì»ú¹Ø"
      region.rooms[59].zone = "Ã÷½Ì"
      region.rooms[59].id = 1888
      region.rooms[59].links = {}
        region.rooms[59].links.e = {}
          region.rooms[59].links.e.to = 1888
          region.rooms[59].links.e.con = ""
        region.rooms[59].links.s = {}
          region.rooms[59].links.s.to = 1888
          region.rooms[59].links.s.con = ""
        region.rooms[59].links.w = {}
          region.rooms[59].links.w.to = 1888
          region.rooms[59].links.w.con = ""
        region.rooms[59].links.n = {}
          region.rooms[59].links.n.to = 1888
          region.rooms[59].links.n.con = ""
      region.rooms[59].exits = "south|north|east|west"
      region.rooms[59].desc = "    ÄãÑÛÇ°ÖèÈ»Ò»°µ£¬ëüëÊÖĞ£¬Ö»¼û×óÓÒÇ°ºó£¬µ½´¦¶¼ÊÇÆÌÌì¸ÇµØµÄ²»ÖªÃûµÄ¾ŞÊ÷£¬ºÃÏóËÉ°Ø£¬ÓÖËÆÀäÉ¼£¬´ØÔÚÒ»Æğ£¬ÃÜÊµµÄÖ¦Ò¶ÏóÒ»ÅîÅî¾ŞÉ¡°ãÉìÏòÌì¿Õ£¬ÕÚÌì±ÎÈÕ¡£ÄãËÆºõÃÔÊ§ÁË·½Ïò£¬ÏóÃ»Í·²ÔÓ¬°ãµ½´¦ÂÒ´³¡£"
    region.rooms[60] = {}
      region.rooms[60].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd"
      region.rooms[60].name = "ÇàÊ¯½×"
      region.rooms[60].zone = "Ã÷½Ì"
      region.rooms[60].id = 1889
      region.rooms[60].links = {}
        region.rooms[60].links.nu = {}
          region.rooms[60].links.nu.to = 1849
          region.rooms[60].links.nu.con = ""
        region.rooms[60].links.sd = {}
          region.rooms[60].links.sd.to = 1890
          region.rooms[60].links.sd.con = ""
      region.rooms[60].exits = "northup|southdown"
      region.rooms[60].desc = "    ÕâÀïÉ½Â·½¥¿í£¬ÇàÊ¯ÆÌÂ·£¬Ì¦ºÛµ­Çà£¬Â·×óÇàËÉÎ¡Î¡£¬Â·ÓÒÌÙÂÜÈÆÊ÷£¬Ô¶Ô¶µÄ£¬Ö»¼ûÇ°·½·¿ÓîÒÀÏ¡£¬³àºìÉ«ÆìÖÄÕĞÕ¹£¬ÌıËµÃ÷½ÌÁÒ»ğÆìÔÚ´Ë¾İÊØ£¬Êı°ÙÄêÀ´¹ÌÈçÅÍÊ¯¡£"
    region.rooms[61] = {}
      region.rooms[61].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd"
      region.rooms[61].name = "ĞüÌìÑÂ"
      region.rooms[61].zone = "Ã÷½Ì"
      region.rooms[61].id = 1890
      region.rooms[61].links = {}
        region.rooms[61].links.u = {}
          region.rooms[61].links.u.to = 1891
          region.rooms[61].links.u.con = ""
        region.rooms[61].links.sd = {}
          region.rooms[61].links.sd.to = 1892
          region.rooms[61].links.sd.con = ""
        region.rooms[61].links.nu = {}
          region.rooms[61].links.nu.to = 1889
          region.rooms[61].links.nu.con = ""
      region.rooms[61].exits = "up|northup|southdown"
      region.rooms[61].desc = "    ÕâÀïÉ½Â·¶¸ÇÍ£¬½öÓĞÒ»ÈË¶à¿í£¬Â·×óÊÇÇÍ±Ú¸ßËÊ£¬Â·ÓÒ½ôÁÙÍòÕÉÉîÔ¨£¬ÊµÔÚÊÇÒ»·òµ±¹Ø¡¢Íò·òÄª¿ªµÄÏÕÒªÖ®´¦¡£¼ÌĞøÉÏÅÊ£¬¾ÍÒªµ½´ïÃ÷½ÌÎåĞĞÆìÁË¡£½ô°¤Â·ÓÒ£¬ÌìÈ»ÉúÓĞÒ»¿é¾ŞÊ¯£¬¸ß½üÈıÕÉ£¬ÃûÎª¡°ĞüÌìÊ¯¡±£¬³£ÓĞÏÀ¿ÍÓÚÉÏÔ¶¹ÛÔÆº£¡£"
    region.rooms[62] = {}
      region.rooms[62].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;u"
      region.rooms[62].name = "ĞüÌìÊ¯"
      region.rooms[62].zone = "Ã÷½Ì"
      region.rooms[62].id = 1891
      region.rooms[62].links = {}
        region.rooms[62].links.d = {}
          region.rooms[62].links.d.to = 1890
          region.rooms[62].links.d.con = ""
      region.rooms[62].exits = "down"
      region.rooms[62].desc = "    ´ÓÊ¯ÉÏÔ¶Ì÷£¬Ö»¼ûÔÆº£²ÔÃ£´¦£¬ÏÕ¾øÍòÂÍÉú£¬À¥ÂØÒ»Âö£¬åÔåÆÇ§Àï£¬ÕæÒ»ÅÉ´óºÃ½­É½¡£¹ØÓÚĞüÌìÊ¯£¬»¹ÓĞĞí¶à´«Ëµ¡£Ïà´«Ã÷½ÌµÚÈıÊ®´ú½ÌÖ÷¡¼·çÎèÁøÓ°¡½°¢ÄÈ(Doll)Îª½âÃ÷½ÌÖ®ÄÑ£¬ÉáÉíÓÚ´Ë£¬Ã÷½ÌÒ»´ú¾øÑ§¡°Ç¬À¤´óÅ²ÒÆ¡±´Ó´ËÊ§´«¡£Ğí¶àºóÀ´Ö®ÈËÓÚ´ËÆ¾µõ£¬Äª²»ÆüÀá£¬µ«¸ü¶àµÄÊÇ´Ó´ËÊ¯ÌøÏÂ£¬ÏëÑ°ÕÒ¡°Ç¬À¤´óÅ²ÒÆ¡±ÃØ¼®£¬È´´ÓÃ»ÓĞÈËÄÜ°²È»¶ø¹é¡£"
    region.rooms[63] = {}
      region.rooms[63].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd"
      region.rooms[63].name = "ÇàÊ¯½×"
      region.rooms[63].zone = "Ã÷½Ì"
      region.rooms[63].id = 1892
      region.rooms[63].links = {}
        region.rooms[63].links.nu = {}
          region.rooms[63].links.nu.to = 1890
          region.rooms[63].links.nu.con = ""
        region.rooms[63].links.w = {}
          region.rooms[63].links.w.to = 1893
          region.rooms[63].links.w.con = ""
        region.rooms[63].links.ed = {}
          region.rooms[63].links.ed.to = 1895
          region.rooms[63].links.ed.con = ""
      region.rooms[63].exits = "eastdown|northup|west"
      region.rooms[63].desc = "    ÑÛÇ°åáÈ»³öÏÖÒ»´óÆ¬ËÉÁÖ¡£ËÉÁÖ³¤µÃ¼«ÃÜ£¬Ê¯½××ªÏò±±ÆÂ£¬ÉÏÃæÆÌÂúÁËºñºñµÄ½ğ»ÆµÄËÉÕë¡£²ÈÔÚ½ÅÏÂ£¬·¢³ö²ì²ìµÄÏìÉù¡£Ò»ÌõÕ­Ğ¡µÄ»ÆÍÁĞ¡Â·¼ÌĞøÏòÎ÷ÑÓÉì£¬½øÈëÊ÷ÁÖÉî´¦£¬ÏûÊ§ÔÚÃ£Ã£ÁÖº£Ö®ÖĞ¡£"
    region.rooms[64] = {}
      region.rooms[64].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w"
      region.rooms[64].name = "»ÆÍÁĞ¡Â·"
      region.rooms[64].zone = "Ã÷½Ì"
      region.rooms[64].id = 1893
      region.rooms[64].links = {}
        region.rooms[64].links.e = {}
          region.rooms[64].links.e.to = 1892
          region.rooms[64].links.e.con = ""
        region.rooms[64].links.w = {}
          region.rooms[64].links.w.to = 1894
          region.rooms[64].links.w.con = ""
      region.rooms[64].exits = "east|west"
      region.rooms[64].desc = "    ÕâÀïÊÇÃ¯ÃÜËÉÁÖÖĞµÄÒ»Ìõ»ÆÍÁĞ¡Â·¡£ËÉÁÖ¼«ÃÜ£¬ËÄÃæ¶¼ÊÇÀ¶ÓÄÓÄµÄ¸Ğ¾õ£¬Ó³³Ä×ÅÌìĞÄÑ©·å£¬¼«¾¡ÆàÃÀ¡£"
    region.rooms[65] = {}
      region.rooms[65].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w"
      region.rooms[65].name = "»ÆÍÁĞ¡Â·"
      region.rooms[65].zone = "Ã÷½Ì"
      region.rooms[65].id = 1894
      region.rooms[65].links = {}
        region.rooms[65].links.e = {}
          region.rooms[65].links.e.to = 1893
          region.rooms[65].links.e.con = ""
      region.rooms[65].exits = "east|enter"
      region.rooms[65].desc = "    ÕâÀïÊÇÃ¯ÃÜËÉÁÖÖĞµÄÒ»Ìõ»ÆÍÁĞ¡Â·¡£ËÉÁÖ¼«ÃÜ£¬ËÄÃæ¶¼ÊÇÀ¶ÓÄÓÄµÄ¸Ğ¾õ£¬°×°×µÄ±ùÑ©·´¹âÒ«ÑÛ¡£ÄãÀ´µ½Ò»¸öÉ½ÑüµÄÎ£ÑÂÖ®±ß£¬Ç°±ßÓĞÒ»¸öĞ¡¶´¡£"
    region.rooms[66] = {}
      region.rooms[66].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed"
      region.rooms[66].name = "ÇàÊ¯½×"
      region.rooms[66].zone = "Ã÷½Ì"
      region.rooms[66].id = 1895
      region.rooms[66].links = {}
        region.rooms[66].links.ed = {}
          region.rooms[66].links.ed.to = 1896
          region.rooms[66].links.ed.con = ""
        region.rooms[66].links.wu = {}
          region.rooms[66].links.wu.to = 1892
          region.rooms[66].links.wu.con = ""
      region.rooms[66].exits = "westup|eastdown"
      region.rooms[66].desc = "    ÕâÀïÒÑÊÇ°ëÉ½ÑüÁË¡£²»Ô¶µÄÇ°ÃæÓĞÒ»×ùÖñÍ¤£¬¼¸Î»½£¿ÍÔÚÕâÀïĞªÏ¢¡£É½Â·µ½ÕâÀï¸ü¼Ó¶¸ÇÍ£¬ËÄÏÂÍûÈ¥£¬²ãÂÍµüáÖ£¬ÂúÄ¿µÎ´äÔ¶É½ÅûÒø×°£¬ÔÆº£ÏÖÆæ¹Û¡£"
    region.rooms[67] = {}
      region.rooms[67].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed"
      region.rooms[67].name = "Ã÷½ÌÉ½ÃÅ"
      region.rooms[67].zone = "Ã÷½Ì"
      region.rooms[67].id = 1896
      region.rooms[67].links = {}
        region.rooms[67].links.e = {}
          region.rooms[67].links.e.to = 1897
          region.rooms[67].links.e.con = ""
        region.rooms[67].links.wu = {}
          region.rooms[67].links.wu.to = 1895
          region.rooms[67].links.wu.con = ""
      region.rooms[67].exits = "westup|east"
      region.rooms[67].desc = "    Ò»¸ö¾Ş´óµÄÌìÈ»Ê¯ÇÅºá¿çÔÚÁ½Æ¬É½±ÚÖ®¼ä£¬Ê¯ÇÅÕıÉÏ·½ÁúÅÌ·ïÎè¿Ì×ÅÁ½¸ö´ó×Ö£º¡ºÃ÷½Ì¡»¡£×Ö¼£ÓĞĞ©°şÂä£¬¿´ÉÏÈ¥Äê´ú¾ÃÔ¶¡£Á½Î»ÈıÊ®À´ËêµÄ´óººÊÖ³Ö¸Ö½£ÊØÔÚÉ½ÃÅÁ½²à¡£"
    region.rooms[68] = {}
      region.rooms[68].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e"
      region.rooms[68].name = "ÇàÊ¯½×"
      region.rooms[68].zone = "Ã÷½Ì"
      region.rooms[68].id = 1897
      region.rooms[68].links = {}
        region.rooms[68].links.w = {}
          region.rooms[68].links.w.to = 1896
          region.rooms[68].links.w.con = ""
        region.rooms[68].links.e = {}
          region.rooms[68].links.e.to = 1898
          region.rooms[68].links.e.con = ""
      region.rooms[68].exits = "east|west"
      region.rooms[68].desc = "    Ê¯¼¶µ½ÕâÀïËÆºõ±äµÃ¿íÀ«ÁËĞ©¡£ÇåĞÂµÄÉ½·çÆËÃæ¶øÀ´£¬ÁîÈË¾«Éñ¶ÙÎªÒ»Ë¬¡£Ô¶´¦´«À´äÈäÈË®Éù£¬½¥ĞĞ½¥Ô¶¡£É½±ÚÉÏ¹ÒÂúÁËºñÃÜµÄÌÙÂÜ£¬Ëæ·çÇáÇáÒ¡ß®¡£"
    region.rooms[69] = {}
      region.rooms[69].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e"
      region.rooms[69].name = "ÇàÊ¯½×"
      region.rooms[69].zone = "Ã÷½Ì"
      region.rooms[69].id = 1898
      region.rooms[69].links = {}
        region.rooms[69].links.e = {}
          region.rooms[69].links.e.to = 1899
          region.rooms[69].links.e.con = ""
        region.rooms[69].links.w = {}
          region.rooms[69].links.w.to = 1897
          region.rooms[69].links.w.con = ""
        region.rooms[69].links.s = {}
          region.rooms[69].links.s.to = 1900
          region.rooms[69].links.s.con = ""
      region.rooms[69].exits = "south|east|west"
      region.rooms[69].desc = "    ËÉÁÖ½¥½¥¿ªÀ«£¬ÃæÇ°³öÏÖÁËÒ»Ìõ¿í¹ãµÄÊ¯°åµÀ£¬±ÊÖ±Í¨ÏòÇ°·½¡£ÑØµÀÏ¡Ï¡ÂäÂäµØÖÖ×Å¼¸¿Ã°ØÊ÷£¬È´ÏÔµÃ¸ß´óÍ¦°Î£¬òøÁú°ãµÄÖ¦¸ÉÏòÌì¿Õ¸ß¸ßÉìÕ¹×Å¡£ÓÉ´ËÏòÄÏÔ¶Ô¶ÍûÈ¥£¬ÊÇÒ»×ùºì×©±ÌÍßµÄ»Öºê´óÕ¬¡£"
    region.rooms[70] = {}
      region.rooms[70].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e"
      region.rooms[70].name = "À¥ÂØÉ½ÏÂ"
      region.rooms[70].zone = "Ã÷½Ì"
      region.rooms[70].id = 1899
      region.rooms[70].links = {}
        region.rooms[70].links.w = {}
          region.rooms[70].links.w.to = 1898
          region.rooms[70].links.w.con = ""
        region.rooms[70].links.e = {}
          region.rooms[70].links.e.to = 1918
          region.rooms[70].links.e.con = ""
      region.rooms[70].exits = "northwest|east|west"
      region.rooms[70].desc = "    ÕâÀïÊÇÇ§ÀïÀ¥ÂØµÄ¶«Â´£¬Ô¶Íû²ÔÌìºÆºÆ£¬°×ÔÆÓÆÓÆ¡£¶«·½ÎÖÒ°Ç§Àï£¬³şÌìÁÉÀ«£»Î÷Ãæ¸ßÉ½Î¡Î¡£¬åÆåÎÍòÀï¡£ß³ßåÎäÁÖ°Ë°ÙÄêµÄÃ÷½Ì¾Í×ùÂäÔÚÕâÈºÉ½Ö®ÖĞ¡£Ã÷½Ì----ÊÇ¶àÉÙÎäÁÖºÀ½ÜËùÏòÍùµÄµØ·½£¬ÔÚÄÇÀï£¬ÓĞÎŞÊıÉúËÀÏàĞíµÄºÃĞÖµÜ£¬ÎŞÂÛÊÇÕıÊÇĞ°¡£¾ÍÔÚÕâÎ÷·½µÄÈºÉ½Ö®ºó£¬µÈ´ı×ÅÄãÈ¥Æ×Ğ´ÓÖÒ»ÇúÎäÁÖ´«Ææ¡£"
    region.rooms[71] = {}
      region.rooms[71].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s"
      region.rooms[71].name = "ÇàÊ¯µÀ"
      region.rooms[71].zone = "Ã÷½Ì"
      region.rooms[71].id = 1900
      region.rooms[71].links = {}
        region.rooms[71].links.s = {}
          region.rooms[71].links.s.to = 1901
          region.rooms[71].links.s.con = ""
        region.rooms[71].links.n = {}
          region.rooms[71].links.n.to = 1898
          region.rooms[71].links.n.con = ""
      region.rooms[71].exits = "south|north"
      region.rooms[71].desc = "    ´©¹ıÒ»Æ¬Ğ¡ËÉÁÖ£¬ÃæÇ°³öÏÖÁËÒ»Ìõ¿í¹ãµÄÊ¯°åµÀ£¬±ÊÖ±Í¨ÏòÇ°·½¡£ÑØµÀÏ¡Ï¡ÂäÂäµØÖÖ×Å¼¸¿Ã°ØÊ÷£¬È´ÏÔµÃ¸ß´óÍ¦°Î£¬òøÁú°ãµÄÖ¦¸ÉÏòÌì¿Õ¸ß¸ßÉìÕ¹×Å¡£"
    region.rooms[72] = {}
      region.rooms[72].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s"
      region.rooms[72].name = "¹ã³¡"
      region.rooms[72].zone = "Ã÷½Ì"
      region.rooms[72].id = 1901
      region.rooms[72].links = {}
        region.rooms[72].links.ne = {}
          region.rooms[72].links.ne.to = 1911
          region.rooms[72].links.ne.con = ""
        region.rooms[72].links.se = {}
          region.rooms[72].links.se.to = 1907
          region.rooms[72].links.se.con = ""
        region.rooms[72].links.sw = {}
          region.rooms[72].links.sw.to = 1904
          region.rooms[72].links.sw.con = ""
        region.rooms[72].links.nw = {}
          region.rooms[72].links.nw.to = 1902
          region.rooms[72].links.nw.con = ""
        region.rooms[72].links.n = {}
          region.rooms[72].links.n.to = 1900
          region.rooms[72].links.n.con = ""
      region.rooms[72].exits = "northwest|north|southeast|northeast|southwest"
      region.rooms[72].desc = "    ÕâÀïÊÇÒ»Æ¬Í¥ÔºÖĞÑëµÄ¹ã³¡£¬Õû¸ö¹ã³¡ÓÉ´ó¿éµÄÇàÊ¯ÆÌ³É£¬¼«ÎªÆ½Ì¹¡£µ«ÒòÄê´ú¾ÃÔ¶£¬¶¼ÓĞĞ©ÆÆËğ¡£´Ô´ÔĞ¡²İ´ÓÊ¯°åµÄ·ìÏ¶ÖĞ³¤ÁË³öÀ´¡£¹ã³¡ËÄÃæÓĞ¼¸ÌõĞ¡µÀ£¬Í¨ÏòÃ÷½ÌµÄ¡°ÌìµØ·çÀ×¡±ËÄÃÅ¡£"
    region.rooms[73] = {}
      region.rooms[73].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;nw"
      region.rooms[73].name = "»ÆÍÁµØ"
      region.rooms[73].zone = "Ã÷½Ì"
      region.rooms[73].id = 1902
      region.rooms[73].links = {}
        region.rooms[73].links.nw = {}
          region.rooms[73].links.nw.to = 1903
          region.rooms[73].links.nw.con = ""
        region.rooms[73].links.se = {}
          region.rooms[73].links.se.to = 1901
          region.rooms[73].links.se.con = ""
      region.rooms[73].exits = "northwest|southeast"
      region.rooms[73].desc = "    ÕâÊÇÒ»Æ¬»ÆÍÁµØ£¬³¾É³·ºÆğ£¬½£Ã¢Áè¿Õ£¬µ¶Ç¹»ÎÈÕ£¬É±ÆøÓ¯Ò°£¬¼¸¸öĞ¡»ï×Ó°ò´óÑüÔ²£¬Ò»Éí¶Ì´ò£¬Á·¹¦²»¶Ş¡£µ½´ËµØ£¬±ãÄÜ¸Ğ¾õµ½Ã÷½Ì°ÙÄêĞËÍúµÄ¸ùèÜ·ÇĞé¡£"
    region.rooms[74] = {}
      region.rooms[74].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;nw;nw"
      region.rooms[74].name = "ÃÅ¿Ú"
      region.rooms[74].zone = "Ã÷½Ì"
      region.rooms[74].id = 1903
      region.rooms[74].links = {}
        region.rooms[74].links.se = {}
          region.rooms[74].links.se.to = 1902
          region.rooms[74].links.se.con = ""
      region.rooms[74].exits = "enter|southeast"
      region.rooms[74].desc = "    Ç°Ãæ¾ÍÊÇÃ÷½ÌµÄ¡°Ìì×ÖÃÅ¡±ÁË£¬ÕâÀïÊÇÃ÷½ÌÖĞÄĞµÜ×ÓĞŞÁ¶µÄµØ·½£¬´ÓÃÅ¿Ú¿´½øÈ¥£¬º¹ÉÀÑï³ô£¬Ä¾×ÀÁ÷¾Æ¡£´Ë´¦²»ÔÊÅ®ÈËËæÒâ½øÈë¡£"
    region.rooms[75] = {}
      region.rooms[75].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;sw"
      region.rooms[75].name = "ÇàÊ¯µØ"
      region.rooms[75].zone = "Ã÷½Ì"
      region.rooms[75].id = 1904
      region.rooms[75].links = {}
        region.rooms[75].links.ne = {}
          region.rooms[75].links.ne.to = 1901
          region.rooms[75].links.ne.con = ""
        region.rooms[75].links.sw = {}
          region.rooms[75].links.sw.to = 1905
          region.rooms[75].links.sw.con = ""
      region.rooms[75].exits = "northeast|southwest"
      region.rooms[75].desc = "    ÕâÊÇÒ»Æ¬ÇàÊ¯µØ£¬¾²ÄÂÎŞ³¾¡£Ğ±êÍµ­É¨£¬Ê¯À¸Ó³ÈÕ£¬»ÔÓ°Ñ©É½¡£ÈıÈıÁ½Á½¸ß±ÇÉîÄ¿£¬Ñ©·ô½ğ·¢ÄĞÅ®½ÌÖÚ¼±²½´Ò´ÒÀ´È¥£¬ËùÅä±øÆ÷Ò²·ÇÖĞÍÁÄÜ¼û¡£"
    region.rooms[76] = {}
      region.rooms[76].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;sw;sw"
      region.rooms[76].name = "ÃÅ¿Ú"
      region.rooms[76].zone = "Ã÷½Ì"
      region.rooms[76].id = 1905
      region.rooms[76].links = {}
        region.rooms[76].links.ne = {}
          region.rooms[76].links.ne.to = 1904
          region.rooms[76].links.ne.con = ""
        region.rooms[76].links.enter = {}
          region.rooms[76].links.enter.to = 1906
          region.rooms[76].links.enter.con = ""
      region.rooms[76].exits = "enter|northeast"
      region.rooms[76].desc = "    Ç°Ãæ¾ÍÊÇÃ÷½ÌµÄ¡°À××ÖÃÅ¡±ÁË£¬ÕâÀïÊÇÃ÷½ÌÖĞÎ÷ÓòµÜ×ÓĞŞÁ¶µÄµØ·½¡£Î÷Óò·çË×´óÒìÖĞÍÁ£¬ËûÃÇµÄÉú»îÏ°¹ßÒÔ¼°Ê¹ÓÃÎïÆ·Ò²ÓëÖĞÍÁåÄÒì¡£"
    region.rooms[77] = {}
      region.rooms[77].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;sw;sw;enter"
      region.rooms[77].name = "À×ÃÅËŞÉá"
      region.rooms[77].zone = "Ã÷½Ì"
      region.rooms[77].id = 1906
      region.rooms[77].links = {}
        region.rooms[77].links.out = {}
          region.rooms[77].links.out.to = 1905
          region.rooms[77].links.out.con = ""
      region.rooms[77].exits = "out"
      region.rooms[77].desc = "    ×ß½øÕâ¼äËŞÉá£¬ÂúÄ¿Òì¹úÇéµ÷¡£À×ÃÅ½ÌÖÚËÆºõ²»´óÀí²ÇÄã¡£ĞíÊÇÑÔÓï²»Í¨£¬ÄãÒ²²»ÏëÔÚ´Ë¶àÁô¡£"
    region.rooms[78] = {}
      region.rooms[78].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;se"
      region.rooms[78].name = "ÖñÁÖ"
      region.rooms[78].zone = "Ã÷½Ì"
      region.rooms[78].id = 1907
      region.rooms[78].links = {}
        region.rooms[78].links.nw = {}
          region.rooms[78].links.nw.to = 1901
          region.rooms[78].links.nw.con = ""
        region.rooms[78].links.se = {}
          region.rooms[78].links.se.to = 1908
          region.rooms[78].links.se.con = ""
      region.rooms[78].exits = "northwest|southeast"
      region.rooms[78].desc = "    ÕâÊÇÒ»ÌõËéÊ¯ÆÌ³ÉµÄĞ¡µÀ£¬ÇúÇúÕÛÕÛµØÍ¨ÏòÇ°·½¡£Á½±ßÊÇÃÜÃÜµÄÖñÁÖ¡£ÕâÀïÈË¼£º±ÖÁ£¬Î©ÎÅ×ãµ×ßµ»÷Â·Ãæ£¬É®ÇÃÄ¾ÓãÉù£¬µÀËÌµÀµÂ¾­£¬Î¢·ç´µ·÷ÖñÒ¶£¬Èçóùóùìø³ª¡£ÁîÈË³¾ĞÄÎªÖ®Ò»µÓ£¬ÕæÊÇ¾ø¼ÑµÄìøĞŞËùÔÚ¡£"
    region.rooms[79] = {}
      region.rooms[79].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;se;se"
      region.rooms[79].name = "ÖñÁÖ"
      region.rooms[79].zone = "Ã÷½Ì"
      region.rooms[79].id = 1908
      region.rooms[79].links = {}
        region.rooms[79].links.nw = {}
          region.rooms[79].links.nw.to = 1907
          region.rooms[79].links.nw.con = ""
        region.rooms[79].links.s = {}
          region.rooms[79].links.s.to = 1909
          region.rooms[79].links.s.con = ""
        region.rooms[79].links.n = {}
          region.rooms[79].links.n.to = 1910
          region.rooms[79].links.n.con = ""
      region.rooms[79].exits = "south|north|northwest"
      region.rooms[79].desc = "    ÕâÊÇÖñÁÖÖĞµÄÒ»¼äĞ¡Ôº£¬ÖñÓ°ÒÀÒÀ£¬¾­ÉùÈë¶ú£¬ÆäÄÏ±±¸÷ÓĞÒ»¼äÖñÉá£¬ÄËÊÇÃ÷½ÌÖĞÊÍµÀºÍ·ğ¼ÒµÜ×ÓµÄĞŞÁ¶³¡Ëù¡£"
    region.rooms[80] = {}
      region.rooms[80].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;se;se;s"
      region.rooms[80].name = "µÀ¼ÒÖñÉá"
      region.rooms[80].zone = "Ã÷½Ì"
      region.rooms[80].id = 1909
      region.rooms[80].links = {}
        region.rooms[80].links.n = {}
          region.rooms[80].links.n.to = 1908
          region.rooms[80].links.n.con = ""
      region.rooms[80].exits = "north"
      region.rooms[80].desc = "    ×ß½øÕâ¼äÖñÉá£¬Ò»ÕóÏãÜø×íÈË£¬Ö»¼û¼¸Î»°×ÒÂµÀÈËÕıÔÚÆ·²èÂÛµÀ£¬¼¸¸öÇàÒÂĞ¡Í¯ÊÌÁ¢Á½ÅÔ¡£ÖĞ¼äÄÇÎ»µÀÈËÖĞµÈÄê¼Í£¬ÏÉ·çµÀ¹Ç£¬Æ®È»¶øÁ¢£¬Éíºó¹ÒÓĞÒ»·ù¶ÔÁª(dui lian)£¬ÄËÊÇÃ÷½ÌÒ»Î»ÏÈ±²ÀîåĞÒ£ËùÊé¡£"
    region.rooms[81] = {}
      region.rooms[81].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;se;se;n"
      region.rooms[81].name = "·ğ¼ÒÖñÉá"
      region.rooms[81].zone = "Ã÷½Ì"
      region.rooms[81].id = 1910
      region.rooms[81].links = {}
        region.rooms[81].links.s = {}
          region.rooms[81].links.s.to = 1908
          region.rooms[81].links.s.con = ""
      region.rooms[81].exits = "south"
      region.rooms[81].desc = "    ×ß½øÕâ¼äÖñÉá£¬Ò»ÕóÇåÏãÆ®À´£¬Ö»¼û¼¸ÎªÇàÒÂÉ®ÈË¶Ë×øÓÚÆÎÍÅÖ®ÉÏ£¬ÕıµÍÉùÓ½Äî¡°½ğ¸Õ¾­¡±¡£ÊÒÖĞÏãÑÌÇåÈÆ£¬ÖñÓ°Á÷·¼£¬Ò»°×Ã¼ÀÏÉ®¶Ë×øÕıÖĞ£¬ÊÖ³ÖÆĞÌáÄîÖé£¬ÄîÄîÓĞ´Ê¡£ÉíºóÇ½±ÚÖ®ÉÏ£¬¸ßĞüÒ»Ìõ·ù(tiao fu)£¬Ö½ÒÑ·¢»Æ,µ«±ÊÁ¦åÙ¾¢£¬Ò»¼û¿ÉÖªÊÇ¼ş¹ÅÎï¡£"
    region.rooms[82] = {}
      region.rooms[82].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;ne"
      region.rooms[82].name = "²İµØ"
      region.rooms[82].zone = "Ã÷½Ì"
      region.rooms[82].id = 1911
      region.rooms[82].links = {}
        region.rooms[82].links.ne = {}
          region.rooms[82].links.ne.to = 1912
          region.rooms[82].links.ne.con = ""
        region.rooms[82].links.sw = {}
          region.rooms[82].links.sw.to = 1901
          region.rooms[82].links.sw.con = ""
      region.rooms[82].exits = "northeast|southwest"
      region.rooms[82].desc = "    ÕâÊÇÒ»Æ¬·¼²İµØ£¬ÂäÓ¢çÍ·×£¬·ä¸èµûÎè£¬³¯Â¶Ï¦¹â£¬ÇßÈËĞÄÆ¢¡£¼¸¸öĞ¡¹ÃÄïİºÉùÂüÓ°£¬ÍçÆ¤¿ÉÈË£¬ÍğÈçÈıÔÂÌÒÀî£¬À°¶¬ÄÛÃ·£¬ÈÇÈËÁ¯°®¡£ÈÎÄãÊÇ½­ºşºÀ½Ü£¬×ßµ½ÕâÀï£¬ĞÄÖĞÒ²Æ½Ìí¼¸´çÎÂÈá£¬ÉÙÈ´Èı·ÖÉ±Òâ¡£"
    region.rooms[83] = {}
      region.rooms[83].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;ne;ne"
      region.rooms[83].name = "ÃÅ¿Ú"
      region.rooms[83].zone = "Ã÷½Ì"
      region.rooms[83].id = 1912
      region.rooms[83].links = {}
        region.rooms[83].links.enter = {}
          region.rooms[83].links.enter.to = 1913
          region.rooms[83].links.enter.con = ""
        region.rooms[83].links.sw = {}
          region.rooms[83].links.sw.to = 1911
          region.rooms[83].links.sw.con = ""
      region.rooms[83].exits = "enter|southwest"
      region.rooms[83].desc = "    Ç°Ãæ¾ÍÊÇÃ÷½ÌµÄ¡°µØ×ÖÃÅ¡±ÁË£¬ÕâÀïÊÇÃ÷½ÌÖĞÅ®µÜ×ÓĞŞÁ¶µÄµØ·½£¬´ÓÃÅ¿Ú¿´½øÈ¥£¬ç±ÂŞá£Ó°£¬Éí×Ë´Â´Â¡£ËäÊÇ½­ºş¶ùÅ®£¬È´Ò²²»ÈÃÄĞ×ÓËæÒâ½øÈë¡£ÃÅ¿Ú»¹Á¢ÓĞÒ»¿éÄ¾ÅÆ(mu pai)¡£"
    region.rooms[84] = {}
      region.rooms[84].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;ne;ne;enter"
      region.rooms[84].name = "ÉîÌ¶"
      region.rooms[84].zone = "Ã÷½Ì"
      region.rooms[84].id = 1913
      region.rooms[84].links = {}
        region.rooms[84].links.e = {}
          region.rooms[84].links.e.to = 1914
          region.rooms[84].links.e.con = ""
        region.rooms[84].links.w = {}
          region.rooms[84].links.w.to = 1913
          region.rooms[84].links.w.con = ""
        region.rooms[84].links.n = {}
          region.rooms[84].links.n.to = 1913
          region.rooms[84].links.n.con = ""
      region.rooms[84].exits = "south|north|east|west"
      region.rooms[84].desc = "    ÕâÀïÊÇÆÙ²¼ÏÂµÄº®Ì¶£¬Ë®ÖĞÓÄ°µÎŞ±È£¬ËÄÖÜËÆºõÓĞ¼¸´¦³ö¿Ú£¬µ«ÊµÔÚ¿´²»ÇåÊÇÍ¨ÏòºÎ´¦¡£Ë®ÖĞ±ùÀä´Ì¹Ç£¬ÁîÈËÄÑÒÔÈÌÊÜ£¬ÄãÖ»¾õµÃÆøÁ¦ÔÚÒ»µãÒ»µãÏûÊ§¡£"
    region.rooms[85] = {}
      region.rooms[85].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;ne;ne;enter;e"
      region.rooms[85].name = "ÉîÌ¶"
      region.rooms[85].zone = "Ã÷½Ì"
      region.rooms[85].id = 1914
      region.rooms[85].links = {}
        region.rooms[85].links.e = {}
          region.rooms[85].links.e.to = 1914
          region.rooms[85].links.e.con = ""
        region.rooms[85].links.s = {}
          region.rooms[85].links.s.to = 1915
          region.rooms[85].links.s.con = ""
        region.rooms[85].links.w = {}
          region.rooms[85].links.w.to = 1913
          region.rooms[85].links.w.con = ""
        region.rooms[85].links.n = {}
          region.rooms[85].links.n.to = 1914
          region.rooms[85].links.n.con = ""
      region.rooms[85].exits = "south|north|east|west"
      region.rooms[85].desc = "    ÕâÀïÊÇÆÙ²¼ÏÂµÄº®Ì¶£¬Ë®ÖĞÓÄ°µÎŞ±È£¬ËÄÖÜËÆºõÓĞ¼¸´¦³ö¿Ú£¬µ«ÊµÔÚ¿´²»ÇåÊÇÍ¨ÏòºÎ´¦¡£Ë®ÖĞ±ùÀä´Ì¹Ç£¬ÁîÈËÄÑÒÔÈÌÊÜ£¬ÄãÖ»¾õµÃÆøÁ¦ÔÚÒ»µãÒ»µãÏûÊ§¡£"
    region.rooms[86] = {}
      region.rooms[86].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;ne;ne;enter;e;s"
      region.rooms[86].name = "ÉîÌ¶"
      region.rooms[86].zone = "Ã÷½Ì"
      region.rooms[86].id = 1915
      region.rooms[86].links = {}
        region.rooms[86].links.e = {}
          region.rooms[86].links.e.to = 1916
          region.rooms[86].links.e.con = ""
        region.rooms[86].links.w = {}
          region.rooms[86].links.w.to = 1915
          region.rooms[86].links.w.con = ""
        region.rooms[86].links.s = {}
          region.rooms[86].links.s.to = 1915
          region.rooms[86].links.s.con = ""
        region.rooms[86].links.n = {}
          region.rooms[86].links.n.to = 1914
          region.rooms[86].links.n.con = ""
      region.rooms[86].exits = "south|north|east|west"
      region.rooms[86].desc = "    ÕâÀïÊÇÆÙ²¼ÏÂµÄº®Ì¶£¬Ë®ÖĞÓÄ°µÎŞ±È£¬ËÄÖÜËÆºõÓĞ¼¸´¦³ö¿Ú£¬µ«ÊµÔÚ¿´²»ÇåÊÇÍ¨ÏòºÎ´¦¡£Ë®ÖĞ±ùÀä´Ì¹Ç£¬ÁîÈËÄÑÒÔÈÌÊÜ£¬ÄãÖ»¾õµÃÆøÁ¦ÔÚÒ»µãÒ»µãÏûÊ§¡£"
    region.rooms[87] = {}
      region.rooms[87].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;ne;ne;enter;e;s;e"
      region.rooms[87].name = "ÉîÌ¶"
      region.rooms[87].zone = "Ã÷½Ì"
      region.rooms[87].id = 1916
      region.rooms[87].links = {}
        region.rooms[87].links.e = {}
          region.rooms[87].links.e.to = 1917
          region.rooms[87].links.e.con = ""
        region.rooms[87].links.w = {}
          region.rooms[87].links.w.to = 1915
          region.rooms[87].links.w.con = ""
        region.rooms[87].links.s = {}
          region.rooms[87].links.s.to = 1916
          region.rooms[87].links.s.con = ""
        region.rooms[87].links.n = {}
          region.rooms[87].links.n.to = 1916
          region.rooms[87].links.n.con = ""
      region.rooms[87].exits = "south|north|east|west"
      region.rooms[87].desc = "    ÕâÀïÊÇÆÙ²¼ÏÂµÄº®Ì¶£¬Ë®ÖĞÓÄ°µÎŞ±È£¬Ë®ÖĞ±ùÀä´Ì¹Ç£¬ÁîÈËÄÑÒÔÈÌÊÜ£¬ÄãÖ»¾õµÃÆøÁ¦ÔÚÒ»µãÒ»µãÏûÊ§¡£ËÄÖÜÓĞ¼¸´¦³ö¿Ú£¬¶«ÃæµÄËÆºõÓĞĞ©ÁÁ¹âÍ¸À´¡£"
    region.rooms[88] = {}
      region.rooms[88].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;s;s;ne;ne;enter;e;s;e;e"
      region.rooms[88].name = "ÉîÌ¶"
      region.rooms[88].zone = "Ã÷½Ì"
      region.rooms[88].id = 1917
      region.rooms[88].links = {}
        region.rooms[88].links.w = {}
          region.rooms[88].links.w.to = 1916
          region.rooms[88].links.w.con = ""
        region.rooms[88].links.u = {}
          region.rooms[88].links.u.to = 1867
          region.rooms[88].links.u.con = ""
      region.rooms[88].exits = "up|west"
      region.rooms[88].desc = "    ÕâÀïµÄË®Ö»ÓĞÆëÑüÉî£¬µ«Õ¾ÔÚË®ÖĞ£¬ÈÔ¸Ğ¾õº®Òâ´Ó½ÅÏÂÂşÆğ£¬¾­¾Ã²»É¢¡£"
    region.rooms[89] = {}
      region.rooms[89].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e"
      region.rooms[89].name = "¸ê±ÚÌ²"
      region.rooms[89].zone = "Ã÷½Ì"
      region.rooms[89].id = 1918
      region.rooms[89].links = {}
        region.rooms[89].links.e = {}
          region.rooms[89].links.e.to = 1918
          region.rooms[89].links.e.con = ""
        region.rooms[89].links.s = {}
          region.rooms[89].links.s.to = 1919
          region.rooms[89].links.s.con = ""
        region.rooms[89].links.w = {}
          region.rooms[89].links.w.to = 1899
          region.rooms[89].links.w.con = ""
        region.rooms[89].links.n = {}
          region.rooms[89].links.n.to = 1918
          region.rooms[89].links.n.con = ""
      region.rooms[89].exits = "south|north|east|west"
      region.rooms[89].desc = "    ÑÛÇ°ÊÇÒ»ÍûÎŞ¼ÊµÄ¸ê±ÚÌ²£¬Ã»ÓĞÂ·±ê£¬Ò²Ã»ÓĞÒ»¸öĞĞÈË£¬ÌìÏÔµÃºÜ¸ß£¬Ô¶É½ÅûÑ©£¬²ÔÓ¥°¿Ïè£¬×ßÔÚÕâÃ£Ã£¸ê±ÚÖ®ÉÏ£¬ÄãËÆºõÃÔÂ·ÁË¡£"
    region.rooms[90] = {}
      region.rooms[90].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e;s"
      region.rooms[90].name = "¸ê±ÚÌ²"
      region.rooms[90].zone = "Ã÷½Ì"
      region.rooms[90].id = 1919
      region.rooms[90].links = {}
        region.rooms[90].links.e = {}
          region.rooms[90].links.e.to = 1919
          region.rooms[90].links.e.con = ""
        region.rooms[90].links.s = {}
          region.rooms[90].links.s.to = 1920
          region.rooms[90].links.s.con = ""
        region.rooms[90].links.w = {}
          region.rooms[90].links.w.to = 1919
          region.rooms[90].links.w.con = ""
        region.rooms[90].links.n = {}
          region.rooms[90].links.n.to = 1918
          region.rooms[90].links.n.con = ""
      region.rooms[90].exits = "south|north|east|west"
      region.rooms[90].desc = "    ÑÛÇ°ÊÇÒ»ÍûÎŞ¼ÊµÄ¸ê±ÚÌ²£¬Ã»ÓĞÂ·±ê£¬Ò²Ã»ÓĞÒ»¸öĞĞÈË£¬ÌìÏÔµÃºÜ¸ß£¬Ô¶É½ÅûÑ©£¬²ÔÓ¥°¿Ïè£¬×ßÔÚÕâÃ£Ã£¸ê±ÚÖ®ÉÏ£¬ÄãËÆºõÃÔÂ·ÁË¡£"
    region.rooms[91] = {}
      region.rooms[91].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e;s;s"
      region.rooms[91].name = "¸ê±ÚÌ²"
      region.rooms[91].zone = "Ã÷½Ì"
      region.rooms[91].id = 1920
      region.rooms[91].links = {}
        region.rooms[91].links.e = {}
          region.rooms[91].links.e.to = 1921
          region.rooms[91].links.e.con = ""
        region.rooms[91].links.s = {}
          region.rooms[91].links.s.to = 1920
          region.rooms[91].links.s.con = ""
        region.rooms[91].links.w = {}
          region.rooms[91].links.w.to = 1920
          region.rooms[91].links.w.con = ""
        region.rooms[91].links.n = {}
          region.rooms[91].links.n.to = 1919
          region.rooms[91].links.n.con = ""
      region.rooms[91].exits = "south|north|east|west"
      region.rooms[91].desc = "    ÑÛÇ°ÊÇÒ»ÍûÎŞ¼ÊµÄ¸ê±ÚÌ²£¬Ã»ÓĞÂ·±ê£¬Ò²Ã»ÓĞÒ»¸öĞĞÈË£¬ÌìÏÔµÃºÜ¸ß£¬Ô¶É½ÅûÑ©£¬²ÔÓ¥°¿Ïè£¬×ßÔÚÕâÃ£Ã£¸ê±ÚÖ®ÉÏ£¬ÄãËÆºõÃÔÂ·ÁË¡£"
    region.rooms[92] = {}
      region.rooms[92].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e;s;s;e"
      region.rooms[92].name = "¸ê±ÚÌ²"
      region.rooms[92].zone = "Ã÷½Ì"
      region.rooms[92].id = 1921
      region.rooms[92].links = {}
        region.rooms[92].links.e = {}
          region.rooms[92].links.e.to = 1922
          region.rooms[92].links.e.con = ""
        region.rooms[92].links.w = {}
          region.rooms[92].links.w.to = 1920
          region.rooms[92].links.w.con = ""
        region.rooms[92].links.s = {}
          region.rooms[92].links.s.to = 1921
          region.rooms[92].links.s.con = ""
        region.rooms[92].links.n = {}
          region.rooms[92].links.n.to = 1921
          region.rooms[92].links.n.con = ""
      region.rooms[92].exits = "south|north|east|west"
      region.rooms[92].desc = "    ÑÛÇ°ÊÇÒ»ÍûÎŞ¼ÊµÄ¸ê±ÚÌ²£¬Ã»ÓĞÂ·±ê£¬Ò²Ã»ÓĞÒ»¸öĞĞÈË£¬ÌìÏÔµÃºÜ¸ß£¬Ô¶É½ÅûÑ©£¬²ÔÓ¥°¿Ïè£¬×ßÔÚÕâÃ£Ã£¸ê±ÚÖ®ÉÏ£¬ÄãËÆºõÃÔÂ·ÁË¡£"
    region.rooms[93] = {}
      region.rooms[93].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e;s;s;e;e"
      region.rooms[93].name = "¸ê±ÚÌ²"
      region.rooms[93].zone = "Ã÷½Ì"
      region.rooms[93].id = 1922
      region.rooms[93].links = {}
        region.rooms[93].links.e = {}
          region.rooms[93].links.e.to = 1923
          region.rooms[93].links.e.con = ""
        region.rooms[93].links.s = {}
          region.rooms[93].links.s.to = 1922
          region.rooms[93].links.s.con = ""
        region.rooms[93].links.w = {}
          region.rooms[93].links.w.to = 1921
          region.rooms[93].links.w.con = ""
        region.rooms[93].links.n = {}
          region.rooms[93].links.n.to = 1922
          region.rooms[93].links.n.con = ""
      region.rooms[93].exits = "south|north|east|west"
      region.rooms[93].desc = "    ÖÕÓÚ´©³öÁËÃÜÁÖ£¬ÑÛÇ°ÊÇÒ»ÍûÎŞ¼ÊµÄ¸ê±ÚÌ²£¬Ã»ÓĞÂ·±ê£¬Ò²Ã»ÓĞÒ»¸öĞĞÈË£¬ÌìÏÔµÃºÜ¸ß£¬Ô¶É½ÅûÑ©£¬²ÔÓ¥°¿Ïè£¬ºÃÒ»ÅÉ²»Í¬ÓÚÖĞÍÁµÄÒìÓò·ç¹â¡£²»Ô¶´¦£¬¼¸Ö»°×¹ÇÉ¢ÂäµØÉÏ£¬ËÆºõÊÇêóÅ£µÄÊ¬¹Ç¡×ßÔÚÕâÃ£Ã£¸ê±ÚÖ®ÉÏ£¬ÄãËÆºõÃÔÂ·ÁË¡£"
    region.rooms[94] = {}
      region.rooms[94].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e;s;s;e;e;e"
      region.rooms[94].name = "ÉîÉ½"
      region.rooms[94].zone = "Ã÷½Ì"
      region.rooms[94].id = 1923
      region.rooms[94].links = {}
        region.rooms[94].links.e = {}
          region.rooms[94].links.e.to = 1925
          region.rooms[94].links.e.con = ""
        region.rooms[94].links.s = {}
          region.rooms[94].links.s.to = 1924
          region.rooms[94].links.s.con = ""
        region.rooms[94].links.w = {}
          region.rooms[94].links.w.to = 1922
          region.rooms[94].links.w.con = ""
      region.rooms[94].exits = "south|east|west"
      region.rooms[94].desc = "    ÒÑ¾­×ßÁËºÜ¾Ã£¬É½ÁÖÔ½À´Ô½ÃÜ£¬Ò¹ÍíÀ´ÁÙÁË£¬Ò¹èÉºôºÅ£¬ÁîÈËÃ«¹Çã¤È»¡£ÕæÊÇ¡°ÊñµÀÄÑ£¬ÄÑÓÚÉÏÇàÌì¡±¡£ÔÙÏòÎ÷£¬¾ÍÒª³öÉ½ÁË¡£Í»È»£¬ÄãÓÖ·¢ÏÖÄÏÃæÓĞÁãĞÇ»ğ¹â¡£"
    region.rooms[95] = {}
      region.rooms[95].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e;s;s;e;e;e;s"
      region.rooms[95].name = "ÃçÈË²¿Âä"
      region.rooms[95].zone = "Ã÷½Ì"
      region.rooms[95].id = 1924
      region.rooms[95].links = {}
        region.rooms[95].links.n = {}
          region.rooms[95].links.n.to = 1923
          region.rooms[95].links.n.con = ""
      region.rooms[95].exits = "north"
      region.rooms[95].desc = "    ÄãÑÛÇ°Í»È»Ò»ÁÁ£¬Ô­À´ÊÇ×ß½øÁËÒ»¸öÃçÈË²¿Âä¡£ÃçÈËÃÇÎ§×øÔÚ»ğ¶Ñ±ß£¬ÃæÉ«ò¯³Ï£¬ºÃÏóÔÚ×÷Ä³ÖÖ¼ÀÉñÒÇÊ½¡£¼¸¸öÎ×Ê¿»ÓÎè×ÅÄ¾ïÛ£¬¿Ú\\ÖĞÄîÄîÓĞ´Ê¡£Í»È»£¬ËûÃÇºÃÏó·¢ÏÖÁËÄã¡£"
    region.rooms[96] = {}
      region.rooms[96].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e;s;s;e;e;e;e"
      region.rooms[96].name = "É½Â·"
      region.rooms[96].zone = "Ã÷½Ì"
      region.rooms[96].id = 1925
      region.rooms[96].links = {}
        region.rooms[96].links.w = {}
          region.rooms[96].links.w.to = 1923
          region.rooms[96].links.w.con = ""
        region.rooms[96].links.e = {}
          region.rooms[96].links.e.to = 1926
          region.rooms[96].links.e.con = ""
      region.rooms[96].exits = "east|west"
      region.rooms[96].desc = "    ÕâÊÇÒ»ÌõÖ±Í¨Î÷·½µÄÉ½Â·£¬ÏòÎ÷Ô¶Íû£¬ÈºÉ½Î¡¶ë£¬ÔÆÎíÆ®Ãì£¬ÔÙÍùÇ°²»Ô¶£¬¾ÍÒª½øÈëÉîÉ½Ö®ÖĞÁË¡£¶«Ãæ¾ÍÊÇÈ¥ÖĞÔ­µÄÂ·¡£"
    region.rooms[97] = {}
      region.rooms[97].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;ed;ed;e;e;e;e;s;s;e;e;e;e;e"
      region.rooms[97].name = "Ë¿³ñÖ®Â·"
      region.rooms[97].zone = "Ã÷½Ì"
      region.rooms[97].id = 1926
      region.rooms[97].links = {}
        region.rooms[97].links.w = {}
          region.rooms[97].links.w.to = 1925
          region.rooms[97].links.w.con = ""
      region.rooms[97].exits = "northwest|east|west"
      region.rooms[97].desc = "    ÕâÊÇÒ»ÌõÖĞÔ­ºÍÎ÷ÓòÖ®¼äµÄÉÌµÀ¡£ÄÏÃæÁ¬ÃàµÄÆîÁ¬É½ÂöÔÚÑô¹âµÄÕÕÉäÏÂºÃÏñÊÇÒ»ÌõÓñ´ø¡£¶«±ßÊÇÖĞÔ­£¬Î÷ÃæÔòÍ¨ÍùÎ÷Óò¡£"
  region.center = 1830

return region
