local region = {}
  region.cmd = "fly wjg"
  region.name = "万劫谷"
  region.id = "wjg"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly wjg;s;enter;s;out;out;e;su;eu;ed;nd;ed;e;e;e;su"
      region.rooms[1].name = "江边小路"
      region.rooms[1].zone = "大理|万劫谷"
      region.rooms[1].id = 644
      region.rooms[1].desc = "    这是澜沧江边的一条小路，江水滔滔，从下面奔腾而过，江面上不时传来艄公的号子声，与江风的呼啸声形成一曲动人的交响乐"
      region.rooms[1].exits = "southeast|southdown|northdown"
      region.rooms[1].links = {}
        region.rooms[1].links.nd = {}
          region.rooms[1].links.nd.to = 1633
          region.rooms[1].links.nd.con = ""
        region.rooms[1].links.sd = {}
          region.rooms[1].links.sd.to = 1632
          region.rooms[1].links.sd.con = ""
        region.rooms[1].links.se = {}
          region.rooms[1].links.se.to = 640
          region.rooms[1].links.se.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly wjg;s;enter;s;out;out;e;su;eu;ed;nd;ed;e;e;e;su;sd"
      region.rooms[2].name = "江边小路"
      region.rooms[2].zone = "万劫谷"
      region.rooms[2].id = 1632
      region.rooms[2].links = {}
        region.rooms[2].links.nu = {}
          region.rooms[2].links.nu.to = 644
          region.rooms[2].links.nu.con = ""
      region.rooms[2].exits = "northup"
      region.rooms[2].desc = "    这是澜沧江边的一条小路，江水滔滔，从下面奔腾而过，江面上不时传来艄公的号子声，与江风的呼啸声形成一曲动人的交响乐"
    region.rooms[3] = {}
      region.rooms[3].path = "fly wjg;s;enter;s;out;out;e;su;eu;ed;nd;ed;e;e;e"
      region.rooms[3].name = "江边小路"
      region.rooms[3].zone = "万劫谷"
      region.rooms[3].id = 1633
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 1634
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.su = {}
          region.rooms[3].links.su.to = 644
          region.rooms[3].links.su.con = ""
      region.rooms[3].exits = "southup|west"
      region.rooms[3].desc = "    这是澜沧江边的一条小路，江水滔滔，从下面奔腾而过，江面上不时传来艄公的号子声，与江风的呼啸声形成一曲动人的交响乐"
    region.rooms[4] = {}
      region.rooms[4].path = "fly wjg;s;enter;s;out;out;e;su;eu;ed;nd;ed;e;e"
      region.rooms[4].name = "善人渡"
      region.rooms[4].zone = "万劫谷"
      region.rooms[4].id = 1634
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 1633
          region.rooms[4].links.e.con = ""
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 1635
          region.rooms[4].links.w.con = ""
      region.rooms[4].exits = "east|west"
      region.rooms[4].desc = "    这里从前是澜沧江的一个渡口，后来大理国在此修了一座铁索桥，人们便不用再乘船过江了。桥边石上清清楚楚地刻着三个大字“善人渡”。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly wjg;s;enter;s;out;out;e;su;eu;ed;nd;ed;e"
      region.rooms[5].name = "铁索桥"
      region.rooms[5].zone = "万劫谷"
      region.rooms[5].id = 1635
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 1634
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 1636
          region.rooms[5].links.w.con = ""
      region.rooms[5].exits = "east|west"
      region.rooms[5].desc = "    一座横跨澜沧江的铁索桥，此桥共有四道铁索，两条在下，上铺木板，以供行走，两条在旁，作为扶手。一踏上桥，几条铁索便即晃动。江水荡荡，如快马奔腾从脚底飞过，只要一个失足，卷入江水，任你多好的水性也难活命。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly wjg;s;enter;s;out;out;e;su;eu;ed;nd;ed"
      region.rooms[6].name = "澜沧江畔"
      region.rooms[6].zone = "万劫谷"
      region.rooms[6].id = 1636
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 1635
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.wu = {}
          region.rooms[6].links.wu.to = 1637
          region.rooms[6].links.wu.con = ""
      region.rooms[6].exits = "westup|east"
      region.rooms[6].desc = "    这里是一个小山坡，前面立着一条细铁杆(tiegan)，西面是上山的路，东面一条铁索桥横跨江面，只见江水奔腾，呼啸而过，江风吹得铁索桥晃来晃去。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly wjg;s;enter;s;out;out;e;su;eu;ed;nd"
      region.rooms[7].name = "山坡"
      region.rooms[7].zone = "万劫谷"
      region.rooms[7].id = 1637
      region.rooms[7].links = {}
        region.rooms[7].links.ed = {}
          region.rooms[7].links.ed.to = 1636
          region.rooms[7].links.ed.con = ""
        region.rooms[7].links.su = {}
          region.rooms[7].links.su.to = 1638
          region.rooms[7].links.su.con = ""
      region.rooms[7].exits = "eastdown|southup"
      region.rooms[7].desc = "    山坡之上张着一些不知名的杂草，以及三三两两分布其间的灌木丛，这里很少有大树，几朵野花在路边悄悄开放，偶尔有几只蝴蝶飞来飞去。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly wjg;s;enter;s;out;out;e;su;eu;ed"
      region.rooms[8].name = "山路"
      region.rooms[8].zone = "万劫谷"
      region.rooms[8].id = 1638
      region.rooms[8].links = {}
        region.rooms[8].links.wu = {}
          region.rooms[8].links.wu.to = 1639
          region.rooms[8].links.wu.con = ""
        region.rooms[8].links.nd = {}
          region.rooms[8].links.nd.to = 1637
          region.rooms[8].links.nd.con = ""
      region.rooms[8].exits = "westup|northdown"
      region.rooms[8].desc = "    这是一条山间小路，两边山坡上张了许多树木，北风吹过，发出沙沙的响声。路上张着许多杂草，看起来这里很少有人走动。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly wjg;s;enter;s;out;out;e;su;eu"
      region.rooms[9].name = "山路"
      region.rooms[9].zone = "万劫谷"
      region.rooms[9].id = 1639
      region.rooms[9].links = {}
        region.rooms[9].links.ed = {}
          region.rooms[9].links.ed.to = 1638
          region.rooms[9].links.ed.con = ""
        region.rooms[9].links.wd = {}
          region.rooms[9].links.wd.to = 1640
          region.rooms[9].links.wd.con = ""
      region.rooms[9].exits = "eastdown|westdown"
      region.rooms[9].desc = "    这是一条山间小路，两边山坡上张了许多树木，北风吹过，发出沙沙的响声。路上张着许多杂草，看起来这里很少有人走动。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly wjg;s;enter;s;out;out;e;su"
      region.rooms[10].name = "山路"
      region.rooms[10].zone = "万劫谷"
      region.rooms[10].id = 1640
      region.rooms[10].links = {}
        region.rooms[10].links.nd = {}
          region.rooms[10].links.nd.to = 1641
          region.rooms[10].links.nd.con = ""
        region.rooms[10].links.eu = {}
          region.rooms[10].links.eu.to = 1639
          region.rooms[10].links.eu.con = ""
      region.rooms[10].exits = "eastup|northdown"
      region.rooms[10].desc = "    这是一条山间小路，两边山坡上张了许多树木，北风吹过，发出沙沙的响声。路上张着许多杂草，看起来这里很少有人走动。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly wjg;s;enter;s;out;out;e"
      region.rooms[11].name = "山路"
      region.rooms[11].zone = "万劫谷"
      region.rooms[11].id = 1641
      region.rooms[11].links = {}
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 1642
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.su = {}
          region.rooms[11].links.su.to = 1640
          region.rooms[11].links.su.con = ""
      region.rooms[11].exits = "southup|west"
      region.rooms[11].desc = "    这是一条山间小路，两边山坡上张了许多树木，北风吹过，发出沙沙的响声。路上张着许多杂草，看起来这里很少有人走动。往西看，远远可见黑压压一片大森林。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly wjg;s;enter;s;out;out"
      region.rooms[12].name = "大森林"
      region.rooms[12].zone = "万劫谷"
      region.rooms[12].id = 1642
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 1641
          region.rooms[12].links.e.con = ""
        region.rooms[12].links["pushaside grass;enter"] = {}
          region.rooms[12].links["pushaside grass;enter"].to = 1643
          region.rooms[12].links["pushaside grass;enter"].con = ""
      region.rooms[12].exits = "east"
      region.rooms[12].desc = "    这里是好大一座森林，黑压压的一片望不到边。最特别是左首一排并列着九株参天大松树，每颗树都高耸入云。树下草丛茂密，挡住了去路。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly wjg;s;enter;s;out"
      region.rooms[13].name = "树洞"
      region.rooms[13].zone = "万劫谷"
      region.rooms[13].id = 1643
      region.rooms[13].links = {}
        region.rooms[13].links["pull ring;enter"] = {}
          region.rooms[13].links["pull ring;enter"].to = 1644
          region.rooms[13].links["pull ring;enter"].con = ""
        region.rooms[13].links.out = {}
          region.rooms[13].links.out.to = 1642
          region.rooms[13].links.out.con = ""
      region.rooms[13].exits = "out"
      region.rooms[13].desc = "    树洞内非常狭窄，光线黑暗，地上铺满是枯草。洞的墙上有一只大蜘蛛正在编织一个蜘蛛网。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly wjg;s;enter;s"
      region.rooms[14].name = "地道"
      region.rooms[14].zone = "万劫谷"
      region.rooms[14].id = 1644
      region.rooms[14].links = {}
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 1645
          region.rooms[14].links.n.con = ""
        region.rooms[14].links.out = {}
          region.rooms[14].links.out.to = 1643
          region.rooms[14].links.out.con = ""
      region.rooms[14].exits = "north|out"
      region.rooms[14].desc = "    地道里光线黑暗，空气浑浊，一股霉味扑鼻而来。地道里石台阶异常粗糙，两边土墙上不时渗出水滴掉到地上。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly wjg;s;enter"
      region.rooms[15].name = "地道"
      region.rooms[15].zone = "万劫谷"
      region.rooms[15].id = 1645
      region.rooms[15].links = {}
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 1644
          region.rooms[15].links.s.con = ""
        region.rooms[15].links.out = {}
          region.rooms[15].links.out.to = 1646
          region.rooms[15].links.out.con = ""
      region.rooms[15].exits = "south|out"
      region.rooms[15].desc = "    地道里光线黑暗，空气浑浊，一股霉味扑鼻而来。地道里石台阶异常粗糙，两边土墙上不时渗出水滴掉到地上。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly wjg;s"
      region.rooms[16].name = "草地"
      region.rooms[16].zone = "万劫谷"
      region.rooms[16].id = 1646
      region.rooms[16].links = {}
        region.rooms[16].links.enter = {}
          region.rooms[16].links.enter.to = 1645
          region.rooms[16].links.enter.con = ""
        region.rooms[16].links["knock 段;n"] = {}
          region.rooms[16].links["knock 段;n"].to = 1647
          region.rooms[16].links["knock 段;n"].con = ""
      region.rooms[16].exits = "enter"
      region.rooms[16].desc = "    这是一大片草地，前面一排松树挡住了去路。只见一株大松上削下了丈许长、尺许宽的一片，漆着白漆，写着九个大字，“姓段者入此谷杀无赦”。树上挂着一个铁锤。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly wjg"
      region.rooms[17].name = "小厅"
      region.rooms[17].zone = "万劫谷"
      region.rooms[17].id = 1647
      region.rooms[17].links = {}
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 1646
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 1648
          region.rooms[17].links.n.con = ""
      region.rooms[17].exits = "south|north"
      region.rooms[17].desc = "    这是一间小厅，桌上点着一对巨烛。东壁四幅屏条，绘的是梅兰竹菊，西壁上的四幅是春夏秋冬。可是全挂错了方位，看来这里的主人并不懂得书画。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly wjg;n"
      region.rooms[18].name = "内堂"
      region.rooms[18].zone = "万劫谷"
      region.rooms[18].id = 1648
      region.rooms[18].links = {}
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 1649
          region.rooms[18].links.e.con = ""
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 1651
          region.rooms[18].links.w.con = ""
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 1647
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 1653
          region.rooms[18].links.n.con = ""
      region.rooms[18].exits = "south|east|north|west"
      region.rooms[18].desc = "    这里放着一张大桌子，靠墙有两张凳子，白白的墙壁一尘不染，有一个人正在屋里走来走去，显的心情焦操。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly wjg;n;e"
      region.rooms[19].name = "右厢房"
      region.rooms[19].zone = "万劫谷"
      region.rooms[19].id = 1649
      region.rooms[19].links = {}
        region.rooms[19].links.w = {}
          region.rooms[19].links.w.to = 1648
          region.rooms[19].links.w.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 1650
          region.rooms[19].links.n.con = ""
      region.rooms[19].exits = "north|west"
      region.rooms[19].desc = "    这是一间普通的房间，里面放着一些日常用品，墙角落里堆着一堆药草，是钟谷主采集而来，日后要用它制造各种药物。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly wjg;n;e;n"
      region.rooms[20].name = "药房"
      region.rooms[20].zone = "万劫谷"
      region.rooms[20].id = 1650
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 1649
          region.rooms[20].links.s.con = ""
      region.rooms[20].exits = "south"
      region.rooms[20].desc = "    刚进这间屋子，就有一股浓重的药味扑面而来。房子中间有一个练药用的石臼，还有几只药匙放在一边。靠墙一排架子，架子上摆满了药瓶，数百个瓶子上都写着药物的名字。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly wjg;n;w"
      region.rooms[21].name = "左厢房"
      region.rooms[21].zone = "万劫谷"
      region.rooms[21].id = 1651
      region.rooms[21].links = {}
        region.rooms[21].links.e = {}
          region.rooms[21].links.e.to = 1648
          region.rooms[21].links.e.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 1652
          region.rooms[21].links.n.con = ""
      region.rooms[21].exits = "east|north"
      region.rooms[21].desc = "    这是一间普通的房间，里面放着一些日常用品。桌子上放着一壶茶，还没有冷掉。旁边一个大柜子，里面放着许多衣服。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly wjg;n;w;n"
      region.rooms[22].name = "卧室"
      region.rooms[22].zone = "万劫谷"
      region.rooms[22].id = 1652
      region.rooms[22].links = {}
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 1651
          region.rooms[22].links.s.con = ""
      region.rooms[22].exits = "south"
      region.rooms[22].desc = "    这是钟谷主的卧室，室内大红的帏帐挂在大红的木床之上。墙上贴满了各种花花绿绿的东西。床边有个小柜，柜上放着一盏豆油灯。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly wjg;n;n"
      region.rooms[23].name = "后院"
      region.rooms[23].zone = "万劫谷"
      region.rooms[23].id = 1653
      region.rooms[23].links = {}
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 1648
          region.rooms[23].links.s.con = ""
      region.rooms[23].exits = "south"
      region.rooms[23].desc = "    后院是一大片开阔的草地，绿草如荫，几朵野花点缀其间，草地中间放着一块大石刻成的棋盘，一个黄眉老僧和一个青袍客正在下棋。北边有一间石屋，门口被一块大石头挡住了。"
  region.center = 1647
return region