local region = {}
  region.cmd = "fly xx"
  region.name = "星宿海"
  region.id = "xx"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly xx;su;s;ed;se;sw"
      region.rooms[1].name = "草原"
      region.rooms[1].zone = "血刀门|星宿海"
      region.rooms[1].id = 2151
      region.rooms[1].links = {}
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 2150
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.ne = {}
          region.rooms[1].links.ne.to = 2312
          region.rooms[1].links.ne.con = ""
      region.rooms[1].exits = "northeast|west"
      region.rooms[1].desc = "    这里是雪山脚下的一片草原。北面是起伏的群山，山顶上积着终年不化的雪。西边有一条土路。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly xx"
      region.rooms[2].name = "星宿海"
      region.rooms[2].zone = "星宿海"
      region.rooms[2].id = 2285
      region.rooms[2].desc = "    这里是星宿海边。说是海，其实是片湖泊和沼泽，地形十分险恶。东面石壁上一道裂缝通到一个山洞。南面有一条捷径可通往白驼山。"
      region.rooms[2].exits = "westup|south|north|southup"
      region.rooms[2].links = {}
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 2286
          region.rooms[2].links.n.con = "k1:摘星子"
        region.rooms[2].links.wu = {}
          region.rooms[2].links.wu.to = 2298
          region.rooms[2].links.wu.con = "k1:摘星子"
        region.rooms[2].links.su = {}
          region.rooms[2].links.su.to = 2303
          region.rooms[2].links.su.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly xx;[k1:摘星子]n"
      region.rooms[3].name = "星宿海"
      region.rooms[3].zone = "星宿海"
      region.rooms[3].id = 2286
      region.rooms[3].desc = "    这里是星宿海边。说是海，其实是片湖泊和沼泽，地形十分险恶。这里左右两厢通向星宿海深处，北边通向星宿派总舵──日月洞。洞口立着一个牌子(paizi)。"
      region.rooms[3].exits = "south|northwest|north|northeast"
      region.rooms[3].links = {}
        region.rooms[3].links.ne = {}
          region.rooms[3].links.ne.to = 2296
          region.rooms[3].links.ne.con = "aw:3:flatter 星宿老仙"
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 2285
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.nw = {}
          region.rooms[3].links.nw.to = 2288
          region.rooms[3].links.nw.con = "aw:3:flatter 星宿老仙"
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 2287
          region.rooms[3].links.n.con = "aw:3:flatter 星宿老仙"
    region.rooms[4] = {}
      region.rooms[4].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]n"
      region.rooms[4].name = "日月洞"
      region.rooms[4].zone = "星宿海"
      region.rooms[4].id = 2287
      region.rooms[4].desc = "    这里是星宿派总舵所在地日月洞。洞内灯火通明，正中一把虎皮椅上端坐着星宿派掌门人丁春秋。洞壁上装饰着虎皮、鹿头、雕羽，及一些字画(zihua)。洞两侧竖立兵器架，上面排列的大多是各种棍棒。"
      region.rooms[4].exits = "south"
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 2286
          region.rooms[4].links.s.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw"
      region.rooms[5].name = "星宿海"
      region.rooms[5].zone = "星宿海"
      region.rooms[5].id = 2288
      region.rooms[5].desc = "    这里是星宿海边。说是海，其实是片湖泊和沼泽，地形十分险恶。这里通向星宿海的深处。西面有一条新铺的石头路。"
      region.rooms[5].exits = "northwest|southeast|northeast|west"
      region.rooms[5].links = {}
        region.rooms[5].links.ne = {}
          region.rooms[5].links.ne.to = 2297
          region.rooms[5].links.ne.con = ""
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 2966
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.nw = {}
          region.rooms[5].links.nw.to = 2295
          region.rooms[5].links.nw.con = ""
        region.rooms[5].links.se = {}
          region.rooms[5].links.se.to = 2286
          region.rooms[5].links.se.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw;w;[k1:采花子]enter"
      region.rooms[6].name = "逍遥洞"
      region.rooms[6].zone = "星宿海"
      region.rooms[6].id = 2289
      region.rooms[6].desc = "    这是一个粗糙的石洞，里面铺了几张臭哄哄的草垫子。垫子旁边是一些破酒罐子。洞壁(wall)上有些字迹。"
      region.rooms[6].exits = "out"
      region.rooms[6].links = {}
        region.rooms[6].links.out = {}
          region.rooms[6].links.out.to = 2966
          region.rooms[6].links.out.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw;w;nw"
      region.rooms[7].name = "小路"
      region.rooms[7].zone = "星宿海"
      region.rooms[7].id = 2290
      region.rooms[7].desc = "    你走在一条在山壁上人工开凿出来崎岖的小路上，这里，寒风凛冽，西面是望不见底的深涧。"
      region.rooms[7].exits = "northup|southeast"
      region.rooms[7].links = {}
        region.rooms[7].links.nu = {}
          region.rooms[7].links.nu.to = 2291
          region.rooms[7].links.nu.con = ""
        region.rooms[7].links.se = {}
          region.rooms[7].links.se.to = 2966
          region.rooms[7].links.se.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw;w;nw;nu"
      region.rooms[8].name = "小路"
      region.rooms[8].zone = "星宿海"
      region.rooms[8].id = 2291
      region.rooms[8].desc = "    山势在这里渐渐变得平缓，你已经可以听见西边山涧底的水声。东面有一个山洞。"
      region.rooms[8].exits = "north|enter|southdown"
      region.rooms[8].links = {}
        region.rooms[8].links.enter = {}
          region.rooms[8].links.enter.to = 2292
          region.rooms[8].links.enter.con = ""
        region.rooms[8].links.sd = {}
          region.rooms[8].links.sd.to = 2290
          region.rooms[8].links.sd.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 2293
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw;w;nw;nu;enter"
      region.rooms[9].name = "星宿派储藏室"
      region.rooms[9].zone = "星宿海"
      region.rooms[9].id = 2292
      region.rooms[9].desc = "    这里原来是一个长在山壁上的天然溶洞，因为地点隐密而且洞中空气十分干燥，星宿派把这里改造成了一个仓库。"
      region.rooms[9].exits = "out"
      region.rooms[9].links = {}
        region.rooms[9].links.out = {}
          region.rooms[9].links.out.to = 2291
          region.rooms[9].links.out.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw;nw;nu;nw"
      region.rooms[10].name = "山间平地"
      region.rooms[10].zone = "星宿海"
      region.rooms[10].id = 2293
      region.rooms[10].desc = "    山间平地，地上是嫩绿的小草，周围布了几棵桦树，山边有一眼清泉。草地上树着几个毒僵尸，显是星宿弟子练功所用。"
      region.rooms[10].exits = "south|southeast"
      region.rooms[10].links = {}
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 2291
          region.rooms[10].links.s.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw;nw;nu"
      region.rooms[11].name = "小路"
      region.rooms[11].zone = "星宿海"
      region.rooms[11].id = 2294
      region.rooms[11].desc = "    你走在一条崎岖的小路上，这里荒无人烟，寒风凛冽。"
      region.rooms[11].exits = "northwest|southdown|northeast"
      region.rooms[11].links = {}
        region.rooms[11].links.ne = {}
          region.rooms[11].links.ne.to = 2286
          region.rooms[11].links.ne.con = ""
        region.rooms[11].links.sd = {}
          region.rooms[11].links.sd.to = 2295
          region.rooms[11].links.sd.con = ""
        region.rooms[11].links.nw = {}
          region.rooms[11].links.nw.to = 2293
          region.rooms[11].links.nw.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw;nw"
      region.rooms[12].name = "小路"
      region.rooms[12].zone = "星宿海"
      region.rooms[12].id = 2295
      region.rooms[12].desc = "    你走在一条崎岖的小路上，这里荒无人烟，寒风凛冽。"
      region.rooms[12].exits = "southeast|northup"
      region.rooms[12].links = {}
        region.rooms[12].links.nu = {}
          region.rooms[12].links.nu.to = 2294
          region.rooms[12].links.nu.con = ""
        region.rooms[12].links.se = {}
          region.rooms[12].links.se.to = 2288
          region.rooms[12].links.se.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]ne"
      region.rooms[13].name = "星宿海"
      region.rooms[13].zone = "星宿海"
      region.rooms[13].id = 2296
      region.rooms[13].desc = "    这里是星宿海边。说是海，其实是片湖泊和沼泽，地形十分险恶。这里通向星宿海的深处。"
      region.rooms[13].exits = "northwest|southwest"
      region.rooms[13].links = {}
        region.rooms[13].links.nw = {}
          region.rooms[13].links.nw.to = 2297
          region.rooms[13].links.nw.con = ""
        region.rooms[13].links.sw = {}
          region.rooms[13].links.sw.to = 2286
          region.rooms[13].links.sw.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]ne;nw"
      region.rooms[14].name = "星宿海"
      region.rooms[14].zone = "星宿海"
      region.rooms[14].id = 2297
      region.rooms[14].desc = ""
      region.rooms[14].exits = "southeast|southwest"
      region.rooms[14].links = {}
        region.rooms[14].links.se = {}
          region.rooms[14].links.se.to = 2296
          region.rooms[14].links.se.con = ""
        region.rooms[14].links.sw = {}
          region.rooms[14].links.sw.to = 2288
          region.rooms[14].links.sw.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly xx;[k1:摘星子]wu"
      region.rooms[15].name = "天山山路"
      region.rooms[15].zone = "星宿海"
      region.rooms[15].id = 2298
      region.rooms[15].desc = "    这里是天山东麓，山风从山上吹来，你冷得瑟瑟发抖。路边是一片草原。西面一条深涧(valley)挡住了上山的路。"
      region.rooms[15].exits = "eastdown"
      region.rooms[15].links = {}
        region.rooms[15].links.ed = {}
          region.rooms[15].links.ed.to = 2285
          region.rooms[15].links.ed.con = ""
        region.rooms[15].links.hi = {}
          region.rooms[15].links.hi.to = 2299
          region.rooms[15].links.hi.con = "aw:3:jump valley"
    region.rooms[16] = {}
      region.rooms[16].path = "fly xx;[k1:摘星子]wu;[aw:3:jump valley]hi"
      region.rooms[16].name = "天山山路"
      region.rooms[16].zone = "星宿海"
      region.rooms[16].id = 2299
      region.rooms[16].desc = "    这里是天山东麓，山风从山上吹来，你冷得瑟瑟发抖。路边是一片针叶林。石壁上盛开着一朵洁白的天山雪莲，一个采药人正在采药。东面一条深涧(valley)挡住了下山的路。"
      region.rooms[16].exits = "westup"
      region.rooms[16].links = {}
        region.rooms[16].links["jump valley"] = {}
          region.rooms[16].links["jump valley"].to = 2298
          region.rooms[16].links["jump valley"].con = ""
        region.rooms[16].links.wu = {}
          region.rooms[16].links.wu.to = 2300
          region.rooms[16].links.wu.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly xx;[k1:摘星子]wu;[aw:3:jump valley]hi;wu"
      region.rooms[17].name = "天山山路"
      region.rooms[17].zone = "星宿海"
      region.rooms[17].id = 2300
      region.rooms[17].desc = "    这里是天山东麓，山风从山上吹来，你冷得瑟瑟发抖。路边是一片针叶林。西边望去，顶峰遥遥可见。南边有个黑黢黢的山洞(cave)。"
      region.rooms[17].exits = "westup|enter|eastdown"
      region.rooms[17].links = {}
        region.rooms[17].links.ed = {}
          region.rooms[17].links.ed.to = 2299
          region.rooms[17].links.ed.con = ""
        region.rooms[17].links.enter = {}
          region.rooms[17].links.enter.to = 2301
          region.rooms[17].links.enter.con = ""
        region.rooms[17].links.wu = {}
          region.rooms[17].links.wu.to = 2302
          region.rooms[17].links.wu.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly xx;[k1:摘星子]wu;[aw:3:jump valley]hi;wu;enter"
      region.rooms[18].name = "山洞"
      region.rooms[18].zone = "星宿海"
      region.rooms[18].id = 2301
      region.rooms[18].desc = "    这个山洞里伸手不见五指，只有出口处透进一丝光线。"
      region.rooms[18].exits = "out"
      region.rooms[18].links = {}
        region.rooms[18].links.out = {}
          region.rooms[18].links.out.to = 2300
          region.rooms[18].links.out.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly xx;[k1:摘星子]wu;[aw:3:jump valley]hi;wu;wu"
      region.rooms[19].name = "天山顶峰"
      region.rooms[19].zone = "星宿海"
      region.rooms[19].id = 2302
      region.rooms[19].desc = "    这里是天山顶峰。从这里向周围望去，帕米尔高原的风光尽收眼底。东面一条小路可以下山。山风(wind)凛冽，极为强劲，几乎无法站立。"
      region.rooms[19].exits = "eastdown"
      region.rooms[19].links = {}
        region.rooms[19].links.ed = {}
          region.rooms[19].links.ed.to = 2300
          region.rooms[19].links.ed.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly xx;su"
      region.rooms[20].name = "天山山路"
      region.rooms[20].zone = "星宿海"
      region.rooms[20].id = 2303
      region.rooms[20].desc = "    这里是天山东麓，山风从山上吹来，你冷得瑟瑟发抖。路边是一片草原。路尽头松林下一位壮汉正在长啸练功。北上就是人人害怕的灵鹫宫了."
      region.rooms[20].exits = "south|northup|northdown"
      region.rooms[20].links = {}
        region.rooms[20].links.nu = {}
          region.rooms[20].links.nu.to = 2060
          region.rooms[20].links.nu.con = ""
        region.rooms[20].links.nd = {}
          region.rooms[20].links.nd.to = 2285
          region.rooms[20].links.nd.con = ""
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 2304
          region.rooms[20].links.s.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly xx;su;s"
      region.rooms[21].name = "天山山路"
      region.rooms[21].zone = "星宿海"
      region.rooms[21].id = 2304
      region.rooms[21].desc = "    这里是天山东麓，山风从山上吹来，你冷得瑟瑟发抖。路边是一片草原。草原上一位牧羊人赶着一群羊。这里向东可以下山。北边传来阵阵猛兽的啸声。"
      region.rooms[21].exits = "north|eastdown"
      region.rooms[21].links = {}
        region.rooms[21].links.ed = {}
          region.rooms[21].links.ed.to = 2305
          region.rooms[21].links.ed.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 2303
          region.rooms[21].links.n.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly xx;su;s;ed"
      region.rooms[22].name = "天山脚下"
      region.rooms[22].zone = "星宿海"
      region.rooms[22].id = 2305
      region.rooms[22].desc = "    这里是天山脚下，西面是高耸入云的天山。天晴的时候可以看到山顶上的冰川。一道天山将西域分为两半。北疆是西域各族的聚居区，南疆是无边的塔克拉马干大沙漠。"
      region.rooms[22].exits = "westup|northwest|southeast|southwest"
      region.rooms[22].links = {}
        region.rooms[22].links.wu = {}
          region.rooms[22].links.wu.to = 2304
          region.rooms[22].links.wu.con = ""
        region.rooms[22].links.sw = {}
          region.rooms[22].links.sw.to = 2967
          region.rooms[22].links.sw.con = ""
        region.rooms[22].links.nw = {}
          region.rooms[22].links.nw.to = 2306
          region.rooms[22].links.nw.con = ""
        region.rooms[22].links.se = {}
          region.rooms[22].links.se.to = 2312
          region.rooms[22].links.se.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly xx;su;s;ed;nw"
      region.rooms[23].name = "伊犁"
      region.rooms[23].zone = "星宿海"
      region.rooms[23].id = 2306
      region.rooms[23].desc = "    这里是一座维吾尔族聚居的小镇。镇上人来人往，十分热闹。只是他们说的话你听不懂。镇西有家小店铺，西北边人声鼎沸，好像在举行什么比赛。东面有家院落，院门口有棵大树。北边是一家马厩。"
      region.rooms[23].exits = "northwest|north|east|southeast|west"
      region.rooms[23].links = {}
        region.rooms[23].links.se = {}
          region.rooms[23].links.se.to = 2305
          region.rooms[23].links.se.con = ""
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 2308
          region.rooms[23].links.e.con = ""
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 2307
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.nw = {}
          region.rooms[23].links.nw.to = 2311
          region.rooms[23].links.nw.con = ""
        region.rooms[23].links.n = {}
          region.rooms[23].links.n.to = 2310
          region.rooms[23].links.n.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly xx;su;s;ed;nw;w"
      region.rooms[24].name = "杂货铺"
      region.rooms[24].zone = "星宿海"
      region.rooms[24].id = 2307
      region.rooms[24].desc = "    这是一个杂货铺。房屋内铺着地毯。店老板坐在地毯上，旁边堆着他的货。墙上有个牌子，是个价目表(sign)。"
      region.rooms[24].exits = "east"
      region.rooms[24].links = {}
        region.rooms[24].links.e = {}
          region.rooms[24].links.e.to = 2306
          region.rooms[24].links.e.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly xx;su;s;ed;nw;e"
      region.rooms[25].name = "巴依家院"
      region.rooms[25].zone = "星宿海"
      region.rooms[25].id = 2308
      region.rooms[25].desc = "    这是一个巴依家的庭院。门口大树的树荫投到院子里，让人觉得很凉快。院子东面是巴依的客厅，西边就是小镇大街。"
      region.rooms[25].exits = "east|west"
      region.rooms[25].links = {}
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 2306
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 2309
          region.rooms[25].links.e.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly xx;su;s;ed;nw;e;e"
      region.rooms[26].name = "巴依家客厅"
      region.rooms[26].zone = "星宿海"
      region.rooms[26].id = 2309
      region.rooms[26].desc = "    这是巴依家的客厅。地上铺着波斯地毯，木架上摆这中原的瓷器。看得出这家的主人一定很有钱。"
      region.rooms[26].exits = "west"
      region.rooms[26].links = {}
        region.rooms[26].links.w = {}
          region.rooms[26].links.w.to = 2308
          region.rooms[26].links.w.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly xx;su;s;ed;nw;n"
      region.rooms[27].name = "马厩"
      region.rooms[27].zone = "星宿海"
      region.rooms[27].id = 2310
      region.rooms[27].desc = "    这是北疆小镇的马厩，常年供应新鲜草料。这里地处会疆，边民古朴而好客，把所有远方来宾均作兄弟看待。马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再梳理得清清爽爽，一直伺候到客人上路。马厩旧木柱上钉着一块破木牌(paizi)。        马厩中堆放著几堆草料，正中有一口泔槽。"
      region.rooms[27].exits = "south"
      region.rooms[27].links = {}
        region.rooms[27].links.s = {}
          region.rooms[27].links.s.to = 2306
          region.rooms[27].links.s.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly xx;su;s;ed;nw;nw"
      region.rooms[28].name = "赛马场"
      region.rooms[28].zone = "星宿海"
      region.rooms[28].id = 2311
      region.rooms[28].desc = "    这里是小镇的赛马场。场上正在举行维吾尔族的「姑娘追」表演。一个小伙子可以找一个姑娘并骑慢驰到一处折返点。去的路上小伙子可以对姑娘随便挑逗。回来时姑娘则可以用鞭子抽打小伙子。当然，如果姑娘喜欢这个小伙子，落鞭就会轻些。否则的话，有小伙子好受的。"
      region.rooms[28].exits = "southeast"
      region.rooms[28].links = {}
        region.rooms[28].links.se = {}
          region.rooms[28].links.se.to = 2306
          region.rooms[28].links.se.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly xx;su;s;ed;se"
      region.rooms[29].name = "丝绸之路"
      region.rooms[29].zone = "星宿海"
      region.rooms[29].id = 2312
      region.rooms[29].desc = "    这是一条中原和西域之间的商道。西面是一望无际的大沙漠，传说那里常有盗匪出没。西北则通向一片连绵的山脉，东面就是通向中原的路。路边有一块石碑(shibei)。"
      region.rooms[29].exits = "northwest|east|west|southwest"
      region.rooms[29].links = {}
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 2313
          region.rooms[29].links.e.con = ""
        region.rooms[29].links.sw = {}
          region.rooms[29].links.sw.to = 2151
          region.rooms[29].links.sw.con = ""
        region.rooms[29].links.nw = {}
          region.rooms[29].links.nw.to = 2305
          region.rooms[29].links.nw.con = ""
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 2975
          region.rooms[29].links.w.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly xx;su;s;ed;se;e"
      region.rooms[30].name = "丝绸之路"
      region.rooms[30].zone = "星宿海"
      region.rooms[30].id = 2313
      region.rooms[30].desc = "    这是一条中原和西域之间的商道。南面连绵的祁连山脉在阳光的照射下好像是一条玉带。东边是中原，西面则通往西域。西南有一座黄沙堆积形成的山(mount)。这里的茅草(grass)似乎很密很厚。"
      region.rooms[30].exits = "southeast|west"
      region.rooms[30].links = {}
        region.rooms[30].links["climb mount"] = {}
          region.rooms[30].links["climb mount"].to = 2318
          region.rooms[30].links["climb mount"].con = ""
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 2312
          region.rooms[30].links.w.con = ""
        region.rooms[30].links.se = {}
          region.rooms[30].links.se.to = 2314
          region.rooms[30].links.se.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly xx;su;s;ed;se;e;se"
      region.rooms[31].name = "丝绸之路"
      region.rooms[31].zone = "星宿海"
      region.rooms[31].id = 2314
      region.rooms[31].desc = "    这是一条中原和西域之间的商道。南面连绵的祁连山脉在阳光的照射下好像是一条玉带。东边是中原，西面则通往西域。"
      region.rooms[31].exits = "northwest|east|west"
      region.rooms[31].links = {}
        region.rooms[31].links.nw = {}
          region.rooms[31].links.nw.to = 2313
          region.rooms[31].links.nw.con = ""
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 2315
          region.rooms[31].links.e.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly xx;su;s;ed;se;e;se;e"
      region.rooms[32].name = "丝绸之路"
      region.rooms[32].zone = "星宿海"
      region.rooms[32].id = 2315
      region.rooms[32].desc = "    这是一条中原和西域之间的商道。东边有一座雄伟的关隘，西面则通往西域。"
      region.rooms[32].exits = "east|west"
      region.rooms[32].links = {}
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 2314
          region.rooms[32].links.w.con = ""
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 2316
          region.rooms[32].links.e.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly xx;su;s;ed;se;e;se;e;e"
      region.rooms[33].name = "嘉峪关"
      region.rooms[33].zone = "星宿海"
      region.rooms[33].id = 2316
      region.rooms[33].desc = "    这是长城最西的关隘。岁月沧桑，仍掩不住它的风采。群山环抱之下，更显它的雄浑。由于西域安定，久无战事，边关守军已大为减少。一条大道向东延伸通向中原。出关向西，便是著名的“丝绸之路”。"
      region.rooms[33].exits = "eastup|west"
      region.rooms[33].links = {}
        region.rooms[33].links.w = {}
          region.rooms[33].links.w.to = 2315
          region.rooms[33].links.w.con = ""
        region.rooms[33].links.eu = {}
          region.rooms[33].links.eu.to = 2317
          region.rooms[33].links.eu.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly xx;su;s;ed;se;e;se;e;e;eu"
      region.rooms[34].name = "六盘山"
      region.rooms[34].zone = "星宿海"
      region.rooms[34].id = 2317
      region.rooms[34].desc = "    这是一座不太高的小山。山顶望去，瓦蓝的天空(sky)飘着几朵淡淡的白云。一群大雁发出「嘎嘎」的叫声，从头上飞过。西面山下长城的残垣断壁依稀可辨。长城的尽头是一座雄伟的关隘。路旁有一处悬崖之上刻着首词(poem)。"
      region.rooms[34].exits = "southdown|westdown"
      region.rooms[34].links = {}
        region.rooms[34].links.wd = {}
          region.rooms[34].links.wd.to = 2316
          region.rooms[34].links.wd.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly xx;su;s;ed;se;e;climb mount"
      region.rooms[35].name = "鸣沙山"
      region.rooms[35].zone = "星宿海"
      region.rooms[35].id = 2318
      region.rooms[35].desc = "    这是一座黄沙堆积形成的山。微风吹动，沙山发出嗡嗡的响声。故而当地人称之为鸣沙山。沙土中似乎有一种虫子在蠕动。"
      region.rooms[35].exits = "northeast|west"
      region.rooms[35].links = {}
        region.rooms[35].links.ne = {}
          region.rooms[35].links.ne.to = 2313
          region.rooms[35].links.ne.con = ""
        region.rooms[35].links.w = {}
          region.rooms[35].links.w.to = 2319
          region.rooms[35].links.w.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly xx;su;s;ed;se;e;climb mount;w"
      region.rooms[36].name = "月儿泉"
      region.rooms[36].zone = "星宿海"
      region.rooms[36].id = 2319
      region.rooms[36].desc = "    出乎你的意料之外，在沙漠中竟然有泉水。一泓清澈的泉水形成一个月牙的形状，因而得名月儿泉。南面是一片峭壁(cliff)，东边传来嗡嗡的声响。"
      region.rooms[36].exits = "east"
      region.rooms[36].links = {}
        region.rooms[36].links.e = {}
          region.rooms[36].links.e.to = 2318
          region.rooms[36].links.e.con = ""
        region.rooms[36].links["enter hole"] = {}
          region.rooms[36].links["enter hole"].to = 2320
          region.rooms[36].links["enter hole"].con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly xx;su;s;ed;se;e;climb mount;w;enter hole"
      region.rooms[37].name = "莫高窟"
      region.rooms[37].zone = "星宿海"
      region.rooms[37].id = 2320
      region.rooms[37].desc = "    这里墙壁上绘制着与佛教相关的画面，有仙女飞天，还有反弹琵琶。洞中还有很多佛像和经书。你被这些瑰丽的文化之宝惊呆了。"
      region.rooms[37].exits = "north"
      region.rooms[37].links = {}
        region.rooms[37].links.n = {}
          region.rooms[37].links.n.to = 2319
          region.rooms[37].links.n.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly xx;[k1:摘星子]n;[aw:3:flatter 星宿老仙]nw;w"
      region.rooms[38].name = "石道"
      region.rooms[38].zone = "星宿海"
      region.rooms[38].id = 2966
      region.rooms[38].links = {}
        region.rooms[38].links.e = {}
          region.rooms[38].links.e.to = 2288
          region.rooms[38].links.e.con = ""
        region.rooms[38].links.nw = {}
          region.rooms[38].links.nw.to = 2290
          region.rooms[38].links.nw.con = ""
        region.rooms[38].links.enter = {}
          region.rooms[38].links.enter.to = 2289
          region.rooms[38].links.enter.con = "k1:采花子"
      region.rooms[38].exits = "northwest|east|enter"
      region.rooms[38].desc = "    这是星宿海边有人用石头铺成的一条小道，周围弥漫着沼泽的瘴气和一种说不出来的香味。路边有个石洞。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly xx;su;s;ed;sw"
      region.rooms[39].name = "南疆沙漠"
      region.rooms[39].zone = "星宿海"
      region.rooms[39].id = 2967
      region.rooms[39].desc = "    这就是浩瀚的塔克拉马干大沙漠，一走进来，你仿佛迷失了方向。你感到口内十分焦渴，还是快些离开吧。"
      region.rooms[39].exits = "north|southwest|southeast|south|northwest|east|northeast|west"
      region.rooms[39].links = {}
        region.rooms[39].links.ne = {}
          region.rooms[39].links.ne.to = 2305
          region.rooms[39].links.ne.con = ""
        region.rooms[39].links.nw = {}
          region.rooms[39].links.nw.to = 2968
          region.rooms[39].links.nw.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly xx;su;s;ed;sw;nw"
      region.rooms[40].name = "南疆沙漠"
      region.rooms[40].zone = "星宿海"
      region.rooms[40].id = 2968
      region.rooms[40].desc = "    这就是浩瀚的塔克拉马干大沙漠，一走进来，你仿佛迷失了方向。你感到口内十分焦渴，还是快些离开吧。"
      region.rooms[40].exits = "north|southwest|southeast|south|northwest|east|northeast|west"
      region.rooms[40].links = {}
        region.rooms[40].links.sw = {}
          region.rooms[40].links.sw.to = 2969
          region.rooms[40].links.sw.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly xx;su;s;ed;sw;nw;sw"
      region.rooms[41].name = "南疆沙漠"
      region.rooms[41].zone = "星宿海"
      region.rooms[41].id = 2969
      region.rooms[41].desc = "    这就是浩瀚的塔克拉马干大沙漠，一走进来，你仿佛迷失了方向。你感到口内十分焦渴，还是快些离开吧。"
      region.rooms[41].exits = "north|southwest|southeast|south|northwest|east|northeast|west"
      region.rooms[41].links = {}
        region.rooms[41].links.w = {}
          region.rooms[41].links.w.to = 2972
          region.rooms[41].links.w.con = ""
        region.rooms[41].links.se = {}
          region.rooms[41].links.se.to = 2970
          region.rooms[41].links.se.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly xx;su;s;ed;sw;nw;sw;se"
      region.rooms[42].name = "南疆沙漠"
      region.rooms[42].zone = "星宿海"
      region.rooms[42].id = 2970
      region.rooms[42].desc = "    这就是浩瀚的塔克拉马干大沙漠，一走进来，你仿佛迷失了方向。你感到口内十分焦渴，还是快些离开吧。"
      region.rooms[42].exits = "north|southwest|southeast|south|northwest|east|northeast|west"
      region.rooms[42].links = {}
        region.rooms[42].links.ne = {}
          region.rooms[42].links.ne.to = 2971
          region.rooms[42].links.ne.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly xx;su;s;ed;sw;nw;sw;se;ne"
      region.rooms[43].name = "沙漠绿洲"
      region.rooms[43].zone = "星宿海"
      region.rooms[43].id = 2971
      region.rooms[43].desc = "    在沙漠的尽头出现了一个绿洲。灌木丛中有一眼坎儿井。井台上有一个木杯专供口渴的行人喝水。井边是一块瓜地。"
      region.rooms[43].exits = "northeast|southwest"
      region.rooms[43].links = {}
        region.rooms[43].links.ne = {}
          region.rooms[43].links.ne.to = 2305
          region.rooms[43].links.ne.con = ""
        region.rooms[43].links.sw = {}
          region.rooms[43].links.sw.to = 2970
          region.rooms[43].links.sw.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly xx;su;s;ed;sw;nw;sw;w"
      region.rooms[44].name = "沙漠绿洲"
      region.rooms[44].zone = "星宿海"
      region.rooms[44].id = 2972
      region.rooms[44].desc = "    这里是沙漠中不多的一块绿洲，向南不远隐约可以看见一座黑黑的山洞。随风传来一些叮叮当当的打铁的声音。也不知是谁在打造什么。"
      region.rooms[44].exits = "south|east"
      region.rooms[44].links = {}
        region.rooms[44].links.e = {}
          region.rooms[44].links.e.to = 2969
          region.rooms[44].links.e.con = ""
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 2973
          region.rooms[44].links.s.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly xx;su;s;ed;sw;nw;sw;w;s"
      region.rooms[45].name = "玄兵古洞"
      region.rooms[45].zone = "星宿海"
      region.rooms[45].id = 2973
      region.rooms[45].desc = "    这里是玄兵古洞洞口，里面传来阵阵的捶打声。似乎在锻造着什么。隐隐的透着一股萧杀的气息。"
      region.rooms[45].exits = "enter|east"
      region.rooms[45].links = {}
        region.rooms[45].links.enter = {}
          region.rooms[45].links.enter.to = 2974
          region.rooms[45].links.enter.con = ""
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 2972
          region.rooms[45].links.n.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly xx;su;s;ed;sw;nw;sw;w;s;enter"
      region.rooms[46].name = "玄兵古洞"
      region.rooms[46].zone = "星宿海"
      region.rooms[46].id = 2974
      region.rooms[46].desc = "    这里是玄兵古洞，四面洞壁之上结满了石英的柱状结晶体，显得十分漂亮。前方一个巨大的炉子前站着一位长髯老者正看着炉火想着什么心事，旁边几个彪形大汉正挥舞着锤头敲打着一块似乎总也烧不红的什么金属。旁边仔细的放着几把刚刚出炉的兵器。那种骇人的杀气竟是从这些兵器上散发出来的。"
      region.rooms[46].exits = "out"
      region.rooms[46].links = {}
        region.rooms[46].links.out = {}
          region.rooms[46].links.out.to = 2973
          region.rooms[46].links.out.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly xx;su;s;ed;se;w"
      region.rooms[47].name = "大沙漠"
      region.rooms[47].zone = "星宿海"
      region.rooms[47].id = 2975
      region.rooms[47].desc = "    这是一片一望无际的大沙漠。你一进来就迷失了方向。看来要走出这块沙漠并非易事。"
      region.rooms[47].exits = "south|north|east|west"
      region.rooms[47].links = {}
        region.rooms[47].links.e = {}
          region.rooms[47].links.e.to = 2312
          region.rooms[47].links.e.con = ""
        region.rooms[47].links.w = {}
          region.rooms[47].links.w.to = 2975
          region.rooms[47].links.w.con = ""
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 2975
          region.rooms[47].links.s.con = ""
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 2976
          region.rooms[47].links.n.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "fly xx;su;s;ed;se;w;n"
      region.rooms[48].name = "大沙漠"
      region.rooms[48].zone = "星宿海"
      region.rooms[48].id = 2976
      region.rooms[48].desc = "    这是一片一望无际的大沙漠。你一进来就迷失了方向。看来要走出这块沙漠并非易事。"
      region.rooms[48].exits = "south|north|east|west"
      region.rooms[48].links = {}
        region.rooms[48].links.e = {}
          region.rooms[48].links.e.to = 2976
          region.rooms[48].links.e.con = ""
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 2977
          region.rooms[48].links.s.con = ""
        region.rooms[48].links.w = {}
          region.rooms[48].links.w.to = 2976
          region.rooms[48].links.w.con = ""
        region.rooms[48].links.n = {}
          region.rooms[48].links.n.to = 2976
          region.rooms[48].links.n.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly xx;su;s;ed;se;w;n;s"
      region.rooms[49].name = "大沙漠"
      region.rooms[49].zone = "星宿海"
      region.rooms[49].id = 2977
      region.rooms[49].desc = "    这是一片一望无际的大沙漠。你一进来就迷失了方向。看来要走出这块沙漠并非易事。"
      region.rooms[49].exits = "south|north|east|west"
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 2978
          region.rooms[49].links.e.con = ""
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 2049
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 2976
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.n = {}
          region.rooms[49].links.n.to = 2976
          region.rooms[49].links.n.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly xx;su;s;ed;se;w;n;s;e"
      region.rooms[50].name = "大沙漠"
      region.rooms[50].zone = "星宿海"
      region.rooms[50].id = 2978
      region.rooms[50].desc = "    这是一片一望无际的大沙漠。你一进来就迷失了方向。看来要走出这块沙漠并非易事。"
      region.rooms[50].exits = "south|north|east|west"
      region.rooms[50].links = {}
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 2975
          region.rooms[50].links.e.con = ""
        region.rooms[50].links.s = {}
          region.rooms[50].links.s.to = 2978
          region.rooms[50].links.s.con = ""
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 2977
          region.rooms[50].links.w.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 2978
          region.rooms[50].links.n.con = ""
  region.center = 2285
return region