local region = {}
  region.cmd = "fly xyl"
  region.name = "逍遥林"
  region.id = "xyl"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly xyl"
      region.rooms[1].name = "青草坪"
      region.rooms[1].zone = "逍遥林"
      region.rooms[1].id = 2742
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 2752
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 2750
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 2743
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 2748
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "south|east|north|west"
      region.rooms[1].desc = "    这里是树林中的一片比较大的空地，名曰：青草坪。因为处于密林之中所以这里平时很少有人来，但是不知道为什么，这里却经常有人迹出现。你看，又一个来了。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly xyl;w"
      region.rooms[2].name = "林间小道"
      region.rooms[2].zone = "逍遥林"
      region.rooms[2].id = 2743
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 2742
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 2744
          region.rooms[2].links.w.con = ""
      region.rooms[2].exits = "east|west"
      region.rooms[2].desc = "    这是一条长长的林间小道，从东边一直通到西边，一眼望去，看不到路的尽头。两旁百花争艳。令人留连忘返。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly xyl;w;w"
      region.rooms[3].name = "林间小道"
      region.rooms[3].zone = "逍遥林"
      region.rooms[3].id = 2744
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 2743
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 2747
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 2745
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 2746
          region.rooms[3].links.n.con = ""
      region.rooms[3].exits = "south|north|east|west"
      region.rooms[3].desc = "    这是一条长长的林间小道，从东边一直通到西边，一眼望去，看不到路的尽头。两旁百花争艳。令人留连忘返。南边好象有香味散发出来，北边是个兵器房。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly xyl;w;w;s"
      region.rooms[4].name = "酒家"
      region.rooms[4].zone = "逍遥林"
      region.rooms[4].id = 2745
      region.rooms[4].links = {}
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 2744
          region.rooms[4].links.n.con = ""
      region.rooms[4].exits = "north"
      region.rooms[4].desc = "    这里是树林中的一间小小的酒家，地方虽然不大，但是也有不少逍遥派的弟子光顾这里。你终于找到香味的来源了，看着可口的饭菜，你忍不住也想叫 (order)一份了。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly xyl;w;w;n"
      region.rooms[5].name = "打铁屋"
      region.rooms[5].zone = "逍遥林"
      region.rooms[5].id = 2746
      region.rooms[5].links = {}
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 2744
          region.rooms[5].links.s.con = ""
      region.rooms[5].exits = "south"
      region.rooms[5].desc = "    这里是树林深处的一间小石屋，看来是打造兵器的，屋子中有个大火炉好烫的呢，屋中还有一张石几，上面放在一些已经打造好的兵器。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly xyl;w;w;w"
      region.rooms[6].name = "小屋"
      region.rooms[6].zone = "逍遥林"
      region.rooms[6].id = 2747
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 2744
          region.rooms[6].links.e.con = ""
      region.rooms[6].exits = "east"
      region.rooms[6].desc = "    这是一间在树林中的小屋，屋子中间摆着几张大床，几张桌子，看来是个休息的地方，室中光线柔和，使人更增睡意。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly xyl;n"
      region.rooms[7].name = "林间小道"
      region.rooms[7].zone = "逍遥林"
      region.rooms[7].id = 2748
      region.rooms[7].links = {}
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 2742
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 2749
          region.rooms[7].links.n.con = ""
      region.rooms[7].exits = "south|north"
      region.rooms[7].desc = "    这是一条从南到北的林间小道，沿途风景极之清幽，参天古树，拔地而起，两旁百花争艳。令人留连忘返。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly xyl;n;n"
      region.rooms[8].name = "小木屋"
      region.rooms[8].zone = "逍遥林"
      region.rooms[8].id = 2749
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 2748
          region.rooms[8].links.s.con = ""
      region.rooms[8].exits = "south"
      region.rooms[8].desc = "    这是一间不是很大的木头屋子，这里看起来象个药室，室中摆放着各种不同的配药的用具和一些已经配好了的药。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly xyl;s"
      region.rooms[9].name = "林间小道"
      region.rooms[9].zone = "逍遥林"
      region.rooms[9].id = 2750
      region.rooms[9].links = {}
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 2751
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 2742
          region.rooms[9].links.n.con = ""
      region.rooms[9].exits = "south|north"
      region.rooms[9].desc = "    这是一条从南到北的林间小道，沿途风景极之清幽，参天古树，拔地而起，两旁百花争艳。令人留连忘返。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly xyl;s;s"
      region.rooms[10].name = "木屋"
      region.rooms[10].zone = "逍遥林"
      region.rooms[10].id = 2751
      region.rooms[10].links = {}
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 2750
          region.rooms[10].links.n.con = ""
      region.rooms[10].exits = "north"
      region.rooms[10].desc = "    这里是一间不大的木头屋子，但是麻雀虽小，五藏俱全，屋子中只是疏疏落落地摆着几件家具，所以也不显得怎么小。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly xyl;e"
      region.rooms[11].name = "林间小道"
      region.rooms[11].zone = "逍遥林"
      region.rooms[11].id = 2752
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 2756
          region.rooms[11].links.e.con = ""
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 2754
          region.rooms[11].links.s.con = ""
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 2742
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 2753
          region.rooms[11].links.n.con = ""
      region.rooms[11].exits = "south|north|east|west"
      region.rooms[11].desc = "    这是一条长长的林间小道，从东边一直通到西边，一眼望去，看不到路的尽头。两旁百花争艳。令人留连忘返。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly xyl;e;n"
      region.rooms[12].name = "石屋"
      region.rooms[12].zone = "逍遥林"
      region.rooms[12].id = 2753
      region.rooms[12].links = {}
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 2752
          region.rooms[12].links.s.con = ""
      region.rooms[12].exits = "south"
      region.rooms[12].desc = "    这是树林中的一间石屋，屋内显得什么清净和简朴，房间中并没有什么特别的摆设在这里，不会受到任何东西的骚扰，是个修炼内功的好地方。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly xyl;e;s"
      region.rooms[13].name = "木板路"
      region.rooms[13].zone = "逍遥林"
      region.rooms[13].id = 2754
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 2755
          region.rooms[13].links.s.con = ""
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 2752
          region.rooms[13].links.n.con = ""
      region.rooms[13].exits = "south|north"
      region.rooms[13].desc = "    这是一条用木板铺成的小道，虽然不是很长，但是却看得出铺得十分细心，连一些细微的疏忽也注意到了。道路两旁好种着一些奇花异树，使过路人有心旷神怡的感觉。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly xyl;e;s;s"
      region.rooms[14].name = "工匠屋"
      region.rooms[14].zone = "逍遥林"
      region.rooms[14].id = 2755
      region.rooms[14].links = {}
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 2754
          region.rooms[14].links.n.con = ""
      region.rooms[14].exits = "north"
      region.rooms[14].desc = "    这里也是一间木屋，屋子中的摆设什么简单，但是却有很多工具，锯子啦，刨子啦，锤子啦，还有满地的木屑，一看就知道是一个工匠的家。看！我们的巧匠正忙着呢，不过不知道他又在做什么呢？"
    region.rooms[15] = {}
      region.rooms[15].path = "fly xyl;e;e"
      region.rooms[15].name = "树林"
      region.rooms[15].zone = "逍遥林"
      region.rooms[15].id = 2756
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 2757
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 2756
          region.rooms[15].links.s.con = ""
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 2752
          region.rooms[15].links.w.con = ""
        region.rooms[15].links.n = {}
          region.rooms[15].links.n.to = 2756
          region.rooms[15].links.n.con = ""
      region.rooms[15].exits = "south|east|north|west"
      region.rooms[15].desc = "    这是一片茂密的树林。很多棵几十丈高的大树聚在一块，象一把把琼天大伞，连日月都被遮蔽得暗然无光。树林中还不时可以听到大自然发出的声响。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly xyl;e;e;e"
      region.rooms[16].name = "树林"
      region.rooms[16].zone = "逍遥林"
      region.rooms[16].id = 2757
      region.rooms[16].links = {}
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 2757
          region.rooms[16].links.e.con = ""
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 2757
          region.rooms[16].links.w.con = ""
        region.rooms[16].links.s = {}
          region.rooms[16].links.s.to = 2756
          region.rooms[16].links.s.con = ""
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 2758
          region.rooms[16].links.n.con = ""
      region.rooms[16].exits = "south|east|north|west"
      region.rooms[16].desc = "    这是一片茂密的树林。很多棵几十丈高的大树聚在一块，象一把把琼天大伞，连日月都被遮蔽得暗然无光。树林中还不时可以听到大自然发出的声响。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly xyl;e;e;e;n"
      region.rooms[17].name = "树林"
      region.rooms[17].zone = "逍遥林"
      region.rooms[17].id = 2758
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 2757
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 462
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 2758
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 2758
          region.rooms[17].links.n.con = ""
      region.rooms[17].exits = "south|east|north|west"
      region.rooms[17].desc = "    这是一片茂密的树林。很多棵几十丈高的大树聚在一块，象一把把琼天大伞，连日月都被遮蔽得暗然无光。树林中还不时可以听到大自然发出的声响。"
  region.center = 2742
return region