local region = {}
  region.cmd = "fly bj"
  region.name = "北京"
  region.id = "bj"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly bj"
      region.rooms[1].name = "天安门"
      region.rooms[1].zone = "北京紫禁城|北京"
      region.rooms[1].id = 962
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 982
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 1095
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 983
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 963
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "south|east|north|west"
      region.rooms[1].desc = "    这里就是天安门广场，灰色的城墙给人以庄严肃穆之感，再往北就是皇宫了。皇宫正门前有座小桥，一条护城河绕城而过。越过小桥向北望去，紫禁城的轮廓益发显得雄伟高大。一条笔直的大道横贯东西，东边是东长安街，西边是西长安街。南边是一条繁华的大道，从那往下有一座天桥，据说游人很多。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly bj;n"
      region.rooms[2].name = "小桥"
      region.rooms[2].zone = "北京紫禁城|北京"
      region.rooms[2].id = 963
      region.rooms[2].desc = "    这是一座破旧的石桥，桥下是护城河缓缓的流水。水看上去很清，据说曾有人在这里跳河(out)。这里是进皇宫正门的必经之路。"
      region.rooms[2].exits = "south|east|north|west"
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 964
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 962
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 965
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 966
          region.rooms[2].links.n.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly bj;n;e"
      region.rooms[3].name = "桥底东侧"
      region.rooms[3].zone = "北京紫禁城|北京"
      region.rooms[3].id = 964
      region.rooms[3].desc = "    这里是小桥东侧，一股寒风吹过，冷得你瑟瑟发抖，只想离开。"
      region.rooms[3].exits = "west"
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 963
          region.rooms[3].links.w.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly bj;n;w"
      region.rooms[4].name = "桥底西侧"
      region.rooms[4].zone = "北京紫禁城|北京"
      region.rooms[4].id = 965
      region.rooms[4].desc = "    这里是小桥西侧，一股寒风吹过，冷得你瑟瑟发抖，只想离开。"
      region.rooms[4].exits = "east"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 963
          region.rooms[4].links.e.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly bj;n;n"
      region.rooms[5].name = "皇宫正门"
      region.rooms[5].zone = "北京紫禁城|北京"
      region.rooms[5].id = 966
      region.rooms[5].desc = "    这便是皇宫正门。巍峨雄伟的城墙上，'紫禁城'三个大字十分显眼，气势辉煌。一张镶金边的告示(gaoshi)贴在墙上，许多官兵立在两旁。"
      region.rooms[5].exits = "south|north"
      region.rooms[5].links = {}
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 963
          region.rooms[5].links.s.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 967
          region.rooms[5].links.n.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly bj;e"
      region.rooms[6].name = "东长安街"
      region.rooms[6].zone = "北京"
      region.rooms[6].id = 982
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 1054
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 962
          region.rooms[6].links.w.con = ""
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 984
          region.rooms[6].links.n.con = ""
      region.rooms[6].exits = "north|east|west"
      region.rooms[6].desc = "    这里是东长安街，宽阔的街道上车水马龙，人来人往。向西走就是天安门了。由于王府井大街就在北边，许多人都往北去，那里人声鼎沸，似乎十分热闹。相比之下，东边就显得冷清多了。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly bj;w"
      region.rooms[7].name = "西长安街"
      region.rooms[7].zone = "北京"
      region.rooms[7].id = 983
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 962
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 1049
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 1036
          region.rooms[7].links.w.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 1051
          region.rooms[7].links.n.con = ""
      region.rooms[7].exits = "south|north|east|west"
      region.rooms[7].desc = "    这是一条宽阔的青石板街道，向东西两头延伸。往西望去，长长的街道看不到头。东边就是天安门。一阵阵喝采声不时从北边的戏院传来。南边就是京城最著名的‘回春堂’药店。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly bj;e;n"
      region.rooms[8].name = "王府井大街"
      region.rooms[8].zone = "北京"
      region.rooms[8].id = 984
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 985
          region.rooms[8].links.e.con = ""
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 986
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 982
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 993
          region.rooms[8].links.n.con = ""
      region.rooms[8].exits = "south|north|east|west"
      region.rooms[8].desc = "    你走在一条繁忙的街道上，车水马龙，人来人往。许多人都从南边走来，那里是东长安街。西边是一条宽阔的街道，不知为何却十分冷清。东边是一家钱庄，可以听到叮叮当当的金银声音。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly bj;e;n;e"
      region.rooms[9].name = "钱庄"
      region.rooms[9].zone = "北京"
      region.rooms[9].id = 985
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 984
          region.rooms[9].links.w.con = ""
      region.rooms[9].exits = "west"
      region.rooms[9].desc = "    这是一家老字号的钱庄，已有几百年的历史，在全国各地都有分店。它发行的银票信誉非常好，通行全国。不管你走到哪里，在任何一个本庄分店都可以任意存取。墙上挂着一个牌子(paizi)。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly bj;e;n;w"
      region.rooms[10].name = "街道"
      region.rooms[10].zone = "北京"
      region.rooms[10].id = 986
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 984
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 987
          region.rooms[10].links.w.con = ""
      region.rooms[10].exits = "east|west"
      region.rooms[10].desc = "    再往西就是鳌拜府了，谁也不敢往那儿去。东面是王府井大街。路边有个狗洞(dong)，几只懒狗正在那里探头。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly bj;e;n;w;w"
      region.rooms[11].name = "鳌府大门"
      region.rooms[11].zone = "北京"
      region.rooms[11].id = 987
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 986
          region.rooms[11].links.e.con = ""
        region.rooms[11].links["unwield all;w"] = {}
          region.rooms[11].links["unwield all;w"].to = 988
          region.rooms[11].links["unwield all;w"].con = ""
      region.rooms[11].exits = "east|west"
      region.rooms[11].desc = "    一座富丽堂皇的大宅院出现在你的眼前，两头高大的石狮子镇住了大门两侧。门额上悬挂一方横匾，写着‘满洲第一勇士鳌拜府’几个大字，门外有官兵把守，戒备森严。门上挂着两个灯笼，赫然写着“鳌”字。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly bj;e;n;w;w;unwield all;w"
      region.rooms[12].name = "鳌府大院"
      region.rooms[12].zone = "北京"
      region.rooms[12].id = 988
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 987
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 990
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 989
          region.rooms[12].links.n.con = ""
      region.rooms[12].exits = "north|east|west"
      region.rooms[12].desc = "    你走进大院，迎面是一个假山水池，池中立着一块巨大无比的翡翠，显然是鳌拜收刮来的宝物。水池的两旁种满了花草。北边是厨房，有一棵槐树，郁郁葱葱，遮盖了大半个院子，显得阴森恐怖。西边一条长廊走道通往后院，有几个官兵把守。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly bj;e;n;w;w;unwield all;w;n"
      region.rooms[13].name = "鳌府厨房"
      region.rooms[13].zone = "北京"
      region.rooms[13].id = 989
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 988
          region.rooms[13].links.s.con = ""
      region.rooms[13].exits = "south"
      region.rooms[13].desc = "    一进门，一股香气扑鼻而来，熏得你直流口水。灶台上满是油烟，一个肥肥胖胖的家伙正在炒菜,一看就象个大厨师。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly bj;e;n;w;w;unwield all;w;w"
      region.rooms[14].name = "鳌府后院"
      region.rooms[14].zone = "北京"
      region.rooms[14].id = 990
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 988
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 991
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 992
          region.rooms[14].links.n.con = ""
      region.rooms[14].exits = "north|east|west"
      region.rooms[14].desc = "    这里是鳌府后院，中心是一个大花园。西边一条长廊走道直通往鳌拜的卧房，有几个官兵把守。北边是书房。南边是鳌拜私设的牢房,牢门(men)是锁着的。"
    region.rooms[15] = {}
      region.rooms[15].attr = "danger"
      region.rooms[15].path = "fly bj;e;n;w;w;unwield all;w;w;w"
      region.rooms[15].name = "鳌拜卧房"
      region.rooms[15].zone = "北京"
      region.rooms[15].id = 991
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 990
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.n = {}
          region.rooms[15].links.n.to = 1014
          region.rooms[15].links.n.con = ""
      region.rooms[15].exits = "north|east"
      region.rooms[15].desc = "    这是鳌拜的卧房。鳌拜躺在床上睡着了，粗声粗气地打着呼噜。北边有一扇门(door)。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly bj;e;n;w;w;unwield all;w;w;n"
      region.rooms[16].name = "鳌拜书房"
      region.rooms[16].zone = "北京"
      region.rooms[16].id = 992
      region.rooms[16].links = {}
        region.rooms[16].links.s = {}
          region.rooms[16].links.s.to = 990
          region.rooms[16].links.s.con = ""
      region.rooms[16].exits = "south"
      region.rooms[16].desc = "    这里是鳌拜书房，却没有一本书。各种古玩琳琅满目，商周青铜、汉瓦当、唐三彩，珍珠宝石，应有尽有，只要拥有一件，就够你吃一辈子了。北面墙上有一副画。书桌上有一本书。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly bj;e;n;n"
      region.rooms[17].name = "王府井大街"
      region.rooms[17].zone = "北京"
      region.rooms[17].id = 993
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 994
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 995
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 984
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 997
          region.rooms[17].links.n.con = ""
      region.rooms[17].exits = "south|north|east|west"
      region.rooms[17].desc = "    这是一条宽阔的青石街道，向南北两头延伸。南边北边都是长长的街道，西边是著名的‘全聚德’酒楼，东边通往朝阳门。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly bj;e;n;n;e"
      region.rooms[18].name = "朝阳路"
      region.rooms[18].zone = "北京"
      region.rooms[18].id = 994
      region.rooms[18].links = {}
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 993
          region.rooms[18].links.w.con = ""
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 1058
          region.rooms[18].links.e.con = ""
      region.rooms[18].exits = "east|west"
      region.rooms[18].desc = "    这是一条东西走向的大道。西边人声鼎沸，十分热闹。东边就是朝阳门。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly bj;e;n;n;w"
      region.rooms[19].name = "全聚德酒楼"
      region.rooms[19].zone = "北京"
      region.rooms[19].id = 995
      region.rooms[19].links = {}
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 993
          region.rooms[19].links.e.con = ""
        region.rooms[19].links.u = {}
          region.rooms[19].links.u.to = 996
          region.rooms[19].links.u.con = ""
      region.rooms[19].exits = "up|east"
      region.rooms[19].desc = "    方圆数百里内提起全聚德酒楼可以说是无人不知，无人不晓。楼下布置简易，顾客多是匆匆的行人，买点包子、鸡腿、米酒就赶路去了。楼上是雅座。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly bj;e;n;n;w;u"
      region.rooms[20].name = "全聚德酒楼二楼"
      region.rooms[20].zone = "北京"
      region.rooms[20].id = 996
      region.rooms[20].links = {}
        region.rooms[20].links.d = {}
          region.rooms[20].links.d.to = 995
          region.rooms[20].links.d.con = ""
      region.rooms[20].exits = "down"
      region.rooms[20].desc = "    这里是雅座，文人学士经常在这里吟诗作画，富商土豪也在这里边吃喝边作交易。这里也是城里举办喜宴的最佳场所。墙上挂着价格牌子(paizi)。你站在楼上眺望京城，只觉得心旷神怡。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly bj;e;n;n;n"
      region.rooms[21].name = "王府井大街"
      region.rooms[21].zone = "北京"
      region.rooms[21].id = 997
      region.rooms[21].links = {}
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 1008
          region.rooms[21].links.w.con = ""
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 993
          region.rooms[21].links.s.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 998
          region.rooms[21].links.n.con = ""
      region.rooms[21].exits = "south|north|west"
      region.rooms[21].desc = "    这里是王府井大街的尽头。北边是一座富丽堂皇的大楼，门额上悬挂一方横匾，写着“康亲王府”四个大字，乃是康熙皇帝亲笔。西边通往地安门。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly bj;e;n;n;n;n"
      region.rooms[22].name = "康府大门"
      region.rooms[22].zone = "北京"
      region.rooms[22].id = 998
      region.rooms[22].links = {}
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 997
          region.rooms[22].links.s.con = ""
        region.rooms[22].links["unwield all;n"] = {}
          region.rooms[22].links["unwield all;n"].to = 999
          region.rooms[22].links["unwield all;n"].con = ""
      region.rooms[22].exits = "south|north"
      region.rooms[22].desc = "    一座富丽堂皇的大宅院出现在你的眼前，两头高大的石狮子镇住了大门两侧。门外有带刀侍卫把守，戒备森严。门上挂着两个灯笼，赫然写着大大的“康”字。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly bj;e;n;n;n;n;unwield all;n"
      region.rooms[23].name = "康府大院"
      region.rooms[23].zone = "北京"
      region.rooms[23].id = 999
      region.rooms[23].links = {}
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 1000
          region.rooms[23].links.e.con = ""
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 1001
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 998
          region.rooms[23].links.s.con = ""
        region.rooms[23].links.n = {}
          region.rooms[23].links.n.to = 1002
          region.rooms[23].links.n.con = ""
      region.rooms[23].exits = "south|north|east|west"
      region.rooms[23].desc = "    这是一个宽大的练武场，有几个武师在这里练功。其中一个秃顶和尚，东走走，西看看，好象是这儿的领头。还有一个身材瘦高的武师，两手别在腰后，似乎也有一身好武功。东面是一个小一些的练武场。北面是后院。西边有个武器库。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly bj;e;n;n;n;n;unwield all;n;e"
      region.rooms[24].name = "练武场"
      region.rooms[24].zone = "北京"
      region.rooms[24].id = 1000
      region.rooms[24].links = {}
        region.rooms[24].links.w = {}
          region.rooms[24].links.w.to = 999
          region.rooms[24].links.w.con = ""
      region.rooms[24].exits = "west"
      region.rooms[24].desc = "    这是一个练武场,由巨大的花岗岩石板铺就,竖立着几个木人。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly bj;e;n;n;n;n;unwield all;n;w"
      region.rooms[25].name = "武器库"
      region.rooms[25].zone = "北京"
      region.rooms[25].id = 1001
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 999
          region.rooms[25].links.e.con = ""
      region.rooms[25].exits = "east"
      region.rooms[25].desc = "    这里是武器库，架上摆满了各种武器,任由武士门挑选。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly bj;e;n;n;n;n;unwield all;n;n"
      region.rooms[26].name = "康府后院"
      region.rooms[26].zone = "北京"
      region.rooms[26].id = 1002
      region.rooms[26].links = {}
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 1003
          region.rooms[26].links.e.con = ""
        region.rooms[26].links.w = {}
          region.rooms[26].links.w.to = 1004
          region.rooms[26].links.w.con = ""
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 999
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.n = {}
          region.rooms[26].links.n.to = 1006
          region.rooms[26].links.n.con = ""
      region.rooms[26].exits = "south|north|east|west"
      region.rooms[26].desc = "    这里是康府后院，西首是一个小花园。北边有一条长廊走道直通往内堂。东边是一间马棚。南边就是康亲王最爱去的私人练武场。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly bj;e;n;n;n;n;unwield all;n;n;e"
      region.rooms[27].name = "马棚"
      region.rooms[27].zone = "北京"
      region.rooms[27].id = 1003
      region.rooms[27].links = {}
        region.rooms[27].links.w = {}
          region.rooms[27].links.w.to = 1002
          region.rooms[27].links.w.con = ""
      region.rooms[27].exits = "west"
      region.rooms[27].desc = "    这里是康亲王府的马棚，其中好马无数。刚一进门，马儿就冲你“恢恢”直叫。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly bj;e;n;n;n;n;unwield all;n;n;w"
      region.rooms[28].name = "康府花园"
      region.rooms[28].zone = "北京"
      region.rooms[28].id = 1004
      region.rooms[28].links = {}
        region.rooms[28].links.e = {}
          region.rooms[28].links.e.to = 1002
          region.rooms[28].links.e.con = ""
        region.rooms[28].links.n = {}
          region.rooms[28].links.n.to = 1005
          region.rooms[28].links.n.con = ""
      region.rooms[28].exits = "north|east"
      region.rooms[28].desc = "    这是一个小花园，虽然花儿不太多，却十分幽雅清洁，显是平日有人修整打扫。花园北边是一间佛堂。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly bj;e;n;n;n;n;unwield all;n;n;w;n"
      region.rooms[29].name = "佛堂"
      region.rooms[29].zone = "北京"
      region.rooms[29].id = 1005
      region.rooms[29].links = {}
        region.rooms[29].links.s = {}
          region.rooms[29].links.s.to = 1004
          region.rooms[29].links.s.con = ""
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 1006
          region.rooms[29].links.e.con = ""
      region.rooms[29].exits = "south|east"
      region.rooms[29].desc = "    这是一间佛堂，墙和地板都是砖(brick)砌的。里供着一尊如来佛像(foxiang)，佛像前是一张供桌。桌上点着盏油灯。屋里有些昏暗。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly bj;e;n;n;n;n;unwield all;n;n;n"
      region.rooms[30].name = "康府内堂"
      region.rooms[30].zone = "北京"
      region.rooms[30].id = 1006
      region.rooms[30].links = {}
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 1005
          region.rooms[30].links.w.con = ""
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 1002
          region.rooms[30].links.s.con = ""
        region.rooms[30].links.n = {}
          region.rooms[30].links.n.to = 1007
          region.rooms[30].links.n.con = ""
      region.rooms[30].exits = "south|north|west"
      region.rooms[30].desc = "    这里是康府内堂，一个仆役正在和丫环们聊天。南边是康府后院，北边是书房，西边是一座佛堂。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly bj;e;n;n;n;n;unwield all;n;n;n;n"
      region.rooms[31].name = "康亲王书房"
      region.rooms[31].zone = "北京"
      region.rooms[31].id = 1007
      region.rooms[31].links = {}
        region.rooms[31].links.s = {}
          region.rooms[31].links.s.to = 1006
          region.rooms[31].links.s.con = ""
      region.rooms[31].exits = "south"
      region.rooms[31].desc = "    这里是康亲王书房，房中书架上整整齐齐地堆放着很多书。不过书上积了一些灰尘，显然是很久没有动过了。而书橱里的几件精巧玉器却更显得玲珑剔透，光彩照人。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly bj;e;n;n;n;w"
      region.rooms[32].name = "地安门东大街"
      region.rooms[32].zone = "北京"
      region.rooms[32].id = 1008
      region.rooms[32].links = {}
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 997
          region.rooms[32].links.e.con = ""
        region.rooms[32].links.s = {}
          region.rooms[32].links.s.to = 1009
          region.rooms[32].links.s.con = ""
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 1015
          region.rooms[32].links.w.con = ""
      region.rooms[32].exits = "south|east|west"
      region.rooms[32].desc = "    这是一条东西走向的大道。西边通往地安门。东边通往王府井。南边就是东厂了，一般人都不敢往那儿去。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly bj;e;n;n;n;w;s"
      region.rooms[33].name = "东厂大门"
      region.rooms[33].zone = "北京"
      region.rooms[33].id = 1009
      region.rooms[33].links = {}
        region.rooms[33].links.s = {}
          region.rooms[33].links.s.to = 1010
          region.rooms[33].links.s.con = "k1:官兵"
        region.rooms[33].links.n = {}
          region.rooms[33].links.n.to = 1008
          region.rooms[33].links.n.con = ""
      region.rooms[33].exits = "south|north"
      region.rooms[33].desc = "    这里就是东厂大门，可以看到里面有许多太监。穿着制服的官兵正在操练，不时地传来呐喊声。如果你不想找死的话，最好还是赶快离开。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly bj;e;n;n;n;w;s;|!k1:官兵:s|"
      region.rooms[34].name = "兵营"
      region.rooms[34].zone = "北京"
      region.rooms[34].id = 1010
      region.rooms[34].links = {}
        region.rooms[34].links.s = {}
          region.rooms[34].links.s.to = 1011
          region.rooms[34].links.s.con = "k1:官兵"
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 1009
          region.rooms[34].links.n.con = ""
      region.rooms[34].exits = "south|north"
      region.rooms[34].desc = "    这里是兵营，密密麻麻到处都是官兵，有的在武将的指挥下列队操练，有的独自在练功，有的坐着、躺着正在休息。还有些太监在四处走动。南边有一扇铁门(door)。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly bj;e;n;n;n;w;s;|!k1:官兵:s|;|!k1:官兵:s|"
      region.rooms[35].name = "东厂兵器库"
      region.rooms[35].zone = "北京"
      region.rooms[35].id = 1011
      region.rooms[35].links = {}
        region.rooms[35].links.sw = {}
          region.rooms[35].links.sw.to = 1012
          region.rooms[35].links.sw.con = ""
        region.rooms[35].links.n = {}
          region.rooms[35].links.n.to = 1010
          region.rooms[35].links.n.con = ""
      region.rooms[35].exits = "north|southwest"
      region.rooms[35].desc = "    这里是兵器库，到处银光闪闪，让人眼花缭乱。宝刀、宝剑、金箍棒，大刀、长剑、哨棒，短刀、短剑、短棍，各色各样的兵器应有尽有，你一时不知道挑什么好。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly bj;e;n;n;n;w;s;|!k1:官兵:s|;|!k1:官兵:s|;sw"
      region.rooms[36].name = "东厂暗道"
      region.rooms[36].zone = "北京"
      region.rooms[36].id = 1012
      region.rooms[36].links = {}
        region.rooms[36].links.ne = {}
          region.rooms[36].links.ne.to = 1011
          region.rooms[36].links.ne.con = ""
        region.rooms[36].links.sw = {}
          region.rooms[36].links.sw.to = 1013
          region.rooms[36].links.sw.con = ""
      region.rooms[36].exits = "northeast|southwest"
      region.rooms[36].desc = "    这是一条暗道，是专为鳌拜从鳌府直接到东厂用的。"
    region.rooms[37] = {}
      region.rooms[37].path = "fly bj;e;n;w;w;unwield all;w;w;w;n;ne"
      region.rooms[37].name = "东厂暗道"
      region.rooms[37].zone = "北京"
      region.rooms[37].id = 1013
      region.rooms[37].links = {}
        region.rooms[37].links.ne = {}
          region.rooms[37].links.ne.to = 1012
          region.rooms[37].links.ne.con = ""
        region.rooms[37].links.sw = {}
          region.rooms[37].links.sw.to = 1014
          region.rooms[37].links.sw.con = ""
      region.rooms[37].exits = "northeast|southwest"
      region.rooms[37].desc = "    这是一条暗道，是专为鳌拜从鳌府直接到东厂用的。"
    region.rooms[38] = {}
      region.rooms[38].path = "fly bj;e;n;w;w;unwield all;w;w;w;n"
      region.rooms[38].name = "东厂暗道"
      region.rooms[38].zone = "北京"
      region.rooms[38].id = 1014
      region.rooms[38].links = {}
        region.rooms[38].links.ne = {}
          region.rooms[38].links.ne.to = 1013
          region.rooms[38].links.ne.con = ""
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 991
          region.rooms[38].links.s.con = ""
      region.rooms[38].exits = "south|northeast"
      region.rooms[38].desc = "    这是一条暗道，是专为鳌拜从鳌府直接到东厂用的。南边是一扇木门(door)。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly bj;e;n;n;n;w;w"
      region.rooms[39].name = "地安门东大街"
      region.rooms[39].zone = "北京"
      region.rooms[39].id = 1015
      region.rooms[39].links = {}
        region.rooms[39].links.e = {}
          region.rooms[39].links.e.to = 1008
          region.rooms[39].links.e.con = ""
        region.rooms[39].links.w = {}
          region.rooms[39].links.w.to = 1016
          region.rooms[39].links.w.con = ""
      region.rooms[39].exits = "east|west"
      region.rooms[39].desc = "    这是一条东西走向的大道。西边通往地安门。东边通往王府井。"
    region.rooms[40] = {}
      region.rooms[40].path = "fly bj;e;n;n;n;w;w;w"
      region.rooms[40].name = "地安门"
      region.rooms[40].zone = "北京"
      region.rooms[40].id = 1016
      region.rooms[40].links = {}
        region.rooms[40].links.e = {}
          region.rooms[40].links.e.to = 1015
          region.rooms[40].links.e.con = ""
        region.rooms[40].links.w = {}
          region.rooms[40].links.w.to = 1019
          region.rooms[40].links.w.con = ""
        region.rooms[40].links.s = {}
          region.rooms[40].links.s.to = 1018
          region.rooms[40].links.s.con = ""
        region.rooms[40].links.n = {}
          region.rooms[40].links.n.to = 1017
          region.rooms[40].links.n.con = ""
      region.rooms[40].exits = "south|east|north|west"
      region.rooms[40].desc = "    这里就是地安门广场，灰色的城墙给人以庄严肃穆之感，再往南就是皇宫后门。门前有座小桥，一条护城河绕城而过。越过小桥向南望去，紫禁城的轮廓益发显得雄伟高大。一条笔直的大道横贯东西，东边是地安门东街，西边是地安门西街。北边通往安定门。"
    region.rooms[41] = {}
      region.rooms[41].path = "fly bj;e;n;n;n;w;w;w;n"
      region.rooms[41].name = "安定门"
      region.rooms[41].zone = "北京"
      region.rooms[41].id = 1017
      region.rooms[41].links = {}
        region.rooms[41].links.s = {}
          region.rooms[41].links.s.to = 1016
          region.rooms[41].links.s.con = ""
      region.rooms[41].exits = "south"
      region.rooms[41].desc = "    这里是永定门，城门正上方刻着“安定门”三个大字，城墙上贴着几张官府告示 (gaoshi)。几个官兵守在两旁。"
    region.rooms[42] = {}
      region.rooms[42].path = "fly bj;e;n;n;n;w;w;w;s"
      region.rooms[42].name = "小桥"
      region.rooms[42].zone = "北京"
      region.rooms[42].id = 1018
      region.rooms[42].links = {}
        region.rooms[42].links.n = {}
          region.rooms[42].links.n.to = 1016
          region.rooms[42].links.n.con = ""
      region.rooms[42].exits = "north"
      region.rooms[42].desc = "    这是一座破旧的石桥，桥下是护城河缓缓的流水。水看上去很清，这里是进皇宫后门的必经之路。"
    region.rooms[43] = {}
      region.rooms[43].path = "fly bj;e;n;n;n;w;w;w;w"
      region.rooms[43].name = "地安门西大街"
      region.rooms[43].zone = "北京"
      region.rooms[43].id = 1019
      region.rooms[43].links = {}
        region.rooms[43].links.e = {}
          region.rooms[43].links.e.to = 1016
          region.rooms[43].links.e.con = ""
        region.rooms[43].links.w = {}
          region.rooms[43].links.w.to = 1020
          region.rooms[43].links.w.con = ""
      region.rooms[43].exits = "east|west"
      region.rooms[43].desc = "    这是一条东西走向的大道。东边通往地安门。西边通往西四。不知道为什么，这里总是冷冷清清，见不到几个行人。"
    region.rooms[44] = {}
      region.rooms[44].path = "fly bj;w;w;n;n;n;n;e"
      region.rooms[44].name = "地安门西大街"
      region.rooms[44].zone = "北京"
      region.rooms[44].id = 1020
      region.rooms[44].links = {}
        region.rooms[44].links.e = {}
          region.rooms[44].links.e.to = 1019
          region.rooms[44].links.e.con = ""
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 1021
          region.rooms[44].links.s.con = ""
        region.rooms[44].links.w = {}
          region.rooms[44].links.w.to = 1023
          region.rooms[44].links.w.con = ""
      region.rooms[44].exits = "south|east|west"
      region.rooms[44].desc = "    这是一条东西走向的大道。东边通往地安门。西边通往西四北大街。南边是西厂了，一般人都不敢往那儿去。"
    region.rooms[45] = {}
      region.rooms[45].path = "fly bj;w;w;n;n;n;n;e;s"
      region.rooms[45].name = "西厂大门"
      region.rooms[45].zone = "北京"
      region.rooms[45].id = 1021
      region.rooms[45].links = {}
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 1022
          region.rooms[45].links.s.con = "k1:"
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 1020
          region.rooms[45].links.n.con = ""
      region.rooms[45].exits = "south|north"
      region.rooms[45].desc = "    这里就是西厂大门，可以看到里面有许多太监。穿着制服的官兵正在操练，不时地传来呐喊声。如果你不想找死的话，最好还是赶快离开。"
    region.rooms[46] = {}
      region.rooms[46].path = "fly bj;w;w;n;n;n;n;e;s;|!k1::s|"
      region.rooms[46].name = "兵营"
      region.rooms[46].zone = "北京"
      region.rooms[46].id = 1022
      region.rooms[46].links = {}
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 1021
          region.rooms[46].links.n.con = ""
      region.rooms[46].exits = "north"
      region.rooms[46].desc = "    这里是兵营，密密麻麻到处都是官兵，有的在武将的指挥下列队操练，有的独自在练功，有的坐着、躺着正在休息。还有些太监在四处走动。"
    region.rooms[47] = {}
      region.rooms[47].path = "fly bj;w;w;n;n;n;n"
      region.rooms[47].name = "西四北大街"
      region.rooms[47].zone = "北京"
      region.rooms[47].id = 1023
      region.rooms[47].links = {}
        region.rooms[47].links.e = {}
          region.rooms[47].links.e.to = 1020
          region.rooms[47].links.e.con = ""
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 1025
          region.rooms[47].links.s.con = ""
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 1024
          region.rooms[47].links.n.con = ""
      region.rooms[47].exits = "south|north|east"
      region.rooms[47].desc = "    这里是西四北大街。南边通往西单。东边通向地安门,北面是一间书院。"
    region.rooms[48] = {}
      region.rooms[48].path = "fly bj;w;w;n;n;n;n;n"
      region.rooms[48].name = "书院"
      region.rooms[48].zone = "北京"
      region.rooms[48].id = 1024
      region.rooms[48].links = {}
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 1023
          region.rooms[48].links.s.con = ""
      region.rooms[48].exits = "south"
      region.rooms[48].desc = "    这里是书院的讲堂，窗明几净，一尘不染。一位庄重严肃的老者坐在太师椅上讲学，那就是京城的大儒顾炎武了。在他的两侧坐满了求学的学生。一张古意盎然的书案放在顾先生的前面，案上摆着几本翻开了的线装书籍。顾先生的身后是一个书架(shujia)讲堂内多历代楹联石刻，足见书院历史的悠久。值得一提的是嵌在讲堂前左壁的学规(xuegui)。"
    region.rooms[49] = {}
      region.rooms[49].path = "fly bj;w;w;n;n;n"
      region.rooms[49].name = "西四北大街"
      region.rooms[49].zone = "北京"
      region.rooms[49].id = 1025
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 1026
          region.rooms[49].links.e.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 1027
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.n = {}
          region.rooms[49].links.n.to = 1023
          region.rooms[49].links.n.con = ""
      region.rooms[49].exits = "south|east|north"
      region.rooms[49].desc = "    这是一条长长的街道。东边就是游人们常去的文庙，那里长年香火不断，烟雾缭绕。南边是西单。"
    region.rooms[50] = {}
      region.rooms[50].path = "fly bj;w;w;n;n;n;e"
      region.rooms[50].name = "文庙"
      region.rooms[50].zone = "北京"
      region.rooms[50].id = 1026
      region.rooms[50].links = {}
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 1025
          region.rooms[50].links.w.con = ""
      region.rooms[50].exits = "west"
      region.rooms[50].desc = "    这里是文庙正殿，内有孔夫子像。历代皇帝都懂得利用儒教思想来巩固自己的江山社稷，当朝皇帝自然也不例外。不论何人到此，都毕恭毕敬地上香礼拜。"
    region.rooms[51] = {}
      region.rooms[51].path = "fly bj;w;w;n;n"
      region.rooms[51].name = "西单北大街"
      region.rooms[51].zone = "北京"
      region.rooms[51].id = 1027
      region.rooms[51].links = {}
        region.rooms[51].links.e = {}
          region.rooms[51].links.e.to = 1028
          region.rooms[51].links.e.con = ""
        region.rooms[51].links.s = {}
          region.rooms[51].links.s.to = 1034
          region.rooms[51].links.s.con = ""
        region.rooms[51].links.n = {}
          region.rooms[51].links.n.to = 1025
          region.rooms[51].links.n.con = ""
      region.rooms[51].exits = "south|east|north"
      region.rooms[51].desc = "    这里是西单北大街。东边有一家很大的赌场，里面闹哄哄的。北边是西四北大街。南边就是西单了。"
    region.rooms[52] = {}
      region.rooms[52].path = "fly bj;w;w;n;n;e"
      region.rooms[52].name = "赌场"
      region.rooms[52].zone = "北京"
      region.rooms[52].id = 1028
      region.rooms[52].links = {}
        region.rooms[52].links.w = {}
          region.rooms[52].links.w.to = 1027
          region.rooms[52].links.w.con = ""
        region.rooms[52].links.u = {}
          region.rooms[52].links.u.to = 1029
          region.rooms[52].links.u.con = ""
      region.rooms[52].exits = "up|west"
      region.rooms[52].desc = "    这里是赌场的大堂，四周的房间里传出来吆五喝六的赌博声。北边是赌「大小」的房间，墙上挂着一块牌子(paizi)。楼上可以拱猪. 一进门，只见房中人声嘈杂，十分混乱。有一桌围着一群人，其中一胖一瘦两个头陀十分惹眼。一个老叫化正和他们赌得起劲。"
    region.rooms[53] = {}
      region.rooms[53].path = "fly bj;w;w;n;n;e;u"
      region.rooms[53].name = "赌场"
      region.rooms[53].zone = "北京"
      region.rooms[53].id = 1029
      region.rooms[53].links = {}
        region.rooms[53].links.s = {}
          region.rooms[53].links.s.to = 1032
          region.rooms[53].links.s.con = ""
        region.rooms[53].links.e = {}
          region.rooms[53].links.e.to = 1030
          region.rooms[53].links.e.con = ""
        region.rooms[53].links.d = {}
          region.rooms[53].links.d.to = 1028
          region.rooms[53].links.d.con = ""
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 1031
          region.rooms[53].links.w.con = ""
        region.rooms[53].links.n = {}
          region.rooms[53].links.n.to = 1033
          region.rooms[53].links.n.con = ""
      region.rooms[53].exits = "south|north|east|west|down"
      region.rooms[53].desc = "    这里有四条走廊通向不同的房间。"
    region.rooms[54] = {}
      region.rooms[54].path = "fly bj;w;w;n;n;e;u;e"
      region.rooms[54].name = "拱猪房"
      region.rooms[54].zone = "北京"
      region.rooms[54].id = 1030
      region.rooms[54].links = {}
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 1029
          region.rooms[54].links.w.con = ""
      region.rooms[54].exits = "west"
      region.rooms[54].desc = "        这是一间专门为拱猪而特别设计的拱猪房。房间里面灯火通明，仿佛永远准备着为拱猪狂们服务似的。房间的中心放着一张用百年老松树木材特制的拱猪桌(table)，周围放着四把楠木靠背椅。桌子上摆着一本记分簿(scoreboard)，北边的墙上贴着一张纸(paper)。"
    region.rooms[55] = {}
      region.rooms[55].path = "fly bj;w;w;n;n;e;u;w"
      region.rooms[55].name = "拱猪房"
      region.rooms[55].zone = "北京"
      region.rooms[55].id = 1031
      region.rooms[55].links = {}
        region.rooms[55].links.e = {}
          region.rooms[55].links.e.to = 1029
          region.rooms[55].links.e.con = ""
      region.rooms[55].exits = "east"
      region.rooms[55].desc = "        这是一间专门为拱猪而特别设计的拱猪房。房间里面灯火通明，仿佛永远准备着为拱猪狂们服务似的。房间的中心放着一张用百年老松树木材特制的拱猪桌(table)，周围放着四把楠木靠背椅。桌子上摆着一本记分簿(scoreboard)，北边的墙上贴着一张纸(paper)。"
    region.rooms[56] = {}
      region.rooms[56].path = "fly bj;w;w;n;n;e;u;s"
      region.rooms[56].name = "拱猪房"
      region.rooms[56].zone = "北京"
      region.rooms[56].id = 1032
      region.rooms[56].links = {}
        region.rooms[56].links.n = {}
          region.rooms[56].links.n.to = 1029
          region.rooms[56].links.n.con = ""
      region.rooms[56].exits = "north"
      region.rooms[56].desc = "        这是一间专门为拱猪而特别设计的拱猪房。房间里面灯火通明，仿佛永远准备着为拱猪狂们服务似的。房间的中心放着一张用百年老松树木材特制的拱猪桌(table)，周围放着四把楠木靠背椅。桌子上摆着一本记分簿(scoreboard)，北边的墙上贴着一张纸(paper)。"
    region.rooms[57] = {}
      region.rooms[57].path = "fly bj;w;w;n;n;e;u;n"
      region.rooms[57].name = "拱猪房"
      region.rooms[57].zone = "北京"
      region.rooms[57].id = 1033
      region.rooms[57].links = {}
        region.rooms[57].links.s = {}
          region.rooms[57].links.s.to = 1029
          region.rooms[57].links.s.con = ""
      region.rooms[57].exits = "south"
      region.rooms[57].desc = "        这是一间专门为拱猪而特别设计的拱猪房。房间里面灯火通明，仿佛永远准备着为拱猪狂们服务似的。房间的中心放着一张用百年老松树木材特制的拱猪桌(table)，周围放着四把楠木靠背椅。桌子上摆着一本记分簿(scoreboard)，北边的墙上贴着一张纸(paper)。"
    region.rooms[58] = {}
      region.rooms[58].path = "fly bj;w;w;n"
      region.rooms[58].name = "西单"
      region.rooms[58].zone = "北京"
      region.rooms[58].id = 1034
      region.rooms[58].links = {}
        region.rooms[58].links.s = {}
          region.rooms[58].links.s.to = 1036
          region.rooms[58].links.s.con = ""
        region.rooms[58].links.w = {}
          region.rooms[58].links.w.to = 1035
          region.rooms[58].links.w.con = ""
        region.rooms[58].links.n = {}
          region.rooms[58].links.n.to = 1027
          region.rooms[58].links.n.con = ""
      region.rooms[58].exits = "south|north|west"
      region.rooms[58].desc = "    这里就是西单，人来人往，十分热闹。游人虽然多，但大都只四处晃悠,着东瞅瞅西看看，也不急着买什么。西边有家杂货铺，去那里买东西的人很多。不断有人从北边走来，似乎那里也挺热闹。南边是西长安街。"
    region.rooms[59] = {}
      region.rooms[59].path = "fly bj;w;w;n;w"
      region.rooms[59].name = "杂货铺"
      region.rooms[59].zone = "北京"
      region.rooms[59].id = 1035
      region.rooms[59].links = {}
        region.rooms[59].links.e = {}
          region.rooms[59].links.e.to = 1034
          region.rooms[59].links.e.con = ""
      region.rooms[59].exits = "east"
      region.rooms[59].desc = "    这是一家杂货铺，大箱小箱堆满了一地，都是一些日常用品。胡掌柜懒洋洋地躺在一只躺椅上，招呼着过往行人。据说私底下他也卖一些贵重的东西。摊上立着一块招牌(zhaopai)。"
    region.rooms[60] = {}
      region.rooms[60].path = "fly bj;w;w"
      region.rooms[60].name = "西长安街"
      region.rooms[60].zone = "北京"
      region.rooms[60].id = 1036
      region.rooms[60].links = {}
        region.rooms[60].links.e = {}
          region.rooms[60].links.e.to = 983
          region.rooms[60].links.e.con = ""
        region.rooms[60].links.w = {}
          region.rooms[60].links.w.to = 1046
          region.rooms[60].links.w.con = ""
        region.rooms[60].links.s = {}
          region.rooms[60].links.s.to = 1037
          region.rooms[60].links.s.con = ""
        region.rooms[60].links.n = {}
          region.rooms[60].links.n.to = 1034
          region.rooms[60].links.n.con = ""
      region.rooms[60].exits = "south|north|east|west"
      region.rooms[60].desc = "    你走在街上，感到这里的街面要比别处的干净、整洁。再往西就是西城门，直通往郊外。东边是空荡荡的街道。南边是一条行人稀少的小巷，北边通往西单。"
    region.rooms[61] = {}
      region.rooms[61].path = "fly bj;w;w;s"
      region.rooms[61].name = "杨柳胡同"
      region.rooms[61].zone = "北京"
      region.rooms[61].id = 1037
      region.rooms[61].links = {}
        region.rooms[61].links.e = {}
          region.rooms[61].links.e.to = 1038
          region.rooms[61].links.e.con = ""
        region.rooms[61].links.s = {}
          region.rooms[61].links.s.to = 1039
          region.rooms[61].links.s.con = ""
        region.rooms[61].links.n = {}
          region.rooms[61].links.n.to = 1036
          region.rooms[61].links.n.con = ""
      region.rooms[61].exits = "south|north|east"
      region.rooms[61].desc = "    你走在巷道上，感到似乎有些不妙。南边仍是空荡荡的小道,见不到几个行人。东边是一家面馆。北边是西长安大道。一股阴风吹来，你禁不住打了个寒颤。 "
    region.rooms[62] = {}
      region.rooms[62].path = "fly bj;w;w;s;e"
      region.rooms[62].name = "面馆"
      region.rooms[62].zone = "北京"
      region.rooms[62].id = 1038
      region.rooms[62].links = {}
        region.rooms[62].links.w = {}
          region.rooms[62].links.w.to = 1037
          region.rooms[62].links.w.con = ""
      region.rooms[62].exits = "west"
      region.rooms[62].desc = "    这是一家价钱低廉的面馆，生意非常兴隆。外地游客多选择这里落脚，你可以在这里打听到各地的风土人情。穷人们也都喜欢来这里。店小二里里外外忙得团团转，接待着南腔北调的客人。几张脏乎乎的小木桌旁，坐满了各种各样的食客。"
    region.rooms[63] = {}
      region.rooms[63].path = "fly bj;w;w;s;s"
      region.rooms[63].name = "杨柳胡同"
      region.rooms[63].zone = "北京"
      region.rooms[63].id = 1039
      region.rooms[63].links = {}
        region.rooms[63].links.sw = {}
          region.rooms[63].links.sw.to = 1042
          region.rooms[63].links.sw.con = ""
        region.rooms[63].links.se = {}
          region.rooms[63].links.se.to = 1040
          region.rooms[63].links.se.con = ""
        region.rooms[63].links.n = {}
          region.rooms[63].links.n.to = 1037
          region.rooms[63].links.n.con = ""
      region.rooms[63].exits = "north|southeast|southwest"
      region.rooms[63].desc = "    街道上一个人也看不到。你突然有点害怕起来。东南边有一家棺材店。西南边是一条黑漆漆的小巷，你不知道要不要继续向里走。“还是往北回去吧，免得。。。。。。”，心底里一个声音不住地对你说。"
    region.rooms[64] = {}
      region.rooms[64].path = "fly bj;w;w;s;s;se"
      region.rooms[64].name = "棺材店"
      region.rooms[64].zone = "北京"
      region.rooms[64].id = 1040
      region.rooms[64].links = {}
        region.rooms[64].links.nw = {}
          region.rooms[64].links.nw.to = 1039
          region.rooms[64].links.nw.con = ""
        region.rooms[64].links.e = {}
          region.rooms[64].links.e.to = 1041
          region.rooms[64].links.e.con = ""
      region.rooms[64].exits = "east|northwest"
      region.rooms[64].desc = "    这是一家棺材店，一进门，一股楠木味扑鼻而来。屋子里很阴暗，桌子椅子都很破旧。往东是一间内室，一个三十出头的精壮汉子挡在门口。"
    region.rooms[65] = {}
      region.rooms[65].path = "fly bj;w;w;s;s;se;e"
      region.rooms[65].name = "棺材店内室"
      region.rooms[65].zone = "北京"
      region.rooms[65].id = 1041
      region.rooms[65].links = {}
        region.rooms[65].links.w = {}
          region.rooms[65].links.w.to = 1040
          region.rooms[65].links.w.con = ""
        region.rooms[65].links["knock guancai 3;enter hole"] = {}
          region.rooms[65].links["knock guancai 3;enter hole"].to = 1343
          region.rooms[65].links["knock guancai 3;enter hole"].con = ""
      region.rooms[65].exits = "west"
      region.rooms[65].desc = "    一进门，一股腐臭让你几乎要窒息了。屋里满是棺材(guancai)。"
    region.rooms[66] = {}
      region.rooms[66].path = "fly bj;w;w;s;s;sw"
      region.rooms[66].name = "杨柳胡同"
      region.rooms[66].zone = "北京"
      region.rooms[66].id = 1042
      region.rooms[66].links = {}
        region.rooms[66].links.ne = {}
          region.rooms[66].links.ne.to = 1039
          region.rooms[66].links.ne.con = ""
        region.rooms[66].links.se = {}
          region.rooms[66].links.se.to = 1043
          region.rooms[66].links.se.con = ""
      region.rooms[66].exits = "southeast|northeast"
      region.rooms[66].desc = "    这是一条十分僻静的小胡同，东南面有一家客店，隐隐约约传来打斗之声。你颇有些犹豫：要不要过去看一看呢，不会有什么危险吧？东北边可以出胡同。"
    region.rooms[67] = {}
      region.rooms[67].path = "fly bj;w;w;s;s;sw;se"
      region.rooms[67].name = "客店"
      region.rooms[67].zone = "北京"
      region.rooms[67].id = 1043
      region.rooms[67].links = {}
        region.rooms[67].links.nw = {}
          region.rooms[67].links.nw.to = 1042
          region.rooms[67].links.nw.con = ""
        region.rooms[67].links.s = {}
          region.rooms[67].links.s.to = 1044
          region.rooms[67].links.s.con = ""
      region.rooms[67].exits = "south|northwest"
      region.rooms[67].desc = "    这是一家价钱低廉的客店，因为地方偏僻，房客很少。不时有打斗之声从东南边传来。掌柜早不知躲哪儿去了，屋里见不到一个人。南边是后院，通往各厢房。"
    region.rooms[68] = {}
      region.rooms[68].path = "fly bj;w;w;s;s;sw;se;s"
      region.rooms[68].name = "客店后院"
      region.rooms[68].zone = "北京"
      region.rooms[68].id = 1044
      region.rooms[68].links = {}
        region.rooms[68].links.e = {}
          region.rooms[68].links.e.to = 2986
          region.rooms[68].links.e.con = ""
        region.rooms[68].links.w = {}
          region.rooms[68].links.w.to = 1045
          region.rooms[68].links.w.con = ""
        region.rooms[68].links.n = {}
          region.rooms[68].links.n.to = 1043
          region.rooms[68].links.n.con = ""
      region.rooms[68].exits = "north|east|west"
      region.rooms[68].desc = "    这里客店后院。一阵阵打斗之声从东面的厢房 (room) 中传来，其中夹杂着一个女子的声音。房门的板壁(wall)不住的震动，似乎客房四周的板壁都要被刀风掌力震坍一般。西首也是厢房，不时有人探头出来观望。北面是客店大门。"
    region.rooms[69] = {}
      region.rooms[69].path = "fly bj;w;w;s;s;sw;se;s;w"
      region.rooms[69].name = "西客房"
      region.rooms[69].zone = "北京"
      region.rooms[69].id = 1045
      region.rooms[69].links = {}
        region.rooms[69].links.e = {}
          region.rooms[69].links.e.to = 1044
          region.rooms[69].links.e.con = ""
      region.rooms[69].exits = "east"
      region.rooms[69].desc = "    这里是西客房，一个掌柜和两个伙计躲在角落里瑟瑟发抖。"
    region.rooms[70] = {}
      region.rooms[70].path = "fly bj;w;w;w"
      region.rooms[70].name = "西城门"
      region.rooms[70].zone = "北京"
      region.rooms[70].id = 1046
      region.rooms[70].links = {}
        region.rooms[70].links.e = {}
          region.rooms[70].links.e.to = 1036
          region.rooms[70].links.e.con = ""
        region.rooms[70].links.w = {}
          region.rooms[70].links.w.to = 1047
          region.rooms[70].links.w.con = ""
      region.rooms[70].exits = "east|west"
      region.rooms[70].desc = "    这是西城门，几年前曾经遭到土匪的攻打，因此显得有些破败。城门正上方勉勉强强可以认出“西门”两个大字，城墙上贴着几张通缉告示(gaoshi)。罪犯常常从这里逃出京城，官兵们戒备森严，动不动就截住行人盘问。一条笔直的青石板大道向东西两边延伸。西边是郊外，骑马的、坐轿的、走路的，行人匆匆。东边是城里。"
    region.rooms[71] = {}
      region.rooms[71].path = "fly bj;w;w;w;w"
      region.rooms[71].name = "西门外"
      region.rooms[71].zone = "北京"
      region.rooms[71].id = 1047
      region.rooms[71].links = {}
        region.rooms[71].links.e = {}
          region.rooms[71].links.e.to = 1046
          region.rooms[71].links.e.con = ""
        region.rooms[71].links.w = {}
          region.rooms[71].links.w.to = 1048
          region.rooms[71].links.w.con = ""
      region.rooms[71].exits = "east|west"
      region.rooms[71].desc = "    这里是北京的西城门外。人来人往，煞是热闹。"
    region.rooms[72] = {}
      region.rooms[72].path = "fly bj;w;w;w;w;w"
      region.rooms[72].name = "黄土路"
      region.rooms[72].zone = "北京"
      region.rooms[72].id = 1048
      region.rooms[72].links = {}
        region.rooms[72].links.e = {}
          region.rooms[72].links.e.to = 1047
          region.rooms[72].links.e.con = ""
      region.rooms[72].exits = "east|west"
      region.rooms[72].desc = "    你走在一条黄土路上。西面望去，隐隐可以看到平定州。望东，北京城快到了。"
    region.rooms[73] = {}
      region.rooms[73].path = "fly bj;w;s"
      region.rooms[73].name = "回春堂药店"
      region.rooms[73].zone = "北京"
      region.rooms[73].id = 1049
      region.rooms[73].links = {}
        region.rooms[73].links.w = {}
          region.rooms[73].links.w.to = 1050
          region.rooms[73].links.w.con = ""
        region.rooms[73].links.n = {}
          region.rooms[73].links.n.to = 983
          region.rooms[73].links.n.con = ""
      region.rooms[73].exits = "north|west"
      region.rooms[73].desc = "    这是一家药铺，一股浓浓的药味让你几欲窒息，那是从药柜上的几百个小抽屉里散发出来的。一位老者在柜台后站着。柜台上贴着一张发黄的广告(guanggao)。柜台后面往西是一间内室(neishi)。"
    region.rooms[74] = {}
      region.rooms[74].path = "fly bj;w;s;w"
      region.rooms[74].name = "内室"
      region.rooms[74].zone = "北京"
      region.rooms[74].id = 1050
      region.rooms[74].links = {}
        region.rooms[74].links.e = {}
          region.rooms[74].links.e.to = 1049
          region.rooms[74].links.e.con = ""
      region.rooms[74].exits = "east"
      region.rooms[74].desc = "    这里是一个空荡荡的房间，除了地板(floor)，什么也没有。"
    region.rooms[75] = {}
      region.rooms[75].path = "fly bj;w;n"
      region.rooms[75].name = "长安戏院"
      region.rooms[75].zone = "北京"
      region.rooms[75].id = 1051
      region.rooms[75].links = {}
        region.rooms[75].links.s = {}
          region.rooms[75].links.s.to = 983
          region.rooms[75].links.s.con = ""
        region.rooms[75].links.e = {}
          region.rooms[75].links.e.to = 1052
          region.rooms[75].links.e.con = ""
      region.rooms[75].exits = "up|south|east"
      region.rooms[75].desc = "    这里就是著名的长安戏院，几个戏子在台上(stage)唱戏。台下黑压压的一片都是人。唱到妙处，观众们禁不住大声喝采。东边是后台。"
    region.rooms[76] = {}
      region.rooms[76].path = "fly bj;w;n;e"
      region.rooms[76].name = "戏院后台"
      region.rooms[76].zone = "北京"
      region.rooms[76].id = 1052
      region.rooms[76].links = {}
        region.rooms[76].links.w = {}
          region.rooms[76].links.w.to = 1051
          region.rooms[76].links.w.con = ""
        region.rooms[76].links.nu = {}
          region.rooms[76].links.nu.to = 1053
          region.rooms[76].links.nu.con = ""
      region.rooms[76].exits = "northup|west"
      region.rooms[76].desc = "    这里是戏院后台，几个戏子正在化妆。从北边可以上台。"
    region.rooms[77] = {}
      region.rooms[77].path = "fly bj;w;n;e;nu"
      region.rooms[77].name = "戏台"
      region.rooms[77].zone = "北京"
      region.rooms[77].id = 1053
      region.rooms[77].links = {}
        region.rooms[77].links.sd = {}
          region.rooms[77].links.sd.to = 1052
          region.rooms[77].links.sd.con = ""
      region.rooms[77].exits = "southdown|down"
      region.rooms[77].desc = "    这里是戏台，虽然有些小，但是很干净。一个戏子正在表演。你一踏上戏台，情不自禁地就唱起歌来。"
    region.rooms[78] = {}
      region.rooms[78].path = "fly bj;e;e"
      region.rooms[78].name = "东长安街"
      region.rooms[78].zone = "北京"
      region.rooms[78].id = 1054
      region.rooms[78].links = {}
        region.rooms[78].links.e = {}
          region.rooms[78].links.e.to = 1056
          region.rooms[78].links.e.con = ""
        region.rooms[78].links.w = {}
          region.rooms[78].links.w.to = 982
          region.rooms[78].links.w.con = ""
        region.rooms[78].links.s = {}
          region.rooms[78].links.s.to = 1055
          region.rooms[78].links.s.con = ""
      region.rooms[78].exits = "south|north|east|west"
      region.rooms[78].desc = "    你走在东长安街上，踩着坚实的青石板地面。东边是东城门，可以听到守城官兵的吆喝声。南边是打铁铺，叮叮当当的声音老远就能听到。北边是京城最有名的“怡红院”，达官显贵、宫廷侍卫都爱去。西边比这里更热闹，从那儿往北可以去王府井。"
    region.rooms[79] = {}
      region.rooms[79].path = "fly bj;e;e;s"
      region.rooms[79].name = "打铁铺"
      region.rooms[79].zone = "北京"
      region.rooms[79].id = 1055
      region.rooms[79].links = {}
        region.rooms[79].links.n = {}
          region.rooms[79].links.n.to = 1054
          region.rooms[79].links.n.con = ""
      region.rooms[79].exits = "north"
      region.rooms[79].desc = "    这是一家简陋的打铁铺，中心摆着一个火炉，炉火把四周照得一片通红，你一走进去就感到浑身火热。墙角堆满了已完工和未完工的菜刀、铁锤、铁棍、匕首、盔甲等物。一位铁匠满头大汗挥舞着铁锤，专心致志地在打铁。"
    region.rooms[80] = {}
      region.rooms[80].path = "fly bj;e;e;e"
      region.rooms[80].name = "东门"
      region.rooms[80].zone = "北京"
      region.rooms[80].id = 1056
      region.rooms[80].links = {}
        region.rooms[80].links.e = {}
          region.rooms[80].links.e.to = 1059
          region.rooms[80].links.e.con = ""
        region.rooms[80].links.nw = {}
          region.rooms[80].links.nw.to = 1057
          region.rooms[80].links.nw.con = ""
        region.rooms[80].links.w = {}
          region.rooms[80].links.w.to = 1054
          region.rooms[80].links.w.con = ""
      region.rooms[80].exits = "northwest|east|west"
      region.rooms[80].desc = "    这是东城门，城门正上方刻着“东门”两个大字，城墙上贴着几张官府告示(gaoshi)。一条笔直的青石板大道向东西两边延伸。东边是郊外，越过城门可以看到驿道上人来车往，尘土飞扬。西边通往城里。西北边是朝阳门。"
    region.rooms[81] = {}
      region.rooms[81].path = "fly bj;e;e;e;nw"
      region.rooms[81].name = "朝阳路"
      region.rooms[81].zone = "北京"
      region.rooms[81].id = 1057
      region.rooms[81].links = {}
        region.rooms[81].links.nw = {}
          region.rooms[81].links.nw.to = 1058
          region.rooms[81].links.nw.con = ""
        region.rooms[81].links.se = {}
          region.rooms[81].links.se.to = 1056
          region.rooms[81].links.se.con = ""
      region.rooms[81].exits = "northwest|southeast"
      region.rooms[81].desc = "    这是一条青石路，一路走来见不到几个行人。东南边是东门。朝阳门在西北边。"
    region.rooms[82] = {}
      region.rooms[82].path = "fly bj;e;e;e;nw;nw"
      region.rooms[82].name = "朝阳门"
      region.rooms[82].zone = "北京"
      region.rooms[82].id = 1058
      region.rooms[82].links = {}
        region.rooms[82].links.w = {}
          region.rooms[82].links.w.to = 994
          region.rooms[82].links.w.con = ""
        region.rooms[82].links.se = {}
          region.rooms[82].links.se.to = 1057
          region.rooms[82].links.se.con = ""
      region.rooms[82].exits = "southeast|west"
      region.rooms[82].desc = "    这里就是朝阳门，城墙上刻着“朝阳门”三个大字。东门就在东南边，那里人来车往，是进出京城的要道，盘查十分严密。一条宽阔的大道向西延伸，通往著名的王府井大街。"
    region.rooms[83] = {}
      region.rooms[83].path = "fly bj;e;e;e;e"
      region.rooms[83].name = "大驿道"
      region.rooms[83].zone = "北京"
      region.rooms[83].id = 1059
      region.rooms[83].links = {}
        region.rooms[83].links.ne = {}
          region.rooms[83].links.ne.to = 1060
          region.rooms[83].links.ne.con = ""
        region.rooms[83].links.w = {}
          region.rooms[83].links.w.to = 1056
          region.rooms[83].links.w.con = ""
        region.rooms[83].links.se = {}
          region.rooms[83].links.se.to = 1069
          region.rooms[83].links.se.con = ""
      region.rooms[83].exits = "southeast|northeast|west"
      region.rooms[83].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。西边就是京城东门。东北方是一条小路。"
    region.rooms[84] = {}
      region.rooms[84].path = "fly bj;e;e;e;e;ne"
      region.rooms[84].name = "小路"
      region.rooms[84].zone = "北京"
      region.rooms[84].id = 1060
      region.rooms[84].links = {}
        region.rooms[84].links.n = {}
          region.rooms[84].links.n.to = 1061
          region.rooms[84].links.n.con = ""
        region.rooms[84].links.sw = {}
          region.rooms[84].links.sw.to = 1059
          region.rooms[84].links.sw.con = ""
      region.rooms[84].exits = "north|southwest"
      region.rooms[84].desc = "    你走在一条小路上。前面道路崎岖，行人很少。"
    region.rooms[85] = {}
      region.rooms[85].path = "fly bj;e;e;e;e;ne;n"
      region.rooms[85].name = "小路"
      region.rooms[85].zone = "北京"
      region.rooms[85].id = 1061
      region.rooms[85].links = {}
        region.rooms[85].links.s = {}
          region.rooms[85].links.s.to = 1060
          region.rooms[85].links.s.con = ""
        region.rooms[85].links.n = {}
          region.rooms[85].links.n.to = 1062
          region.rooms[85].links.n.con = ""
      region.rooms[85].exits = "south|north"
      region.rooms[85].desc = "    你走在一条小路上。前面道路崎岖，行人很少。前方隐约有房屋可见."
    region.rooms[86] = {}
      region.rooms[86].path = "fly bj;e;e;e;e;ne;n;n"
      region.rooms[86].name = "庄府大门"
      region.rooms[86].zone = "北京"
      region.rooms[86].id = 1062
      region.rooms[86].links = {}
        region.rooms[86].links.s = {}
          region.rooms[86].links.s.to = 1061
          region.rooms[86].links.s.con = ""
        region.rooms[86].links["climb wall"] = {}
          region.rooms[86].links["climb wall"].to = 1063
          region.rooms[86].links["climb wall"].con = ""
      region.rooms[86].exits = "south"
      region.rooms[86].desc = "    这里就是文士庄允城的旧居。自从他被朝廷抓走后,这里好象就没有人住了。一扇大门(men)紧锁着,周围是高高的围墙(wall).一切都很干净,并没有积多少灰尘。"
    region.rooms[87] = {}
      region.rooms[87].path = "fly bj;e;e;e;e;ne;n;n;climb wall"
      region.rooms[87].name = "大院"
      region.rooms[87].zone = "北京"
      region.rooms[87].id = 1063
      region.rooms[87].links = {}
        region.rooms[87].links.s = {}
          region.rooms[87].links.s.to = 1062
          region.rooms[87].links.s.con = ""
        region.rooms[87].links.n = {}
          region.rooms[87].links.n.to = 1064
          region.rooms[87].links.n.con = ""
      region.rooms[87].exits = "south|north"
      region.rooms[87].desc = "    这是一个破旧的大院。院内十分宽阔，可容百人。正中一口天井,再往里是座大厅."
    region.rooms[88] = {}
      region.rooms[88].path = "fly bj;e;e;e;e;ne;n;n;climb wall;n"
      region.rooms[88].name = "庄府大厅"
      region.rooms[88].zone = "北京"
      region.rooms[88].id = 1064
      region.rooms[88].links = {}
        region.rooms[88].links.e = {}
          region.rooms[88].links.e.to = 1065
          region.rooms[88].links.e.con = ""
        region.rooms[88].links.w = {}
          region.rooms[88].links.w.to = 1066
          region.rooms[88].links.w.con = ""
        region.rooms[88].links.s = {}
          region.rooms[88].links.s.to = 1063
          region.rooms[88].links.s.con = ""
        region.rooms[88].links.n = {}
          region.rooms[88].links.n.to = 1067
          region.rooms[88].links.n.con = ""
      region.rooms[88].exits = "south|north|east|west"
      region.rooms[88].desc = "    这是一间大厅。通往各个房间.东边的屋里有女子啼哭之声隐隐传来."
    region.rooms[89] = {}
      region.rooms[89].path = "fly bj;e;e;e;e;ne;n;n;climb wall;n;e"
      region.rooms[89].name = "庄府大厅"
      region.rooms[89].zone = "北京"
      region.rooms[89].id = 1065
      region.rooms[89].links = {}
        region.rooms[89].links.w = {}
          region.rooms[89].links.w.to = 1064
          region.rooms[89].links.w.con = ""
      region.rooms[89].exits = "west"
      region.rooms[89].desc = "    这是一间灵堂。堂上供了七八个牌位.看来一座灵堂上供的是一家死人.一阵阴风吹过,蜡烛突然灭了."
    region.rooms[90] = {}
      region.rooms[90].path = "fly bj;e;e;e;e;ne;n;n;climb wall;n;w"
      region.rooms[90].name = "庄府大厅"
      region.rooms[90].zone = "北京"
      region.rooms[90].id = 1066
      region.rooms[90].links = {}
        region.rooms[90].links.e = {}
          region.rooms[90].links.e.to = 1064
          region.rooms[90].links.e.con = ""
      region.rooms[90].exits = "east"
      region.rooms[90].desc = "    这是一间灵堂。堂上供了七八个牌位.看来一座灵堂上供的是一家死人.一阵阴风吹过,蜡烛突然灭了."
    region.rooms[91] = {}
      region.rooms[91].path = "fly bj;e;e;e;e;ne;n;n;climb wall;n;n"
      region.rooms[91].name = "长廊"
      region.rooms[91].zone = "北京"
      region.rooms[91].id = 1067
      region.rooms[91].links = {}
        region.rooms[91].links.s = {}
          region.rooms[91].links.s.to = 1064
          region.rooms[91].links.s.con = ""
        region.rooms[91].links.n = {}
          region.rooms[91].links.n.to = 1068
          region.rooms[91].links.n.con = ""
      region.rooms[91].exits = "south|north"
      region.rooms[91].desc = "    这是条长长的走廊。四处黑沉沉的."
    region.rooms[92] = {}
      region.rooms[92].path = "fly bj;e;e;e;e;ne;n;n;climb wall;n;n;n"
      region.rooms[92].name = "小房间"
      region.rooms[92].zone = "北京"
      region.rooms[92].id = 1068
      region.rooms[92].links = {}
        region.rooms[92].links.s = {}
          region.rooms[92].links.s.to = 1067
          region.rooms[92].links.s.con = ""
      region.rooms[92].exits = "south"
      region.rooms[92].desc = "    这是一个小房间,桌上点着蜡烛.房中只有一桌一床,陈设简单,却十分干净.床上铺着被褥."
    region.rooms[93] = {}
      region.rooms[93].path = "fly bj;e;e;e;e;se"
      region.rooms[93].name = "大驿道"
      region.rooms[93].zone = "北京"
      region.rooms[93].id = 1069
      region.rooms[93].links = {}
        region.rooms[93].links.nw = {}
          region.rooms[93].links.nw.to = 1059
          region.rooms[93].links.nw.con = ""
        region.rooms[93].links.se = {}
          region.rooms[93].links.se.to = 1070
          region.rooms[93].links.se.con = ""
      region.rooms[93].exits = "northwest|southeast"
      region.rooms[93].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。马上的人个个身着劲装，衣甲鲜明，有的还随身佩带着刀剑。看来都是些些习武的江湖人。道路两旁是整整齐齐的杨树林。"
    region.rooms[94] = {}
      region.rooms[94].path = "fly bj;e;e;e;e;se;se"
      region.rooms[94].name = "大驿道"
      region.rooms[94].zone = "北京"
      region.rooms[94].id = 1070
      region.rooms[94].links = {}
        region.rooms[94].links.ne = {}
          region.rooms[94].links.ne.to = 1071
          region.rooms[94].links.ne.con = ""
        region.rooms[94].links.nw = {}
          region.rooms[94].links.nw.to = 1069
          region.rooms[94].links.nw.con = ""
        region.rooms[94].links.s = {}
          region.rooms[94].links.s.to = 1072
          region.rooms[94].links.s.con = ""
      region.rooms[94].exits = "south|northwest|northeast"
      region.rooms[94].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的，赶着大车的马夫，上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。东北方向是另一条大道。"
    region.rooms[95] = {}
      region.rooms[95].path = "fly gw;s;s;s;sw;sw;s;sw;sw;sw;se"
      region.rooms[95].name = "老龙头"
      region.rooms[95].zone = "北京|关外"
      region.rooms[95].id = 1071
      region.rooms[95].desc = "    老龙头是万里长城最东端。澄海楼巍峨高踞城头，楼上“雄襟万里”的横匾居高临下，直俯大海。自澄海楼筑有一石城逐级而下伸入大海，站在石城终端楼平台上四眺，海天一色，无边无际，气象万千。"
      region.rooms[95].exits = "northwest|southwest"
      region.rooms[95].links = {}
        region.rooms[95].links.nw = {}
          region.rooms[95].links.nw.to = 1555
          region.rooms[95].links.nw.con = ""
        region.rooms[95].links.sw = {}
          region.rooms[95].links.sw.to = 1070
          region.rooms[95].links.sw.con = ""
    region.rooms[96] = {}
      region.rooms[96].path = "fly bj;e;e;e;e;se;se;s"
      region.rooms[96].name = "大驿道"
      region.rooms[96].zone = "北京"
      region.rooms[96].id = 1072
      region.rooms[96].links = {}
        region.rooms[96].links.s = {}
          region.rooms[96].links.s.to = 1074
          region.rooms[96].links.s.con = ""
        region.rooms[96].links.w = {}
          region.rooms[96].links.w.to = 1073
          region.rooms[96].links.w.con = ""
        region.rooms[96].links.n = {}
          region.rooms[96].links.n.to = 1070
          region.rooms[96].links.n.con = ""
      region.rooms[96].exits = "south|north|west"
      region.rooms[96].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。从这里向北向西都可以上京城。南边通往汝州城。"
    region.rooms[97] = {}
      region.rooms[97].path = "fly bj;s;s;s;s;se;se"
      region.rooms[97].name = "大驿道"
      region.rooms[97].zone = "北京"
      region.rooms[97].id = 1073
      region.rooms[97].links = {}
        region.rooms[97].links.e = {}
          region.rooms[97].links.e.to = 1072
          region.rooms[97].links.e.con = ""
        region.rooms[97].links.nw = {}
          region.rooms[97].links.nw.to = 1088
          region.rooms[97].links.nw.con = ""
      region.rooms[97].exits = "east|northwest"
      region.rooms[97].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。"
    region.rooms[98] = {}
      region.rooms[98].path = "fly bj;e;e;e;e;se;se;s;s"
      region.rooms[98].name = "大驿道"
      region.rooms[98].zone = "北京"
      region.rooms[98].id = 1074
      region.rooms[98].links = {}
        region.rooms[98].links.s = {}
          region.rooms[98].links.s.to = 1076
          region.rooms[98].links.s.con = ""
        region.rooms[98].links.w = {}
          region.rooms[98].links.w.to = 1075
          region.rooms[98].links.w.con = ""
        region.rooms[98].links.n = {}
          region.rooms[98].links.n.to = 1072
          region.rooms[98].links.n.con = ""
      region.rooms[98].exits = "south|north|west"
      region.rooms[98].desc = "    你走在一条尘土飞扬的大驿道上。北上就是北京城。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。西边有个小摊，许多人在那里歇息。"
    region.rooms[99] = {}
      region.rooms[99].path = "fly bj;e;e;e;e;se;se;s;s;w"
      region.rooms[99].name = "小摊"
      region.rooms[99].zone = "北京"
      region.rooms[99].id = 1075
      region.rooms[99].links = {}
        region.rooms[99].links.e = {}
          region.rooms[99].links.e.to = 1074
          region.rooms[99].links.e.con = ""
      region.rooms[99].exits = "east"
      region.rooms[99].desc = "    这是一临时搭成的小摊，生意却非常兴隆。路人都爱在这里落脚，你可以在这里打听到京城的奇闻逸趣。小二匆匆忙忙地接待着南来北往的客人。树荫下摆着几张小木桌，桌旁坐满了各种各样的游人。"
    region.rooms[100] = {}
      region.rooms[100].path = "fly bj;e;e;e;e;se;se;s;s;s"
      region.rooms[100].name = "大驿道"
      region.rooms[100].zone = "北京"
      region.rooms[100].id = 1076
      region.rooms[100].links = {}
        region.rooms[100].links.s = {}
          region.rooms[100].links.s.to = 1077
          region.rooms[100].links.s.con = ""
        region.rooms[100].links.n = {}
          region.rooms[100].links.n.to = 1074
          region.rooms[100].links.n.con = ""
      region.rooms[100].exits = "south|north"
      region.rooms[100].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。马上的人个个身着劲装，衣甲鲜明，有的还随身佩带着刀剑。看来都是些些习武的江湖人。道路两旁是整整齐齐的杨树林。"
    region.rooms[101] = {}
      region.rooms[101].path = "fly bj;e;e;e;e;se;se;s;s;s;s"
      region.rooms[101].name = "小道"
      region.rooms[101].zone = "北京"
      region.rooms[101].id = 1077
      region.rooms[101].links = {}
        region.rooms[101].links.e = {}
          region.rooms[101].links.e.to = 1078
          region.rooms[101].links.e.con = ""
        region.rooms[101].links.s = {}
          region.rooms[101].links.s.to = 1079
          region.rooms[101].links.s.con = ""
        region.rooms[101].links.n = {}
          region.rooms[101].links.n.to = 1076
          region.rooms[101].links.n.con = ""
      region.rooms[101].exits = "south|north|east"
      region.rooms[101].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。东边就是大海之滨了。"
    region.rooms[102] = {}
      region.rooms[102].path = "fly bj;e;e;e;e;se;se;s;s;s;s;e"
      region.rooms[102].name = "塘沽口"
      region.rooms[102].zone = "北京"
      region.rooms[102].id = 1078
      region.rooms[102].links = {}
        region.rooms[102].links.w = {}
          region.rooms[102].links.w.to = 1077
          region.rooms[102].links.w.con = ""
      region.rooms[102].exits = "west"
      region.rooms[102].desc = "    这里就是大海之滨，浪花拍打着礁石，发出阵阵响声，海面上一群群海鸥『欧欧..』地叫着，不时有鱼儿跃出海面，溅起层层的浪花。边上有艘大船(chuan)，船上坐着几个渔夫打扮的人，乘船可渡过大海到达海的另一端。西面过天津城就是北京了，东面是一望无际的大海。"
    region.rooms[103] = {}
      region.rooms[103].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s"
      region.rooms[103].name = "汝州城"
      region.rooms[103].zone = "北京"
      region.rooms[103].id = 1079
      region.rooms[103].links = {}
        region.rooms[103].links.s = {}
          region.rooms[103].links.s.to = 1081
          region.rooms[103].links.s.con = ""
        region.rooms[103].links.w = {}
          region.rooms[103].links.w.to = 1080
          region.rooms[103].links.w.con = ""
        region.rooms[103].links.n = {}
          region.rooms[103].links.n.to = 1077
          region.rooms[103].links.n.con = ""
      region.rooms[103].exits = "south|north|west"
      region.rooms[103].desc = "    汝州城是本府的大城，立来是兵家必争之地。故州治在此驻扎重兵，盘查南来北往的行人，并负责翦灭附近山上的草寇。城内一队队官兵来来去去，一派森严气象。再折向西，就是五岳之一的嵩山。"
    region.rooms[104] = {}
      region.rooms[104].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd;s;s;s"
      region.rooms[104].name = "太室阙"
      region.rooms[104].zone = "北京|嵩山"
      region.rooms[104].id = 1080
      region.rooms[104].links = {}
        region.rooms[104].links.e = {}
          region.rooms[104].links.e.to = 1079
          region.rooms[104].links.e.con = ""
        region.rooms[104].links.n = {}
          region.rooms[104].links.n.to = 1385
          region.rooms[104].links.n.con = ""
      region.rooms[104].exits = "east|north|west"
      region.rooms[104].desc = "    嵩山古称方外，又称崇山，为五岳中的中岳，由太室少室二山沿绵而成。汉武帝时称 \"嵩高\" ，取自诗经 \"嵩岳维高，峻极于天\" ，道教以之为第六小洞天。阕高丈余，南面刻 \"中岳太室阳城\" 六字，篆文古朴，苍劲有力。向西就是去少室山少林寺的路。向北一里许便是中岳庙了。"
    region.rooms[105] = {}
      region.rooms[105].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s"
      region.rooms[105].name = "大驿道"
      region.rooms[105].zone = "北京"
      region.rooms[105].id = 1081
      region.rooms[105].links = {}
        region.rooms[105].links.s = {}
          region.rooms[105].links.s.to = 1082
          region.rooms[105].links.s.con = ""
        region.rooms[105].links.n = {}
          region.rooms[105].links.n.to = 1079
          region.rooms[105].links.n.con = ""
      region.rooms[105].exits = "south|north"
      region.rooms[105].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的行商，赶着大车的马夫，上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。"
    region.rooms[106] = {}
      region.rooms[106].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s;s"
      region.rooms[106].name = "南阳城"
      region.rooms[106].zone = "北京"
      region.rooms[106].id = 1082
      region.rooms[106].links = {}
        region.rooms[106].links.ne = {}
          region.rooms[106].links.ne.to = 1087
          region.rooms[106].links.ne.con = ""
        region.rooms[106].links.s = {}
          region.rooms[106].links.s.to = 1086
          region.rooms[106].links.s.con = ""
        region.rooms[106].links.e = {}
          region.rooms[106].links.e.to = 1083
          region.rooms[106].links.e.con = ""
        region.rooms[106].links.w = {}
          region.rooms[106].links.w.to = 1084
          region.rooms[106].links.w.con = ""
        region.rooms[106].links.n = {}
          region.rooms[106].links.n.to = 1081
          region.rooms[106].links.n.con = ""
      region.rooms[106].exits = "south|east|north|northeast|west"
      region.rooms[106].desc = "    这里便是当年诸葛先生的故居。南阳城不大，因为地出要冲，南来北往的客人特别多，所以也五脏俱全，酒楼，客栈，马店，满城子都是。本地人口甚少，到处都是行色匆匆的江湖客人。"
    region.rooms[107] = {}
      region.rooms[107].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s;s;e"
      region.rooms[107].name = "悦来客栈"
      region.rooms[107].zone = "北京"
      region.rooms[107].id = 1083
      region.rooms[107].links = {}
        region.rooms[107].links.w = {}
          region.rooms[107].links.w.to = 1082
          region.rooms[107].links.w.con = ""
      region.rooms[107].exits = "up|west"
      region.rooms[107].desc = "    这是一家远近闻名的悦来客栈，生意非常兴隆。外地游客多选择在这里落脚，你可以在这里打听到各地的风土人情。店小二里里外外忙得团团转，接待着南腔北调的客人。墙上挂着一个牌子(paizi)。"
    region.rooms[108] = {}
      region.rooms[108].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s;s;w"
      region.rooms[108].name = "迎宾楼"
      region.rooms[108].zone = "北京"
      region.rooms[108].id = 1084
      region.rooms[108].links = {}
        region.rooms[108].links.e = {}
          region.rooms[108].links.e.to = 1082
          region.rooms[108].links.e.con = ""
        region.rooms[108].links.u = {}
          region.rooms[108].links.u.to = 1085
          region.rooms[108].links.u.con = ""
      region.rooms[108].exits = "up|east"
      region.rooms[108].desc = "    方圆数百里内提起迎宾楼可以说是无人不知，无人不晓。当年苏学士云游到此，对迎宾楼的素齐赞不绝口，欣然为其题匾，流下一段传遍海内的佳话，从此迎宾楼名声大震。楼下布置简易，顾客多是匆匆的行人，买点包子，鸡腿、米酒就赶路去了。楼上是雅座。"
    region.rooms[109] = {}
      region.rooms[109].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s;s;w;u"
      region.rooms[109].name = "迎宾楼二楼"
      region.rooms[109].zone = "北京"
      region.rooms[109].id = 1085
      region.rooms[109].links = {}
        region.rooms[109].links.d = {}
          region.rooms[109].links.d.to = 1084
          region.rooms[109].links.d.con = ""
      region.rooms[109].exits = "down"
      region.rooms[109].desc = "    这里是雅座，文人学士经常在这里吟诗作画，富商土豪也在这里边吃喝边作交易。这里也是城里举办喜宴的最佳场所。你站在楼上眺望，只觉得心旷神怡。东面是一池湖水，碧波荡漾。北面是崇山峻岭。墙上挂着价格牌子(paizi)。"
    region.rooms[110] = {}
      region.rooms[110].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s;s;s"
      region.rooms[110].name = "汉水北岸"
      region.rooms[110].zone = "北京"
      region.rooms[110].id = 1086
      region.rooms[110].links = {}
        region.rooms[110].links.n = {}
          region.rooms[110].links.n.to = 1082
          region.rooms[110].links.n.con = ""
      region.rooms[110].exits = "north"
      region.rooms[110].desc = "    汉水北岸也是相当热闹，自北岸渡口往北，一条笔直的官道直通南阳。此地民风淳朴，路旁夹柳成阴，酒厮林立，且都有一面大大的「酒」旗迎风飘扬，蔚为壮观。也有不少小贩沿路叫买，语多难辨，却也令人盛情难却。"
    region.rooms[111] = {}
      region.rooms[111].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s;s;ne"
      region.rooms[111].name = "聚贤庄门"
      region.rooms[111].zone = "北京"
      region.rooms[111].id = 1087
      region.rooms[111].links = {}
        region.rooms[111].links.sw = {}
          region.rooms[111].links.sw.to = 1082
          region.rooms[111].links.sw.con = ""
      region.rooms[111].exits = "southwest"
      region.rooms[111].desc = "    这里是聚贤庄大门。聚贤庄庄主乃是游氏双雄游骥、游驹。二位庄主家财豪富，交游广阔，武功了得，名头响亮，但在武林中既无什么了不起的势力，也算不上如何德高望重。"
    region.rooms[112] = {}
      region.rooms[112].path = "fly bj;s;s;s;s;se"
      region.rooms[112].name = "大驿道"
      region.rooms[112].zone = "北京"
      region.rooms[112].id = 1088
      region.rooms[112].links = {}
        region.rooms[112].links.nw = {}
          region.rooms[112].links.nw.to = 1089
          region.rooms[112].links.nw.con = ""
        region.rooms[112].links.se = {}
          region.rooms[112].links.se.to = 1073
          region.rooms[112].links.se.con = ""
      region.rooms[112].exits = "northwest|southeast|southwest"
      region.rooms[112].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。从这里远远的就可以望见北京城。西南是通往恒山。"
    region.rooms[113] = {}
      region.rooms[113].path = "fly bj;s;s;s;s"
      region.rooms[113].name = "大驿道"
      region.rooms[113].zone = "北京"
      region.rooms[113].id = 1089
      region.rooms[113].links = {}
        region.rooms[113].links.n = {}
          region.rooms[113].links.n.to = 1091
          region.rooms[113].links.n.con = ""
        region.rooms[113].links.w = {}
          region.rooms[113].links.w.to = 1090
          region.rooms[113].links.w.con = ""
        region.rooms[113].links.se = {}
          region.rooms[113].links.se.to = 1088
          region.rooms[113].links.se.con = ""
      region.rooms[113].exits = "north|southeast|west"
      region.rooms[113].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。北边就是永定门了。"
    region.rooms[114] = {}
      region.rooms[114].path = "fly bj;s;s;s;s;w"
      region.rooms[114].name = "雪山别院"
      region.rooms[114].zone = "北京"
      region.rooms[114].id = 1090
      region.rooms[114].links = {}
        region.rooms[114].links.e = {}
          region.rooms[114].links.e.to = 1089
          region.rooms[114].links.e.con = ""
      region.rooms[114].exits = "east"
      region.rooms[114].desc = "    这里是雪山寺的分部，当年贡唐仓大喇嘛不远万里进京面圣，被封为国师，就在此处宣扬佛法。"
    region.rooms[115] = {}
      region.rooms[115].path = "fly bj;s;s;s"
      region.rooms[115].name = "永定门"
      region.rooms[115].zone = "北京"
      region.rooms[115].id = 1091
      region.rooms[115].links = {}
        region.rooms[115].links.s = {}
          region.rooms[115].links.s.to = 1089
          region.rooms[115].links.s.con = ""
        region.rooms[115].links.n = {}
          region.rooms[115].links.n.to = 1092
          region.rooms[115].links.n.con = ""
      region.rooms[115].exits = "south|north"
      region.rooms[115].desc = "    这里是永定门，城门正上方刻着“永定门”三个大字，城墙上贴着几张官府告示 (gaoshi)。每天都有许多人从这里是出入京城，正因如此官兵盘查得格外仔细。 一条笔直的大道向南北两边延伸。南边的驿道上人来车往，尘土飞扬。北边通往城中心。"
    region.rooms[116] = {}
      region.rooms[116].path = "fly bj;s;s"
      region.rooms[116].name = "南城广场"
      region.rooms[116].zone = "北京"
      region.rooms[116].id = 1092
      region.rooms[116].links = {}
        region.rooms[116].links.e = {}
          region.rooms[116].links.e.to = 1093
          region.rooms[116].links.e.con = ""
        region.rooms[116].links.w = {}
          region.rooms[116].links.w.to = 1094
          region.rooms[116].links.w.con = ""
        region.rooms[116].links.s = {}
          region.rooms[116].links.s.to = 1091
          region.rooms[116].links.s.con = ""
        region.rooms[116].links.n = {}
          region.rooms[116].links.n.to = 1095
          region.rooms[116].links.n.con = ""
      region.rooms[116].exits = "south|north|east|west"
      region.rooms[116].desc = "    这里是一个热闹的广场，正是北京城里最热闹、最杂乱的地段。一座天桥横跨东西，正是卖杂货、变把戏、跑江湖的闲杂人等聚居的所在。宽阔的大道向南北两头延伸。南边是永定门，通往郊外;北边是南大街，通往天安门。东边是有名的“高升茶馆”，人们都爱在那儿休息聊天。西边有一家很大的屠宰场，不时传来猪凄厉的哀嚎。"
    region.rooms[117] = {}
      region.rooms[117].path = "fly bj;s;s;e"
      region.rooms[117].name = "高升茶馆"
      region.rooms[117].zone = "北京"
      region.rooms[117].id = 1093
      region.rooms[117].links = {}
        region.rooms[117].links.w = {}
          region.rooms[117].links.w.to = 1092
          region.rooms[117].links.w.con = ""
      region.rooms[117].exits = "west"
      region.rooms[117].desc = "        你一走进来，就闻到一股茶香沁入心脾，精神为之一爽。几张八仙桌一字排开，坐满了客人，或高声谈笑，或交头接耳。你要想打听江湖掌故和谣言，这里是个好所在。"
    region.rooms[118] = {}
      region.rooms[118].path = "fly bj;s;s;w"
      region.rooms[118].name = "屠宰场"
      region.rooms[118].zone = "北京"
      region.rooms[118].id = 1094
      region.rooms[118].links = {}
        region.rooms[118].links.e = {}
          region.rooms[118].links.e.to = 1092
          region.rooms[118].links.e.con = ""
      region.rooms[118].exits = "east"
      region.rooms[118].desc = "    这里是屠宰场，空气中弥漫着猪的气味。偶尔一阵热风吹过，顿时一股臭气袭来，直熏得人作呕。一个中年人手握屠刀，指挥着伙计们杀猪去毛。这就是京城最大的屠宰场，据说宫里所有的猪肉都是从这里送去的。"
    region.rooms[119] = {}
      region.rooms[119].path = "fly bj;s"
      region.rooms[119].name = "南大街"
      region.rooms[119].zone = "北京"
      region.rooms[119].id = 1095
      region.rooms[119].links = {}
        region.rooms[119].links.e = {}
          region.rooms[119].links.e.to = 1096
          region.rooms[119].links.e.con = ""
        region.rooms[119].links.w = {}
          region.rooms[119].links.w.to = 1098
          region.rooms[119].links.w.con = ""
        region.rooms[119].links.s = {}
          region.rooms[119].links.s.to = 1092
          region.rooms[119].links.s.con = ""
        region.rooms[119].links.n = {}
          region.rooms[119].links.n.to = 962
          region.rooms[119].links.n.con = ""
      region.rooms[119].exits = "south|north|east|west"
      region.rooms[119].desc = "    这里是南大街。北边是天安门广场，南边是南大街广场。西边是一家店铺，墙上写着一个大大的“当”字，仔细倾听，可以听到压低的讨价还价的声音。东边是一家小客店。"
    region.rooms[120] = {}
      region.rooms[120].path = "fly bj;s;e"
      region.rooms[120].name = "客店"
      region.rooms[120].zone = "北京"
      region.rooms[120].id = 1096
      region.rooms[120].links = {}
        region.rooms[120].links.w = {}
          region.rooms[120].links.w.to = 1095
          region.rooms[120].links.w.con = ""
        region.rooms[120].links.e = {}
          region.rooms[120].links.e.to = 1097
          region.rooms[120].links.e.con = ""
      region.rooms[120].exits = "east|west"
      region.rooms[120].desc = "    这是一家价钱低廉的客栈，生意非常兴隆。据说全国各地都有这样的分店，而且所有的客栈都归一个人所有。不过他从来不露面，谁也不知道他究竟是怎样一个人。"
    region.rooms[121] = {}
      region.rooms[121].path = "fly bj;s;e;e"
      region.rooms[121].name = "马厩"
      region.rooms[121].zone = "北京"
      region.rooms[121].id = 1097
      region.rooms[121].links = {}
        region.rooms[121].links.w = {}
          region.rooms[121].links.w.to = 1096
          region.rooms[121].links.w.con = ""
      region.rooms[121].exits = "west"
      region.rooms[121].desc = "    这是客店后的马厩，常年供应新鲜草料。北京自古天子脚下，啥都有规矩，客店也特会伺候人，马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净，一直伺候到客人上路。马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。    马厩中堆放著几堆草料，正中有一口泔槽。"
    region.rooms[122] = {}
      region.rooms[122].path = "fly bj;s;w"
      region.rooms[122].name = "当铺"
      region.rooms[122].zone = "北京"
      region.rooms[122].id = 1098
      region.rooms[122].links = {}
        region.rooms[122].links.e = {}
          region.rooms[122].links.e.to = 1095
          region.rooms[122].links.e.con = ""
      region.rooms[122].exits = "east"
      region.rooms[122].desc = "    这是一家以买卖公平著称的当铺，一个五尺高的柜台挡在你的面前，柜台上摆着一个牌子(paizi)，柜台后坐着贾老板，一双精明的眼睛上上下下打量着你。"
    region.rooms[123] = {}
      region.rooms[123].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole"
      region.rooms[123].name = "天地会暗道"
      region.rooms[123].zone = "北京"
      region.rooms[123].id = 1343
      region.rooms[123].links = {}
        region.rooms[123].links.n = {}
          region.rooms[123].links.n.to = 1354
          region.rooms[123].links.n.con = ""
        region.rooms[123].links.s = {}
          region.rooms[123].links.s.to = 1344
          region.rooms[123].links.s.con = ""
        region.rooms[123].links.wu = {}
          region.rooms[123].links.wu.to = 1041
          region.rooms[123].links.wu.con = ""
      region.rooms[123].exits = "westup|south|north|eastup"
      region.rooms[123].desc = "    这是一条黑漆漆的地道，曲曲折折地通向前方。两边都是土墙，隐约可以听到上面脚底落地的声音。空气中弥漫着潮湿的泥土气息，令人感到十分凉爽。一个道人站在这里，守卫着上面的两个出口。"
    region.rooms[124] = {}
      region.rooms[124].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;s"
      region.rooms[124].name = "天地会暗道"
      region.rooms[124].zone = "北京"
      region.rooms[124].id = 1344
      region.rooms[124].links = {}
        region.rooms[124].links.s = {}
          region.rooms[124].links.s.to = 1345
          region.rooms[124].links.s.con = ""
        region.rooms[124].links.n = {}
          region.rooms[124].links.n.to = 1343
          region.rooms[124].links.n.con = ""
      region.rooms[124].exits = "south|north"
      region.rooms[124].desc = "    一走进黑漆漆的地道，阵阵阴风从南边吹来，你感到有些冷。两边都是土墙，隐约可以听到上面脚底落地的声音。"
    region.rooms[125] = {}
      region.rooms[125].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;s;s"
      region.rooms[125].name = "天地会暗道"
      region.rooms[125].zone = "北京"
      region.rooms[125].id = 1345
      region.rooms[125].links = {}
        region.rooms[125].links.e = {}
          region.rooms[125].links.e.to = 1345
          region.rooms[125].links.e.con = ""
        region.rooms[125].links.w = {}
          region.rooms[125].links.w.to = 1346
          region.rooms[125].links.w.con = ""
        region.rooms[125].links.s = {}
          region.rooms[125].links.s.to = 1345
          region.rooms[125].links.s.con = ""
        region.rooms[125].links.n = {}
          region.rooms[125].links.n.to = 1347
          region.rooms[125].links.n.con = ""
      region.rooms[125].exits = "south|east|north|west"
      region.rooms[125].desc = "    地道里一片漆黑，呼呼的风声从四面八方传来。你什么也看不见，只能在地道里瞎摸乱撞。西面似乎隐隐约约有人说话，但只一会儿又没声了。你使劲地摇了摇头，很怀疑这到底是不是幻觉。好象你已经迷路了。"
    region.rooms[126] = {}
      region.rooms[126].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;s;s;w"
      region.rooms[126].name = "天地会暗道"
      region.rooms[126].zone = "北京"
      region.rooms[126].id = 1346
      region.rooms[126].links = {}
        region.rooms[126].links.e = {}
          region.rooms[126].links.e.to = 1347
          region.rooms[126].links.e.con = ""
        region.rooms[126].links.w = {}
          region.rooms[126].links.w.to = 1348
          region.rooms[126].links.w.con = ""
        region.rooms[126].links.s = {}
          region.rooms[126].links.s.to = 1345
          region.rooms[126].links.s.con = ""
        region.rooms[126].links.n = {}
          region.rooms[126].links.n.to = 1349
          region.rooms[126].links.n.con = ""
      region.rooms[126].exits = "south|east|north|west"
      region.rooms[126].desc = "    地道里一片漆黑，呼呼的风声从四面八方传来。你什么也看不见，只能在地道里瞎摸乱撞。西面似乎隐隐约约有人说话，但只一会儿又没声了。你使劲地摇了摇头，很怀疑这到底是不是幻觉。好象你已经迷路了。"
    region.rooms[127] = {}
      region.rooms[127].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;n;n"
      region.rooms[127].name = "天地会暗道"
      region.rooms[127].zone = "北京"
      region.rooms[127].id = 1347
      region.rooms[127].links = {}
        region.rooms[127].links.e = {}
          region.rooms[127].links.e.to = 1348
          region.rooms[127].links.e.con = ""
        region.rooms[127].links.w = {}
          region.rooms[127].links.w.to = 1347
          region.rooms[127].links.w.con = ""
        region.rooms[127].links.s = {}
          region.rooms[127].links.s.to = 1347
          region.rooms[127].links.s.con = ""
        region.rooms[127].links.n = {}
          region.rooms[127].links.n.to = 1345
          region.rooms[127].links.n.con = ""
      region.rooms[127].exits = "south|east|north|west"
      region.rooms[127].desc = "    地道里一片漆黑，呼呼的风声从四面八方传来。你什么也看不见，只能在地道里瞎摸乱撞。东面似乎隐隐约约有人说话，但只一会儿又没声了。你使劲地摇了摇头，很怀疑这到底是不是幻觉。好象你已经迷路了。"
    region.rooms[128] = {}
      region.rooms[128].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;n;n;e"
      region.rooms[128].name = "天地会暗道"
      region.rooms[128].zone = "北京"
      region.rooms[128].id = 1348
      region.rooms[128].links = {}
        region.rooms[128].links.e = {}
          region.rooms[128].links.e.to = 1346
          region.rooms[128].links.e.con = ""
        region.rooms[128].links.s = {}
          region.rooms[128].links.s.to = 1349
          region.rooms[128].links.s.con = ""
        region.rooms[128].links.w = {}
          region.rooms[128].links.w.to = 1347
          region.rooms[128].links.w.con = ""
        region.rooms[128].links.n = {}
          region.rooms[128].links.n.to = 1345
          region.rooms[128].links.n.con = ""
      region.rooms[128].exits = "south|east|north|west"
      region.rooms[128].desc = "    地道里一片漆黑，呼呼的风声从四面八方传来。你什么也看不见，只能在地道里瞎摸乱撞。东面似乎隐隐约约有人说话，但只一会儿又没声了。你使劲地摇了摇头，很怀疑这到底是不是幻觉。好象你已经迷路了。"
    region.rooms[129] = {}
      region.rooms[129].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;n;n;e;s"
      region.rooms[129].name = "天地会暗道"
      region.rooms[129].zone = "北京"
      region.rooms[129].id = 1349
      region.rooms[129].links = {}
        region.rooms[129].links.e = {}
          region.rooms[129].links.e.to = 1350
          region.rooms[129].links.e.con = ""
        region.rooms[129].links.s = {}
          region.rooms[129].links.s.to = 1346
          region.rooms[129].links.s.con = ""
        region.rooms[129].links.w = {}
          region.rooms[129].links.w.to = 1347
          region.rooms[129].links.w.con = ""
        region.rooms[129].links.n = {}
          region.rooms[129].links.n.to = 1345
          region.rooms[129].links.n.con = ""
      region.rooms[129].exits = "south|north|east|west"
      region.rooms[129].desc = "    地道里一片漆黑，呼呼的风声从四面八方传来。你什么也看不见，只能在地道里瞎摸乱撞。北面似乎隐隐约约有人说话，但只一会儿又没声了。你使劲地摇了摇头，很怀疑这到底是不是幻觉。好象你已经迷路了。"
    region.rooms[130] = {}
      region.rooms[130].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;n;n;e;s;e"
      region.rooms[130].name = "天地会暗道"
      region.rooms[130].zone = "北京"
      region.rooms[130].id = 1350
      region.rooms[130].links = {}
        region.rooms[130].links.e = {}
          region.rooms[130].links.e.to = 1351
          region.rooms[130].links.e.con = ""
        region.rooms[130].links.s = {}
          region.rooms[130].links.s.to = 1349
          region.rooms[130].links.s.con = ""
        region.rooms[130].links.w = {}
          region.rooms[130].links.w.to = 1351
          region.rooms[130].links.w.con = ""
        region.rooms[130].links.n = {}
          region.rooms[130].links.n.to = 1351
          region.rooms[130].links.n.con = ""
      region.rooms[130].exits = "south|east|north|west"
      region.rooms[130].desc = "    地道里一片漆黑，呼呼的风声从四面八方传来。你什么也看不见，只能在地道里瞎摸乱撞。北面似乎隐隐约约有人说话，但只一会儿又没声了。你使劲地摇了摇头，很怀疑这到底是不是幻觉。好象你已经迷路了。"
    region.rooms[131] = {}
      region.rooms[131].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;n;n;e;s;e;e"
      region.rooms[131].name = "天地会暗道"
      region.rooms[131].zone = "北京"
      region.rooms[131].id = 1351
      region.rooms[131].links = {}
        region.rooms[131].links.e = {}
          region.rooms[131].links.e.to = 1350
          region.rooms[131].links.e.con = ""
        region.rooms[131].links.w = {}
          region.rooms[131].links.w.to = 1350
          region.rooms[131].links.w.con = ""
        region.rooms[131].links.s = {}
          region.rooms[131].links.s.to = 1350
          region.rooms[131].links.s.con = ""
        region.rooms[131].links.n = {}
          region.rooms[131].links.n.to = 1352
          region.rooms[131].links.n.con = ""
      region.rooms[131].exits = "south|east|north|west"
      region.rooms[131].desc = "    终于走出了暗道，你长长的舒了一口气。北边是天地会青木堂的大厅，明亮的灯光让人感到无比温暖。"
    region.rooms[132] = {}
      region.rooms[132].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;n;n;e;s;e;e;n"
      region.rooms[132].name = "大厅"
      region.rooms[132].zone = "北京"
      region.rooms[132].id = 1352
      region.rooms[132].links = {}
        region.rooms[132].links.e = {}
          region.rooms[132].links.e.to = 1353
          region.rooms[132].links.e.con = ""
        region.rooms[132].links.s = {}
          region.rooms[132].links.s.to = 1351
          region.rooms[132].links.s.con = ""
        region.rooms[132].links.n = {}
          region.rooms[132].links.n.to = 1094
          region.rooms[132].links.n.con = ""
      region.rooms[132].exits = "south|east|north"
      region.rooms[132].desc = "    这里就是天下闻名的天地会青木堂大厅，只见一张板桌上供着两个灵牌，中间一个写着“大明天子之位”，侧边一个写着“大明延平郡王郑之位”。此外有一块白木 (baimu)，上面密密麻麻全是血字。厅侧有一副对联(duilian)。东边是侧厅，南北都是暗道。"
    region.rooms[133] = {}
      region.rooms[133].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;n;n;e;s;e;e;n;e"
      region.rooms[133].name = "侧厅"
      region.rooms[133].zone = "北京"
      region.rooms[133].id = 1353
      region.rooms[133].links = {}
        region.rooms[133].links.w = {}
          region.rooms[133].links.w.to = 1352
          region.rooms[133].links.w.con = ""
      region.rooms[133].exits = "west"
      region.rooms[133].desc = "    这里是侧厅，靠墙是一排书架，摆满了各种拳谱、书籍。墙角有一张木床。天地会总舵主陈近南常常在这里读书、休息。"
    region.rooms[134] = {}
      region.rooms[134].path = "fly bj;w;w;s;s;se;e;knock guancai 3;enter hole;n"
      region.rooms[134].name = "天地会暗道"
      region.rooms[134].zone = "北京"
      region.rooms[134].id = 1354
      region.rooms[134].links = {}
        region.rooms[134].links.s = {}
          region.rooms[134].links.s.to = 1343
          region.rooms[134].links.s.con = ""
        region.rooms[134].links.n = {}
          region.rooms[134].links.n.to = 1347
          region.rooms[134].links.n.con = ""
      region.rooms[134].exits = "south|north"
      region.rooms[134].desc = "    一走进黑漆漆的地道，阵阵阴风从北边吹来，你感到有些冷。两边都是土墙，隐约可以听到上面脚底落地的声音。"
    region.rooms[135] = {}
      region.rooms[135].attr = "danger"
      region.rooms[135].path = "fly bj;w;w;s;s;sw;se;s;e"
      region.rooms[135].name = "东客房"
      region.rooms[135].zone = "北京"
      region.rooms[135].id = 2986
      region.rooms[135].desc = "    一进门，只见六个喇嘛手持戒刀，围着一白衣女尼拼命砍杀，只是给白衣女尼的袖力掌风逼住了，欺不近身。但那白衣女子头顶已冒出丝丝白气，显然已尽了全力。她只一条臂膀，再支持下去恐怕难以抵敌。地上斑斑点点都是血迹。"
      region.rooms[135].exits = "west"
      region.rooms[135].links = {}
        region.rooms[135].links.w = {}
          region.rooms[135].links.w.to = 1044
          region.rooms[135].links.w.con = ""
  region.center = 962
return region