local region = {}
  region.cmd = "fly bt"
  region.name = "白驼山"
  region.id = "bt"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly bt"
      region.rooms[1].name = "大厅"
      region.rooms[1].zone = "白驼山"
      region.rooms[1].id = 2002
      region.rooms[1].links = {}
        region.rooms[1].links.sd = {}
          region.rooms[1].links.sd.to = 2024
          region.rooms[1].links.sd.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 2003
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "north|southdown"
      region.rooms[1].desc = "    这是『白驼山庄』的大厅，内部摆设极尽豪华，当中一张黑色檀木条案，上面陈放着精美的花瓶和一些珍贵的瓷器，四壁挂满名家的字画。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly bt;n"
      region.rooms[2].name = "练功场"
      region.rooms[2].zone = "白驼山"
      region.rooms[2].id = 2003
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 2004
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 2015
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 2002
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 2005
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "south|north|east|west"
      region.rooms[2].desc = "    这里是白驼山弟子的练功场。东边是一个练功房。北边是个门廊，西边连着一条长廊，雕梁画柱，非常气派。南面可见巍巍大厅。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly bt;n;e"
      region.rooms[3].name = "练功房"
      region.rooms[3].zone = "白驼山"
      region.rooms[3].id = 2004
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 2003
          region.rooms[3].links.w.con = ""
      region.rooms[3].exits = "3|2|1|west"
      region.rooms[3].desc = "    这里是白驼山弟子的练功房。里面有几个单间，是练功室。第子们在里边砌磋武艺，绝对不允许外人打搅。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly bt;n;n"
      region.rooms[4].name = "门廊"
      region.rooms[4].zone = "白驼山"
      region.rooms[4].id = 2005
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 2003
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 2006
          region.rooms[4].links.n.con = ""
      region.rooms[4].exits = "south|north"
      region.rooms[4].desc = "    这是个门廊，门廊的飞檐上挂着一串串的小铜铃，在清风中发出清脆动听的铃声。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly bt;n;n;n"
      region.rooms[5].name = "花园"
      region.rooms[5].zone = "白驼山"
      region.rooms[5].id = 2006
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 2009
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 2005
          region.rooms[5].links.s.con = ""
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 2007
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 2011
          region.rooms[5].links.n.con = ""
      region.rooms[5].exits = "south|east|north|west"
      region.rooms[5].desc = "    这是个美丽的大花园，园子里面种着鲜艳的红玫瑰。白衣少女常来这里嬉戏。沿着弯弯曲曲的花径，可以通到山庄的许多地方。东边是厨房。西边是白驼山少主『欧阳克』的内室，门虚掩着，不知主人在不在。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly bt;n;n;n;w"
      region.rooms[6].name = "内室"
      region.rooms[6].zone = "白驼山"
      region.rooms[6].id = 2007
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 2006
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.d = {}
          region.rooms[6].links.d.to = 2008
          region.rooms[6].links.d.con = ""
      region.rooms[6].exits = "east|down"
      region.rooms[6].desc = "    这是『欧阳克』的内室，内部摆设很有情趣。屋角摆着一盆名贵兰花，正骄傲地吐露芳蕊。花盆(pen) 下撒落一些浮土，可能是被人搬出去晒太阳时撒下的。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly bt;n;n;n;w;d"
      region.rooms[7].name = "密道"
      region.rooms[7].zone = "白驼山"
      region.rooms[7].id = 2008
      region.rooms[7].links = {}
      region.rooms[7].exits = "east"
      region.rooms[7].desc = "    这里是漆黑的密道，当年白驼山弟子为了直达中原而挖凿的。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly bt;n;n;n;e"
      region.rooms[8].name = "厨房"
      region.rooms[8].zone = "白驼山"
      region.rooms[8].id = 2009
      region.rooms[8].links = {}
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 2006
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 2010
          region.rooms[8].links.e.con = ""
      region.rooms[8].exits = "east|west"
      region.rooms[8].desc = "    这是间宽敞的厨房，厨师们在展示各自的烹饪绝活。整个房间弥漫着令人垂涎欲滴的菜香。墙上贴着一张醒目的启事(note)。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly bt;n;n;n;e;e"
      region.rooms[9].name = "柴房"
      region.rooms[9].zone = "白驼山"
      region.rooms[9].id = 2010
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 2009
          region.rooms[9].links.w.con = ""
      region.rooms[9].exits = "west"
      region.rooms[9].desc = "    这是间不宽的柴房，木柴已经快烧光了，墙角放着几把『柴刀』。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly bt;n;n;n;n"
      region.rooms[10].name = "竹园"
      region.rooms[10].zone = "白驼山"
      region.rooms[10].id = 2011
      region.rooms[10].links = {}
        region.rooms[10].links.ne = {}
          region.rooms[10].links.ne.to = 2013
          region.rooms[10].links.ne.con = ""
        region.rooms[10].links.nw = {}
          region.rooms[10].links.nw.to = 2012
          region.rooms[10].links.nw.con = ""
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 2006
          region.rooms[10].links.s.con = ""
      region.rooms[10].exits = "south|northwest|northeast"
      region.rooms[10].desc = "    这里是一个幽静的竹园，高高低低的翠竹把这里装点得别有情致。西北方是后院，东北方有个兔苑。南边是花园。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly bt;n;n;n;n;nw"
      region.rooms[11].name = "后院"
      region.rooms[11].zone = "白驼山"
      region.rooms[11].id = 2012
      region.rooms[11].links = {}
        region.rooms[11].links.se = {}
          region.rooms[11].links.se.to = 2011
          region.rooms[11].links.se.con = ""
      region.rooms[11].exits = "southeast"
      region.rooms[11].desc = "    这是僻静的后院，住着『欧阳克』的老奶妈『张妈』。由于年岁已高，她已经不干活了，在这里静养。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly bt;n;n;n;n;ne"
      region.rooms[12].name = "兔苑"
      region.rooms[12].zone = "白驼山"
      region.rooms[12].id = 2013
      region.rooms[12].links = {}
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 2014
          region.rooms[12].links.n.con = ""
        region.rooms[12].links.sw = {}
          region.rooms[12].links.sw.to = 2011
          region.rooms[12].links.sw.con = ""
      region.rooms[12].exits = "east|north|west|southwest"
      region.rooms[12].desc = "    这是个好玩的兔苑，几只大白兔静静地蹲在绿草地上吃草。往北是后门，西南方是竹园。西面传来阵阵猛兽的嚎叫，东面有一个蛇园。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly bt;n;n;n;n;ne;n"
      region.rooms[13].name = "后门"
      region.rooms[13].zone = "白驼山"
      region.rooms[13].id = 2014
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 2013
          region.rooms[13].links.s.con = "k1:门卫"
      region.rooms[13].exits = "south|north"
      region.rooms[13].desc = "    这是个山庄的后门。这里有捷径可以通向星宿海。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly bt;n;w"
      region.rooms[14].name = "长廊"
      region.rooms[14].zone = "白驼山"
      region.rooms[14].id = 2015
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 2003
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 2018
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 2017
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 2016
          region.rooms[14].links.n.con = "k1:门卫"
      region.rooms[14].exits = "south|east|north|west"
      region.rooms[14].desc = "    这里是非常气派的长廊。北边是间休息室。南边有间药房，里面传来一阵器皿碰击的声音。西边是扇拱月形小敞门。东边是练功场。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly bt;n;w;|!k1:门卫:n|"
      region.rooms[15].name = "休息室"
      region.rooms[15].zone = "白驼山"
      region.rooms[15].id = 2016
      region.rooms[15].links = {}
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 2015
          region.rooms[15].links.s.con = ""
      region.rooms[15].exits = "south"
      region.rooms[15].desc = "    这里是间休息室，里面有张大床。在这里睡觉非常舒服，没人能打扰。南面是气派的长廊。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly bt;n;w;s"
      region.rooms[16].name = "药房"
      region.rooms[16].zone = "白驼山"
      region.rooms[16].id = 2017
      region.rooms[16].links = {}
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 2015
          region.rooms[16].links.n.con = ""
      region.rooms[16].exits = "north"
      region.rooms[16].desc = "    这里是间药房，靠墙放着一只大药柜。屋子里有张桌子，上边摆满了炼药用的瓶瓶罐罐。其中一个药瓶(bottle)里只装了清水。炼药师是位小姑娘，正在那里发呆，不知在想什么。北面是气派的长廊。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly bt;n;w;w"
      region.rooms[17].name = "西门"
      region.rooms[17].zone = "白驼山"
      region.rooms[17].id = 2018
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 2015
          region.rooms[17].links.e.con = "k1:门卫"
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 2019
          region.rooms[17].links.w.con = ""
      region.rooms[17].exits = "east|west"
      region.rooms[17].desc = "    这是个山庄的西门。拱月形的竹门分外雅致，门上挂着一块竹牌(pai)。西门外面杂草丛生。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly bt;n;w;w;w"
      region.rooms[18].name = "草丛"
      region.rooms[18].zone = "白驼山"
      region.rooms[18].id = 2019
      region.rooms[18].links = {}
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 2018
          region.rooms[18].links.e.con = ""
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 2019
          region.rooms[18].links.w.con = ""
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 2019
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 2020
          region.rooms[18].links.n.con = ""
      region.rooms[18].exits = "south|east|north|west"
      region.rooms[18].desc = "    这里是乱草丛。东边是扇拱月形小敞门。其余三面都是齐腰高的蒿草，常有蛇出没。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly bt;n;w;w;w;n"
      region.rooms[19].name = "草丛"
      region.rooms[19].zone = "白驼山"
      region.rooms[19].id = 2020
      region.rooms[19].links = {}
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 2019
          region.rooms[19].links.e.con = ""
        region.rooms[19].links.w = {}
          region.rooms[19].links.w.to = 2020
          region.rooms[19].links.w.con = ""
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 2019
          region.rooms[19].links.s.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 2021
          region.rooms[19].links.n.con = ""
      region.rooms[19].exits = "south|east|north|west"
      region.rooms[19].desc = "    这里是乱草丛。北边是青竹林。其余三面都是齐腰高的蒿草，常有蛇出没。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly bt;n;w;w;w;n;n"
      region.rooms[20].name = "竹林"
      region.rooms[20].zone = "白驼山"
      region.rooms[20].id = 2021
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 2020
          region.rooms[20].links.s.con = ""
        region.rooms[20].links.nu = {}
          region.rooms[20].links.nu.to = 2022
          region.rooms[20].links.nu.con = ""
      region.rooms[20].exits = "south|northup"
      region.rooms[20].desc = "    这里是青竹林，常有蛇出没。南边是蒿草丛。北边有一个大岩洞。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly bt;n;w;w;w;n;n;nu"
      region.rooms[21].name = "岩洞"
      region.rooms[21].zone = "白驼山"
      region.rooms[21].id = 2022
      region.rooms[21].links = {}
        region.rooms[21].links.sd = {}
          region.rooms[21].links.sd.to = 2021
          region.rooms[21].links.sd.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 2023
          region.rooms[21].links.n.con = ""
      region.rooms[21].exits = "north|southdown"
      region.rooms[21].desc = "    这里是大岩洞，它是在『白驼山』特殊的地质条件下经过漫长的年代形成的。南边是青竹林。再往北走就进洞了。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly bt;n;w;w;w;n;n;nu;n"
      region.rooms[22].name = "岩洞内"
      region.rooms[22].zone = "白驼山"
      region.rooms[22].id = 2023
      region.rooms[22].links = {}
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 2022
          region.rooms[22].links.s.con = ""
      region.rooms[22].exits = "south"
      region.rooms[22].desc = "    这里是岩洞内部，洞顶上悬挂着洁白的钟乳石，中间有一个黑黑的大洞(hole)，看起来很深，不知道通向那里。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly bt;sd"
      region.rooms[23].name = "院子"
      region.rooms[23].zone = "白驼山"
      region.rooms[23].id = 2024
      region.rooms[23].links = {}
        region.rooms[23].links.nu = {}
          region.rooms[23].links.nu.to = 2002
          region.rooms[23].links.nu.con = ""
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 2025
          region.rooms[23].links.s.con = ""
      region.rooms[23].exits = "south|northup|west"
      region.rooms[23].desc = "    这是一个大院子，打扫得一尘不染。四周装点着青青翠竹，错落有致。西边是武器库。东边有一间储藏室，房门(door)关闭着。北边是『白驼山庄』的大厅。南边就是大门了。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly bt;sd;s"
      region.rooms[24].name = "大门"
      region.rooms[24].zone = "白驼山"
      region.rooms[24].id = 2025
      region.rooms[24].links = {}
        region.rooms[24].links.sd = {}
          region.rooms[24].links.sd.to = 2026
          region.rooms[24].links.sd.con = ""
        region.rooms[24].links.n = {}
          region.rooms[24].links.n.to = 2024
          region.rooms[24].links.n.con = ""
      region.rooms[24].exits = "north|southdown"
      region.rooms[24].desc = "    这就是闻名天下的『白驼山庄』的大门。大门梁上雕龙刻凤，美奂美仑，不知凝聚着多少能工巧匠的心血。更显出庄主的富有与显贵。门前左右各蹲着一只威武庄严的石狮子。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly bt;sd;s;sd"
      region.rooms[25].name = "石阶"
      region.rooms[25].zone = "白驼山"
      region.rooms[25].id = 2026
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 2027
          region.rooms[25].links.e.con = ""
        region.rooms[25].links.sd = {}
          region.rooms[25].links.sd.to = 2028
          region.rooms[25].links.sd.con = ""
        region.rooms[25].links.nu = {}
          region.rooms[25].links.nu.to = 2025
          region.rooms[25].links.nu.con = ""
      region.rooms[25].exits = "east|northup|southdown"
      region.rooms[25].desc = "    你走在青石板铺成的石阶上。这里就是传说中神秘的白驼山。远远望去，两座白沙堆积形成的山峰好像一只骆驼的脊背。一座山门立在你的眼前。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly bt;sd;s;sd;e"
      region.rooms[26].name = "草坪"
      region.rooms[26].zone = "白驼山"
      region.rooms[26].id = 2027
      region.rooms[26].links = {}
        region.rooms[26].links.w = {}
          region.rooms[26].links.w.to = 2026
          region.rooms[26].links.w.con = ""
      region.rooms[26].exits = "west"
      region.rooms[26].desc = "    这里是一块芳草坪，绿草茵茵，蝴蝶漫舞，让人感到惬意。不过偶尔也会碰到菜花蛇。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly bt;sd;s;sd;sd"
      region.rooms[27].name = "广场"
      region.rooms[27].zone = "白驼山"
      region.rooms[27].id = 2028
      region.rooms[27].links = {}
        region.rooms[27].links.nu = {}
          region.rooms[27].links.nu.to = 2026
          region.rooms[27].links.nu.con = ""
        region.rooms[27].links.e = {}
          region.rooms[27].links.e.to = 2034
          region.rooms[27].links.e.con = ""
        region.rooms[27].links.nw = {}
          region.rooms[27].links.nw.to = 2029
          region.rooms[27].links.nw.con = ""
        region.rooms[27].links.se = {}
          region.rooms[27].links.se.to = 2035
          region.rooms[27].links.se.con = ""
      region.rooms[27].exits = "northwest|east|southeast|northup"
      region.rooms[27].desc = "    这里是一块不小的广场，上面堆着农家晒的谷物。北上是『白驼山庄』。东面有间小农舍，西边有块菜地，东南方是一座小桥。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly bt;sd;s;sd;sd;nw"
      region.rooms[28].name = "山路"
      region.rooms[28].zone = "白驼山"
      region.rooms[28].id = 2029
      region.rooms[28].links = {}
        region.rooms[28].links.nw = {}
          region.rooms[28].links.nw.to = 2030
          region.rooms[28].links.nw.con = ""
        region.rooms[28].links.se = {}
          region.rooms[28].links.se.to = 2028
          region.rooms[28].links.se.con = ""
      region.rooms[28].exits = "northwest|southeast"
      region.rooms[28].desc = "    这里是山上的泥路。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly bt;sd;s;sd;sd;nw;nw"
      region.rooms[29].name = "山路"
      region.rooms[29].zone = "白驼山"
      region.rooms[29].id = 2030
      region.rooms[29].links = {}
        region.rooms[29].links.n = {}
          region.rooms[29].links.n.to = 2031
          region.rooms[29].links.n.con = ""
        region.rooms[29].links.se = {}
          region.rooms[29].links.se.to = 2029
          region.rooms[29].links.se.con = ""
      region.rooms[29].exits = "north|southeast"
      region.rooms[29].desc = "    这里是山上的泥路。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly bt;sd;s;sd;sd;nw;nw;n"
      region.rooms[30].name = "树林"
      region.rooms[30].zone = "白驼山"
      region.rooms[30].id = 2031
      region.rooms[30].links = {}
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 2030
          region.rooms[30].links.s.con = ""
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 2032
          region.rooms[30].links.w.con = ""
      region.rooms[30].exits = "south|west"
      region.rooms[30].desc = "    这里是一片茂密的树林(wood)。旁边立着一张木牌(pai)。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly bt;sd;s;sd;sd;nw;nw;n;w"
      region.rooms[31].name = "树林"
      region.rooms[31].zone = "白驼山"
      region.rooms[31].id = 2032
      region.rooms[31].links = {}
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 2031
          region.rooms[31].links.e.con = ""
        region.rooms[31].links.sw = {}
          region.rooms[31].links.sw.to = 2033
          region.rooms[31].links.sw.con = ""
      region.rooms[31].exits = "east|southwest"
      region.rooms[31].desc = "    这里是一片茂密的树林(wood)。旁边立着一张木牌(pai)。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly bt;sd;s;sd;sd;nw;nw;n;w;sw"
      region.rooms[32].name = "草莓地"
      region.rooms[32].zone = "白驼山"
      region.rooms[32].id = 2033
      region.rooms[32].links = {}
        region.rooms[32].links.ne = {}
          region.rooms[32].links.ne.to = 2032
          region.rooms[32].links.ne.con = ""
      region.rooms[32].exits = "northeast"
      region.rooms[32].desc = "    这里是一块草莓地，鲜红的草莓散落在绿草中，让人感到美妙惬意。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly bt;sd;s;sd;sd;e"
      region.rooms[33].name = "农舍"
      region.rooms[33].zone = "白驼山"
      region.rooms[33].id = 2034
      region.rooms[33].links = {}
        region.rooms[33].links.w = {}
          region.rooms[33].links.w.to = 2028
          region.rooms[33].links.w.con = ""
      region.rooms[33].exits = "west"
      region.rooms[33].desc = "    这里是一间小农舍，家具很新。看来主人比较富裕。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly bt;sd;s;sd;sd;se"
      region.rooms[34].name = "小桥"
      region.rooms[34].zone = "白驼山"
      region.rooms[34].id = 2035
      region.rooms[34].links = {}
        region.rooms[34].links.nw = {}
          region.rooms[34].links.nw.to = 2028
          region.rooms[34].links.nw.con = ""
        region.rooms[34].links.e = {}
          region.rooms[34].links.e.to = 2036
          region.rooms[34].links.e.con = ""
      region.rooms[34].exits = "east|northwest"
      region.rooms[34].desc = "    这是一座小竹桥，『白驼山』上的冰雪融化形成一条清澈的小溪，从桥下缓缓流过。不时有顽皮的小鱼跃出水面，在阳光下划出一条银白色的弧线。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly bt;sd;s;sd;sd;se;e"
      region.rooms[35].name = "西街"
      region.rooms[35].zone = "白驼山"
      region.rooms[35].id = 2036
      region.rooms[35].links = {}
        region.rooms[35].links.e = {}
          region.rooms[35].links.e.to = 2038
          region.rooms[35].links.e.con = ""
        region.rooms[35].links.w = {}
          region.rooms[35].links.w.to = 2035
          region.rooms[35].links.w.con = ""
        region.rooms[35].links.n = {}
          region.rooms[35].links.n.to = 2037
          region.rooms[35].links.n.con = ""
      region.rooms[35].exits = "north|east|west"
      region.rooms[35].desc = "    这里是小镇的西街。北边有个酒店，门前树立着高高的旗杆，一块青布幌子迎风飘扬，上面印着朱红色的大字‘酒’。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly bt;sd;s;sd;sd;se;e;n"
      region.rooms[36].name = "酒店"
      region.rooms[36].zone = "白驼山"
      region.rooms[36].id = 2037
      region.rooms[36].links = {}
        region.rooms[36].links.s = {}
          region.rooms[36].links.s.to = 2036
          region.rooms[36].links.s.con = ""
      region.rooms[36].exits = "south"
      region.rooms[36].desc = "    这里是一家独具特色的酒店，由于地处『白驼山』下，酒店可以供应风味食品－－蛇肉。许多中原来客都爱来尝尝鲜，所以酒店生意兴隆。酒店还经营打散装酒的业务。"
    region.rooms[37] = {}
      region.rooms[37].path = "fly bt;sd;s;sd;sd;se;e;e"
      region.rooms[37].name = "东街"
      region.rooms[37].zone = "白驼山"
      region.rooms[37].id = 2038
      region.rooms[37].links = {}
        region.rooms[37].links.ne = {}
          region.rooms[37].links.ne.to = 2040
          region.rooms[37].links.ne.con = ""
        region.rooms[37].links.w = {}
          region.rooms[37].links.w.to = 2036
          region.rooms[37].links.w.con = ""
        region.rooms[37].links.s = {}
          region.rooms[37].links.s.to = 2039
          region.rooms[37].links.s.con = ""
        region.rooms[37].links.se = {}
          region.rooms[37].links.se.to = 2049
          region.rooms[37].links.se.con = ""
      region.rooms[37].exits = "south|southeast|northeast|west"
      region.rooms[37].desc = "    这里是小镇的东街。南边有个打铁铺，里面传来丁丁当当的声音。东南方是荒凉的戈壁，东北方有条小路可上山。"
    region.rooms[38] = {}
      region.rooms[38].path = "fly bt;sd;s;sd;sd;se;e;e;s"
      region.rooms[38].name = "打铁铺"
      region.rooms[38].zone = "白驼山"
      region.rooms[38].id = 2039
      region.rooms[38].links = {}
        region.rooms[38].links.n = {}
          region.rooms[38].links.n.to = 2038
          region.rooms[38].links.n.con = ""
      region.rooms[38].exits = "north"
      region.rooms[38].desc = "    这里是一家打铁铺，铁匠忙着打制铁制兵器，卖给江湖侠客。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly bt;sd;s;sd;sd;se;e;e;ne"
      region.rooms[39].name = "小路"
      region.rooms[39].zone = "白驼山"
      region.rooms[39].id = 2040
      region.rooms[39].links = {}
        region.rooms[39].links.nu = {}
          region.rooms[39].links.nu.to = 2041
          region.rooms[39].links.nu.con = ""
        region.rooms[39].links.sw = {}
          region.rooms[39].links.sw.to = 2038
          region.rooms[39].links.sw.con = ""
        region.rooms[39].links.ne = {}
          region.rooms[39].links.ne.to = 2047
          region.rooms[39].links.ne.con = ""
      region.rooms[39].exits = "northup|northeast|southwest"
      region.rooms[39].desc = "    这里是一条上山的小路。"
    region.rooms[40] = {}
      region.rooms[40].path = "fly bt;sd;s;sd;sd;se;e;e;ne;nu"
      region.rooms[40].name = "小路"
      region.rooms[40].zone = "白驼山"
      region.rooms[40].id = 2041
      region.rooms[40].links = {}
        region.rooms[40].links.sd = {}
          region.rooms[40].links.sd.to = 2040
          region.rooms[40].links.sd.con = ""
        region.rooms[40].links.nu = {}
          region.rooms[40].links.nu.to = 2042
          region.rooms[40].links.nu.con = ""
      region.rooms[40].exits = "northup|southdown"
      region.rooms[40].desc = "    这里是一条上山的小路。"
    region.rooms[41] = {}
      region.rooms[41].path = "fly bt;sd;s;sd;sd;se;e;e;ne;nu;nu"
      region.rooms[41].name = "小路"
      region.rooms[41].zone = "白驼山"
      region.rooms[41].id = 2042
      region.rooms[41].links = {}
        region.rooms[41].links.sd = {}
          region.rooms[41].links.sd.to = 2041
          region.rooms[41].links.sd.con = ""
        region.rooms[41].links.ne = {}
          region.rooms[41].links.ne.to = 2043
          region.rooms[41].links.ne.con = ""
      region.rooms[41].exits = "southdown|northeast"
      region.rooms[41].desc = "    这里是一条上山的小路。东北方有山贼出没，要格外小心。"
    region.rooms[42] = {}
      region.rooms[42].path = "fly bt;sd;s;sd;sd;se;e;e;ne;nu;nu;ne"
      region.rooms[42].name = "小路"
      region.rooms[42].zone = "白驼山"
      region.rooms[42].id = 2043
      region.rooms[42].links = {}
        region.rooms[42].links.n = {}
          region.rooms[42].links.n.to = 2044
          region.rooms[42].links.n.con = ""
        region.rooms[42].links.sw = {}
          region.rooms[42].links.sw.to = 2042
          region.rooms[42].links.sw.con = ""
      region.rooms[42].exits = "north|southwest"
      region.rooms[42].desc = "    这里是一条上山的小路向西分出一条岔道。北边是山贼的老窝。"
    region.rooms[43] = {}
      region.rooms[43].path = "fly bt;sd;s;sd;sd;se;e;e;ne;nu;nu;ne;n"
      region.rooms[43].name = "洞口"
      region.rooms[43].zone = "白驼山"
      region.rooms[43].id = 2044
      region.rooms[43].links = {}
        region.rooms[43].links.s = {}
          region.rooms[43].links.s.to = 2043
          region.rooms[43].links.s.con = ""
        region.rooms[43].links.n = {}
          region.rooms[43].links.n.to = 2045
          region.rooms[43].links.n.con = ""
      region.rooms[43].exits = "south|north"
      region.rooms[43].desc = "    这里是山贼的老窝的洞口，守备森严。"
    region.rooms[44] = {}
      region.rooms[44].path = "fly bt;sd;s;sd;sd;se;e;e;ne;nu;nu;ne;n;n"
      region.rooms[44].name = "洞内"
      region.rooms[44].zone = "白驼山"
      region.rooms[44].id = 2045
      region.rooms[44].links = {}
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 2044
          region.rooms[44].links.s.con = ""
        region.rooms[44].links.w = {}
          region.rooms[44].links.w.to = 2046
          region.rooms[44].links.w.con = "k1:山贼头"
      region.rooms[44].exits = "south|west"
      region.rooms[44].desc = "    这里是山贼的老窝的所在。旁边有一侧洞，里面隐隐传来女子的哭声。"
    region.rooms[45] = {}
      region.rooms[45].path = "fly bt;sd;s;sd;sd;se;e;e;ne;nu;nu;ne;n;n;|!k1:山贼头:w|"
      region.rooms[45].name = "侧洞"
      region.rooms[45].zone = "白驼山"
      region.rooms[45].id = 2046
      region.rooms[45].links = {}
        region.rooms[45].links.e = {}
          region.rooms[45].links.e.to = 2045
          region.rooms[45].links.e.con = ""
      region.rooms[45].exits = "east"
      region.rooms[45].desc = "    这里是一个小小的侧洞，里面有张梳妆台，上边摆放着一些女人的用品。"
    region.rooms[46] = {}
      region.rooms[46].path = "fly bt;sd;s;sd;sd;se;e;e;ne;ne"
      region.rooms[46].name = "坟地"
      region.rooms[46].zone = "白驼山"
      region.rooms[46].id = 2047
      region.rooms[46].links = {}
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 2048
          region.rooms[46].links.n.con = ""
        region.rooms[46].links.sw = {}
          region.rooms[46].links.sw.to = 2040
          region.rooms[46].links.sw.con = ""
      region.rooms[46].exits = "north|southwest"
      region.rooms[46].desc = "    这里是荒凉阴森的荒坟地。"
    region.rooms[47] = {}
      region.rooms[47].path = "fly bt;sd;s;sd;sd;se;e;e;ne;ne;n"
      region.rooms[47].name = "墓门"
      region.rooms[47].zone = "白驼山"
      region.rooms[47].id = 2048
      region.rooms[47].links = {}
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 2047
          region.rooms[47].links.s.con = ""
      region.rooms[47].exits = "south"
      region.rooms[47].desc = "    这是个一座豪华墓地的墓门。大理石雕花的门梁，青石板的路面，修剪整齐的长青木，显得庄重肃穆。墓门边立着一块青白色石碑(bei)。"
    region.rooms[48] = {}
      region.rooms[48].path = "fly bt;sd;s;sd;sd;se;e;e;se"
      region.rooms[48].name = "戈壁"
      region.rooms[48].zone = "白驼山"
      region.rooms[48].id = 2049
      region.rooms[48].links = {}
        region.rooms[48].links.nw = {}
          region.rooms[48].links.nw.to = 2038
          region.rooms[48].links.nw.con = ""
      region.rooms[48].exits = "northwest|east"
      region.rooms[48].desc = "    这里是临近沙漠的戈壁滩，荒无人烟。东边是一望无际的大沙漠，西北方可以看见一座小镇。"
  region.center = 2002
return region