local region = {}
  region.cmd = "fly ca"
  region.name = "长安"
  region.id = "ca"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly ca;e;e;se;e;e;e"
      region.rooms[1].name = "函谷关"
      region.rooms[1].zone = "襄阳|长安"
      region.rooms[1].id = 715
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 116
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 716
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 834
          region.rooms[1].links.w.con = ""
      region.rooms[1].exits = "south|east|west"
      region.rooms[1].desc = "    这里就是古函古关。它东起崤山，西接潼津，关设谷中。当年强秦一隅之地，制关东六国而不敢稍动，最后横扫天下，就是因为它据此，进可攻，退可守，乃天下形胜之处。老子西出化胡，也是在此留下两册道德经，千载以下，后人仍研读不尽。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly ca;e;e;se;e;e"
      region.rooms[2].name = "大官道"
      region.rooms[2].zone = "长安"
      region.rooms[2].id = 834
      region.rooms[2].desc = "    这是一条宽阔笔直的官道，足可容得下十马并驰。往东通向函谷关，往西则直达长安城。北边有一条小路通往山里。"
      region.rooms[2].exits = "east|north|west"
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 715
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 835
          region.rooms[2].links.w.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly zns"
      region.rooms[3].name = "终南山口"
      region.rooms[3].zone = "长安"
      region.rooms[3].id = 835
      region.rooms[3].desc = "    终南山又称太乙山，距长安城八十多里，素有“锦秀巨屏拱长安”之说。据传老子曾在山中讲经。这条大官道穿越终南山口，两面秀峰入云，这里却没有一条路可以上山。西面是往长安的大道，东面前往中原。"
      region.rooms[3].exits = "east|west"
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 834
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 836
          region.rooms[3].links.w.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly ca;e;e;se"
      region.rooms[4].name = "大官道"
      region.rooms[4].zone = "长安|武功"
      region.rooms[4].id = 836
      region.rooms[4].desc = "    这是一条宽阔笔直的官道，足可容得下十马并驰。往东通向函谷关，往西北则直达长安城。"
      region.rooms[4].exits = "east|northwest|west"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 835
          region.rooms[4].links.e.con = ""
        region.rooms[4].links.nw = {}
          region.rooms[4].links.nw.to = 837
          region.rooms[4].links.nw.con = ""
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 854
          region.rooms[4].links.w.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly ca;e;e"
      region.rooms[5].name = "大官道"
      region.rooms[5].zone = "长安"
      region.rooms[5].id = 837
      region.rooms[5].desc = "    这是一条宽阔笔直的官道，足可容得下十马并驰。往东南通向函谷关，往西则直达长安城。"
      region.rooms[5].exits = "south|southeast|west"
      region.rooms[5].links = {}
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 852
          region.rooms[5].links.s.con = ""
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 838
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.se = {}
          region.rooms[5].links.se.to = 836
          region.rooms[5].links.se.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly ca;e"
      region.rooms[6].name = "长安城东门"
      region.rooms[6].zone = "长安"
      region.rooms[6].id = 838
      region.rooms[6].desc = "    这里是长安城的东门。西面就到了城中，远望人山人海，往来行人车流不绝。西面一条大路通向远方。城门下有一些执勤的兵士。时下虽已天下太平，但一干兵将还是英姿勃勃，警惕的盯着往来人士。"
      region.rooms[6].exits = "east|west"
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 837
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 839
          region.rooms[6].links.w.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly ca"
      region.rooms[7].name = "十字街头"
      region.rooms[7].zone = "长安"
      region.rooms[7].id = 839
      region.rooms[7].desc = "    这里便是长安城的中心，四条大街交汇于此。一座巍峨高大的钟楼耸立于前，很是有些气势。每到清晨，响亮的钟声便会伴着淡淡雾气传向长安城的大街小巷。路口车水马龙，来往人潮不断。"
      region.rooms[7].exits = "south|east|north|west"
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 838
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 840
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 841
          region.rooms[7].links.w.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 844
          region.rooms[7].links.n.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly ca;s"
      region.rooms[8].name = "相记钱庄"
      region.rooms[8].zone = "长安"
      region.rooms[8].id = 840
      region.rooms[8].desc = "    这是一家老字号的钱庄，相老板是山西人，这家钱庄从他的爷爷的爷爷的爷爷的爷爷那辈开始办起，一直传到他手里，声誉非常好，在全国各地都有分店。它发行的银票通行全国。钱庄的门口挂有一块牌子(paizi)。"
      region.rooms[8].exits = "north"
      region.rooms[8].links = {}
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 839
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly ca;w"
      region.rooms[9].name = "长安城西门"
      region.rooms[9].zone = "长安"
      region.rooms[9].id = 841
      region.rooms[9].desc = "    这里是长安城的西门。东面就到了城中，远望人山人海，往来行人车流不绝。西面一条大路通向远方。城门下有一些执勤的兵士。时下虽已天下太平，但一干兵将还是英姿勃勃，警惕的盯着往来人士。"
      region.rooms[9].exits = "east|west"
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 839
          region.rooms[9].links.e.con = ""
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 842
          region.rooms[9].links.w.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly ca;w;w"
      region.rooms[10].name = "大道"
      region.rooms[10].zone = "长安"
      region.rooms[10].id = 842
      region.rooms[10].desc = "    你走在一条青石大道上，尘土飞扬。东面是一座大城池，看城墙上旗帜飘扬，好象就是长安了。西面望去一片黄土和荒野。"
      region.rooms[10].exits = "east|west"
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 841
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 843
          region.rooms[10].links.w.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly ca;w;w;w"
      region.rooms[11].name = "大道"
      region.rooms[11].zone = "长安"
      region.rooms[11].id = 843
      region.rooms[11].desc = "    这是一条青石大道。东面隐约可以看到长安城的城墙。北面有座小山丘。"
      region.rooms[11].exits = "east|northup"
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 842
          region.rooms[11].links.e.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly ca;n"
      region.rooms[12].name = "长安乐坊"
      region.rooms[12].zone = "长安"
      region.rooms[12].id = 844
      region.rooms[12].desc = "    这里是长安城一家有名的娱乐场所。当夜幕降临后，这里就格外热闹。进进出出的客人有达官贵人，南来北往的商旅，浪迹天涯的游子，三五成群的兵士，有时也能看见一些作俗客打扮的僧人或道士。"
      region.rooms[12].exits = "south|up"
      region.rooms[12].links = {}
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 839
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.u = {}
          region.rooms[12].links.u.to = 845
          region.rooms[12].links.u.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly ca;n;u"
      region.rooms[13].name = "长安二楼"
      region.rooms[13].zone = "长安"
      region.rooms[13].id = 845
      region.rooms[13].desc = "    乐坊楼上显得格外热闹，走廊里人来人往，几间屋子里人声嘈杂，牌签骨骰钱币落盘的声音不绝。看样子，客人们赌得正欢呢。"
      region.rooms[13].exits = "up|down"
      region.rooms[13].links = {}
        region.rooms[13].links.u = {}
          region.rooms[13].links.u.to = 846
          region.rooms[13].links.u.con = ""
        region.rooms[13].links.d = {}
          region.rooms[13].links.d.to = 844
          region.rooms[13].links.d.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly ca;n;u;u"
      region.rooms[14].name = "乐府诗社"
      region.rooms[14].zone = "长安"
      region.rooms[14].id = 846
      region.rooms[14].desc = "    高楼之上，满城繁华尽收眼底。文人骚客都喜欢在这里品茶吟诗，谈古论今，你瞧，不知谁在茶桌上刚刚写好一首诗(poem)。里边柜台上新贴了张启事(qishi)，你不由得走过去看了几眼。"
      region.rooms[14].exits = "up|east|west|down"
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 847
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.d = {}
          region.rooms[14].links.d.to = 845
          region.rooms[14].links.d.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 848
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.u = {}
          region.rooms[14].links.u.to = 849
          region.rooms[14].links.u.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly ca;n;u;u;e"
      region.rooms[15].name = "拱猪房"
      region.rooms[15].zone = "长安"
      region.rooms[15].id = 847
      region.rooms[15].desc = "    屋中间摆着一张看起来相当结实的大方桌(table)，桌边围着四把靠背木椅。东面墙上有一块大牌子(paizi)，西面墙上有一块小牌子(score)。"
      region.rooms[15].exits = "west"
      region.rooms[15].links = {}
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 846
          region.rooms[15].links.w.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly ca;n;u;u;w"
      region.rooms[16].name = "骰子房"
      region.rooms[16].zone = "长安"
      region.rooms[16].id = 848
      region.rooms[16].desc = "    屋中间摆着一张看起来相当结实的大长条桌(table)，四周围了十几把靠背木椅。北面墙上有一块牌子(paizi)。"
      region.rooms[16].exits = "east"
      region.rooms[16].links = {}
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 846
          region.rooms[16].links.e.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly ca;n;u;u;u"
      region.rooms[17].name = "聚义厅"
      region.rooms[17].zone = "长安"
      region.rooms[17].id = 849
      region.rooms[17].desc = "    这是一间宽敞明亮的大厅，厅的正中间是一根圆形的柱子。柱子上贴满了各种广告：有换房的，有卖家具的，但其中最多的还是找打牌搭档的广告。厅的东南西北各有个门，里面传出“拱啊！”“毙了！”等的叫声。"
      region.rooms[17].exits = "south|north|down"
      region.rooms[17].links = {}
        region.rooms[17].links.d = {}
          region.rooms[17].links.d.to = 846
          region.rooms[17].links.d.con = ""
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 850
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 851
          region.rooms[17].links.n.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly ca;n;u;u;u;s"
      region.rooms[18].name = "入神坐照室"
      region.rooms[18].zone = "长安"
      region.rooms[18].id = 850
      region.rooms[18].desc = "        只见好大一间房中，除了一张石桌、两只石凳之外，空荡荡的一无所有，石桌上刻着纵横十九道棋路，对放着一盒黑子、一盒白子。这棋室中除了几椅棋子之外不设一物，当是免得对局者分心。墙上贴了一张小帖子(tie)。"
      region.rooms[18].exits = "north"
      region.rooms[18].links = {}
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 849
          region.rooms[18].links.n.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly ca;n;u;u;u;n"
      region.rooms[19].name = "拱猪房"
      region.rooms[19].zone = "长安"
      region.rooms[19].id = 851
      region.rooms[19].desc = "    这间房子是专门为了拱猪用而设的，整间屋子都是用不去皮的松树搭成。一张石桌 (table)周围摆着四个石礅，桌面镶了一块大理石，摸上去极为光滑。四壁挂着长明灯，把屋子照得有如白昼。墙角里烧了一炉不知名的香，似乎颇有提神之效。香炉旁边挂着张告示(gaoshi)，上面写着这里的规矩；桌上有张小纸条(note)，上面草草的记着拱猪成绩。"
      region.rooms[19].exits = "south"
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 849
          region.rooms[19].links.s.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly ca;e;e;s"
      region.rooms[20].name = "骊山脚下"
      region.rooms[20].zone = "长安"
      region.rooms[20].id = 852
      region.rooms[20].desc = "    这里是骊山脚下，传说秦始皇陵就埋于此处。"
      region.rooms[20].exits = "north|southup"
      region.rooms[20].links = {}
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 837
          region.rooms[20].links.n.con = ""
        region.rooms[20].links.su = {}
          region.rooms[20].links.su.to = 853
          region.rooms[20].links.su.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly ca;e;e;s;su"
      region.rooms[21].name = "骊山"
      region.rooms[21].zone = "长安"
      region.rooms[21].id = 853
      region.rooms[21].desc = "    骊山位于长安城南，由东西秀玲组成，山势逶迤，树木葱茏，远望宛如一匹苍黛色的骏马而得名。骊山也因景色翠秀，美如锦绣，故又名“绣岭”。每当夕阳西下，骊山辉映在金色的晚霞之中，景色格外绮丽，有“骊山晚照”之美誉。"
      region.rooms[21].exits = "northdown"
      region.rooms[21].links = {}
        region.rooms[21].links.nd = {}
          region.rooms[21].links.nd.to = 852
          region.rooms[21].links.nd.con = ""
  region.center = 839
return region