local region = {}
  region.cmd = "fly em"
  region.name = "峨眉山"
  region.id = "em"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;e;nd"
      region.rooms[1].name = "青石阶"
      region.rooms[1].zone = "大理|峨眉山"
      region.rooms[1].id = 643
      region.rooms[1].desc = "    已经是峨嵋山脚下了。南面一条通往峨嵋的青石阶，两旁绿树荫蔽，空气十分清新。西南方通向南诏的大理国。西边好象有人搭了个小草棚。"
      region.rooms[1].exits = "southup|northeast|west|southwest"
      region.rooms[1].links = {}
        region.rooms[1].links.ne = {}
          region.rooms[1].links.ne.to = 664
          region.rooms[1].links.ne.con = ""
        region.rooms[1].links.sw = {}
          region.rooms[1].links.sw.to = 642
          region.rooms[1].links.sw.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 1654
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.su = {}
          region.rooms[1].links.su.to = 1656
          region.rooms[1].links.su.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;e;nd;ne"
      region.rooms[2].name = "青石阶"
      region.rooms[2].zone = "成都|峨眉山"
      region.rooms[2].id = 664
      region.rooms[2].links = {}
        region.rooms[2].links.sw = {}
          region.rooms[2].links.sw.to = 643
          region.rooms[2].links.sw.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 665
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 1737
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "north|west|southwest"
      region.rooms[2].desc = "    快到峨嵋山了。这是一条通往峨嵋山的青石阶，两旁绿树荫蔽，空气十分清新。时常能见到些游人香客。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;e;nd;w"
      region.rooms[3].name = "草棚"
      region.rooms[3].zone = "峨眉山"
      region.rooms[3].id = 1654
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 643
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 1655
          region.rooms[3].links.w.con = ""
      region.rooms[3].exits = "east|west"
      region.rooms[3].desc = "    这是峨嵋山脚下一个简单的草棚，地上堆著些上货。很多上山的游客都在这里买些上山用品。草棚后有个口井，西面是一间马厩。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;e;nd;w;w"
      region.rooms[4].name = "马厩"
      region.rooms[4].zone = "峨眉山"
      region.rooms[4].id = 1655
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 1654
          region.rooms[4].links.e.con = ""
      region.rooms[4].exits = "east"
      region.rooms[4].desc = "    这是草棚边的马厩，常年供应新鲜草料。据说此地民风淳朴，马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净，一直伺候到客人上路。马厩中堆放著几堆草料，正中有一口泔槽。    马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;e"
      region.rooms[5].name = "报国寺山门"
      region.rooms[5].zone = "峨眉山"
      region.rooms[5].id = 1656
      region.rooms[5].links = {}
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 1657
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.nd = {}
          region.rooms[5].links.nd.to = 643
          region.rooms[5].links.nd.con = ""
      region.rooms[5].exits = "northdown|west"
      region.rooms[5].desc = "    报国寺为峨嵋出入之门户。山门(gate)上有一块大匾。寺外苍楠环卫，翠柏掩映。由此一路向西上开始登峨嵋山，北面下山是一条弯弯的石阶路。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne"
      region.rooms[6].name = "报国寺"
      region.rooms[6].zone = "峨眉山"
      region.rooms[6].id = 1657
      region.rooms[6].links = {}
        region.rooms[6].links.enter = {}
          region.rooms[6].links.enter.to = 1658
          region.rooms[6].links.enter.con = ""
        region.rooms[6].links.sw = {}
          region.rooms[6].links.sw.to = 1661
          region.rooms[6].links.sw.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 1660
          region.rooms[6].links.w.con = ""
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 1656
          region.rooms[6].links.e.con = ""
      region.rooms[6].exits = "east|enter|west|southwest"
      region.rooms[6].desc = "    报国寺是峨眉山最大寺院之一。寺庙倚山建造，弥勒殿、大雄殿、七佛殿逐级升高，规模宏大。殿内佛像金光闪闪，气宇轩昂。寺内芳草迷径，花开不绝。这里有一座华严塔(ta)。这里向西，约二里可达伏虎寺。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;enter"
      region.rooms[7].name = "大雄殿"
      region.rooms[7].zone = "峨眉山"
      region.rooms[7].id = 1658
      region.rooms[7].links = {}
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 1659
          region.rooms[7].links.n.con = ""
        region.rooms[7].links.out = {}
          region.rooms[7].links.out.to = 1657
          region.rooms[7].links.out.con = ""
      region.rooms[7].exits = "north|out|west"
      region.rooms[7].desc = "    这里是报国寺大雄殿。报国寺是峨嵋山最大寺院之一。大雄殿内供着金光灿灿的佛像，气宇轩昂。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;enter;n"
      region.rooms[8].name = "藏经楼"
      region.rooms[8].zone = "峨眉山"
      region.rooms[8].id = 1659
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 1658
          region.rooms[8].links.s.con = ""
      region.rooms[8].exits = "south"
      region.rooms[8].desc = "    这里是报国寺的藏经楼。阁楼上密密麻麻排了好多书架，架上摆满了经书。有两个身穿白衣的小师太正在一角静静地读着经书。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;w"
      region.rooms[9].name = "报国寺西墙"
      region.rooms[9].zone = "峨眉山"
      region.rooms[9].id = 1660
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 1657
          region.rooms[9].links.e.con = ""
      region.rooms[9].exits = "east"
      region.rooms[9].desc = "    这里是峨眉山报国寺的西墙。寺院里的钟声从墙那边飘来，在空气中回响。一条山溪从西面山上的解脱桥下流经这里，向山下淌去。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e"
      region.rooms[10].name = "密林"
      region.rooms[10].zone = "峨眉山"
      region.rooms[10].id = 1661
      region.rooms[10].links = {}
        region.rooms[10].links.ne = {}
          region.rooms[10].links.ne.to = 1657
          region.rooms[10].links.ne.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 1662
          region.rooms[10].links.w.con = ""
      region.rooms[10].exits = "northeast|west"
      region.rooms[10].desc = "    这是黑森森的一片密林，楠木参天，浓阴蔽日。这里东下二里是报国寺，西边林间隐藏着一座庙宇。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed"
      region.rooms[11].name = "伏虎寺"
      region.rooms[11].zone = "峨眉山"
      region.rooms[11].id = 1662
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 1661
          region.rooms[11].links.e.con = ""
        region.rooms[11].links.wu = {}
          region.rooms[11].links.wu.to = 1663
          region.rooms[11].links.wu.con = ""
      region.rooms[11].exits = "westup|east"
      region.rooms[11].desc = "    伏虎寺是入山第一大宝刹，隐伏在高大的乔木林间，四周楠木参天，多达十万余株。伏虎寺气象庄严，规模宏盛，殿堂宽敞，势度巍峨。寺刹虽掩覆于翠绿浓黛之中，但屋瓦却无一片落叶。出寺西上解脱坡便是观音堂。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed"
      region.rooms[12].name = "密林"
      region.rooms[12].zone = "峨眉山"
      region.rooms[12].id = 1663
      region.rooms[12].links = {}
        region.rooms[12].links.ed = {}
          region.rooms[12].links.ed.to = 1662
          region.rooms[12].links.ed.con = ""
        region.rooms[12].links.wu = {}
          region.rooms[12].links.wu.to = 1664
          region.rooms[12].links.wu.con = ""
      region.rooms[12].exits = "westup|eastdown"
      region.rooms[12].desc = "    这是黑森森的一片密林，楠木参天，浓阴蔽日。这里西上是报国寺，东边林间隐藏着一座庙宇。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed"
      region.rooms[13].name = "解脱坡"
      region.rooms[13].zone = "峨眉山"
      region.rooms[13].id = 1664
      region.rooms[13].links = {}
        region.rooms[13].links.ed = {}
          region.rooms[13].links.ed.to = 1663
          region.rooms[13].links.ed.con = ""
        region.rooms[13].links.wu = {}
          region.rooms[13].links.wu.to = 1665
          region.rooms[13].links.wu.con = ""
      region.rooms[13].exits = "westup|eastdown"
      region.rooms[13].desc = "    这里是峨嵋胜地解脱坡。坡下一座小桥，叫解脱桥。行人至此，坐桥上听泉声甚美。当此良辰美景，心无芥蒂，心即解脱。坡上一座庵堂，东下一片密林。桥下山溪向东流淌到报国寺的西面。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed"
      region.rooms[14].name = "观音堂"
      region.rooms[14].zone = "峨眉山"
      region.rooms[14].id = 1665
      region.rooms[14].links = {}
        region.rooms[14].links.ed = {}
          region.rooms[14].links.ed.to = 1664
          region.rooms[14].links.ed.con = ""
        region.rooms[14].links.wu = {}
          region.rooms[14].links.wu.to = 1666
          region.rooms[14].links.wu.con = ""
      region.rooms[14].exits = "westup|eastdown"
      region.rooms[14].desc = "    观音堂高踞坡岗，近临危崖，环境幽静，四周树木蓊郁，悦目赏心。传说入山于此，解脱尘凡；出山于此，解脱险阻，又故名解脱庵。进山的人在此焚香洗心，入山方可化险为夷，步步平安。这里东下可达伏虎寺，西上行约二里可到归云阁。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed"
      region.rooms[15].name = "归云阁"
      region.rooms[15].zone = "峨眉山"
      region.rooms[15].id = 1666
      region.rooms[15].links = {}
        region.rooms[15].links.ed = {}
          region.rooms[15].links.ed.to = 1665
          region.rooms[15].links.ed.con = ""
        region.rooms[15].links.wu = {}
          region.rooms[15].links.wu.to = 1668
          region.rooms[15].links.wu.con = ""
        region.rooms[15].links.su = {}
          region.rooms[15].links.su.to = 1667
          region.rooms[15].links.su.con = ""
      region.rooms[15].exits = "westup|eastdown|southup"
      region.rooms[15].desc = "    归云阁，原是唐代福昌达道禅师的道场。宋代绍兴年间，僧人士性又率众重建。归云阁左有玉女峰，西上可抵纯阳殿，东下是观音堂。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;su"
      region.rooms[16].name = "玉女峰"
      region.rooms[16].zone = "峨眉山"
      region.rooms[16].id = 1667
      region.rooms[16].links = {}
        region.rooms[16].links.nd = {}
          region.rooms[16].links.nd.to = 1666
          region.rooms[16].links.nd.con = ""
      region.rooms[16].exits = "northdown"
      region.rooms[16].desc = "    这是归云阁边的玉女峰，峰顶有一个四尺见方的小池，深亦四尺，四季不枯，传为天女沐浴之器。古时州刺史冯楫，曾在此结茅而居，发奋诵读《华严经》，不食人间烟火，于是玉女下凡，为他馈赠食物。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed"
      region.rooms[17].name = "纯阳殿"
      region.rooms[17].zone = "峨眉山"
      region.rooms[17].id = 1668
      region.rooms[17].links = {}
        region.rooms[17].links.ed = {}
          region.rooms[17].links.ed.to = 1666
          region.rooms[17].links.ed.con = ""
        region.rooms[17].links.wu = {}
          region.rooms[17].links.wu.to = 1669
          region.rooms[17].links.wu.con = ""
      region.rooms[17].exits = "westup|eastdown"
      region.rooms[17].desc = "    纯阳殿海拔一千余米，四面古木苍翠，幽静宜人。殿前有一石，叫普贤石，据说普贤菩萨登山时曾坐在这里休息过。在此可纵观峨嵋诸峰，仰望金顶，悬崖峭壁，离天咫尺。这里西上至神水庵，东下是归云阁。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed"
      region.rooms[18].name = "神水庵"
      region.rooms[18].zone = "峨眉山"
      region.rooms[18].id = 1669
      region.rooms[18].links = {}
        region.rooms[18].links.ed = {}
          region.rooms[18].links.ed.to = 1668
          region.rooms[18].links.ed.con = ""
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 1670
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.wu = {}
          region.rooms[18].links.wu.to = 1674
          region.rooms[18].links.wu.con = ""
      region.rooms[18].exits = "south|westup|eastdown"
      region.rooms[18].desc = "    神水庵位于宝掌峰下，庵前有大峨石和玉液泉，泉出石下，清澈无比，终年不涸。一株大海棠树，已是数百苍龄，抱可数围，高达十余丈。旁边有福寿庵；由此西上中峰寺，东下纯阳殿。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;s"
      region.rooms[19].name = "福寿庵"
      region.rooms[19].zone = "峨眉山"
      region.rooms[19].id = 1670
      region.rooms[19].links = {}
        region.rooms[19].links.enter = {}
          region.rooms[19].links.enter.to = 1671
          region.rooms[19].links.enter.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 1669
          region.rooms[19].links.n.con = ""
      region.rooms[19].exits = "north|enter"
      region.rooms[19].desc = "    福寿庵在神水庵南，是一个名叫天性的僧人建造的。庵前有九曲渠、流杯池，古人曾据在此饮酒流杯，观景赋诗，歌咏兴叹，不知夕日。庵旁有株大海棠树，数百苍龄，高达十余丈。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;s;enter"
      region.rooms[20].name = "灵文阁"
      region.rooms[20].zone = "峨眉山"
      region.rooms[20].id = 1671
      region.rooms[20].links = {}
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 1672
          region.rooms[20].links.e.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 1673
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.out = {}
          region.rooms[20].links.out.to = 1670
          region.rooms[20].links.out.con = ""
      region.rooms[20].exits = "east|west|out"
      region.rooms[20].desc = "    这里是福寿庵的灵文阁，是主持静照师太传授佛法的地方。两名青衣小尼随侍在旁，似乎在聆听师太的教晦。阁内布置简陋，靠墙放着几把竹椅，地上放着几个蒲团。东首有一禅房。西面是一个斋厅。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;s;enter;e"
      region.rooms[21].name = "禅房"
      region.rooms[21].zone = "峨眉山"
      region.rooms[21].id = 1672
      region.rooms[21].links = {}
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 1671
          region.rooms[21].links.w.con = ""
      region.rooms[21].exits = "west"
      region.rooms[21].desc = "    这里是一间安静宽敞的禅房，乃是福寿庵中弟子打坐修行之所。地下整整齐齐地放着许多蒲团。几位年轻师太和俗家女弟子正肃容入定。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;s;enter;w"
      region.rooms[22].name = "福寿庵斋堂"
      region.rooms[22].zone = "峨眉山"
      region.rooms[22].id = 1673
      region.rooms[22].links = {}
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 1671
          region.rooms[22].links.e.con = ""
      region.rooms[22].exits = "east"
      region.rooms[22].desc = "    这里便是峨嵋福寿庵的斋堂。福寿庵本不大，但由于经常接待其他庵的弟子，斋堂倒也不小。只见厅内摆满了长长的餐桌和长凳，几位小师太正来回忙碌着布置素斋。桌上摆了几盆豆腐，花生，青菜以及素鸭等美味素食。北面有一扇门(door)。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se"
      region.rooms[23].name = "中峰寺"
      region.rooms[23].zone = "峨眉山"
      region.rooms[23].id = 1674
      region.rooms[23].links = {}
        region.rooms[23].links.ed = {}
          region.rooms[23].links.ed.to = 1669
          region.rooms[23].links.ed.con = ""
        region.rooms[23].links.nw = {}
          region.rooms[23].links.nw.to = 1675
          region.rooms[23].links.nw.con = ""
      region.rooms[23].exits = "northwest|eastdown"
      region.rooms[23].desc = "    中峰寺在白云峰下，始建于晋代，原为道观。传说观内的道人每年在三月三日都献身给山中一条大蟒，以为可以升仙。后来有个从资州来的明果禅师，杀了那条大蟒，道士们始知上当，感激不已，自愿改信佛教，从此改观为寺。这里往北可到清音阁，东下至神水庵。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly em;ed;d;ne;ed;ne;ed;sd;se"
      region.rooms[24].name = "清音阁"
      region.rooms[24].zone = "峨眉山"
      region.rooms[24].id = 1675
      region.rooms[24].links = {}
        region.rooms[24].links.sw = {}
          region.rooms[24].links.sw.to = 1677
          region.rooms[24].links.sw.con = ""
        region.rooms[24].links.nw = {}
          region.rooms[24].links.nw.to = 1676
          region.rooms[24].links.nw.con = ""
        region.rooms[24].links.se = {}
          region.rooms[24].links.se.to = 1674
          region.rooms[24].links.se.con = ""
      region.rooms[24].exits = "northwest|southeast|southwest"
      region.rooms[24].desc = "    这里是峨嵋山的清音阁。此阁位于牛心岭下，东有白龙江，西有黑龙江，两江之水交汇于清音阁下。江上有拱桥两座，分夸黑龙白龙二江，这就是双飞桥。两江合流处，有一数米高的黑褐色巨石傲然挺立，形似牛心，名之为「牛心石」。桥边立有一石碑(shibei)。由此向西上，左行是黑龙江栈道，右路至白龙洞，东去中峰寺。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly em;ed;d;ne;ed;ne;ed;sd"
      region.rooms[25].name = "白龙洞"
      region.rooms[25].zone = "峨眉山"
      region.rooms[25].id = 1676
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 1698
          region.rooms[25].links.e.con = ""
        region.rooms[25].links.nu = {}
          region.rooms[25].links.nu.to = 1695
          region.rooms[25].links.nu.con = ""
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 1699
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.se = {}
          region.rooms[25].links.se.to = 1675
          region.rooms[25].links.se.con = ""
      region.rooms[25].exits = "east|southeast|northup|west"
      region.rooms[25].desc = "    白龙洞据说是《白蛇传》中的白娘子修炼成仙之处。这里楠木参天，林荫夹道，株株秀挺俊拔，枝叶分披上捧，如两手拥佛，传为古时一高僧按《法华经》口诵一字，植树一株，共植六万九千七百七十七株，时称古德林。这里北上至万年庵，南下是清音阁。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly em;se;ne;ed;ne;ed;ne;n;n"
      region.rooms[26].name = "黑龙江栈道"
      region.rooms[26].zone = "峨眉山"
      region.rooms[26].id = 1677
      region.rooms[26].links = {}
        region.rooms[26].links.ne = {}
          region.rooms[26].links.ne.to = 1675
          region.rooms[26].links.ne.con = ""
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 1678
          region.rooms[26].links.s.con = ""
      region.rooms[26].exits = "south|northeast"
      region.rooms[26].desc = "    黑龙江栈道沿黑龙江而建。这里一山中开，两崖并立，形成一道宽仅数尺，长达几百米的深峡──白云峡。黑龙江栈道就从狭窄的白云峡中转折穿过，架设在绝壁上。走在栈道上，只觉道窄人危；俯视深涧，急流飞旋，山静而觉动；仰观头顶，天光如隙，崖开而欲合。这就是天开画图的「一线天」。栈道南通千佛庵，北至清音阁。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly em;se;ne;ed;ne;ed;ne;n"
      region.rooms[27].name = "黑龙江栈道"
      region.rooms[27].zone = "峨眉山"
      region.rooms[27].id = 1678
      region.rooms[27].links = {}
        region.rooms[27].links.s = {}
          region.rooms[27].links.s.to = 1679
          region.rooms[27].links.s.con = ""
        region.rooms[27].links.n = {}
          region.rooms[27].links.n.to = 1677
          region.rooms[27].links.n.con = ""
      region.rooms[27].exits = "south|north"
      region.rooms[27].desc = "    黑龙江栈道沿黑龙江而建。这里一山中开，两崖并立，形成一道宽仅数尺，长达几百米的深峡──白云峡。黑龙江栈道就从狭窄的白云峡中转折穿过，架设在绝壁上。走在栈道上，只觉道窄人危；俯视深涧，急流飞旋，山静而觉动；仰观头顶，天光如隙，崖开而欲合。这就是天开画图的「一线天」。栈道南通千佛庵，北至清音阁。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly em;se;ne;ed;ne;ed;ne"
      region.rooms[28].name = "千佛庵"
      region.rooms[28].zone = "峨眉山"
      region.rooms[28].id = 1679
      region.rooms[28].links = {}
        region.rooms[28].links.enter = {}
          region.rooms[28].links.enter.to = 1680
          region.rooms[28].links.enter.con = ""
        region.rooms[28].links.sw = {}
          region.rooms[28].links.sw.to = 1682
          region.rooms[28].links.sw.con = ""
        region.rooms[28].links.n = {}
          region.rooms[28].links.n.to = 1678
          region.rooms[28].links.n.con = ""
      region.rooms[28].exits = "north|enter|southwest"
      region.rooms[28].desc = "    此处是洪椿坪千佛庵。山间小坪坝，四面层峦叠障，峰环岭护；两侧深谷幽岚，溪涧玲叮。坪上古木扶疏，亭亭如盖，山阴沁透，白雾飘游，极为幽静清凉。此处常见雨雾霏霏，林中迷迷蒙蒙，乃山中雾气所为。正所谓「山行本无雨，空翠湿人衣」。这就是誉为奇观的「洪椿晓雨」。此处殿美景幽，气象新异，令人心醉。沿途南上是「九十九道拐」，北下经黑龙江栈道至清音阁。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly em;se;ne;ed;ne;ed;ne;enter"
      region.rooms[29].name = "千佛庵大殿"
      region.rooms[29].zone = "峨眉山"
      region.rooms[29].id = 1680
      region.rooms[29].links = {}
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 1681
          region.rooms[29].links.e.con = ""
        region.rooms[29].links.out = {}
          region.rooms[29].links.out.to = 1679
          region.rooms[29].links.out.con = ""
      region.rooms[29].exits = "east|out"
      region.rooms[29].desc = "    千佛庵殿宇高广宏阔，清洁庄严。庵内有一具七万千佛莲灯，有纹龙七条环于灯体，并有佛像数百周匝排列，雕缕精致无比。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly em;se;ne;ed;ne;ed;ne;enter;e"
      region.rooms[30].name = "禅房"
      region.rooms[30].zone = "峨眉山"
      region.rooms[30].id = 1681
      region.rooms[30].links = {}
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 1680
          region.rooms[30].links.w.con = ""
      region.rooms[30].exits = "west"
      region.rooms[30].desc = "    这里是一间安静宽敞的禅房，乃是千佛庵中弟子打坐修行之所。地下整整齐齐放着许多蒲团。几位年轻师太和俗家女弟子正肃容入定。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly em;se;ne;ed;ne;ed"
      region.rooms[31].name = "九十九道拐"
      region.rooms[31].zone = "峨眉山"
      region.rooms[31].id = 1682
      region.rooms[31].links = {}
        region.rooms[31].links.ne = {}
          region.rooms[31].links.ne.to = 1679
          region.rooms[31].links.ne.con = ""
        region.rooms[31].links.wu = {}
          region.rooms[31].links.wu.to = 1683
          region.rooms[31].links.wu.con = ""
      region.rooms[31].exits = "westup|northeast"
      region.rooms[31].desc = "    这是著名的「九十九道拐」，道路纡曲陡竖，千折百回。据说过去曾有个百余岁的疯僧至此，见一巨蟒挡路，便念咒驱蟒。但人们得知此处有巨蟒出没后，便再也无人敢碰这里的草木，并以「龙居」名之。由此东可至千佛庵，西达九老洞。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly em;se;ne;ed;ne"
      region.rooms[32].name = "九十九道拐"
      region.rooms[32].zone = "峨眉山"
      region.rooms[32].id = 1683
      region.rooms[32].links = {}
        region.rooms[32].links.ed = {}
          region.rooms[32].links.ed.to = 1682
          region.rooms[32].links.ed.con = ""
        region.rooms[32].links.sw = {}
          region.rooms[32].links.sw.to = 1684
          region.rooms[32].links.sw.con = ""
      region.rooms[32].exits = "eastdown|southwest"
      region.rooms[32].desc = "    这是著名的「九十九道拐」，道路纡曲陡竖，千折百回。据说过去曾有个百余岁的疯僧至此，见一巨蟒挡路，便念咒驱蟒。但人们得知此处有巨蟒出没后，便再也无人敢碰这里的草木，并以「龙居」名之。由此东可至千佛庵，西达九老洞。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly em;se;ne;ed"
      region.rooms[33].name = "九十九道拐"
      region.rooms[33].zone = "峨眉山"
      region.rooms[33].id = 1684
      region.rooms[33].links = {}
        region.rooms[33].links.ne = {}
          region.rooms[33].links.ne.to = 1683
          region.rooms[33].links.ne.con = ""
        region.rooms[33].links.wu = {}
          region.rooms[33].links.wu.to = 1685
          region.rooms[33].links.wu.con = ""
      region.rooms[33].exits = "westup|northeast"
      region.rooms[33].desc = "    这是著名的「九十九道拐」，道路纡曲陡竖，千折百回。据说过去曾有个百余岁的疯僧至此，见一巨蟒挡路，便念咒驱蟒。但人们得知此处有巨蟒出没后，便再也无人敢碰这里的草木，并以「龙居」名之。由此东可至千佛庵，西达九老洞。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly em;se;ne"
      region.rooms[34].name = "九十九道拐"
      region.rooms[34].zone = "峨眉山"
      region.rooms[34].id = 1685
      region.rooms[34].links = {}
        region.rooms[34].links.ed = {}
          region.rooms[34].links.ed.to = 1684
          region.rooms[34].links.ed.con = ""
        region.rooms[34].links.sw = {}
          region.rooms[34].links.sw.to = 1686
          region.rooms[34].links.sw.con = ""
      region.rooms[34].exits = "eastdown|southwest"
      region.rooms[34].desc = "    这是著名的「九十九道拐」，道路纡曲陡竖，千折百回。据说过去曾有个百余岁的疯僧至此，见一巨蟒挡路，便念咒驱蟒。但人们得知此处有巨蟒出没后，便再也无人敢碰这里的草木，并以「龙居」名之。这路边被疯长的野草掩盖了一个小洞（dong）。由此东可至千佛庵，西达九老洞。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly em;se"
      region.rooms[35].name = "九老洞口"
      region.rooms[35].zone = "峨眉山"
      region.rooms[35].id = 1686
      region.rooms[35].links = {}
        region.rooms[35].links.enter = {}
          region.rooms[35].links.enter.to = 1687
          region.rooms[35].links.enter.con = ""
        region.rooms[35].links.nw = {}
          region.rooms[35].links.nw.to = 1688
          region.rooms[35].links.nw.con = ""
        region.rooms[35].links.ne = {}
          region.rooms[35].links.ne.to = 1685
          region.rooms[35].links.ne.con = ""
      region.rooms[35].exits = "northwest|enter|northeast"
      region.rooms[35].desc = "    九老洞在仙峰寺外。传说远古时候，有九位仙叟住在这个洞里，不知他们生于何年，终于何年。轩辕皇帝访道于此，见一老叟，问曰：『有侣乎？』答曰：『九人』。这就是九老洞的来历。这个洞很深，很少有人进去，只有些人站在洞口谈笑呼叫（yell）。这里向西经九十九道拐到千佛庵，一路向北到莲花石。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly em;se;enter"
      region.rooms[36].name = "九老洞"
      region.rooms[36].zone = "峨眉山"
      region.rooms[36].id = 1687
      region.rooms[36].desc = "    这就是峨嵋第一大洞，洞内深窈无比，神秘难测。你一走进来，便发觉洞中叉洞多如迷宫，怪异莫测，似乎黝黑无底。还是快快离开吧。"
      region.rooms[36].exits = "south|east|north|west|out"
      region.rooms[36].links = {}
        region.rooms[36].links.out = {}
          region.rooms[36].links.out.to = 1686
          region.rooms[36].links.out.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly em"
      region.rooms[37].name = "莲花石"
      region.rooms[37].zone = "峨眉山"
      region.rooms[37].id = 1688
      region.rooms[37].desc = "    这是莲花石。此处岩石纹理纵横，形似莲花，颜如芙蓉，仿佛萼瓣层叠，细蕊欲绽。上有一庵，叫「莲花社」。由此往西上直达洗象池，东下左通华严顶，右通九老洞。"
      region.rooms[37].exits = "westup|eastdown|southeast"
      region.rooms[37].links = {}
        region.rooms[37].links.ed = {}
          region.rooms[37].links.ed.to = 1689
          region.rooms[37].links.ed.con = ""
        region.rooms[37].links.se = {}
          region.rooms[37].links.se.to = 1686
          region.rooms[37].links.se.con = ""
        region.rooms[37].links.wu = {}
          region.rooms[37].links.wu.to = 1700
          region.rooms[37].links.wu.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly em;ed"
      region.rooms[38].name = "华严顶"
      region.rooms[38].zone = "峨眉山"
      region.rooms[38].id = 1689
      region.rooms[38].desc = "    华严顶挺拔高峭，古刹云深，殿宇孤耸，风景奇险。这里视野开阔，仰可见金顶巍巍，俯可望群峰罗列，许多蹲伏山间的寺院也在眼底。由此向西过数坡，即到莲花石，东下过十二盘可到万年寺。北面是一间马厩。"
      region.rooms[38].exits = "westup|north|down"
      region.rooms[38].links = {}
        region.rooms[38].links.d = {}
          region.rooms[38].links.d.to = 1691
          region.rooms[38].links.d.con = ""
        region.rooms[38].links.wu = {}
          region.rooms[38].links.wu.to = 1688
          region.rooms[38].links.wu.con = ""
        region.rooms[38].links.n = {}
          region.rooms[38].links.n.to = 1690
          region.rooms[38].links.n.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly em;ed;n"
      region.rooms[39].name = "马厩"
      region.rooms[39].zone = "峨眉山"
      region.rooms[39].id = 1690
      region.rooms[39].desc = "    这是草棚边的马厩，常年供应新鲜草料。据说此地民风淳朴，马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净，一直伺候到客人上路。马厩中堆放著几堆草料，正中有一口泔槽。    马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。"
      region.rooms[39].exits = "south"
      region.rooms[39].links = {}
        region.rooms[39].links.s = {}
          region.rooms[39].links.s.to = 1689
          region.rooms[39].links.s.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly em;ed;d"
      region.rooms[40].name = "十二盘"
      region.rooms[40].zone = "峨眉山"
      region.rooms[40].id = 1691
      region.rooms[40].desc = "    这里石阶陡折多弯，号称「十二盘」。由此西上可达华严顶，东下则到万年庵。"
      region.rooms[40].exits = "up|northeast"
      region.rooms[40].links = {}
        region.rooms[40].links.u = {}
          region.rooms[40].links.u.to = 1689
          region.rooms[40].links.u.con = ""
        region.rooms[40].links.ne = {}
          region.rooms[40].links.ne.to = 1692
          region.rooms[40].links.ne.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly em;ed;d;ne"
      region.rooms[41].name = "十二盘"
      region.rooms[41].zone = "峨眉山"
      region.rooms[41].id = 1692
      region.rooms[41].desc = "    这里石阶陡折多弯，号称「十二盘」。你见路边有个八音池，有人正在向池中击掌(clap)。由此西上可达华严顶，东下则到万年庵。"
      region.rooms[41].exits = "eastdown|southwest"
      region.rooms[41].links = {}
        region.rooms[41].links.ed = {}
          region.rooms[41].links.ed.to = 1693
          region.rooms[41].links.ed.con = ""
        region.rooms[41].links.sw = {}
          region.rooms[41].links.sw.to = 1691
          region.rooms[41].links.sw.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly em;ed;d;ne;ed"
      region.rooms[42].name = "十二盘"
      region.rooms[42].zone = "峨眉山"
      region.rooms[42].id = 1693
      region.rooms[42].desc = "    这里石阶陡折多弯，号称「十二盘」。由此西上可达华严顶，东下则到万年庵。"
      region.rooms[42].exits = "westup|northeast"
      region.rooms[42].links = {}
        region.rooms[42].links.ne = {}
          region.rooms[42].links.ne.to = 1694
          region.rooms[42].links.ne.con = ""
        region.rooms[42].links.wu = {}
          region.rooms[42].links.wu.to = 1692
          region.rooms[42].links.wu.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly em;ed;d;ne;ed;ne"
      region.rooms[43].name = "十二盘"
      region.rooms[43].zone = "峨眉山"
      region.rooms[43].id = 1694
      region.rooms[43].desc = "    这里石阶陡折多弯，号称「十二盘」。由此西上可达华严顶，东下则到万年庵。"
      region.rooms[43].exits = "eastdown|southwest"
      region.rooms[43].links = {}
        region.rooms[43].links.ed = {}
          region.rooms[43].links.ed.to = 1695
          region.rooms[43].links.ed.con = ""
        region.rooms[43].links.sw = {}
          region.rooms[43].links.sw.to = 1693
          region.rooms[43].links.sw.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly em;ed;d;ne;ed;ne;ed"
      region.rooms[44].name = "万年庵"
      region.rooms[44].zone = "峨眉山"
      region.rooms[44].id = 1695
      region.rooms[44].desc = "    万年庵建在一座突起的山峰上，周围古木森森，清泉淙淙，闲步无坎，吟游无坷，景色非常迷人。由此西上过十二盘可达华严顶，南下至白龙洞。"
      region.rooms[44].exits = "westup|enter|southdown"
      region.rooms[44].links = {}
        region.rooms[44].links.enter = {}
          region.rooms[44].links.enter.to = 1696
          region.rooms[44].links.enter.con = ""
        region.rooms[44].links.sd = {}
          region.rooms[44].links.sd.to = 1676
          region.rooms[44].links.sd.con = ""
        region.rooms[44].links.wu = {}
          region.rooms[44].links.wu.to = 1694
          region.rooms[44].links.wu.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly em;ed;d;ne;ed;ne;ed;enter"
      region.rooms[45].name = "万年庵砖殿"
      region.rooms[45].zone = "峨眉山"
      region.rooms[45].id = 1696
      region.rooms[45].desc = "    这里是万年庵的拱顶无梁砖殿。砖殿四壁为正方形，顶为穹窿圆拱形，殿内有普贤菩萨骑六牙白象的铜铸像一尊。拱顶无梁砖殿四壁下方，有小龛二十四个，内各供铁铸佛像一尊。四壁上方则有横龛六道，列置铜铸小佛三百零七个。"
      region.rooms[45].exits = "east|out"
      region.rooms[45].links = {}
        region.rooms[45].links.e = {}
          region.rooms[45].links.e.to = 1697
          region.rooms[45].links.e.con = ""
        region.rooms[45].links.out = {}
          region.rooms[45].links.out.to = 1695
          region.rooms[45].links.out.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly em;ed;d;ne;ed;ne;ed;enter;e"
      region.rooms[46].name = "禅房"
      region.rooms[46].zone = "峨眉山"
      region.rooms[46].id = 1697
      region.rooms[46].desc = "    这里是一间安静宽敞的禅房，乃是庵中弟子打坐修行之所。地下整整齐齐地放着许多蒲团。几位年轻师太和俗家女弟子正肃容入定。"
      region.rooms[46].exits = "west"
      region.rooms[46].links = {}
        region.rooms[46].links.w = {}
          region.rooms[46].links.w.to = 1696
          region.rooms[46].links.w.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly em;ed;d;ne;ed;ne;ed;sd;e"
      region.rooms[47].name = "古德林"
      region.rooms[47].zone = "峨眉山"
      region.rooms[47].id = 1698
      region.rooms[47].desc = "    这是一片密密的楠木林，株株秀挺俊拔，枝叶分披上捧，如两手拥佛，据说有七万株之多，要是不熟悉地形很容易迷路。林中有一片空地，几只楠木桩排成梅花模样。"
      region.rooms[47].exits = "south|northwest|southeast|northeast|southwest"
      region.rooms[47].links = {}
        region.rooms[47].links.ne = {}
          region.rooms[47].links.ne.to = 1699
          region.rooms[47].links.ne.con = ""
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 1676
          region.rooms[47].links.s.con = ""
        region.rooms[47].links.se = {}
          region.rooms[47].links.se.to = 1699
          region.rooms[47].links.se.con = ""
        region.rooms[47].links.sw = {}
          region.rooms[47].links.sw.to = 1699
          region.rooms[47].links.sw.con = ""
        region.rooms[47].links.nw = {}
          region.rooms[47].links.nw.to = 1699
          region.rooms[47].links.nw.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "fly em;ed;d;ne;ed;ne;ed;sd;w"
      region.rooms[48].name = "古德林"
      region.rooms[48].zone = "峨眉山"
      region.rooms[48].id = 1699
      region.rooms[48].desc = "    这是一片密密的楠木林，株株秀挺俊拔，枝叶分披上捧，如两手拥佛，据说有七万株之多，要是不熟悉地形很容易迷路。林中有一片空地，几只楠木桩排成梅花模样。"
      region.rooms[48].exits = "south|northwest|southeast|northeast|southwest"
      region.rooms[48].links = {}
        region.rooms[48].links.ne = {}
          region.rooms[48].links.ne.to = 1698
          region.rooms[48].links.ne.con = ""
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 1676
          region.rooms[48].links.s.con = ""
        region.rooms[48].links.se = {}
          region.rooms[48].links.se.to = 1698
          region.rooms[48].links.se.con = ""
        region.rooms[48].links.sw = {}
          region.rooms[48].links.sw.to = 1698
          region.rooms[48].links.sw.con = ""
        region.rooms[48].links.nw = {}
          region.rooms[48].links.nw.to = 1698
          region.rooms[48].links.nw.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly em;wu"
      region.rooms[49].name = "钻天坡"
      region.rooms[49].zone = "峨眉山"
      region.rooms[49].id = 1700
      region.rooms[49].desc = "    莲花石与洗象池之间，道路陡绝，石栈若齿，直上蓝天，石蹬达一千三百多级，是在陡峭山壁上开凿出来的坡道。人行其上，前后顶踵相接，一如登天。这段路叫「鹁鸽钻天」，这段陡坡也因此而叫「钻天坡」。这里西上坡顶便到洗象池，东下可达莲花石。"
      region.rooms[49].exits = "westup|eastdown"
      region.rooms[49].links = {}
        region.rooms[49].links.ed = {}
          region.rooms[49].links.ed.to = 1688
          region.rooms[49].links.ed.con = ""
        region.rooms[49].links.wu = {}
          region.rooms[49].links.wu.to = 1701
          region.rooms[49].links.wu.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly em;wu;wu"
      region.rooms[50].name = "钻天坡"
      region.rooms[50].zone = "峨眉山"
      region.rooms[50].id = 1701
      region.rooms[50].desc = "    莲花石与洗象池之间，道路陡绝，石栈若齿，直上蓝天，石蹬达一千三百多级，是在陡峭山壁上开凿出来的坡道。人行其上，前后顶踵相接，一如登天。这段路叫「鹁鸽钻天」，这段陡坡也因此而叫「钻天坡」。这里西上坡顶便到洗象池，东下可达莲花石。"
      region.rooms[50].exits = "westup|eastdown"
      region.rooms[50].links = {}
        region.rooms[50].links.ed = {}
          region.rooms[50].links.ed.to = 1700
          region.rooms[50].links.ed.con = ""
        region.rooms[50].links.wu = {}
          region.rooms[50].links.wu.to = 1702
          region.rooms[50].links.wu.con = ""
    region.rooms[51] = {}
      region.rooms[51].path = "fly em;wu;wu;wu"
      region.rooms[51].name = "洗象池"
      region.rooms[51].zone = "峨眉山"
      region.rooms[51].id = 1702
      region.rooms[51].desc = "    洗象池原只是一亭，亭前有一个石砌的小池(pool)，池边不远就是危岩。洗象池寓于一片冷杉林中，有若白云深处的仙山琼阁。若是云收雾敛、碧空万里、月朗中天时，便觉万籁俱寂，清光无限，宛若身在天宫，彻体生凉。这正是著名的「象池池夜」。由此向南上攀，便至雷洞坪，东下至莲花石。"
      region.rooms[51].exits = "eastdown|southup"
      region.rooms[51].links = {}
        region.rooms[51].links.ed = {}
          region.rooms[51].links.ed.to = 1701
          region.rooms[51].links.ed.con = ""
        region.rooms[51].links.su = {}
          region.rooms[51].links.su.to = 1703
          region.rooms[51].links.su.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "fly em;wu;wu;wu;su"
      region.rooms[52].name = "凌云梯"
      region.rooms[52].zone = "峨眉山"
      region.rooms[52].id = 1703
      region.rooms[52].desc = "    这是凌云梯，最早是一位叫阿婆多的外国和尚在此缚木架石，以渡行人，又叫「胡僧梯」。路边有梅子坡，可见满坡青梅如豆，于疏枝密叶中逗引行人，甚有「望梅止渴」之功用。此梯北通洗象池，南至雷洞坪。"
      region.rooms[52].exits = "southup|northdown"
      region.rooms[52].links = {}
        region.rooms[52].links.nd = {}
          region.rooms[52].links.nd.to = 1702
          region.rooms[52].links.nd.con = ""
        region.rooms[52].links.su = {}
          region.rooms[52].links.su.to = 1704
          region.rooms[52].links.su.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "fly em;wu;wu;wu;su;su"
      region.rooms[53].name = "雷洞坪"
      region.rooms[53].zone = "峨眉山"
      region.rooms[53].id = 1704
      region.rooms[53].desc = "    雷洞坪一带，道路艰险骇人，路左是蔽日遮天的冷杉林，路右是深不见底的绝壁峡谷。这里长年云遮雾罩，空蒙黑暗。岩上建有雷神殿，旁边竖一铁碑。由此往上是「八十四盘」至接引殿，北下到洗象池。"
      region.rooms[53].exits = "east|southup|northdown"
      region.rooms[53].links = {}
        region.rooms[53].links.e = {}
          region.rooms[53].links.e.to = 1706
          region.rooms[53].links.e.con = ""
        region.rooms[53].links.nd = {}
          region.rooms[53].links.nd.to = 1703
          region.rooms[53].links.nd.con = ""
        region.rooms[53].links.su = {}
          region.rooms[53].links.su.to = 1705
          region.rooms[53].links.su.con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "fly em;wu;wu;wu;su;su;su"
      region.rooms[54].name = "八十四盘"
      region.rooms[54].zone = "峨眉山"
      region.rooms[54].id = 1705
      region.rooms[54].desc = "    八十四盘，道路艰险陡峭，迂回盘折，令人不能喘息。路左是蔽日遮天的冷杉林，路右是深不见底的绝壁峡谷。由此往上至接引殿，北下到洗象池。"
      region.rooms[54].exits = "southeast|northdown|southwest"
      region.rooms[54].links = {}
        region.rooms[54].links.nd = {}
          region.rooms[54].links.nd.to = 1704
          region.rooms[54].links.nd.con = ""
        region.rooms[54].links.sw = {}
          region.rooms[54].links.sw.to = 1710
          region.rooms[54].links.sw.con = ""
        region.rooms[54].links.se = {}
          region.rooms[54].links.se.to = 1707
          region.rooms[54].links.se.con = ""
    region.rooms[55] = {}
      region.rooms[55].path = "fly em;wu;wu;wu;su;su;e"
      region.rooms[55].name = "冷杉林"
      region.rooms[55].zone = "峨眉山"
      region.rooms[55].id = 1706
      region.rooms[55].desc = "    这是一片遮天蔽日的冷杉林。数人也合抱不过来的冷杉树簇在一块，棵棵枝繁叶茂，象一蓬蓬巨伞般伸向天空，把阳光遮得丝毫也无。看地上厚厚的枯枝烂叶，显然游客很少踏足此处。"
      region.rooms[55].exits = "southup|northdown|west"
      region.rooms[55].links = {}
        region.rooms[55].links.nd = {}
          region.rooms[55].links.nd.to = 1703
          region.rooms[55].links.nd.con = ""
        region.rooms[55].links.w = {}
          region.rooms[55].links.w.to = 1704
          region.rooms[55].links.w.con = ""
        region.rooms[55].links.su = {}
          region.rooms[55].links.su.to = 1707
          region.rooms[55].links.su.con = ""
    region.rooms[56] = {}
      region.rooms[56].path = "fly em;wu;wu;wu;su;su;e;su"
      region.rooms[56].name = "冷杉林"
      region.rooms[56].zone = "峨眉山"
      region.rooms[56].id = 1707
      region.rooms[56].desc = "    这是一片遮天蔽日的冷杉林。数人也合抱不过来的冷杉树簇在一块，棵棵枝繁叶茂，象一蓬蓬巨伞般伸向天空，把阳光遮得丝毫也无。看地上厚厚的枯枝烂叶，显然游客很少踏足此处。"
      region.rooms[56].exits = "east|northdown|southwest"
      region.rooms[56].links = {}
        region.rooms[56].links.e = {}
          region.rooms[56].links.e.to = 1705
          region.rooms[56].links.e.con = ""
        region.rooms[56].links.nd = {}
          region.rooms[56].links.nd.to = 1706
          region.rooms[56].links.nd.con = ""
        region.rooms[56].links.sw = {}
          region.rooms[56].links.sw.to = 1708
          region.rooms[56].links.sw.con = ""
    region.rooms[57] = {}
      region.rooms[57].path = "fly em;wu;wu;wu;su;su;e;su;sw"
      region.rooms[57].name = "冷杉林"
      region.rooms[57].zone = "峨眉山"
      region.rooms[57].id = 1708
      region.rooms[57].desc = "    这是一片遮天蔽日的冷杉林。数人也合抱不过来的冷杉树簇在一块，棵棵枝繁叶茂，象一蓬蓬巨伞般伸向天空，把阳光遮得丝毫也无。看地上厚厚的枯枝烂叶，显然游客很少踏足此处。"
      region.rooms[57].exits = "southup|northeast|west"
      region.rooms[57].links = {}
        region.rooms[57].links.ne = {}
          region.rooms[57].links.ne.to = 1707
          region.rooms[57].links.ne.con = ""
        region.rooms[57].links.w = {}
          region.rooms[57].links.w.to = 1710
          region.rooms[57].links.w.con = ""
        region.rooms[57].links.su = {}
          region.rooms[57].links.su.to = 1709
          region.rooms[57].links.su.con = ""
    region.rooms[58] = {}
      region.rooms[58].path = "fly em;wu;wu;wu;su;su;e;su;sw;su"
      region.rooms[58].name = "冷杉林"
      region.rooms[58].zone = "峨眉山"
      region.rooms[58].id = 1709
      region.rooms[58].desc = "    这是一片遮天蔽日的冷杉林。数人也合抱不过来的冷杉树簇在一块，棵棵枝繁叶茂，象一蓬蓬巨伞般伸向天空，把阳光遮得丝毫也无。看地上厚厚的枯枝烂叶，显然游客很少踏足此处。"
      region.rooms[58].exits = "southeast|northdown|southwest"
      region.rooms[58].links = {}
        region.rooms[58].links.nd = {}
          region.rooms[58].links.nd.to = 1708
          region.rooms[58].links.nd.con = ""
        region.rooms[58].links.sw = {}
          region.rooms[58].links.sw.to = 1711
          region.rooms[58].links.sw.con = ""
        region.rooms[58].links.se = {}
          region.rooms[58].links.se.to = 1712
          region.rooms[58].links.se.con = ""
    region.rooms[59] = {}
      region.rooms[59].path = "fly em;wu;wu;wu;su;su;su;sw"
      region.rooms[59].name = "八十四盘"
      region.rooms[59].zone = "峨眉山"
      region.rooms[59].id = 1710
      region.rooms[59].desc = "    八十四盘，道路艰险陡峭，迂回盘折，令人不能喘息。路左是蔽日遮天的冷杉林，路右是深不见底的绝壁峡谷。由此往上至接引殿，北下到洗象池。"
      region.rooms[59].exits = "east|northeast|southup"
      region.rooms[59].links = {}
        region.rooms[59].links.ne = {}
          region.rooms[59].links.ne.to = 1705
          region.rooms[59].links.ne.con = ""
        region.rooms[59].links.e = {}
          region.rooms[59].links.e.to = 1708
          region.rooms[59].links.e.con = ""
        region.rooms[59].links.su = {}
          region.rooms[59].links.su.to = 1711
          region.rooms[59].links.su.con = ""
    region.rooms[60] = {}
      region.rooms[60].path = "fly em;wu;wu;wu;su;su;su;sw;su"
      region.rooms[60].name = "八十四盘"
      region.rooms[60].zone = "峨眉山"
      region.rooms[60].id = 1711
      region.rooms[60].desc = "    八十四盘，道路艰险陡峭，迂回盘折，令人不能喘息。路左是蔽日遮天的冷杉林，路右是深不见底的绝壁峡谷。由此往上至接引殿，北下到洗象池。"
      region.rooms[60].exits = "southeast|northeast|northdown"
      region.rooms[60].links = {}
        region.rooms[60].links.ne = {}
          region.rooms[60].links.ne.to = 1709
          region.rooms[60].links.ne.con = ""
        region.rooms[60].links.nd = {}
          region.rooms[60].links.nd.to = 1710
          region.rooms[60].links.nd.con = ""
        region.rooms[60].links.se = {}
          region.rooms[60].links.se.to = 1712
          region.rooms[60].links.se.con = ""
    region.rooms[61] = {}
      region.rooms[61].path = "fly em;wu;wu;wu;su;su;su;sw;su;se"
      region.rooms[61].name = "接引殿"
      region.rooms[61].zone = "峨眉山"
      region.rooms[61].id = 1712
      region.rooms[61].desc = "    接引殿右边濒崖，是金钢嘴。崖下有一块巨石，形状似钟，故名「钟石」。对面有一石，高耸十余丈，叫「仙人石」。由此向上仰攀即到万行庵，北下经「八十四盘」至洗象池。"
      region.rooms[61].exits = "westup|northwest"
      region.rooms[61].links = {}
        region.rooms[61].links.nw = {}
          region.rooms[61].links.nw.to = 1711
          region.rooms[61].links.nw.con = ""
        region.rooms[61].links.wu = {}
          region.rooms[61].links.wu.to = 1713
          region.rooms[61].links.wu.con = ""
    region.rooms[62] = {}
      region.rooms[62].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu"
      region.rooms[62].name = "万行庵"
      region.rooms[62].zone = "峨眉山"
      region.rooms[62].id = 1713
      region.rooms[62].desc = "    太子坪万行庵是古智禅师创建的。庵外满山长满莎椤花，花数芭合成一朵，叶子包在花外，古人以其根坚难易而盛赞之，以喻洁身自好之高贵品质。由此向南上便至金顶，下至接引殿。"
      region.rooms[62].exits = "eastdown|southup"
      region.rooms[62].links = {}
        region.rooms[62].links.ed = {}
          region.rooms[62].links.ed.to = 1712
          region.rooms[62].links.ed.con = ""
        region.rooms[62].links.su = {}
          region.rooms[62].links.su.to = 1714
          region.rooms[62].links.su.con = ""
    region.rooms[63] = {}
      region.rooms[63].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su"
      region.rooms[63].name = "金顶"
      region.rooms[63].zone = "峨眉山"
      region.rooms[63].id = 1714
      region.rooms[63].desc = "    这就是峨嵋山的主峰金顶了。此峰耸立大地，高入云表，秀丽而又壮美，李白赞颂它：『青冥倚天开，彩错疑画出。』登上金顶，视野豁然开朗，鸟看脚下，但见群峰涌绿叠翠，三江如丝如带；回首远眺，则见大雪山横亘天际，贡嘎山直插苍穹。"
      region.rooms[63].exits = "south|northdown|southwest"
      region.rooms[63].links = {}
        region.rooms[63].links.nd = {}
          region.rooms[63].links.nd.to = 1713
          region.rooms[63].links.nd.con = ""
        region.rooms[63].links.s = {}
          region.rooms[63].links.s.to = 1715
          region.rooms[63].links.s.con = ""
        region.rooms[63].links.sw = {}
          region.rooms[63].links.sw.to = 1716
          region.rooms[63].links.sw.con = ""
    region.rooms[64] = {}
      region.rooms[64].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s"
      region.rooms[64].name = "华藏庵"
      region.rooms[64].zone = "峨眉山"
      region.rooms[64].id = 1715
      region.rooms[64].desc = "    华藏庵是金顶的主要建筑，规模宏大，中祀普贤菩萨，旁列万佛。　　华藏庵后边是睹光台，旁边是卧云庵。"
      region.rooms[64].exits = "south|northwest|north|enter"
      region.rooms[64].links = {}
        region.rooms[64].links.enter = {}
          region.rooms[64].links.enter.to = 1719
          region.rooms[64].links.enter.con = ""
        region.rooms[64].links.nw = {}
          region.rooms[64].links.nw.to = 1716
          region.rooms[64].links.nw.con = ""
        region.rooms[64].links.s = {}
          region.rooms[64].links.s.to = 1718
          region.rooms[64].links.s.con = ""
        region.rooms[64].links.n = {}
          region.rooms[64].links.n.to = 1714
          region.rooms[64].links.n.con = ""
    region.rooms[65] = {}
      region.rooms[65].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;sw"
      region.rooms[65].name = "卧云庵"
      region.rooms[65].zone = "峨眉山"
      region.rooms[65].id = 1716
      region.rooms[65].desc = "    卧云庵旁边有个井络泉，据说以前曾因饮水人多而干涸，众尼为之诵经，于是泉水复出。出了卧云庵便是睹光台，旁边是华藏庵。"
      region.rooms[65].exits = "southeast|northeast|out"
      region.rooms[65].links = {}
        region.rooms[65].links.ne = {}
          region.rooms[65].links.ne.to = 1714
          region.rooms[65].links.ne.con = ""
        region.rooms[65].links.se = {}
          region.rooms[65].links.se.to = 1715
          region.rooms[65].links.se.con = ""
        region.rooms[65].links.out = {}
          region.rooms[65].links.out.to = 1717
          region.rooms[65].links.out.con = ""
    region.rooms[66] = {}
      region.rooms[66].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;sw;out"
      region.rooms[66].name = "睹光台舍身崖"
      region.rooms[66].zone = "峨眉山"
      region.rooms[66].id = 1717
      region.rooms[66].desc = "    从卧云庵出来，这里是看日出、云海、佛光、神灯之地。台下深崖万丈，陡彻无底，云遮雾掩。极目四望，数百里外的大小雪山皆历历在目。因为这里至高至洁，至险至奇，又至美至幻，常有人在这里投身云海，舍此肉身尘世。　　金顶云海，迷迷茫茫，笼罩四野，远接天际。云海轻荡时，你在金顶，脚踏白云，大有飘飘欲仙之感；当云涛迅猛涌来时，整个金顶都似在向前浮动，令人有乘舟欲风之意。"
      region.rooms[66].exits = "east|enter"
      region.rooms[66].links = {}
        region.rooms[66].links.enter = {}
          region.rooms[66].links.enter.to = 1716
          region.rooms[66].links.enter.con = ""
        region.rooms[66].links.e = {}
          region.rooms[66].links.e.to = 1718
          region.rooms[66].links.e.con = ""
    region.rooms[67] = {}
      region.rooms[67].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;s"
      region.rooms[67].name = "睹光台"
      region.rooms[67].zone = "峨眉山"
      region.rooms[67].id = 1718
      region.rooms[67].desc = "    这里是看日出、云海、佛光、神灯之地。台下深崖万丈，陡彻无底，云遮雾掩。极目四望，数百里外的大小雪山皆历历在目。　　金顶云海，迷迷茫茫，笼罩四野，远接天际。云海轻荡时，你在金顶，脚踏白云，大有飘飘欲仙之感；当云涛迅猛涌来时，整个金顶都似在向前浮动，令人有乘舟欲风之意。"
      region.rooms[67].exits = "north|west"
      region.rooms[67].links = {}
        region.rooms[67].links.w = {}
          region.rooms[67].links.w.to = 1717
          region.rooms[67].links.w.con = ""
        region.rooms[67].links.n = {}
          region.rooms[67].links.n.to = 1715
          region.rooms[67].links.n.con = ""
    region.rooms[68] = {}
      region.rooms[68].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter"
      region.rooms[68].name = "华藏庵正殿"
      region.rooms[68].zone = "峨眉山"
      region.rooms[68].id = 1719
      region.rooms[68].desc = "    这里是峨嵋山金顶华藏庵的正殿。华藏庵规模宏大，殿内青砖铺地，中间有普贤菩萨像，两旁列有万佛。正前方放一红木供桌，陈列香烛，以供叩拜。自此左右各有一间侧殿，是接待香客的地方。南面是通往一个大广场，只有峨嵋弟子才能过去。"
      region.rooms[68].exits = "south|east|west|out"
      region.rooms[68].links = {}
        region.rooms[68].links.e = {}
          region.rooms[68].links.e.to = 1720
          region.rooms[68].links.e.con = ""
        region.rooms[68].links.w = {}
          region.rooms[68].links.w.to = 1721
          region.rooms[68].links.w.con = ""
        region.rooms[68].links.s = {}
          region.rooms[68].links.s.to = 1722
          region.rooms[68].links.s.con = "k1:静心师太"
        region.rooms[68].links.out = {}
          region.rooms[68].links.out.to = 1715
          region.rooms[68].links.out.con = ""
    region.rooms[69] = {}
      region.rooms[69].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;e"
      region.rooms[69].name = "华藏庵侧殿"
      region.rooms[69].zone = "峨眉山"
      region.rooms[69].id = 1720
      region.rooms[69].desc = "    这里是金顶华藏庵东侧殿，是接待香客及来宾的地方。殿内摆着几张桌子，桌旁围放数把椅子。墙上悬着几幅字画，墙边一排书架，架上摆满经书。有几位进香客正在品茶养神，欣赏墙上的字画或翻阅架上的经书。还有两个二十来岁的姑娘在向一位师太打听有关出家的事。一个十来岁的小师太正在忙前忙后招待客人。"
      region.rooms[69].exits = "west"
      region.rooms[69].links = {}
        region.rooms[69].links.w = {}
          region.rooms[69].links.w.to = 1719
          region.rooms[69].links.w.con = ""
    region.rooms[70] = {}
      region.rooms[70].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;w"
      region.rooms[70].name = "华藏庵侧殿"
      region.rooms[70].zone = "峨眉山"
      region.rooms[70].id = 1721
      region.rooms[70].desc = "    这里是金顶华藏庵西侧殿，是接待香客及来宾的地方。殿内摆着几张桌子，桌旁围放数把椅子。墙上悬着几幅字画，墙边一排书架，架上摆满经书。有几位进香客正在品茶养神，欣赏墙上的字画或翻阅架上的经书。还有两个二十来岁的姑娘在向一位师太打听有关出家的事。一个十来岁的小师太正在忙前忙后招待客人。南边有扇窗子(chuang)。"
      region.rooms[70].exits = "east"
      region.rooms[70].links = {}
        region.rooms[70].links.e = {}
          region.rooms[70].links.e.to = 1719
          region.rooms[70].links.e.con = ""
        region.rooms[70].links["jump chuang"] = {}
          region.rooms[70].links["jump chuang"].to = 1733
          region.rooms[70].links["jump chuang"].con = ""
    region.rooms[71] = {}
      region.rooms[71].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|"
      region.rooms[71].name = "华藏庵广场"
      region.rooms[71].zone = "峨眉山"
      region.rooms[71].id = 1722
      region.rooms[71].desc = "    这里是峨嵋华藏庵的广场，地上铺着青砖。正前方有一道台阶，通往大雄宝殿。殿前有个丈许高的大香炉，香炉前的香台上，红烛高烧，香烟飘绕。广场上有几个小师太正在练功。自此左右各有一条走廊通向后殿。"
      region.rooms[71].exits = "east|north|southup|west"
      region.rooms[71].links = {}
        region.rooms[71].links.e = {}
          region.rooms[71].links.e.to = 1723
          region.rooms[71].links.e.con = ""
        region.rooms[71].links.n = {}
          region.rooms[71].links.n.to = 1719
          region.rooms[71].links.n.con = ""
        region.rooms[71].links.w = {}
          region.rooms[71].links.w.to = 1728
          region.rooms[71].links.w.con = ""
        region.rooms[71].links.su = {}
          region.rooms[71].links.su.to = 1732
          region.rooms[71].links.su.con = ""
    region.rooms[72] = {}
      region.rooms[72].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;e"
      region.rooms[72].name = "华藏庵东廊"
      region.rooms[72].zone = "峨眉山"
      region.rooms[72].id = 1723
      region.rooms[72].desc = "    这里是峨嵋华藏庵东廊。走廊往南通往斋堂，西边通往广场。"
      region.rooms[72].exits = "south|west"
      region.rooms[72].links = {}
        region.rooms[72].links.w = {}
          region.rooms[72].links.w.to = 1722
          region.rooms[72].links.w.con = ""
        region.rooms[72].links.s = {}
          region.rooms[72].links.s.to = 1724
          region.rooms[72].links.s.con = ""
    region.rooms[73] = {}
      region.rooms[73].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;e;s"
      region.rooms[73].name = "华藏庵东廊"
      region.rooms[73].zone = "峨眉山"
      region.rooms[73].id = 1724
      region.rooms[73].desc = "    这里是峨嵋华藏庵东廊。走廊往南通往斋堂，北边通往广场。"
      region.rooms[73].exits = "south|north"
      region.rooms[73].links = {}
        region.rooms[73].links.s = {}
          region.rooms[73].links.s.to = 1725
          region.rooms[73].links.s.con = ""
        region.rooms[73].links.n = {}
          region.rooms[73].links.n.to = 1723
          region.rooms[73].links.n.con = ""
    region.rooms[74] = {}
      region.rooms[74].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;e;s;s"
      region.rooms[74].name = "华藏庵斋堂"
      region.rooms[74].zone = "峨眉山"
      region.rooms[74].id = 1725
      region.rooms[74].desc = "    这里便是峨嵋华藏庵的斋堂。斋堂里摆满了长长的餐桌和长凳，几位小师太正来回忙碌着布置素斋。桌上摆了几盆豆腐，花生，青菜以及素鸭等美味素食。斋堂后面有一道门通往华藏庵储物间，北边的走廊通向广场。"
      region.rooms[74].exits = "south|north"
      region.rooms[74].links = {}
        region.rooms[74].links.s = {}
          region.rooms[74].links.s.to = 1726
          region.rooms[74].links.s.con = ""
        region.rooms[74].links.n = {}
          region.rooms[74].links.n.to = 1724
          region.rooms[74].links.n.con = ""
    region.rooms[75] = {}
      region.rooms[75].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;e;s;s;s"
      region.rooms[75].name = "储物间"
      region.rooms[75].zone = "峨眉山"
      region.rooms[75].id = 1726
      region.rooms[75].desc = "    这里便是峨嵋华藏庵的储物间，四周都是架子。一个架上放满了各样兵器，有长剑，拂尘，长鞭等，琳琅满目。另一个架上放了各种防具。还有一个架上摆了许多小柜子，原来是装满药品的药柜。一位师太负责管理这里的物品，正忙碌着整理防具。后面好象有个小楼梯。门外就是斋堂了。"
      region.rooms[75].exits = "up|north"
      region.rooms[75].links = {}
        region.rooms[75].links.u = {}
          region.rooms[75].links.u.to = 1727
          region.rooms[75].links.u.con = ""
        region.rooms[75].links.n = {}
          region.rooms[75].links.n.to = 1725
          region.rooms[75].links.n.con = ""
    region.rooms[76] = {}
      region.rooms[76].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;e;s;s;s;u"
      region.rooms[76].name = "藏经阁"
      region.rooms[76].zone = "峨眉山"
      region.rooms[76].id = 1727
      region.rooms[76].desc = "    小阁楼上便是峨嵋派的藏经阁了。这里都是密密麻麻，高及顶棚的书架。窗口下有一张大桌子，桌上放了几本佛经。有个小师太正在向静道师太借书。"
      region.rooms[76].exits = "down"
      region.rooms[76].links = {}
        region.rooms[76].links.d = {}
          region.rooms[76].links.d.to = 1726
          region.rooms[76].links.d.con = ""
    region.rooms[77] = {}
      region.rooms[77].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;w"
      region.rooms[77].name = "华藏庵西廊"
      region.rooms[77].zone = "峨眉山"
      region.rooms[77].id = 1728
      region.rooms[77].desc = "    这里是峨嵋华藏庵西廊。走廊往南通往禅房，东边通往广场。"
      region.rooms[77].exits = "south|east"
      region.rooms[77].links = {}
        region.rooms[77].links.e = {}
          region.rooms[77].links.e.to = 1722
          region.rooms[77].links.e.con = ""
        region.rooms[77].links.s = {}
          region.rooms[77].links.s.to = 1729
          region.rooms[77].links.s.con = ""
    region.rooms[78] = {}
      region.rooms[78].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;w;s"
      region.rooms[78].name = "华藏庵西廊"
      region.rooms[78].zone = "峨眉山"
      region.rooms[78].id = 1729
      region.rooms[78].desc = "    这里是峨嵋华藏庵西廊。走廊往南禅房，北边通往广场。"
      region.rooms[78].exits = "south|north"
      region.rooms[78].links = {}
        region.rooms[78].links.s = {}
          region.rooms[78].links.s.to = 1730
          region.rooms[78].links.s.con = ""
        region.rooms[78].links.n = {}
          region.rooms[78].links.n.to = 1728
          region.rooms[78].links.n.con = ""
    region.rooms[79] = {}
      region.rooms[79].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;w;s;s"
      region.rooms[79].name = "华藏庵禅房"
      region.rooms[79].zone = "峨眉山"
      region.rooms[79].id = 1730
      region.rooms[79].desc = "    这里便是峨嵋华藏庵的禅房。地下散乱地放着许多蒲团，木鱼等，此处正是本派弟子打坐修行之所。几位年轻师太和俗家女弟子正肃容入定。　　禅房后面有一道门通往华藏庵休息室，北边的走廊通向广场。"
      region.rooms[79].exits = "south|north"
      region.rooms[79].links = {}
        region.rooms[79].links.s = {}
          region.rooms[79].links.s.to = 1731
          region.rooms[79].links.s.con = ""
        region.rooms[79].links.n = {}
          region.rooms[79].links.n.to = 1729
          region.rooms[79].links.n.con = ""
    region.rooms[80] = {}
      region.rooms[80].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;w;s;s;s"
      region.rooms[80].name = "华藏庵休息室"
      region.rooms[80].zone = "峨眉山"
      region.rooms[80].id = 1731
      region.rooms[80].desc = "    这里是峨嵋华藏庵的休息室。窗帘拉下来，房里整整齐齐放了很多木床。有几个夜晚守庵的小师太正在睡觉。　　休息室外就是禅房。"
      region.rooms[80].exits = "north"
      region.rooms[80].links = {}
        region.rooms[80].links.n = {}
          region.rooms[80].links.n.to = 1730
          region.rooms[80].links.n.con = ""
    region.rooms[81] = {}
      region.rooms[81].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;|!k1:静心师太:s|;su"
      region.rooms[81].name = "华藏庵大雄宝殿"
      region.rooms[81].zone = "峨眉山"
      region.rooms[81].id = 1732
      region.rooms[81].desc = "    这是峨嵋山华藏庵的大雄宝殿。正中供奉着普贤菩萨。一群青衣小师太正在地上诵经。后面有道小门通往后殿。"
      region.rooms[81].exits = "south|northdown"
      region.rooms[81].links = {}
        region.rooms[81].links.nd = {}
          region.rooms[81].links.nd.to = 1722
          region.rooms[81].links.nd.con = ""
    region.rooms[82] = {}
      region.rooms[82].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;w;jump chuang"
      region.rooms[82].name = "小树林"
      region.rooms[82].zone = "峨眉山"
      region.rooms[82].id = 1733
      region.rooms[82].desc = "    这是峨嵋山金顶华藏庵外的一片小树林。林中没有路，但地上依稀有些足迹，似乎刚有人走过。北面有一扇小窗。"
      region.rooms[82].exits = "south"
      region.rooms[82].links = {}
        region.rooms[82].links.s = {}
          region.rooms[82].links.s.to = 1734
          region.rooms[82].links.s.con = ""
        region.rooms[82].links["jump chuang"] = {}
          region.rooms[82].links["jump chuang"].to = 1721
          region.rooms[82].links["jump chuang"].con = ""
    region.rooms[83] = {}
      region.rooms[83].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;w;jump chuang;s"
      region.rooms[83].name = "小树林"
      region.rooms[83].zone = "峨眉山"
      region.rooms[83].id = 1734
      region.rooms[83].desc = "    这是峨嵋山金顶华藏庵外的一片小树林。林中没有路，但地上依稀有些足迹，似乎刚有人走过。"
      region.rooms[83].exits = "south|north"
      region.rooms[83].links = {}
        region.rooms[83].links.s = {}
          region.rooms[83].links.s.to = 1735
          region.rooms[83].links.s.con = ""
        region.rooms[83].links.n = {}
          region.rooms[83].links.n.to = 1733
          region.rooms[83].links.n.con = ""
    region.rooms[84] = {}
      region.rooms[84].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;w;jump chuang;s;s"
      region.rooms[84].name = "小树林"
      region.rooms[84].zone = "峨眉山"
      region.rooms[84].id = 1735
      region.rooms[84].desc = "    这是峨嵋山金顶华藏庵外的一片小树林。林中没有路，但地上依稀有些足迹，似乎刚有人走过。"
      region.rooms[84].exits = "north|southeast"
      region.rooms[84].links = {}
        region.rooms[84].links.n = {}
          region.rooms[84].links.n.to = 1734
          region.rooms[84].links.n.con = ""
        region.rooms[84].links.se = {}
          region.rooms[84].links.se.to = 1736
          region.rooms[84].links.se.con = ""
    region.rooms[85] = {}
      region.rooms[85].path = "fly em;wu;wu;wu;su;su;su;sw;su;se;wu;su;s;enter;w;jump chuang;s;s;se"
      region.rooms[85].name = "小树林"
      region.rooms[85].zone = "峨眉山"
      region.rooms[85].id = 1736
      region.rooms[85].desc = "    这是峨嵋山金顶华藏庵外的一片小树林。北边是峨嵋派女弟子们的寝宫的窗户，窗下好像蹲着一个人。"
      region.rooms[85].exits = "north|northwest"
      region.rooms[85].links = {}
        region.rooms[85].links.nw = {}
          region.rooms[85].links.nw.to = 1735
          region.rooms[85].links.nw.con = ""
    region.rooms[86] = {}
      region.rooms[86].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;e;nd;ne;n"
      region.rooms[86].name = "小路"
      region.rooms[86].zone = "峨眉山"
      region.rooms[86].id = 1737
      region.rooms[86].desc = "    这是四川与湖北的交界。一条静悄悄的小土路，两旁有疏疏落落的农舍耕田，但路上行人很少，都匆匆赶路。"
      region.rooms[86].exits = "south|east"
      region.rooms[86].links = {}
        region.rooms[86].links.s = {}
          region.rooms[86].links.s.to = 664
          region.rooms[86].links.s.con = ""
        region.rooms[86].links.e = {}
          region.rooms[86].links.e.to = 1738
          region.rooms[86].links.e.con = ""
    region.rooms[87] = {}
      region.rooms[87].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;e;nd;ne;n;e"
      region.rooms[87].name = "小路"
      region.rooms[87].zone = "峨眉山"
      region.rooms[87].id = 1738
      region.rooms[87].desc = "    这是四川与湖北的交界。一条静悄悄的小土路，两旁有疏疏落落的农舍耕田，但路上行人很少，都匆匆赶路。"
      region.rooms[87].exits = "northeast|west"
      region.rooms[87].links = {}
        region.rooms[87].links.w = {}
          region.rooms[87].links.w.to = 1737
          region.rooms[87].links.w.con = ""
        region.rooms[87].links.ne = {}
          region.rooms[87].links.ne.to = 1739
          region.rooms[87].links.ne.con = ""
    region.rooms[88] = {}
      region.rooms[88].path = "fly em;ed;d;ne;ed;ne;ed;sd;se;se;ed;ed;ed;ed;ed;ed;ed;e;ne;e;nd;ne;n;e;ne"
      region.rooms[88].name = "大道"
      region.rooms[88].zone = "峨眉山|武当山"
      region.rooms[88].id = 1739
      region.rooms[88].desc = "    你走在一条黄土大道上，不时地有人挂剑跨马匆匆而过。东北通向武当。"
      region.rooms[88].exits = "northeast|southwest"
      region.rooms[88].links = {}
        region.rooms[88].links.ne = {}
          region.rooms[88].links.ne.to = 1740
          region.rooms[88].links.ne.con = ""
        region.rooms[88].links.sw = {}
          region.rooms[88].links.sw.to = 1738
          region.rooms[88].links.sw.con = ""
  region.center = 1688
return region