local region = {}
  region.cmd = "fly es"
  region.name = "泰山"
  region.id = "es"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly es;sd;sd;sd;sd;sd;sd;wd;sd;sd;sd;s;s;s"
      region.rooms[1].name = "大驿道"
      region.rooms[1].zone = "扬州|泰山"
      region.rooms[1].id = 84
      region.rooms[1].links = {}
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 1268
          region.rooms[1].links.n.con = ""
        region.rooms[1].links.sw = {}
          region.rooms[1].links.sw.to = 82
          region.rooms[1].links.sw.con = ""
      region.rooms[1].exits = "north|southwest"
      region.rooms[1].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的行商，赶着大车的马夫，上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。    现在是正午时分，天阴着，凛冽的北风呼呼的吹着。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly es;sd;sd;sd;sd;sd;sd;wd;sd;sd;sd;s;s"
      region.rooms[2].name = "大驿道"
      region.rooms[2].zone = "泰山"
      region.rooms[2].id = 1268
      region.rooms[2].links = {}
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 84
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 1269
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "south|north"
      region.rooms[2].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的行商，赶着大车的马夫，上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly es;sd;sd;sd;sd;sd;sd;wd;sd;sd;sd;s"
      region.rooms[3].name = "泰山脚下"
      region.rooms[3].zone = "泰山"
      region.rooms[3].id = 1269
      region.rooms[3].links = {}
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 1268
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 1270
          region.rooms[3].links.n.con = ""
      region.rooms[3].exits = "south|north"
      region.rooms[3].desc = "    泰山古称岱山，为五岳的东岳，为道教第二小洞天，向有 \"五岳独尊\" 之称誉，以 \"泰山天下雄\" 名闻域内。往北就到岱宗坊了。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly es;sd;sd;sd;sd;sd;sd;wd;sd;sd;sd"
      region.rooms[4].name = "岱宗坊"
      region.rooms[4].zone = "泰山"
      region.rooms[4].id = 1270
      region.rooms[4].links = {}
        region.rooms[4].links.nu = {}
          region.rooms[4].links.nu.to = 1272
          region.rooms[4].links.nu.con = ""
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 1271
          region.rooms[4].links.w.con = ""
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 1269
          region.rooms[4].links.s.con = ""
      region.rooms[4].exits = "south|northup|west"
      region.rooms[4].desc = "    位于泰安县城以北约一里，此处是登泰山的入口。相传当年碧霞元君被姜子牙戏弄，诱她投掷绣花鞋以定泰山地界，结果碧霞元君只能把绣花鞋从山顶掷到此处。从此泰山便以此为起点。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly es;sd;sd;sd;sd;sd;sd;wd;sd;sd;sd;w"
      region.rooms[5].name = "黄河岸边"
      region.rooms[5].zone = "泰山|河套地区"
      region.rooms[5].id = 1271
      region.rooms[5].desc = "    这里是黄河岸边。黄河流淌到这里，河床宽阔。黄色的河水在静静地向东流去，使人忘记它发洪水时的狂威。"
      region.rooms[5].exits = "east|northeast|southwest"
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 1270
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.sw = {}
          region.rooms[5].links.sw.to = 2420
          region.rooms[5].links.sw.con = ""
        region.rooms[5].links.ne = {}
          region.rooms[5].links.ne.to = 2421
          region.rooms[5].links.ne.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly es;sd;sd;sd;sd;sd;sd;wd;sd;sd"
      region.rooms[6].name = "白鹤泉"
      region.rooms[6].zone = "泰山"
      region.rooms[6].id = 1272
      region.rooms[6].links = {}
        region.rooms[6].links.sd = {}
          region.rooms[6].links.sd.to = 1270
          region.rooms[6].links.sd.con = ""
        region.rooms[6].links.nu = {}
          region.rooms[6].links.nu.to = 1273
          region.rooms[6].links.nu.con = ""
      region.rooms[6].exits = "northup|southdown"
      region.rooms[6].desc = "    相传从前这里有一个白鹤泉，它的水清凉甘甜，为泰山之最。这泉水长年涌流不断，喷出的水象仙鹤扑扇着翅膀洗澡一样，因以为名。可惜后来有一个自私自利的小官，独霸了泉水，后来更因迷信风水之说，把泉眼堵塞，白鹤泉从此便干涸了。现在只剩下一座刻着「白鹤泉」三字的石坊以为纪念。从这里继续北上，便是上山之路。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly es;sd;sd;sd;sd;sd;sd;wd;sd"
      region.rooms[7].name = "一天门"
      region.rooms[7].zone = "泰山"
      region.rooms[7].id = 1273
      region.rooms[7].links = {}
        region.rooms[7].links.sd = {}
          region.rooms[7].links.sd.to = 1272
          region.rooms[7].links.sd.con = ""
        region.rooms[7].links.nu = {}
          region.rooms[7].links.nu.to = 1274
          region.rooms[7].links.nu.con = ""
      region.rooms[7].exits = "northup|southdown"
      region.rooms[7].desc = "    从岱宗坊上山大约走四里，便来到一天门。北面有一座天阶坊，过了此坊便进入了登泰山的盘道。南面有一座更衣亭，士大夫们及其随从，都会在这里换上轻便的服装，才继续登山。从一天门向北眺望，南天门与十八盘在云雾明灭间或隐或现，登泰山的人到此已有观止之叹。附近有一牌坊，上写「孔子登临处」，相传为「孔子过泰山侧」的故事发生的地方。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly es;sd;sd;sd;sd;sd;sd;wd"
      region.rooms[8].name = "斗母宫"
      region.rooms[8].zone = "泰山"
      region.rooms[8].id = 1274
      region.rooms[8].links = {}
        region.rooms[8].links.sd = {}
          region.rooms[8].links.sd.to = 1273
          region.rooms[8].links.sd.con = ""
        region.rooms[8].links.eu = {}
          region.rooms[8].links.eu.to = 1275
          region.rooms[8].links.eu.con = ""
      region.rooms[8].exits = "eastup|southdown"
      region.rooms[8].desc = "    上了一段山路，游人一般都会在这里稍为休息。这里的地势已经比泰山邻近的徂徕山为高，从这里往东北走便是石经峪。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly es;sd;sd;sd;sd;sd;sd"
      region.rooms[9].name = "石经峪"
      region.rooms[9].zone = "泰山"
      region.rooms[9].id = 1275
      region.rooms[9].links = {}
        region.rooms[9].links.wd = {}
          region.rooms[9].links.wd.to = 1274
          region.rooms[9].links.wd.con = ""
        region.rooms[9].links.nu = {}
          region.rooms[9].links.nu.to = 1276
          region.rooms[9].links.nu.con = ""
      region.rooms[9].exits = "northup|westdown"
      region.rooms[9].desc = "    这里是一块大石坪，石面刻有篆文「金刚经」，字体其大如斗，但却没有记载刻石者的名字和刻石的年代。过了此处，渐入空山，山路越来越不好走了。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly es;sd;sd;sd;sd;sd"
      region.rooms[10].name = "回马岭"
      region.rooms[10].zone = "泰山"
      region.rooms[10].id = 1276
      region.rooms[10].links = {}
        region.rooms[10].links.sd = {}
          region.rooms[10].links.sd.to = 1275
          region.rooms[10].links.sd.con = ""
        region.rooms[10].links.nu = {}
          region.rooms[10].links.nu.to = 1277
          region.rooms[10].links.nu.con = ""
      region.rooms[10].exits = "northup|southdown"
      region.rooms[10].desc = "    此处又名天关，到了这里，马匹已不能再前进。据说当年唐玄宗上泰山封禅，来到这里，因陡峭难攀，累死了白马，要改乘小轿上山。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly es;sd;sd;sd;sd"
      region.rooms[11].name = "二天门"
      region.rooms[11].zone = "泰山"
      region.rooms[11].id = 1277
      region.rooms[11].links = {}
        region.rooms[11].links.sd = {}
          region.rooms[11].links.sd.to = 1276
          region.rooms[11].links.sd.con = ""
        region.rooms[11].links.nu = {}
          region.rooms[11].links.nu.to = 1278
          region.rooms[11].links.nu.con = ""
      region.rooms[11].exits = "northup|southdown"
      region.rooms[11].desc = "    这里又叫「中天门」。一般的登山者来到这里都已累极，但是这里才是泰山的一半啊！面对前面险峻的十八盘，很多人都不禁犹豫起来。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly es;sd;sd;sd"
      region.rooms[12].name = "五大夫松"
      region.rooms[12].zone = "泰山"
      region.rooms[12].id = 1278
      region.rooms[12].links = {}
        region.rooms[12].links.sd = {}
          region.rooms[12].links.sd.to = 1277
          region.rooms[12].links.sd.con = ""
        region.rooms[12].links.nu = {}
          region.rooms[12].links.nu.to = 1279
          region.rooms[12].links.nu.con = ""
      region.rooms[12].exits = "northup|southdown"
      region.rooms[12].desc = "    相传当年秦始皇上泰山，来到这里下起雨来，他就到两棵松树底下避雨，结果没淋着。因此，他就封这两棵松树为「五大夫」。后来不知从哪里来了一块巨大的飞来石把两棵松树砸死了。后人再在旁补种五株松树。在不远处还有一个御帐坪，据说就是秦始皇当年结帐的位置。从这里再往山上走便会到达十八盘的入口。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly es;sd;sd"
      region.rooms[13].name = "龙门"
      region.rooms[13].zone = "泰山"
      region.rooms[13].id = 1279
      region.rooms[13].links = {}
        region.rooms[13].links.sd = {}
          region.rooms[13].links.sd.to = 1278
          region.rooms[13].links.sd.con = ""
        region.rooms[13].links.nu = {}
          region.rooms[13].links.nu.to = 1280
          region.rooms[13].links.nu.con = ""
      region.rooms[13].exits = "northup|southdown"
      region.rooms[13].desc = "    这里便是泰山十八盘的起点。此处山势陡峭，登山的人一个不小心很容易便会跌堕到崖谷之中。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly es;sd"
      region.rooms[14].name = "升仙坊"
      region.rooms[14].zone = "泰山"
      region.rooms[14].id = 1280
      region.rooms[14].links = {}
        region.rooms[14].links.sd = {}
          region.rooms[14].links.sd.to = 1279
          region.rooms[14].links.sd.con = ""
        region.rooms[14].links.nu = {}
          region.rooms[14].links.nu.to = 1281
          region.rooms[14].links.nu.con = ""
      region.rooms[14].exits = "northup|southdown"
      region.rooms[14].desc = "    这里是十八盘的中间，从龙门至此的一段称为缓十八，从这里直上南天门的一段称为紧十八。由此刻攀石而上，后面的人可以看到前面的人的鞋底，前面的人回头则可见到后面的人的发顶。在这里一般人每走十来步便要稍一休息。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly es"
      region.rooms[15].name = "南天门"
      region.rooms[15].zone = "泰山"
      region.rooms[15].id = 1281
      region.rooms[15].links = {}
        region.rooms[15].links.nu = {}
          region.rooms[15].links.nu.to = 1290
          region.rooms[15].links.nu.con = "k1:江百胜"
        region.rooms[15].links.eu = {}
          region.rooms[15].links.eu.to = 1284
          region.rooms[15].links.eu.con = ""
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 1282
          region.rooms[15].links.w.con = ""
        region.rooms[15].links.sd = {}
          region.rooms[15].links.sd.to = 1280
          region.rooms[15].links.sd.con = ""
      region.rooms[15].exits = "eastup|northup|southdown|west"
      region.rooms[15].desc = "    走完了十八盘，这里便是泰山顶的入口处。从这里附视山下，群山如龟伏地，河流如蚓缠绕，天地空阔，无可名状。从这里往东北走可到一个市集，往西走便是月观峰，往北走则是到玉皇顶之路。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly es;w"
      region.rooms[16].name = "月观峰"
      region.rooms[16].zone = "泰山"
      region.rooms[16].id = 1282
      region.rooms[16].links = {}
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 1281
          region.rooms[16].links.e.con = ""
        region.rooms[16].links.nu = {}
          region.rooms[16].links.nu.to = 1283
          region.rooms[16].links.nu.con = ""
      region.rooms[16].exits = "east|northup"
      region.rooms[16].desc = "    这里是位于南天门西面的山岭，怪石攒簇，最高的地方一石卓立，名为君子峰。往北走便是泰山的西天门。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly es;w;nu"
      region.rooms[17].name = "西天门"
      region.rooms[17].zone = "泰山"
      region.rooms[17].id = 1283
      region.rooms[17].links = {}
        region.rooms[17].links.sd = {}
          region.rooms[17].links.sd.to = 1282
          region.rooms[17].links.sd.con = ""
      region.rooms[17].exits = "southdown"
      region.rooms[17].desc = "    这里有两块巨石壁立，有如给人斩削过似的，正是岱顶的西面出口。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly es;eu"
      region.rooms[18].name = "天街"
      region.rooms[18].zone = "泰山"
      region.rooms[18].id = 1284
      region.rooms[18].links = {}
        region.rooms[18].links.ed = {}
          region.rooms[18].links.ed.to = 1288
          region.rooms[18].links.ed.con = ""
        region.rooms[18].links.eu = {}
          region.rooms[18].links.eu.to = 1285
          region.rooms[18].links.eu.con = ""
        region.rooms[18].links.wd = {}
          region.rooms[18].links.wd.to = 1281
          region.rooms[18].links.wd.con = ""
      region.rooms[18].exits = "eastdown|eastup|westdown"
      region.rooms[18].desc = "    此地在南天门东北，这里有数十户小贩聚而成市。从这里往东南走便是莲花峰，东北是围屏山，西南便回到南天门。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly es;eu;eu"
      region.rooms[19].name = "围屏山"
      region.rooms[19].zone = "泰山"
      region.rooms[19].id = 1285
      region.rooms[19].links = {}
        region.rooms[19].links.wd = {}
          region.rooms[19].links.wd.to = 1284
          region.rooms[19].links.wd.con = ""
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 1286
          region.rooms[19].links.e.con = ""
      region.rooms[19].exits = "east|westdown"
      region.rooms[19].desc = "    这里是泰山的其中一座山峰。山的东面有一个虎头崖，其形状有如一头伏虎。南面有避风崖，崖上大大地刻着「振衣冈」三字于上面。北边则有北斗坛。从这里往东走，便可到达伺奉泰山之神碧霞元君的碧霞祠。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly es;eu;eu;e"
      region.rooms[20].name = "碧霞祠"
      region.rooms[20].zone = "泰山"
      region.rooms[20].id = 1286
      region.rooms[20].links = {}
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 1285
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.ed = {}
          region.rooms[20].links.ed.to = 1287
          region.rooms[20].links.ed.con = ""
      region.rooms[20].exits = "eastdown|west"
      region.rooms[20].desc = "    这是一座历史悠久而宏伟壮丽的祠院。相传建于唐代以前，宋、元、明、清各代均曾增建。祠院设有东西两殿，分别称为东西宝库，储存着进香客的捐施，两殿的屋瓦都是由铁铸成。从四方八面来泰山上香的男女，都是先到碧霞祠，然后才到其他的庙宇。从这里往东南走便可到达宝藏岭。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly es;eu;eu;e;ed"
      region.rooms[21].name = "宝藏岭"
      region.rooms[21].zone = "泰山"
      region.rooms[21].id = 1287
      region.rooms[21].links = {}
        region.rooms[21].links.wu = {}
          region.rooms[21].links.wu.to = 1286
          region.rooms[21].links.wu.con = ""
      region.rooms[21].exits = "westup"
      region.rooms[21].desc = "    这里是泰山的一个名胜。岭上有一座状似狮子的巨石，称为狮子崖。最出名的还是要数在东北面的东岳庙，也称上岳庙，是古代封禅的地方，那里有一块唐玄宗的纪泰山铭。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly es;eu;ed"
      region.rooms[22].name = "莲花峰"
      region.rooms[22].zone = "泰山"
      region.rooms[22].id = 1288
      region.rooms[22].links = {}
        region.rooms[22].links.nu = {}
          region.rooms[22].links.nu.to = 1289
          region.rooms[22].links.nu.con = ""
        region.rooms[22].links.wu = {}
          region.rooms[22].links.wu.to = 1284
          region.rooms[22].links.wu.con = ""
      region.rooms[22].exits = "westup|northup"
      region.rooms[22].desc = "    莲花峰其实是由五座山峰攒簇而成，状如莲花，因以为名。东面有危崖万仞，叫五花崖。登上莲花峰后，可看到在盘道中的游人如小蚁般往来穿梭，故此莲花峰又叫望人峰。往上走便是莲花峰的峰顶。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly es;eu;ed;nu"
      region.rooms[23].name = "试心石"
      region.rooms[23].zone = "泰山"
      region.rooms[23].id = 1289
      region.rooms[23].links = {}
        region.rooms[23].links.sd = {}
          region.rooms[23].links.sd.to = 1288
          region.rooms[23].links.sd.con = ""
      region.rooms[23].exits = "southdown"
      region.rooms[23].desc = "    这里便是莲花峰的峰顶，由两块巨石勾连在一起，据说若果你心存诚意，登上试心石时石快便不会动摇，反之则摇动不止。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly es;|!k1:江百胜:nu|"
      region.rooms[24].name = "玉皇顶"
      region.rooms[24].zone = "泰山"
      region.rooms[24].id = 1290
      region.rooms[24].links = {}
        region.rooms[24].links.ed = {}
          region.rooms[24].links.ed.to = 1293
          region.rooms[24].links.ed.con = ""
        region.rooms[24].links.u = {}
          region.rooms[24].links.u.to = 1296
          region.rooms[24].links.u.con = ""
        region.rooms[24].links.w = {}
          region.rooms[24].links.w.to = 1291
          region.rooms[24].links.w.con = ""
        region.rooms[24].links.sd = {}
          region.rooms[24].links.sd.to = 1281
          region.rooms[24].links.sd.con = ""
      region.rooms[24].exits = "up|eastdown|southdown|west"
      region.rooms[24].desc = "    此处便是泰山绝顶。这里有一座玉帝观，观前为古登封台，厉代皇帝封禅的仪式都是在这里举行。台下有一无字碑，据说是汉武帝所立。不远处有一石碣，上书「孔子小天下处」。正中往上便是武林盟主所在之处─封禅台。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly es;|!k1:江百胜:nu|;w"
      region.rooms[25].name = "丈人峰"
      region.rooms[25].zone = "泰山"
      region.rooms[25].id = 1291
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 1290
          region.rooms[25].links.e.con = ""
        region.rooms[25].links.nu = {}
          region.rooms[25].links.nu.to = 1292
          region.rooms[25].links.nu.con = ""
      region.rooms[25].exits = "east|northup"
      region.rooms[25].desc = "    这里位于玉皇顶以西里许的地方，形状有如一个伛偻的老人。靠西有黄华洞，因洞路极为危险，后人在进路处写上「回车岩」。从这里往北走便是岱顶的北天门。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly es;|!k1:江百胜:nu|;w;nu"
      region.rooms[26].name = "北天门"
      region.rooms[26].zone = "泰山"
      region.rooms[26].id = 1292
      region.rooms[26].links = {}
        region.rooms[26].links.sd = {}
          region.rooms[26].links.sd.to = 1291
          region.rooms[26].links.sd.con = ""
      region.rooms[26].exits = "southdown"
      region.rooms[26].desc = "    这里位于石马山的北麓，是岱顶的北面出口，路口有一石坊，上面写着「玄武」二字。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly es;|!k1:江百胜:nu|;ed"
      region.rooms[27].name = "日观峰"
      region.rooms[27].zone = "泰山"
      region.rooms[27].id = 1293
      region.rooms[27].links = {}
        region.rooms[27].links.eu = {}
          region.rooms[27].links.eu.to = 1294
          region.rooms[27].links.eu.con = ""
        region.rooms[27].links.wu = {}
          region.rooms[27].links.wu.to = 1290
          region.rooms[27].links.wu.con = ""
      region.rooms[27].exits = "westup|eastup"
      region.rooms[27].desc = "    这里是位于南天门西面的山岭，怪石攒簇，最高的地方一石卓立，名为君子峰。往北走便是泰山的西天门。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly es;|!k1:江百胜:nu|;ed;eu"
      region.rooms[28].name = "探海石"
      region.rooms[28].zone = "泰山"
      region.rooms[28].id = 1294
      region.rooms[28].links = {}
        region.rooms[28].links.wd = {}
          region.rooms[28].links.wd.to = 1293
          region.rooms[28].links.wd.con = ""
        region.rooms[28].links.e = {}
          region.rooms[28].links.e.to = 1295
          region.rooms[28].links.e.con = ""
      region.rooms[28].exits = "east|westdown"
      region.rooms[28].desc = "    这是一块从山崖向横突出的巨石，长约二丈余，向东直指渤海。巨石三面无所凭依，视野广阔，但除非有绝高胆色的人，普通人一般都不敢攀登这块探海石。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly es;|!k1:江百胜:nu|;ed;eu;e"
      region.rooms[29].name = "东天门"
      region.rooms[29].zone = "泰山"
      region.rooms[29].id = 1295
      region.rooms[29].links = {}
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 1294
          region.rooms[29].links.w.con = ""
      region.rooms[29].exits = "west"
      region.rooms[29].desc = "    这里是岱顶的东面出口。往东依次经过伏虎门峡口、鹰愁涧等，便可下山。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly es;|!k1:江百胜:nu|;u"
      region.rooms[30].name = "封禅台"
      region.rooms[30].zone = "泰山"
      region.rooms[30].id = 1296
      region.rooms[30].links = {}
        region.rooms[30].links.e = {}
          region.rooms[30].links.e.to = 1297
          region.rooms[30].links.e.con = ""
        region.rooms[30].links.d = {}
          region.rooms[30].links.d.to = 1290
          region.rooms[30].links.d.con = ""
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 1298
          region.rooms[30].links.w.con = ""
      region.rooms[30].exits = "east|west|down"
      region.rooms[30].desc = "    如今这里是推选天下武林总盟主之处，各路英雄如能技压群雄，比武夺魁，便能问鼎盟主宝座，成为统领中原武林的领袖。高台上摆放着汉白玉宝座，盟主便在此坐堂议事。台上高高立着一竿旗，上书：替天行道 四个大字。 盟主左右各侍立着两位白衣武士，两边都放着一长排虎皮交椅，时常有武林前辈高手前来参见盟主。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly es;|!k1:江百胜:nu|;u;e"
      region.rooms[31].name = "侠义厅"
      region.rooms[31].zone = "泰山"
      region.rooms[31].id = 1297
      region.rooms[31].links = {}
        region.rooms[31].links.w = {}
          region.rooms[31].links.w.to = 1296
          region.rooms[31].links.w.con = ""
      region.rooms[31].exits = "west"
      region.rooms[31].desc = "    这里是封禅台左边的侠义厅，武林盟赏善使者平时不下山时，通常都是在这里办理武林公案。上首正中放着把太师椅，赏善使者就坐在上面开堂审理。左右各侍立着几位红衣武士，看上去威风凛凛，自有一股庄严气象。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly es;|!k1:江百胜:nu|;u;w"
      region.rooms[32].name = "正气厅"
      region.rooms[32].zone = "泰山"
      region.rooms[32].id = 1298
      region.rooms[32].links = {}
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 1296
          region.rooms[32].links.e.con = ""
      region.rooms[32].exits = "east"
      region.rooms[32].desc = "    这里是封禅台右边的正气厅，武林盟罚恶使者平时不下山时，通常都是在这里处置武林公案。上首正中放着把虎皮椅，罚恶使者就坐在上面开堂审理。左右各侍立着几位红衣武士，看上去杀气腾腾，令人凛然而生惧意。"
  region.center = 1281
return region