local region = {}
  region.cmd = "fly fz"
  region.name = "福州"
  region.id = "fz"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;nu;n;ne"
      region.rooms[1].name = "丘陵野路"
      region.rooms[1].zone = "杭州|福州"
      region.rooms[1].id = 325
      region.rooms[1].desc = "    从浙江到福建的山路，不算太长，但有些难走。"
      region.rooms[1].exits = "northeast|southwest"
      region.rooms[1].links = {}
        region.rooms[1].links.ne = {}
          region.rooms[1].links.ne.to = 242
          region.rooms[1].links.ne.con = ""
        region.rooms[1].links.sw = {}
          region.rooms[1].links.sw.to = 326
          region.rooms[1].links.sw.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;nu;n"
      region.rooms[2].name = "仙霞岭"
      region.rooms[2].zone = "杭州|福州"
      region.rooms[2].id = 326
      region.rooms[2].desc = "    这里就是闽浙分水的仙霞岭。向阳的坡面郁郁葱葱，长满了长长的马尾松。沿途的山路十分难行，来往的口音也渐渐带有闽音，越来越难以辩识了。"
      region.rooms[2].exits = "south|northeast"
      region.rooms[2].links = {}
        region.rooms[2].links.ne = {}
          region.rooms[2].links.ne.to = 325
          region.rooms[2].links.ne.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 327
          region.rooms[2].links.s.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;nu"
      region.rooms[3].name = "廿八铺"
      region.rooms[3].zone = "福州"
      region.rooms[3].id = 327
      region.rooms[3].desc = "    廿八铺高居仙霞岭上，四望群山连绵，长风振岗，十分爽利。这里是个很小的小村落，虽然南来北往的客商繁多，可是也只有一家小小客店。"
      region.rooms[3].exits = "north|southdown|west"
      region.rooms[3].links = {}
        region.rooms[3].links.sd = {}
          region.rooms[3].links.sd.to = 329
          region.rooms[3].links.sd.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 328
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 326
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;nu;w"
      region.rooms[4].name = "客店"
      region.rooms[4].zone = "福州"
      region.rooms[4].id = 328
      region.rooms[4].desc = "    山野客店十分简陋。一个小二临台买卖，一片破门扇扑在地上，显得相当忙乱。柜台上贴着个牌子(paizi)。"
      region.rooms[4].exits = "east"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 327
          region.rooms[4].links.e.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd"
      region.rooms[5].name = "武夷山道"
      region.rooms[5].zone = "福州"
      region.rooms[5].id = 329
      region.rooms[5].desc = "    你走在窄窄的武夷山小道上，山路崎岖，密林森森，常有长虫野兽出没。所谓“闽道更比蜀道难”，诚不相欺。西面隔着崇阳溪，就是奇秀甲于东南的武夷山了。"
      region.rooms[5].exits = "northup|southup|west"
      region.rooms[5].links = {}
        region.rooms[5].links.nu = {}
          region.rooms[5].links.nu.to = 327
          region.rooms[5].links.nu.con = ""
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 330
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.su = {}
          region.rooms[5].links.su.to = 337
          region.rooms[5].links.su.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;w"
      region.rooms[6].name = "武夷山"
      region.rooms[6].zone = "福州"
      region.rooms[6].id = 330
      region.rooms[6].desc = "    武夷山方圆两百四十里，九曲溪盘流群山之中，沿溪森列三十六峰，碧水丹山，风光旖丽。奇峰云海，山清水秀，号称“三三水，六六峰”。"
      region.rooms[6].exits = "east|west"
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 329
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 331
          region.rooms[6].links.w.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;w;w"
      region.rooms[7].name = "九曲溪"
      region.rooms[7].zone = "福州"
      region.rooms[7].id = 331
      region.rooms[7].desc = "    九曲溪依山而流，九曲九折，穿梭丹岩之中，水色碧透，掬手可饮，“曲曲山回转，峰峰水抱流”，山光水色，融为一体。沿岸大王峰巍峨，玉女峰俏立，备极景致。"
      region.rooms[7].exits = "east|northup|southup|west"
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 330
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.nu = {}
          region.rooms[7].links.nu.to = 332
          region.rooms[7].links.nu.con = ""
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 334
          region.rooms[7].links.w.con = ""
        region.rooms[7].links.su = {}
          region.rooms[7].links.su.to = 333
          region.rooms[7].links.su.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;w;w;nu"
      region.rooms[8].name = "大王峰"
      region.rooms[8].zone = "福州"
      region.rooms[8].id = 332
      region.rooms[8].desc = "    大王峰又称纱帽峰，山形如宦者纱帽，独具王仪而得名。四周悬崖壁立，上丰下敛，气势雄浑。远远望去，宛若擎天巨柱，与玉女遥遥相望。石壁上刻有“居高思危”四字。"
      region.rooms[8].exits = "southdown"
      region.rooms[8].links = {}
        region.rooms[8].links.sd = {}
          region.rooms[8].links.sd.to = 331
          region.rooms[8].links.sd.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;w;w;su"
      region.rooms[9].name = "玉女峰"
      region.rooms[9].zone = "福州"
      region.rooms[9].id = 333
      region.rooms[9].desc = "    玉女峰亭亭如少女玉立，突兀挺拔。峰顶花卉参簇，恰似山花插鬓。岩壁秀润光滑，宛如玉肌清凉。俏立溪畔，凛然不可侵犯，无路攀登。“插花临水一奇峰，玉骨冰肌处女容”即其写照。峰下浴香潭，为玉女沐浴处。峰东圆石如镜，是为梳妆台。"
      region.rooms[9].exits = "northdown"
      region.rooms[9].links = {}
        region.rooms[9].links.nd = {}
          region.rooms[9].links.nd.to = 331
          region.rooms[9].links.nd.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;w;w;w"
      region.rooms[10].name = "九曲溪"
      region.rooms[10].zone = "福州"
      region.rooms[10].id = 334
      region.rooms[10].desc = "    盈盈一水，折为九曲。两岸树绿竹翠，奇峰突兀，真是“溪流九曲泻云液，山光倒浸清涟漪”。"
      region.rooms[10].exits = "northwest|east|northup"
      region.rooms[10].links = {}
        region.rooms[10].links.nu = {}
          region.rooms[10].links.nu.to = 335
          region.rooms[10].links.nu.con = ""
        region.rooms[10].links.nw = {}
          region.rooms[10].links.nw.to = 336
          region.rooms[10].links.nw.con = ""
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 331
          region.rooms[10].links.e.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;w;w;w;nu"
      region.rooms[11].name = "天游峰"
      region.rooms[11].zone = "福州"
      region.rooms[11].id = 335
      region.rooms[11].desc = "    天游峰为武夷第一胜地，山势陡峭，石阶因山而凿，极为险峻，山峰巍然屹立，登顶远眺，武夷山全景尽收眼底。只见大王玉女遥遥相望，默默伤情。"
      region.rooms[11].exits = "southdown"
      region.rooms[11].links = {}
        region.rooms[11].links.sd = {}
          region.rooms[11].links.sd.to = 334
          region.rooms[11].links.sd.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;w;w;w;nw"
      region.rooms[12].name = "天心岩"
      region.rooms[12].zone = "福州"
      region.rooms[12].id = 336
      region.rooms[12].desc = "    天心岩为武夷名胜，岩下永乐寺为天下著名禅林。山腰“大红袍”岩茶为天下极品，驰名海内外。"
      region.rooms[12].exits = "southeast"
      region.rooms[12].links = {}
        region.rooms[12].links.se = {}
          region.rooms[12].links.se.to = 334
          region.rooms[12].links.se.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly fz;w;w;w;w;w;nw;nw;nu"
      region.rooms[13].name = "闽浙古道"
      region.rooms[13].zone = "福州"
      region.rooms[13].id = 337
      region.rooms[13].desc = "    自古入闽无敞途。往来货运全靠肩挑背扛，逶迤入闽，车马不通。古道号称“三千八百坎”，宽仅三尺，青石砌就，行商头脚相继。下到坎底，就是延平府城了。"
      region.rooms[13].exits = "southdown|northdown"
      region.rooms[13].links = {}
        region.rooms[13].links.sd = {}
          region.rooms[13].links.sd.to = 338
          region.rooms[13].links.sd.con = ""
        region.rooms[13].links.nd = {}
          region.rooms[13].links.nd.to = 329
          region.rooms[13].links.nd.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly fz;w;w;w;w;w;nw;nw"
      region.rooms[14].name = "延平府"
      region.rooms[14].zone = "福州"
      region.rooms[14].id = 338
      region.rooms[14].desc = "    延平府廛市繁华，占溪山之雄，当水陆之会，向为入闽之咽喉。周遭山势壁立，深湍饶郭，易守难攻，为省城屏障，故关防严密不轻怠。隆武天子以国姓爷食栗此方，赐封延平郡王。"
      region.rooms[14].exits = "southeast|northup|southwest"
      region.rooms[14].links = {}
        region.rooms[14].links.nu = {}
          region.rooms[14].links.nu.to = 337
          region.rooms[14].links.nu.con = ""
        region.rooms[14].links.sw = {}
          region.rooms[14].links.sw.to = 339
          region.rooms[14].links.sw.con = ""
        region.rooms[14].links.se = {}
          region.rooms[14].links.se.to = 344
          region.rooms[14].links.se.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly fz;w;w;w;w;w;nw;nw;sw"
      region.rooms[15].name = "闽赣古道"
      region.rooms[15].zone = "福州"
      region.rooms[15].id = 339
      region.rooms[15].desc = "    福建境内数不尽的山坎相连。密林幽谷相继，终日不见天光。山中毒虫猛兽出没无常，行路艰辛。"
      region.rooms[15].exits = "northeast|southwest"
      region.rooms[15].links = {}
        region.rooms[15].links.ne = {}
          region.rooms[15].links.ne.to = 338
          region.rooms[15].links.ne.con = ""
        region.rooms[15].links.sw = {}
          region.rooms[15].links.sw.to = 340
          region.rooms[15].links.sw.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly fz;w;w;w;w;w;nw;nw;sw;sw"
      region.rooms[16].name = "闽赣古道"
      region.rooms[16].zone = "福州"
      region.rooms[16].id = 340
      region.rooms[16].desc = "    福建境内数不尽的山坎相连。密林幽谷相继，终日不见天光。山中毒虫猛兽出没无常，行路艰辛。路边有一年轻汉子倚在树上冷眼看着你。"
      region.rooms[16].exits = "westup|northeast"
      region.rooms[16].links = {}
        region.rooms[16].links.ne = {}
          region.rooms[16].links.ne.to = 339
          region.rooms[16].links.ne.con = ""
        region.rooms[16].links.wu = {}
          region.rooms[16].links.wu.to = 341
          region.rooms[16].links.wu.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly fz;w;w;w;w;w;nw;nw;sw;sw;wu"
      region.rooms[17].name = "闽赣古道"
      region.rooms[17].zone = "福州"
      region.rooms[17].id = 341
      region.rooms[17].desc = "    福建境内数不尽的山坎相连。密林幽谷相继，终日不见天光。山中毒虫猛兽出没无常，行路艰辛。一个粗豪汉子站在当道。"
      region.rooms[17].exits = "eastdown|westdown"
      region.rooms[17].links = {}
        region.rooms[17].links.ed = {}
          region.rooms[17].links.ed.to = 340
          region.rooms[17].links.ed.con = ""
        region.rooms[17].links.wd = {}
          region.rooms[17].links.wd.to = 342
          region.rooms[17].links.wd.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly fz;w;w;w;w;w;nw;nw;sw;sw;wu;wd"
      region.rooms[18].name = "闽赣古道"
      region.rooms[18].zone = "福州|衡阳"
      region.rooms[18].id = 342
      region.rooms[18].desc = "    进入江西，还是不尽的山坎和密林幽谷，终日不见天光。放眼山中毒虫猛兽出没无常，行路艰辛。一到这里就闻到一股腥风扑鼻而来。"
      region.rooms[18].exits = "northwest|eastup"
      region.rooms[18].links = {}
        region.rooms[18].links.nw = {}
          region.rooms[18].links.nw.to = 460
          region.rooms[18].links.nw.con = ""
        region.rooms[18].links.eu = {}
          region.rooms[18].links.eu.to = 341
          region.rooms[18].links.eu.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly fz;w;w;w;w;w;nw"
      region.rooms[19].name = "闽江"
      region.rooms[19].zone = "福州"
      region.rooms[19].id = 343
      region.rooms[19].desc = "    自延福门放江而下，两岸青山夹翠，游鱼泛波，小舟穿行险滩之中，耳畔哗哗水响，自延平到福州三百六十里水路，朝发夕至。"
      region.rooms[19].exits = "northwest|southeast"
      region.rooms[19].links = {}
        region.rooms[19].links.nw = {}
          region.rooms[19].links.nw.to = 338
          region.rooms[19].links.nw.con = ""
        region.rooms[19].links.se = {}
          region.rooms[19].links.se.to = 344
          region.rooms[19].links.se.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly fz;w;w;w;w;w"
      region.rooms[20].name = "闽中大道"
      region.rooms[20].zone = "福州"
      region.rooms[20].id = 344
      region.rooms[20].desc = "    你走在闽江北岸大道上。福建境内无山不青，无水不翠，山陡林深少行人，不禁让你惴惴。北面有股青烟冒起，似乎有家野店。"
      region.rooms[20].exits = "east|north|northwest"
      region.rooms[20].links = {}
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 346
          region.rooms[20].links.e.con = ""
        region.rooms[20].links.nw = {}
          region.rooms[20].links.nw.to = 343
          region.rooms[20].links.nw.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 345
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly fz;w;w;w;w;w;n"
      region.rooms[21].name = "酒肆"
      region.rooms[21].zone = "福州"
      region.rooms[21].id = 345
      region.rooms[21].desc = "    酒店门口一个酒招子半拉子挂着，店主人老蔡却不见了。两间茅屋的小店显得十分空落，只有一个青袍年轻憨子靠在酒炉上冷冷地瞧着你。"
      region.rooms[21].exits = "south"
      region.rooms[21].links = {}
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 344
          region.rooms[21].links.s.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly fz;w;w;w;w"
      region.rooms[22].name = "闽中大道"
      region.rooms[22].zone = "福州"
      region.rooms[22].id = 346
      region.rooms[22].desc = "    这里密迩城郊，来往行人也渐渐都了起来。福州的官话听起来刺耳难懂，可是抑扬顿挫，别有一番风味。"
      region.rooms[22].exits = "east|west"
      region.rooms[22].links = {}
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 344
          region.rooms[22].links.w.con = ""
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 347
          region.rooms[22].links.e.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly fz;w;w;w"
      region.rooms[23].name = "福州西门"
      region.rooms[23].zone = "福州"
      region.rooms[23].id = 347
      region.rooms[23].desc = "    这里是福州西门。出此门向西可达中原。"
      region.rooms[23].exits = "east|west"
      region.rooms[23].links = {}
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 346
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 348
          region.rooms[23].links.e.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly fz;w;w"
      region.rooms[24].name = "西门大街"
      region.rooms[24].zone = "福州"
      region.rooms[24].id = 348
      region.rooms[24].desc = "    青石板路笔直地伸展出去，直通西门。街北望去，一片的潋滟水色，街南却是一片丛林，佛号钟呤，悠远传音。"
      region.rooms[24].exits = "south|north|east|west"
      region.rooms[24].links = {}
        region.rooms[24].links.e = {}
          region.rooms[24].links.e.to = 351
          region.rooms[24].links.e.con = ""
        region.rooms[24].links.s = {}
          region.rooms[24].links.s.to = 349
          region.rooms[24].links.s.con = ""
        region.rooms[24].links.w = {}
          region.rooms[24].links.w.to = 347
          region.rooms[24].links.w.con = ""
        region.rooms[24].links.n = {}
          region.rooms[24].links.n.to = 350
          region.rooms[24].links.n.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly fz;w;w;s"
      region.rooms[25].name = "西禅寺"
      region.rooms[25].zone = "福州"
      region.rooms[25].id = 349
      region.rooms[25].desc = "    西禅寺始建于梁朝，寺中玉佛楼玉佛为整玉雕就，宝相庄严，从来香火不绝。香客往来，但有所求，多得灵验。"
      region.rooms[25].exits = "north"
      region.rooms[25].links = {}
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 348
          region.rooms[25].links.n.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly fz;w;w;n"
      region.rooms[26].name = "西湖"
      region.rooms[26].zone = "福州"
      region.rooms[26].id = 350
      region.rooms[26].desc = "    福州西湖原为灌溉疏浚之利而掘，汇一郭之水以为滋农时。而今，春水环绿岛，长柳戏游鱼，已有十分景致。"
      region.rooms[26].exits = "south"
      region.rooms[26].links = {}
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 348
          region.rooms[26].links.s.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly fz;w"
      region.rooms[27].name = "西大街"
      region.rooms[27].zone = "福州"
      region.rooms[27].id = 351
      region.rooms[27].desc = "    大街北面，一座结构宏伟的建筑前，左右石坛上各插着一根两丈多高的旗杆，杆上青旗飘扬。右首旗子用金线绣着一头张牙舞爪的狮子，旗风招展，奕奕如生。雄狮上头有一对黑丝线绣的蝙蝠展翅飞翔。左首旗子上写着“福威镖局”四个黑字，银钩铁划，刚劲非凡。"
      region.rooms[27].exits = "east|north|southup|west"
      region.rooms[27].links = {}
        region.rooms[27].links.e = {}
          region.rooms[27].links.e.to = 358
          region.rooms[27].links.e.con = ""
        region.rooms[27].links.n = {}
          region.rooms[27].links.n.to = 352
          region.rooms[27].links.n.con = ""
        region.rooms[27].links.w = {}
          region.rooms[27].links.w.to = 348
          region.rooms[27].links.w.con = ""
        region.rooms[27].links.su = {}
          region.rooms[27].links.su.to = 357
          region.rooms[27].links.su.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly fz;w;n"
      region.rooms[28].name = "福威镖局"
      region.rooms[28].zone = "福州"
      region.rooms[28].id = 352
      region.rooms[28].desc = "    朱漆大门上茶杯大小的铜钉闪闪发光，门顶匾额写着“福威镖局”四个金漆大字，下面横书“总号”两个小字。进门处两排长凳，分坐八名劲装汉子，个个腰板笔挺，显出一股英悍之气。"
      region.rooms[28].exits = "south|enter"
      region.rooms[28].links = {}
        region.rooms[28].links.s = {}
          region.rooms[28].links.s.to = 351
          region.rooms[28].links.s.con = ""
        region.rooms[28].links.enter = {}
          region.rooms[28].links.enter.to = 353
          region.rooms[28].links.enter.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly fz;w;n;enter"
      region.rooms[29].name = "福威镖局大院"
      region.rooms[29].zone = "福州"
      region.rooms[29].id = 353
      region.rooms[29].desc = "    大院里显得有些凌乱，趟子手和镖师们进进出出，似乎都在满地里忙碌着什么。一棵很大的榕树栽在院子中央，给火辣辣的福州带来一点凉爽。"
      region.rooms[29].exits = "north|out"
      region.rooms[29].links = {}
        region.rooms[29].links.out = {}
          region.rooms[29].links.out.to = 352
          region.rooms[29].links.out.con = ""
        region.rooms[29].links.n = {}
          region.rooms[29].links.n.to = 354
          region.rooms[29].links.n.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly fz;w;n;enter;n"
      region.rooms[30].name = "正厅"
      region.rooms[30].zone = "福州"
      region.rooms[30].id = 354
      region.rooms[30].desc = "    这里是福威镖局的正厅，几只太师椅一字排开，正中央坐着总镖头，手持烟袋杆正在闭目沉思。墙上挂着几幅字画和一把宝剑。"
      region.rooms[30].exits = "south|north|west"
      region.rooms[30].links = {}
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 353
          region.rooms[30].links.s.con = ""
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 355
          region.rooms[30].links.w.con = ""
        region.rooms[30].links.n = {}
          region.rooms[30].links.n.to = 356
          region.rooms[30].links.n.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly fz;w;n;enter;n;w"
      region.rooms[31].name = "内宅"
      region.rooms[31].zone = "福州"
      region.rooms[31].id = 355
      region.rooms[31].desc = "    福威镖局内宅装点的十分华贵。花梨木桌上放着一尊精致的振鬃长嘶的玉马，右首太师椅上好大一张豹皮把整张椅子遮得严严实实。"
      region.rooms[31].exits = "east"
      region.rooms[31].links = {}
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 354
          region.rooms[31].links.e.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly fz;w;n;enter;n;n"
      region.rooms[32].name = "福威镖局后院"
      region.rooms[32].zone = "福州"
      region.rooms[32].id = 356
      region.rooms[32].desc = "    镖局后院是平常镖师们打拳练功之所，除了几个木桩石锁外，别无它物。"
      region.rooms[32].exits = "south"
      region.rooms[32].links = {}
        region.rooms[32].links.s = {}
          region.rooms[32].links.s.to = 354
          region.rooms[32].links.s.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly fz;w;su"
      region.rooms[33].name = "福州乌山"
      region.rooms[33].zone = "福州"
      region.rooms[33].id = 357
      region.rooms[33].desc = "    福州古城三山，以城内乌山、于山和屏山三山恃立之故也。乌山上有乌塔。"
      region.rooms[33].exits = "northdown"
      region.rooms[33].links = {}
        region.rooms[33].links.nd = {}
          region.rooms[33].links.nd.to = 351
          region.rooms[33].links.nd.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly fz"
      region.rooms[34].name = "东街口"
      region.rooms[34].zone = "福州"
      region.rooms[34].id = 358
      region.rooms[34].desc = "    这里是福州的中心。向东通往鼓山，向南经泉州出海可去台湾，北去屏山，向西经延平府直达中原。街边沉沉郁郁的都是榕树，福州又称“榕城”即以其遍地植榕而名。    街上几个混混嬉皮笑脸地调戏过往行人。"
      region.rooms[34].exits = "south|east|north|west"
      region.rooms[34].links = {}
        region.rooms[34].links.e = {}
          region.rooms[34].links.e.to = 361
          region.rooms[34].links.e.con = ""
        region.rooms[34].links.w = {}
          region.rooms[34].links.w.to = 351
          region.rooms[34].links.w.con = ""
        region.rooms[34].links.s = {}
          region.rooms[34].links.s.to = 372
          region.rooms[34].links.s.con = ""
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 359
          region.rooms[34].links.n.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly fz;n"
      region.rooms[35].name = "北大街"
      region.rooms[35].zone = "福州"
      region.rooms[35].id = 359
      region.rooms[35].desc = "    街道两侧，榕木参天。福州盛夏苦热，广植榕树以纳凉爽，别名“榕城”。南面是一个大路口，北上就是屏山。"
      region.rooms[35].exits = "south|northup"
      region.rooms[35].links = {}
        region.rooms[35].links.s = {}
          region.rooms[35].links.s.to = 358
          region.rooms[35].links.s.con = ""
        region.rooms[35].links.nu = {}
          region.rooms[35].links.nu.to = 360
          region.rooms[35].links.nu.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly fz;n;nu"
      region.rooms[36].name = "福州屏山"
      region.rooms[36].zone = "福州"
      region.rooms[36].id = 360
      region.rooms[36].desc = "    屏山古称越王山，横亘福州城北，山下华林寺，构法考究。屏山上俯瞰榕城，历历如画。"
      region.rooms[36].exits = "southdown"
      region.rooms[36].links = {}
        region.rooms[36].links.sd = {}
          region.rooms[36].links.sd.to = 359
          region.rooms[36].links.sd.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly fz;e"
      region.rooms[37].name = "东大街"
      region.rooms[37].zone = "福州"
      region.rooms[37].id = 361
      region.rooms[37].desc = "    街道两侧，榕木参天。福州盛夏苦热，广植榕树以纳凉爽，别名“榕城”。北面是客店，南面通往山上。"
      region.rooms[37].exits = "east|north|southup|west"
      region.rooms[37].links = {}
        region.rooms[37].links.e = {}
          region.rooms[37].links.e.to = 366
          region.rooms[37].links.e.con = ""
        region.rooms[37].links.su = {}
          region.rooms[37].links.su.to = 362
          region.rooms[37].links.su.con = ""
        region.rooms[37].links.w = {}
          region.rooms[37].links.w.to = 358
          region.rooms[37].links.w.con = ""
        region.rooms[37].links.n = {}
          region.rooms[37].links.n.to = 363
          region.rooms[37].links.n.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly fz;e;su"
      region.rooms[38].name = "福州于山"
      region.rooms[38].zone = "福州"
      region.rooms[38].id = 362
      region.rooms[38].desc = "    于山因战国时于越族在此居住而得名。相传闽越王无诸曾于九月九日大宴于此，又称“九日山”，于山之麓的白塔，又称定光塔，系唐王审知为了向死去的父母报恩而建。登上白塔榕城历历如画。"
      region.rooms[38].exits = "northdown"
      region.rooms[38].links = {}
        region.rooms[38].links.nd = {}
          region.rooms[38].links.nd.to = 361
          region.rooms[38].links.nd.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly fz;e;n"
      region.rooms[39].name = "榕城驿"
      region.rooms[39].zone = "福州"
      region.rooms[39].id = 363
      region.rooms[39].desc = "    榕城驿是全省最大的客店，生意非常兴隆。外地游客多选择这里落脚，你可以在这里打听到本省的风土人情。店小二里里外外忙得团团转，福州的方言你是实在听不顺耳。还是上楼睡觉去。墙上挂着一个牌子(paizi)。"
      region.rooms[39].exits = "up|south|north"
      region.rooms[39].links = {}
        region.rooms[39].links.u = {}
          region.rooms[39].links.u.to = 365
          region.rooms[39].links.u.con = ""
        region.rooms[39].links.s = {}
          region.rooms[39].links.s.to = 361
          region.rooms[39].links.s.con = ""
        region.rooms[39].links.n = {}
          region.rooms[39].links.n.to = 364
          region.rooms[39].links.n.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly fz;e;n;n"
      region.rooms[40].name = "马厩"
      region.rooms[40].zone = "福州"
      region.rooms[40].id = 364
      region.rooms[40].desc = "    这是榕城驿的马厩，常年供应新鲜草料。福州民风淳朴，马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净，一直伺候到客人上路。马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。    马厩中堆放著几堆草料，正中有一口泔槽。"
      region.rooms[40].exits = "south"
      region.rooms[40].links = {}
        region.rooms[40].links.s = {}
          region.rooms[40].links.s.to = 363
          region.rooms[40].links.s.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly fz;e;n;u"
      region.rooms[41].name = "榕城驿二楼"
      region.rooms[41].zone = "福州"
      region.rooms[41].id = 365
      region.rooms[41].desc = "    这是一间很大的客房，陈设十分简陋。靠墙放了十几张小木床，不少客人正和衣而卧，满屋子都是呼呼的打酣声。你看到西边有张床是空的，就蹑手蹑脚地走了过去。"
      region.rooms[41].exits = "down"
      region.rooms[41].links = {}
        region.rooms[41].links.d = {}
          region.rooms[41].links.d.to = 363
          region.rooms[41].links.d.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly fz;e;e"
      region.rooms[42].name = "东小街"
      region.rooms[42].zone = "福州"
      region.rooms[42].id = 366
      region.rooms[42].desc = "    街道两侧，榕木参天。福州盛夏苦热，广植榕树以纳凉爽，别名“榕城”。东面就出城了，西面是城中心。"
      region.rooms[42].exits = "east|west"
      region.rooms[42].links = {}
        region.rooms[42].links.w = {}
          region.rooms[42].links.w.to = 361
          region.rooms[42].links.w.con = ""
        region.rooms[42].links.e = {}
          region.rooms[42].links.e.to = 367
          region.rooms[42].links.e.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly fz;e;e;e"
      region.rooms[43].name = "福州东门"
      region.rooms[43].zone = "福州"
      region.rooms[43].id = 367
      region.rooms[43].desc = "    东门外是福州平原。从这里看去，可以见到密密的丛林。出东门十里地就是鼓山了。"
      region.rooms[43].exits = "east|west"
      region.rooms[43].links = {}
        region.rooms[43].links.w = {}
          region.rooms[43].links.w.to = 366
          region.rooms[43].links.w.con = ""
        region.rooms[43].links.e = {}
          region.rooms[43].links.e.to = 368
          region.rooms[43].links.e.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly fz;e;e;e;e"
      region.rooms[44].name = "树林"
      region.rooms[44].zone = "福州"
      region.rooms[44].id = 368
      region.rooms[44].desc = "    你走在福州东门外密林中。林中时时传来虫鸟的啼鸣。北边林深处似乎有一小庙。东边一山，其形如鼓。卧在平坦平原上。"
      region.rooms[44].exits = "north|eastup|west"
      region.rooms[44].links = {}
        region.rooms[44].links.eu = {}
          region.rooms[44].links.eu.to = 370
          region.rooms[44].links.eu.con = ""
        region.rooms[44].links.w = {}
          region.rooms[44].links.w.to = 367
          region.rooms[44].links.w.con = ""
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 369
          region.rooms[44].links.n.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly fz;e;e;e;e;n"
      region.rooms[45].name = "无相庵"
      region.rooms[45].zone = "福州"
      region.rooms[45].id = 369
      region.rooms[45].desc = "    一个小小庵堂。"
      region.rooms[45].exits = "south"
      region.rooms[45].links = {}
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 368
          region.rooms[45].links.s.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly fz;e;e;e;e;eu"
      region.rooms[46].name = "鼓山"
      region.rooms[46].zone = "福州"
      region.rooms[46].id = 370
      region.rooms[46].desc = "    鼓山以山上有石形如鼓，扣之如擂鼓而得名，非只山势如鼓覆地。山上苍松滴翠，岩秀谷幽，风景秀丽，四季如春。有晋以来，即为“八闽二绝”之一。"
      region.rooms[46].exits = "north|westdown"
      region.rooms[46].links = {}
        region.rooms[46].links.wd = {}
          region.rooms[46].links.wd.to = 368
          region.rooms[46].links.wd.con = ""
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 371
          region.rooms[46].links.n.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly fz;e;e;e;e;eu;n"
      region.rooms[47].name = "涌泉寺"
      region.rooms[47].zone = "福州"
      region.rooms[47].id = 371
      region.rooms[47].desc = "    涌泉寺为闽中第一丛林。构筑宏伟，气势磅礴，工艺精巧，冠绝一时。寺东胜境灵源深处，悬崖峭壁，峥嵘奇巧，古树参天，宁静幽雅，其中千载碑林，多朱熹、蔡襄遗墨。寺北绝顶峰，远望东海烟波，近瞰闽江流带，福州平原一派田园风光尽收眼底。"
      region.rooms[47].exits = "south"
      region.rooms[47].links = {}
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 370
          region.rooms[47].links.s.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "fly fz;s"
      region.rooms[48].name = "南大街"
      region.rooms[48].zone = "福州"
      region.rooms[48].id = 372
      region.rooms[48].desc = "    街道两侧，榕木参天。福州盛夏苦热，广植榕树以纳凉爽，别名“榕城”。西面是府衙，东面是一家闽菜馆。"
      region.rooms[48].exits = "south|east|north|west"
      region.rooms[48].links = {}
        region.rooms[48].links.e = {}
          region.rooms[48].links.e.to = 374
          region.rooms[48].links.e.con = ""
        region.rooms[48].links.w = {}
          region.rooms[48].links.w.to = 373
          region.rooms[48].links.w.con = ""
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 375
          region.rooms[48].links.s.con = ""
        region.rooms[48].links.n = {}
          region.rooms[48].links.n.to = 358
          region.rooms[48].links.n.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly fz;s;w"
      region.rooms[49].name = "提督衙门"
      region.rooms[49].zone = "福州"
      region.rooms[49].id = 373
      region.rooms[49].desc = "    这里是衙门大门，两扇朱木大门紧紧关闭着。“肃静”“回避”的牌子分放两头石狮子的旁边。前面有一个大鼓，几名戈什哈站在门前。"
      region.rooms[49].exits = "east"
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 372
          region.rooms[49].links.e.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly fz;s;e"
      region.rooms[50].name = "味中味"
      region.rooms[50].zone = "福州"
      region.rooms[50].id = 374
      region.rooms[50].desc = "    提起“味中味”方圆百里无人不知。这里各式闽菜均是福州一绝。来游湖的人们都一定会来这里尝尝。整个大堂闹哄哄的挤满了各式人等。店小儿跑来跑去，忙着招呼客人。墙上挂着价格牌子(paizi)。"
      region.rooms[50].exits = "west"
      region.rooms[50].links = {}
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 372
          region.rooms[50].links.w.con = ""
    region.rooms[51] = {}
      region.rooms[51].path = "fly fz;s;s"
      region.rooms[51].name = "南门兜"
      region.rooms[51].zone = "福州"
      region.rooms[51].id = 375
      region.rooms[51].desc = "    南门兜中央有一株巨大古榕，根繁叶茂，浓荫遮盖树亩，将整个街口遮闭严实不漏日光。大榕树下有一小洞(dong)，深藏根下。"
      region.rooms[51].exits = "south|east|north|west"
      region.rooms[51].links = {}
        region.rooms[51].links.e = {}
          region.rooms[51].links.e.to = 376
          region.rooms[51].links.e.con = ""
        region.rooms[51].links.w = {}
          region.rooms[51].links.w.to = 377
          region.rooms[51].links.w.con = ""
        region.rooms[51].links.s = {}
          region.rooms[51].links.s.to = 384
          region.rooms[51].links.s.con = ""
        region.rooms[51].links.n = {}
          region.rooms[51].links.n.to = 372
          region.rooms[51].links.n.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "fly fz;s;s;e"
      region.rooms[52].name = "校场"
      region.rooms[52].zone = "福州"
      region.rooms[52].id = 376
      region.rooms[52].desc = "    福州校场为福建水师校场。场中点将楼上高挂“施”字黑锈金边帅旗，刀枪耀日生辉。水师提督施琅施大人亲率十万雄兵，隔海相望，壮心不已。"
      region.rooms[52].exits = "west"
      region.rooms[52].links = {}
        region.rooms[52].links.w = {}
          region.rooms[52].links.w.to = 375
          region.rooms[52].links.w.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "fly fz;s;s;w"
      region.rooms[53].name = "石桥"
      region.rooms[53].zone = "福州"
      region.rooms[53].id = 377
      region.rooms[53].desc = "    这是城里一条普普通通的石桥。大概总有几百年历史了，桥侧生满青苔，桥下有小孩戏水，岸边洗衣的母亲大声呵斥着自己的孩子。"
      region.rooms[53].exits = "east|west"
      region.rooms[53].links = {}
        region.rooms[53].links.e = {}
          region.rooms[53].links.e.to = 375
          region.rooms[53].links.e.con = ""
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 378
          region.rooms[53].links.w.con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "fly fz;s;s;w;w"
      region.rooms[54].name = "向阳巷"
      region.rooms[54].zone = "福州"
      region.rooms[54].id = 378
      region.rooms[54].desc = "    这里是福州城西向阳巷。北面有一所破败的宅子。西面有一家杂货铺，专卖女人家用的东西，男人不可以进去。"
      region.rooms[54].exits = "north|east|west"
      region.rooms[54].links = {}
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 377
          region.rooms[54].links.e.con = ""
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 379
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.n = {}
          region.rooms[54].links.n.to = 380
          region.rooms[54].links.n.con = ""
    region.rooms[55] = {}
      region.rooms[55].path = "fly fz;s;s;w;w;w"
      region.rooms[55].name = "杂货铺"
      region.rooms[55].zone = "福州"
      region.rooms[55].id = 379
      region.rooms[55].desc = "    这里是一家专卖女人用的东西的小铺子。"
      region.rooms[55].exits = "east"
      region.rooms[55].links = {}
        region.rooms[55].links.e = {}
          region.rooms[55].links.e.to = 378
          region.rooms[55].links.e.con = ""
    region.rooms[56] = {}
      region.rooms[56].path = "fly fz;s;s;w;w;n"
      region.rooms[56].name = "向阳老宅"
      region.rooms[56].zone = "福州"
      region.rooms[56].id = 380
      region.rooms[56].desc = "    这里是福威镖局总镖头林震南在福建的旧居。室内的家具横七竖八地倒在地上。房间的一角结着一张蜘蛛网，屋里到处是尘土，显然是已经很久没有人住了。房间的尽头有一扇门(men)，但已被坍塌的砖瓦挡住了。"
      region.rooms[56].exits = "south"
      region.rooms[56].links = {}
        region.rooms[56].links.s = {}
          region.rooms[56].links.s.to = 378
          region.rooms[56].links.s.con = ""
        region.rooms[56].links["break men;n"] = {}
          region.rooms[56].links["break men;n"].to = 381
          region.rooms[56].links["break men;n"].con = ""
    region.rooms[57] = {}
      region.rooms[57].path = "fly fz;s;s;w;w;n;break men;n"
      region.rooms[57].name = "老宅后院"
      region.rooms[57].zone = "福州"
      region.rooms[57].id = 381
      region.rooms[57].desc = "    这里是向阳老宅的后院。满地是发出朽烂霉气的落叶。院子的中央有一口井，井台(tai) 上刻着些字。院子南面有一扇门(men)，但已被坍塌的砖瓦挡住了。"
      region.rooms[57].exits = "down"
      region.rooms[57].links = {}
        region.rooms[57].links["break men;s"] = {}
          region.rooms[57].links["break men;s"].to = 380
          region.rooms[57].links["break men;s"].con = ""
        region.rooms[57].links.d = {}
          region.rooms[57].links.d.to = 382
          region.rooms[57].links.d.con = ""
    region.rooms[58] = {}
      region.rooms[58].path = "fly fz;s;s;w;w;n;break men;n;d"
      region.rooms[58].name = "井中"
      region.rooms[58].zone = "福州"
      region.rooms[58].id = 382
      region.rooms[58].desc = "    这是在一口枯井中。光线极暗，什么也看不清。"
      region.rooms[58].exits = "up|down"
      region.rooms[58].links = {}
        region.rooms[58].links.u = {}
          region.rooms[58].links.u.to = 381
          region.rooms[58].links.u.con = ""
        region.rooms[58].links.d = {}
          region.rooms[58].links.d.to = 383
          region.rooms[58].links.d.con = ""
        region.rooms[58].links["use fire;zuan"] = {}
          region.rooms[58].links["use fire;zuan"].to = 2605
          region.rooms[58].links["use fire;zuan"].con = ""
    region.rooms[59] = {}
      region.rooms[59].path = "fly fz;s;s;w;w;n;break men;n;d;d"
      region.rooms[59].name = "井底"
      region.rooms[59].zone = "福州"
      region.rooms[59].id = 383
      region.rooms[59].desc = "    这是在一口枯井的井底。光线极暗，什么也看不清。"
      region.rooms[59].exits = "up"
      region.rooms[59].links = {}
        region.rooms[59].links.u = {}
          region.rooms[59].links.u.to = 382
          region.rooms[59].links.u.con = ""
    region.rooms[60] = {}
      region.rooms[60].path = "fly fz;s;s;s"
      region.rooms[60].name = "福州南门"
      region.rooms[60].zone = "福州"
      region.rooms[60].id = 384
      region.rooms[60].desc = "    这里是福州南门。"
      region.rooms[60].exits = "south|north"
      region.rooms[60].links = {}
        region.rooms[60].links.s = {}
          region.rooms[60].links.s.to = 385
          region.rooms[60].links.s.con = ""
        region.rooms[60].links.n = {}
          region.rooms[60].links.n.to = 375
          region.rooms[60].links.n.con = ""
    region.rooms[61] = {}
      region.rooms[61].path = "fly fz;s;s;s;s"
      region.rooms[61].name = "中洲桥"
      region.rooms[61].zone = "福州"
      region.rooms[61].id = 385
      region.rooms[61].desc = "    中洲桥横越闽江，桥面平整，桥下水花喧闹。中洲为一小岛，尽是水上人家。"
      region.rooms[61].exits = "south|north"
      region.rooms[61].links = {}
        region.rooms[61].links.s = {}
          region.rooms[61].links.s.to = 386
          region.rooms[61].links.s.con = ""
        region.rooms[61].links.n = {}
          region.rooms[61].links.n.to = 384
          region.rooms[61].links.n.con = ""
    region.rooms[62] = {}
      region.rooms[62].path = "fly fz;s;s;s;s;s"
      region.rooms[62].name = "莆仙平原"
      region.rooms[62].zone = "福州"
      region.rooms[62].id = 386
      region.rooms[62].desc = "    你走在莆仙平原上。这里物产丰饶，人烟稠密，望北就是福州府城了。往南就进入闽南。"
      region.rooms[62].exits = "south|north"
      region.rooms[62].links = {}
        region.rooms[62].links.s = {}
          region.rooms[62].links.s.to = 387
          region.rooms[62].links.s.con = ""
        region.rooms[62].links.n = {}
          region.rooms[62].links.n.to = 385
          region.rooms[62].links.n.con = ""
    region.rooms[63] = {}
      region.rooms[63].path = "fly fz;s;s;s;s;s;s"
      region.rooms[63].name = "大路"
      region.rooms[63].zone = "福州|泉州"
      region.rooms[63].id = 387
      region.rooms[63].links = {}
        region.rooms[63].links.e = {}
          region.rooms[63].links.e.to = 389
          region.rooms[63].links.e.con = ""
        region.rooms[63].links.s = {}
          region.rooms[63].links.s.to = 388
          region.rooms[63].links.s.con = ""
        region.rooms[63].links.n = {}
          region.rooms[63].links.n.to = 386
          region.rooms[63].links.n.con = ""
      region.rooms[63].exits = "south|east|north"
      region.rooms[63].desc = "    你走在一条大路上。时值春日，路旁的山坡上开满了金黄色的油菜花。向北是福州城，向南则是泉州。东面有一个供路人休息的小茶亭。"
    region.rooms[64] = {}
      region.rooms[64].path = "fly fz;s;s;s;s;s;s;s"
      region.rooms[64].name = "泉州北门"
      region.rooms[64].zone = "福州|泉州"
      region.rooms[64].id = 388
      region.rooms[64].links = {}
        region.rooms[64].links.s = {}
          region.rooms[64].links.s.to = 391
          region.rooms[64].links.s.con = ""
        region.rooms[64].links.n = {}
          region.rooms[64].links.n.to = 387
          region.rooms[64].links.n.con = ""
      region.rooms[64].exits = "south|north"
      region.rooms[64].desc = "    这里是南方第一港泉州的北门。出此门向北可抵中原。"
    region.rooms[65] = {}
      region.rooms[65].path = "fly fz;s;s;w;w;n;break men;n;d;use fire;zuan"
      region.rooms[65].name = "密道"
      region.rooms[65].zone = "福州"
      region.rooms[65].id = 2605
      region.rooms[65].desc = "    这是水井里的一个密道。周围都是些机关，只有出口很明显在哪里。湿漉漉的墙壁上有四块石板，分别刻着１、２、３、４。旁边还有一个铁板(tieban)扔在地上。"
      region.rooms[65].exits = "out"
      region.rooms[65].links = {}
        region.rooms[65].links.enter = {}
          region.rooms[65].links.enter.to = 2606
          region.rooms[65].links.enter.con = "press:"
        region.rooms[65].links.out = {}
          region.rooms[65].links.out.to = 382
          region.rooms[65].links.out.con = ""
    region.rooms[66] = {}
      region.rooms[66].path = "fly fz;s;s;w;w;n;break men;n;d;use fire;zuan;|!press::enter|"
      region.rooms[66].name = "密室"
      region.rooms[66].zone = "福州"
      region.rooms[66].id = 2606
      region.rooms[66].desc = "    这是一间黑黢黢的小房间，墙上的砖头(zhuan)已经掉渣子了，房梁(liang)也已经朽烂不堪。墙脚处有一个铁箱子，上面积满了尘土。"
      region.rooms[66].exits = "out"
      region.rooms[66].links = {}
        region.rooms[66].links["climb xiang;jump liang"] = {}
          region.rooms[66].links["climb xiang;jump liang"].to = 2607
          region.rooms[66].links["climb xiang;jump liang"].con = ""
        region.rooms[66].links.out = {}
          region.rooms[66].links.out.to = 2605
          region.rooms[66].links.out.con = ""
    region.rooms[67] = {}
      region.rooms[67].path = "fly fz;s;s;w;w;n;break men;n;d;use fire;zuan;|!press::enter|;climb xiang;jump liang"
      region.rooms[67].name = "密室房梁"
      region.rooms[67].zone = "福州"
      region.rooms[67].id = 2607
      region.rooms[67].desc = "    你现在在密室的房梁上四下观瞧，周围都是些烂木头破砖瓦。突然你瞟见犄角旮旯处有一件袈裟。"
      region.rooms[67].exits = "down"
      region.rooms[67].links = {}
        region.rooms[67].links.d = {}
          region.rooms[67].links.d.to = 2606
          region.rooms[67].links.d.con = ""
  region.center = 358
return region