local region = {}
  region.cmd = "|!c:fire:fly fz|;s;s;w;w;n;break men;n;d;use fire;zuan"
  region.name = "福州1"
  region.id = "fz1"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "|!c:fire:fly fz|;s;s;w;w;n;break men;n;d;use fire;zuan"
      region.rooms[1].name = "密道"
      region.rooms[1].zone = "福州"
      region.rooms[1].id = 2605
      region.rooms[1].desc = "    这是水井里的一个密道。周围都是些机关，只有出口很明显在哪里。湿漉漉的墙壁上有四块石板，分别刻着１、２、３、４。旁边还有一个铁板(tieban)扔在地上。"
      region.rooms[1].exits = "out"
      region.rooms[1].links = {}
        region.rooms[1].links.enter = {}
          region.rooms[1].links.enter.to = 2606
          region.rooms[1].links.enter.con = "press:"
        region.rooms[1].links.out = {}
          region.rooms[1].links.out.to = 382
          region.rooms[1].links.out.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "|!c:fire:fly fz|;s;s;w;w;n;break men;n;d;use fire;zuan;|!press::enter|"
      region.rooms[2].name = "密室"
      region.rooms[2].zone = "福州"
      region.rooms[2].id = 2606
      region.rooms[2].desc = "    这是一间黑黢黢的小房间，墙上的砖头(zhuan)已经掉渣子了，房梁(liang)也已经朽烂不堪。墙脚处有一个铁箱子，上面积满了尘土。"
      region.rooms[2].exits = "out"
      region.rooms[2].links = {}
        region.rooms[2].links["climb xiang;jump liang"] = {}
          region.rooms[2].links["climb xiang;jump liang"].to = 2607
          region.rooms[2].links["climb xiang;jump liang"].con = ""
        region.rooms[2].links.out = {}
          region.rooms[2].links.out.to = 2605
          region.rooms[2].links.out.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "|!c:fire:fly fz|;s;s;w;w;n;break men;n;d;use fire;zuan;|!press::enter|;climb xiang;jump liang"
      region.rooms[3].name = "密室房梁"
      region.rooms[3].zone = "福州"
      region.rooms[3].id = 2607
      region.rooms[3].desc = "    你现在在密室的房梁上四下观瞧，周围都是些烂木头破砖瓦。突然你瞟见犄角旮旯处有一件袈裟。"
      region.rooms[3].exits = "down"
      region.rooms[3].links = {}
        region.rooms[3].links.d = {}
          region.rooms[3].links.d.to = 2606
          region.rooms[3].links.d.con = ""
  region.center = 2605
return region