local region = {}
  region.cmd = "fly gw"
  region.name = "关外"
  region.id = "gw"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly gw;s;s;s;sw;sw;s;sw;sw;sw;se"
      region.rooms[1].name = "老龙头"
      region.rooms[1].zone = "北京|关外"
      region.rooms[1].id = 1071
      region.rooms[1].desc = "    老龙头是万里长城最东端。澄海楼巍峨高踞城头，楼上“雄襟万里”的横匾居高临下，直俯大海。自澄海楼筑有一石城逐级而下伸入大海，站在石城终端楼平台上四眺，海天一色，无边无际，气象万千。"
      region.rooms[1].exits = "northwest|southwest"
      region.rooms[1].links = {}
        region.rooms[1].links.nw = {}
          region.rooms[1].links.nw.to = 1555
          region.rooms[1].links.nw.con = ""
        region.rooms[1].links.sw = {}
          region.rooms[1].links.sw.to = 1070
          region.rooms[1].links.sw.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly gw;s;s;s;sw;sw;s;sw;sw;sw"
      region.rooms[2].name = "山海关"
      region.rooms[2].zone = "关外"
      region.rooms[2].id = 1555
      region.rooms[2].links = {}
        region.rooms[2].links.ne = {}
          region.rooms[2].links.ne.to = 1556
          region.rooms[2].links.ne.con = ""
        region.rooms[2].links.se = {}
          region.rooms[2].links.se.to = 1071
          region.rooms[2].links.se.con = ""
      region.rooms[2].exits = "southeast|northeast"
      region.rooms[2].desc = "    这里就是万里长城最东面的重要关口--山海关。这里地势险要，自古就是关外通往中原的必经之地。站在关楼上北望，角山，古堡，烽火台历历在目，南沿长城远眺，直深入海的老龙头依稀可见。城楼二楼上悬挂着一块巨幅横匾(bian)。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly gw;s;s;s;sw;sw;s;sw;sw"
      region.rooms[3].name = "官道"
      region.rooms[3].zone = "关外"
      region.rooms[3].id = 1556
      region.rooms[3].links = {}
        region.rooms[3].links.ne = {}
          region.rooms[3].links.ne.to = 1557
          region.rooms[3].links.ne.con = ""
        region.rooms[3].links.sw = {}
          region.rooms[3].links.sw.to = 1555
          region.rooms[3].links.sw.con = ""
      region.rooms[3].exits = "northeast|southwest"
      region.rooms[3].desc = "    这里是通往关外的官道，几米宽的大道，全部由黄土铺成，可并行三四辆马车而不显拥挤。这里是进出关口的必经之路，路上三俩成群的行人都是往来贩运皮货，药材的生意人。偶尔有身着官兵骑马飞驰而过。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly gw;s;s;s;sw;sw;s;sw"
      region.rooms[4].name = "官道"
      region.rooms[4].zone = "关外"
      region.rooms[4].id = 1557
      region.rooms[4].links = {}
        region.rooms[4].links.ne = {}
          region.rooms[4].links.ne.to = 1558
          region.rooms[4].links.ne.con = ""
        region.rooms[4].links.sw = {}
          region.rooms[4].links.sw.to = 1556
          region.rooms[4].links.sw.con = ""
      region.rooms[4].exits = "northeast|southwest"
      region.rooms[4].desc = "    这里是通往关外的官道，几米宽的大道，全部由黄土铺成，可并行三四辆马车而不显拥挤。这里是进出关口的必经之路，路上三俩成群的行人都是往来贩运皮货，药材的生意人。偶尔有身着官兵骑马飞驰而过。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly gw;s;s;s;sw;sw;s"
      region.rooms[5].name = "官道"
      region.rooms[5].zone = "关外"
      region.rooms[5].id = 1558
      region.rooms[5].links = {}
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 1559
          region.rooms[5].links.n.con = ""
        region.rooms[5].links.sw = {}
          region.rooms[5].links.sw.to = 1557
          region.rooms[5].links.sw.con = ""
      region.rooms[5].exits = "north|southwest"
      region.rooms[5].desc = "    这里是通往关外的官道，几米宽的大道，全部由黄土铺成，可并行三四辆马车而不显拥挤。这里是进出关口的必经之路，路上三俩成群的行人都是往来贩运皮货，药材的生意人。偶尔有身着官兵骑马飞驰而过。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly gw;s;s;s;sw;sw"
      region.rooms[6].name = "宁远"
      region.rooms[6].zone = "关外"
      region.rooms[6].id = 1559
      region.rooms[6].links = {}
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 1558
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.ne = {}
          region.rooms[6].links.ne.to = 1560
          region.rooms[6].links.ne.con = ""
      region.rooms[6].exits = "south|northeast"
      region.rooms[6].desc = "    这里是关外驻防的军事重镇。城高河宽，守备森严，城楼上不但有大量的官兵驻防，甚至还有几门红衣火炮，架设其上。城门旁几名官兵正在检察来往行人的物品，不时传来几声叱骂之声。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly gw;s;s;s;sw"
      region.rooms[7].name = "大道"
      region.rooms[7].zone = "关外"
      region.rooms[7].id = 1560
      region.rooms[7].links = {}
        region.rooms[7].links.ne = {}
          region.rooms[7].links.ne.to = 1561
          region.rooms[7].links.ne.con = ""
        region.rooms[7].links.sw = {}
          region.rooms[7].links.sw.to = 1559
          region.rooms[7].links.sw.con = ""
      region.rooms[7].exits = "northeast|southwest"
      region.rooms[7].desc = "    你走在一条碎石铺成的大道上，道两旁种着笔直通天的白杨树，放眼向两侧望去，全是无边无际的田野，天边处仿佛有几座低矮的丘陵，为平坦的大地增加了几许柔和的曲线。路上行人渐渐稀少起来。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly gw;s;s;s"
      region.rooms[8].name = "大道"
      region.rooms[8].zone = "关外"
      region.rooms[8].id = 1561
      region.rooms[8].links = {}
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 1562
          region.rooms[8].links.n.con = ""
        region.rooms[8].links.sw = {}
          region.rooms[8].links.sw.to = 1560
          region.rooms[8].links.sw.con = ""
      region.rooms[8].exits = "north|southwest"
      region.rooms[8].desc = "    你走在一条碎石铺成的大道上，道两旁种着笔直通天的白杨树，放眼向两侧望去，全是无边无际的田野，天边处仿佛有几座低矮的丘陵，为平坦的大地增加了几许柔和的曲线。路上行人渐渐稀少起来。天气也渐渐变凉了。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly gw;s;s"
      region.rooms[9].name = "大道"
      region.rooms[9].zone = "关外"
      region.rooms[9].id = 1562
      region.rooms[9].links = {}
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 1561
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 1563
          region.rooms[9].links.n.con = ""
      region.rooms[9].exits = "south|north"
      region.rooms[9].desc = "    你走在一条碎石铺成的大道上，道两旁种着笔直通天的白杨树，放眼向两侧望去，全是无边无际的田野，天边处仿佛有几座低矮的丘陵，为平坦的大地增加了几许柔和的曲线。路上渐渐的出现了一些积雪。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly gw;s"
      region.rooms[10].name = "大道"
      region.rooms[10].zone = "关外"
      region.rooms[10].id = 1563
      region.rooms[10].links = {}
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 1562
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 1564
          region.rooms[10].links.n.con = ""
      region.rooms[10].exits = "south|north"
      region.rooms[10].desc = "    你走在一条碎石铺成的大道上，道两旁种着笔直通天的白杨树，放眼向两侧望去，全是无边无际的田野，天边处仿佛有几座低矮的丘陵，为平坦的大地增加了几许柔和的曲线。呼啸而过的狂风冻得人直打哆嗦。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly gw"
      region.rooms[11].name = "大道"
      region.rooms[11].zone = "关外"
      region.rooms[11].id = 1564
      region.rooms[11].links = {}
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 1563
          region.rooms[11].links.s.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 1565
          region.rooms[11].links.n.con = ""
      region.rooms[11].exits = "south|north"
      region.rooms[11].desc = "    你走在一条碎石铺成的大道上。四周的田野已经被积雪覆盖，放眼望去发现自己已经置身于无边无际的雪原中。狂风夹杂着雪花呼啸而过，冻得人浑身发抖。北面的天边似乎有一缕炊烟升起。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly gw;n"
      region.rooms[12].name = "木桥"
      region.rooms[12].zone = "关外"
      region.rooms[12].id = 1565
      region.rooms[12].links = {}
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 1564
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 1566
          region.rooms[12].links.n.con = ""
      region.rooms[12].exits = "south|north"
      region.rooms[12].desc = "    这是一座年久失修的破木桥，由几根树干捆扎而成。下面的河水早以结成坚冰。这里本是赫图阿拉城的护城河，现已废弃不用了。河岸北面是用黄土堆成的城墙，很多处都已坍塌。由此向北就是赫图阿拉城了。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly gw;n;n"
      region.rooms[13].name = "南城"
      region.rooms[13].zone = "关外"
      region.rooms[13].id = 1566
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 1565
          region.rooms[13].links.s.con = ""
        region.rooms[13].links.w = {}
          region.rooms[13].links.w.to = 1567
          region.rooms[13].links.w.con = ""
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 1568
          region.rooms[13].links.n.con = ""
      region.rooms[13].exits = "south|north|west"
      region.rooms[13].desc = "    这里是用黄土铺就的街道，街上的行人不多，看起来很冷清。偶尔有几个身着异域服饰的行人走过，看起来是满族，鲜祖的居民。西面有一座低埃的土房，门口挂着一个写满鲜文的幌子，还传来阵阵的肉香，看起来象一个小饭馆。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly gw;n;n;w"
      region.rooms[14].name = "香肉馆"
      region.rooms[14].zone = "关外"
      region.rooms[14].id = 1567
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 1566
          region.rooms[14].links.e.con = ""
      region.rooms[14].exits = "east"
      region.rooms[14].desc = "    这是一间很小的狗肉馆，屋内有一个很大的土炕，几乎占去了房间的一半。炕中是一个火灶，上架一口大铁锅，香喷喷的热气从锅中不断冒出。饭馆的老板坐在锅旁，不断的给客人盛上一碗碗热腾腾的肉汤。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly gw;n;n;n"
      region.rooms[15].name = "集市"
      region.rooms[15].zone = "关外"
      region.rooms[15].id = 1568
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 1570
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 1566
          region.rooms[15].links.s.con = ""
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 1569
          region.rooms[15].links.w.con = ""
        region.rooms[15].links.n = {}
          region.rooms[15].links.n.to = 1571
          region.rooms[15].links.n.con = ""
      region.rooms[15].exits = "south|east|north|west"
      region.rooms[15].desc = "    这里是城中一片开阔的广场，乃是来往客商交易毛皮，药材以及其它杂物的集市。由于附近方圆百里仅有这么一个集市，因此这里的人最多，货物也最全。不同的服饰，不同的语言都可以在这里看到，听到。杂乱的人群中传出各种吆喝，叫卖的声音。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly gw;n;n;n;w"
      region.rooms[16].name = "马厩"
      region.rooms[16].zone = "关外"
      region.rooms[16].id = 1569
      region.rooms[16].links = {}
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 1568
          region.rooms[16].links.e.con = ""
      region.rooms[16].exits = "east"
      region.rooms[16].desc = "    这是关外的马厩，关外苦寒之地，颇乏新鲜草料。但东北大汉惯能吃苦，马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净，一直伺候到客人上路。马厩雪披下的木柱上钉着一块破木牌(paizi)。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly gw;n;n;n;e"
      region.rooms[17].name = "东城"
      region.rooms[17].zone = "关外"
      region.rooms[17].id = 1570
      region.rooms[17].links = {}
        region.rooms[17].links.ne = {}
          region.rooms[17].links.ne.to = 1575
          region.rooms[17].links.ne.con = ""
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 1578
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 1574
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 1568
          region.rooms[17].links.w.con = ""
      region.rooms[17].exits = "south|east|northeast|west"
      region.rooms[17].desc = "    这里是用黄土铺就的街道，街上的行人不多，看起来很冷清。偶尔有几个身着异域服饰的行人走过，看起来是满族，鲜祖的居民。西面传来嘈杂的叫卖声。南面是一排黄泥垒成的土房，里面有嬉笑的声音。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly gw;n;n;n;n"
      region.rooms[18].name = "北城"
      region.rooms[18].zone = "关外"
      region.rooms[18].id = 1571
      region.rooms[18].links = {}
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 1568
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 1572
          region.rooms[18].links.w.con = ""
      region.rooms[18].exits = "south|west"
      region.rooms[18].desc = "    这里是用黄土铺就的街道，街上的行人不多，看起来很冷清。偶尔有几个身着异域服饰的行人走过，看起来是满族，鲜祖的居民。西面有一条幽深的小巷，不知通向何处。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly gw;n;n;n;n;w"
      region.rooms[19].name = "小巷"
      region.rooms[19].zone = "关外"
      region.rooms[19].id = 1572
      region.rooms[19].links = {}
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 1571
          region.rooms[19].links.e.con = ""
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 1573
          region.rooms[19].links.s.con = ""
      region.rooms[19].exits = "south|east"
      region.rooms[19].desc = "    这是一个僻静幽深的小巷，四周寂静无声，一个人影也没有。长长的石板路上落了一层厚厚的积雪，踩在脚下发出“咯吱”的响声。小巷的尽头有一座土屋。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly gw;n;n;n;n;w;s"
      region.rooms[20].name = "小土屋"
      region.rooms[20].zone = "关外"
      region.rooms[20].id = 1573
      region.rooms[20].links = {}
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 1572
          region.rooms[20].links.n.con = ""
      region.rooms[20].exits = "north"
      region.rooms[20].desc = "    这是一座用黄土垒成的小屋，屋内打扫的很干净。四周的墙壁上挂满了各种棍子，钎子，开山斧，小锯子等工具，看来似乎是采参所用的工具。屋内西面的火炕上坐着一位上了年纪的老人，正在吸着旱烟袋。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly gw;n;n;n;e;s"
      region.rooms[21].name = "土窑馆"
      region.rooms[21].zone = "关外"
      region.rooms[21].id = 1574
      region.rooms[21].links = {}
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 1570
          region.rooms[21].links.n.con = ""
      region.rooms[21].exits = "north"
      region.rooms[21].desc = "    一迈进这间小房，一股脂粉混合着大蒜的味道扑鼻而来，差点把你呛了一个跟头。屋内点着很多蜡烛和灯笼，把四壁照得通红。很多穿着破烂的汉子，一手搂着姑娘，一个握着酒壶，正在高谈阔论。一个肥胖的老鸦一遍招待着客人，一遍大声催促的这里的伴当和姑娘们。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly gw;n;n;n;e;ne"
      region.rooms[22].name = "荒路"
      region.rooms[22].zone = "关外"
      region.rooms[22].id = 1575
      region.rooms[22].links = {}
        region.rooms[22].links.ne = {}
          region.rooms[22].links.ne.to = 1576
          region.rooms[22].links.ne.con = ""
        region.rooms[22].links.sw = {}
          region.rooms[22].links.sw.to = 1570
          region.rooms[22].links.sw.con = ""
      region.rooms[22].exits = "northeast|southwest"
      region.rooms[22].desc = "    这是城东的一条荒路，路旁杂乱的长着齐膝的荒草，远近荒无一人。两旁干枯的老树上落满了成群的乌鸦，凄凉的鸣叫声在荒野上远远传去，一派凄凉的景象。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly gw;n;n;n;e;ne;ne"
      region.rooms[23].name = "荒路"
      region.rooms[23].zone = "关外"
      region.rooms[23].id = 1576
      region.rooms[23].links = {}
        region.rooms[23].links.enter = {}
          region.rooms[23].links.enter.to = 1577
          region.rooms[23].links.enter.con = ""
        region.rooms[23].links.sw = {}
          region.rooms[23].links.sw.to = 1575
          region.rooms[23].links.sw.con = ""
      region.rooms[23].exits = "enter|southwest"
      region.rooms[23].desc = "    这是城东的一条荒路，路旁杂乱的长着齐膝的荒草，远近荒无一人。两旁干枯的老树上落满了成群的乌鸦，凄凉的鸣叫声在荒野上远远传去，一派凄凉的景象。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly gw;n;n;n;e;ne;ne;enter"
      region.rooms[24].name = "山神庙"
      region.rooms[24].zone = "关外"
      region.rooms[24].id = 1577
      region.rooms[24].links = {}
        region.rooms[24].links.out = {}
          region.rooms[24].links.out.to = 1576
          region.rooms[24].links.out.con = ""
      region.rooms[24].exits = "out"
      region.rooms[24].desc = "    这是一个用木板和石头垒成的小庙，庙前地上散落着一些然过的灰烬。庙里供奉着山神爷老把头的灵位(lingwei)。传说他是所有采参人的祖师爷，所以每个进山挖参的参客都要来这里祭拜，希望能得到他老人家的保佑。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly gw;n;n;n;e;e"
      region.rooms[25].name = "雪地"
      region.rooms[25].zone = "关外"
      region.rooms[25].id = 1578
      region.rooms[25].links = {}
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 1570
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.ne = {}
          region.rooms[25].links.ne.to = 1579
          region.rooms[25].links.ne.con = ""
      region.rooms[25].exits = "northeast|west"
      region.rooms[25].desc = "    这里是一片白茫茫的雪地，一眼望不到边际。四周一个人影也没有，厚厚的积雪踩起来发出咯吱的响声，大地上留下一串孤独的脚印。寒冷的北风呼啸而过，吹得脸生痛。暗淡的太阳低悬在天边，显得那么苍白。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly gw;n;n;n;e;e;ne"
      region.rooms[26].name = "雪地"
      region.rooms[26].zone = "关外"
      region.rooms[26].id = 1579
      region.rooms[26].links = {}
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 1580
          region.rooms[26].links.e.con = ""
        region.rooms[26].links.sw = {}
          region.rooms[26].links.sw.to = 1578
          region.rooms[26].links.sw.con = ""
      region.rooms[26].exits = "east|southwest"
      region.rooms[26].desc = "    这里是一片白茫茫的雪地，一眼望不到边际。四周一个人影也没有，厚厚的积雪踩起来发出咯吱的响声，大地上留下一串孤独的脚印。寒冷的北风呼啸而过，吹得脸生痛。暗淡的太阳低悬在天边，显得那么苍白。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly gw;n;n;n;e;e;ne;e"
      region.rooms[27].name = "雪地"
      region.rooms[27].zone = "关外"
      region.rooms[27].id = 1580
      region.rooms[27].links = {}
        region.rooms[27].links.w = {}
          region.rooms[27].links.w.to = 1579
          region.rooms[27].links.w.con = ""
        region.rooms[27].links.n = {}
          region.rooms[27].links.n.to = 1581
          region.rooms[27].links.n.con = ""
      region.rooms[27].exits = "north|west"
      region.rooms[27].desc = "    这里是一片白茫茫的雪地，一眼望不到边际。四周一个人影也没有，厚厚的积雪踩起来发出咯吱的响声，大地上留下一串孤独的脚印。寒冷的北风呼啸而过，吹得脸生痛。暗淡的太阳低悬在天边，显得那么苍白。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly gw;n;n;n;e;e;ne;e;n"
      region.rooms[28].name = "船厂"
      region.rooms[28].zone = "关外"
      region.rooms[28].id = 1581
      region.rooms[28].links = {}
        region.rooms[28].links.s = {}
          region.rooms[28].links.s.to = 1580
          region.rooms[28].links.s.con = ""
        region.rooms[28].links.e = {}
          region.rooms[28].links.e.to = 1583
          region.rooms[28].links.e.con = ""
      region.rooms[28].exits = "south|east"
      region.rooms[28].desc = "    这里是古镇船厂。船厂是位于关外大平原中部的一个古老的小镇，此镇西、南、北、三面是以高墙垒筑，利于坚守。东面临松花江天成天险，乃兵家必争的要地。松花江在冬春时结冰可通行，夏秋化冻你只好找船家帮忙了。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly gw;n;n;n;e;e;ne;e;n;e;e"
      region.rooms[29].name = "大门坎子"
      region.rooms[29].zone = "关外"
      region.rooms[29].id = 1582
      region.rooms[29].links = {}
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 1583
          region.rooms[29].links.w.con = ""
        region.rooms[29].links.se = {}
          region.rooms[29].links.se.to = 1584
          region.rooms[29].links.se.con = ""
      region.rooms[29].exits = "southeast|west"
      region.rooms[29].desc = "    这里是沿江向东的古道，多为进山采参的参客所走，因此也称“参路”。前面一座小山截断去路，因其行似门坎，且为东去采参的第一道屏障，故被称为大门坎子。西面是宽阔的松花江。松花江在冬春时结冰可通行，夏秋化冻你只好找船家帮忙了。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly gw;n;n;n;e;e;ne;e;n;e"
      region.rooms[30].name = "冰面"
      region.rooms[30].zone = "关外"
      region.rooms[30].id = 1583
      region.rooms[30].links = {}
        region.rooms[30].links.e = {}
          region.rooms[30].links.e.to = 1582
          region.rooms[30].links.e.con = ""
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 1581
          region.rooms[30].links.w.con = ""
      region.rooms[30].exits = "east|west"
      region.rooms[30].desc = "    这里是松花江的江面，现已冻成了几尺厚的坚冰。行人或马匹，车辆均可横逾江面而绝无危险。冰面上留有厚厚的积雪，与两岸连成一片，只有中间经常行走之出，露出一条青色的冰路。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se"
      region.rooms[31].name = "二门坎子"
      region.rooms[31].zone = "关外"
      region.rooms[31].id = 1584
      region.rooms[31].links = {}
        region.rooms[31].links.nw = {}
          region.rooms[31].links.nw.to = 1582
          region.rooms[31].links.nw.con = ""
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 1585
          region.rooms[31].links.e.con = ""
      region.rooms[31].exits = "northwest|east"
      region.rooms[31].desc = "    漫长的参路蜿蜒的消失在原处的天边，路上依稀还留有一些浅浅的足印，看来是前面的参客留下的。白茫茫的雪地反射出耀眼的银光，看得人头昏眼花。偶尔有几只雪兔飞驰而过，转眼就无影无踪了。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e"
      region.rooms[32].name = "满天星"
      region.rooms[32].zone = "关外"
      region.rooms[32].id = 1585
      region.rooms[32].links = {}
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 1584
          region.rooms[32].links.w.con = ""
        region.rooms[32].links.se = {}
          region.rooms[32].links.se.to = 1586
          region.rooms[32].links.se.con = ""
      region.rooms[32].exits = "southeast|west"
      region.rooms[32].desc = "    这里是一片开阔的平原，附近不但没有任何小山丘陵，就连一棵树也找不到。抬眼望去，地平线笔直的将蓝天与雪原分隔在两边。据说夜间因这里无物遮挡，可遍观满天星斗。进山的人们多在此祈求上苍的保佑。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se"
      region.rooms[33].name = "谷草垛"
      region.rooms[33].zone = "关外"
      region.rooms[33].id = 1586
      region.rooms[33].links = {}
        region.rooms[33].links.nw = {}
          region.rooms[33].links.nw.to = 1585
          region.rooms[33].links.nw.con = ""
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 1587
          region.rooms[33].links.e.con = ""
      region.rooms[33].exits = "east|northwest"
      region.rooms[33].desc = "    经过一番艰苦的跋涉，你的眼前出现了一片低矮的丘陵。远远看去象秋收后堆成的谷草垛，密密麻麻，数不清有多少个。翻过这片丘陵再向东行，就可进入长白大山了。东面的天边有一缕炊烟，看来似乎有人。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e"
      region.rooms[34].name = "白河"
      region.rooms[34].zone = "关外"
      region.rooms[34].id = 1587
      region.rooms[34].links = {}
        region.rooms[34].links.e = {}
          region.rooms[34].links.e.to = 1589
          region.rooms[34].links.e.con = ""
        region.rooms[34].links.w = {}
          region.rooms[34].links.w.to = 1586
          region.rooms[34].links.w.con = ""
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 1588
          region.rooms[34].links.n.con = ""
      region.rooms[34].exits = "north|east|west"
      region.rooms[34].desc = "    这里是长白山下的一个小村，只有四，五间粗陋的小木屋。这里并没有固定的居民，木屋都是进山采参的参客所盖，为的是在进山前能在这里好好的休息一下。东面就是巍峨耸立的长白大山。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;n"
      region.rooms[35].name = "小茅屋"
      region.rooms[35].zone = "关外"
      region.rooms[35].id = 1588
      region.rooms[35].links = {}
        region.rooms[35].links.s = {}
          region.rooms[35].links.s.to = 1587
          region.rooms[35].links.s.con = ""
      region.rooms[35].exits = "south"
      region.rooms[35].desc = "    这是一座用长白山松木垒成的小屋，屋内打扫的很干净。四周的墙壁上挂满了兽皮和雪橇，一张小小的桌旁坐着一个英俊少年。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e"
      region.rooms[36].name = "密林"
      region.rooms[36].zone = "关外"
      region.rooms[36].id = 1589
      region.rooms[36].links = {}
        region.rooms[36].links.w = {}
          region.rooms[36].links.w.to = 1587
          region.rooms[36].links.w.con = ""
        region.rooms[36].links.eu = {}
          region.rooms[36].links.eu.to = 1590
          region.rooms[36].links.eu.con = ""
      region.rooms[36].exits = "eastup|west"
      region.rooms[36].desc = "    这是一片茂密的松林，杂乱的生长在倾斜的山坡上。每棵松树都有三四抱粗细，高达十几丈。树冠枝多叶密，将天空完全遮住，因此林内显得有些昏暗。树木之间长着很多灌木杂草，使行走很艰难，据说人参就生长在这些杂草之中。"
    region.rooms[37] = {}
      region.rooms[37].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu"
      region.rooms[37].name = "密林"
      region.rooms[37].zone = "关外"
      region.rooms[37].id = 1590
      region.rooms[37].links = {}
        region.rooms[37].links.wd = {}
          region.rooms[37].links.wd.to = 1589
          region.rooms[37].links.wd.con = ""
        region.rooms[37].links.su = {}
          region.rooms[37].links.su.to = 1591
          region.rooms[37].links.su.con = ""
      region.rooms[37].exits = "southup|westdown"
      region.rooms[37].desc = "    这是一片茂密的松林，杂乱的生长在倾斜的山坡上。每棵松树都有三四抱粗细，高达十几丈。树冠枝多叶密，将天空完全遮住，因此林内显得有些昏暗。树木之间长着很多灌木杂草，使行走很艰难，据说人参就生长在这些杂草之中。"
    region.rooms[38] = {}
      region.rooms[38].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su"
      region.rooms[38].name = "密林"
      region.rooms[38].zone = "关外"
      region.rooms[38].id = 1591
      region.rooms[38].links = {}
        region.rooms[38].links.eu = {}
          region.rooms[38].links.eu.to = 1592
          region.rooms[38].links.eu.con = ""
        region.rooms[38].links.nd = {}
          region.rooms[38].links.nd.to = 1590
          region.rooms[38].links.nd.con = ""
      region.rooms[38].exits = "eastup|northdown"
      region.rooms[38].desc = "    这是一片茂密的松林，杂乱的生长在倾斜的山坡上。每棵松树都有三四抱粗细，高达十几丈。树冠枝多叶密，将天空完全遮住，因此林内显得有些昏暗。树木之间长着很多灌木杂草，使行走很艰难，据说人参就生长在这些杂草之中。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu"
      region.rooms[39].name = "黑风口"
      region.rooms[39].zone = "关外"
      region.rooms[39].id = 1592
      region.rooms[39].links = {}
        region.rooms[39].links.wd = {}
          region.rooms[39].links.wd.to = 1591
          region.rooms[39].links.wd.con = ""
        region.rooms[39].links.e = {}
          region.rooms[39].links.e.to = 1593
          region.rooms[39].links.e.con = ""
      region.rooms[39].exits = "east|westdown"
      region.rooms[39].desc = "    这里是密林中的险恶之境周围是为茂密的松林，不见天光。林中传来野兽饥饿之极的嘶吼。四处有不知名的草菰和野果，可你一点也不敢尝尝。林木幽暗深邃，似乎暗藏杀机。你到了此处，心胆俱裂，只想快点离开。"
    region.rooms[40] = {}
      region.rooms[40].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e"
      region.rooms[40].name = "小天池"
      region.rooms[40].zone = "关外"
      region.rooms[40].id = 1593
      region.rooms[40].links = {}
        region.rooms[40].links.w = {}
          region.rooms[40].links.w.to = 1592
          region.rooms[40].links.w.con = ""
        region.rooms[40].links.eu = {}
          region.rooms[40].links.eu.to = 1594
          region.rooms[40].links.eu.con = ""
      region.rooms[40].exits = "eastup|west"
      region.rooms[40].desc = "    小天池又称长白镜湖，圆圆如镜。湖水碧蓝，林海峭壁倒映其间，风光幽丽，一层绿里透红的细沙，均匀地铺在湖底，恰似展开着的一幅金丝绒毯。相传天上仙女每日天池中沐浴，洗毕就到天豁峰的峰颠，坐在两个峰尖中间的开阔岩石上，对着小天池打扮梳妆，故名镜湖。"
    region.rooms[41] = {}
      region.rooms[41].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu"
      region.rooms[41].name = "长白瀑布"
      region.rooms[41].zone = "关外"
      region.rooms[41].id = 1594
      region.rooms[41].links = {}
        region.rooms[41].links.wd = {}
          region.rooms[41].links.wd.to = 1593
          region.rooms[41].links.wd.con = ""
        region.rooms[41].links.se = {}
          region.rooms[41].links.se.to = 1595
          region.rooms[41].links.se.con = ""
      region.rooms[41].exits = "southeast|westdown"
      region.rooms[41].desc = "    天池水从两百余尺高飞流跌落，轰鸣之声远传数里，水花直落大嶂谷，与天然屏障玉壁、金壁相映，恰似白练当空，水柱扑向深深的谷底，溅起几丈高的飞浪，犹如仙女散花，阳光照射下，虹飞氤跃，璀灿壮观之极。古人诗云：“白河两岸景清幽，碧水悬崖万古留；疑似龙池喷瑞雪，如同天际挂飞流。不须鞭石渡沧海，直可乘槎问斗牛？欲识林泉真乐趣，明朝结伴再来游。”"
    region.rooms[42] = {}
      region.rooms[42].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se"
      region.rooms[42].name = "达门"
      region.rooms[42].zone = "关外"
      region.rooms[42].id = 1595
      region.rooms[42].links = {}
        region.rooms[42].links.nw = {}
          region.rooms[42].links.nw.to = 1594
          region.rooms[42].links.nw.con = ""
        region.rooms[42].links.sw = {}
          region.rooms[42].links.sw.to = 1596
          region.rooms[42].links.sw.con = ""
      region.rooms[42].exits = "northwest|southwest"
      region.rooms[42].desc = "    天池三面壅注不流，惟独北面偏东一线斜垂，白练飞舞，这就是达门。池水经达门外流，水流清冷，在石壁间冲撞有声。"
    region.rooms[43] = {}
      region.rooms[43].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw"
      region.rooms[43].name = "龙门峰"
      region.rooms[43].zone = "关外"
      region.rooms[43].id = 1596
      region.rooms[43].links = {}
        region.rooms[43].links.ne = {}
          region.rooms[43].links.ne.to = 1595
          region.rooms[43].links.ne.con = ""
        region.rooms[43].links.sd = {}
          region.rooms[43].links.sd.to = 1602
          region.rooms[43].links.sd.con = ""
        region.rooms[43].links.w = {}
          region.rooms[43].links.w.to = 1597
          region.rooms[43].links.w.con = ""
        region.rooms[43].links.e = {}
          region.rooms[43].links.e.to = 1598
          region.rooms[43].links.e.con = ""
      region.rooms[43].exits = "east|southdown|northeast|west"
      region.rooms[43].desc = "    龙门峰在乘槎河西岸，因状如门形，故名龙门。崇崖峻壁，形态奇特，宛如卧龙吸水，传说大禹治水曾到此峰，旁有蝌蚪形石柱。"
    region.rooms[44] = {}
      region.rooms[44].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw;w"
      region.rooms[44].name = "鹿鸣峰"
      region.rooms[44].zone = "关外"
      region.rooms[44].id = 1597
      region.rooms[44].links = {}
        region.rooms[44].links.e = {}
          region.rooms[44].links.e.to = 1596
          region.rooms[44].links.e.con = ""
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 1599
          region.rooms[44].links.s.con = ""
      region.rooms[44].exits = "south|east"
      region.rooms[44].desc = "    龙门峰西侧就是鹿鸣峰。鹿鸣峰又称芝盘峰，因峰上有一草甸子，形圆如盖，有热气从地下冒出，每到严冬，其它峰均积雪甚厚，唯鹿鸣峰依然植物茂盛，且盛产芝草，鹿多居之。常有鹤、雀、雕、燕飞落其上，有“鹿鸣翠谷，雕飞芝盖”之称。"
    region.rooms[45] = {}
      region.rooms[45].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw;e"
      region.rooms[45].name = "天豁峰"
      region.rooms[45].zone = "关外"
      region.rooms[45].id = 1598
      region.rooms[45].links = {}
        region.rooms[45].links.w = {}
          region.rooms[45].links.w.to = 1596
          region.rooms[45].links.w.con = ""
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 1604
          region.rooms[45].links.s.con = ""
      region.rooms[45].exits = "south|west"
      region.rooms[45].desc = "    乘槎河东岸，与龙门峰对峙。峰顶如鹰嘴般的峻峭山峰破石而出，伸向天池，故又名鹰嘴峰。古书载：“峰起双尖，中辟一线，有豁然开朗、令人不可思议之趣”，相传为大禹治水所劈，石多赤色，犹如二龙蟠踞，妙趣横生。"
    region.rooms[46] = {}
      region.rooms[46].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw;sd;wu"
      region.rooms[46].name = "白云峰"
      region.rooms[46].zone = "关外"
      region.rooms[46].id = 1599
      region.rooms[46].links = {}
        region.rooms[46].links.ed = {}
          region.rooms[46].links.ed.to = 1602
          region.rooms[46].links.ed.con = ""
        region.rooms[46].links.sw = {}
          region.rooms[46].links.sw.to = 1600
          region.rooms[46].links.sw.con = ""
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 1597
          region.rooms[46].links.n.con = ""
      region.rooms[46].exits = "north|eastdown|southwest"
      region.rooms[46].desc = "    白云峰在天池之西，鹿鸣峰之南，为长白山主峰。山峰圆而高大，临天池而耸立，巍峨磅礴，如一口宝剑直插云天。天气晴好，天池十六峰毕露，惟独此峰常有烟云缭绕，终日不散。古人有“看罢归来回首顾，白山依旧白云封”的赞语。登临此峰，诚有飘飘欲仙之感。"
    region.rooms[47] = {}
      region.rooms[47].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw;sd;wu;sw"
      region.rooms[47].name = "玉柱峰"
      region.rooms[47].zone = "关外"
      region.rooms[47].id = 1600
      region.rooms[47].links = {}
        region.rooms[47].links.ne = {}
          region.rooms[47].links.ne.to = 1599
          region.rooms[47].links.ne.con = ""
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 1601
          region.rooms[47].links.n.con = ""
      region.rooms[47].exits = "north|northeast"
      region.rooms[47].desc = "    白云峰西南，有峰高耸挺秀，多峰突起，形如玉柱。东麓泻出一水，悬流如线，注入天池，就是古籍所载的“金线泉”了。"
    region.rooms[48] = {}
      region.rooms[48].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw;sd;wu;sw;n"
      region.rooms[48].name = "梯云峰"
      region.rooms[48].zone = "关外"
      region.rooms[48].id = 1601
      region.rooms[48].links = {}
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 1600
          region.rooms[48].links.s.con = ""
      region.rooms[48].exits = "south"
      region.rooms[48].desc = "    玉柱峰北，有一山峰，峰脊出梯河瀑布，远望如腾白如云，纵列如梯，故名梯云峰。"
    region.rooms[49] = {}
      region.rooms[49].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw;sd"
      region.rooms[49].name = "白头山天池"
      region.rooms[49].zone = "关外"
      region.rooms[49].id = 1602
      region.rooms[49].links = {}
        region.rooms[49].links.nu = {}
          region.rooms[49].links.nu.to = 1596
          region.rooms[49].links.nu.con = ""
        region.rooms[49].links.eu = {}
          region.rooms[49].links.eu.to = 1604
          region.rooms[49].links.eu.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 1603
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.wu = {}
          region.rooms[49].links.wu.to = 1599
          region.rooms[49].links.wu.con = ""
      region.rooms[49].exits = "westup|south|eastup|northup"
      region.rooms[49].desc = "    “天池在长白山巅中心点，群峰环抱，离地高约二十里，故名天池。”天池碧波盈盈，清澈湛蓝。湖周围峭壁百丈，峰影云影倒映其中，湖光山色、岚影云天十分诱人。湖岸周遭芳草茵茵，百花吐艳。古人诗云：“周迥八十里，峭壁立池边。水满疑天池，云低别有天。江山宜漫画，鹿逐结前缘。予卜携书隐，遨游慰晚年。”"
    region.rooms[50] = {}
      region.rooms[50].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw;sd;s"
      region.rooms[50].name = "白头山天池"
      region.rooms[50].zone = "关外"
      region.rooms[50].id = 1603
      region.rooms[50].links = {}
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 1602
          region.rooms[50].links.n.con = ""
      region.rooms[50].exits = "north"
      region.rooms[50].desc = "    天池十天九雾，云蒸雾绕，变幻无穷。瞬息万变的雾霭风雨，使天池时而清亮如蓝天明镜，时而缥缈如轻莹薄纱，时而腾跃如大海波涛，景色大观令人神往。"
    region.rooms[51] = {}
      region.rooms[51].path = "fly gw;n;n;n;e;e;ne;e;n;e;e;se;e;se;e;e;eu;su;eu;e;eu;se;sw;sd;eu"
      region.rooms[51].name = "华盖峰"
      region.rooms[51].zone = "关外"
      region.rooms[51].id = 1604
      region.rooms[51].links = {}
        region.rooms[51].links.wd = {}
          region.rooms[51].links.wd.to = 1602
          region.rooms[51].links.wd.con = ""
        region.rooms[51].links.n = {}
          region.rooms[51].links.n.to = 1598
          region.rooms[51].links.n.con = ""
      region.rooms[51].exits = "north|westdown"
      region.rooms[51].desc = "    长白东侧最高峰，自古以来，华盖峰就是风雨云雾的故道。云雾起处，恰似掀开锅盖一般，雾气翻滚，池水云天，一脉相连，气壮华夏，故名华盖峰。"
  region.center = 1564

return region
