local region = {}
  region.cmd = "fly hy"
  region.name = "衡阳"
  region.id = "hy"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly hy;n;e;ne;se"
      region.rooms[1].name = "闽赣古道"
      region.rooms[1].zone = "福州|衡阳"
      region.rooms[1].id = 342
      region.rooms[1].desc = "    进入江西，还是不尽的山坎和密林幽谷，终日不见天光。放眼山中毒虫猛兽出没无常，行路艰辛。一到这里就闻到一股腥风扑鼻而来。"
      region.rooms[1].exits = "northwest|eastup"
      region.rooms[1].links = {}
        region.rooms[1].links.nw = {}
          region.rooms[1].links.nw.to = 460
          region.rooms[1].links.nw.con = ""
        region.rooms[1].links.eu = {}
          region.rooms[1].links.eu.to = 341
          region.rooms[1].links.eu.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly hy;n;w;w;w;su;sd"
      region.rooms[2].name = "南岭山口"
      region.rooms[2].zone = "佛山|衡阳"
      region.rooms[2].id = 439
      region.rooms[2].desc = "    这里是南岭的一个山口。南面就是佛山了，北面是横亘湖南广东的五岭。这里地气炎热，百物速生快长，口音也远异中原了。"
      region.rooms[2].exits = "south|northup"
      region.rooms[2].links = {}
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 424
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.nu = {}
          region.rooms[2].links.nu.to = 440
          region.rooms[2].links.nu.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly hy;n;w;w;w;su"
      region.rooms[3].name = "南岭山口"
      region.rooms[3].zone = "衡阳"
      region.rooms[3].id = 440
      region.rooms[3].desc = "    这里是南岭的一个山口。南面是岭南的大镇佛山，北面是湖南的地界。岭南广东富庶繁盛，颇有豪侠之士。"
      region.rooms[3].exits = "southdown|northdown"
      region.rooms[3].links = {}
        region.rooms[3].links.sd = {}
          region.rooms[3].links.sd.to = 439
          region.rooms[3].links.sd.con = ""
        region.rooms[3].links.nd = {}
          region.rooms[3].links.nd.to = 441
          region.rooms[3].links.nd.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly hy;n;w;w;w"
      region.rooms[4].name = "林间大道"
      region.rooms[4].zone = "衡阳"
      region.rooms[4].id = 441
      region.rooms[4].desc = "    这里是一条林间大道。这里是湖南境内。南边通向南岭的一个山口。路东隐隐可以看到一角城墙。西面是一座猛恶山林。"
      region.rooms[4].exits = "north|east|southup|west"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 446
          region.rooms[4].links.e.con = ""
        region.rooms[4].links.su = {}
          region.rooms[4].links.su.to = 440
          region.rooms[4].links.su.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 442
          region.rooms[4].links.n.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly hy;n;w;w;w;n"
      region.rooms[5].name = "林间大道"
      region.rooms[5].zone = "衡阳"
      region.rooms[5].id = 442
      region.rooms[5].desc = "    这里是一条林间大道，在树丛中蜿蜒。这里是湖南境内。北边是湖北。路边有可供路人休息的小茶亭。"
      region.rooms[5].exits = "south|north|east"
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 445
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 441
          region.rooms[5].links.s.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 443
          region.rooms[5].links.n.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly hy;n;w;w;w;n;n"
      region.rooms[6].name = "林间大道"
      region.rooms[6].zone = "衡阳"
      region.rooms[6].id = 443
      region.rooms[6].desc = "    这里是一条林间大道，在树丛中蜿蜒。这里是湖北境内。南边是湖南。"
      region.rooms[6].exits = "south|north"
      region.rooms[6].links = {}
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 442
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 444
          region.rooms[6].links.n.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly hy;n;w;w;w;n;n;n"
      region.rooms[7].name = "林间道"
      region.rooms[7].zone = "衡阳"
      region.rooms[7].id = 444
      region.rooms[7].desc = ""
      region.rooms[7].exits = "south|northwest"
      region.rooms[7].links = {}
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 443
          region.rooms[7].links.s.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly hy;n;w;w;w;n;e"
      region.rooms[8].name = "茶亭"
      region.rooms[8].zone = "衡阳"
      region.rooms[8].id = 445
      region.rooms[8].desc = "    这是一家路边的小茶亭，赶山路的人常在此处歇歇脚。亭子里有几张桌子和几支条凳。周围是一片树林。"
      region.rooms[8].exits = "west"
      region.rooms[8].links = {}
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 442
          region.rooms[8].links.w.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly hy;n;w;w"
      region.rooms[9].name = "黄土路"
      region.rooms[9].zone = "衡阳"
      region.rooms[9].id = 446
      region.rooms[9].desc = "    你走在一条尘土飞扬的黄土路上，两旁是阴森森的树林。东面不远就是衡阳县城了。往西是另外一条大道。"
      region.rooms[9].exits = "east|west"
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 441
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 447
          region.rooms[9].links.e.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly hy;n;w"
      region.rooms[10].name = "衡阳西街"
      region.rooms[10].zone = "衡阳"
      region.rooms[10].id = 447
      region.rooms[10].desc = "    你走在碎石铺就的狭小街道上。街上时常有人持剑疾行，似乎这里出了啥事了。南边是一家小店，北面一座大宇巍峨，重檐叠瓦，门口彩灯高悬，管家家丁好象都是武林中人。"
      region.rooms[10].exits = "south|north|east|west"
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 455
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 448
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 446
          region.rooms[10].links.w.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 450
          region.rooms[10].links.n.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly hy;n;w;s"
      region.rooms[11].name = "小店"
      region.rooms[11].zone = "衡阳"
      region.rooms[11].id = 448
      region.rooms[11].desc = "    这里是衡阳县城的一间小店，卖些简单的饮食，专门赚那些游客的钱。"
      region.rooms[11].exits = "up|north"
      region.rooms[11].links = {}
        region.rooms[11].links.u = {}
          region.rooms[11].links.u.to = 449
          region.rooms[11].links.u.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 447
          region.rooms[11].links.n.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly hy;n;w;s;u"
      region.rooms[12].name = "回雁楼"
      region.rooms[12].zone = "衡阳"
      region.rooms[12].id = 449
      region.rooms[12].desc = "    这里是衡阳回雁楼，是本地最大的酒楼。往日这时已经十分忙碌的酒楼今天却有点异样。一个年近四十的白衣汉子，正端坐自饮，桌面横放着一把快刀，旁边却坐着一个小尼姑，满脸忧急愁苦之色，容貌却十分秀丽。"
      region.rooms[12].exits = "down"
      region.rooms[12].links = {}
        region.rooms[12].links.d = {}
          region.rooms[12].links.d.to = 448
          region.rooms[12].links.d.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly hy;n;w;n"
      region.rooms[13].name = "刘府大门"
      region.rooms[13].zone = "衡阳"
      region.rooms[13].id = 450
      region.rooms[13].desc = "    这里是刘府大门。刘府的主人，就是衡山派中的仅次于掌门人莫大先生的第二号人物刘正风刘老爷子。今天兴许刘府有事吧，大门(gate)紧闭，管家家丁也异样紧张。只有檐下的写着 \"刘府\" 二字的大红灯笼中的烛火忽闪晃动才显出点活人气。"
      region.rooms[13].exits = "south"
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 447
          region.rooms[13].links.s.con = ""
        region.rooms[13].links.enter = {}
          region.rooms[13].links.enter.to = 451
          region.rooms[13].links.enter.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly hy;n;w;n;knock gate;push gate;enter"
      region.rooms[14].name = "刘府大院"
      region.rooms[14].zone = "衡阳"
      region.rooms[14].id = 451
      region.rooms[14].desc = "    刘府大院里现在挤着很多江湖豪客，原来今天是刘正风金盆洗手的好日子。刘老爷子在衡阳人缘很好，来捧场的自然不少，大院里已摆了很多张桌子，杯筷往来，很是热闹。"
      region.rooms[14].exits = "north|out"
      region.rooms[14].links = {}
        region.rooms[14].links.out = {}
          region.rooms[14].links.out.to = 450
          region.rooms[14].links.out.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 452
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly hy;n;w;n;knock gate;push gate;enter;n"
      region.rooms[15].name = "刘府大厅"
      region.rooms[15].zone = "衡阳"
      region.rooms[15].id = 452
      region.rooms[15].desc = ""
      region.rooms[15].exits = "south|east|west"
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 453
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 451
          region.rooms[15].links.s.con = ""
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 454
          region.rooms[15].links.w.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly hy;n;w;n;knock gate;push gate;enter;n;e"
      region.rooms[16].name = "刘府东厢房"
      region.rooms[16].zone = "衡阳"
      region.rooms[16].id = 453
      region.rooms[16].desc = "    这儿是东厢房，这儿整理得干干净净，窗外露出点绿绿的枝叶，家具上一尘不染，地上铺着很大块的青砖，一点灰尘也不沾。"
      region.rooms[16].exits = "west"
      region.rooms[16].links = {}
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 452
          region.rooms[16].links.w.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly hy;n;w;n;knock gate;push gate;enter;n;w"
      region.rooms[17].name = "刘府西厢房"
      region.rooms[17].zone = "衡阳"
      region.rooms[17].id = 454
      region.rooms[17].desc = "    这儿是西厢房，这儿整理得干干净净，窗外露出点绿绿的枝叶，家具上一尘不染，地上铺着很大块的青砖，一点灰尘也不沾。刘府的小孩们不知在这里悄悄说着什么。"
      region.rooms[17].exits = "east"
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 452
          region.rooms[17].links.e.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly hy;n"
      region.rooms[18].name = "衡阳城"
      region.rooms[18].zone = "衡阳"
      region.rooms[18].id = 455
      region.rooms[18].desc = "    这里就是衡阳县城。衡阳地处偏远，显见远不如中原繁华了。"
      region.rooms[18].exits = "south|north|east|west"
      region.rooms[18].links = {}
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 459
          region.rooms[18].links.e.con = ""
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 456
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 447
          region.rooms[18].links.w.con = ""
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 457
          region.rooms[18].links.n.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly hy"
      region.rooms[19].name = "衡阳茶馆"
      region.rooms[19].zone = "衡阳"
      region.rooms[19].id = 456
      region.rooms[19].desc = "    你一走进来，就闻到一股茶香沁入心脾，精神为之一爽。几张八仙桌一字排开，坐满了客人，或高声谈笑，或交头接耳。你要想打听江湖掌故和谣言，这里是个好所在。"
      region.rooms[19].exits = "north"
      region.rooms[19].links = {}
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 455
          region.rooms[19].links.n.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly hy;n;n"
      region.rooms[20].name = "棂星门"
      region.rooms[20].zone = "衡阳"
      region.rooms[20].id = 457
      region.rooms[20].desc = "    这里是南岳大庙的第一道门，由汉白玉，花岗石打就的石牌坊。南岳衡山是祝融游息之地，道教奉为第三小洞天。在此远望衡山，山势如飞，如云雾中凌空的大鸟。"
      region.rooms[20].exits = "south|north"
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 455
          region.rooms[20].links.s.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 458
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly hy;n;n;n"
      region.rooms[21].name = "奎星阁"
      region.rooms[21].zone = "衡阳"
      region.rooms[21].id = 458
      region.rooms[21].desc = "    奎星阁是南岳大庙的第二进。阁为一个大舞台，阁左为鼓亭，右是钟亭。乡俗年节唱戏，这里总是热闹非凡。"
      region.rooms[21].exits = "south|north|east"
      region.rooms[21].links = {}
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 457
          region.rooms[21].links.s.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly hy;n;e"
      region.rooms[22].name = "黄土路"
      region.rooms[22].zone = "衡阳"
      region.rooms[22].id = 459
      region.rooms[22].desc = "    你走在一条尘土飞扬的黄土路上，两旁是阴森森的树林。西面不远就是衡阳县城了。"
      region.rooms[22].exits = "northeast|west"
      region.rooms[22].links = {}
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 455
          region.rooms[22].links.w.con = ""
        region.rooms[22].links.ne = {}
          region.rooms[22].links.ne.to = 460
          region.rooms[22].links.ne.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly hy;n;e;ne"
      region.rooms[23].name = "黄土路"
      region.rooms[23].zone = "衡阳"
      region.rooms[23].id = 460
      region.rooms[23].desc = "    你走在一条尘土飞扬的黄土路上，两旁是阴森森的树林。"
      region.rooms[23].exits = "northwest|southeast|southwest"
      region.rooms[23].links = {}
        region.rooms[23].links.sw = {}
          region.rooms[23].links.sw.to = 459
          region.rooms[23].links.sw.con = ""
        region.rooms[23].links.nw = {}
          region.rooms[23].links.nw.to = 461
          region.rooms[23].links.nw.con = ""
        region.rooms[23].links.se = {}
          region.rooms[23].links.se.to = 342
          region.rooms[23].links.se.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly hy;n;e;ne;nw"
      region.rooms[24].name = "黄土路"
      region.rooms[24].zone = "衡阳"
      region.rooms[24].id = 461
      region.rooms[24].desc = "    你走在一条尘土飞扬的黄土路上，两旁是阴森森的树林。这里向北通往扬州，往南就进入湖南地界了。"
      region.rooms[24].exits = "southeast|northdown"
      region.rooms[24].links = {}
        region.rooms[24].links.se = {}
          region.rooms[24].links.se.to = 460
          region.rooms[24].links.se.con = ""
        region.rooms[24].links.nd = {}
          region.rooms[24].links.nd.to = 462
          region.rooms[24].links.nd.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly hy;n;e;ne;nw;nd"
      region.rooms[25].name = "青石大道"
      region.rooms[25].zone = "衡阳"
      region.rooms[25].id = 462
      region.rooms[25].desc = "    你走在一条青石大道上，四周静悄悄的。西边是一条大道，东边是好大的一片树林。往南还有一条大道，掩映在密密的树林中。"
      region.rooms[25].exits = "north|east|southup|west"
      region.rooms[25].links = {}
        region.rooms[25].links.su = {}
          region.rooms[25].links.su.to = 461
          region.rooms[25].links.su.con = ""
  region.center = 456

return region
