local region = {}
  region.cmd = "fly jx"
  region.name = "嘉兴"
  region.id = "jx"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly jx;n;nw;w;nw"
      region.rooms[1].name = "山路"
      region.rooms[1].zone = "苏州|嘉兴"
      region.rooms[1].id = 190
      region.rooms[1].links = {}
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 192
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.nw = {}
          region.rooms[1].links.nw.to = 188
          region.rooms[1].links.nw.con = ""
        region.rooms[1].links.se = {}
          region.rooms[1].links.se.to = 191
          region.rooms[1].links.se.con = ""
      region.rooms[1].exits = "south|northwest|southeast"
      region.rooms[1].desc = "    你走在一条山路上。时值春日，路旁的山坡上开满了金黄色的油菜花。东面是江南名城嘉兴。西边望去，波光粼闪，白帆点缀，便是周遭五百里的太湖了。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly jx;n;nw;w"
      region.rooms[2].name = "嘉兴城"
      region.rooms[2].zone = "嘉兴"
      region.rooms[2].id = 191
      region.rooms[2].desc = "    这里是江南名城嘉兴。城东是风景如画的南湖。城北早先有座醉仙楼，当年全真七子之一的丘处机和江南七怪就在那里盟约寻找忠良之后。不知道什么原因店主把它迁到扬州了。"
      region.rooms[2].exits = "south|east|northwest"
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 198
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 196
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.nw = {}
          region.rooms[2].links.nw.to = 190
          region.rooms[2].links.nw.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly jx;n;nw;w;nw;s"
      region.rooms[3].name = "山路"
      region.rooms[3].zone = "嘉兴"
      region.rooms[3].id = 192
      region.rooms[3].desc = "    你走在一条山路上。时值春日，路旁的山坡上开满了金黄色的油菜花。"
      region.rooms[3].exits = "south|north"
      region.rooms[3].links = {}
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 193
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 190
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly jx;n;nw;s;w;sw;n"
      region.rooms[4].name = "山路"
      region.rooms[4].zone = "嘉兴"
      region.rooms[4].id = 193
      region.rooms[4].desc = "    你走在一条山路上。时值春日，路旁的山坡上开满了金黄色的油菜花。"
      region.rooms[4].exits = "south|north"
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 194
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 192
          region.rooms[4].links.n.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly jx;n;nw;s;w;sw"
      region.rooms[5].name = "杭嘉湖平原"
      region.rooms[5].zone = "嘉兴"
      region.rooms[5].id = 194
      region.rooms[5].desc = "    富庶的杭嘉湖平原。"
      region.rooms[5].exits = "north|northeast|southwest"
      region.rooms[5].links = {}
        region.rooms[5].links.ne = {}
          region.rooms[5].links.ne.to = 196
          region.rooms[5].links.ne.con = ""
        region.rooms[5].links.sw = {}
          region.rooms[5].links.sw.to = 195
          region.rooms[5].links.sw.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 193
          region.rooms[5].links.n.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly jx;n;nw;s;w;sw;sw"
      region.rooms[6].name = "青石大道"
      region.rooms[6].zone = "嘉兴|杭州"
      region.rooms[6].id = 195
      region.rooms[6].links = {}
        region.rooms[6].links.ne = {}
          region.rooms[6].links.ne.to = 194
          region.rooms[6].links.ne.con = ""
        region.rooms[6].links.sw = {}
          region.rooms[6].links.sw.to = 281
          region.rooms[6].links.sw.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 211
          region.rooms[6].links.w.con = ""
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 212
          region.rooms[6].links.s.con = ""
      region.rooms[6].exits = "south|northeast|west|southwest"
      region.rooms[6].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道延伸向西边。断桥在大道的西南边。南边则是另一条大道。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly jx;n;nw;s;w"
      region.rooms[7].name = "嘉兴南门"
      region.rooms[7].zone = "嘉兴"
      region.rooms[7].id = 196
      region.rooms[7].desc = "    这里是嘉兴的南门。周围长着茂密的竹林。东面是座庙宇。向南可入福建。向西南就是号称天堂的杭州城了。"
      region.rooms[7].exits = "east|north|southwest"
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 197
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.sw = {}
          region.rooms[7].links.sw.to = 194
          region.rooms[7].links.sw.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 191
          region.rooms[7].links.n.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly jx;n;nw;s"
      region.rooms[8].name = "铁枪庙"
      region.rooms[8].zone = "嘉兴"
      region.rooms[8].id = 197
      region.rooms[8].desc = "    这铁枪庙祀奉的是五代时名将铁枪王彦章。庙旁有座高塔，塔顶群鸦世代为巢，当地乡民传说铁枪庙的乌鸦是神兵神将，向来不敢侵犯，以致生养繁殖，越来越多。案桌下有个小洞(dong)。"
      region.rooms[8].exits = "north|west"
      region.rooms[8].links = {}
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 196
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 198
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly jx;n;nw"
      region.rooms[9].name = "嘉兴南湖"
      region.rooms[9].zone = "嘉兴"
      region.rooms[9].id = 198
      region.rooms[9].desc = "    这里是嘉兴南湖。节近中秋，荷叶渐残，莲肉饱实。一阵轻柔婉转的歌声，飘在烟水蒙蒙的湖面上。湖边一个道姑在一排柳树下悄立已久。"
      region.rooms[9].exits = "south|east|southeast|west"
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 199
          region.rooms[9].links.e.con = ""
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 197
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 191
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.se = {}
          region.rooms[9].links.se.to = 200
          region.rooms[9].links.se.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly jx;n;nw;e"
      region.rooms[10].name = "嘉兴海港"
      region.rooms[10].zone = "嘉兴"
      region.rooms[10].id = 199
      region.rooms[10].desc = "    这里是嘉兴海港，港内白帆点点，码头上停着好多渔船，可是一提起桃花岛却个个摇头。"
      region.rooms[10].exits = "west"
      region.rooms[10].links = {}
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 198
          region.rooms[10].links.w.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly jx;n"
      region.rooms[11].name = "嘉兴南湖"
      region.rooms[11].zone = "嘉兴"
      region.rooms[11].id = 200
      region.rooms[11].desc = "    这里是烟波浩淼的南湖。湖上几只画舫在游荡，船上的游客和青楼女子在嘻笑。湖水很深，没有船是渡不过去的。但不知是谁在湖底钉了一些木桩。桩顶潜在水面之下一两寸的地方。即使是不懂轻功的人走上去也像是水上漂的样子。似乎水下有了些什么. 近来有人潜(out)下湖去搜寻什么, 总也不知道结果如何. 只是有人传闻在湖底找到了什么宝贝."
      region.rooms[11].exits = "south|northwest"
      region.rooms[11].links = {}
        region.rooms[11].links.nw = {}
          region.rooms[11].links.nw.to = 198
          region.rooms[11].links.nw.con = ""
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 201
          region.rooms[11].links.s.con = ""
        region.rooms[11].links.out = {}
          region.rooms[11].links.out.to = 203
          region.rooms[11].links.out.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly jx"
      region.rooms[12].name = "烟雨楼"
      region.rooms[12].zone = "嘉兴"
      region.rooms[12].id = 201
      region.rooms[12].desc = "    烟雨楼建在南湖中心的一个小岛上。南湖终年不断的水气把它笼罩得迷迷蒙蒙的。楼内是家饭店。店内正在装修楼梯。请勿上楼。"
      region.rooms[12].exits = "up|north"
      region.rooms[12].links = {}
        region.rooms[12].links.u = {}
          region.rooms[12].links.u.to = 202
          region.rooms[12].links.u.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 200
          region.rooms[12].links.n.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly jx;u"
      region.rooms[13].name = "烟雨楼二楼"
      region.rooms[13].zone = "嘉兴"
      region.rooms[13].id = 202
      region.rooms[13].desc = "    烟雨楼在南湖畔，四望临风，醺醺醉人。柳岸翻曳，禽噪起伏。湖面轻烟薄雾，几尾小舟荡漾其间。半湖水里都浮着碧油油的菱叶，越女轻歌，娇痴无那。    你放眼观赏，直欲跳入她的怀中。    楼中立了一幅长匾(bian)，绞丝镶边，楠木为里，年代虽久，桐油粉漆，犹自清新如昨。柱子上隐隐有些字迹（ziji）。"
      region.rooms[13].exits = "down"
      region.rooms[13].links = {}
        region.rooms[13].links.d = {}
          region.rooms[13].links.d.to = 201
          region.rooms[13].links.d.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly jx;n;out"
      region.rooms[14].name = "嘉兴南湖"
      region.rooms[14].zone = "嘉兴"
      region.rooms[14].id = 203
      region.rooms[14].desc = "    这里是嘉兴南湖水下，四周倒还比较明亮，几道天光从头顶的潭水中投射下来，显得十分美丽。脚下漆黑一片也不知有些什么。你不由对自己说......"
      region.rooms[14].exits = "up|down"
      region.rooms[14].links = {}
        region.rooms[14].links.u = {}
          region.rooms[14].links.u.to = 200
          region.rooms[14].links.u.con = ""
        region.rooms[14].links.d = {}
          region.rooms[14].links.d.to = 204
          region.rooms[14].links.d.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly jx;n;out;d"
      region.rooms[15].name = "嘉兴南湖"
      region.rooms[15].zone = "嘉兴"
      region.rooms[15].id = 204
      region.rooms[15].desc = "    这里是嘉兴南湖水下，四周倒还渐渐有些昏暗了，几道天光从头顶的潭水中投射下来，此时也不那么瑰丽了，昏沉沉的犹如天边的晚霞。脚下漆黑一片也不知有些什么。四周的水流也没有那么平静了，似乎在向一个方向流动着。你不由心中一动：不会有暗流吧！！"
      region.rooms[15].exits = "up|down"
      region.rooms[15].links = {}
        region.rooms[15].links.u = {}
          region.rooms[15].links.u.to = 203
          region.rooms[15].links.u.con = ""
        region.rooms[15].links.d = {}
          region.rooms[15].links.d.to = 205
          region.rooms[15].links.d.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly jx;n;out;d;d"
      region.rooms[16].name = "嘉兴南湖"
      region.rooms[16].zone = "嘉兴"
      region.rooms[16].id = 205
      region.rooms[16].desc = "    这里是嘉兴南湖底，四周黑忽忽的，头顶上只能看见一点亮光，身边的水流似乎更加湍急了。脚下似乎有一点亮光，也不知是些什么。周围一片死寂，似乎暗藏着层层杀机。"
      region.rooms[16].exits = "south|up|north|east|west"
      region.rooms[16].links = {}
        region.rooms[16].links.s = {}
          region.rooms[16].links.s.to = 208
          region.rooms[16].links.s.con = ""
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 206
          region.rooms[16].links.e.con = ""
        region.rooms[16].links.u = {}
          region.rooms[16].links.u.to = 204
          region.rooms[16].links.u.con = ""
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 207
          region.rooms[16].links.w.con = ""
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 206
          region.rooms[16].links.n.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly jx;n;out;d;d;e"
      region.rooms[17].name = "嘉兴南湖"
      region.rooms[17].zone = "嘉兴"
      region.rooms[17].id = 206
      region.rooms[17].desc = "    这里是嘉兴南湖水下，四周黑乎乎的伸手不见五指。看不见一点亮光，身边的水流忽上忽下的涌动着。看起来是一处海眼。脚下似乎有一点亮光，也不知是些什么。周围一片死寂，似乎暗藏着层层杀机。"
      region.rooms[17].exits = "south|up|north|east|down"
      region.rooms[17].links = {}
        region.rooms[17].links.u = {}
          region.rooms[17].links.u.to = 204
          region.rooms[17].links.u.con = ""
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 205
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 205
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 205
          region.rooms[17].links.n.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly jx;n;out;d;d;w"
      region.rooms[18].name = "嘉兴南湖"
      region.rooms[18].zone = "嘉兴"
      region.rooms[18].id = 207
      region.rooms[18].desc = "    这里是嘉兴南湖底，四周黑忽忽的，头顶上看不见一点亮光，身边的水流忽上忽下的涌动着。看起来是一处海眼。脚下似乎有一点亮光，也不知是些什么。周围一片死寂，似乎暗藏着层层杀机。"
      region.rooms[18].exits = "up|northwest|southwest|down"
      region.rooms[18].links = {}
        region.rooms[18].links.u = {}
          region.rooms[18].links.u.to = 204
          region.rooms[18].links.u.con = ""
        region.rooms[18].links.sw = {}
          region.rooms[18].links.sw.to = 206
          region.rooms[18].links.sw.con = ""
        region.rooms[18].links.nw = {}
          region.rooms[18].links.nw.to = 206
          region.rooms[18].links.nw.con = ""
        region.rooms[18].links.d = {}
          region.rooms[18].links.d.to = 208
          region.rooms[18].links.d.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly jx;n;out;d;d;s"
      region.rooms[19].name = "嘉兴南湖"
      region.rooms[19].zone = "嘉兴"
      region.rooms[19].id = 208
      region.rooms[19].desc = "    这里是嘉兴南湖底，四周黑忽忽的，头顶上看不见一点亮光，身边的水流忽上忽下的涌动着。看起来是一处海眼。东边似乎有一点亮光，被一块巨大的石块(stone)挡着。周围一片死寂，似乎暗藏着层层杀机。"
      region.rooms[19].exits = "south|up|north|west"
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 209
          region.rooms[19].links.s.con = ""
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 210
          region.rooms[19].links.e.con = "pushstone:"
		  region.rooms[19].links.e.block = "y"
        region.rooms[19].links.u = {}
          region.rooms[19].links.u.to = 206
          region.rooms[19].links.u.con = ""
        region.rooms[19].links.w = {}
          region.rooms[19].links.w.to = 209
          region.rooms[19].links.w.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 209
          region.rooms[19].links.n.con = ""
    region.rooms[20] = {}
      region.rooms[20].danger = 5
      region.rooms[20].path = "fly jx;n;out;d;d;s;s"
      region.rooms[20].name = "嘉兴南湖"
      region.rooms[20].zone = "嘉兴"
      region.rooms[20].id = 209
      region.rooms[20].desc = "    这里是嘉兴南湖底，四周黑忽忽的，头顶上看不见一点亮光，身边的水流忽上忽下的涌动着。看起来是一处海眼。脚下似乎有一点亮光，也不知是些什么。周围一片死寂，似乎暗藏着层层杀机。"
      region.rooms[20].exits = "south|up|north|east|west"
      region.rooms[20].links = {}
        region.rooms[20].links.u = {}
          region.rooms[20].links.u.to = 209
          region.rooms[20].links.u.con = ""
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 208
          region.rooms[20].links.e.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 209
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 209
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly jx;n;out;d;d;s;|!pushstone::e|"
      region.rooms[21].name = "湖心小洞"
      region.rooms[21].zone = "嘉兴"
      region.rooms[21].id = 210
      region.rooms[21].desc = "    这里是潭中的一个小洞，里面零零落落的有几块石头。"
      region.rooms[21].exits = "west"
      region.rooms[21].links = {}
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 208
          region.rooms[21].links.w.con = ""
  region.center = 201
return region