local region = {}
  region.cmd = "|!kl2::hi|"
  region.name = "昆仑山2"
  region.id = "kl2"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "|!kl2::hi|"
      region.rooms[1].name = "翠谷"
      region.rooms[1].zone = "昆仑山2"
      region.rooms[1].id = 3014
      region.rooms[1].desc = "    出得洞来，面前竟是个花团锦簇的翠谷，红花绿树，交相掩映。脚下踏著的是柔软细草，鼻中闻到的是清幽花香，鸣禽间关，鲜果悬枝，哪想得到在这黑黝黝的洞穴之后，竟会有这样一个洞天福地？离地丈许高处有一山洞(dong)。"
      region.rooms[1].exits = "south|eastup|west"
      region.rooms[1].links = {}
        region.rooms[1].links.eu = {}
          region.rooms[1].links.eu.to = 3017
          region.rooms[1].links.eu.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 3016
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 3015
          region.rooms[1].links.s.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "|!kl2::hi|;s"
      region.rooms[2].name = "昆仑仙境"
      region.rooms[2].zone = "昆仑山2"
      region.rooms[2].id = 3015
      region.rooms[2].desc = "    放开脚步向前急奔，直奔了两里有馀，才遇一座高峰阻路。放眼四望，旦见翠谷四周高山环绕，似乎亘古以来从未有人迹到过。四面雪峰插云，险峻陡绝计无法攀援而入。"
      region.rooms[2].exits = "north"
      region.rooms[2].links = {}
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 3014
          region.rooms[2].links.n.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "|!kl2::hi|;w"
      region.rooms[3].name = "瀑布"
      region.rooms[3].zone = "昆仑山2"
      region.rooms[3].id = 3016
      region.rooms[3].desc = "    向西走了二里多，只见峭壁上有一道大瀑布冲击而下，料想是雪融而成，阳光照射下尤如一条大玉龙，极是壮丽。瀑布泄在一座清澈碧绿的深潭(tan )之中，潭水却也不见满，当是另有泄水的去路。你观赏了半晌，一低头，见手足上染满了清苔污泥，另有无数给荆棘硬草割破的血痕，於是走近潭边，除下鞋袜，伸足到潭水中去洗涤(xidi)。"
      region.rooms[3].exits = "east"
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 3014
          region.rooms[3].links.e.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "|!kl2::hi|;eu"
      region.rooms[4].name = "山壁"
      region.rooms[4].zone = "昆仑山2"
      region.rooms[4].id = 3017
      region.rooms[4].desc = "    这是一片陡峭的山壁，全为极为坚硬的岩石，滑不溜脚，稍微不小心就会滑倒。在山壁上划有六个大字：【张无忌埋经处】。往西而下是一片洞天，往东而下是一山沟。"
      region.rooms[4].exits = "westdown|eastdown"
      region.rooms[4].links = {}
        region.rooms[4].links.wd = {}
          region.rooms[4].links.wd.to = 3014
          region.rooms[4].links.wd.con = ""
        region.rooms[4].links.ed = {}
          region.rooms[4].links.ed.to = 3018
          region.rooms[4].links.ed.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "|!kl2::hi|;eu;ed"
      region.rooms[5].name = "山沟"
      region.rooms[5].zone = "昆仑山2"
      region.rooms[5].id = 3018
      region.rooms[5].desc = "    山壁之下的一条小山沟，往西是一片稍矮的山壁，其余三面山壁直接云天。这里绿草丛生，有许多雪中之鸡出没其中。"
      region.rooms[5].exits = "westup"
      region.rooms[5].links = {}
        region.rooms[5].links.wu = {}
          region.rooms[5].links.wu.to = 3017
          region.rooms[5].links.wu.con = ""
  region.center = 3014
return region