local region = {}
  region.cmd = "fly lz"
  region.name = "灵州"
  region.id = "lz"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly lz"
      region.rooms[1].name = "城中心"
      region.rooms[1].zone = "灵州"
      region.rooms[1].id = 890
      region.rooms[1].desc = "    这里是西夏都城灵州的中心广场，也是四条大街的交汇处，北面是皇城，南面是商业繁华地段，西面是普通商人区和骠骑营，东面衙门和王公贵族们的府第。灵州是西域最大的物资集散地和商业中心，也是西域通往中原的必经之地。各色人等来来往往，马嘶人喊，热闹非凡，广场空地上卖艺的、要饭的、大腹便便的财主、提笼携鸟的王公贵戚到处都是，偶尔也有行色匆匆的江湖人士一晃而过。"
      region.rooms[1].exits = "south|east|north|west"
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 914
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 903
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 891
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 935
          region.rooms[1].links.n.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly lz;w"
      region.rooms[2].name = "西大街"
      region.rooms[2].zone = "灵州"
      region.rooms[2].id = 891
      region.rooms[2].desc = "    这是灵州西大街，街道宽敞而干净，青砖砌的路面被雨水冲得光明如镜，街道两侧的瓦房高大而宏伟，双人合抱的杨树十步一株，整齐地排在两边。大街北面一对大红灯笼，悬挂在朱门两旁。这里就是一品堂总坛。大街南面有几家店铺，街道有点冷清。"
      region.rooms[2].exits = "south|east|north|west"
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 890
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 892
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 899
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 893
          region.rooms[2].links.n.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly lz;w;s"
      region.rooms[3].name = "刀店"
      region.rooms[3].zone = "灵州"
      region.rooms[3].id = 892
      region.rooms[3].desc = "    这是一家以卖西域特产“英吉儿”小刀出名的兵器铺，上百把各式各样的“英吉儿”小刀整整齐齐的摆放在柜台上，说是小刀却尺寸型制大不相同，既有长仅一寸的柳叶飞刀、也有长达三尺的阿拉伯弯刀。最多的还是长六寸，宽三分，背厚一黍，刃薄如纸的匕首柜台后面的墙上也挂着些长剑，钢刀，铁杖等中原兵器。"
      region.rooms[3].exits = "north"
      region.rooms[3].links = {}
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 891
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly lz;w;n"
      region.rooms[4].name = "一品堂大门"
      region.rooms[4].zone = "灵州"
      region.rooms[4].id = 893
      region.rooms[4].desc = "    这里是西夏一品堂的所在地，座落在西大街的北面，是一座高大的石头建筑，看上去坚固之极。门口有两个武士站着，既不高大也不彪悍，和皇宫门口的守卫差远啦，就是和衙门口的衙役比也颇有不如，但从他们阴鹫的眼神里你不难看出他们是身怀绝技的高手，谁不知西夏一品堂广招天下高手为皇上效命。"
      region.rooms[4].exits = "south|north"
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 891
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 894
          region.rooms[4].links.n.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly lz;w;n;n"
      region.rooms[5].name = "一品堂大院"
      region.rooms[5].zone = "灵州"
      region.rooms[5].id = 894
      region.rooms[5].desc = "    这里是西夏一品堂的大院，青石铺就的石板路，从大门直通正北面那座构筑巍峨的一品堂大厅。东面立着一个旗杆，杆上一面不知颜色的锦旗挺精神地飘扬着，杆后是个低矮一些的回廊厅堂。西面一排平房看那样子也象是帐房。大院里有几棵老树撑着几片树荫，中央有一些武士在练拳。"
      region.rooms[5].exits = "south|east|north|west"
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 896
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 895
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 893
          region.rooms[5].links.s.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 897
          region.rooms[5].links.n.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly lz;w;n;n;w"
      region.rooms[6].name = "一品堂帐房"
      region.rooms[6].zone = "灵州"
      region.rooms[6].id = 895
      region.rooms[6].desc = "    这里是西夏一品堂的帐房，自愿加入一品堂的江湖高手，都可以领到饷银。一个老先生两眼一抹黑在此管帐。"
      region.rooms[6].exits = "east"
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 894
          region.rooms[6].links.e.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly lz;w;n;n;e"
      region.rooms[7].name = "接引堂"
      region.rooms[7].zone = "灵州"
      region.rooms[7].id = 896
      region.rooms[7].desc = "    这里是西夏一品堂的接引堂，每个自愿加入一品堂的江湖高手，都需有人充当接引人，查清底细，方能入堂。入堂以后，才有资格由赫连主管分派任务，为一品堂效力。好在这里有个专职接引的汉子，为一品堂广开贤路，所以一品堂在江湖中也确实声名雀起。"
      region.rooms[7].exits = "west"
      region.rooms[7].links = {}
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 894
          region.rooms[7].links.w.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly lz;w;n;n;n"
      region.rooms[8].name = "一品堂大厅"
      region.rooms[8].zone = "灵州"
      region.rooms[8].id = 897
      region.rooms[8].desc = "    这里是西夏一品堂的大厅，厅内阔大，显得有点阴晦。数十根合抱大柱撑着看不清顶的飞檐，厅里气氛很是森森煞人。北面正中一副楠木匾额(bian)高悬，金字蓝底，隐隐生威。红木公案后虎皮交椅上，正襟威坐着的，就是征东大将军赫连总管。周围立着几个一品堂卫士，纹风不动。"
      region.rooms[8].exits = "south|enter"
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 894
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.enter = {}
          region.rooms[8].links.enter.to = 898
          region.rooms[8].links.enter.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly lz;w;n;n;n;enter"
      region.rooms[9].name = "一品堂密室"
      region.rooms[9].zone = "灵州"
      region.rooms[9].id = 898
      region.rooms[9].desc = "    一间阴暗的密室，充满了血腥气。一品堂重金招募天下杀手，只要肯出钱，自有人为你效命。不知有多少秘密交易都是在这里完成的。墙上贴了一张破纸，看得出颇有些时日了。"
      region.rooms[9].exits = "out"
      region.rooms[9].links = {}
        region.rooms[9].links.out = {}
          region.rooms[9].links.out.to = 897
          region.rooms[9].links.out.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly lz;w;w"
      region.rooms[10].name = "骠骑营"
      region.rooms[10].zone = "灵州"
      region.rooms[10].id = 899
      region.rooms[10].desc = "    这里是皇室禁卫军的驻地，在灵州城西北，骠骑营占地面积庞大，北面是营房，南面是小校场，西面紧挨着城墙是一排马厩，有东营门和南营门通向皇宫和大街。骠骑营的军士俱是西夏军中千挑万选的猛士，平时负责皇城外围的警戒，皇上出巡时便挑起开道护卫的重责，战时更是一支生力军。"
      region.rooms[10].exits = "south|east|north|west"
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 891
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 901
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 902
          region.rooms[10].links.w.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 900
          region.rooms[10].links.n.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly lz;w;w;n"
      region.rooms[11].name = "营房"
      region.rooms[11].zone = "灵州"
      region.rooms[11].id = 900
      region.rooms[11].desc = "    这里是骠骑营的营房，一排排木屋煞是齐整, 门口空地许多军士们围成个圈在喧闹，西夏军中崇尚勇力，佩服的是英雄，士兵个个都是彪形大汉。"
      region.rooms[11].exits = "south"
      region.rooms[11].links = {}
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 899
          region.rooms[11].links.s.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly lz;w;w;s"
      region.rooms[12].name = "小校场"
      region.rooms[12].zone = "灵州"
      region.rooms[12].id = 901
      region.rooms[12].desc = "    这里是骠骑营的小校场，平时军士们就在这里操练，地上很平整，居中是指挥台，有根长达数丈的旗杆，杆顶一面绣着一条红龙的骠骑营白色军旗迎风猎猎作响。平时军士们一天三练，早上出操，中午出城练马术和野战，晚上则负责皇城外的巡逻。"
      region.rooms[12].exits = "north"
      region.rooms[12].links = {}
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 899
          region.rooms[12].links.n.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly lz;w;w;w"
      region.rooms[13].name = "马栏"
      region.rooms[13].zone = "灵州"
      region.rooms[13].id = 902
      region.rooms[13].desc = "    这里是骠骑营的马栏，清一色的蒙古高头战马。西夏军中多是骑兵，所以行军作战来去如风，快若闪电，西夏铁骑的彪悍连大辽的骑兵都颇有不如。骠骑营的战马俱是精选，膘肥体壮，马夫们正给马槽里添黑豆和草料，一股马粪味和草料的混合味道飘了过来。"
      region.rooms[13].exits = "east"
      region.rooms[13].links = {}
        region.rooms[13].links.e = {}
          region.rooms[13].links.e.to = 899
          region.rooms[13].links.e.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly lz;s"
      region.rooms[14].name = "南大街"
      region.rooms[14].zone = "灵州"
      region.rooms[14].id = 903
      region.rooms[14].desc = "    这里是灵州南大街，也是商业最繁华的地段，一眼望去只见街两旁店铺林立，五颜六色的店招和旗帜在阳光的照耀下分外鲜明，街上行人很是不少，西面是一家酒馆，东面是一家车马店。"
      region.rooms[14].exits = "south|east|north|west"
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 904
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 907
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 908
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 890
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly lz;s;e"
      region.rooms[15].name = "车马店"
      region.rooms[15].zone = "灵州"
      region.rooms[15].id = 904
      region.rooms[15].desc = "    一家低档的车马客栈，建筑相当陈旧，很不起眼，不过由于价钱低廉，又是在北门的交通要道上，三教九流多选择这里落脚，生意也相当不错，你也可以在这里打听到当地的风土人情。    墙上挂着一个牌子(paizi)。"
      region.rooms[15].exits = "up|east|west"
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 905
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 903
          region.rooms[15].links.w.con = ""
        region.rooms[15].links.u = {}
          region.rooms[15].links.u.to = 906
          region.rooms[15].links.u.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly lz;s;e;e"
      region.rooms[16].name = "马厩"
      region.rooms[16].zone = "灵州"
      region.rooms[16].id = 905
      region.rooms[16].desc = "    这是车马店边上的马厩，常年供应新鲜草料。据说此地民风淳朴，客人只要住店，马夫们就会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净。一直伺候到客人离店上路。马厩中堆放著几堆草料，正中有一口泔槽。马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。"
      region.rooms[16].exits = "west"
      region.rooms[16].links = {}
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 904
          region.rooms[16].links.w.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly lz;s;e;u"
      region.rooms[17].name = "车马店二楼"
      region.rooms[17].zone = "灵州"
      region.rooms[17].id = 906
      region.rooms[17].desc = "    这是一间很大的客房，陈设十分简陋。靠墙放了十几张小木床，不少客人正和衣而卧，满屋子都是呼呼的打酣声。西边有张床是空的，你蹑手蹑脚地走了过去。"
      region.rooms[17].exits = "down"
      region.rooms[17].links = {}
        region.rooms[17].links.d = {}
          region.rooms[17].links.d.to = 904
          region.rooms[17].links.d.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly lz;s;w"
      region.rooms[18].name = "酒馆"
      region.rooms[18].zone = "灵州"
      region.rooms[18].id = 907
      region.rooms[18].desc = "    这是一家小酒馆，紧挨着灵州西门，五开间的门面，规模颇大。来来往往的行人多到这里来打尖歇脚，叫上一盘阿訇宰杀的牛羊肉，喝上几口醇香的马奶酒，酒足饭饱离店之际带上几个有脸盆大小的馕，花钱不多又很实惠，生意特别兴旺。北面是厨房，南面是上楼的楼梯，东面有条布帘。"
      region.rooms[18].exits = "east"
      region.rooms[18].links = {}
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 903
          region.rooms[18].links.e.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly lz;s;s"
      region.rooms[19].name = "灵州南门"
      region.rooms[19].zone = "灵州"
      region.rooms[19].id = 908
      region.rooms[19].desc = "    这是南城门，城门正上方刻得有几个西夏文字。城墙上贴着几张官府告示。一条大路往南通向黄羊滩。"
      region.rooms[19].exits = "south|north"
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 909
          region.rooms[19].links.s.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 903
          region.rooms[19].links.n.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly lz;s;s;s"
      region.rooms[20].name = "黄羊滩"
      region.rooms[20].zone = "灵州"
      region.rooms[20].id = 909
      region.rooms[20].desc = "    这里就是灵州西南著名的黄羊滩，本来是黄河边的一大片水泽盐碱地，黄河水泛滥后退去形成了一大片低洼水滩，上面水草丰盛，春秋两季吸引了大批塞北的野生黄羊到这里来饮水嬉戏，休养生息，成为塞上一大景观。"
      region.rooms[20].exits = "north|southwest"
      region.rooms[20].links = {}
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 908
          region.rooms[20].links.n.con = ""
        region.rooms[20].links.sw = {}
          region.rooms[20].links.sw.to = 910
          region.rooms[20].links.sw.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly lz;s;s;s;sw"
      region.rooms[21].name = "小坝"
      region.rooms[21].zone = "灵州"
      region.rooms[21].id = 910
      region.rooms[21].desc = "    这里是黄河边的一条小支流大柳河与黄河汇合的地方，当地百姓为了防止黄河的泥沙倒灌进大柳河而在这里修了一座小小的石坝，小坝不高，有三孔泄沙的洞（dong），一扇结实的石闸门，两边是绞盘用来控制闸门的升降。小坝使得大柳河两岸的百姓免受了黄河泥沙的侵扰。"
      region.rooms[21].exits = "northeast|southwest"
      region.rooms[21].links = {}
        region.rooms[21].links.ne = {}
          region.rooms[21].links.ne.to = 909
          region.rooms[21].links.ne.con = ""
        region.rooms[21].links.sw = {}
          region.rooms[21].links.sw.to = 911
          region.rooms[21].links.sw.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly lz;s;s;s;sw;sw"
      region.rooms[22].name = "青铜峡"
      region.rooms[22].zone = "灵州"
      region.rooms[22].id = 911
      region.rooms[22].desc = "    这里是黄河河西走廊段中最遄急的青铜峡，黄河一路流淌到这里，宽阔的河面一下子变窄，两岸的峭壁象一对生死恋人紧紧不愿分开，黄河却象不懂事的孩子从中硬挤而过，结果水流一下子变得咆哮起来，波浪滔天，水声隆隆。"
      region.rooms[22].exits = "northeast|southwest"
      region.rooms[22].links = {}
        region.rooms[22].links.ne = {}
          region.rooms[22].links.ne.to = 910
          region.rooms[22].links.ne.con = ""
        region.rooms[22].links.sw = {}
          region.rooms[22].links.sw.to = 912
          region.rooms[22].links.sw.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly lz;s;s;s;sw;sw;sw"
      region.rooms[23].name = "鸣沙洲"
      region.rooms[23].zone = "灵州"
      region.rooms[23].id = 912
      region.rooms[23].desc = "    鸣沙洲就在青铜峡的上游，附近就是连天的沙丘，这里正好处在风口，强劲的西北风吹的黄沙漫天横飞、嗡嗡作响，鸣沙洲由此得名，一走到这里你就觉得透体冰凉，飞沙打在你脸上生疼生疼，让你睁不开眼睛。"
      region.rooms[23].exits = "northeast|southwest"
      region.rooms[23].links = {}
        region.rooms[23].links.ne = {}
          region.rooms[23].links.ne.to = 911
          region.rooms[23].links.ne.con = ""
        region.rooms[23].links.sw = {}
          region.rooms[23].links.sw.to = 913
          region.rooms[23].links.sw.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly lz;s;s;s;sw;sw;sw;sw"
      region.rooms[24].name = "宣和堡"
      region.rooms[24].zone = "灵州"
      region.rooms[24].id = 913
      region.rooms[24].desc = "    这里就是西北小镇宣和堡，南面是黄河，西面是沙漠，只有这里有一片不大的绿洲，住户们都是从关内迁移过来的，大多以经营手工艺品为生, 这里的手织羊毛挂毯颇有名气。每逢初一、十五附近的百姓都来到这摆渡过河到关内去赶集。河案边熙熙攘攘，人们都在挣着叫(yell)船过河。"
      region.rooms[24].exits = "northeast"
      region.rooms[24].links = {}
        region.rooms[24].links.ne = {}
          region.rooms[24].links.ne.to = 912
          region.rooms[24].links.ne.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly lz;e"
      region.rooms[25].name = "东大街"
      region.rooms[25].zone = "灵州"
      region.rooms[25].id = 914
      region.rooms[25].desc = "    这是灵州东大街，同样的宽阔与干净，相比西大街的冷清要热闹多了，街上人来人往，熙熙攘攘，几个小孩正在胡同口玩耍，南面有不少人围在一起，北面是衙门，路边有条狗正在追一只猫。"
      region.rooms[25].exits = "south|east|north|west"
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 918
          region.rooms[25].links.e.con = ""
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 890
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.s = {}
          region.rooms[25].links.s.to = 916
          region.rooms[25].links.s.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 915
          region.rooms[25].links.n.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly lz;e;n"
      region.rooms[26].name = "衙门"
      region.rooms[26].zone = "灵州"
      region.rooms[26].id = 915
      region.rooms[26].desc = "    这是灵州府衙所在地，黑色大门平时紧紧闭着，门前四个身着皂服的衙役没精打采的拄着水火棍站着。边上有个大鼓。"
      region.rooms[26].exits = "south"
      region.rooms[26].links = {}
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 914
          region.rooms[26].links.s.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly lz;e;s"
      region.rooms[27].name = "大将军府"
      region.rooms[27].zone = "灵州"
      region.rooms[27].id = 916
      region.rooms[27].desc = "    这里是征东大将军赫连铁树的府第，在东大街的正中，对面就是衙门。一色高檐大屋，两个校尉看上去彪悍骁勇，此刻正神气活现的挎着弯刀守在门前。"
      region.rooms[27].exits = "south|north"
      region.rooms[27].links = {}
        region.rooms[27].links["open door;s"] = {}
          region.rooms[27].links["open door;s"].to = 917
          region.rooms[27].links["open door;s"].con = "k1:"
        region.rooms[27].links.n = {}
          region.rooms[27].links.n.to = 914
          region.rooms[27].links.n.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly lz;e;s;|!k1::open door;s|"
      region.rooms[28].name = "将军府大院"
      region.rooms[28].zone = "灵州"
      region.rooms[28].id = 917
      region.rooms[28].desc = "    这里是将军府的大院，当面一堵宽阔的白玉照壁，上书“忠心报国”四个大字，落款是当今西夏皇帝李元昊。一色的青砖铺地，有几个仆役正在院中洒扫，南面是内宅，西面是帐房，东面是个小院。"
      region.rooms[28].exits = "north"
      region.rooms[28].links = {}
        region.rooms[28].links.n = {}
          region.rooms[28].links.n.to = 916
          region.rooms[28].links.n.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly lz;e;e"
      region.rooms[29].name = "灵州东门"
      region.rooms[29].zone = "灵州"
      region.rooms[29].id = 918
      region.rooms[29].desc = "    这是东城门，城门正上方刻着几个西夏文字。城墙上贴着几张官府告示。一条路往东北通向城外一片松林。"
      region.rooms[29].exits = "northeast|west"
      region.rooms[29].links = {}
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 914
          region.rooms[29].links.w.con = ""
        region.rooms[29].links.ne = {}
          region.rooms[29].links.ne.to = 919
          region.rooms[29].links.ne.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly lz;e;e;ne"
      region.rooms[30].name = "落日林"
      region.rooms[30].zone = "灵州"
      region.rooms[30].id = 919
      region.rooms[30].desc = "    落日林位于灵州的东北，在西夏王陵和灵州的中间，延绵百里，多长的是红松。"
      region.rooms[30].exits = "north|southwest"
      region.rooms[30].links = {}
        region.rooms[30].links.sw = {}
          region.rooms[30].links.sw.to = 918
          region.rooms[30].links.sw.con = ""
        region.rooms[30].links.n = {}
          region.rooms[30].links.n.to = 920
          region.rooms[30].links.n.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly lz;e;e;ne;n"
      region.rooms[31].name = "林中大路"
      region.rooms[31].zone = "灵州"
      region.rooms[31].id = 920
      region.rooms[31].desc = "    这是山间的土路，勉强可以通行一辆大车，路面上有两条深深的车辙印，路边山坡上全是参天巨木，看上去密不透风，这里很幽静，除了偶尔几声鸟叫才能打破寂静。土路向北蜿蜒延伸转了个弯。"
      region.rooms[31].exits = "south|north|northeast"
      region.rooms[31].links = {}
        region.rooms[31].links.ne = {}
          region.rooms[31].links.ne.to = 926
          region.rooms[31].links.ne.con = ""
        region.rooms[31].links.s = {}
          region.rooms[31].links.s.to = 919
          region.rooms[31].links.s.con = ""
        region.rooms[31].links.n = {}
          region.rooms[31].links.n.to = 921
          region.rooms[31].links.n.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly lz;e;e;ne;n;n"
      region.rooms[32].name = "林中小路"
      region.rooms[32].zone = "灵州"
      region.rooms[32].id = 921
      region.rooms[32].desc = "    这是陡坡上的一条杂草丛生的羊肠小路，看起来平时没什么人迹，路边开着不知名的野花，两边的松树依然高大、挺拔。阳光透下来照的你身上是斑斑驳驳的影子。"
      region.rooms[32].exits = "south|north"
      region.rooms[32].links = {}
        region.rooms[32].links.s = {}
          region.rooms[32].links.s.to = 920
          region.rooms[32].links.s.con = ""
        region.rooms[32].links.n = {}
          region.rooms[32].links.n.to = 922
          region.rooms[32].links.n.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly lz;e;e;ne;n;n;n"
      region.rooms[33].name = "林中小路"
      region.rooms[33].zone = "灵州"
      region.rooms[33].id = 922
      region.rooms[33].desc = "    这是陡坡上的一条杂草丛生的羊肠小路，看起来平时没什么人迹，路边开着不知名的野花，两边的松树依然高大、挺拔。阳光透下来照的你身上是斑斑驳驳的影子。"
      region.rooms[33].exits = "south|east|west"
      region.rooms[33].links = {}
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 923
          region.rooms[33].links.e.con = ""
        region.rooms[33].links.s = {}
          region.rooms[33].links.s.to = 921
          region.rooms[33].links.s.con = ""
        region.rooms[33].links.w = {}
          region.rooms[33].links.w.to = 924
          region.rooms[33].links.w.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly lz;e;e;ne;n;n;n;e"
      region.rooms[34].name = "八仙道观"
      region.rooms[34].zone = "灵州"
      region.rooms[34].id = 923
      region.rooms[34].desc = "    这里是八仙道观，内有八仙殿，供着张果老、铁拐李、吕洞宾等八仙的塑像，香案上香烟缭绕。靠墙放着几张太师椅，地上放着几个蒲团。东西两侧是走廊，北边是东二巷， 南边是后院,种着些杨柳和老槐树，是道士们休息的地方。后院还有一口井，不过看上去有点异样。"
      region.rooms[34].exits = "west"
      region.rooms[34].links = {}
        region.rooms[34].links.w = {}
          region.rooms[34].links.w.to = 922
          region.rooms[34].links.w.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly lz;e;e;ne;n;n;n;w"
      region.rooms[35].name = "林中小路"
      region.rooms[35].zone = "灵州"
      region.rooms[35].id = 924
      region.rooms[35].desc = "    这是陡坡上的一条杂草丛生的羊肠小路，看起来平时没什么人迹，路边开着不知名的野花，两边的松树依然高大、挺拔。阳光透下来照的你身上是斑斑驳驳的影子。"
      region.rooms[35].exits = "east|west"
      region.rooms[35].links = {}
        region.rooms[35].links.e = {}
          region.rooms[35].links.e.to = 922
          region.rooms[35].links.e.con = ""
        region.rooms[35].links.w = {}
          region.rooms[35].links.w.to = 925
          region.rooms[35].links.w.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly lz;e;e;ne;n;n;n;w;w"
      region.rooms[36].name = "边门"
      region.rooms[36].zone = "灵州"
      region.rooms[36].id = 925
      region.rooms[36].desc = "    这里是皇宫的边门，供侍卫和内侍们出入之用，宫里所需的东西一般都由此运入，因为比较偏僻，守卫的卫士也不多。"
      region.rooms[36].exits = "east|west"
      region.rooms[36].links = {}
        region.rooms[36].links.e = {}
          region.rooms[36].links.e.to = 924
          region.rooms[36].links.e.con = ""
        region.rooms[36].links.w = {}
          region.rooms[36].links.w.to = 947
          region.rooms[36].links.w.con = "k1:"
    region.rooms[37] = {}
      region.rooms[37].path = "fly lz;e;e;ne;n;ne"
      region.rooms[37].name = "落日林"
      region.rooms[37].zone = "灵州"
      region.rooms[37].id = 926
      region.rooms[37].desc = "    这里是一片方圆百里的森林，林中古木参天，树荫蔽日，光线黯淡，落日林的伐木场就在这里，这里是树木大都树龄百年以上，数人和抱的大树比比皆是，一条不宽的土路蜿蜒通向前方。"
      region.rooms[37].exits = "north|southwest"
      region.rooms[37].links = {}
        region.rooms[37].links.sw = {}
          region.rooms[37].links.sw.to = 920
          region.rooms[37].links.sw.con = ""
        region.rooms[37].links.n = {}
          region.rooms[37].links.n.to = 927
          region.rooms[37].links.n.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly lz;e;e;ne;n;ne;n"
      region.rooms[38].name = "林中土路"
      region.rooms[38].zone = "灵州"
      region.rooms[38].id = 927
      region.rooms[38].desc = "    这是山间的土路，勉强可以通行一辆大车，路面上有两条深深的车辙印，路边山坡上全是参天巨木，看上去密不透风，这里很幽静，除了偶尔几声鸟叫才能打破寂静。土路向东北蜿蜒延伸转了个弯，西南面隐约可以看见林中一面大屋顶上的旗帜。"
      region.rooms[38].exits = "south|northeast"
      region.rooms[38].links = {}
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 926
          region.rooms[38].links.s.con = ""
        region.rooms[38].links.ne = {}
          region.rooms[38].links.ne.to = 928
          region.rooms[38].links.ne.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly lz;e;e;ne;n;ne;n;ne"
      region.rooms[39].name = "林中空地"
      region.rooms[39].zone = "灵州"
      region.rooms[39].id = 928
      region.rooms[39].desc = "    这是山谷中的一大块空地，错落有致的分布着数十幢木屋，炊烟袅袅的飘荡在上空，几个小孩正在追逐嬉闹，两条大狗没精打采的趴在屋檐下晒太阳，周围山坡上同样是巨木参天，看上去这里就象一个气氛祥和的小村。靠北的空地上有座大木屋看上去有点引人注目。西北和东北各有一条山路。"
      region.rooms[39].exits = "northwest|enter|southwest"
      region.rooms[39].links = {}
        region.rooms[39].links.enter = {}
          region.rooms[39].links.enter.to = 929
          region.rooms[39].links.enter.con = ""
        region.rooms[39].links.sw = {}
          region.rooms[39].links.sw.to = 927
          region.rooms[39].links.sw.con = ""
        region.rooms[39].links.nw = {}
          region.rooms[39].links.nw.to = 930
          region.rooms[39].links.nw.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly lz;e;e;ne;n;ne;n;ne;enter"
      region.rooms[40].name = "林中大屋"
      region.rooms[40].zone = "灵州"
      region.rooms[40].id = 929
      region.rooms[40].desc = "    这是一幢原木制成的三层高大建筑，看上去已有些年月但仍坚固异常，底层是由数根巨木架空，一座木梯通向二楼，三楼的楼顶上挂着一面绣着一条青龙的大旗，看上去已破旧不堪。人们只知道主人姓李。"
      region.rooms[40].exits = "out"
      region.rooms[40].links = {}
        region.rooms[40].links.out = {}
          region.rooms[40].links.out.to = 928
          region.rooms[40].links.out.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly lz;e;e;ne;n;ne;n;ne;nw"
      region.rooms[41].name = "清新泉"
      region.rooms[41].zone = "灵州"
      region.rooms[41].id = 930
      region.rooms[41].desc = "    这是山中的一口清泉，位于林场北面的山坡上，周围是翠绿的松树，潺潺的山泉水从泉眼缓缓的涌出，聚成一个小潭，小潭水又溢出流向山下，旁边一条小路通向山下。"
      region.rooms[41].exits = "southeast|northdown"
      region.rooms[41].links = {}
        region.rooms[41].links.se = {}
          region.rooms[41].links.se.to = 928
          region.rooms[41].links.se.con = ""
        region.rooms[41].links.nd = {}
          region.rooms[41].links.nd.to = 931
          region.rooms[41].links.nd.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly lz;e;e;ne;n;ne;n;ne;nw;nd"
      region.rooms[42].name = "西夏王陵"
      region.rooms[42].zone = "灵州"
      region.rooms[42].id = 931
      region.rooms[42].desc = "    这里是西夏历代皇帝的陵墓。座落在灵州西北，周围四山环抱，环境非常幽静，周围种满了苍松翠柏，其中当今西夏皇帝李元昊的父亲赵德明的陵墓最为雄伟，概因西夏虽自唐初开国，然直至宋初赵德明才称皇帝，所以李元昊常自比为李世民第二，而把他父亲陵墓造的异常宏大。"
      region.rooms[42].exits = "north|southup"
      region.rooms[42].links = {}
        region.rooms[42].links.su = {}
          region.rooms[42].links.su.to = 930
          region.rooms[42].links.su.con = ""
        region.rooms[42].links.n = {}
          region.rooms[42].links.n.to = 932
          region.rooms[42].links.n.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly lz;e;e;ne;n;ne;n;ne;nw;nd;n"
      region.rooms[43].name = "赤陵"
      region.rooms[43].zone = "灵州"
      region.rooms[43].id = 932
      region.rooms[43].desc = "    这是西夏前身平夏部开国之主拓跋赤辞的陵墓，因为年代久远而看上去有点破败，不大的石制坟头，几棵小草从石缝里伸出头来看着你，陵前的两棵松柏倒长得非常高大。毕竟是几百年前种的呀。"
      region.rooms[43].exits = "south|north"
      region.rooms[43].links = {}
        region.rooms[43].links.s = {}
          region.rooms[43].links.s.to = 931
          region.rooms[43].links.s.con = ""
        region.rooms[43].links.n = {}
          region.rooms[43].links.n.to = 933
          region.rooms[43].links.n.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly lz;e;e;ne;n;ne;n;ne;nw;nd;n;n"
      region.rooms[44].name = "德陵"
      region.rooms[44].zone = "灵州"
      region.rooms[44].id = 933
      region.rooms[44].desc = "    这就是李元昊的父亲赵德明的陵墓。宽十米高五米，为整个王陵中最高大也是最完整的建筑。陵前左右各有两个石人武士护卫，陵前有汉白玉栏杆围成的平台，上面石桌石凳一应俱全。"
      region.rooms[44].exits = "south|north"
      region.rooms[44].links = {}
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 932
          region.rooms[44].links.s.con = ""
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 934
          region.rooms[44].links.n.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly lz;e;e;ne;n;ne;n;ne;nw;nd;n;n;n"
      region.rooms[45].name = "恭陵"
      region.rooms[45].zone = "灵州"
      region.rooms[45].id = 934
      region.rooms[45].desc = "    这是西夏先主拓跋思恭的陵墓，拓跋思恭当年率党项羌族归顺唐太宗李世民而被赐姓为李，这李思恭在唐初也是极有名的大将。如今因为年代久远他的陵墓也不复当年的雄伟而看上去有点破败。"
      region.rooms[45].exits = "south"
      region.rooms[45].links = {}
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 933
          region.rooms[45].links.s.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly lz;n"
      region.rooms[46].name = "北大街"
      region.rooms[46].zone = "灵州"
      region.rooms[46].id = 935
      region.rooms[46].desc = "    这是灵州北大街，干净、宽敞、安静。双人合抱的杨树十步一株，整齐的排在路的两边。西面和东面都是高高的围墙，南面通向城中心，北面就是西夏皇宫大门了。因为是皇城和城中心的唯一连接通道，便不容许在两边开店，显得特别清静。"
      region.rooms[46].exits = "south|north"
      region.rooms[46].links = {}
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 890
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 936
          region.rooms[46].links.n.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly lz;n;n"
      region.rooms[47].name = "皇宫大门"
      region.rooms[47].zone = "灵州"
      region.rooms[47].id = 936
      region.rooms[47].desc = "    这里就是西夏皇宫正门，四扇宽阔的朱红大门，上面包着拳头大的铜钉。门的两边站着两排衣甲鲜明的武士，戒备深严。"
      region.rooms[47].exits = "south|north"
      region.rooms[47].links = {}
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 935
          region.rooms[47].links.s.con = ""
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 937
          region.rooms[47].links.n.con = "k1:"
    region.rooms[48] = {}
      region.rooms[48].path = "fly lz;n;n;|!k1::n|"
      region.rooms[48].name = "皇宫广场"
      region.rooms[48].zone = "灵州"
      region.rooms[48].id = 937
      region.rooms[48].desc = "    这里是皇宫广场。"
      region.rooms[48].exits = "south|north"
      region.rooms[48].links = {}
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 936
          region.rooms[48].links.s.con = ""
        region.rooms[48].links.n = {}
          region.rooms[48].links.n.to = 938
          region.rooms[48].links.n.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly lz;n;n;|!k1::n|;n"
      region.rooms[49].name = "皇宫走廊"
      region.rooms[49].zone = "灵州"
      region.rooms[49].id = 938
      region.rooms[49].desc = "    这里是皇宫走廊。"
      region.rooms[49].exits = "south|north|east|west"
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 943
          region.rooms[49].links.e.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 937
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 959
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.n = {}
          region.rooms[49].links.n.to = 939
          region.rooms[49].links.n.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly lz;n;n;|!k1::n|;n;n"
      region.rooms[50].name = "御花园"
      region.rooms[50].zone = "灵州"
      region.rooms[50].id = 939
      region.rooms[50].desc = "    一座漂亮的御花园，里面养了许多孔雀、。远远望见花木掩映中露出楼台一角，阁边挑出两盏宫灯。"
      region.rooms[50].exits = "south|north"
      region.rooms[50].links = {}
        region.rooms[50].links.s = {}
          region.rooms[50].links.s.to = 938
          region.rooms[50].links.s.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 940
          region.rooms[50].links.n.con = ""
    region.rooms[51] = {}
      region.rooms[51].path = "fly lz;n;n;|!k1::n|;n;n;n"
      region.rooms[51].name = "青凤阁大门"
      region.rooms[51].zone = "灵州"
      region.rooms[51].id = 940
      region.rooms[51].desc = "    这里是银川公主的居所。门口站着四名宫女，每人手提一盏轻纱灯笼，其后一名身披紫衫的女官，在招呼来宾进去奉茶。"
      region.rooms[51].exits = "south|north"
      region.rooms[51].links = {}
        region.rooms[51].links.s = {}
          region.rooms[51].links.s.to = 939
          region.rooms[51].links.s.con = ""
        region.rooms[51].links.n = {}
          region.rooms[51].links.n.to = 941
          region.rooms[51].links.n.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "fly lz;n;n;|!k1::n|;n;n;n;n"
      region.rooms[52].name = "凝香堂"
      region.rooms[52].zone = "灵州"
      region.rooms[52].id = 941
      region.rooms[52].desc = "    只见阁内好大一座厅堂，地下铺着厚厚的羊毛地毯，地毯上织了五彩花朵，鲜艳夺目。一张张小茶几排列成行，几上放着青花盖碗，每只盖碗旁一只青衣碟子，碟中装了奶酪、糕饼等四色点心。厅堂尽处有个高出三四尺的平台，铺了淡黄地毯，台上放着一张锦垫圆凳。"
      region.rooms[52].exits = "south|east"
      region.rooms[52].links = {}
        region.rooms[52].links.s = {}
          region.rooms[52].links.s.to = 940
          region.rooms[52].links.s.con = ""
        region.rooms[52].links.e = {}
          region.rooms[52].links.e.to = 942
          region.rooms[52].links.e.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "fly lz;n;n;|!k1::n|;n;n;n;n;e"
      region.rooms[53].name = "甬道"
      region.rooms[53].zone = "灵州"
      region.rooms[53].id = 942
      region.rooms[53].desc = "    一条长长的甬道。尽头是一扇石门（men）。"
      region.rooms[53].exits = "west"
      region.rooms[53].links = {}
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 941
          region.rooms[53].links.w.con = ""
        region.rooms[53].links["search;knock men;drop jinshu pian;enter"] = {}
          region.rooms[53].links["search;knock men;drop jinshu pian;enter"].to = 960
          region.rooms[53].links["search;knock men;drop jinshu pian;enter"].con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "fly lz;n;n;|!k1::n|;n;e"
      region.rooms[54].name = "皇宫走廊"
      region.rooms[54].zone = "灵州"
      region.rooms[54].id = 943
      region.rooms[54].desc = "    这里是皇宫走廊。"
      region.rooms[54].exits = "east|west"
      region.rooms[54].links = {}
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 938
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 944
          region.rooms[54].links.e.con = ""
    region.rooms[55] = {}
      region.rooms[55].path = "fly lz;n;n;|!k1::n|;n;e;e"
      region.rooms[55].name = "皇宫走廊"
      region.rooms[55].zone = "灵州"
      region.rooms[55].id = 944
      region.rooms[55].desc = "    这里是皇宫走廊。"
      region.rooms[55].exits = "north|west"
      region.rooms[55].links = {}
        region.rooms[55].links.w = {}
          region.rooms[55].links.w.to = 943
          region.rooms[55].links.w.con = ""
        region.rooms[55].links.n = {}
          region.rooms[55].links.n.to = 945
          region.rooms[55].links.n.con = ""
    region.rooms[56] = {}
      region.rooms[56].path = "fly lz;n;n;|!k1::n|;n;e;e;n"
      region.rooms[56].name = "皇宫走廊"
      region.rooms[56].zone = "灵州"
      region.rooms[56].id = 945
      region.rooms[56].desc = "    这里是皇宫走廊。"
      region.rooms[56].exits = "south|north"
      region.rooms[56].links = {}
        region.rooms[56].links.s = {}
          region.rooms[56].links.s.to = 944
          region.rooms[56].links.s.con = ""
        region.rooms[56].links.n = {}
          region.rooms[56].links.n.to = 946
          region.rooms[56].links.n.con = ""
    region.rooms[57] = {}
      region.rooms[57].path = "fly lz;n;n;|!k1::n|;n;e;e;n;n"
      region.rooms[57].name = "皇宫走廊"
      region.rooms[57].zone = "灵州"
      region.rooms[57].id = 946
      region.rooms[57].desc = "    这里是皇宫走廊。"
      region.rooms[57].exits = "south|east|north"
      region.rooms[57].links = {}
        region.rooms[57].links.e = {}
          region.rooms[57].links.e.to = 947
          region.rooms[57].links.e.con = ""
        region.rooms[57].links.s = {}
          region.rooms[57].links.s.to = 945
          region.rooms[57].links.s.con = ""
        region.rooms[57].links.n = {}
          region.rooms[57].links.n.to = 948
          region.rooms[57].links.n.con = ""
    region.rooms[58] = {}
      region.rooms[58].path = "fly lz;e;e;ne;n;n;n;w;w;|!k1::w|"
      region.rooms[58].name = "皇宫广场"
      region.rooms[58].zone = "灵州"
      region.rooms[58].id = 947
      region.rooms[58].desc = "    这里是皇宫广场。"
      region.rooms[58].exits = "east|west"
      region.rooms[58].links = {}
        region.rooms[58].links.w = {}
          region.rooms[58].links.w.to = 946
          region.rooms[58].links.w.con = ""
        region.rooms[58].links.e = {}
          region.rooms[58].links.e.to = 925
          region.rooms[58].links.e.con = ""
    region.rooms[59] = {}
      region.rooms[59].path = "fly lz;n;n;|!k1::n|;n;e;e;n;n;n"
      region.rooms[59].name = "皇宫走廊"
      region.rooms[59].zone = "灵州"
      region.rooms[59].id = 948
      region.rooms[59].desc = "    这里是皇宫走廊。"
      region.rooms[59].exits = "south|north"
      region.rooms[59].links = {}
        region.rooms[59].links.s = {}
          region.rooms[59].links.s.to = 946
          region.rooms[59].links.s.con = ""
        region.rooms[59].links.n = {}
          region.rooms[59].links.n.to = 949
          region.rooms[59].links.n.con = ""
    region.rooms[60] = {}
      region.rooms[60].path = "fly lz;n;n;|!k1::n|;n;e;e;n;n;n;n"
      region.rooms[60].name = "皇宫走廊"
      region.rooms[60].zone = "灵州"
      region.rooms[60].id = 949
      region.rooms[60].desc = "    这里是皇宫走廊。"
      region.rooms[60].exits = "south|west"
      region.rooms[60].links = {}
        region.rooms[60].links.s = {}
          region.rooms[60].links.s.to = 948
          region.rooms[60].links.s.con = ""
        region.rooms[60].links.w = {}
          region.rooms[60].links.w.to = 950
          region.rooms[60].links.w.con = ""
    region.rooms[61] = {}
      region.rooms[61].path = "fly lz;n;n;|!k1::n|;n;e;e;n;n;n;n;w"
      region.rooms[61].name = "皇宫走廊"
      region.rooms[61].zone = "灵州"
      region.rooms[61].id = 950
      region.rooms[61].desc = "    这里是皇宫走廊。"
      region.rooms[61].exits = "east|west"
      region.rooms[61].links = {}
        region.rooms[61].links.e = {}
          region.rooms[61].links.e.to = 949
          region.rooms[61].links.e.con = ""
        region.rooms[61].links.w = {}
          region.rooms[61].links.w.to = 951
          region.rooms[61].links.w.con = ""
    region.rooms[62] = {}
      region.rooms[62].path = "fly lz;n;n;|!k1::n|;n;e;e;n;n;n;n;w;w"
      region.rooms[62].name = "皇宫走廊"
      region.rooms[62].zone = "灵州"
      region.rooms[62].id = 951
      region.rooms[62].desc = "    这里是皇宫走廊。"
      region.rooms[62].exits = "north|east|west"
      region.rooms[62].links = {}
        region.rooms[62].links.e = {}
          region.rooms[62].links.e.to = 950
          region.rooms[62].links.e.con = ""
        region.rooms[62].links.w = {}
          region.rooms[62].links.w.to = 953
          region.rooms[62].links.w.con = ""
        region.rooms[62].links.n = {}
          region.rooms[62].links.n.to = 952
          region.rooms[62].links.n.con = ""
    region.rooms[63] = {}
      region.rooms[63].path = "fly lz;n;n;|!k1::n|;n;e;e;n;n;n;n;w;w;n"
      region.rooms[63].name = "皇宫走廊"
      region.rooms[63].zone = "灵州"
      region.rooms[63].id = 952
      region.rooms[63].desc = "    这里是皇宫走廊。"
      region.rooms[63].exits = "south"
      region.rooms[63].links = {}
        region.rooms[63].links.s = {}
          region.rooms[63].links.s.to = 951
          region.rooms[63].links.s.con = ""
    region.rooms[64] = {}
      region.rooms[64].path = "fly lz;n;n;|!k1::n|;n;w;w;n;n;n;n;e"
      region.rooms[64].name = "皇宫走廊"
      region.rooms[64].zone = "灵州"
      region.rooms[64].id = 953
      region.rooms[64].desc = "    这里是皇宫走廊。"
      region.rooms[64].exits = "east|west"
      region.rooms[64].links = {}
        region.rooms[64].links.e = {}
          region.rooms[64].links.e.to = 951
          region.rooms[64].links.e.con = ""
        region.rooms[64].links.w = {}
          region.rooms[64].links.w.to = 954
          region.rooms[64].links.w.con = ""
    region.rooms[65] = {}
      region.rooms[65].path = "fly lz;n;n;|!k1::n|;n;w;w;n;n;n;n"
      region.rooms[65].name = "皇宫走廊"
      region.rooms[65].zone = "灵州"
      region.rooms[65].id = 954
      region.rooms[65].desc = "    这里是皇宫走廊。"
      region.rooms[65].exits = "south|east"
      region.rooms[65].links = {}
        region.rooms[65].links.e = {}
          region.rooms[65].links.e.to = 953
          region.rooms[65].links.e.con = ""
        region.rooms[65].links.s = {}
          region.rooms[65].links.s.to = 955
          region.rooms[65].links.s.con = ""
    region.rooms[66] = {}
      region.rooms[66].path = "fly lz;n;n;|!k1::n|;n;w;w;n;n;n"
      region.rooms[66].name = "皇宫走廊"
      region.rooms[66].zone = "灵州"
      region.rooms[66].id = 955
      region.rooms[66].desc = "    这里是皇宫走廊。"
      region.rooms[66].exits = "south|north"
      region.rooms[66].links = {}
        region.rooms[66].links.s = {}
          region.rooms[66].links.s.to = 956
          region.rooms[66].links.s.con = ""
        region.rooms[66].links.n = {}
          region.rooms[66].links.n.to = 954
          region.rooms[66].links.n.con = ""
    region.rooms[67] = {}
      region.rooms[67].path = "fly lz;n;n;|!k1::n|;n;w;w;n;n"
      region.rooms[67].name = "皇宫走廊"
      region.rooms[67].zone = "灵州"
      region.rooms[67].id = 956
      region.rooms[67].desc = "    这里是皇宫走廊。"
      region.rooms[67].exits = "south|north"
      region.rooms[67].links = {}
        region.rooms[67].links.s = {}
          region.rooms[67].links.s.to = 957
          region.rooms[67].links.s.con = ""
        region.rooms[67].links.n = {}
          region.rooms[67].links.n.to = 955
          region.rooms[67].links.n.con = ""
    region.rooms[68] = {}
      region.rooms[68].path = "fly lz;n;n;|!k1::n|;n;w;w;n"
      region.rooms[68].name = "皇宫走廊"
      region.rooms[68].zone = "灵州"
      region.rooms[68].id = 957
      region.rooms[68].desc = "    这里是皇宫走廊。"
      region.rooms[68].exits = "south|north"
      region.rooms[68].links = {}
        region.rooms[68].links.s = {}
          region.rooms[68].links.s.to = 958
          region.rooms[68].links.s.con = ""
        region.rooms[68].links.n = {}
          region.rooms[68].links.n.to = 956
          region.rooms[68].links.n.con = ""
    region.rooms[69] = {}
      region.rooms[69].path = "fly lz;n;n;|!k1::n|;n;w;w"
      region.rooms[69].name = "皇宫走廊"
      region.rooms[69].zone = "灵州"
      region.rooms[69].id = 958
      region.rooms[69].desc = "    这里是皇宫走廊。"
      region.rooms[69].exits = "east|north"
      region.rooms[69].links = {}
        region.rooms[69].links.e = {}
          region.rooms[69].links.e.to = 959
          region.rooms[69].links.e.con = ""
        region.rooms[69].links.n = {}
          region.rooms[69].links.n.to = 957
          region.rooms[69].links.n.con = ""
    region.rooms[70] = {}
      region.rooms[70].path = "fly lz;n;n;|!k1::n|;n;w"
      region.rooms[70].name = "皇宫走廊"
      region.rooms[70].zone = "灵州"
      region.rooms[70].id = 959
      region.rooms[70].desc = "    这里是皇宫走廊。"
      region.rooms[70].exits = "east|west"
      region.rooms[70].links = {}
        region.rooms[70].links.e = {}
          region.rooms[70].links.e.to = 938
          region.rooms[70].links.e.con = ""
        region.rooms[70].links.w = {}
          region.rooms[70].links.w.to = 958
          region.rooms[70].links.w.con = ""
    region.rooms[71] = {}
      region.rooms[71].path = "fly lz;n;n;|!k1::n|;n;n;n;n;e;search;knock men;drop jinshu pian;enter"
      region.rooms[71].name = "甬道"
      region.rooms[71].zone = "灵州"
      region.rooms[71].id = 960
      region.rooms[71].desc = "    山内又是一条长甬道，两边石壁上燃着油灯。"
      region.rooms[71].exits = "north|out"
      region.rooms[71].links = {}
        region.rooms[71].links.out = {}
          region.rooms[71].links.out.to = 942
          region.rooms[71].links.out.con = ""
        region.rooms[71].links.n = {}
          region.rooms[71].links.n.to = 961
          region.rooms[71].links.n.con = ""
    region.rooms[72] = {}
      region.rooms[72].path = "fly lz;n;n;|!k1::n|;n;n;n;n;e;search;knock men;drop jinshu pian;enter;n"
      region.rooms[72].name = "幽兰涧"
      region.rooms[72].zone = "灵州"
      region.rooms[72].id = 961
      region.rooms[72].desc = "    在禁宫之中突然见到这样一条深涧，实是匪夷所思。涧旁点着四个明晃晃的火把，偶尔有身形婀娜，娉娉婷婷的从涧上凌空走了过去。涧旁有几块大岩石（stone）。"
      region.rooms[72].exits = "south"
      region.rooms[72].links = {}
	  region.rooms[72].nodig = true
        region.rooms[72].links.s = {}
          region.rooms[72].links.s.to = 960
          region.rooms[72].links.s.con = ""
        region.rooms[72].links["press jikuo;zou gangsi"] = {}
          region.rooms[72].links["press jikuo;zou gangsi"].to = 2983
          region.rooms[72].links["press jikuo;zou gangsi"].con = "ylj"
    region.rooms[73] = {}
      region.rooms[73].path = "fly lz;n;n;|!k1::n|;n;n;n;n;e;search;knock men;drop jinshu pian;enter;n;|!ylj:press jikuo;zou gangsi|"
      region.rooms[73].name = "幽兰涧"
      region.rooms[73].zone = "灵州"
      region.rooms[73].id = 2983
	  region.rooms[73].nodig = true
      region.rooms[73].links = {}
        region.rooms[73].links["press jikuo;zou gangsi"] = {}
          region.rooms[73].links["press jikuo;zou gangsi"].to = 961
          region.rooms[73].links["press jikuo;zou gangsi"].con = "ylj"
        region.rooms[73].links.n = {}
          region.rooms[73].links.n.to = 2984
          region.rooms[73].links.n.con = ""
      region.rooms[73].exits = "north"
      region.rooms[73].desc = "    在禁宫之中突然见到这样一条深涧，实是匪夷所思。涧旁点着四个明晃晃的火把，偶尔有身形婀娜，娉娉婷婷的从涧上凌空走了过去。涧旁有几块大岩石（stone）。"
    region.rooms[74] = {}
      region.rooms[74].path = "fly lz;n;n;|!k1::n|;n;n;n;n;e;search;knock men;drop jinshu pian;enter;n;|!ylj:press jikuo;zou gangsi|;n"
      region.rooms[74].name = "竹林"
      region.rooms[74].zone = "灵州"
      region.rooms[74].id = 2984
	  region.rooms[74].nodig = true
      region.rooms[74].links = {}
        region.rooms[74].links.s = {}
          region.rooms[74].links.s.to = 2983
          region.rooms[74].links.s.con = ""
        region.rooms[74].links.w = {}
          region.rooms[74].links.w.to = 2985
          region.rooms[74].links.w.con = ""
      region.rooms[74].exits = "south|west"
      region.rooms[74].desc = "    这里是一片茂密的竹林，西边通向一座厅堂。"
    region.rooms[75] = {}
      region.rooms[75].path = "fly lz;n;n;|!k1::n|;n;n;n;n;e;search;knock men;drop jinshu pian;enter;n;|!ylj:press jikuo;zou gangsi|;n;w"
      region.rooms[75].name = "厅堂"
      region.rooms[75].zone = "灵州"
      region.rooms[75].id = 2985
	  region.rooms[75].nodig = true
      region.rooms[75].links = {}
        region.rooms[75].links.e = {}
          region.rooms[75].links.e.to = 2984
          region.rooms[75].links.e.con = ""
		region.rooms[75].links["ask gong nv about 梦郎"] = {}
          region.rooms[75].links["ask gong nv about 梦郎"].to = 3035
          region.rooms[75].links["ask gong nv about 梦郎"].con = ""
      region.rooms[75].exits = "east"
      region.rooms[75].desc = "    这厅堂比之先前喝茶的凝香堂大了三有余，显然本是山峰中一个天然洞穴，再加上偌大人工修饰而成。厅壁打磨得十分光滑，到处挂满了字画。一般山洞都有湿气水滴，这所在却干燥异常，字画（zihua）悬在壁间，全无受潮之象。堂侧放着一张紫檀木的大书桌，桌上放了文房四宝，碑帖古玩，更有几座书架，三四张石凳、石几。"
	region.rooms[76] = {}
      region.rooms[76].path = "fly lz;n;n;|!k1::n|;n;n;n;n;e;search;knock men;drop jinshu pian;enter;n;|!ylj:press jikuo;zou gangsi|;n;w;ask gong nv about 梦郎"
      region.rooms[76].name = "内堂"
      region.rooms[76].zone = "灵州"
      region.rooms[76].id = 3035
      region.rooms[76].links = {}
        region.rooms[76].links.out = {}
          region.rooms[76].links.out.to = 2985
          region.rooms[76].links.out.con = ""
      region.rooms[76].exits = "out"
      region.rooms[76].desc = "    这里是银川公主的闺房，里面简单的布置了些梳妆用品。房间里一股淡淡的香气。"
  region.center = 890
return region