local region = {}
  region.cmd = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter"
  region.name = "明教1"
  region.id = "mj1"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter"
      region.rooms[1].name = "甬道"
      region.rooms[1].zone = "明教1"
      region.rooms[1].id = 3019
      region.rooms[1].links = {}
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 3020
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "north"
      region.rooms[1].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。向外的石门早已悄然合上，你只有鼓勇向前。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n"
      region.rooms[2].name = "石室"
      region.rooms[2].zone = "明教1"
      region.rooms[2].id = 3020
      region.rooms[2].links = {}
        region.rooms[2].links["open west;w"] = {}
          region.rooms[2].links["open west;w"].to = 3023
          region.rooms[2].links["open west;w"].con = ""
        region.rooms[2].links["open north;n"] = {}
          region.rooms[2].links["open north;n"].to = 3024
          region.rooms[2].links["open north;n"].con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 3019
          region.rooms[2].links.s.con = ""
        region.rooms[2].links["open east;e"] = {}
          region.rooms[2].links["open east;e"].to = 3021
          region.rooms[2].links["open east;e"].con = ""
      region.rooms[2].exits = "south"
      region.rooms[2].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open east;e"
      region.rooms[3].name = "石室"
      region.rooms[3].zone = "明教1"
      region.rooms[3].id = 3021
      region.rooms[3].links = {}
        region.rooms[3].links["open west;w"] = {}
          region.rooms[3].links["open west;w"].to = 3020
          region.rooms[3].links["open west;w"].con = ""
        region.rooms[3].links["open south;s"] = {}
          region.rooms[3].links["open south;s"].to = 3029
          region.rooms[3].links["open south;s"].con = ""
        region.rooms[3].links["open north;n"] = {}
          region.rooms[3].links["open north;n"].to = 3025
          region.rooms[3].links["open north;n"].con = ""
        region.rooms[3].links["open east;e"] = {}
          region.rooms[3].links["open east;e"].to = 3022
          region.rooms[3].links["open east;e"].con = ""
      region.rooms[3].exits = "west"
      region.rooms[3].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open west;w;open west;w"
      region.rooms[4].name = "石室"
      region.rooms[4].zone = "明教1"
      region.rooms[4].id = 3022
      region.rooms[4].links = {}
        region.rooms[4].links["open west;w"] = {}
          region.rooms[4].links["open west;w"].to = 3021
          region.rooms[4].links["open west;w"].con = ""
        region.rooms[4].links["open south;s"] = {}
          region.rooms[4].links["open south;s"].to = 3030
          region.rooms[4].links["open south;s"].con = ""
        region.rooms[4].links["open north;n"] = {}
          region.rooms[4].links["open north;n"].to = 3026
          region.rooms[4].links["open north;n"].con = ""
        region.rooms[4].links["open east;e"] = {}
          region.rooms[4].links["open east;e"].to = 3023
          region.rooms[4].links["open east;e"].con = ""
      region.rooms[4].exits = "west"
      region.rooms[4].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open west;w"
      region.rooms[5].name = "石室"
      region.rooms[5].zone = "明教1"
      region.rooms[5].id = 3023
      region.rooms[5].links = {}
        region.rooms[5].links["open west;w"] = {}
          region.rooms[5].links["open west;w"].to = 3022
          region.rooms[5].links["open west;w"].con = ""
        region.rooms[5].links["open south;s"] = {}
          region.rooms[5].links["open south;s"].to = 3031
          region.rooms[5].links["open south;s"].con = ""
        region.rooms[5].links["open north;n"] = {}
          region.rooms[5].links["open north;n"].to = 3027
          region.rooms[5].links["open north;n"].con = ""
        region.rooms[5].links["open east;e"] = {}
          region.rooms[5].links["open east;e"].to = 3020
          region.rooms[5].links["open east;e"].con = ""
      region.rooms[5].exits = "west"
      region.rooms[5].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open north;n"
      region.rooms[6].name = "石室"
      region.rooms[6].zone = "明教1"
      region.rooms[6].id = 3024
      region.rooms[6].links = {}
        region.rooms[6].links["open west;w"] = {}
          region.rooms[6].links["open west;w"].to = 3027
          region.rooms[6].links["open west;w"].con = ""
        region.rooms[6].links["open south;s"] = {}
          region.rooms[6].links["open south;s"].to = 3020
          region.rooms[6].links["open south;s"].con = ""
        region.rooms[6].links["open north;n"] = {}
          region.rooms[6].links["open north;n"].to = 3028
          region.rooms[6].links["open north;n"].con = ""
        region.rooms[6].links["open east;e"] = {}
          region.rooms[6].links["open east;e"].to = 3025
          region.rooms[6].links["open east;e"].con = ""
      region.rooms[6].exits = "south"
      region.rooms[6].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open north;n;open east;e"
      region.rooms[7].name = "石室"
      region.rooms[7].zone = "明教1"
      region.rooms[7].id = 3025
      region.rooms[7].links = {}
        region.rooms[7].links["open west;w"] = {}
          region.rooms[7].links["open west;w"].to = 3024
          region.rooms[7].links["open west;w"].con = ""
        region.rooms[7].links["open south;s"] = {}
          region.rooms[7].links["open south;s"].to = 3021
          region.rooms[7].links["open south;s"].con = ""
        region.rooms[7].links["open north;n"] = {}
          region.rooms[7].links["open north;n"].to = 3029
          region.rooms[7].links["open north;n"].con = ""
        region.rooms[7].links["open east;e"] = {}
          region.rooms[7].links["open east;e"].to = 3026
          region.rooms[7].links["open east;e"].con = ""
      region.rooms[7].exits = "west"
      region.rooms[7].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open west;w;open west;w;open north;n"
      region.rooms[8].name = "石室"
      region.rooms[8].zone = "明教1"
      region.rooms[8].id = 3026
      region.rooms[8].links = {}
        region.rooms[8].links["open west;w"] = {}
          region.rooms[8].links["open west;w"].to = 3025
          region.rooms[8].links["open west;w"].con = ""
        region.rooms[8].links["open south;s"] = {}
          region.rooms[8].links["open south;s"].to = 3022
          region.rooms[8].links["open south;s"].con = ""
        region.rooms[8].links["open north;n"] = {}
          region.rooms[8].links["open north;n"].to = 3030
          region.rooms[8].links["open north;n"].con = ""
        region.rooms[8].links["open east;e"] = {}
          region.rooms[8].links["open east;e"].to = 3027
          region.rooms[8].links["open east;e"].con = ""
      region.rooms[8].exits = "west"
      region.rooms[8].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open west;w;open north;n"
      region.rooms[9].name = "石室"
      region.rooms[9].zone = "明教1"
      region.rooms[9].id = 3027
      region.rooms[9].links = {}
        region.rooms[9].links["open west;w"] = {}
          region.rooms[9].links["open west;w"].to = 3026
          region.rooms[9].links["open west;w"].con = ""
        region.rooms[9].links["open south;s"] = {}
          region.rooms[9].links["open south;s"].to = 3023
          region.rooms[9].links["open south;s"].con = ""
        region.rooms[9].links["open north;n"] = {}
          region.rooms[9].links["open north;n"].to = 3031
          region.rooms[9].links["open north;n"].con = ""
        region.rooms[9].links["open east;e"] = {}
          region.rooms[9].links["open east;e"].to = 3024
          region.rooms[9].links["open east;e"].con = ""
      region.rooms[9].exits = "west"
      region.rooms[9].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open north;n;open north;n"
      region.rooms[10].name = "石室"
      region.rooms[10].zone = "明教1"
      region.rooms[10].id = 3028
      region.rooms[10].links = {}
        region.rooms[10].links["open west;w"] = {}
          region.rooms[10].links["open west;w"].to = 3031
          region.rooms[10].links["open west;w"].con = ""
        region.rooms[10].links["open south;s"] = {}
          region.rooms[10].links["open south;s"].to = 3024
          region.rooms[10].links["open south;s"].con = ""
        region.rooms[10].links["open north;n"] = {}
          region.rooms[10].links["open north;n"].to = 3032
          region.rooms[10].links["open north;n"].con = ""
        region.rooms[10].links["open east;e"] = {}
          region.rooms[10].links["open east;e"].to = 3029
          region.rooms[10].links["open east;e"].con = ""
      region.rooms[10].exits = "south"
      region.rooms[10].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open east;e;open south;s"
      region.rooms[11].name = "石室"
      region.rooms[11].zone = "明教1"
      region.rooms[11].id = 3029
      region.rooms[11].links = {}
        region.rooms[11].links["open west;w"] = {}
          region.rooms[11].links["open west;w"].to = 3028
          region.rooms[11].links["open west;w"].con = ""
        region.rooms[11].links["open south;s"] = {}
          region.rooms[11].links["open south;s"].to = 3025
          region.rooms[11].links["open south;s"].con = ""
        region.rooms[11].links["open north;n"] = {}
          region.rooms[11].links["open north;n"].to = 3021
          region.rooms[11].links["open north;n"].con = ""
        region.rooms[11].links["open east;e"] = {}
          region.rooms[11].links["open east;e"].to = 3030
          region.rooms[11].links["open east;e"].con = ""
      region.rooms[11].exits = "west"
      region.rooms[11].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open west;w;open west;w;open south;s"
      region.rooms[12].name = "石室"
      region.rooms[12].zone = "明教1"
      region.rooms[12].id = 3030
      region.rooms[12].links = {}
        region.rooms[12].links["open west;w"] = {}
          region.rooms[12].links["open west;w"].to = 3029
          region.rooms[12].links["open west;w"].con = ""
        region.rooms[12].links["open south;s"] = {}
          region.rooms[12].links["open south;s"].to = 3026
          region.rooms[12].links["open south;s"].con = ""
        region.rooms[12].links["open north;n"] = {}
          region.rooms[12].links["open north;n"].to = 3022
          region.rooms[12].links["open north;n"].con = ""
        region.rooms[12].links["open east;e"] = {}
          region.rooms[12].links["open east;e"].to = 3031
          region.rooms[12].links["open east;e"].con = ""
      region.rooms[12].exits = "west"
      region.rooms[12].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open west;w;open south;s"
      region.rooms[13].name = "石室"
      region.rooms[13].zone = "明教1"
      region.rooms[13].id = 3031
      region.rooms[13].links = {}
        region.rooms[13].links["open west;w"] = {}
          region.rooms[13].links["open west;w"].to = 3030
          region.rooms[13].links["open west;w"].con = ""
        region.rooms[13].links["open south;s"] = {}
          region.rooms[13].links["open south;s"].to = 3027
          region.rooms[13].links["open south;s"].con = ""
        region.rooms[13].links["open north;n"] = {}
          region.rooms[13].links["open north;n"].to = 3023
          region.rooms[13].links["open north;n"].con = ""
        region.rooms[13].links["open east;e"] = {}
          region.rooms[13].links["open east;e"].to = 3028
          region.rooms[13].links["open east;e"].con = ""
      region.rooms[13].exits = "west"
      region.rooms[13].desc = "    这是一条小小的甬道，周围都是石壁，极为坚硬，看来不是什么武功能打破的。石室里伸手不见无指，顺着石壁你摸索着好象周围有石门。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly mj;s;sd;s;sd;sd;sd;sd;out;sd;sd;sd;sd;w;w;enter;break men;enter;n;open north;n;open north;n;open north;n"
      region.rooms[14].name = "石室"
      region.rooms[14].zone = "明教1"
      region.rooms[14].id = 3032
      region.rooms[14].links = {}
        region.rooms[14].links["open south;s"] = {}
          region.rooms[14].links["open south;s"].to = 3028
          region.rooms[14].links["open south;s"].con = ""
      region.rooms[14].exits = "south|up"
      region.rooms[14].desc = "    这间石室极大，顶上垂下钟乳，显是天然的石洞。走了几步，突见地下倒着两具骷髅。骷髅身上衣服尚未烂尽，着得出是一男一女。走近两具骷髅，只见那女子右手抓着一柄晶光闪亮的匕首，插在她自己胸口。"
  region.center = 3019
return region