local region = {}
  region.cmd = "fly ns"
  region.name = "恒山"
  region.id = "ns"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd;n;n;wd;ed;d;nw;nw"
      region.rooms[1].name = "金龙峡"
      region.rooms[1].zone = "恒山"
      region.rooms[1].id = 1355
      region.rooms[1].desc = "    金龙峡又称唐峪，是进入恒山的入口。恒山一名太恒山，或称玄岳，是五岳中的北岳，道教以之为 \"第五小洞天\" 。它横亘三百余里，如一队行进中的队列，昔人以为 \"恒山如行\" 来相对 \"泰山如坐\" ，\"华山如立\"，\"嵩山如卧\"和\"衡山如飞\"。"
      region.rooms[1].exits = "southeast|northeast"
      region.rooms[1].links = {}
        region.rooms[1].links.ne = {}
          region.rooms[1].links.ne.to = 1088
          region.rooms[1].links.ne.con = ""
        region.rooms[1].links.se = {}
          region.rooms[1].links.se.to = 1356
          region.rooms[1].links.se.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd;n;n;wd;ed;d;nw"
      region.rooms[2].name = "翠屏谷"
      region.rooms[2].zone = "恒山"
      region.rooms[2].id = 1356
      region.rooms[2].desc = "    浑河在谷中冲刷而过，天峰岭和翠屏山分列峡谷两侧，绝壁千仞，犹如刀削斧劈，高耸入云，这里自古就是塞外通往内地的咽喉要道，真有一夫当关万夫莫开之势。"
      region.rooms[2].exits = "northwest|southeast"
      region.rooms[2].links = {}
        region.rooms[2].links.nw = {}
          region.rooms[2].links.nw.to = 1355
          region.rooms[2].links.nw.con = ""
        region.rooms[2].links.se = {}
          region.rooms[2].links.se.to = 1357
          region.rooms[2].links.se.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd;n;n;wd;ed;d"
      region.rooms[3].name = "翠屏谷"
      region.rooms[3].zone = "恒山"
      region.rooms[3].id = 1357
      region.rooms[3].desc = "    这里峡谷幽深，石壁陡直，两崖壁立，一涧中流。就在这地势绝险的恒山山谷中，却有数十殿堂悬挂在翠屏山腰。它们上载危岩，下临深谷，错落有致，如玉宇琼楼自空中冉冉降落。那就是悬空寺了。"
      region.rooms[3].exits = "up|northwest"
      region.rooms[3].links = {}
        region.rooms[3].links.nw = {}
          region.rooms[3].links.nw.to = 1356
          region.rooms[3].links.nw.con = ""
        region.rooms[3].links.u = {}
          region.rooms[3].links.u.to = 1358
          region.rooms[3].links.u.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd;n;n;wd;ed"
      region.rooms[4].name = "翠屏山道"
      region.rooms[4].zone = "恒山"
      region.rooms[4].id = 1358
      region.rooms[4].desc = "    你爬在翠屏山道上，石阶陡峭，近在目前。回头外望，恒山重峦叠嶂，林木幽深，倍感静谧。"
      region.rooms[4].exits = "westup|down"
      region.rooms[4].links = {}
        region.rooms[4].links.d = {}
          region.rooms[4].links.d.to = 1357
          region.rooms[4].links.d.con = ""
        region.rooms[4].links.wu = {}
          region.rooms[4].links.wu.to = 1359
          region.rooms[4].links.wu.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd;n;n;wd"
      region.rooms[5].name = "翠屏山道"
      region.rooms[5].zone = "恒山"
      region.rooms[5].id = 1359
      region.rooms[5].desc = "    你爬在翠屏山道上，树木遮天，难见天日。山林静谧，隐隐晨钟轻敲，一切尘俗尽皆洗尽，山深有静气，恒山本色。"
      region.rooms[5].exits = "eastdown|eastup"
      region.rooms[5].links = {}
        region.rooms[5].links.ed = {}
          region.rooms[5].links.ed.to = 1358
          region.rooms[5].links.ed.con = ""
        region.rooms[5].links.eu = {}
          region.rooms[5].links.eu.to = 1360
          region.rooms[5].links.eu.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd;n;n"
      region.rooms[6].name = "悬空寺北楼"
      region.rooms[6].zone = "恒山"
      region.rooms[6].id = 1360
      region.rooms[6].desc = "    这里是悬空寺的北门楼，也是北碑亭。登楼俯视，如临深渊，谷底仰望，如壁间丹凤。向南有悬空栈桥通往南楼。"
      region.rooms[6].exits = "up|south|westdown"
      region.rooms[6].links = {}
        region.rooms[6].links.u = {}
          region.rooms[6].links.u.to = 1361
          region.rooms[6].links.u.con = ""
        region.rooms[6].links.wd = {}
          region.rooms[6].links.wd.to = 1359
          region.rooms[6].links.wd.con = ""
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 1362
          region.rooms[6].links.s.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd;n;n;u"
      region.rooms[7].name = "三教殿"
      region.rooms[7].zone = "恒山"
      region.rooms[7].id = 1361
      region.rooms[7].desc = "    这里是全寺最高处的三教殿，也是悬空寺最大的殿宇。三层九脊，全部由每根插入崖石的木梁承受，真是 \"公输天巧\"， 古今奇迹。"
      region.rooms[7].exits = "down"
      region.rooms[7].links = {}
        region.rooms[7].links.d = {}
          region.rooms[7].links.d.to = 1360
          region.rooms[7].links.d.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd;n"
      region.rooms[8].name = "悬空栈桥"
      region.rooms[8].zone = "恒山"
      region.rooms[8].id = 1362
      region.rooms[8].desc = "    栈道悬于南北危楼之间，由无数的掾铺成，每节掾宽尺许，九节并排在一起，每根掾绑在铁索上，上铺木板，长数十丈，下临深渊。山风呼啸，惊心动魄。"
      region.rooms[8].exits = "south|north"
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 1363
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 1360
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd;nd"
      region.rooms[9].name = "悬空寺南楼"
      region.rooms[9].zone = "恒山"
      region.rooms[9].id = 1363
      region.rooms[9].desc = "    这里是悬空寺的南门楼，也是南碑亭。悬空寺于陡崖上凿石穴插悬梁为基，楼宇间栈桥相连。全寺面东座西，南北危楼对望，断崖分断，很是艰险。"
      region.rooms[9].exits = "north|southup"
      region.rooms[9].links = {}
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 1362
          region.rooms[9].links.n.con = ""
        region.rooms[9].links.su = {}
          region.rooms[9].links.su.to = 1364
          region.rooms[9].links.su.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w;nd"
      region.rooms[10].name = "梯式栈道"
      region.rooms[10].zone = "恒山"
      region.rooms[10].id = 1364
      region.rooms[10].desc = "    栈道悬于壁，由无数的掾铺成，每节掾宽尺许，九节并排在一起，每根掾插入岩壁，上铺木板，长约十丈，下临深渊。人必须踏上悬空的木板，紧攀铁索，屏息静气，缓步挪动，才能过去。"
      region.rooms[10].exits = "northdown|southup"
      region.rooms[10].links = {}
        region.rooms[10].links.nd = {}
          region.rooms[10].links.nd.to = 1363
          region.rooms[10].links.nd.con = ""
        region.rooms[10].links.su = {}
          region.rooms[10].links.su.to = 1365
          region.rooms[10].links.su.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly ns;wd;sd;sd;sd;sd;sw;sw;w"
      region.rooms[11].name = "云阁虹桥"
      region.rooms[11].zone = "恒山"
      region.rooms[11].id = 1365
      region.rooms[11].desc = "    过完栈道，就到云阁虹桥。前往恒山主峰见性峰，都要在这里跨过唐峪河。拱桥卧波，水天亮丽，倍觉胸襟舒畅。"
      region.rooms[11].exits = "east|northdown"
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 1366
          region.rooms[11].links.e.con = ""
        region.rooms[11].links.nd = {}
          region.rooms[11].links.nd.to = 1364
          region.rooms[11].links.nd.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly ns;wd;sd;sd;sd;sd;sw;sw"
      region.rooms[12].name = "大字岭"
      region.rooms[12].zone = "恒山"
      region.rooms[12].id = 1366
      region.rooms[12].desc = "    大字岭是入恒山必由之路。石壁上镌有 \"恒宗\" 二字，高可两丈，笔力遒劲，气势雄浑。"
      region.rooms[12].exits = "northeast|west"
      region.rooms[12].links = {}
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 1365
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.ne = {}
          region.rooms[12].links.ne.to = 1367
          region.rooms[12].links.ne.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly ns;wd;sd;sd;sd;sd;sw"
      region.rooms[13].name = "虎风口"
      region.rooms[13].zone = "恒山"
      region.rooms[13].id = 1367
      region.rooms[13].desc = "    过 \"步云桥\" ， \"望仙亭\" ，就到了一个峰回路转的陡峭路口，这里是一处风口，大风来处，声如虎啸，比别处强劲多多，故有是名。"
      region.rooms[13].exits = "northeast|west|southwest"
      region.rooms[13].links = {}
        region.rooms[13].links.ne = {}
          region.rooms[13].links.ne.to = 1369
          region.rooms[13].links.ne.con = ""
        region.rooms[13].links.sw = {}
          region.rooms[13].links.sw.to = 1366
          region.rooms[13].links.sw.con = ""
        region.rooms[13].links.w = {}
          region.rooms[13].links.w.to = 1368
          region.rooms[13].links.w.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly ns;wd;sd;sd;sd;sd;sw;w"
      region.rooms[14].name = "悬根松"
      region.rooms[14].zone = "恒山"
      region.rooms[14].id = 1368
      region.rooms[14].desc = "    就在虎风口这个风口险地，却有一株古松，虽被大风吹得树根裸露，千百年来仍迎风挺立，这就是恒山著名的 \"梵宫悬根\" 。"
      region.rooms[14].exits = "east"
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 1367
          region.rooms[14].links.e.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly ns;wd;sd;sd;sd;sd"
      region.rooms[15].name = "果老岭"
      region.rooms[15].zone = "恒山"
      region.rooms[15].id = 1369
      region.rooms[15].desc = "    光滑的岩面上断续分布着行行马蹄形凹坑，坑径三四寸，深寸许。传说这就是当年八仙中的张果老在恒山修道时，骑小毛驴由此登天。由于路陡坡滑，他不得不牵驴步行，留下这些脚印。后人诗云:  \"盘跚云路岭头那，凹石相传果老过，想是婆心来度世，故留遗迹使人摩。\" "
      region.rooms[15].exits = "northup|westdown|southwest"
      region.rooms[15].links = {}
        region.rooms[15].links.nu = {}
          region.rooms[15].links.nu.to = 1371
          region.rooms[15].links.nu.con = ""
        region.rooms[15].links.sw = {}
          region.rooms[15].links.sw.to = 1367
          region.rooms[15].links.sw.con = ""
        region.rooms[15].links.wd = {}
          region.rooms[15].links.wd.to = 1370
          region.rooms[15].links.wd.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly ns;wd;sd;sd;sd;sd;wd"
      region.rooms[16].name = "通元谷"
      region.rooms[16].zone = "恒山"
      region.rooms[16].id = 1370
      region.rooms[16].desc = "    通元谷孤处见性峰下，相传为张果老成仙前修道之所，由于他道号 \"通元\" ，这里也就成了通元谷。"
      region.rooms[16].exits = "eastup"
      region.rooms[16].links = {}
        region.rooms[16].links.eu = {}
          region.rooms[16].links.eu.to = 1369
          region.rooms[16].links.eu.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly ns;wd;sd;sd;sd"
      region.rooms[17].name = "北岳庙"
      region.rooms[17].zone = "恒山"
      region.rooms[17].id = 1371
      region.rooms[17].desc = "    北岳庙是个巍巍壮观的宫殿庙宇，山门三重，高列阜上，其下石阶数层。这里是北岳庙最大最高的 \"朝殿\" 。"
      region.rooms[17].exits = "east|northup|southdown|west"
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 1374
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 1373
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.sd = {}
          region.rooms[17].links.sd.to = 1369
          region.rooms[17].links.sd.con = ""
        region.rooms[17].links.nu = {}
          region.rooms[17].links.nu.to = 1372
          region.rooms[17].links.nu.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly ns;wd;sd;sd"
      region.rooms[18].name = "北岳殿"
      region.rooms[18].zone = "恒山"
      region.rooms[18].id = 1372
      region.rooms[18].desc = "    北岳殿上负绝壁，下临宫廨，下云级插天，庑门上下，穹碑森立。殿正中悬风字形匾，上书“贞元之殿”，殿内北岳恒山之神全身塑像，高可丈余。"
      region.rooms[18].exits = "westup|eastup|northup|southdown"
      region.rooms[18].links = {}
        region.rooms[18].links.nu = {}
          region.rooms[18].links.nu.to = 1376
          region.rooms[18].links.nu.con = ""
        region.rooms[18].links.eu = {}
          region.rooms[18].links.eu.to = 1377
          region.rooms[18].links.eu.con = ""
        region.rooms[18].links.sd = {}
          region.rooms[18].links.sd.to = 1371
          region.rooms[18].links.sd.con = ""
        region.rooms[18].links.wu = {}
          region.rooms[18].links.wu.to = 1375
          region.rooms[18].links.wu.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly ns;wd;sd;sd;sd;w"
      region.rooms[19].name = "鸡叫石"
      region.rooms[19].zone = "恒山"
      region.rooms[19].id = 1373
      region.rooms[19].desc = "    北岳庙的西侧，有一尺许见方的石头，称鸡叫石。击之， \"咯咯\" 作鸡鸣声，故名。清晨敲击，引起山谷回声，如群鸡争鸣，就称 \"金鸡报晓\" 。"
      region.rooms[19].exits = "east"
      region.rooms[19].links = {}
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 1371
          region.rooms[19].links.e.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly ns;wd;sd;sd;sd;e"
      region.rooms[20].name = "苦甜井"
      region.rooms[20].zone = "恒山"
      region.rooms[20].id = 1374
      region.rooms[20].desc = "    北岳庙的右下角，有二井相距不过三尺，而水质一苦一甜，称为苦甜井。甜井中水味清洌甘甜，道家弟子奉为圣水，游人到此，每感口枯舌燥，饮此水确有消暑清热之益。"
      region.rooms[20].exits = "west"
      region.rooms[20].links = {}
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 1371
          region.rooms[20].links.w.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly ns;wd;sd;sd;wu"
      region.rooms[21].name = "会仙台"
      region.rooms[21].zone = "恒山"
      region.rooms[21].id = 1375
      region.rooms[21].desc = "    走出北岳殿，就能看见一个石窟，紧靠在绝壁中凿出的一个小室，就是会仙台。台上排列群仙雕像，密密麻麻，不能胜数。"
      region.rooms[21].exits = "eastdown"
      region.rooms[21].links = {}
        region.rooms[21].links.ed = {}
          region.rooms[21].links.ed.to = 1372
          region.rooms[21].links.ed.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly ns;wd;sd"
      region.rooms[22].name = "见性峰山道"
      region.rooms[22].zone = "恒山"
      region.rooms[22].id = 1376
      region.rooms[22].desc = "    你走在见性峰山脊小路上，听着山下庙宇的钟鼓，眼前白云漂荡，感觉幽逸极了。"
      region.rooms[22].exits = "northup|southdown"
      region.rooms[22].links = {}
        region.rooms[22].links.sd = {}
          region.rooms[22].links.sd.to = 1372
          region.rooms[22].links.sd.con = ""
        region.rooms[22].links.nu = {}
          region.rooms[22].links.nu.to = 1378
          region.rooms[22].links.nu.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly ns;wd;sd;sd;eu"
      region.rooms[23].name = "玉羊游云"
      region.rooms[23].zone = "恒山"
      region.rooms[23].id = 1377
      region.rooms[23].desc = "    东峰峭壁崖顶上，白石累累，散布有致，在云雾拂动下，似有动感，象正在吃草的羊只。这就是和“金鸡报晓”齐名的恒山胜景“玉羊游云”。"
      region.rooms[23].exits = "westdown"
      region.rooms[23].links = {}
        region.rooms[23].links.wd = {}
          region.rooms[23].links.wd.to = 1372
          region.rooms[23].links.wd.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly ns;wd"
      region.rooms[24].name = "见性峰山道"
      region.rooms[24].zone = "恒山"
      region.rooms[24].id = 1378
      region.rooms[24].desc = "    你走在见性峰山脊小路上，听着山下庙宇的钟鼓，眼前白云漂荡，远远看到前面就是峰顶了。"
      region.rooms[24].exits = "eastup|southdown"
      region.rooms[24].links = {}
        region.rooms[24].links.sd = {}
          region.rooms[24].links.sd.to = 1376
          region.rooms[24].links.sd.con = ""
        region.rooms[24].links.eu = {}
          region.rooms[24].links.eu.to = 1379
          region.rooms[24].links.eu.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly ns"
      region.rooms[25].name = "见性峰广场"
      region.rooms[25].zone = "恒山"
      region.rooms[25].id = 1379
      region.rooms[25].desc = "    这里是恒山主峰见性峰峰顶的广场。在这里俯瞰群山，才理会得何以恒山是华夏北方万山之宗，这里也是威震江湖的恒山派的根本重地。"
      region.rooms[25].exits = "north|east|westdown"
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 1381
          region.rooms[25].links.e.con = ""
        region.rooms[25].links.wd = {}
          region.rooms[25].links.wd.to = 1378
          region.rooms[25].links.wd.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 1380
          region.rooms[25].links.n.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly ns;n"
      region.rooms[26].name = "白云庵"
      region.rooms[26].zone = "恒山"
      region.rooms[26].id = 1380
      region.rooms[26].desc = "    这里就是恒山派掌门人的居所。庵内供奉白衣观世音，除地上一个蒲团，四壁萧然。恒山派威震江湖，没想到主庵居然简朴一至如斯。"
      region.rooms[26].exits = "south"
      region.rooms[26].links = {}
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 1379
          region.rooms[26].links.s.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly ns;e"
      region.rooms[27].name = "见性峰小路"
      region.rooms[27].zone = "恒山"
      region.rooms[27].id = 1381
      region.rooms[27].desc = "    你走在见性峰小路上，小路的两旁松柏青青.听着山下庙宇的钟鼓，眼前白云漂荡，显得格外宁静。"
      region.rooms[27].exits = "east|west"
      region.rooms[27].links = {}
        region.rooms[27].links.w = {}
          region.rooms[27].links.w.to = 1379
          region.rooms[27].links.w.con = ""
        region.rooms[27].links.e = {}
          region.rooms[27].links.e.to = 1382
          region.rooms[27].links.e.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly ns;e;e"
      region.rooms[28].name = "见性峰小路"
      region.rooms[28].zone = "恒山"
      region.rooms[28].id = 1382
      region.rooms[28].desc = "    你走在见性峰小路上，这里更加幽静了,路旁的松柏也更浓更密了,庙宇的钟鼓声已几不可闻,路的尽头隐约是一栋房舍."
      region.rooms[28].exits = "east|west"
      region.rooms[28].links = {}
        region.rooms[28].links.w = {}
          region.rooms[28].links.w.to = 1381
          region.rooms[28].links.w.con = ""
        region.rooms[28].links.e = {}
          region.rooms[28].links.e.to = 1383
          region.rooms[28].links.e.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly ns;e;e;e"
      region.rooms[29].name = "木屋"
      region.rooms[29].zone = "恒山"
      region.rooms[29].id = 1383
      region.rooms[29].desc = "    这里便是师太们平时休息之地摆设极为简朴,仅放着几个蒲团和几个矮几.除此之外就没有别的什么了,旁边还有一个挂着竹帘的小门里面便是师太们的卧房."
      region.rooms[29].exits = "enter|west"
      region.rooms[29].links = {}
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 1382
          region.rooms[29].links.w.con = ""
        region.rooms[29].links.enter = {}
          region.rooms[29].links.enter.to = 1384
          region.rooms[29].links.enter.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly ns;e;e;e;enter"
      region.rooms[30].name = "卧房"
      region.rooms[30].zone = "恒山"
      region.rooms[30].id = 1384
      region.rooms[30].desc = "    这里就是白云庵师太们的卧房,陈设同样的简朴,室内虽大,但是空荡荡的,除了几张木椅和几个放置衣物的木柜外,就是几张朴实的木塌,师太们常在这修禅打坐."
      region.rooms[30].exits = "out"
      region.rooms[30].links = {}
        region.rooms[30].links.out = {}
          region.rooms[30].links.out.to = 1383
          region.rooms[30].links.out.con = ""
  region.center = 1379
return region