local region = {}
  region.cmd = "fly qc"
  region.name = "青城"
  region.id = "qc"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly qc;n;wd;sd;wd;sd;sd;ed;ed;ed;se;s;s;s;e"
      region.rooms[1].name = "青石大道"
      region.rooms[1].zone = "成都|青城"
      region.rooms[1].id = 682
      region.rooms[1].desc = "    你走在青石大道上。两边是稀硫的树林和连片的田野。一条条小溪和路平行，溪流清澈见底，水流甚急。"
      region.rooms[1].exits = "south|west"
      region.rooms[1].links = {}
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 681
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 1246
          region.rooms[1].links.w.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly qc;n;wd;sd;wd;sd;sd;ed;ed;ed;se;s;s;s"
      region.rooms[2].name = "青泥小道"
      region.rooms[2].zone = "青城"
      region.rooms[2].id = 1246
      region.rooms[2].desc = "    你走在青泥小道上。左边不远传来阵阵水响，原来那里就是天下知名都江堰。拦河分流，使岷江之水分注到无数小小溪流中，才免了连年的水祸，灌溉出了这富饶的成都平原。"
      region.rooms[2].exits = "east|north"
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 682
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 1247
          region.rooms[2].links.n.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly qc;n;wd;sd;wd;sd;sd;ed;ed;ed;se;s;s"
      region.rooms[3].name = "青石大道"
      region.rooms[3].zone = "青城"
      region.rooms[3].id = 1247
      region.rooms[3].desc = "    你走在青石大道上。远远传来细细的水声，掩盖在路边密密树林的风声中。望北可以看到一座大山了，苍苍翠翠，象一块清清纯纯的碧玉。"
      region.rooms[3].exits = "south|north"
      region.rooms[3].links = {}
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 1246
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 1248
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly qc;n;wd;sd;wd;sd;sd;ed;ed;ed;se;s"
      region.rooms[4].name = "小桥"
      region.rooms[4].zone = "青城"
      region.rooms[4].id = 1248
      region.rooms[4].desc = "    小桥横跨小溪上。溪水清澈，游鱼卵石斑驳可数。桥北面就是青城建福宫了。青城是道家发轫之处，号道教的“第五洞天”，相传东汉张陵在此结庐传授五斗米道，至今宫阙连绵，传道嗣法不绝。"
      region.rooms[4].exits = "south|north"
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 1247
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 1249
          region.rooms[4].links.n.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly qc;n;wd;sd;wd;sd;sd;ed;ed;ed;se"
      region.rooms[5].name = "建福宫"
      region.rooms[5].zone = "青城"
      region.rooms[5].id = 1249
      region.rooms[5].desc = "    建福宫旧称丈人观，以其座落丈人峰下故也。相传五岳丈人宁封子修道于此。院内树木假山，相互掩映；周围林木苍翠，浓荫蔽日，炎夏来此，十分凉爽。这里也是上山的起点。"
      region.rooms[5].exits = "south|northwest"
      region.rooms[5].links = {}
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 1248
          region.rooms[5].links.s.con = ""
        region.rooms[5].links.nw = {}
          region.rooms[5].links.nw.to = 1250
          region.rooms[5].links.nw.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly qc;n;wd;sd;wd;sd;sd;ed;ed;ed"
      region.rooms[6].name = "盘山磴道"
      region.rooms[6].zone = "青城"
      region.rooms[6].id = 1250
      region.rooms[6].desc = "    你走在盘山磴道上。山木蔽日，幽静宜人。过了“青城”木牌楼，西上就是天然图画了。东南方向是建福宫。"
      region.rooms[6].exits = "westup|southeast"
      region.rooms[6].links = {}
        region.rooms[6].links.se = {}
          region.rooms[6].links.se.to = 1249
          region.rooms[6].links.se.con = ""
        region.rooms[6].links.wu = {}
          region.rooms[6].links.wu.to = 1251
          region.rooms[6].links.wu.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly qc;n;wd;sd;wd;sd;sd;ed;ed"
      region.rooms[7].name = "天然图画"
      region.rooms[7].zone = "青城"
      region.rooms[7].id = 1251
      region.rooms[7].desc = "    这里岩壁矗立，绿树映辉，牌阁在山垭间巍然屹立。四顾峰奇石异，云雾缥缈，远近观赏，如在画中。阁左“天生桥”，一石丈余飞插石壁之间，十分险峻。"
      region.rooms[7].exits = "westup|north|eastdown"
      region.rooms[7].links = {}
        region.rooms[7].links.ed = {}
          region.rooms[7].links.ed.to = 1250
          region.rooms[7].links.ed.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 1252
          region.rooms[7].links.n.con = ""
        region.rooms[7].links.wu = {}
          region.rooms[7].links.wu.to = 1253
          region.rooms[7].links.wu.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly qc;n;wd;sd;wd;sd;sd;ed;ed;n"
      region.rooms[8].name = "驻鹤庄"
      region.rooms[8].zone = "青城"
      region.rooms[8].id = 1252
      region.rooms[8].desc = "    驻鹤庄相传为仙人休息赏玩之所。常有成群丹顶鹤栖息、飞鸣于林间。"
      region.rooms[8].exits = "south"
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 1251
          region.rooms[8].links.s.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly qc;n;wd;sd;wd;sd;sd;ed"
      region.rooms[9].name = "青城山路"
      region.rooms[9].zone = "青城"
      region.rooms[9].id = 1253
      region.rooms[9].desc = "    你走在青城山路上。山木蔽日，幽静宜人。西上就是天师洞，东边是天然图画。"
      region.rooms[9].exits = "westup|eastdown"
      region.rooms[9].links = {}
        region.rooms[9].links.ed = {}
          region.rooms[9].links.ed.to = 1251
          region.rooms[9].links.ed.con = ""
        region.rooms[9].links.wu = {}
          region.rooms[9].links.wu.to = 1254
          region.rooms[9].links.wu.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly qc;n;wd;sd;wd;sd;sd"
      region.rooms[10].name = "天师洞"
      region.rooms[10].zone = "青城"
      region.rooms[10].id = 1254
      region.rooms[10].desc = "    天师洞以东汉张陵在此讲道修炼而得名，又名古常道观。洞在山腰混元顶下峭壁间。中塑天师像，沿岩壁有廊可通。正殿名三皇殿，重檐回廊，雄锯高台，气势宏伟。内供伏羲、神农、轩辕三皇石刻造像。"
      region.rooms[10].exits = "east|north|eastdown|northup|west"
      region.rooms[10].links = {}
        region.rooms[10].links.ed = {}
          region.rooms[10].links.ed.to = 1253
          region.rooms[10].links.ed.con = ""
        region.rooms[10].links.nu = {}
          region.rooms[10].links.nu.to = 1259
          region.rooms[10].links.nu.con = ""
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 1257
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 1256
          region.rooms[10].links.w.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 1255
          region.rooms[10].links.n.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly qc;n;wd;sd;wd;sd;sd;n"
      region.rooms[11].name = "三清殿"
      region.rooms[11].zone = "青城"
      region.rooms[11].id = 1255
      region.rooms[11].desc = "    古常道观的中心是三清殿。殿中供奉三清教主：玉清原始天尊、上清灵宝天尊和太清太上老君。原始天尊手拿圆珠，象征洪元；灵宝天尊怀抱太极图，象征混元；太上老君手持扇子，象征太初。殿旁有一对联(lian)，著墨极浓。"
      region.rooms[11].exits = "south"
      region.rooms[11].links = {}
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 1254
          region.rooms[11].links.s.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly qc;n;wd;sd;wd;sd;sd;w"
      region.rooms[12].name = "古银杏树"
      region.rooms[12].zone = "青城"
      region.rooms[12].id = 1256
      region.rooms[12].desc = "    观前古银杏树相传为张天师手植，高可十余丈，腰围七、八人合抱，枝叶扶疏，苍盖如云。"
      region.rooms[12].exits = "east"
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 1254
          region.rooms[12].links.e.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly qc;n;wd;sd;wd;sd;sd;e"
      region.rooms[13].name = "三岛石"
      region.rooms[13].zone = "青城"
      region.rooms[13].id = 1257
      region.rooms[13].desc = "    三岛石上刻“降魔”二字，相传为张天师当年降魔，因巨石当道，挥剑力劈，石裂为三，成为三块相连的岛石。石裂处自然生成石梯。"
      region.rooms[13].exits = "eastdown|west"
      region.rooms[13].links = {}
        region.rooms[13].links.w = {}
          region.rooms[13].links.w.to = 1254
          region.rooms[13].links.w.con = ""
        region.rooms[13].links.ed = {}
          region.rooms[13].links.ed.to = 1258
          region.rooms[13].links.ed.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly qc;n;wd;sd;wd;sd;sd;e;ed"
      region.rooms[14].name = "听泉亭"
      region.rooms[14].zone = "青城"
      region.rooms[14].id = 1258
      region.rooms[14].desc = "    沿石梯向下，就是海棠溪。这里是溪上的听泉亭，四顾山环水绕，古藤蔓蔓，飞泉溅落池中，如琴弦轻拨，如珠落玉盘，清绝幽绝。"
      region.rooms[14].exits = "westup"
      region.rooms[14].links = {}
        region.rooms[14].links.wu = {}
          region.rooms[14].links.wu.to = 1257
          region.rooms[14].links.wu.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly qc;n;wd;sd;wd;sd"
      region.rooms[15].name = "古龙桥"
      region.rooms[15].zone = "青城"
      region.rooms[15].id = 1259
      region.rooms[15].desc = "    你走在古龙桥上。望见岩壁上一个大裂槽。宽二十余丈深，深达六、七丈，传说是张天师降魔时以笔划山而过的仙家痕迹。"
      region.rooms[15].exits = "northup|southdown"
      region.rooms[15].links = {}
        region.rooms[15].links.sd = {}
          region.rooms[15].links.sd.to = 1254
          region.rooms[15].links.sd.con = ""
        region.rooms[15].links.nu = {}
          region.rooms[15].links.nu.to = 1260
          region.rooms[15].links.nu.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly qc;n;wd;sd;wd"
      region.rooms[16].name = "祖师殿"
      region.rooms[16].zone = "青城"
      region.rooms[16].id = 1260
      region.rooms[16].desc = "    祖师殿又名真武宫。祖师殿背靠轩辕峰，面向白云溪，十分清幽。附近轩皇台，相传为黄帝受道处。"
      region.rooms[16].exits = "eastup|southdown"
      region.rooms[16].links = {}
        region.rooms[16].links.sd = {}
          region.rooms[16].links.sd.to = 1259
          region.rooms[16].links.sd.con = ""
        region.rooms[16].links.eu = {}
          region.rooms[16].links.eu.to = 1261
          region.rooms[16].links.eu.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly qc;n;wd;sd"
      region.rooms[17].name = "朝阳洞"
      region.rooms[17].zone = "青城"
      region.rooms[17].id = 1261
      region.rooms[17].desc = "    你来到朝阳洞。洞深广数丈，相传是宁封子栖息处。这里也是观日好去处，“古洞常临光照耀”，正是指旭日东升，霞光透过绿荫，射到洞口，一片璀灿绚丽的景色。"
      region.rooms[17].exits = "northup|westdown"
      region.rooms[17].links = {}
        region.rooms[17].links.wd = {}
          region.rooms[17].links.wd.to = 1260
          region.rooms[17].links.wd.con = ""
        region.rooms[17].links.nu = {}
          region.rooms[17].links.nu.to = 1262
          region.rooms[17].links.nu.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly qc;n;wd"
      region.rooms[18].name = "三弯九倒"
      region.rooms[18].zone = "青城"
      region.rooms[18].id = 1262
      region.rooms[18].desc = "    山势越来越陡峭，石梯几近壁立，拐过观日亭，远远看到青城山巅，高台山之阳的飞檐流瓦，上清宫到了。"
      region.rooms[18].exits = "eastup|southdown"
      region.rooms[18].links = {}
        region.rooms[18].links.sd = {}
          region.rooms[18].links.sd.to = 1261
          region.rooms[18].links.sd.con = ""
        region.rooms[18].links.eu = {}
          region.rooms[18].links.eu.to = 1263
          region.rooms[18].links.eu.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly qc;n"
      region.rooms[19].name = "上清宫"
      region.rooms[19].zone = "青城"
      region.rooms[19].id = 1263
      region.rooms[19].desc = "    上清宫是老君道场。宫前山门，矮树搭就，甚为灵动。宫内殿堂古色清雅，正殿供奉太上老君、吕纯阳和张三丰塑像。山前摩崖石刻 \"天下第五名山\" 气势浑厚，很是壮观。"
      region.rooms[19].exits = "south|westup|east|west|westdown"
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 1264
          region.rooms[19].links.s.con = ""
        region.rooms[19].links.wu = {}
          region.rooms[19].links.wu.to = 1267
          region.rooms[19].links.wu.con = ""
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 1266
          region.rooms[19].links.e.con = ""
        region.rooms[19].links.wd = {}
          region.rooms[19].links.wd.to = 1262
          region.rooms[19].links.wd.con = ""
        region.rooms[19].links.w = {}
          region.rooms[19].links.w.to = 1265
          region.rooms[19].links.w.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly qc"
      region.rooms[20].name = "松风观"
      region.rooms[20].zone = "青城"
      region.rooms[20].id = 1264
      region.rooms[20].desc = "    这里是松风观，是青城派总所。青城派威镇川中，以其人才辈出之故。当今掌门人余沧海道长，虽其貌不扬，身形矮小，却是青城一代宗师。观中陈设奢华，显见青城派财力不菲。"
      region.rooms[20].exits = "north"
      region.rooms[20].links = {}
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 1263
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly qc;n;w"
      region.rooms[21].name = "鸳鸯井"
      region.rooms[21].zone = "青城"
      region.rooms[21].id = 1265
      region.rooms[21].desc = "    上清殿左有鸳鸯井，一方一圆，泉流暗通。圆者水浊，方者水清。井水一温一凉，昔人题诗曰：“谁知上界神仙客，也与炎凉世态同”。"
      region.rooms[21].exits = "east"
      region.rooms[21].links = {}
        region.rooms[21].links.e = {}
          region.rooms[21].links.e.to = 1263
          region.rooms[21].links.e.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly qc;n;e"
      region.rooms[22].name = "麻姑池"
      region.rooms[22].zone = "青城"
      region.rooms[22].id = 1266
      region.rooms[22].desc = "    上清殿右是麻姑池，亦称天池。池深数尺，形如半月，水色清澈，四季久雨不盈，长旱不涸。"
      region.rooms[22].exits = "west"
      region.rooms[22].links = {}
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 1263
          region.rooms[22].links.w.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly qc;n;wu"
      region.rooms[23].name = "呼应亭"
      region.rooms[23].zone = "青城"
      region.rooms[23].id = 1267
      region.rooms[23].desc = "    呼应亭高居彭祖峰顶，是青城最高处。登临长啸，余音回荡，众山皆应。看雪岭光腾，红吞沧海，锦江春涨，绿到瀛洲。夏日夜分，有圣灯浮云，传说是神仙朝贺张天师所点仙灯，看来让人感叹不已。"
      region.rooms[23].exits = "eastdown"
      region.rooms[23].links = {}
        region.rooms[23].links.ed = {}
          region.rooms[23].links.ed.to = 1263
          region.rooms[23].links.ed.con = ""
  region.center = 1264
return region