local region = {}
  region.cmd = "fly qz"
  region.name = "泉州2"
  region.id = "qz2"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly qz;|!a:enter chuan:|;|!a:enter zhou:|"
      region.rooms[1].name = "赤嵌城"
      region.rooms[1].zone = "泉州"
      region.rooms[1].id = 3045
      region.rooms[1].links = {}
        region.rooms[1].links.eu = {}
          region.rooms[1].links.eu.to = 3046
          region.rooms[1].links.eu.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 3047
          region.rooms[1].links.n.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 3048
          region.rooms[1].links.s.con = ""
      region.rooms[1].exits = "south|eastup|north"
      region.rooms[1].desc = "    此地为台湾府驻所。台湾开化未久，国姓爷东征，收复此城，围困红毛鬼达两年之久，终致金瓯无缺。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly qz;|!a:enter chuan:|;|!a:enter zhou:|;eu"
      region.rooms[2].name = "日月潭"
      region.rooms[2].zone = "泉州"
      region.rooms[2].id = 3046
	  region.rooms[2].danger = 5
      region.rooms[2].links = {}
        region.rooms[2].links.wd = {}
          region.rooms[2].links.wd.to = 3045
          region.rooms[2].links.wd.con = ""
      region.rooms[2].exits = "westdown"
      region.rooms[2].desc = "    翠峰环抱，湖水澄碧的日月潭，潭北形如日轮，潭南弯曲如月，为台湾避暑胜地。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly qz;|!a:enter chuan:|;|!a:enter zhou:|;n"
      region.rooms[3].name = "鸡笼港"
      region.rooms[3].zone = "泉州"
      region.rooms[3].id = 3047
	  region.rooms[3].danger = 5
	  region.rooms[3].links = {}
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 3045
          region.rooms[3].links.s.con = ""
      region.rooms[3].exits = "south"
      region.rooms[3].desc = "    鸡笼为台湾北部良港。群山环抱的港口腹地广大，人烟稠密，有“台湾诸葛亮”之称的陈永华先生在此垦田养桑，修养生息，遗爱甚长。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly qz;|!a:enter chuan:|;|!a:enter zhou:|;s"
      region.rooms[4].name = "打狗港"
      region.rooms[4].zone = "泉州"
      region.rooms[4].id = 3048
	  region.rooms[4].danger = 5
      region.rooms[4].links = {}
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 3045
          region.rooms[4].links.n.con = ""
      region.rooms[4].exits = "north"
      region.rooms[4].desc = "    打狗港位于台湾南部，港域口小腹大，外有岛链环抱，内具曲折峡湾，诚全台第一良港。"
  region.center = 3045
return region