local region = {}
  region.cmd = "fly qzj"
  region.name = "全真教"
  region.id = "qzj"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly wm;e;s;s"
      region.rooms[1].name = "中央广场"
      region.rooms[1].zone = "扬州|全真教"
      region.rooms[1].id = 40
      region.rooms[1].desc = "    这里是城市的正中心，一个很宽阔的广场，铺着青石地面。一些游手好闲的人在这里溜溜达达，经常有艺人在这里表演。中央有一棵大榕树，盘根错节，据传已有千年的树龄，是这座城市的历史见证。树干底部有一个很大的树洞 (dong)。 你可以看到北边有来自各地的行人来来往往，南面人声鼎沸，一派繁华景象，东边不时地传来朗朗的读书声，西边则见不到几个行人，一片肃静。"
      region.rooms[1].exits = "south|north|east|west"
      region.rooms[1].links = {}
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 41
          region.rooms[1].links.s.con = ""
        region.rooms[1].links["climb tree"] = {}
          region.rooms[1].links["climb tree"].con = "k1:流氓头"
          region.rooms[1].links["climb tree"].to = 67
          region.rooms[1].links["climb tree"].block = "y"
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 68
          region.rooms[1].links.e.con = ""
        region.rooms[1].links["enter dong"] = {}
          region.rooms[1].links["enter dong"].to = 117
          region.rooms[1].links["enter dong"].con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 97
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 34
          region.rooms[1].links.n.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly qzj"
      region.rooms[2].name = "重阳宫大门"
      region.rooms[2].zone = "终南山|全真教"
      region.rooms[2].id = 1147
      region.rooms[2].links = {}
        region.rooms[2].links.wd = {}
          region.rooms[2].links.wd.to = 1142
          region.rooms[2].links.wd.con = ""
        region.rooms[2].links["knock gate;e"] = {}
          region.rooms[2].links["knock gate;e"].to = 1194
          region.rooms[2].links["knock gate;e"].con = ""
      region.rooms[2].exits = "westdown"
      region.rooms[2].desc = "    你已走到了终南山半山腰，前面就是全真教的总部重阳宫了。殿宇依山而筑，高低错落有致。周围古木森森，翠竹成林，景色清幽。正前方黄墙碧瓦，飞檐翘檩，正中一道二丈来宽，三丈来高的朱红杉木包铜大门(gate)，气势不凡。门上挂着一块匾(bian)，门前的石柱上挂着一副对联(duilian)。"
    region.rooms[3] = {}
      region.rooms[3].path = "|!c:qling:fly qzj;knock gate|;e"
      region.rooms[3].name = "大堂一进"
      region.rooms[3].zone = "全真教"
      region.rooms[3].id = 1194
      region.rooms[3].desc = "    这里是大堂，是全真教接待客人的地方。堂很大，几十张桌椅一字排开也丝毫不显拥挤。地下铺着整齐的青砖，几名道童正忙前忙后地端茶送水招呼客人。"
      region.rooms[3].exits = "south|north|east|west"
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 1200
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 1147
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 1197
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 1195
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "|!c:qling:fly qzj;knock gate|;e;n"
      region.rooms[4].name = "会真堂"
      region.rooms[4].zone = "全真教"
      region.rooms[4].id = 1195
      region.rooms[4].desc = "    这里是大堂旁边的一个侧厅，也是接待重要客人的地方。厅不大，只摆放着一张桌子和几把椅子。桌上摆放着一盆青松山石的盆景，墙壁上挂着一些字画。"
      region.rooms[4].exits = "south|north|east"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 1201
          region.rooms[4].links.e.con = ""
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 1194
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 1196
          region.rooms[4].links.n.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "|!c:qling:fly qzj;knock gate|;e;n;n"
      region.rooms[5].name = "万物堂"
      region.rooms[5].zone = "全真教"
      region.rooms[5].id = 1196
      region.rooms[5].desc = "    这里是全真七子之五王处一的居所。房间不大，收拾的素雅整洁，墙上挂着一萧一琴和一些字画，小几上摆放着宣纸和徽墨狼毫，不知道主人是要练字还是绘画。"
      region.rooms[5].exits = "south"
      region.rooms[5].links = {}
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 1195
          region.rooms[5].links.s.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "|!c:qling:fly qzj;knock gate|;e;s"
      region.rooms[6].name = "显真堂"
      region.rooms[6].zone = "全真教"
      region.rooms[6].id = 1197
      region.rooms[6].desc = "    这里是大堂旁边的一个侧厅，也是接待重要客人的地方。厅不大，只摆放着一张桌子和几把椅子。桌上摆放着一盆高山流水的盆景，墙壁上挂着一些字画。西面有一间药剂室，是配药的地方。"
      region.rooms[6].exits = "south|north|east|west"
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 1203
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 1198
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 1199
          region.rooms[6].links.w.con = ""
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 1194
          region.rooms[6].links.n.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "|!c:qling:fly qzj;knock gate|;e;s;s"
      region.rooms[7].name = "容物堂"
      region.rooms[7].zone = "全真教"
      region.rooms[7].id = 1198
      region.rooms[7].desc = "    这里是全真七子之二谭处端的居室，这间房间收拾的和普通的民居没什么区别，只是一尘不染，墙上斜挂着一把宝剑。"
      region.rooms[7].exits = "north"
      region.rooms[7].links = {}
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 1197
          region.rooms[7].links.n.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "|!c:qling:fly qzj;knock gate|;e;s;w"
      region.rooms[8].name = "药剂室"
      region.rooms[8].zone = "全真教"
      region.rooms[8].id = 1199
      region.rooms[8].desc = "    这里是全真教制药、配药的地方。这间房间本来很大，只是被前后左右堆放的药柜药箱挤的显得小多了。药柜已经很陈旧了，不过是用上好的南海沉香木做成的，据说用这种木材做成的柜子用来储藏东西不会遭虫蛀。一位道长站在这里，全真教的弟子可以向他申请采药和炼丹的任务。(ask zhangyao about job)"
      region.rooms[8].exits = "south|east"
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 1197
          region.rooms[8].links.e.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "|!c:qling:fly qzj;knock gate|;e;e"
      region.rooms[9].name = "大堂二进"
      region.rooms[9].zone = "全真教"
      region.rooms[9].id = 1200
      region.rooms[9].desc = "    这里是大堂的第二重，是全真教弟子做功课的所在。现在还不到功课时间，大堂里空荡荡的，只有全真教掌管上下杂事的掌理道长带领着几个小道童在整理桌椅，预备餐饭。"
      region.rooms[9].exits = "south|north|east|west"
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 1205
          region.rooms[9].links.e.con = ""
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 1194
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 1203
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 1201
          region.rooms[9].links.n.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "|!c:qling:fly qzj;knock gate|;e;e;n"
      region.rooms[10].name = "侧堂"
      region.rooms[10].zone = "全真教"
      region.rooms[10].id = 1201
      region.rooms[10].desc = "    这里是大堂旁边的一个侧厅，也是接待重要客人的地方。厅不大，只摆放着一张桌子和几把椅子。桌上摆放着一盆青松山石的盆景，墙壁上挂着一些字画。"
      region.rooms[10].exits = "south|north|east|west"
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 1206
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 1200
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 1195
          region.rooms[10].links.w.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 1202
          region.rooms[10].links.n.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "|!c:qling:fly qzj;knock gate|;e;e;n;n"
      region.rooms[11].name = "事为室"
      region.rooms[11].zone = "全真教"
      region.rooms[11].id = 1202
      region.rooms[11].desc = "    这里是全真七子之首马钰的居室。房间很小，只摆放了一张床、一张书桌和一把椅子。书桌上放着一本‘老子’，只看了一半，床上被褥折叠得整整齐齐。"
      region.rooms[11].exits = "south"
      region.rooms[11].links = {}
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 1201
          region.rooms[11].links.s.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "|!c:qling:fly qzj;knock gate|;e;e;s"
      region.rooms[12].name = "偏殿"
      region.rooms[12].zone = "全真教"
      region.rooms[12].id = 1203
      region.rooms[12].desc = "    这里是大堂旁边的一个侧厅，也是接待重要客人的地方。厅不大，只摆放着一张桌子和几把椅子。桌上摆放着一盆青山隐隐的盆景，墙壁上挂着一些字画。"
      region.rooms[12].exits = "south|north|east|west"
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 1211
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 1197
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 1204
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 1200
          region.rooms[12].links.n.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "|!c:qling:fly qzj;knock gate|;e;e;s;s"
      region.rooms[13].name = "广宁居"
      region.rooms[13].zone = "全真教"
      region.rooms[13].id = 1204
      region.rooms[13].desc = "    这里是全真七子之六郝大通的卧室，卧室很小，除了一张小床，一张小茶几而外没有什么别的摆设。茶几晶萤透明，仔细一看，原来几面是用整块的玉琢磨成的。茶几上摆放着几本先天课术的书，还有一些卜卦用的金钱。"
      region.rooms[13].exits = "north"
      region.rooms[13].links = {}
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 1203
          region.rooms[13].links.n.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "|!c:qling:fly qzj;knock gate|;e;e;e"
      region.rooms[14].name = "大堂三进"
      region.rooms[14].zone = "全真教"
      region.rooms[14].id = 1205
      region.rooms[14].desc = "    这里是大堂的第三进，是全真教弟子议事的地方。全真教祖师王重阳王真人最近闭关修炼，教内的俗事一般都交给大弟子马钰来处理。遇有事时，马真人便会召集六位师弟师妹，包括三代弟子中的部分大弟子来到此地议事。"
      region.rooms[14].exits = "south|north|east|west"
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 1213
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 1200
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 1211
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 1206
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "|!c:qling:fly qzj;knock gate|;e;e;e;n"
      region.rooms[15].name = "过真殿"
      region.rooms[15].zone = "全真教"
      region.rooms[15].id = 1206
      region.rooms[15].desc = "    这里是大堂旁边的一个侧殿，也是接待重要客人的地方。殿不大，只摆放着一张桌子和几把椅子。桌上摆放着一盆青山隐隐的盆景，墙壁上挂着一些字画。从这里往北，好象有一座四层的小塔。"
      region.rooms[15].exits = "south|north|west"
      region.rooms[15].links = {}
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 1205
          region.rooms[15].links.s.con = ""
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 1201
          region.rooms[15].links.w.con = ""
        region.rooms[15].links.n = {}
          region.rooms[15].links.n.to = 1207
          region.rooms[15].links.n.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "|!c:qling:fly qzj;knock gate|;e;e;e;n;n"
      region.rooms[16].name = "存道塔一层"
      region.rooms[16].zone = "全真教"
      region.rooms[16].id = 1207
      region.rooms[16].desc = "    这里是存道塔的一层，存道塔是当年全真弟子用来存放经书的地方，塔不高，是用一块一块的大青石砌起来的。塔中的梯子也是用青石所砌，据说之所以用石头砌塔是为了避免失火，烧毁了全真教的经书。"
      region.rooms[16].exits = "westup|south"
      region.rooms[16].links = {}
        region.rooms[16].links.s = {}
          region.rooms[16].links.s.to = 1206
          region.rooms[16].links.s.con = ""
        region.rooms[16].links.wu = {}
          region.rooms[16].links.wu.to = 1208
          region.rooms[16].links.wu.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "|!c:qling:fly qzj;knock gate|;e;e;e;n;n;wu"
      region.rooms[17].name = "存道塔二层"
      region.rooms[17].zone = "全真教"
      region.rooms[17].id = 1208
      region.rooms[17].desc = "    这里是存道塔的二层，塔梯绕着塔内向塔顶延伸。这里空空如也，经书也许全被全真弟子们借去阅读了。"
      region.rooms[17].exits = "eastdown|eastup"
      region.rooms[17].links = {}
        region.rooms[17].links.ed = {}
          region.rooms[17].links.ed.to = 1207
          region.rooms[17].links.ed.con = ""
        region.rooms[17].links.eu = {}
          region.rooms[17].links.eu.to = 1209
          region.rooms[17].links.eu.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "|!c:qling:fly qzj;knock gate|;e;e;e;n;n;wu;eu"
      region.rooms[18].name = "存道塔三层"
      region.rooms[18].zone = "全真教"
      region.rooms[18].id = 1209
      region.rooms[18].desc = "    这里是存道塔的三层，塔梯绕着塔内向塔顶延伸。这里空空如也，经书也许全被全真弟子们借去阅读了。"
      region.rooms[18].exits = "westup|westdown"
      region.rooms[18].links = {}
        region.rooms[18].links.wd = {}
          region.rooms[18].links.wd.to = 1208
          region.rooms[18].links.wd.con = ""
        region.rooms[18].links.wu = {}
          region.rooms[18].links.wu.to = 1210
          region.rooms[18].links.wu.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "|!c:qling:fly qzj;knock gate|;e;e;e;n;n;wu;eu;wu"
      region.rooms[19].name = "存道塔顶"
      region.rooms[19].zone = "全真教"
      region.rooms[19].id = 1210
      region.rooms[19].desc = "    这里是存道塔的塔顶，塔梯到这里就到了尽头。墙壁上开着几个窗户(window)，一个中年道人正捧着一本书苦苦研读。天色昏暗，桌上摆放着一支蜡烛(candle)，却没有点着。"
      region.rooms[19].exits = "eastdown"
      region.rooms[19].links = {}
        region.rooms[19].links.ed = {}
          region.rooms[19].links.ed.to = 1209
          region.rooms[19].links.ed.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "|!c:qling:fly qzj;knock gate|;e;e;e;s"
      region.rooms[20].name = "乃容殿"
      region.rooms[20].zone = "全真教"
      region.rooms[20].id = 1211
      region.rooms[20].desc = "    这里是大堂旁边的一个侧殿，也是接待重要客人的地方。殿不大，只摆放着一张桌子和几把椅子。桌上摆放着一盆青山隐隐的盆景，墙壁上挂着一些字画。"
      region.rooms[20].exits = "south|north|west"
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 1212
          region.rooms[20].links.s.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 1203
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 1205
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "|!c:qling:fly qzj;knock gate|;e;e;e;s;s"
      region.rooms[21].name = "清净居"
      region.rooms[21].zone = "全真教"
      region.rooms[21].id = 1212
      region.rooms[21].desc = "    这里是全真七子之末，也是唯一的女弟子孙不二的居室。这房间窗明几净，和她几位师兄的卧室大不相同。床上折叠着一件道袍，袍上绣着一个骷髅头。这骷髅头可不是随便绣来吓人的，是当年王重阳收孙不二为徒时，画了一副骷髅图案给她，意思是说人生苦短，得道为安。孙不二感念师恩，就将这个骷髅图案绣在自己的道袍上。"
      region.rooms[21].exits = "north"
      region.rooms[21].links = {}
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 1211
          region.rooms[21].links.n.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e"
      region.rooms[22].name = "老君殿"
      region.rooms[22].zone = "全真教"
      region.rooms[22].id = 1213
      region.rooms[22].desc = "    这里是供奉太上老君的大殿。殿的正中塑着老君的塑像，老君骑在青牛上，正临云而去。两旁塑着两个童子，都栩栩如生。殿中的地都是以青砖一块块的铺成，打扫得一尘不染。"
      region.rooms[22].exits = "south|north|east|west"
      region.rooms[22].links = {}
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 1216
          region.rooms[22].links.e.con = ""
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 1205
          region.rooms[22].links.w.con = ""
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 1215
          region.rooms[22].links.s.con = ""
        region.rooms[22].links.n = {}
          region.rooms[22].links.n.to = 1214
          region.rooms[22].links.n.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;n"
      region.rooms[23].name = "元始殿"
      region.rooms[23].zone = "全真教"
      region.rooms[23].id = 1214
      region.rooms[23].desc = "    这里是供奉元始天尊的大殿。殿内香烟缭绕，正中央塑着元始天尊的金身，旁边还塑着几位道友如太乙、俱留孙、云中子、广和子等等的像，正聚在一处或躺或坐，或棋或茶。"
      region.rooms[23].exits = "south"
      region.rooms[23].links = {}
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 1213
          region.rooms[23].links.s.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;s"
      region.rooms[24].name = "通天殿"
      region.rooms[24].zone = "全真教"
      region.rooms[24].id = 1215
      region.rooms[24].desc = "    这里是供奉三清之末--通天教主的大殿，殿内的香烟不甚旺盛。在通天教主的金身旁边，塑着几位截教道友象长耳仙、归云仙、申公豹的塑像。"
      region.rooms[24].exits = "north"
      region.rooms[24].links = {}
        region.rooms[24].links.n = {}
          region.rooms[24].links.n.to = 1213
          region.rooms[24].links.n.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e"
      region.rooms[25].name = "后堂一进"
      region.rooms[25].zone = "全真教"
      region.rooms[25].id = 1216
      region.rooms[25].desc = "    这里是后堂的一进，是平常全真教弟子休息的地方。由于全真教现在广收弟子，堂中摆放的桌椅也不断增加，显得这个堂已经很拥挤了。"
      region.rooms[25].exits = "east|west"
      region.rooms[25].links = {}
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 1213
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 1217
          region.rooms[25].links.e.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e"
      region.rooms[26].name = "后堂二进"
      region.rooms[26].zone = "全真教"
      region.rooms[26].id = 1217
      region.rooms[26].desc = "    这里是全真教弟子平常研讨武功的地方，这个堂不大，由于经常要在这里演武，索性连桌椅也全都靠到墙边去了，这样腾出了一大片空地来。"
      region.rooms[26].exits = "south|north|east|west"
      region.rooms[26].links = {}
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 1224
          region.rooms[26].links.e.con = ""
        region.rooms[26].links.w = {}
          region.rooms[26].links.w.to = 1216
          region.rooms[26].links.w.con = ""
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 1225
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.n = {}
          region.rooms[26].links.n.to = 1218
          region.rooms[26].links.n.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;n"
      region.rooms[27].name = "练功房"
      region.rooms[27].zone = "全真教"
      region.rooms[27].id = 1218
      region.rooms[27].desc = "    这里是全真教弟子练功的房间。这座房间形状甚是奇特，前窄後宽，成为梯形，东边半圆，西边却作三角形状，原来这是全真教独有的练功室，前窄练掌，後宽使指，东圆研剑，西角发镖。房间中央立着几个练功用的木人，吊着几个沙袋(bag)和纸册(paper)。"
      region.rooms[27].exits = "south|north"
      region.rooms[27].links = {}
        region.rooms[27].links.s = {}
          region.rooms[27].links.s.to = 1217
          region.rooms[27].links.s.con = ""
        region.rooms[27].links.n = {}
          region.rooms[27].links.n.to = 1219
          region.rooms[27].links.n.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;n;n"
      region.rooms[28].name = "禅房"
      region.rooms[28].zone = "全真教"
      region.rooms[28].id = 1219
      region.rooms[28].desc = "    这里是全真弟子修身养性、打熬气力的地方。为了方便练功，桌椅都没有摆放，仅仅在地下丢了几个小蒲团。"
      region.rooms[28].exits = "south|east|west"
      region.rooms[28].links = {}
        region.rooms[28].links.e = {}
          region.rooms[28].links.e.to = 1221
          region.rooms[28].links.e.con = ""
        region.rooms[28].links.w = {}
          region.rooms[28].links.w.to = 1220
          region.rooms[28].links.w.con = ""
        region.rooms[28].links.s = {}
          region.rooms[28].links.s.to = 1218
          region.rooms[28].links.s.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;n;n;w"
      region.rooms[29].name = "禅房"
      region.rooms[29].zone = "全真教"
      region.rooms[29].id = 1220
      region.rooms[29].desc = "    这里是全真教弟子摆放兵器的禅房，地下杂乱地堆着一些剑，有的已经锈纹斑斑了，有的还是锋利透亮，全真弟子练功的时候，就到这里来挑选兵刃。"
      region.rooms[29].exits = "east"
      region.rooms[29].links = {}
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 1219
          region.rooms[29].links.e.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;n;n;e"
      region.rooms[30].name = "禅房"
      region.rooms[30].zone = "全真教"
      region.rooms[30].id = 1221
      region.rooms[30].desc = "    这里是全真弟子修身养性、打熬气力的地方。为了方便练功，桌椅都没有摆放，仅仅在地下丢了几个小蒲团。"
      region.rooms[30].exits = "east|west"
      region.rooms[30].links = {}
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 1219
          region.rooms[30].links.w.con = ""
        region.rooms[30].links.e = {}
          region.rooms[30].links.e.to = 1222
          region.rooms[30].links.e.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;ne;ne"
      region.rooms[31].name = "小花园"
      region.rooms[31].zone = "全真教"
      region.rooms[31].id = 1222
      region.rooms[31].desc = "    这里是重阳观里的小花园，种植着一些叫不出名字来的花木，园角砌着一座假山，假山下是一潭小小的金鱼池，池水清澈见底，你看见有数条红色的金鱼在里面悠哉游哉地游来游去。几个道童正在这里嬉戏着。"
      region.rooms[31].exits = "east|west|southwest"
      region.rooms[31].links = {}
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 3007
          region.rooms[31].links.e.con = ""
        region.rooms[31].links.sw = {}
          region.rooms[31].links.sw.to = 1223
          region.rooms[31].links.sw.con = ""
        region.rooms[31].links.w = {}
          region.rooms[31].links.w.to = 1221
          region.rooms[31].links.w.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;ne"
      region.rooms[32].name = "小花园"
      region.rooms[32].zone = "全真教"
      region.rooms[32].id = 1223
      region.rooms[32].desc = "    这里是重阳观里的小花园，空气中飘着一股鲜花的香味。再往北去，就是金鱼池了。这个花园不大，却是全真弟子练功间隙最爱来游玩的地方。园中见不到一根杂草，也许专门有人负责管理这里。"
      region.rooms[32].exits = "northeast|southwest"
      region.rooms[32].links = {}
        region.rooms[32].links.ne = {}
          region.rooms[32].links.ne.to = 1222
          region.rooms[32].links.ne.con = ""
        region.rooms[32].links.sw = {}
          region.rooms[32].links.sw.to = 1224
          region.rooms[32].links.sw.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e"
      region.rooms[33].name = "后堂三进"
      region.rooms[33].zone = "全真教"
      region.rooms[33].id = 1224
      region.rooms[33].desc = "    这里是全真教弟子演练武功的地方。全真教弟子众多，所以每逢每月的十五这天，就召集所有弟子来这里切磋武功，一方面检验弟子们的武功长进，另一方面选拔人才担任教中的重要职务。现在还不到演武的日子，堂中空无一人。"
      region.rooms[33].exits = "east|northeast|west"
      region.rooms[33].links = {}
        region.rooms[33].links.ne = {}
          region.rooms[33].links.ne.to = 1223
          region.rooms[33].links.ne.con = ""
        region.rooms[33].links.w = {}
          region.rooms[33].links.w.to = 1217
          region.rooms[33].links.w.con = ""
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 1230
          region.rooms[33].links.e.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;s"
      region.rooms[34].name = "武场"
      region.rooms[34].zone = "全真教"
      region.rooms[34].id = 1225
      region.rooms[34].desc = "    这里是全真教的演武场，地下的青砖本来铺的整整齐齐，却不知道被谁踩出了几十个大大小小的凹坑。看的出来，这里成年累月的有弟子修炼掌法步法，天长日久，地下就踩出了凹坑。"
      region.rooms[34].exits = "south|north|southeast"
      region.rooms[34].links = {}
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 1217
          region.rooms[34].links.n.con = ""
        region.rooms[34].links.s = {}
          region.rooms[34].links.s.to = 1226
          region.rooms[34].links.s.con = ""
        region.rooms[34].links.se = {}
          region.rooms[34].links.se.to = 1229
          region.rooms[34].links.se.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;s;s"
      region.rooms[35].name = "武场"
      region.rooms[35].zone = "全真教"
      region.rooms[35].id = 1226
      region.rooms[35].desc = "    这里是全真教的演武场，地下的青砖本来铺的整整齐齐，却不知道被谁踩出了几十个大大小小的凹坑。看的出来，这里成年累月的有弟子修炼掌法步法，天长日久，地下就踩出了凹坑。武场中央立着几个练功用的木人。"
      region.rooms[35].exits = "east|north|southeast"
      region.rooms[35].links = {}
        region.rooms[35].links.n = {}
          region.rooms[35].links.n.to = 1225
          region.rooms[35].links.n.con = ""
        region.rooms[35].links.se = {}
          region.rooms[35].links.se.to = 1227
          region.rooms[35].links.se.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;s;s;se"
      region.rooms[36].name = "膳堂"
      region.rooms[36].zone = "全真教"
      region.rooms[36].id = 1227
      region.rooms[36].desc = "    这里是全真教的膳堂，是弟子们用餐的地方。这个堂很大，整齐地摆放着一排一排的桌椅。现在桌椅上三三两两地坐着全真弟子，有的正在用餐，有的低头谈笑。看着可口的饭菜，你忍不住也想叫(order)一份。"
      region.rooms[36].exits = "northwest|east|north"
      region.rooms[36].links = {}
        region.rooms[36].links.e = {}
          region.rooms[36].links.e.to = 1228
          region.rooms[36].links.e.con = ""
        region.rooms[36].links.nw = {}
          region.rooms[36].links.nw.to = 1226
          region.rooms[36].links.nw.con = ""
        region.rooms[36].links.n = {}
          region.rooms[36].links.n.to = 1229
          region.rooms[36].links.n.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;s;s;se;e"
      region.rooms[37].name = "厨房"
      region.rooms[37].zone = "全真教"
      region.rooms[37].id = 1228
      region.rooms[37].desc = "    这里是全真教的厨房，屋角上堆着一大堆手臂粗细的木柴，看来还没有劈好。一位火工道人正愁眉苦脸地坐在那里，看着那堆柴。墙上挂着一块牌子(paizi)，墙边扔着一把柴刀。"
      region.rooms[37].exits = "west"
      region.rooms[37].links = {}
        region.rooms[37].links.w = {}
          region.rooms[37].links.w.to = 1227
          region.rooms[37].links.w.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;s;se"
      region.rooms[38].name = "休息室"
      region.rooms[38].zone = "全真教"
      region.rooms[38].id = 1229
      region.rooms[38].desc = "    这是间很大的房间，光线非常昏暗。房里没有什么别的东西，只有中间放着一张收拾得舒舒服服的大床，床上的被褥也整理得整整洁洁，看着就让人想睡觉。"
      region.rooms[38].exits = "south|northwest|west"
      region.rooms[38].links = {}
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 1227
          region.rooms[38].links.s.con = ""
        region.rooms[38].links.nw = {}
          region.rooms[38].links.nw.to = 1225
          region.rooms[38].links.nw.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e"
      region.rooms[39].name = "静修室"
      region.rooms[39].zone = "全真教"
      region.rooms[39].id = 1230
      region.rooms[39].desc = "    这里是全真教弟子静修参悟道情的房间，房间很小，但收拾的干干净净，桌椅都摆放得整整齐齐，让人一看就心无杂念。"
      region.rooms[39].exits = "south|east|west"
      region.rooms[39].links = {}
        region.rooms[39].links.e = {}
          region.rooms[39].links.e.to = 1232
          region.rooms[39].links.e.con = ""
        region.rooms[39].links.s = {}
          region.rooms[39].links.s.to = 1231
          region.rooms[39].links.s.con = ""
        region.rooms[39].links.w = {}
          region.rooms[39].links.w.to = 1224
          region.rooms[39].links.w.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;s"
      region.rooms[40].name = "弟子居"
      region.rooms[40].zone = "全真教"
      region.rooms[40].id = 1231
      region.rooms[40].desc = "    这里是全真教弟子居住的房间。房间很大，整齐地铺着一排一排的床，床上被褥都折叠得整整齐齐，但是一个人都没有，也许所有的弟子都去练功去了。靠墙的地方有一个柜子(cabinet)。"
      region.rooms[40].exits = "north"
      region.rooms[40].links = {}
        region.rooms[40].links["pull cabinet;d"] = {}
          region.rooms[40].links["pull cabinet;d"].to = 3001
          region.rooms[40].links["pull cabinet;d"].con = ""
        region.rooms[40].links.n = {}
          region.rooms[40].links.n.to = 1230
          region.rooms[40].links.n.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e"
      region.rooms[41].name = "后山"
      region.rooms[41].zone = "全真教"
      region.rooms[41].id = 1232
      region.rooms[41].desc = "    这里已经出了重阳宫，到了终南山的后山。这里鸟语花香，空气清新，山势也平缓得多了。"
      region.rooms[41].exits = "northeast|west"
      region.rooms[41].links = {}
        region.rooms[41].links.ne = {}
          region.rooms[41].links.ne.to = 1233
          region.rooms[41].links.ne.con = ""
        region.rooms[41].links.w = {}
          region.rooms[41].links.w.to = 1230
          region.rooms[41].links.w.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne"
      region.rooms[42].name = "后山小路"
      region.rooms[42].zone = "全真教"
      region.rooms[42].id = 1233
      region.rooms[42].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。"
      region.rooms[42].exits = "northeast|southwest"
      region.rooms[42].links = {}
        region.rooms[42].links.ne = {}
          region.rooms[42].links.ne.to = 1234
          region.rooms[42].links.ne.con = ""
        region.rooms[42].links.sw = {}
          region.rooms[42].links.sw.to = 1232
          region.rooms[42].links.sw.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne"
      region.rooms[43].name = "后山小路"
      region.rooms[43].zone = "全真教"
      region.rooms[43].id = 1234
      region.rooms[43].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。"
      region.rooms[43].exits = "east|southwest"
      region.rooms[43].links = {}
        region.rooms[43].links.e = {}
          region.rooms[43].links.e.to = 1235
          region.rooms[43].links.e.con = ""
        region.rooms[43].links.sw = {}
          region.rooms[43].links.sw.to = 1233
          region.rooms[43].links.sw.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e"
      region.rooms[44].name = "后山小路"
      region.rooms[44].zone = "全真教"
      region.rooms[44].id = 1235
      region.rooms[44].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[44].exits = "south|north|east|west"
      region.rooms[44].links = {}
        region.rooms[44].links.e = {}
          region.rooms[44].links.e.to = 1236
          region.rooms[44].links.e.con = ""
        region.rooms[44].links.w = {}
          region.rooms[44].links.w.to = 1234
          region.rooms[44].links.w.con = ""
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 1237
          region.rooms[44].links.s.con = ""
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 1239
          region.rooms[44].links.n.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;e"
      region.rooms[45].name = "后山小路"
      region.rooms[45].zone = "全真教"
      region.rooms[45].id = 1236
      region.rooms[45].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[45].exits = "south|north|east|west"
      region.rooms[45].links = {}
        region.rooms[45].links.e = {}
          region.rooms[45].links.e.to = 1236
          region.rooms[45].links.e.con = ""
        region.rooms[45].links.w = {}
          region.rooms[45].links.w.to = 1235
          region.rooms[45].links.w.con = ""
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 1238
          region.rooms[45].links.s.con = ""
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 1236
          region.rooms[45].links.n.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;s"
      region.rooms[46].name = "后山小路"
      region.rooms[46].zone = "全真教"
      region.rooms[46].id = 1237
      region.rooms[46].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[46].exits = "south|north|east|west"
      region.rooms[46].links = {}
        region.rooms[46].links.e = {}
          region.rooms[46].links.e.to = 1238
          region.rooms[46].links.e.con = ""
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 1237
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.w = {}
          region.rooms[46].links.w.to = 1237
          region.rooms[46].links.w.con = ""
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 1235
          region.rooms[46].links.n.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;e;s"
      region.rooms[47].name = "后山小路"
      region.rooms[47].zone = "全真教"
      region.rooms[47].id = 1238
      region.rooms[47].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。山壁上好象刻着一些什么字迹(pattern)。走到这里，你好象迷路了。"
      region.rooms[47].exits = "south|north|east|west"
      region.rooms[47].links = {}
        region.rooms[47].links.e = {}
          region.rooms[47].links.e.to = 1238
          region.rooms[47].links.e.con = ""
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 1238
          region.rooms[47].links.s.con = ""
        region.rooms[47].links.w = {}
          region.rooms[47].links.w.to = 1237
          region.rooms[47].links.w.con = ""
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 1236
          region.rooms[47].links.n.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;n"
      region.rooms[48].name = "后山小路"
      region.rooms[48].zone = "全真教"
      region.rooms[48].id = 1239
      region.rooms[48].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[48].exits = "south|north|east|west"
      region.rooms[48].links = {}
        region.rooms[48].links.e = {}
          region.rooms[48].links.e.to = 1240
          region.rooms[48].links.e.con = ""
        region.rooms[48].links.w = {}
          region.rooms[48].links.w.to = 1239
          region.rooms[48].links.w.con = ""
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 1235
          region.rooms[48].links.s.con = ""
        region.rooms[48].links.n = {}
          region.rooms[48].links.n.to = 1245
          region.rooms[48].links.n.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;n;e"
      region.rooms[49].name = "后山小路"
      region.rooms[49].zone = "全真教"
      region.rooms[49].id = 1240
      region.rooms[49].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[49].exits = "south|north|east|west"
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 1241
          region.rooms[49].links.e.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 1240
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 1239
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.n = {}
          region.rooms[49].links.n.to = 1240
          region.rooms[49].links.n.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;n;e;e"
      region.rooms[50].name = "后山小路"
      region.rooms[50].zone = "全真教"
      region.rooms[50].id = 1241
      region.rooms[50].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[50].exits = "south|north|east|west"
      region.rooms[50].links = {}
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 1242
          region.rooms[50].links.e.con = ""
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 1240
          region.rooms[50].links.w.con = ""
        region.rooms[50].links.s = {}
          region.rooms[50].links.s.to = 1243
          region.rooms[50].links.s.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 1241
          region.rooms[50].links.n.con = ""
    region.rooms[51] = {}
      region.rooms[51].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;n;e;e;e"
      region.rooms[51].name = "后山小路"
      region.rooms[51].zone = "全真教"
      region.rooms[51].id = 1242
      region.rooms[51].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[51].exits = "south|north|east|west"
      region.rooms[51].links = {}
        region.rooms[51].links.e = {}
          region.rooms[51].links.e.to = 1242
          region.rooms[51].links.e.con = ""
        region.rooms[51].links.w = {}
          region.rooms[51].links.w.to = 1241
          region.rooms[51].links.w.con = ""
        region.rooms[51].links.s = {}
          region.rooms[51].links.s.to = 1242
          region.rooms[51].links.s.con = ""
        region.rooms[51].links.n = {}
          region.rooms[51].links.n.to = 1242
          region.rooms[51].links.n.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;n;e;e;s"
      region.rooms[52].name = "后山小路"
      region.rooms[52].zone = "全真教"
      region.rooms[52].id = 1243
      region.rooms[52].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[52].exits = "south|north|east|enter|west"
      region.rooms[52].links = {}
        region.rooms[52].links.enter = {}
          region.rooms[52].links.enter.to = 1244
          region.rooms[52].links.enter.con = ""
        region.rooms[52].links.s = {}
          region.rooms[52].links.s.to = 1243
          region.rooms[52].links.s.con = ""
        region.rooms[52].links.e = {}
          region.rooms[52].links.e.to = 1243
          region.rooms[52].links.e.con = ""
        region.rooms[52].links.w = {}
          region.rooms[52].links.w.to = 1243
          region.rooms[52].links.w.con = ""
        region.rooms[52].links.n = {}
          region.rooms[52].links.n.to = 1241
          region.rooms[52].links.n.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;n;e;e;s;enter"
      region.rooms[53].name = "后山山洞"
      region.rooms[53].zone = "全真教"
      region.rooms[53].id = 1244
      region.rooms[53].desc = "    这里是全真教开山祖师王重阳真人静修的山洞。洞不大，但里面布置得很雅致，象大户人家的客厅一样。洞壁上挂着一副画(hua)，桌椅茶几都很精致。"
      region.rooms[53].exits = "out"
      region.rooms[53].links = {}
        region.rooms[53].links.out = {}
          region.rooms[53].links.out.to = 1243
          region.rooms[53].links.out.con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;e;ne;ne;e;n;n"
      region.rooms[54].name = "后山小路"
      region.rooms[54].zone = "全真教"
      region.rooms[54].id = 1245
      region.rooms[54].desc = "    这里是后山上的小路。这条小路好象不是人工刻意修出来的，也许只是以前的采药人踩多了，现出这样一条小路来。走到这里，你好象迷路了。"
      region.rooms[54].exits = "south|north|east|west"
      region.rooms[54].links = {}
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 1245
          region.rooms[54].links.e.con = ""
        region.rooms[54].links.s = {}
          region.rooms[54].links.s.to = 1239
          region.rooms[54].links.s.con = ""
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 1245
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.n = {}
          region.rooms[54].links.n.to = 1245
          region.rooms[54].links.n.con = ""
    region.rooms[55] = {}
      region.rooms[55].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;e;s;pull cabinet;d"
      region.rooms[55].name = "密室"
      region.rooms[55].zone = "全真教"
      region.rooms[55].id = 3001
      region.rooms[55].desc = "    这里是全真教弟子为了直达中原修建的密室，四周都是石壁，这里的光线非常昏暗，也许已经身处地下了。你扶着墙壁向前摸索，忽然发现有块墙壁与其它的地方不同。"
      region.rooms[55].exits = "up|eastup"
      region.rooms[55].links = {}
        region.rooms[55].links.u = {}
          region.rooms[55].links.u.to = 1231
          region.rooms[55].links.u.con = ""
        region.rooms[55].links.eu = {}
          region.rooms[55].links.eu.to = 40
          region.rooms[55].links.eu.con = ""
    region.rooms[56] = {}
      region.rooms[56].path = "|!c:qling:fly qzj;knock gate|;e;e;e;e;e;e;e;ne;ne;e"
      region.rooms[56].name = "小花园"
      region.rooms[56].zone = "全真教"
      region.rooms[56].id = 3007
      region.rooms[56].links = {}
        region.rooms[56].links.w = {}
          region.rooms[56].links.w.to = 1222
          region.rooms[56].links.w.con = ""
      region.rooms[56].exits = "west"
      region.rooms[56].desc = "    这里是重阳观里的小花园，种植着一些叫不出名字来的花木，园角砌着一座假山，假山下是一潭小小的金鱼池，池水清澈见底，你看见有数条红色的金鱼在里面悠哉游哉地游来游去。几个道童正在这里嬉戏着。"
  region.center = 1147
return region