local region = {}
  region.cmd = "fly sld"
  region.name = "神龙岛"
  region.id = "sld"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly sld"
      region.rooms[1].name = "神龙教大厅"
      region.rooms[1].zone = "神龙岛"
      region.rooms[1].id = 2165
      region.rooms[1].desc = "    过了一条长廊,眼前突然现出一座大厅.此厅硕大无朋,足可容千人之众.只见一群群少年男女衣分五色,分站五个方位.青、白、黑、黄四色的都是少年,穿红的却是少女,背上各负短剑,每一队约有百人."
      region.rooms[1].exits = "south|east|north|west"
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 2167
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 2171
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 2173
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 2166
          region.rooms[1].links.n.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly sld;n"
      region.rooms[2].name = "神龙教后厅"
      region.rooms[2].zone = "神龙岛"
      region.rooms[2].id = 2166
      region.rooms[2].desc = "    这是神龙教的议事场所--潜龙厅.此厅较小,前面有两张大竹椅,两边摆着五个小凳."
      region.rooms[2].exits = "south"
      region.rooms[2].links = {}
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 2165
          region.rooms[2].links.s.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly sld;e"
      region.rooms[3].name = "走廊"
      region.rooms[3].zone = "神龙岛"
      region.rooms[3].id = 2167
      region.rooms[3].desc = "    这是一条走廊,两边都是石头柱子, 西边是大厅,东边是厨房,南面是练武场,北面是休息室."
      region.rooms[3].exits = "south|north|east|west"
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 2168
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 2165
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 2170
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 2169
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly sld;e;e"
      region.rooms[4].name = "厨房"
      region.rooms[4].zone = "神龙岛"
      region.rooms[4].id = 2168
      region.rooms[4].desc = "    这是神龙岛的厨房，中央摆着大圆桌，周围则放着几张竹椅。神龙岛的弟子都在这里用餐。"
      region.rooms[4].exits = "west"
      region.rooms[4].links = {}
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 2167
          region.rooms[4].links.w.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly sld;e;n"
      region.rooms[5].name = "休息室"
      region.rooms[5].zone = "神龙岛"
      region.rooms[5].id = 2169
      region.rooms[5].desc = "    这是间整洁的小房，房里别无他物，只有中间放着一张收拾得干干净净的床，这是神龙岛弟子的休息场所."
      region.rooms[5].exits = "south"
      region.rooms[5].links = {}
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 2167
          region.rooms[5].links.s.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly sld;e;s"
      region.rooms[6].name = "练武场"
      region.rooms[6].zone = "神龙岛"
      region.rooms[6].id = 2170
      region.rooms[6].desc = "    这是一个宽大的练武场，有几个手执短剑的少年少女在这里练功。旁边站着几人,有男有女,年纪轻的三十来岁,老的已有六七十岁,身上却不带兵刃.北边是一条走廊."
      region.rooms[6].exits = "north"
      region.rooms[6].links = {}
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 2167
          region.rooms[6].links.n.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly sld;w"
      region.rooms[7].name = "竹林"
      region.rooms[7].zone = "神龙岛"
      region.rooms[7].id = 2171
      region.rooms[7].desc = "    这里是一片青竹林,一阵凉风吹过,竹叶沙沙作响,东边是大厅,西边是教主的居室."
      region.rooms[7].exits = "east|west"
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 2165
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 2172
          region.rooms[7].links.w.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly sld;w;w"
      region.rooms[8].name = "竹屋"
      region.rooms[8].zone = "神龙岛"
      region.rooms[8].id = 2172
      region.rooms[8].desc = "    这里是神龙教主的居室----仙福居,中间一张大桌,墙上挂着水墨画."
      region.rooms[8].exits = "east"
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 2171
          region.rooms[8].links.e.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly sld;s"
      region.rooms[9].name = "大门"
      region.rooms[9].zone = "神龙岛"
      region.rooms[9].id = 2173
      region.rooms[9].desc = "    这是间很大的竹屋。门外站着几个年轻弟子.再住北就是神龙教大厅,隔得虽远,却也可以听得到厅上众人齐声念颂之声."
      region.rooms[9].exits = "south|north"
      region.rooms[9].links = {}
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 2174
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 2165
          region.rooms[9].links.n.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly sld;s;s"
      region.rooms[10].name = "山道"
      region.rooms[10].zone = "神龙岛"
      region.rooms[10].id = 2174
      region.rooms[10].desc = "    这是一条狭窄的山道,向着北方一座山峰行去.转过了几个山坡,抬头遥见峰顶建着几座大竹屋."
      region.rooms[10].exits = "south|north"
      region.rooms[10].links = {}
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 2175
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 2173
          region.rooms[10].links.n.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly sld;s;s;s"
      region.rooms[11].name = "大道"
      region.rooms[11].zone = "神龙岛"
      region.rooms[11].id = 2175
      region.rooms[11].desc = "    这是一条宽敞的大道。全由乱石堆成,显然曾花了不少人力.西边是一片开阔地."
      region.rooms[11].exits = "north|west"
      region.rooms[11].links = {}
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 2176
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 2174
          region.rooms[11].links.n.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly sld;s;s;s;w"
      region.rooms[12].name = "空地"
      region.rooms[12].zone = "神龙岛"
      region.rooms[12].id = 2176
      region.rooms[12].desc = "    这是一片空地,四周都是乱石,杂草丛生。北边是一间小屋.南面是深深的灌木林.东面有一条工整的大道,西面是一片草坪."
      region.rooms[12].exits = "south|north|east|west"
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 2175
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 2177
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 2180
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 2178
          region.rooms[12].links.n.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly sld;s;s;s;w;w"
      region.rooms[13].name = "草坪"
      region.rooms[13].zone = "神龙岛"
      region.rooms[13].id = 2177
      region.rooms[13].desc = "    这里是一片青青的草坪，有几个少年在玩耍，四周开满了各色的鲜花，一阵凉风吹过，清新的空气中传来几缕淡淡的花香。"
      region.rooms[13].exits = "east"
      region.rooms[13].links = {}
        region.rooms[13].links.e = {}
          region.rooms[13].links.e.to = 2176
          region.rooms[13].links.e.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly sld;s;s;s;w;n"
      region.rooms[14].name = "草地"
      region.rooms[14].zone = "神龙岛"
      region.rooms[14].id = 2178
      region.rooms[14].desc = "    这里是一片青青的草地，有几个少年在玩耍。四周开满了各色的鲜花，一阵凉风吹过，清新的空气中传来几缕淡淡的花香。"
      region.rooms[14].exits = "south|north"
      region.rooms[14].links = {}
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 2176
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 2179
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly sld;s;s;s;w;n;n"
      region.rooms[15].name = "小屋"
      region.rooms[15].zone = "神龙岛"
      region.rooms[15].id = 2179
      region.rooms[15].desc = "    一进小屋,只见墙上挂满了无数名贵的字画.书架上也堆满了平时难得一见的各种各样的书籍.一个相貌英武的中年文士正对着一幅字画唉声叹气."
      region.rooms[15].exits = "south"
      region.rooms[15].links = {}
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 2178
          region.rooms[15].links.s.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly sld;s;s;s;w;s"
      region.rooms[16].name = "灌木林"
      region.rooms[16].zone = "神龙岛"
      region.rooms[16].id = 2180
      region.rooms[16].desc = "    这是一片灌木林。走了不远,你就可以看得见前面的空地了。"
      region.rooms[16].exits = "south|north"
      region.rooms[16].links = {}
        region.rooms[16].links.s = {}
          region.rooms[16].links.s.to = 2181
          region.rooms[16].links.s.con = ""
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 2176
          region.rooms[16].links.n.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly sld;s;s;s;w;s;s"
      region.rooms[17].name = "灌木林"
      region.rooms[17].zone = "神龙岛"
      region.rooms[17].id = 2181
      region.rooms[17].desc = "    这是一片灌木林。你对这样一个孤岛上竟有这样大一片灌木林(bush)感到非常吃惊.前面根本没有路,四周的密林中长满了杂草。"
      region.rooms[17].exits = "south"
      region.rooms[17].links = {}
        region.rooms[17].links["kan bush;n"] = {}
          region.rooms[17].links["kan bush;n"].to = 2180
          region.rooms[17].links["kan bush;n"].con = ""
  region.center = 2165
return region