local region = {}
  region.cmd = "fly ss"
  region.name = "衡山"
  region.id = "ss"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s;s;s;s;s;s;s;s"
      region.rooms[1].name = "衡阳城"
      region.rooms[1].zone = "衡阳|衡山"
      region.rooms[1].id = 455
      region.rooms[1].desc = "    这里就是衡阳县城。衡阳地处偏远，显见远不如中原繁华了。"
      region.rooms[1].exits = "south|north|east|west"
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 459
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 456
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 447
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 457
          region.rooms[1].links.n.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s;s;s;s;s;s;s"
      region.rooms[2].name = "棂星门"
      region.rooms[2].zone = "衡阳|衡山"
      region.rooms[2].id = 457
      region.rooms[2].desc = "    这里是南岳大庙的第一道门，由汉白玉，花岗石打就的石牌坊。南岳衡山是祝融游息之地，道教奉为第三小洞天。在此远望衡山，山势如飞，如云雾中凌空的大鸟。"
      region.rooms[2].exits = "south|north"
      region.rooms[2].links = {}
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 455
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 458
          region.rooms[2].links.n.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s;s;s;s;s;s"
      region.rooms[3].name = "奎星阁"
      region.rooms[3].zone = "衡阳|衡山"
      region.rooms[3].id = 458
      region.rooms[3].desc = "    奎星阁是南岳大庙的第二进。阁为一个大舞台，阁左为鼓亭，右是钟亭。乡俗年节唱戏，这里总是热闹非凡。"
      region.rooms[3].exits = "south|north|east"
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 1300
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 457
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 1299
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s;s;s;s;s"
      region.rooms[4].name = "正川门"
      region.rooms[4].zone = "衡山"
      region.rooms[4].id = 1299
      region.rooms[4].desc = "    正川门是南岳大庙的第三进。院内是玄德宗殿，关圣殿，观音阁等楼宇。"
      region.rooms[4].exits = "south|north"
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 458
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 1301
          region.rooms[4].links.n.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s;s;s;s;s;s;e"
      region.rooms[5].name = "钟亭"
      region.rooms[5].zone = "衡山"
      region.rooms[5].id = 1300
      region.rooms[5].desc = "    钟亭内设铁钟一口，重九千斤。每逢山洪暴发，鸣钟镇洪，亦以示警，声闻二十里外。 "
      region.rooms[5].exits = "west"
      region.rooms[5].links = {}
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 458
          region.rooms[5].links.w.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s;s;s;s"
      region.rooms[6].name = "御碑亭"
      region.rooms[6].zone = "衡山"
      region.rooms[6].id = 1301
      region.rooms[6].desc = "    御碑为重修南岳庙大石碑，高数丈，石碑竖立在重三万八千斤的大石龟上，龟身雕刻细腻，极为生动。"
      region.rooms[6].exits = "south|north"
      region.rooms[6].links = {}
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 1299
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 1302
          region.rooms[6].links.n.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s;s;s"
      region.rooms[7].name = "嘉应门"
      region.rooms[7].zone = "衡山"
      region.rooms[7].id = 1302
      region.rooms[7].desc = "    这里是地方官迎接京师御史官来祭南岳的地方，是南岳大庙第五进门了。门上雕塑也较精细些，悬彩灯笼时时换新。"
      region.rooms[7].exits = "south|north"
      region.rooms[7].links = {}
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 1301
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 1303
          region.rooms[7].links.n.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s;s"
      region.rooms[8].name = "御书楼"
      region.rooms[8].zone = "衡山"
      region.rooms[8].id = 1303
      region.rooms[8].desc = "    御书楼为南岳庙历代藏书之处，天子御赐，贤达乐捐，这里早已洋洋大观。"
      region.rooms[8].exits = "south|north"
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 1302
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 1304
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s;s"
      region.rooms[9].name = "大殿"
      region.rooms[9].zone = "衡山"
      region.rooms[9].id = 1304
      region.rooms[9].desc = "    这里是南岳大殿，供祭祀炎帝之用。大殿结构为重檐歇山顶，顶覆七彩琉璃。殿高七十二尺，正面七间，有石柱七十二根，合南岳七十二峰之数。殿中南岳圣帝宝相庄严。南岳庙之雄为衡山小四绝之一。 "
      region.rooms[9].exits = "south|north"
      region.rooms[9].links = {}
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 1303
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 1305
          region.rooms[9].links.n.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd;s"
      region.rooms[10].name = "后殿"
      region.rooms[10].zone = "衡山"
      region.rooms[10].id = 1305
      region.rooms[10].desc = "    后殿是南岳大庙的第八进，也是南岳大帝的寝宫。"
      region.rooms[10].exits = "south|north"
      region.rooms[10].links = {}
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 1304
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 1306
          region.rooms[10].links.n.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se;sd"
      region.rooms[11].name = "正北门"
      region.rooms[11].zone = "衡山"
      region.rooms[11].id = 1306
      region.rooms[11].desc = "    南岳大庙正北门是大庙的后门，正在衡山山麓。回望大庙，红墙黄瓦，金碧辉煌。北面是上山的六小路。"
      region.rooms[11].exits = "south|northup"
      region.rooms[11].links = {}
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 1305
          region.rooms[11].links.s.con = ""
        region.rooms[11].links.nu = {}
          region.rooms[11].links.nu.to = 1307
          region.rooms[11].links.nu.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd;se"
      region.rooms[12].name = "山路"
      region.rooms[12].zone = "衡山"
      region.rooms[12].id = 1307
      region.rooms[12].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。"
      region.rooms[12].exits = "northwest|southdown"
      region.rooms[12].links = {}
        region.rooms[12].links.sd = {}
          region.rooms[12].links.sd.to = 1306
          region.rooms[12].links.sd.con = ""
        region.rooms[12].links.nw = {}
          region.rooms[12].links.nw.to = 1308
          region.rooms[12].links.nw.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;sd"
      region.rooms[13].name = "山路"
      region.rooms[13].zone = "衡山"
      region.rooms[13].id = 1308
      region.rooms[13].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。"
      region.rooms[13].exits = "northup|southeast"
      region.rooms[13].links = {}
        region.rooms[13].links.nu = {}
          region.rooms[13].links.nu.to = 1309
          region.rooms[13].links.nu.con = ""
        region.rooms[13].links.se = {}
          region.rooms[13].links.se.to = 1307
          region.rooms[13].links.se.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su"
      region.rooms[14].name = "赤帝峰"
      region.rooms[14].zone = "衡山"
      region.rooms[14].id = 1309
      region.rooms[14].desc = "    相传祝融能 \"以火施化\" ，是黄帝的 \"火正官\" ，并主管南方的事务，死后葬于此，故名赤帝峰。"
      region.rooms[14].exits = "eastdown|southdown|northdown"
      region.rooms[14].links = {}
        region.rooms[14].links.ed = {}
          region.rooms[14].links.ed.to = 1310
          region.rooms[14].links.ed.con = ""
        region.rooms[14].links.nd = {}
          region.rooms[14].links.nd.to = 1313
          region.rooms[14].links.nd.con = ""
        region.rooms[14].links.sd = {}
          region.rooms[14].links.sd.to = 1308
          region.rooms[14].links.sd.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;ed"
      region.rooms[15].name = "山路"
      region.rooms[15].zone = "衡山"
      region.rooms[15].id = 1310
      region.rooms[15].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。西边上山是赤帝峰。东边远远可以看到衡山五峰之一的紫盖峰了。"
      region.rooms[15].exits = "westup|east"
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 1311
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.wu = {}
          region.rooms[15].links.wu.to = 1309
          region.rooms[15].links.wu.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;ed;e"
      region.rooms[16].name = "山路"
      region.rooms[16].zone = "衡山"
      region.rooms[16].id = 1311
      region.rooms[16].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。西边上山的路。东边隐隐听到水响。"
      region.rooms[16].exits = "eastup|west"
      region.rooms[16].links = {}
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 1310
          region.rooms[16].links.w.con = ""
        region.rooms[16].links.eu = {}
          region.rooms[16].links.eu.to = 1312
          region.rooms[16].links.eu.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se;su;ed;e;eu"
      region.rooms[17].name = "水帘洞"
      region.rooms[17].zone = "衡山"
      region.rooms[17].id = 1312
      region.rooms[17].desc = "    水帘洞在紫盖峰下，在吐雾和香炉两峰之间。紫盖峰之水经山涧汇入紫盖仙洞中，深不可测，水满则溢，飞瀑高二十余丈，数叠垂帘，飘泄而下，蔚为壮观。明张居正诗曰:  \"误疑瀛海翻琼波，莫拟银河倒碧流，自是湘妃深隐处，水晶帘挂五云头。\" 以赞叹这衡山大四绝之一的 \"水帘洞之奇\" 。"
      region.rooms[17].exits = "westdown"
      region.rooms[17].links = {}
        region.rooms[17].links.wd = {}
          region.rooms[17].links.wd.to = 1311
          region.rooms[17].links.wd.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly ss;sd;sd;sw;sw;se;sd;sd;se"
      region.rooms[18].name = "山路"
      region.rooms[18].zone = "衡山"
      region.rooms[18].id = 1313
      region.rooms[18].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。"
      region.rooms[18].exits = "northwest|southup"
      region.rooms[18].links = {}
        region.rooms[18].links.nw = {}
          region.rooms[18].links.nw.to = 1314
          region.rooms[18].links.nw.con = ""
        region.rooms[18].links.su = {}
          region.rooms[18].links.su.to = 1309
          region.rooms[18].links.su.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly ss;sd;sd;sw;sw;se;sd;sd"
      region.rooms[19].name = "山路"
      region.rooms[19].zone = "衡山"
      region.rooms[19].id = 1314
      region.rooms[19].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。"
      region.rooms[19].exits = "northup|southeast"
      region.rooms[19].links = {}
        region.rooms[19].links.nu = {}
          region.rooms[19].links.nu.to = 1315
          region.rooms[19].links.nu.con = ""
        region.rooms[19].links.se = {}
          region.rooms[19].links.se.to = 1313
          region.rooms[19].links.se.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly ss;sd;sd;sw;sw;se;sd"
      region.rooms[20].name = "半山亭"
      region.rooms[20].zone = "衡山"
      region.rooms[20].id = 1315
      region.rooms[20].desc = "    终于到了半山亭。这里离到祝融峰无论高程还是行程，均恰好是一半之径，路边小亭显然已极古久，但仍为过往客旅遮风避雨。"
      region.rooms[20].exits = "northup|southdown"
      region.rooms[20].links = {}
        region.rooms[20].links.sd = {}
          region.rooms[20].links.sd.to = 1314
          region.rooms[20].links.sd.con = ""
        region.rooms[20].links.nu = {}
          region.rooms[20].links.nu.to = 1316
          region.rooms[20].links.nu.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly ss;sd;sd;sw;sw;se"
      region.rooms[21].name = "山路"
      region.rooms[21].zone = "衡山"
      region.rooms[21].id = 1316
      region.rooms[21].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。西边有岔路通往磨镜台和天柱峰。西北方就是芙蓉峰了，祝融峰也是往这个方向。"
      region.rooms[21].exits = "northwest|southdown|west"
      region.rooms[21].links = {}
        region.rooms[21].links.sd = {}
          region.rooms[21].links.sd.to = 1315
          region.rooms[21].links.sd.con = ""
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 1317
          region.rooms[21].links.w.con = ""
        region.rooms[21].links.nw = {}
          region.rooms[21].links.nw.to = 1331
          region.rooms[21].links.nw.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly ss;sd;sd;sw;sw;se;w"
      region.rooms[22].name = "山路"
      region.rooms[22].zone = "衡山"
      region.rooms[22].id = 1317
      region.rooms[22].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。南边山路就是磨镜台和天柱峰。"
      region.rooms[22].exits = "east|southdown"
      region.rooms[22].links = {}
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 1316
          region.rooms[22].links.e.con = ""
        region.rooms[22].links.sd = {}
          region.rooms[22].links.sd.to = 1318
          region.rooms[22].links.sd.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly ss;sd;sd;sw;sw;se;w;sd"
      region.rooms[23].name = "磨镜台"
      region.rooms[23].zone = "衡山"
      region.rooms[23].id = 1318
      region.rooms[23].desc = "    磨镜台位于燕子岩下，与半山亭一沟相邻。台前峰回路转，台旁古松苍翠，环境清幽。相传南宗禅宗怀让在此宣扬 \"顿悟法门\" ，坐台高僧斗法，怀让磨镜，智服北宗道一，此台因而传名。 \"磨镜台之幽\" 是衡山大四绝之一。"
      region.rooms[23].exits = "westup|northup|southdown"
      region.rooms[23].links = {}
        region.rooms[23].links.nu = {}
          region.rooms[23].links.nu.to = 1317
          region.rooms[23].links.nu.con = ""
        region.rooms[23].links.sd = {}
          region.rooms[23].links.sd.to = 1319
          region.rooms[23].links.sd.con = ""
        region.rooms[23].links.wu = {}
          region.rooms[23].links.wu.to = 1325
          region.rooms[23].links.wu.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly ss;sd;sd;sw;sw;se;w;sd;sd"
      region.rooms[24].name = "山路"
      region.rooms[24].zone = "衡山"
      region.rooms[24].id = 1319
      region.rooms[24].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。南边就是福严寺。"
      region.rooms[24].exits = "northup|southup"
      region.rooms[24].links = {}
        region.rooms[24].links.nu = {}
          region.rooms[24].links.nu.to = 1318
          region.rooms[24].links.nu.con = ""
        region.rooms[24].links.su = {}
          region.rooms[24].links.su.to = 1320
          region.rooms[24].links.su.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly ss;sd;sd;sw;sw;se;w;sd;sd;su"
      region.rooms[25].name = "福严寺"
      region.rooms[25].zone = "衡山"
      region.rooms[25].id = 1320
      region.rooms[25].desc = "    福严寺为禅宗七祖怀让的道场，怀让在此宏扬顿悟法门。山门上匾额 \"天下法院\" 正是当年写照，两边门联 \"六朝古刹\"  \"七祖道场\" 字迹剥落，颜色极古。山门墙山有古人留字(zi)，年代古远，犹历历可辩。 寺内石柱有一对联(lian)，字迹圆润回转，不露机锋。"
      region.rooms[25].exits = "westup|southdown|northdown"
      region.rooms[25].links = {}
        region.rooms[25].links.nd = {}
          region.rooms[25].links.nd.to = 1319
          region.rooms[25].links.nd.con = ""
        region.rooms[25].links.sd = {}
          region.rooms[25].links.sd.to = 1321
          region.rooms[25].links.sd.con = ""
        region.rooms[25].links.wu = {}
          region.rooms[25].links.wu.to = 1323
          region.rooms[25].links.wu.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly ss;sd;sd;sw;sw;se;w;sd;sd;su;sd"
      region.rooms[26].name = "山路"
      region.rooms[26].zone = "衡山"
      region.rooms[26].id = 1321
      region.rooms[26].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。南边是南台寺，北边通往福严寺。"
      region.rooms[26].exits = "northup|southup"
      region.rooms[26].links = {}
        region.rooms[26].links.nu = {}
          region.rooms[26].links.nu.to = 1320
          region.rooms[26].links.nu.con = ""
        region.rooms[26].links.su = {}
          region.rooms[26].links.su.to = 1322
          region.rooms[26].links.su.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly ss;sd;sd;sw;sw;se;w;sd;sd;su;sd;su"
      region.rooms[27].name = "南台寺"
      region.rooms[27].zone = "衡山"
      region.rooms[27].id = 1322
      region.rooms[27].desc = "    南台寺为禅宗七祖怀让的弟子石头希迁的道场，寺下紫云峰上是石头和尚墓。寺周林荫夹道，曲径通幽，泉流叮咚，蜂蝶纷飞，山风吹过时万叶悉索，真好去处。"
      region.rooms[27].exits = "northdown"
      region.rooms[27].links = {}
        region.rooms[27].links.nd = {}
          region.rooms[27].links.nd.to = 1321
          region.rooms[27].links.nd.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly ss;sd;sd;sw;sw;se;w;sd;sd;su;wu"
      region.rooms[28].name = "三生塔"
      region.rooms[28].zone = "衡山"
      region.rooms[28].id = 1323
      region.rooms[28].desc = "    三生塔是福严寺开山禅师慧思埋骨处，据说慧思禅师的三生均埋骨这里，故称三生塔。不远处有棵银杏，据说曾受戒于慧思禅师，树龄千年，仍亭亭华盖，岁岁青苍。"
      region.rooms[28].exits = "eastdown|southup"
      region.rooms[28].links = {}
        region.rooms[28].links.ed = {}
          region.rooms[28].links.ed.to = 1320
          region.rooms[28].links.ed.con = ""
        region.rooms[28].links.su = {}
          region.rooms[28].links.su.to = 1324
          region.rooms[28].links.su.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly ss;sd;sd;sw;sw;se;w;sd;sd;su;wu;su"
      region.rooms[29].name = "极高明台"
      region.rooms[29].zone = "衡山"
      region.rooms[29].id = 1324
      region.rooms[29].desc = "    这里是福严寺最高处。唐邺侯李泌手书 \"极高明\" 三个大字于此，意即佛相极高 (高无见顶相) ，佛光极明 (明不借他光) ，佛是至高无上的，故曰极高明台。"
      region.rooms[29].exits = "northdown"
      region.rooms[29].links = {}
        region.rooms[29].links.nd = {}
          region.rooms[29].links.nd.to = 1323
          region.rooms[29].links.nd.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly ss;sd;sd;sw;sw;se;w;sd;wu"
      region.rooms[30].name = "山路"
      region.rooms[30].zone = "衡山"
      region.rooms[30].id = 1325
      region.rooms[30].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。山路东西通向磨镜台和天柱峰。"
      region.rooms[30].exits = "westup|eastdown"
      region.rooms[30].links = {}
        region.rooms[30].links.ed = {}
          region.rooms[30].links.ed.to = 1318
          region.rooms[30].links.ed.con = ""
        region.rooms[30].links.wu = {}
          region.rooms[30].links.wu.to = 1326
          region.rooms[30].links.wu.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly ss;sd;sd;sw;sw;se;w;sd;wu;wu"
      region.rooms[31].name = "天柱峰"
      region.rooms[31].zone = "衡山"
      region.rooms[31].id = 1326
      region.rooms[31].desc = "    你爬上衡山五峰之一的天柱峰，四望群山缥缈云雾中，每每天阴地湿时候，这里就是天柱云气的所在了。 "
      region.rooms[31].exits = "eastdown|westdown"
      region.rooms[31].links = {}
        region.rooms[31].links.ed = {}
          region.rooms[31].links.ed.to = 1325
          region.rooms[31].links.ed.con = ""
        region.rooms[31].links.wd = {}
          region.rooms[31].links.wd.to = 1327
          region.rooms[31].links.wd.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly ss;sd;sd;sw;sw;se;w;sd;wu;wu;wd"
      region.rooms[32].name = "山路"
      region.rooms[32].zone = "衡山"
      region.rooms[32].id = 1327
      region.rooms[32].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。山路向西通向方广寺。东面是天柱峰。"
      region.rooms[32].exits = "eastup|westdown"
      region.rooms[32].links = {}
        region.rooms[32].links.wd = {}
          region.rooms[32].links.wd.to = 1328
          region.rooms[32].links.wd.con = ""
        region.rooms[32].links.eu = {}
          region.rooms[32].links.eu.to = 1326
          region.rooms[32].links.eu.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly ss;sd;sd;sw;sw;se;w;sd;wu;wu;wd;wd"
      region.rooms[33].name = "方广寺"
      region.rooms[33].zone = "衡山"
      region.rooms[33].id = 1328
      region.rooms[33].desc = "    方广寺在莲花峰下。莲花峰有八个山头，犹如金莲瓣瓣，方广寺就建在这莲花中心的一片平地上。深邃幽雅，有 \"不游方广寺，不知南岳之深\" 之说，故 \"方广寺之深\" 为衡山大四绝之一。"
      region.rooms[33].exits = "eastup|southdown"
      region.rooms[33].links = {}
        region.rooms[33].links.sd = {}
          region.rooms[33].links.sd.to = 1329
          region.rooms[33].links.sd.con = ""
        region.rooms[33].links.eu = {}
          region.rooms[33].links.eu.to = 1327
          region.rooms[33].links.eu.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly ss;sd;sd;sw;sw;se;w;sd;wu;wu;wd;wd;sd"
      region.rooms[34].name = "山涧"
      region.rooms[34].zone = "衡山"
      region.rooms[34].id = 1329
      region.rooms[34].desc = "    顺山涧漂流而下，沿溪遍布珍稀树木，泉石，林木，花草及峰峦均极宜人。涧流至崖折叠飞泄而下，声震山谷。"
      region.rooms[34].exits = "northup|down"
      region.rooms[34].links = {}
        region.rooms[34].links.nu = {}
          region.rooms[34].links.nu.to = 1328
          region.rooms[34].links.nu.con = ""
        region.rooms[34].links.d = {}
          region.rooms[34].links.d.to = 1330
          region.rooms[34].links.d.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly ss;sd;sd;sw;sw;se;w;sd;wu;wu;wd;wd;sd;d"
      region.rooms[35].name = "黑沙潭"
      region.rooms[35].zone = "衡山"
      region.rooms[35].id = 1330
      region.rooms[35].desc = "    黑沙潭又称黑龙潭，深不见底，水色苍黑，瀑布流急，水中黑泡共白沫徜徉，幽幽可怖。石壁上 \"海南龙湫\" 四字据载为大宋徽宗赵佶所留。瘦金字体，一如往昔。"
      region.rooms[35].exits = "up"
      region.rooms[35].links = {}
        region.rooms[35].links.u = {}
          region.rooms[35].links.u.to = 1329
          region.rooms[35].links.u.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly ss;sd;sd;sw;sw"
      region.rooms[36].name = "山路"
      region.rooms[36].zone = "衡山"
      region.rooms[36].id = 1331
      region.rooms[36].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。东北方就是南天门了，高高矗立在西北方的就是衡山五峰之一的芙蓉峰。"
      region.rooms[36].exits = "southeast|northeast"
      region.rooms[36].links = {}
        region.rooms[36].links.ne = {}
          region.rooms[36].links.ne.to = 1332
          region.rooms[36].links.ne.con = ""
        region.rooms[36].links.se = {}
          region.rooms[36].links.se.to = 1316
          region.rooms[36].links.se.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly ss;sd;sd;sw"
      region.rooms[37].name = "南天门"
      region.rooms[37].zone = "衡山"
      region.rooms[37].id = 1332
      region.rooms[37].desc = "    到了南天门，才能望到衡山第一的祝融峰。南天门是花岗岩的石碑坊，中门镌有 \"南天门\" 三字横额，左右二门的门楣上，分别刻有 \"行云\" ， \"施雨\" 。楹联(lian)破陋，显见岁月已久。"
      region.rooms[37].exits = "northwest|eastup|southup|northeast|southwest"
      region.rooms[37].links = {}
        region.rooms[37].links.ne = {}
          region.rooms[37].links.ne.to = 1337
          region.rooms[37].links.ne.con = ""
        region.rooms[37].links.sw = {}
          region.rooms[37].links.sw.to = 1331
          region.rooms[37].links.sw.con = ""
        region.rooms[37].links.eu = {}
          region.rooms[37].links.eu.to = 1333
          region.rooms[37].links.eu.con = ""
        region.rooms[37].links.nw = {}
          region.rooms[37].links.nw.to = 1334
          region.rooms[37].links.nw.con = ""
        region.rooms[37].links.su = {}
          region.rooms[37].links.su.to = 1338
          region.rooms[37].links.su.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly ss;sd;sd;sw;eu"
      region.rooms[38].name = "流云坪"
      region.rooms[38].zone = "衡山"
      region.rooms[38].id = 1333
      region.rooms[38].desc = "    每逢雨霁，在后山深壑中升腾起来的云山雾海，涌过南天门山脊，向前山倾泻，直如银河飞泻，蔚为壮观，这就是南天门的流云奇景。"
      region.rooms[38].exits = "westdown"
      region.rooms[38].links = {}
        region.rooms[38].links.wd = {}
          region.rooms[38].links.wd.to = 1332
          region.rooms[38].links.wd.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly ss;sd;sd;sw;nw"
      region.rooms[39].name = "山路"
      region.rooms[39].zone = "衡山"
      region.rooms[39].id = 1334
      region.rooms[39].desc = "    你走在衡山山路上，四望山峰错落，林壑幽深，溪泉飞瀑，云雾缭绕，不觉心胸大快。山路转过芙蓉峰，西面远远看到藏经阁，东南方向通往南天门。"
      region.rooms[39].exits = "southeast|west"
      region.rooms[39].links = {}
        region.rooms[39].links.w = {}
          region.rooms[39].links.w.to = 1335
          region.rooms[39].links.w.con = ""
        region.rooms[39].links.se = {}
          region.rooms[39].links.se.to = 1332
          region.rooms[39].links.se.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly ss;sd;sd;sw;nw;w"
      region.rooms[40].name = "藏经殿"
      region.rooms[40].zone = "衡山"
      region.rooms[40].id = 1335
      region.rooms[40].desc = "    藏经殿深掩祥光峰下，因藏明太祖所赠 \"大藏经\" 故名。这里古木参天，殿宇飘翼，奇花异草，林壑幽深，景色秀丽， \"藏经殿之秀\" 是衡山大四绝之一。"
      region.rooms[40].exits = "south|east"
      region.rooms[40].links = {}
        region.rooms[40].links.e = {}
          region.rooms[40].links.e.to = 1334
          region.rooms[40].links.e.con = ""
        region.rooms[40].links.s = {}
          region.rooms[40].links.s.to = 1336
          region.rooms[40].links.s.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly ss;sd;sd;sw;nw;w;s"
      region.rooms[41].name = "梳妆台"
      region.rooms[41].zone = "衡山"
      region.rooms[41].id = 1336
      region.rooms[41].desc = "    藏经殿有一泓碧泉如镜，向称美容泉。相传为南陈后主妃在此避乱时，对碧水照容颜梳妆打扮的地方。殿前胜迹有灵日，昔时夜间常见飞光，或如繁星点点，或若万萤乱飞，煞是壮观。"
      region.rooms[41].exits = "north"
      region.rooms[41].links = {}
        region.rooms[41].links.n = {}
          region.rooms[41].links.n.to = 1335
          region.rooms[41].links.n.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly ss;sd;sd"
      region.rooms[42].name = "狮子岩"
      region.rooms[42].zone = "衡山"
      region.rooms[42].id = 1337
      region.rooms[42].desc = "    狮子岩布满奇形怪状的岩石，细究则绝类狮子，腾跃伏吼，各肖其类。到狮子岩，祝融峰已经在望了。"
      region.rooms[42].exits = "northup|southwest"
      region.rooms[42].links = {}
        region.rooms[42].links.nu = {}
          region.rooms[42].links.nu.to = 1339
          region.rooms[42].links.nu.con = ""
        region.rooms[42].links.sw = {}
          region.rooms[42].links.sw.to = 1332
          region.rooms[42].links.sw.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly ss;sd;sd;sw;su"
      region.rooms[43].name = "登高台"
      region.rooms[43].zone = "衡山"
      region.rooms[43].id = 1338
      region.rooms[43].desc = "    这里是南天门登高望远的好去处。你站在这里，俯视诸峰，丘垤如泥丸。看湘江北去，九向九背，时隐时现。周围烟霞，碧罗，紫盖，天柱诸峰环抱，气象万千。"
      region.rooms[43].exits = "northdown"
      region.rooms[43].links = {}
        region.rooms[43].links.nd = {}
          region.rooms[43].links.nd.to = 1332
          region.rooms[43].links.nd.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly ss;sd"
      region.rooms[44].name = "望日台"
      region.rooms[44].zone = "衡山"
      region.rooms[44].id = 1339
      region.rooms[44].desc = "    望日台紧邻祝融殿。鸡鸣夜起，登台东望，遥见海门，云水皆赤，倏忽异彩，日轮荡漾，若沉若浮，稍之奋涌而起，光耀夺目。"
      region.rooms[44].exits = "northup|southdown"
      region.rooms[44].links = {}
        region.rooms[44].links.sd = {}
          region.rooms[44].links.sd.to = 1337
          region.rooms[44].links.sd.con = ""
        region.rooms[44].links.nu = {}
          region.rooms[44].links.nu.to = 1340
          region.rooms[44].links.nu.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly ss"
      region.rooms[45].name = "祝融殿"
      region.rooms[45].zone = "衡山"
      region.rooms[45].id = 1340
      region.rooms[45].desc = "    祝融殿，又名老圣殿，祠火神祝融。花岗石砌墙，铁瓦覆顶，殿宇凌空傲雪，巍然屹立在衡山绝顶。殿门石楹上刻有:  \"寅宾日出，峻极于天\" ，殿上有\"圣德重华\"的楣额。现在这里是衡山派掌门所在。"
      region.rooms[45].exits = "westup|southdown|northdown"
      region.rooms[45].links = {}
        region.rooms[45].links.nd = {}
          region.rooms[45].links.nd.to = 1342
          region.rooms[45].links.nd.con = ""
        region.rooms[45].links.sd = {}
          region.rooms[45].links.sd.to = 1339
          region.rooms[45].links.sd.con = ""
        region.rooms[45].links.wu = {}
          region.rooms[45].links.wu.to = 1341
          region.rooms[45].links.wu.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly ss;wu"
      region.rooms[46].name = "祝融峰"
      region.rooms[46].zone = "衡山"
      region.rooms[46].id = 1341
      region.rooms[46].desc = "     \"祝融峰之高\" 为衡山大四绝之首。在此俯瞰群峰，尽收眼底。东望湘江，南及五岭，北瞰洞庭，西视雪山。杜甫望岳诗中有 \"祝融五峰尊，峰峰次低昂。\" 韩愈亦以 \"祝融万丈拔地起，欲见不见轻烟里\" 极言其高。"
      region.rooms[46].exits = "eastdown"
      region.rooms[46].links = {}
        region.rooms[46].links.ed = {}
          region.rooms[46].links.ed.to = 1340
          region.rooms[46].links.ed.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly ss;nd"
      region.rooms[47].name = "望月台"
      region.rooms[47].zone = "衡山"
      region.rooms[47].id = 1342
      region.rooms[47].desc = "    望月台是祝融殿后一高耸巨石。每当夜籁，皓月当空，犹如玉盘冰轮，漫洒万里清辉，清冷月色，辉映低昂的群峰。此时 \"浩然万里，举七十二峰，峰峰贮冰壶中，始信下方无此月也。\" 前人因此有诗: 人间朗魄已皆尽，此地清光犹未低。"
      region.rooms[47].exits = "southup"
      region.rooms[47].links = {}
        region.rooms[47].links.su = {}
          region.rooms[47].links.su.to = 1340
          region.rooms[47].links.su.con = ""
  region.center = 1340
return region