local region = {}
  region.cmd = "fly sz"
  region.name = "苏州"
  region.id = "sz"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly sz;w;s;s;sw;w;w;w;w;w;nw"
      region.rooms[1].name = "寒山寺"
      region.rooms[1].zone = "扬州|苏州"
      region.rooms[1].id = 83
      region.rooms[1].links = {}
        region.rooms[1].links.enter = {}
          region.rooms[1].links.enter.to = 119
          region.rooms[1].links.enter.con = ""
        region.rooms[1].links.nw = {}
          region.rooms[1].links.nw.to = 82
          region.rooms[1].links.nw.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 118
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.se = {}
          region.rooms[1].links.se.to = 123
          region.rooms[1].links.se.con = ""
      region.rooms[1].exits = "south|northwest|enter|southeast"
      region.rooms[1].desc = "    你走出西门约三十里地，就到了枫桥镇，在唐元和年间，有高僧寒山子曾来此居住，后希迁禅师在此建寺院时，更名寒山寺。唐开元年间，诗人张继赴京应试落第，返途舟船停靠枫桥，赋诗一首：“月落乌啼霜满天，江枫渔火对愁眠，姑苏城外寒山寺，夜半歌声到客船”。从此，诗韵钟声，脍炙人口，寺因诗而名扬天下。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly sz;w;s;s;sw;w;w;w;w;w;nw;s"
      region.rooms[2].name = "品棋亭"
      region.rooms[2].zone = "苏州"
      region.rooms[2].id = 118
      region.rooms[2].links = {}
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 83
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "north"
      region.rooms[2].desc = "    品棋亭南眺泾水，北靠长安高墙，虽不是四野开阔，却也是手谈休栖的好地方。亭中有一张石桌(Table)，上面划着一张围棋盘。桌角摆放着棋子。另外还有两张石凳(Seat)，颜色一深一浅。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly sz;w;s;s;sw;w;w;w;w;w;nw;enter"
      region.rooms[3].name = "正殿"
      region.rooms[3].zone = "苏州"
      region.rooms[3].id = 119
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 120
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.out = {}
          region.rooms[3].links.out.to = 83
          region.rooms[3].links.out.con = ""
      region.rooms[3].exits = "east|out"
      region.rooms[3].desc = "    一走进正殿，首先你看到的是号称扬州八怪的画家罗聘所绘寒山，拾得写意画像石刻和郑文焯指画丰干和尚石刻像。左右碑廊中藏历历代名人岳飞等题写得诗文，楹联碑刻树方，世传精品。正殿左右的偏殿保存着宋代樟木雕塑的金身五百罗汉。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly sz;w;s;s;sw;w;w;w;w;w;nw;enter;e"
      region.rooms[4].name = "寒拾殿"
      region.rooms[4].zone = "苏州"
      region.rooms[4].id = 120
      region.rooms[4].links = {}
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 119
          region.rooms[4].links.w.con = ""
        region.rooms[4].links.out = {}
          region.rooms[4].links.out.to = 121
          region.rooms[4].links.out.con = ""
      region.rooms[4].exits = "west|out"
      region.rooms[4].desc = "    这里供奉着相传为“和合二仙”化身的寒山，拾得金身塑像，形态生动，逗人喜爱。寒山寺每年除夕半夜，撞钟一百零八响，其含义是除旧迎新和纪念佛门一百零八位高僧。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly sz;w;s;s;sw;w;w;w;w;w;nw;enter;e;out"
      region.rooms[5].name = "枫桥"
      region.rooms[5].zone = "苏州"
      region.rooms[5].id = 121
      region.rooms[5].links = {}
        region.rooms[5].links.enter = {}
          region.rooms[5].links.enter.to = 120
          region.rooms[5].links.enter.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 122
          region.rooms[5].links.n.con = ""
      region.rooms[5].exits = "north|enter"
      region.rooms[5].desc = "    寺的北面有一座桥孔呈半圆的单空石桥--枫桥，她跨于运河的枫桥湾。桥的东面是铁岭关，它与白虎关，浒墅关，合称苏州三关。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly sz;w;s;s;sw;w;w;w;w;w;nw;enter;e;out;n"
      region.rooms[6].name = "铁岭关"
      region.rooms[6].zone = "苏州"
      region.rooms[6].id = 122
      region.rooms[6].links = {}
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 121
          region.rooms[6].links.s.con = ""
      region.rooms[6].exits = "south"
      region.rooms[6].desc = "    关呈长方形，砖石结构，正中的三层敌楼为新建。铁岭关地处水陆要冲登敌楼，既可了望，又能放炮射箭。这关垣、运河、石桥所组成的联合工事，当时是为了防御合抵抗侵扰的倭寇。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly sz;w;s;s;sw;w;w;w;w;w"
      region.rooms[7].name = "青石官道"
      region.rooms[7].zone = "苏州"
      region.rooms[7].id = 123
      region.rooms[7].links = {}
        region.rooms[7].links.nw = {}
          region.rooms[7].links.nw.to = 83
          region.rooms[7].links.nw.con = ""
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 124
          region.rooms[7].links.e.con = ""
      region.rooms[7].exits = "east|northwest"
      region.rooms[7].desc = "    你走在一条青石大道上，人来人往非常繁忙，不时地有人骑着马匆匆而过。大道两旁有一些小货摊，似乎是一处集市。东面就是苏州城了。西北方通向寒山寺。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly sz;w;s;s;sw;w;w;w;w"
      region.rooms[8].name = "青石官道"
      region.rooms[8].zone = "苏州"
      region.rooms[8].id = 124
      region.rooms[8].links = {}
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 123
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 125
          region.rooms[8].links.e.con = ""
      region.rooms[8].exits = "east|west"
      region.rooms[8].desc = "    你走在一条青石大道上，人来人往非常繁忙，不时地有人骑着马匆匆而过。大道两旁有一些小货摊，似乎是一处集市。东面就是苏州城了。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly sz;w;s;s;sw;w;w;w"
      region.rooms[9].name = "青石官道"
      region.rooms[9].zone = "苏州"
      region.rooms[9].id = 125
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 124
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 126
          region.rooms[9].links.e.con = ""
      region.rooms[9].exits = "east|west"
      region.rooms[9].desc = "    你走在一条青石大道上，人来人往非常繁忙，不时地有人骑着马匆匆而过。大道两旁有一些小货摊，似乎是一处集市。东面就是苏州城了。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly sz;w;s;s;sw;w;w"
      region.rooms[10].name = "西门"
      region.rooms[10].zone = "苏州"
      region.rooms[10].id = 126
      region.rooms[10].links = {}
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 125
          region.rooms[10].links.w.con = ""
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 127
          region.rooms[10].links.e.con = ""
      region.rooms[10].exits = "east|west"
      region.rooms[10].desc = "    这是号称天堂的苏州西城门，城门正上方刻着“西门”两个楷书大字，城墙上贴着几张官府告示(gaoshi)。西门外通向寒山寺一条笔直的青石板大道向东西两边延伸，东边是城里。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly sz;w;s;s;sw;w"
      region.rooms[11].name = "西大街"
      region.rooms[11].zone = "苏州"
      region.rooms[11].id = 127
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 130
          region.rooms[11].links.e.con = ""
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 126
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 128
          region.rooms[11].links.s.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 129
          region.rooms[11].links.n.con = ""
      region.rooms[11].exits = "south|north|east|west"
      region.rooms[11].desc = "    你走在西大街上，感到这里的街面要比别处的干净、整洁。大概因为靠近衙门、兵营可受保护的缘故，富人们都喜欢住在这里。东边静悄悄地没有几个行人，西边是西城门通往郊外。南边是玄妙观，北边是一个书堂。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly sz;w;s;s;sw;w;s"
      region.rooms[12].name = "玄妙观"
      region.rooms[12].zone = "苏州"
      region.rooms[12].id = 128
      region.rooms[12].links = {}
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 127
          region.rooms[12].links.n.con = ""
      region.rooms[12].exits = "north"
      region.rooms[12].desc = "    你一走进玄妙观，看到观中香火缭绕，香客众多。殿是重檐歇山式，屋脊高十几米，内有高大殿柱四十根。屋面坡度平缓，出檐较深，斗拱疏朗宏大，殿内正中有砖砌须弥座，座上供奉着的三尊高十几米的泥塑三清金身像，法像庄严，神采奕奕，不失为道教雕塑中的精品。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly sz;w;s;s;sw;w;n"
      region.rooms[13].name = "书场"
      region.rooms[13].zone = "苏州"
      region.rooms[13].id = 129
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 127
          region.rooms[13].links.s.con = ""
      region.rooms[13].exits = "south"
      region.rooms[13].desc = "    你走进书场，看见里面热热闹闹的，场子里都是听书的，场子前面有一位说书先生，他看上去四五十岁，手中拿着一块响板，正在聚精会神地说着评书--《杨家将》。你也逐渐被评书的内容所吸引，场中的人们不时的发出惊叹和喝彩声，时不时将铜板抛了上去。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly sz;w;s;s;sw"
      region.rooms[14].name = "西大街"
      region.rooms[14].zone = "苏州"
      region.rooms[14].id = 130
      region.rooms[14].links = {}
        region.rooms[14].links.ne = {}
          region.rooms[14].links.ne.to = 134
          region.rooms[14].links.ne.con = ""
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 131
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.se = {}
          region.rooms[14].links.se.to = 135
          region.rooms[14].links.se.con = ""
        region.rooms[14].links.nw = {}
          region.rooms[14].links.nw.to = 133
          region.rooms[14].links.nw.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 127
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 132
          region.rooms[14].links.n.con = ""
      region.rooms[14].exits = "south|northwest|north|southeast|northeast|west"
      region.rooms[14].desc = "    这是一条宽阔的青石板街道，向东西两头延伸。西大街是衙门所在，行人稀少，静悄悄地很是冷清。东边是沧浪亭和宝带桥，南边是兵营。北边就是衙门了。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly sz;w;s;s;sw;s"
      region.rooms[15].name = "兵营"
      region.rooms[15].zone = "苏州"
      region.rooms[15].id = 131
      region.rooms[15].links = {}
        region.rooms[15].links.n = {}
          region.rooms[15].links.n.to = 130
          region.rooms[15].links.n.con = ""
      region.rooms[15].exits = "north"
      region.rooms[15].desc = "    这里是兵营，密密麻麻到处都是官兵，有的在武将的指挥下列队操练，有的独自在练功，有的坐着、躺着正在休息。南墙下坐着主帅，不动声色地寻视着四周。看到你进来，他们全都向你包围了过来，形势看来不太妙。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly sz;w;s;s;sw;n"
      region.rooms[16].name = "苏州府衙"
      region.rooms[16].zone = "苏州"
      region.rooms[16].id = 132
      region.rooms[16].links = {}
        region.rooms[16].links.s = {}
          region.rooms[16].links.s.to = 130
          region.rooms[16].links.s.con = ""
      region.rooms[16].exits = "south"
      region.rooms[16].desc = "    堂上东西有两根楹柱，挂着一幅对联，但是你根本无心细看。正墙上悬挂一个横匾，上面横书“正大光明”四个金光闪闪的大字。“肃静”“回避”的牌子分列两侧。知府正坐在文案后批阅文书，师爷随侍在后。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly sz;w;s;s;sw;nw"
      region.rooms[17].name = "运河码头"
      region.rooms[17].zone = "苏州"
      region.rooms[17].id = 133
      region.rooms[17].links = {}
        region.rooms[17].links.se = {}
          region.rooms[17].links.se.to = 130
          region.rooms[17].links.se.con = ""
      region.rooms[17].exits = "southeast"
      region.rooms[17].desc = "    这里是运河码头。它是朝廷漕运要塞，水陆必经之处。运河中来往船只满载穿梭，极其繁忙。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly sz;w;s;s"
      region.rooms[18].name = "沧浪亭"
      region.rooms[18].zone = "苏州"
      region.rooms[18].id = 134
      region.rooms[18].links = {}
        region.rooms[18].links.se = {}
          region.rooms[18].links.se.to = 160
          region.rooms[18].links.se.con = ""
        region.rooms[18].links.sw = {}
          region.rooms[18].links.sw.to = 130
          region.rooms[18].links.sw.con = ""
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 135
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 136
          region.rooms[18].links.n.con = ""
      region.rooms[18].exits = "south|north|southeast|southwest"
      region.rooms[18].desc = "    沧浪亭在苏州的北大街南侧，因为环境相对幽雅，使得男女老少都喜爱在这里闲庭散步。在亭中放眼望去，四周一片碧绿的草坪，亭子翼然于耸翠之中，飞檐凌空琵琶形牌科，布满檐口四周，亭上的额匾和石柱上的楹联(lian)使人更加喜爱这里。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly sz;w;s;s;s"
      region.rooms[19].name = "宝带桥"
      region.rooms[19].zone = "苏州"
      region.rooms[19].id = 135
      region.rooms[19].links = {}
        region.rooms[19].links.ne = {}
          region.rooms[19].links.ne.to = 160
          region.rooms[19].links.ne.con = ""
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 170
          region.rooms[19].links.s.con = ""
        region.rooms[19].links.nw = {}
          region.rooms[19].links.nw.to = 130
          region.rooms[19].links.nw.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 134
          region.rooms[19].links.n.con = ""
      region.rooms[19].exits = "south|north|northwest|northeast"
      region.rooms[19].desc = "    宝带桥横跨于苏州的运河之上，又因桥形宛若长带，被称为长桥。桥面宽阔，行人在桥上来往，桥边有城里的小贩吆喝、叫卖着，熙熙攘攘，热闹非凡。宝带桥卧于碧波之上，相应生辉，分外多娇。这里是中秋赏月的一处绝佳之地。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly sz;w;s"
      region.rooms[20].name = "北大街"
      region.rooms[20].zone = "苏州"
      region.rooms[20].id = 136
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 134
          region.rooms[20].links.s.con = ""
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 137
          region.rooms[20].links.e.con = ""
        region.rooms[20].links.sw = {}
          region.rooms[20].links.sw.to = 141
          region.rooms[20].links.sw.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 140
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 142
          region.rooms[20].links.n.con = ""
      region.rooms[20].exits = "south|north|east|west|southwest"
      region.rooms[20].desc = "    你走在一条繁忙的街道上，看着操着南腔北调的人们行色匆匆，许多人都往南边走去，那里有一个热闹的亭子。西南面是一家戏园子，不时传来叫好声，来自各地的人们进进出出。在东面是一个客店。西面是一个马厩。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly sz;w;s;e"
      region.rooms[21].name = "客店"
      region.rooms[21].zone = "苏州"
      region.rooms[21].id = 137
      region.rooms[21].links = {}
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 136
          region.rooms[21].links.w.con = "hoteld:"
        region.rooms[21].links.u = {}
          region.rooms[21].links.u.to = 138
          region.rooms[21].links.u.con = "hotelu:"
      region.rooms[21].exits = "up|west"
      region.rooms[21].desc = "    这是一家价钱低廉的客栈，生意非常兴隆。外地游客多选择这里落脚，你可以在这里打听到各地的风土人情。店小二里里外外忙得团团转，接待着南腔北调的客人。    墙上挂着一个牌子(paizi)。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly sz;w;s;e;|!hotelu::u|"
      region.rooms[22].name = "客店二楼"
      region.rooms[22].zone = "苏州"
      region.rooms[22].id = 138
      region.rooms[22].links = {}
        region.rooms[22].links.enter = {}
          region.rooms[22].links.enter.to = 139
          region.rooms[22].links.enter.con = ""
        region.rooms[22].links.d = {}
          region.rooms[22].links.d.to = 137
          region.rooms[22].links.d.con = ""
      region.rooms[22].exits = "enter|down"
      region.rooms[22].desc = "    你正走在客店二楼的走廊上，可以听到从客房里不时地呼呼的打酣声，一阵高过一阵。不时有睡意朦胧的旅客进进出出，到楼下的掌柜处付了钱再上来睡觉。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly sz;w;s;e;|!hotelu::u|;enter"
      region.rooms[23].name = "客店二楼"
      region.rooms[23].zone = "苏州"
      region.rooms[23].id = 139
      region.rooms[23].links = {}
        region.rooms[23].links.out = {}
          region.rooms[23].links.out.to = 138
          region.rooms[23].links.out.con = ""
      region.rooms[23].exits = "out"
      region.rooms[23].desc = "    这是一间很大的客房，陈设十分简陋。靠墙放了十几张小木床，不少客人正和衣而卧，满屋子都是呼呼的打酣声。西边有张床是空的，你蹑手蹑脚地走了过去。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly sz;w;s;w"
      region.rooms[24].name = "马厩"
      region.rooms[24].zone = "苏州"
      region.rooms[24].id = 140
      region.rooms[24].links = {}
        region.rooms[24].links.e = {}
          region.rooms[24].links.e.to = 136
          region.rooms[24].links.e.con = ""
        region.rooms[24].links.s = {}
          region.rooms[24].links.s.to = 141
          region.rooms[24].links.s.con = ""
      region.rooms[24].exits = "south|east"
      region.rooms[24].desc = "    这是北大街的马厩，常年供应新鲜草料。苏州民风淳朴，马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净，一直伺候到客人上路。马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。    马厩中堆放著几堆草料，正中有一口泔槽。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly sz;w;s;sw"
      region.rooms[25].name = "戏园子"
      region.rooms[25].zone = "苏州"
      region.rooms[25].id = 141
      region.rooms[25].links = {}
        region.rooms[25].links.ne = {}
          region.rooms[25].links.ne.to = 136
          region.rooms[25].links.ne.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 140
          region.rooms[25].links.n.con = ""
      region.rooms[25].exits = "north|northeast"
      region.rooms[25].desc = "    这是一座苏州城里鼎鼎有名的戏园，戏园中生，旦，净，墨，丑一应具全，场中一个大戏台，台上正在唱着《遇长春》，台下不时地传来票友们的叫跃，喝彩声。你也忍不住想坐下来看看戏，放松一下筋骨。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly sz;w"
      region.rooms[26].name = "北大街"
      region.rooms[26].zone = "苏州"
      region.rooms[26].id = 142
      region.rooms[26].links = {}
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 144
          region.rooms[26].links.e.con = ""
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 136
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.w = {}
          region.rooms[26].links.w.to = 143
          region.rooms[26].links.w.con = ""
        region.rooms[26].links.n = {}
          region.rooms[26].links.n.to = 145
          region.rooms[26].links.n.con = ""
      region.rooms[26].exits = "south|north|east|west"
      region.rooms[26].desc = "    这是一条宽阔的青石街道，向南北两头延伸。北边是北城门通向城外。南边显得很繁忙。东边是一座两层的楼阁，名为春在楼。西面是一座庙庵，南面是一条笔直的大街，十分繁华。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly sz;w;w"
      region.rooms[27].name = "紫金庵"
      region.rooms[27].zone = "苏州"
      region.rooms[27].id = 143
      region.rooms[27].links = {}
        region.rooms[27].links.e = {}
          region.rooms[27].links.e.to = 142
          region.rooms[27].links.e.con = ""
      region.rooms[27].exits = "east"
      region.rooms[27].desc = "    这是一座苏州城里有名的寺庵，庵中正面是释加摩尼佛眼，似乎在注视前来礼佛之人；右壁一尊诸天用三个手指托起一块轻柔的绣花经盖和后壁观音菩萨头上的一顶刻着牡丹花的紫红色华盖。左壁的每尊罗汉塑像造型生动，各具特征，到达了以神人话、精神超忽、呼之欲活的艺术境界，令人叹为观止。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly sz"
      region.rooms[28].name = "春在楼"
      region.rooms[28].zone = "苏州"
      region.rooms[28].id = 144
      region.rooms[28].links = {}
        region.rooms[28].links.w = {}
          region.rooms[28].links.w.to = 142
          region.rooms[28].links.w.con = ""
      region.rooms[28].exits = "west"
      region.rooms[28].desc = "    这是一座苏州城里有名的酒楼，整个楼面以雕刻为特色，砖雕，木雕，石雕。走进楼内，一眼便看到一副八仙上寿图，八仙人被描画的惟妙惟肖。楼内许多南北来往的门客正在聊天品茶，只见店小二忙的不亦乐乎。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly sz;w;n"
      region.rooms[29].name = "北门"
      region.rooms[29].zone = "苏州"
      region.rooms[29].id = 145
      region.rooms[29].links = {}
        region.rooms[29].links.s = {}
          region.rooms[29].links.s.to = 142
          region.rooms[29].links.s.con = ""
        region.rooms[29].links.n = {}
          region.rooms[29].links.n.to = 146
          region.rooms[29].links.n.con = ""
      region.rooms[29].exits = "south|north"
      region.rooms[29].desc = "    这是苏州府的北城门。出门远远可见西面的虎丘山。放眼望去尽是绿的田，翠的草和清清的小河。门边官兵身后贴着一份告示(gaoshi)。南北一条笔直的官道。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly sz;w;n;n"
      region.rooms[30].name = "青石官道"
      region.rooms[30].zone = "苏州"
      region.rooms[30].id = 146
      region.rooms[30].links = {}
        region.rooms[30].links.sw = {}
          region.rooms[30].links.sw.to = 147
          region.rooms[30].links.sw.con = ""
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 145
          region.rooms[30].links.s.con = ""
        region.rooms[30].links.nw = {}
          region.rooms[30].links.nw.to = 159
          region.rooms[30].links.nw.con = ""
      region.rooms[30].exits = "south|northwest|southwest"
      region.rooms[30].desc = "    你走在一条青石大道上，人来人往非常繁忙，不时地有人骑着马匆匆而过。大道两旁有一些小货摊，似乎是一处集市。南面就是苏州城了。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly sz;w;n;n;sw"
      region.rooms[31].name = "虎丘山"
      region.rooms[31].zone = "苏州"
      region.rooms[31].id = 147
      region.rooms[31].links = {}
        region.rooms[31].links.ne = {}
          region.rooms[31].links.ne.to = 146
          region.rooms[31].links.ne.con = ""
        region.rooms[31].links.s = {}
          region.rooms[31].links.s.to = 148
          region.rooms[31].links.s.con = ""
      region.rooms[31].exits = "south|northeast"
      region.rooms[31].desc = "    虎丘山因其山形似蹲虎而得名。又相传吴王葬后，有白虎出现其墓上，故名虎丘。山前绝岩幽谷，花木繁茂，景色绮丽，后山空蒙宽广，石壁树立，气势雄浑。有“山藏寺里”的特色，被誉为“吴中第一名胜”。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly sz;w;n;n;sw;s"
      region.rooms[32].name = "头门山"
      region.rooms[32].zone = "苏州"
      region.rooms[32].id = 148
      region.rooms[32].links = {}
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 149
          region.rooms[32].links.w.con = ""
        region.rooms[32].links.n = {}
          region.rooms[32].links.n.to = 147
          region.rooms[32].links.n.con = ""
      region.rooms[32].exits = "north|west"
      region.rooms[32].desc = "    头山门在虎丘山的南面，形似虎头。隔河照墙上书着“海涌流辉”四个大字，以示虎丘与大海的渊源关系。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly sz;w;n;n;sw;s;w"
      region.rooms[33].name = "万景山庄"
      region.rooms[33].zone = "苏州"
      region.rooms[33].id = 149
      region.rooms[33].links = {}
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 148
          region.rooms[33].links.e.con = ""
        region.rooms[33].links.eu = {}
          region.rooms[33].links.eu.to = 151
          region.rooms[33].links.eu.con = ""
        region.rooms[33].links.wu = {}
          region.rooms[33].links.wu.to = 150
          region.rooms[33].links.wu.con = ""
      region.rooms[33].exits = "westup|east|eastup"
      region.rooms[33].desc = "    在虎丘山东面就是万景山庄，是一个较大的盆景园，有盆名为“秦汉遗韵”的圆柏，树龄已逾五百年，被誉为“盆景之王”。还有盆景为“云蒸霞蔚”的树石盆景和另一盆四百多年的雀梅古桩盆景，都是盆景艺术的中的珍品。圆内景色优美，颇富园林雅趣。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly sz;w;n;n;sw;s;w;wu"
      region.rooms[34].name = "憨憨泉"
      region.rooms[34].zone = "苏州"
      region.rooms[34].id = 150
      region.rooms[34].links = {}
        region.rooms[34].links.ed = {}
          region.rooms[34].links.ed.to = 149
          region.rooms[34].links.ed.con = ""
      region.rooms[34].exits = "eastdown"
      region.rooms[34].desc = "    在山道西侧有一憨憨泉，系南朝梁代高僧憨憨尊者所开凿，距今一千四百多年。据说泉眼通海，姑又名“海涌泉”。水甚清冽为“天下第五泉”。石刻“憨憨泉”三字，系北宋吕升卿所题。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly sz;w;n;n;sw;s;w;eu"
      region.rooms[35].name = "试剑石"
      region.rooms[35].zone = "苏州"
      region.rooms[35].id = 151
      region.rooms[35].links = {}
        region.rooms[35].links.ne = {}
          region.rooms[35].links.ne.to = 153
          region.rooms[35].links.ne.con = ""
        region.rooms[35].links.s = {}
          region.rooms[35].links.s.to = 155
          region.rooms[35].links.s.con = ""
        region.rooms[35].links.wd = {}
          region.rooms[35].links.wd.to = 149
          region.rooms[35].links.wd.con = ""
        region.rooms[35].links.n = {}
          region.rooms[35].links.n.to = 152
          region.rooms[35].links.n.con = ""
      region.rooms[35].exits = "south|north|northeast|westdown"
      region.rooms[35].desc = "    在山道东侧是试剑石，呈椭圆形，正中有条深而齐裂的裂缝，相传吴王得“干将”，“莫邪”剑后，为试其锋利，将石劈开。石旁刻着元代顾瑛的诗句“剑试一痕秋，崖倾水断流，如何百年后，不斩赵高头？”的诗句。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly sz;w;n;n;sw;s;w;eu;n"
      region.rooms[36].name = "枕石"
      region.rooms[36].zone = "苏州"
      region.rooms[36].id = 152
      region.rooms[36].links = {}
        region.rooms[36].links.s = {}
          region.rooms[36].links.s.to = 151
          region.rooms[36].links.s.con = ""
      region.rooms[36].exits = "south"
      region.rooms[36].desc = "    在山半腰有一块巨石，因石形如枕而得名枕石。相传东晋高僧，常在此倚石阅经，倦则枕石休息。此石其形又象蜒蚰，故亦称“蜒蚰石”。另因有“唐寅三笑姻缘”的传说，故又名“鸳鸯石”。这块大石，实系海涌山遗物。"
    region.rooms[37] = {}
      region.rooms[37].path = "fly sz;w;n;n;sw;s;w;eu;ne"
      region.rooms[37].name = "真娘墓"
      region.rooms[37].zone = "苏州"
      region.rooms[37].id = 153
      region.rooms[37].links = {}
        region.rooms[37].links.n = {}
          region.rooms[37].links.n.to = 154
          region.rooms[37].links.n.con = ""
        region.rooms[37].links.sw = {}
          region.rooms[37].links.sw.to = 151
          region.rooms[37].links.sw.con = ""
      region.rooms[37].exits = "north|southwest"
      region.rooms[37].desc = "    在试剑石北面就是古真娘墓，真娘也称贞娘，因安史之乱流落江南，受骗流落堕入青楼。贞娘为守贞操，自尽抗之。后人筑亭其上，墓前石刻“香魂”两字，墓上遍栽花卉。唐代白居易等诗人墨客纷纷为之题诗，褒赞真娘之贞烈。"
    region.rooms[38] = {}
      region.rooms[38].path = "fly sz;w;n;n;sw;s;w;eu;ne;n"
      region.rooms[38].name = "孙武亭"
      region.rooms[38].zone = "苏州"
      region.rooms[38].id = 154
      region.rooms[38].links = {}
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 153
          region.rooms[38].links.s.con = ""
      region.rooms[38].exits = "south"
      region.rooms[38].desc = "    在真娘幕后的土丘上，有一座小亭子，名为孙武亭。相传春秋时，兵家孙武曾在此训练两队宫女，由吴王的两个宠姬分别担任队长，由于宠姬与宫女们不听军令，虽三令五申，仍置若罔闻，孙武遂下令，先斩两姬于军前以整军纪。后人遂筑此亭。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly sz;w;n;n;sw;s;w;eu;s"
      region.rooms[39].name = "千人石"
      region.rooms[39].zone = "苏州"
      region.rooms[39].id = 155
      region.rooms[39].links = {}
        region.rooms[39].links.e = {}
          region.rooms[39].links.e.to = 156
          region.rooms[39].links.e.con = ""
        region.rooms[39].links.nw = {}
          region.rooms[39].links.nw.to = 158
          region.rooms[39].links.nw.con = ""
        region.rooms[39].links.n = {}
          region.rooms[39].links.n.to = 151
          region.rooms[39].links.n.con = ""
      region.rooms[39].exits = "northwest|north|east"
      region.rooms[39].desc = "    在虎丘山中心，有一块千人石，巨石呈暗紫红色，由南向北倾斜石面甚平坦，石壁如斧削。传说吴王墓筑成后，其子夫差怕泄露筑墓秘密假借墓成祝酒观舞之名，将千余名工匠全部杀戮，鲜血渗透石中，成暗红色。"
    region.rooms[40] = {}
      region.rooms[40].path = "fly sz;w;n;n;sw;s;w;eu;s;e"
      region.rooms[40].name = "二仙亭"
      region.rooms[40].zone = "苏州"
      region.rooms[40].id = 156
      region.rooms[40].links = {}
        region.rooms[40].links.w = {}
          region.rooms[40].links.w.to = 155
          region.rooms[40].links.w.con = ""
        region.rooms[40].links.n = {}
          region.rooms[40].links.n.to = 157
          region.rooms[40].links.n.con = ""
      region.rooms[40].exits = "north|west"
      region.rooms[40].desc = "    二仙亭在千人石东侧，建于北宋。亭壁嵌两方石碑，分别刻着五代宋初陈抟与唐代吕洞宾二仙像。亭柱上有两幅石刻楹联：“梦中说梦原非梦，元里求元便是元”；“昔日岳阳曾显迹，今朝虎阜再留踪”。"
    region.rooms[41] = {}
      region.rooms[41].path = "fly sz;w;n;n;sw;s;w;eu;s;e;n"
      region.rooms[41].name = "白莲池"
      region.rooms[41].zone = "苏州"
      region.rooms[41].id = 157
      region.rooms[41].links = {}
        region.rooms[41].links.s = {}
          region.rooms[41].links.s.to = 156
          region.rooms[41].links.s.con = ""
      region.rooms[41].exits = "south"
      region.rooms[41].desc = "    白莲池位于二仙亭的北面，池中种有千叶莲花，池上架彩莲曲桥，相传吴王夫差与西施曾在此采莲赏荷。"
    region.rooms[42] = {}
      region.rooms[42].path = "fly sz;w;n;n;sw;s;w;eu;s;nw"
      region.rooms[42].name = "致爽阁"
      region.rooms[42].zone = "苏州"
      region.rooms[42].id = 158
      region.rooms[42].links = {}
        region.rooms[42].links.se = {}
          region.rooms[42].links.se.to = 155
          region.rooms[42].links.se.con = ""
      region.rooms[42].exits = "southeast"
      region.rooms[42].desc = "    在千人石西面就是致爽阁，又名伏虎阁，在虎丘塔的西南面，是山上的最高点。阁名取“四山爽气，日夕西来”之意。旧称“小五台”，是海涌峰顶。阁外平台宽阔，俯瞰沃野；远眺群峰逶迤，可赏著名上午“狮子回头看虎丘”一景。深秋季节观成群飞翔的苍鹰，蔚为壮观。"
    region.rooms[43] = {}
      region.rooms[43].path = "fly sz;w;n;n;nw"
      region.rooms[43].name = "山路"
      region.rooms[43].zone = "苏州|归云庄1"
      region.rooms[43].id = 159
      region.rooms[43].desc = "    这里是一片农田。不远处有一些村庄，炊烟袅袅升起。村庄周围是一块块的田地，田里有一些正在耕作的农人。"
      region.rooms[43].exits = "southeast|southwest"
      region.rooms[43].links = {}
        region.rooms[43].links.se = {}
          region.rooms[43].links.se.to = 146
          region.rooms[43].links.se.con = ""
        region.rooms[43].links.sw = {}
          region.rooms[43].links.sw.to = 2622
          region.rooms[43].links.sw.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly sz;w;s;s;se"
      region.rooms[44].name = "东大街"
      region.rooms[44].zone = "苏州"
      region.rooms[44].id = 160
      region.rooms[44].links = {}
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 161
          region.rooms[44].links.s.con = ""
        region.rooms[44].links.e = {}
          region.rooms[44].links.e.to = 166
          region.rooms[44].links.e.con = ""
        region.rooms[44].links.sw = {}
          region.rooms[44].links.sw.to = 135
          region.rooms[44].links.sw.con = ""
        region.rooms[44].links.nw = {}
          region.rooms[44].links.nw.to = 134
          region.rooms[44].links.nw.con = ""
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 162
          region.rooms[44].links.n.con = ""
      region.rooms[44].exits = "south|northwest|north|east|southwest"
      region.rooms[44].desc = "    你走在东大街上，踩着坚实的青石板地面。东边是东大街的延伸，南面是苏州城里一个老字号的当铺，北面是一条小胡同。"
    region.rooms[45] = {}
      region.rooms[45].path = "fly sz;w;s;s;se;s"
      region.rooms[45].name = "宝和记"
      region.rooms[45].zone = "苏州"
      region.rooms[45].id = 161
      region.rooms[45].links = {}
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 160
          region.rooms[45].links.n.con = ""
      region.rooms[45].exits = "north"
      region.rooms[45].desc = "    这是一家以买卖公平著称的当铺，一个五尺高的柜台挡在你的面前，柜台上摆着一个牌子(paizi)，柜台后坐着位老板，一双精明的眼睛上上下下打量着你。"
    region.rooms[46] = {}
      region.rooms[46].path = "fly sz;w;s;s;se;n"
      region.rooms[46].name = "胡同"
      region.rooms[46].zone = "苏州"
      region.rooms[46].id = 162
      region.rooms[46].links = {}
        region.rooms[46].links.ne = {}
          region.rooms[46].links.ne.to = 164
          region.rooms[46].links.ne.con = ""
        region.rooms[46].links.w = {}
          region.rooms[46].links.w.to = 163
          region.rooms[46].links.w.con = ""
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 160
          region.rooms[46].links.s.con = ""
      region.rooms[46].exits = "south|northeast|west"
      region.rooms[46].desc = "    这是一条黑暗、肮脏的小巷，空气中仿佛飘扬着一股罪恶的气息，东北边通向小巷深处，正人君子当然是不会往那边走去的。往南走就会回到城中大路了。西面是一条小巷，名为“生死巷”。"
    region.rooms[47] = {}
      region.rooms[47].path = "fly sz;w;s;s;se;n;w"
      region.rooms[47].name = "擂台前广场"
      region.rooms[47].zone = "苏州"
      region.rooms[47].id = 163
      region.rooms[47].links = {}
        region.rooms[47].links.e = {}
          region.rooms[47].links.e.to = 162
          region.rooms[47].links.e.con = ""
      region.rooms[47].exits = "east"
      region.rooms[47].desc = "    这里是苏州擂台前面的一个大型广场，有许多人正在擂台上比武，到处是人山人海，如果你也想试试身手，那么就请跳上擂台比试比试吧。"
    region.rooms[48] = {}
      region.rooms[48].path = "fly sz;w;s;s;se;n;ne"
      region.rooms[48].name = "胡同"
      region.rooms[48].zone = "苏州"
      region.rooms[48].id = 164
      region.rooms[48].links = {}
        region.rooms[48].links.e = {}
          region.rooms[48].links.e.to = 165
          region.rooms[48].links.e.con = ""
        region.rooms[48].links.sw = {}
          region.rooms[48].links.sw.to = 162
          region.rooms[48].links.sw.con = ""
      region.rooms[48].exits = "east|southwest"
      region.rooms[48].desc = "    这是一条黑暗、肮脏的小巷，空气中仿佛飘扬着一股罪恶的气息，几个贼眉鼠眼地盯着你的腰包，看来会马上扑上来。"
    region.rooms[49] = {}
      region.rooms[49].path = "fly sz;w;s;s;se;e;nw"
      region.rooms[49].name = "胡同"
      region.rooms[49].zone = "苏州"
      region.rooms[49].id = 165
      region.rooms[49].links = {}
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 164
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.se = {}
          region.rooms[49].links.se.to = 166
          region.rooms[49].links.se.con = ""
      region.rooms[49].exits = "southeast|west"
      region.rooms[49].desc = "    这是一条黑暗、肮脏的小巷，空气中仿佛飘扬着一股罪恶的气息，几个流氓在游荡，向东南就能回到大街，你还是赶快走吧。"
    region.rooms[50] = {}
      region.rooms[50].path = "fly sz;w;s;s;se;e"
      region.rooms[50].name = "东大街"
      region.rooms[50].zone = "苏州"
      region.rooms[50].id = 166
      region.rooms[50].links = {}
        region.rooms[50].links.s = {}
          region.rooms[50].links.s.to = 167
          region.rooms[50].links.s.con = ""
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 169
          region.rooms[50].links.e.con = ""
        region.rooms[50].links.nw = {}
          region.rooms[50].links.nw.to = 165
          region.rooms[50].links.nw.con = ""
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 160
          region.rooms[50].links.w.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 168
          region.rooms[50].links.n.con = ""
      region.rooms[50].exits = "south|northwest|north|east|west"
      region.rooms[50].desc = "    你走在东大街上，踩着坚实的青石板地面。东边是东城门，可以听到守城官兵的吆喝声，北边是一家老字号的药铺，南边是打铁铺，叮叮当当的声音老远就能听到。"
    region.rooms[51] = {}
      region.rooms[51].path = "fly sz;w;s;s;se;e;s"
      region.rooms[51].name = "打铁铺"
      region.rooms[51].zone = "苏州"
      region.rooms[51].id = 167
      region.rooms[51].links = {}
        region.rooms[51].links.n = {}
          region.rooms[51].links.n.to = 166
          region.rooms[51].links.n.con = ""
      region.rooms[51].exits = "north"
      region.rooms[51].desc = "    这是一家简陋的打铁铺，中心一个火炉，炉火忽红忽青，热焰灼人。一位光膀铁匠满头大汗挥舞着铁锤，专心致志地在打铁。墙角堆满了已完工和未完工的铁器等物。"
    region.rooms[52] = {}
      region.rooms[52].path = "fly sz;w;s;s;se;e;n"
      region.rooms[52].name = "立春堂"
      region.rooms[52].zone = "苏州"
      region.rooms[52].id = 168
      region.rooms[52].links = {}
        region.rooms[52].links.s = {}
          region.rooms[52].links.s.to = 166
          region.rooms[52].links.s.con = ""
      region.rooms[52].exits = "south"
      region.rooms[52].desc = "    这是一家药铺，一股浓浓的药味让你几欲窒息，那是从药柜上的几百个小抽屉里散发出来的。药房先生却不在店内。一名小伙计站在柜台后招呼着顾客。"
    region.rooms[53] = {}
      region.rooms[53].path = "fly sz;w;s;s;se;e;e"
      region.rooms[53].name = "东门"
      region.rooms[53].zone = "苏州"
      region.rooms[53].id = 169
      region.rooms[53].links = {}
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 166
          region.rooms[53].links.w.con = ""
      region.rooms[53].exits = "west"
      region.rooms[53].desc = "    这是号称天堂的苏州东城门，城门正上方刻着“东门”两个楷书大字，城墙上贴着几张官府告示(gaoshi)。官兵们警惕地注视着过往行人，你最好小心为妙。一条笔直的青石板大道向东西两边延伸，西边是城里。"
    region.rooms[54] = {}
      region.rooms[54].path = "fly sz;w;s;s;s;s"
      region.rooms[54].name = "南大街"
      region.rooms[54].zone = "苏州"
      region.rooms[54].id = 170
      region.rooms[54].links = {}
        region.rooms[54].links.ne = {}
          region.rooms[54].links.ne.to = 172
          region.rooms[54].links.ne.con = ""
        region.rooms[54].links.s = {}
          region.rooms[54].links.s.to = 181
          region.rooms[54].links.s.con = ""
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 174
          region.rooms[54].links.e.con = ""
        region.rooms[54].links.sw = {}
          region.rooms[54].links.sw.to = 173
          region.rooms[54].links.sw.con = ""
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 171
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.n = {}
          region.rooms[54].links.n.to = 135
          region.rooms[54].links.n.con = ""
      region.rooms[54].exits = "south|north|east|northeast|west|southwest"
      region.rooms[54].desc = "    南大街乃是城里的繁华地段，一到晚上，一派灯红酒绿，尤为热闹。笑声、歌声、琴声、箫声，汇成一片送入了你的耳朵，你不禁心猿意马，很想就此停步享受一番。苏州的城里秀丽景色此时已使你心旷神怡，此时此刻只想与这大自然秀丽的景色融为一体。从这里看去，苏州南城的街景是一片喧闹。在街的东北面是一个茶馆，正东望去是一座苏州园林。"
    region.rooms[55] = {}
      region.rooms[55].path = "fly sz;w;s;s;s;s;w"
      region.rooms[55].name = "聚宝斋"
      region.rooms[55].zone = "苏州"
      region.rooms[55].id = 171
      region.rooms[55].links = {}
        region.rooms[55].links.e = {}
          region.rooms[55].links.e.to = 170
          region.rooms[55].links.e.con = ""
      region.rooms[55].exits = "east"
      region.rooms[55].desc = "    这是一家老字号的钱庄，已有几百年的历史，在全国各地都有分店。它发行的银票信誉非常好，通行全国。    在对面的墙上挂了块牌子(paizi)。"
    region.rooms[56] = {}
      region.rooms[56].path = "fly sz;w;s;s;s;s;ne"
      region.rooms[56].name = "茶馆"
      region.rooms[56].zone = "苏州"
      region.rooms[56].id = 172
      region.rooms[56].links = {}
        region.rooms[56].links.sw = {}
          region.rooms[56].links.sw.to = 170
          region.rooms[56].links.sw.con = ""
      region.rooms[56].exits = "southwest"
      region.rooms[56].desc = "    你一走进来，就闻到一股茶香沁入心脾，精神为之一爽。几张八仙桌一字排开，坐满了客人，或高声谈笑，或交头接耳。几个店伙计在一旁伺候着客人们，在台后坐着一位老板娘，正在弹着算盘。"
    region.rooms[57] = {}
      region.rooms[57].path = "fly sz;w;s;s;s;s;sw"
      region.rooms[57].name = "书院"
      region.rooms[57].zone = "苏州"
      region.rooms[57].id = 173
      region.rooms[57].links = {}
        region.rooms[57].links.ne = {}
          region.rooms[57].links.ne.to = 170
          region.rooms[57].links.ne.con = ""
      region.rooms[57].exits = "northeast"
      region.rooms[57].desc = "    这里是书院的讲堂，窗明几净，一尘不染。一位老夫子坐在太师椅上讲学。在他的两侧坐满了求学的学生。一张古意盎然的书案放在他的前面，案上摆着几本翻开了的线装书籍。"
    region.rooms[58] = {}
      region.rooms[58].path = "fly sz;w;s;s;s;s;e"
      region.rooms[58].name = "狮子林"
      region.rooms[58].zone = "苏州"
      region.rooms[58].id = 174
      region.rooms[58].links = {}
        region.rooms[58].links.ne = {}
          region.rooms[58].links.ne.to = 175
          region.rooms[58].links.ne.con = ""
        region.rooms[58].links.w = {}
          region.rooms[58].links.w.to = 170
          region.rooms[58].links.w.con = ""
        region.rooms[58].links.e = {}
          region.rooms[58].links.e.to = 176
          region.rooms[58].links.e.con = ""
      region.rooms[58].exits = "east|northeast|west"
      region.rooms[58].desc = "    你一走进狮子林，便不禁为江南苏州园林的奇妙美景所折服。狮子林东南多山，西北多水，素有”假山王国“之称。假山峰峦叠嶂，曲折盘旋，石洞连绵不断，幽深莫测。咫尺之间，可望而不可及，变幻无穷如入迷宫，不由得不为之赞叹不已。"
    region.rooms[59] = {}
      region.rooms[59].path = "fly sz;w;s;s;s;s;e;ne"
      region.rooms[59].name = "揖峰指柏轩"
      region.rooms[59].zone = "苏州"
      region.rooms[59].id = 175
      region.rooms[59].links = {}
        region.rooms[59].links.sw = {}
          region.rooms[59].links.sw.to = 174
          region.rooms[59].links.sw.con = ""
      region.rooms[59].exits = "southwest"
      region.rooms[59].desc = "    这里曾是为园主接待宾客和亲友的地方，有时也作为演戏说书或写诗做画之处。轩名取朱熹“前揖庐山，一峰独绣”和高启的“笑指庭前柏”句诗意。轩内摆设古香古色。凭轩眺望，满目石峰嶙峋，古柏虬枝盘绕，旧有桃源“十八景”之称。"
    region.rooms[60] = {}
      region.rooms[60].path = "fly sz;w;s;s;s;s;e;e"
      region.rooms[60].name = "燕誉堂"
      region.rooms[60].zone = "苏州"
      region.rooms[60].id = 176
      region.rooms[60].links = {}
        region.rooms[60].links.w = {}
          region.rooms[60].links.w.to = 174
          region.rooms[60].links.w.con = ""
        region.rooms[60].links.se = {}
          region.rooms[60].links.se.to = 177
          region.rooms[60].links.se.con = ""
      region.rooms[60].exits = "southeast|west"
      region.rooms[60].desc = "    燕誉堂是全园主厅，旧时系园主宴客处。曾经作为御膳房。堂名取于《诗经》：“式燕且誉，好而无射”。此处建筑为鸳鸯厅形状，高敞宏丽，堂内陈设富丽精致。"
    region.rooms[61] = {}
      region.rooms[61].path = "fly sz;w;s;s;s;s;e;e;se"
      region.rooms[61].name = "真趣亭"
      region.rooms[61].zone = "苏州"
      region.rooms[61].id = 177
      region.rooms[61].links = {}
        region.rooms[61].links.e = {}
          region.rooms[61].links.e.to = 179
          region.rooms[61].links.e.con = ""
        region.rooms[61].links.s = {}
          region.rooms[61].links.s.to = 178
          region.rooms[61].links.s.con = ""
        region.rooms[61].links.nw = {}
          region.rooms[61].links.nw.to = 176
          region.rooms[61].links.nw.con = ""
      region.rooms[61].exits = "south|northwest|east"
      region.rooms[61].desc = "    亭内高高悬挂御笔题写的“真趣”匾一块。亭内装饰精致金碧辉煌。梁架、围屏、裙板上雕刻的人物、花鸟图案惟妙惟肖。在此可以环览全园景色。南边新从四川搬来一位叫刘好弈的子爵，听说他喜好围棋，家里收藏了不少棋谱。"
    region.rooms[62] = {}
      region.rooms[62].path = "fly sz;w;s;s;s;s;e;e;se;s"
      region.rooms[62].name = "书房门口"
      region.rooms[62].zone = "苏州"
      region.rooms[62].id = 178
      region.rooms[62].links = {}
        region.rooms[62].links.n = {}
          region.rooms[62].links.n.to = 177
          region.rooms[62].links.n.con = ""
      region.rooms[62].exits = "north|enter"
      region.rooms[62].desc = "    这是棋痴「世袭子爵」刘好弈书房的门口，布置的相当雅致，刘好弈正站在门口，一脸得意之色，不知遇到了什么高兴事。"
    region.rooms[63] = {}
      region.rooms[63].path = "fly sz;w;s;s;s;s;e;e;se;e"
      region.rooms[63].name = "问梅阁"
      region.rooms[63].zone = "苏州"
      region.rooms[63].id = 179
      region.rooms[63].links = {}
        region.rooms[63].links.w = {}
          region.rooms[63].links.w.to = 177
          region.rooms[63].links.w.con = ""
        region.rooms[63].links.s = {}
          region.rooms[63].links.s.to = 180
          region.rooms[63].links.s.con = ""
      region.rooms[63].exits = "south|west"
      region.rooms[63].desc = "    阁内的桌凳、花窗、地坪、书画皆取材于梅花，并悬匾额“绮窗春讯”。阁前种植了许多枝梅，以符阁名。曾为旧时文人著书、绘画之处。"
    region.rooms[64] = {}
      region.rooms[64].path = "fly sz;w;s;s;s;s;e;e;se;e;s"
      region.rooms[64].name = "立雪堂"
      region.rooms[64].zone = "苏州"
      region.rooms[64].id = 180
      region.rooms[64].links = {}
        region.rooms[64].links.n = {}
          region.rooms[64].links.n.to = 179
          region.rooms[64].links.n.con = ""
      region.rooms[64].exits = "north"
      region.rooms[64].desc = "    立雪堂名自“程门力雪”和“断臂力雪”之典。堂前小院中的湖石、形似牛、蟹、狮、蛙，谓“狮子静观牛吃蟹”，颇生动有趣。"
    region.rooms[65] = {}
      region.rooms[65].path = "fly sz;w;s;s;s;s;s"
      region.rooms[65].name = "南大街"
      region.rooms[65].zone = "苏州"
      region.rooms[65].id = 181
      region.rooms[65].links = {}
        region.rooms[65].links.e = {}
          region.rooms[65].links.e.to = 186
          region.rooms[65].links.e.con = ""
        region.rooms[65].links.s = {}
          region.rooms[65].links.s.to = 187
          region.rooms[65].links.s.con = ""
        region.rooms[65].links.w = {}
          region.rooms[65].links.w.to = 182
          region.rooms[65].links.w.con = ""
        region.rooms[65].links.n = {}
          region.rooms[65].links.n.to = 170
          region.rooms[65].links.n.con = ""
      region.rooms[65].exits = "south|north|east|west"
      region.rooms[65].desc = "    你走在一条繁华的街道上，向南北两头延伸。北边通往城南大街的中心地段，东面是听雨轩，西面是留园，望南面，是苏州城的南城门。"
    region.rooms[66] = {}
      region.rooms[66].path = "fly sz;w;s;s;s;s;s;w"
      region.rooms[66].name = "留园"
      region.rooms[66].zone = "苏州"
      region.rooms[66].id = 182
      region.rooms[66].links = {}
        region.rooms[66].links.e = {}
          region.rooms[66].links.e.to = 181
          region.rooms[66].links.e.con = ""
        region.rooms[66].links.w = {}
          region.rooms[66].links.w.to = 183
          region.rooms[66].links.w.con = ""
      region.rooms[66].exits = "east|west"
      region.rooms[66].desc = "    留园是苏州的一大名景之一，它以结构布局紧密、厅堂华丽宏敝、装饰精美典雅而享有“吴中第一名园”之誉。"
    region.rooms[67] = {}
      region.rooms[67].path = "fly sz;w;s;s;s;s;s;w;w"
      region.rooms[67].name = "荷花厅"
      region.rooms[67].zone = "苏州"
      region.rooms[67].id = 183
      region.rooms[67].links = {}
        region.rooms[67].links.e = {}
          region.rooms[67].links.e.to = 182
          region.rooms[67].links.e.con = ""
        region.rooms[67].links.w = {}
          region.rooms[67].links.w.to = 184
          region.rooms[67].links.w.con = ""
      region.rooms[67].exits = "east|west"
      region.rooms[67].desc = "    荷花厅的主建筑面阔三间，宽敝高爽，厅名取朱熹：“一水方涵碧，千林以变红”之诗意。厅前宽广的平台依临荷池，为夏日赏荷纳凉胜处，故称“荷花厅”。厅后有花台庭院，叠石种树，自成一景。"
    region.rooms[68] = {}
      region.rooms[68].path = "fly sz;w;s;s;s;s;s;w;w;w"
      region.rooms[68].name = "古木交诃"
      region.rooms[68].zone = "苏州"
      region.rooms[68].id = 184
      region.rooms[68].links = {}
        region.rooms[68].links.e = {}
          region.rooms[68].links.e.to = 183
          region.rooms[68].links.e.con = ""
        region.rooms[68].links.sw = {}
          region.rooms[68].links.sw.to = 185
          region.rooms[68].links.sw.con = ""
      region.rooms[68].exits = "east|southwest"
      region.rooms[68].desc = "    古木交诃在荷花厅的西面，一排不同图案的漏窗，使你透过漏窗隐隐看到中部的水光山色和高低错落的楼阁，此处赏景，有“移步幻影”之妙。向西窗孔可以遥望绿荫轩、明瑟楼，给人一种“庭院深深深几许”和空间不尽之感。"
    region.rooms[69] = {}
      region.rooms[69].path = "fly sz;w;s;s;s;s;s;w;w;w;sw"
      region.rooms[69].name = "池塘"
      region.rooms[69].zone = "苏州"
      region.rooms[69].id = 185
      region.rooms[69].links = {}
        region.rooms[69].links.ne = {}
          region.rooms[69].links.ne.to = 184
          region.rooms[69].links.ne.con = ""
      region.rooms[69].exits = "northeast"
      region.rooms[69].desc = "    一池池水映入你的眼帘，小蓬莱翼然水中，曲折的石桥上架着紫藤花棚。池东你可以看到曲溪楼、西楼、清风池等小筑，掩映于花木山石之间。池西的山腰间，桂树丛生。秋日，置身于“闻木樨香轩”，阵阵桂香，沁人心脾。轩下，水涧两岸叠石重重，你不禁为此景而赞叹不已。"
    region.rooms[70] = {}
      region.rooms[70].path = "fly sz;w;s;s;s;s;s;e"
      region.rooms[70].name = "听雨轩"
      region.rooms[70].zone = "苏州"
      region.rooms[70].id = 186
      region.rooms[70].links = {}
        region.rooms[70].links.w = {}
          region.rooms[70].links.w.to = 181
          region.rooms[70].links.w.con = ""
      region.rooms[70].exits = "west"
      region.rooms[70].desc = "    听雨轩是苏州城内的一处唯一的一家书店了。这里有着各种各样的书籍，什么小说啦、风光旅游啦、手艺制作啦、基本武功啦，等等等等。只须花几两银子就可买到你想要的书。"
    region.rooms[71] = {}
      region.rooms[71].path = "fly sz;w;s;s;s;s;s;s"
      region.rooms[71].name = "南门"
      region.rooms[71].zone = "苏州"
      region.rooms[71].id = 187
      region.rooms[71].links = {}
        region.rooms[71].links.s = {}
          region.rooms[71].links.s.to = 188
          region.rooms[71].links.s.con = ""
        region.rooms[71].links.n = {}
          region.rooms[71].links.n.to = 181
          region.rooms[71].links.n.con = ""
      region.rooms[71].exits = "south|north"
      region.rooms[71].desc = "    这是苏州府的南城门。进进出出的吴侬软语，听来特让人舒服。门口的官兵开口喝骂，也是这种软绵声气。门上贴着一份告示(gaoshi)。南北一条笔直的官道。"
    region.rooms[72] = {}
      region.rooms[72].path = "fly sz;w;s;s;s;s;s;s;s"
      region.rooms[72].name = "青石官道"
      region.rooms[72].zone = "苏州"
      region.rooms[72].id = 188
      region.rooms[72].links = {}
        region.rooms[72].links.sw = {}
          region.rooms[72].links.sw.to = 189
          region.rooms[72].links.sw.con = ""
        region.rooms[72].links.se = {}
          region.rooms[72].links.se.to = 190
          region.rooms[72].links.se.con = ""
        region.rooms[72].links.n = {}
          region.rooms[72].links.n.to = 187
          region.rooms[72].links.n.con = ""
      region.rooms[72].exits = "north|southeast|southwest"
      region.rooms[72].desc = "    你走在一条青石大道上，人来人往非常繁忙，不时地有人骑着马匆匆而过。北面就是苏州城了。西南边远远望去，波光粼闪，白帆点缀，便是周遭五百里的太湖了。"
    region.rooms[73] = {}
      region.rooms[73].path = "fly sz;w;s;s;s;s;s;s;s;sw"
      region.rooms[73].name = "湖边"
      region.rooms[73].zone = "苏州|燕子坞1"
      region.rooms[73].id = 189
      region.rooms[73].links = {}
        region.rooms[73].links.ne = {}
          region.rooms[73].links.ne.to = 188
          region.rooms[73].links.ne.con = ""
        region.rooms[73].links.nw = {}
          region.rooms[73].links.nw.to = 2547
          region.rooms[73].links.nw.con = ""
      region.rooms[73].exits = "northwest|northeast"
      region.rooms[73].desc = "    俗话说：上有天堂，下有苏杭。这里正是大大有名的太湖。湖面绿波上漂着一叶叶的小舟, 一阵阵悦耳的小曲儿随着湖上的轻风不时漂入你的耳中。"
    region.rooms[74] = {}
      region.rooms[74].path = "fly sz;w;s;s;s;s;s;s;s;se"
      region.rooms[74].name = "山路"
      region.rooms[74].zone = "苏州|嘉兴"
      region.rooms[74].id = 190
      region.rooms[74].links = {}
        region.rooms[74].links.s = {}
          region.rooms[74].links.s.to = 192
          region.rooms[74].links.s.con = ""
        region.rooms[74].links.nw = {}
          region.rooms[74].links.nw.to = 188
          region.rooms[74].links.nw.con = ""
        region.rooms[74].links.se = {}
          region.rooms[74].links.se.to = 191
          region.rooms[74].links.se.con = ""
      region.rooms[74].exits = "south|northwest|southeast"
      region.rooms[74].desc = "    你走在一条山路上。时值春日，路旁的山坡上开满了金黄色的油菜花。东面是江南名城嘉兴。西边望去，波光粼闪，白帆点缀，便是周遭五百里的太湖了。"
  region.center = 144
return region