local region = {}
  region.cmd = "fly thd"
  region.name = "桃花岛"
  region.id = "thd"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly wm;e;s;s;e;e;s"
      region.rooms[1].name = "打铁铺"
      region.rooms[1].zone = "扬州|桃花岛"
      region.rooms[1].id = 73
      region.rooms[1].links = {}
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 74
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 72
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "south|north"
      region.rooms[1].desc = "    这是一家简陋的打铁铺，中心摆着一个火炉，炉火把四周照得一片通红，你一走进去就感到浑身火热。墙角堆满了已完工和未完工的菜刀、铁锤、铁棍、匕首、盔甲等物。一位铁匠满头大汗挥舞着铁锤，专心致志地在打铁。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly wm;e;s;s;e;e;s;s"
      region.rooms[2].name = "大院"
      region.rooms[2].zone = "扬州|桃花岛"
      region.rooms[2].id = 74
      region.rooms[2].links = {}
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 73
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "north"
      region.rooms[2].desc = "    这是一个破旧的大院。院子倒挺宽阔，可以容下百十人。院子右首有一对白雕(diao)。原来这里是桃花岛为方便弟子回岛而特意建起的。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly thd"
      region.rooms[3].name = "桃花山庄正厅"
      region.rooms[3].zone = "桃花岛"
      region.rooms[3].id = 2386
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 2390
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 2387
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 2391
          region.rooms[3].links.n.con = ""
      region.rooms[3].exits = "south|east|north|west"
      region.rooms[3].desc = "    这里是桃花山庄的正厅。整个大厅十分宽阔。厅中挂满了各种名家的书法真迹。但最显眼的则是正中挂的一幅对联：            桃花影落飞神剑            碧海潮生按玉箫字体遒劲挺拔，气势宏伟。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly thd;s"
      region.rooms[4].name = "后院"
      region.rooms[4].zone = "桃花岛"
      region.rooms[4].id = 2387
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 2389
          region.rooms[4].links.e.con = ""
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 2388
          region.rooms[4].links.w.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 2386
          region.rooms[4].links.n.con = ""
      region.rooms[4].exits = "east|north|west"
      region.rooms[4].desc = "    这是山庄的后院。院中摆着几个机关人，是给桃花岛弟子练功用的。院后是桃花岛的唯一一座山峰：弹指峰。整个桃花山庄倚山而立，险势天成。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly thd;s;w"
      region.rooms[5].name = "小屋"
      region.rooms[5].zone = "桃花岛"
      region.rooms[5].id = 2388
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 2387
          region.rooms[5].links.e.con = ""
      region.rooms[5].exits = "east"
      region.rooms[5].desc = "    这是专供仆人休息的小屋。屋里放着五六张床，挤挤地占掉了屋子的一大半地方。屋角很散乱地放了一些日常生活用具。中央放着一张桌子，上面摆一茶壶和几个杯子。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly thd;s;e"
      region.rooms[6].name = "思过室"
      region.rooms[6].zone = "桃花岛"
	  region.rooms[6].danger = 3
      region.rooms[6].id = 2389
      region.rooms[6].links = {}
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 2387
          region.rooms[6].links.w.con = ""
      region.rooms[6].exits = "west"
      region.rooms[6].desc = "    这是桃花岛上供本门弟子闭门思过的地方。屋里仅仅放着一张床，显得空荡荡的。四面则是光秃秃的墙壁，看上去黑黝黝的，原来却是铁筑的。靠门的地方有一小洞，洞边放着一只碗。往东是一间不起眼的小屋，门上挂了个牌子「桃花轩」。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly thd;e"
      region.rooms[7].name = "道具房"
      region.rooms[7].zone = "桃花岛"
      region.rooms[7].id = 2390
      region.rooms[7].links = {}
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 2386
          region.rooms[7].links.w.con = ""
      region.rooms[7].exits = "up|west"
      region.rooms[7].desc = "    这是一间道具房。摆着一些桃花弟子们常用的东西。房里好象黑乎乎的，靠窗处有一张斑驳长桌和一把靠背椅，虽是白天还点着小油灯。哑仆看到你进来，就使劲瞪着你，虽然口不能言，可你还是心中惴惴。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly thd;n"
      region.rooms[8].name = "桃花山庄前院"
      region.rooms[8].zone = "桃花岛"
      region.rooms[8].id = 2391
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 2392
          region.rooms[8].links.e.con = ""
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 2393
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 2386
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 2394
          region.rooms[8].links.n.con = ""
      region.rooms[8].exits = "south|east|north|west"
      region.rooms[8].desc = "    你现在正站在一个宽敞的院子中。院子原来是作为练武场用的。但自从桃花岛弟子被黄药师逐出岛外，就已经没人在此练武。东面是兵器室，西面是厨房，往南就是桃花山庄正厅了。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly thd;n;e"
      region.rooms[9].name = "兵器室"
      region.rooms[9].zone = "桃花岛"
      region.rooms[9].id = 2392
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 2391
          region.rooms[9].links.w.con = ""
      region.rooms[9].exits = "west"
      region.rooms[9].desc = "    这是一间存放兵器的屋子。刀、枪、剑、戟等各种兵器都按类放在各自的兵器架上。整个屋子落满灰尘，显然已经好久没人来过。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly thd;n;w"
      region.rooms[10].name = "厨房"
      region.rooms[10].zone = "桃花岛"
      region.rooms[10].id = 2393
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 2391
          region.rooms[10].links.e.con = ""
      region.rooms[10].exits = "east"
      region.rooms[10].desc = "    这是桃花岛的厨房，中央摆着大圆桌，周围则放着几张竹椅。窗口还摆着几盆水仙花。你吸了一下鼻子，啊．．．好香！也不知到底是花香还是饭香。平时桃花岛的弟子和仆人都在这里用餐。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly thd;n;n"
      region.rooms[11].name = "桃花山庄正门"
      region.rooms[11].zone = "桃花岛"
      region.rooms[11].id = 2394
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 2395
          region.rooms[11].links.e.con = ""
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 2391
          region.rooms[11].links.s.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 2404
          region.rooms[11].links.n.con = ""
      region.rooms[11].exits = "south|east|north"
      region.rooms[11].desc = "    这里是桃花山庄的正门。门前疏落有致地种了几株桃花树，更显得此地主人对桃花的偏爱。门口站着两个小童看守大门。看来由于地处边远，人烟罕至，人们对山庄的防卫不是特别谨慎。门前有一对白雕(diao)。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly thd;n;n;e"
      region.rooms[12].name = "小路"
      region.rooms[12].zone = "桃花岛"
      region.rooms[12].id = 2395
      region.rooms[12].links = {}
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 2394
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 2396
          region.rooms[12].links.e.con = ""
      region.rooms[12].exits = "east|west"
      region.rooms[12].desc = "    这是一条小径，弯弯曲曲向远方延伸。小径两边种植了一些桃花树。你只一瞥就发现：这些桃花全是白色的。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly thd;n;n;e;e"
      region.rooms[13].name = "小路"
      region.rooms[13].zone = "桃花岛"
      region.rooms[13].id = 2396
      region.rooms[13].links = {}
        region.rooms[13].links.w = {}
          region.rooms[13].links.w.to = 2395
          region.rooms[13].links.w.con = ""
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 2397
          region.rooms[13].links.s.con = ""
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 2400
          region.rooms[13].links.n.con = ""
      region.rooms[13].exits = "south|north|west"
      region.rooms[13].desc = "    这是一条小径，弯弯曲曲向远方延伸。小径两边种植了一些桃花树。你只一瞥就发现：这些桃花全是白色的。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly thd;n;n;e;e;s"
      region.rooms[14].name = "小路"
      region.rooms[14].zone = "桃花岛"
      region.rooms[14].id = 2397
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 2398
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 2396
          region.rooms[14].links.n.con = ""
      region.rooms[14].exits = "north|east"
      region.rooms[14].desc = "    这是一条通往后山的小径。小路两旁长满了杂草。由于人们很少走这条路，甚至连路中央也稀稀疏疏冒出了草芽。东边有一个小山洞。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly thd;n;n;e;e;s;e"
      region.rooms[15].name = "洞口"
      region.rooms[15].zone = "桃花岛"
      region.rooms[15].id = 2398
      region.rooms[15].links = {}
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 2397
          region.rooms[15].links.w.con = ""
        region.rooms[15].links.enter = {}
          region.rooms[15].links.enter.to = 2399
          region.rooms[15].links.enter.con = ""
      region.rooms[15].exits = "enter|west"
      region.rooms[15].desc = "    这是一条后山上的一个小山洞。洞口很小，但能容一个人钻进去。里面黑黝黝的什么也看不见。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly thd;n;n;e;e;s;e;enter"
      region.rooms[16].name = "山洞"
      region.rooms[16].zone = "桃花岛"
      region.rooms[16].id = 2399
      region.rooms[16].links = {}
        region.rooms[16].links.out = {}
          region.rooms[16].links.out.to = 2398
          region.rooms[16].links.out.con = ""
      region.rooms[16].exits = "out"
      region.rooms[16].desc = "    你正处在一个小山洞中。这里光线很暗，只能隐隐约约看出地上有一堆干草。干草上好象放着一个石匣(xia)。 你突然闻到一股难闻的气味，显然是有人长期住在这里却不打扫的缘故。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly thd;n;n;e;e;n"
      region.rooms[17].name = "小路"
      region.rooms[17].zone = "桃花岛"
      region.rooms[17].id = 2400
      region.rooms[17].links = {}
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 2396
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 2401
          region.rooms[17].links.n.con = ""
      region.rooms[17].exits = "south|north"
      region.rooms[17].desc = "    这是一条小径，弯弯曲曲向远方延伸。小径两边种植了一些桃花树。你只一瞥就发现：这些桃花全是白色的。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly thd;n;n;e;e;n;n"
      region.rooms[18].name = "墓地"
      region.rooms[18].zone = "桃花岛"
      region.rooms[18].id = 2401
      region.rooms[18].links = {}
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 2400
          region.rooms[18].links.s.con = ""
        region.rooms[18].links["#3 (push bei left);#3 (push bei right);d"] = {}
          region.rooms[18].links["#3 (push bei left);#3 (push bei right);d"].to = 2402
          region.rooms[18].links["#3 (push bei left);#3 (push bei right);d"].con = ""
      region.rooms[18].exits = "south"
      region.rooms[18].desc = "    这里是桃花岛岛主夫人的墓地。墓地周围种了一些矮矮的花树。树上的白花星星点点。白花中间是一高大的石碑 (bei)，碑后是两扇坚固的石门。整个墓地干干净净，显然天天有人打扫。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly thd;n;n;e;e;n;n;#3 (push bei left);#3 (push bei right);d"
      region.rooms[19].name = "墓道"
      region.rooms[19].zone = "桃花岛"
      region.rooms[19].id = 2402
      region.rooms[19].links = {}
        region.rooms[19].links.d = {}
          region.rooms[19].links.d.to = 2403
          region.rooms[19].links.d.con = ""
        region.rooms[19].links["#3 (push bei left);#3 (push bei right);u"] = {}
          region.rooms[19].links["#3 (push bei left);#3 (push bei right);u"].to = 2401
          region.rooms[19].links["#3 (push bei left);#3 (push bei right);u"].con = ""
      region.rooms[19].exits = "up|down"
      region.rooms[19].desc = "    这是通往墓室的通道。通道十分宽敞，顶部悬挂着一颗大大的夜明珠，照得整个墓道如同白昼。墓道尽头便是墓室。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly thd;n;n;e;e;n;n;#3 (push bei left);#3 (push bei right);d;d"
      region.rooms[20].name = "墓室"
      region.rooms[20].zone = "桃花岛"
      region.rooms[20].id = 2403
      region.rooms[20].links = {}
        region.rooms[20].links.u = {}
          region.rooms[20].links.u.to = 2402
          region.rooms[20].links.u.con = ""
      region.rooms[20].exits = "up"
      region.rooms[20].desc = "    这是一间墓室。墓室顶上有一颗特别大的明珠闪闪发光。中央放着一副玉棺，周围则堆放了无数的奇珍异玩。一张供桌摆在玉棺前，桌上放着一个香炉及一个盘子 (panzi)。墓室对面挂这一幅青年少妇的画像。画像上的少妇巧笑嫣然，和惨白的玉棺及碧油油的珠光形成了一幅奇诡的画面。忽然一阵阴风吹过，你不禁打了一个寒颤。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly thd;n;n;n"
      region.rooms[21].name = "试剑亭"
      region.rooms[21].zone = "桃花岛"
      region.rooms[21].id = 2404
      region.rooms[21].links = {}
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 2394
          region.rooms[21].links.s.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 2405
          region.rooms[21].links.n.con = ""
      region.rooms[21].exits = "south|north"
      region.rooms[21].desc = "    这里是一个用白玉石砌成的亭子，亭子砌得小巧玲珑，十分精巧。亭子的北面是一片桃花林，南面则是桃花山庄的正门。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly thd;n;n;n;n"
      region.rooms[22].name = "桃花迷阵"
      region.rooms[22].zone = "桃花岛"
      region.rooms[22].id = 2405
      region.rooms[22].links = {}
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 2404
          region.rooms[22].links.s.con = ""
        region.rooms[22].links.n = {}
          region.rooms[22].links.n.to = 2988
          region.rooms[22].links.n.con = ""
      region.rooms[22].exits = "south|north"
      region.rooms[22].desc = "    这是一片桃花的海洋。四周一望无际，全是盛开的桃花。微风拂过，落英缤纷。周围静悄悄的。远处偶尔传来一声鸟叫。往北是一片桃花林，往南则是一个小亭子。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly thd;n;n;n;n;n;|!thmz:n:n|"
      region.rooms[23].name = "海滩"
      region.rooms[23].zone = "桃花岛"
      region.rooms[23].id = 2406
      region.rooms[23].links = {}
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 2988
          region.rooms[23].links.s.con = ""
      region.rooms[23].exits = "south"
      region.rooms[23].desc = "    这是桃花岛前的海滩。往北是一望无际的大海；往南则是一片桃花林。蓝蓝的海蓝蓝的天，金黄色的沙滩，粉红的桃花，这一切都是那么美。海边泊着一艘大船(chuan)。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly thd;n;n;n;n;n"
      region.rooms[24].name = "桃花迷阵"
      region.rooms[24].zone = "桃花岛"
      region.rooms[24].id = 2988
      region.rooms[24].links = {}
        region.rooms[24].links.s = {}
          region.rooms[24].links.s.to = 2405
          region.rooms[24].links.s.con = "thmz:s"
        region.rooms[24].links.n = {}
          region.rooms[24].links.n.to = 2406
          region.rooms[24].links.n.con = "thmz:n"
      region.rooms[24].exits = "south|north|east|west"
      region.rooms[24].desc = "    这是一片桃花的海洋。四周一望无际，全是盛开的桃花。微风拂过，落英缤纷。周围静悄悄的。远处偶尔传来一声鸟叫。你心中不禁慌乱起来：还是早点出去的好。"
  region.center = 2386
return region