local region = {}
  region.cmd = "fly tls"
  region.name = "天龙寺"
  region.id = "tls"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly tls;n;n;n;n"
      region.rooms[1].name = "宏圣寺塔"
      region.rooms[1].zone = "大理|天龙寺"
      region.rooms[1].id = 663
      region.rooms[1].links = {}
        region.rooms[1].links.enter = {}
          region.rooms[1].links.enter.to = 1605
          region.rooms[1].links.enter.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 657
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 1609
          region.rooms[1].links.s.con = ""
      region.rooms[1].exits = "south|enter|west"
      region.rooms[1].desc = "    宏圣寺塔又名“一塔”，屹立于苍山之麓，面向洱海，为云南著名唐塔之一。宏圣寺塔为四方形空心砖石塔，塔身各层之间用砖砌出跌涩椽，使其四角飞翘。整个塔身轮廓呈抛物线，优美流畅。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly tls;n;n;n;n;enter"
      region.rooms[2].name = "塔基"
      region.rooms[2].zone = "天龙寺"
      region.rooms[2].id = 1605
      region.rooms[2].desc = "    宏圣寺塔基座系用石板砌成，与千寻塔基为砖砌不同。基座西面有塔门，可入内攀登而上。"
      region.rooms[2].exits = "up|out"
      region.rooms[2].links = {}
        region.rooms[2].links.u = {}
          region.rooms[2].links.u.to = 1606
          region.rooms[2].links.u.con = ""
        region.rooms[2].links.out = {}
          region.rooms[2].links.out.to = 663
          region.rooms[2].links.out.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly tls;n;n;n;n;enter;u"
      region.rooms[3].name = "宏圣寺塔"
      region.rooms[3].zone = "天龙寺"
      region.rooms[3].id = 1606
      region.rooms[3].desc = "    这里是宏圣寺塔内部，四面墙壁上都辟有佛龛，龛内置佛像。抬头上望，可以看到中心柱、葫芦顶、伞盖、相轮及莲花座托等。伞盖成八角形，角上挂有风铎。"
      region.rooms[3].exits = "up|down"
      region.rooms[3].links = {}
        region.rooms[3].links.u = {}
          region.rooms[3].links.u.to = 1607
          region.rooms[3].links.u.con = ""
        region.rooms[3].links.d = {}
          region.rooms[3].links.d.to = 1605
          region.rooms[3].links.d.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly tls;n;n;n;n;enter;u;u"
      region.rooms[4].name = "宏圣寺塔"
      region.rooms[4].zone = "天龙寺"
      region.rooms[4].id = 1607
      region.rooms[4].desc = "    这里是宏圣寺塔内部，四面墙壁上都辟有佛龛，龛内置佛像。抬头上望，可以看到中心柱、葫芦顶、伞盖、相轮及莲花座托等。伞盖成八角形，角上挂有风铎。"
      region.rooms[4].exits = "up|down"
      region.rooms[4].links = {}
        region.rooms[4].links.u = {}
          region.rooms[4].links.u.to = 1608
          region.rooms[4].links.u.con = ""
        region.rooms[4].links.d = {}
          region.rooms[4].links.d.to = 1606
          region.rooms[4].links.d.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly tls;n;n;n;n;enter;u;u;u"
      region.rooms[5].name = "宏圣寺塔"
      region.rooms[5].zone = "天龙寺"
      region.rooms[5].id = 1608
      region.rooms[5].desc = "    这里是宏圣寺塔内部，四面墙壁上都辟有佛龛，龛内置佛像。西面塔壁由模印砖所砌，上面用梵，汉文刻了阴形文的“阿众佛灭正保咒”。"
      region.rooms[5].exits = "down"
      region.rooms[5].links = {}
        region.rooms[5].links.d = {}
          region.rooms[5].links.d.to = 1607
          region.rooms[5].links.d.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly tls;n;n;n"
      region.rooms[6].name = "大门"
      region.rooms[6].zone = "天龙寺"
      region.rooms[6].id = 1609
      region.rooms[6].desc = "    你来到了天龙寺大门前，只见气势恢弘的两个大门柱上刻有一付对联( duilian )，红漆覆字，颇有点拨众生之意。抬头上望，门楣上一块黑木大匾，上题“崇圣寺”三个大字，笔意苍松。此乃正式寺名，但大理百性叫惯了，都称之为“天龙寺”。"
      region.rooms[6].exits = "south|north"
      region.rooms[6].links = {}
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 1610
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 663
          region.rooms[6].links.n.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly tls;n;n"
      region.rooms[7].name = "塔林"
      region.rooms[7].zone = "天龙寺"
      region.rooms[7].id = 1610
      region.rooms[7].desc = "    这是一片塔林。放眼望去，林林总总有不下百座高矮不一的石塔，这些都是达官显贵们捐资修筑的，或是为了祈求菩萨保佑，或是为了还愿平心。东西北三面各有一座高塔。"
      region.rooms[7].exits = "south|north|east|west"
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 1612
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 1611
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 1613
          region.rooms[7].links.w.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 1609
          region.rooms[7].links.n.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly tls;n"
      region.rooms[8].name = "舍利塔"
      region.rooms[8].zone = "天龙寺"
      region.rooms[8].id = 1611
      region.rooms[8].desc = "    这是天龙三塔中最高的一座，高约三百余尺，共有十六级。相传塔顶原本供奉着一颗前代高僧的舍利子，但在当年奸臣杨义贞弑上德帝篡位以至天下大乱时，舍利子不知何因而失踪了，这也成为天龙寺历代主持的心腹大事。这个传言也不知是真是假。"
      region.rooms[8].exits = "south|north|east|west"
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 1615
          region.rooms[8].links.e.con = ""
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 1614
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 1621
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 1610
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly tls;n;n;e"
      region.rooms[9].name = "舍利塔"
      region.rooms[9].zone = "天龙寺"
      region.rooms[9].id = 1612
      region.rooms[9].desc = "    这是天龙三塔之一，建于唐初，年代久远。传说月圆之夜，在此塔之下默许心愿，塔顶会出现圣光指点迷津，助你达成心愿。"
      region.rooms[9].exits = "west"
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 1610
          region.rooms[9].links.w.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly tls;n;n;w"
      region.rooms[10].name = "舍利塔"
      region.rooms[10].zone = "天龙寺"
      region.rooms[10].id = 1613
      region.rooms[10].desc = "    这是天龙三塔之一，建于唐初，年代久远。虽然塔身已经石迹斑驳，但是仍然耸立挺拔，俨然是天龙寺百年威名的象征。"
      region.rooms[10].exits = "east"
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 1610
          region.rooms[10].links.e.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly tls"
      region.rooms[11].name = "崇圣宝殿"
      region.rooms[11].zone = "天龙寺"
      region.rooms[11].id = 1614
      region.rooms[11].desc = "    这是一座宽广的大殿，正面有一座高约二十余尺的佛祖宝像，通体金光耀眼。座下香烟缭绕。大殿两旁树立两根檀木大柱，题有一联，云曰：　　　　　　守口摄意身莫犯　　莫恼一切诸有情　"
      region.rooms[11].exits = "north"
      region.rooms[11].links = {}
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 1611
          region.rooms[11].links.n.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly tls;n;e"
      region.rooms[12].name = "无我阁"
      region.rooms[12].zone = "天龙寺"
      region.rooms[12].id = 1615
      region.rooms[12].desc = "    这是历代大理王侯前来进香还愿时休息的地方。阁内檀象宝炉，软榻矮几，一应俱全，清静之中隐然透出一丝富贵之象。"
      region.rooms[12].exits = "south|west"
      region.rooms[12].links = {}
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 1611
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 1616
          region.rooms[12].links.s.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly tls;n;e;s"
      region.rooms[13].name = "瑞鹤门"
      region.rooms[13].zone = "天龙寺"
      region.rooms[13].id = 1616
      region.rooms[13].desc = "    这是通往天龙寺后寺的门户。你低头看看地上，只见铜门槛早已被踩踏得锃亮，足见此寺香火之盛了。抬头向南可以望见点苍山耸立云天。"
      region.rooms[13].exits = "south|north"
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 1617
          region.rooms[13].links.s.con = ""
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 1615
          region.rooms[13].links.n.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly tls;n;e;s;s"
      region.rooms[14].name = "无常阁"
      region.rooms[14].zone = "天龙寺"
      region.rooms[14].id = 1617
      region.rooms[14].desc = "    这是历代大理王侯前来进香还愿时休息的地方。阁内檀象宝炉，软榻矮几，一应俱全，清静之中隐然透出一丝富贵之象。"
      region.rooms[14].exits = "north|west"
      region.rooms[14].links = {}
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 1618
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 1616
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly tls;n;e;s;s;w"
      region.rooms[15].name = "晃天门"
      region.rooms[15].zone = "天龙寺"
      region.rooms[15].id = 1618
      region.rooms[15].desc = "    这是出入前后寺的必经之路。往南望去，可见后寺中亭台楼阁规模宏大，构筑精丽，宅地连云，其气势之盛更胜于五台，普陀等诸处佛门胜地的名山大寺。"
      region.rooms[15].exits = "south|east|west"
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 1617
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 1619
          region.rooms[15].links.w.con = ""
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 1622
          region.rooms[15].links.s.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly tls;n;w;s;s"
      region.rooms[16].name = "无乐阁"
      region.rooms[16].zone = "天龙寺"
      region.rooms[16].id = 1619
      region.rooms[16].desc = "    这是历代大理王侯前来进香还愿时休息的地方。阁内檀象宝炉，软榻矮几，一应俱全，清静之中隐然透出一丝富贵之象。"
      region.rooms[16].exits = "east|north"
      region.rooms[16].links = {}
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 1618
          region.rooms[16].links.e.con = ""
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 1620
          region.rooms[16].links.n.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly tls;n;w;s"
      region.rooms[17].name = "翔鹤门"
      region.rooms[17].zone = "天龙寺"
      region.rooms[17].id = 1620
      region.rooms[17].desc = "    这是通往天龙寺后寺的门户。你低头看看地上，只见铜门槛早已被踩踏得锃亮，足见此寺香火之盛了。抬头向南可以望见点苍山耸立云天。"
      region.rooms[17].exits = "south|north"
      region.rooms[17].links = {}
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 1619
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 1621
          region.rooms[17].links.n.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly tls;n;w"
      region.rooms[18].name = "无净阁"
      region.rooms[18].zone = "天龙寺"
      region.rooms[18].id = 1621
      region.rooms[18].desc = "    这是历代大理王侯前来进香还愿时休息的地方。阁内檀象宝炉，软榻矮几，一应俱全，清静之中隐然透出一丝富贵之象。"
      region.rooms[18].exits = "south|east"
      region.rooms[18].links = {}
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 1620
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 1611
          region.rooms[18].links.e.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly tls;n;e;s;s;w;s"
      region.rooms[19].name = "清都瑶台"
      region.rooms[19].zone = "天龙寺"
      region.rooms[19].id = 1622
      region.rooms[19].desc = "    这是出入前后寺的必经之路。往南望去，可见后寺中亭台楼阁规模宏大，构筑精丽，宅地连云，其气势之盛更胜于五台，普陀等诸处佛门胜地的名山大寺。"
      region.rooms[19].exits = "south|north"
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 1623
          region.rooms[19].links.s.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 1618
          region.rooms[19].links.n.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly tls;n;e;s;s;w;s;s"
      region.rooms[20].name = "无无境"
      region.rooms[20].zone = "天龙寺"
      region.rooms[20].id = 1623
      region.rooms[20].desc = "    一片水池静卧眼前，一座精雕木桥横跨其上，与其倒影恰成一圆，映着空灵的水面，使你心中似有所动。仿佛体会到了众生之源，万物之本的真谛。"
      region.rooms[20].exits = "south|east|north|west"
      region.rooms[20].links = {}
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 1626
          region.rooms[20].links.e.con = ""
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 1624
          region.rooms[20].links.s.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 1629
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 1622
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly tls;n;e;s;s;w;s;s;s"
      region.rooms[21].name = "清心阁"
      region.rooms[21].zone = "天龙寺"
      region.rooms[21].id = 1624
      region.rooms[21].desc = "    这是寺中诸僧前去后院参修之前清心净欲的地方。阁中只有地面放有几个蒲团，除此之外别无它物，确然是个清静之处。"
      region.rooms[21].exits = "south|north"
      region.rooms[21].links = {}
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 1625
          region.rooms[21].links.s.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 1623
          region.rooms[21].links.n.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly tls;n;e;s;s;w;s;s;s;s"
      region.rooms[22].name = "兜率大士院"
      region.rooms[22].zone = "天龙寺"
      region.rooms[22].id = 1625
      region.rooms[22].desc = "    这是一般参拜者所能到的最远的地方，再往南就是天龙寺历代高僧静修之处──牟尼堂。那是常人不可轻易打搅的地方，你最好不要擅自闯入。除非你确信能给高僧们带去好消息。院子里摆着一个大香炉。"
      region.rooms[22].exits = "south|northwest|north|northeast"
      region.rooms[22].links = {}
        region.rooms[22].links.ne = {}
          region.rooms[22].links.ne.to = 1627
          region.rooms[22].links.ne.con = ""
        region.rooms[22].links.nw = {}
          region.rooms[22].links.nw.to = 1628
          region.rooms[22].links.nw.con = ""
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 1630
          region.rooms[22].links.s.con = ""
        region.rooms[22].links.n = {}
          region.rooms[22].links.n.to = 1624
          region.rooms[22].links.n.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly tls;n;e;s;s;w;s;s;e"
      region.rooms[23].name = "雨花院"
      region.rooms[23].zone = "天龙寺"
      region.rooms[23].id = 1626
      region.rooms[23].desc = "    相传当年佛祖降临天龙寺传法时，漫天遍洒雨花石。后人以石建院，即成此间玉花院。院中常年檀香四溢，令人心旷神怡。"
      region.rooms[23].exits = "south|west"
      region.rooms[23].links = {}
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 1623
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 1627
          region.rooms[23].links.s.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly tls;n;e;s;s;w;s;s;e;s"
      region.rooms[24].name = "斗母宫"
      region.rooms[24].zone = "天龙寺"
      region.rooms[24].id = 1627
      region.rooms[24].desc = "    这是给进香客们休息的地方。四周围放着一溜檀木红漆椅。几个进香客坐在上面休息。"
      region.rooms[24].exits = "north|southwest"
      region.rooms[24].links = {}
        region.rooms[24].links.n = {}
          region.rooms[24].links.n.to = 1626
          region.rooms[24].links.n.con = ""
        region.rooms[24].links.sw = {}
          region.rooms[24].links.sw.to = 1625
          region.rooms[24].links.sw.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly tls;n;e;s;s;w;s;s;w;s"
      region.rooms[25].name = "三无宫"
      region.rooms[25].zone = "天龙寺"
      region.rooms[25].id = 1628
      region.rooms[25].desc = "    这里可以买香到后面参拜西方大士。几个进香客正围着一个老年僧人讨价还价。"
      region.rooms[25].exits = "north|southeast"
      region.rooms[25].links = {}
        region.rooms[25].links.se = {}
          region.rooms[25].links.se.to = 1625
          region.rooms[25].links.se.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 1629
          region.rooms[25].links.n.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly tls;n;e;s;s;w;s;s;w"
      region.rooms[26].name = "慈悲院"
      region.rooms[26].zone = "天龙寺"
      region.rooms[26].id = 1629
      region.rooms[26].desc = "    这是僧人们点化顽徒的地方。不少江湖豪客由于厌倦了打打杀杀的日子，来到此处落发为僧，叛依佛门。墙上一幅佛祖神像，两边各有一条幅，上书：放下屠刀，立地成佛。"
      region.rooms[26].exits = "south|east"
      region.rooms[26].links = {}
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 1628
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 1623
          region.rooms[26].links.e.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly tls;n;e;s;s;w;s;s;s;s;s"
      region.rooms[27].name = "般若台"
      region.rooms[27].zone = "天龙寺"
      region.rooms[27].id = 1630
      region.rooms[27].desc = "    这是个普通的石台，相传当年佛祖曾降临此台传法。再往南去就是本寺重地──牟尼堂。江湖中传言天龙寺的镇寺之宝──六脉神剑谱就藏于此中，但你千万不要打什么主意。"
      region.rooms[27].exits = "south|north"
      region.rooms[27].links = {}
        region.rooms[27].links.s = {}
          region.rooms[27].links.s.to = 1631
          region.rooms[27].links.s.con = ""
        region.rooms[27].links.n = {}
          region.rooms[27].links.n.to = 1625
          region.rooms[27].links.n.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly tls;n;e;s;s;w;s;s;s;s;s;s"
      region.rooms[28].name = "牟尼堂"
      region.rooms[28].zone = "天龙寺"
      region.rooms[28].id = 1631
      region.rooms[28].desc = "    这是高僧们的静修之处。整堂全以松木制成，板门木柱，木料均不去皮，天然质朴，和一路行来金碧辉煌的殿堂截然不同。堂里的墙上挂着几副剑谱(jianpu)。室中五个和尚分坐五个蒲团。四僧朝外，东首一个和尚面朝里壁一动不动。"
      region.rooms[28].exits = "north"
      region.rooms[28].links = {}
        region.rooms[28].links.n = {}
          region.rooms[28].links.n.to = 1630
          region.rooms[28].links.n.con = ""
  region.center = 1614
return region