local region = {}
  region.cmd = "fly tzf"
  region.name = "铁掌峰"
  region.id = "tzf"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly tzf"
      region.rooms[1].name = "五指堂"
      region.rooms[1].zone = "铁掌峰"
      region.rooms[1].id = 2219
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 2236
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 2239
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.sd = {}
          region.rooms[1].links.sd.to = 2220
          region.rooms[1].links.sd.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 2243
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "north|east|southdown|west"
      region.rooms[1].desc = "    这是一间完全用花岗岩砌成的大厅，透出阵阵逼人的寒气。整座房屋没有窗户，显得阴森黑暗。两旁的墙壁上插着松油火把，散发出昏黄的光亮，寂静的大厅中不时响起火把噼啪的燃烧声。大厅的正中摆放着帮主的宝座，两旁分列着十几把椅子，只有遇到帮中大事时，帮主才会在这里与部下商议。在正面的墙上挂着一面缕金的横匾(bian)。北面有一扇小门通向后面。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly tzf;sd"
      region.rooms[2].name = "广场"
      region.rooms[2].zone = "铁掌峰"
      region.rooms[2].id = 2220
      region.rooms[2].links = {}
        region.rooms[2].links.nu = {}
          region.rooms[2].links.nu.to = 2219
          region.rooms[2].links.nu.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 2223
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 2224
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 2221
          region.rooms[2].links.e.con = ""
      region.rooms[2].exits = "south|east|northup|west"
      region.rooms[2].desc = "    山路行到这里，忽然变得开阔，你眼前出现了一片很大的广场。一些铁掌帮的弟子来回穿梭于其间，显得很忙碌。在广场的周围有很多岩石建的房子。正面的这间尤其显得高大雄伟。左面的房子中不时的涌出阵阵热气，其间还加杂着鼓风的声音。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly tzf;sd;e"
      region.rooms[3].name = "瓜架"
      region.rooms[3].zone = "铁掌峰"
      region.rooms[3].id = 2221
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 2220
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.se = {}
          region.rooms[3].links.se.to = 2222
          region.rooms[3].links.se.con = ""
      region.rooms[3].exits = "southeast|west"
      region.rooms[3].desc = "    转过一个小弯，忽然眼前一绿，面前是一片很大的瓜架。在高大的木架旁，种植着一些蔬菜和瓜类，架子上已爬满了各种植物，从茂密的叶 子中，垂下各种已经成熟的果实，丝瓜，苦瓜，葫芦...还有一些叫不出名称的瓜果也缠杂在其中。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly tzf;sd;e;se"
      region.rooms[4].name = "蝴蝶泉"
      region.rooms[4].zone = "铁掌峰"
      region.rooms[4].id = 2222
      region.rooms[4].links = {}
        region.rooms[4].links.nw = {}
          region.rooms[4].links.nw.to = 2221
          region.rooms[4].links.nw.con = ""
      region.rooms[4].exits = "northwest"
      region.rooms[4].desc = "    在向前行，一路上嫣红姹紫，遍山遍野都是鲜花。春光烂漫已极。转过一树花丛，眼前出现一眼泉水，泉水清澈见底，散发出一种沁人心脾的 清凉。泉水的旁边，飞舞一群群的蝴蝶，或花或白，或黑或紫，翩翩起舞。 蝴蝶并不畏人，飞近时便在人们的身上停留。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly tzf;sd;w"
      region.rooms[5].name = "练功房"
      region.rooms[5].zone = "铁掌峰"
      region.rooms[5].id = 2223
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 2220
          region.rooms[5].links.e.con = ""
      region.rooms[5].exits = "east"
      region.rooms[5].desc = "    这是一间用花岗岩砌成的石屋。室内一只大炉中燃了洪炭，煮着热气腾腾的一镬(huo )东西，镬旁两个黑衣小童，一个使劲推拉风箱，另一个用铁铲翻炒镬中之物，听这沙沙之声，所炒的似是铁沙。几名帮中弟子闭目盘膝坐在锅前，或对着腾上的热气吐呐，或插指于镬中苦练。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly tzf;sd;s"
      region.rooms[6].name = "山路"
      region.rooms[6].zone = "铁掌峰"
      region.rooms[6].id = 2224
      region.rooms[6].links = {}
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 2225
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 2220
          region.rooms[6].links.n.con = ""
      region.rooms[6].exits = "south|north"
      region.rooms[6].desc = "    你走在一条崎岖的山路上，道旁山峰壁立，长草过腰，中间一条羊肠小路，仅容一人勉强过去。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly tzf;sd;s;s"
      region.rooms[7].name = "山路"
      region.rooms[7].zone = "铁掌峰"
      region.rooms[7].id = 2225
      region.rooms[7].links = {}
        region.rooms[7].links.sd = {}
          region.rooms[7].links.sd.to = 2226
          region.rooms[7].links.sd.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 2224
          region.rooms[7].links.n.con = ""
      region.rooms[7].exits = "north|southdown"
      region.rooms[7].desc = "    你走在一条崎岖的山路上，道旁山峰壁立，长草过腰，中间一条羊肠小路，仅容一人勉强过去。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly tzf;sd;s;s;sd"
      region.rooms[8].name = "山门"
      region.rooms[8].zone = "铁掌峰"
      region.rooms[8].id = 2226
      region.rooms[8].links = {}
        region.rooms[8].links.nu = {}
          region.rooms[8].links.nu.to = 2225
          region.rooms[8].links.nu.con = ""
        region.rooms[8].links.sd = {}
          region.rooms[8].links.sd.to = 2227
          region.rooms[8].links.sd.con = ""
      region.rooms[8].exits = "northup|southdown"
      region.rooms[8].desc = "    这里就是江湖上闻风丧胆的“铁掌帮”。自从“铁掌歼衡山”一役将衡山派打得一蹶不振之后，帮主铁掌水上漂的名头威震江湖。这里是进山的必经之路，曲的小路通向山里。路的一侧立着一块牌子(paizi) 。两旁的树林内不时传出一些响声，似乎有人在暗中监视。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly tzf;sd;s;s;sd;sd"
      region.rooms[9].name = "山脚下"
      region.rooms[9].zone = "铁掌峰"
      region.rooms[9].id = 2227
      region.rooms[9].links = {}
        region.rooms[9].links.nu = {}
          region.rooms[9].links.nu.to = 2226
          region.rooms[9].links.nu.con = ""
        region.rooms[9].links.se = {}
          region.rooms[9].links.se.to = 2228
          region.rooms[9].links.se.con = ""
      region.rooms[9].exits = "southeast|northup"
      region.rooms[9].desc = "    这里已到了山脚下，此处近看，但见五座山峰峭兀突怒，确似五根手指竖立在半空之中。居中一峰尤见挺拔，笔立指天，耸入云表，下临深涧。山侧生着一片松林，松梢留雪，树身尽皆向南弯曲，想见北风极烈。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly tzf;sd;s;s;sd;sd;se"
      region.rooms[10].name = "黄土路"
      region.rooms[10].zone = "铁掌峰"
      region.rooms[10].id = 2228
      region.rooms[10].links = {}
        region.rooms[10].links.nw = {}
          region.rooms[10].links.nw.to = 2227
          region.rooms[10].links.nw.con = ""
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 2229
          region.rooms[10].links.e.con = ""
      region.rooms[10].exits = "east|northwest"
      region.rooms[10].desc = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly tzf;sd;s;s;sd;sd;se;e"
      region.rooms[11].name = "黄土路"
      region.rooms[11].zone = "铁掌峰"
      region.rooms[11].id = 2229
      region.rooms[11].links = {}
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 2228
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.ne = {}
          region.rooms[11].links.ne.to = 2230
          region.rooms[11].links.ne.con = ""
      region.rooms[11].exits = "northeast|west"
      region.rooms[11].desc = "    你走在一条尘土飞扬的黄土路上，两旁是阴森森的树林。这里是川湘交界，据说经常有土匪出没，不可久留。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly tzf;sd;s;s;sd;sd;se;e;ne"
      region.rooms[12].name = "黄土路"
      region.rooms[12].zone = "铁掌峰"
      region.rooms[12].id = 2230
      region.rooms[12].links = {}
        region.rooms[12].links.ne = {}
          region.rooms[12].links.ne.to = 2231
          region.rooms[12].links.ne.con = ""
        region.rooms[12].links.sw = {}
          region.rooms[12].links.sw.to = 2229
          region.rooms[12].links.sw.con = ""
      region.rooms[12].exits = "northeast|southwest"
      region.rooms[12].desc = "    你走在一条尘土飞扬的黄土路上，两旁是阴森森的树林。这里是川湘交界，据说经常有土匪出没，不可久留。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly tzf;sd;s;s;sd;sd;se;e;ne;ne"
      region.rooms[13].name = "泸溪"
      region.rooms[13].zone = "铁掌峰"
      region.rooms[13].id = 2231
      region.rooms[13].links = {}
        region.rooms[13].links.sw = {}
          region.rooms[13].links.sw.to = 2230
          region.rooms[13].links.sw.con = ""
        region.rooms[13].links.w = {}
          region.rooms[13].links.w.to = 2232
          region.rooms[13].links.w.con = ""
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 2235
          region.rooms[13].links.n.con = ""
      region.rooms[13].exits = "north|west|southwest"
      region.rooms[13].desc = "    这里是湘西的一个小镇。虽然地处偏僻，但这里来往的行人仍然很多。西面是一间供人休息打尖的小客店。西南方四十里处，就是此处有名的猴爪山。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly tzf;sd;s;s;sd;sd;se;e;ne;ne;w"
      region.rooms[14].name = "客店"
      region.rooms[14].zone = "铁掌峰"
      region.rooms[14].id = 2232
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 2231
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.u = {}
          region.rooms[14].links.u.to = 2233
          region.rooms[14].links.u.con = ""
      region.rooms[14].exits = "up|east"
      region.rooms[14].desc = "    这是一家价钱低廉的客栈，生意非常兴隆。外地游客多选择这里落脚，你可以在这里打听到各地的风土人情。店小二里里外外忙得团团转，接待着南腔北调的客人。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly tzf;sd;s;s;sd;sd;se;e;ne;ne;w;u"
      region.rooms[15].name = "客店二楼"
      region.rooms[15].zone = "铁掌峰"
      region.rooms[15].id = 2233
      region.rooms[15].links = {}
        region.rooms[15].links.enter = {}
          region.rooms[15].links.enter.to = 2234
          region.rooms[15].links.enter.con = ""
        region.rooms[15].links.d = {}
          region.rooms[15].links.d.to = 2232
          region.rooms[15].links.d.con = ""
      region.rooms[15].exits = "enter|down"
      region.rooms[15].desc = "    你正走在客店二楼的走廊上，可以听到从客房里不时地呼呼的打酣声，一阵高过一阵。不时有睡意朦胧的旅客进进出出，到楼下的掌柜处付了钱再上来睡觉。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly tzf;sd;s;s;sd;sd;se;e;ne;ne;w;u;enter"
      region.rooms[16].name = "客店二楼"
      region.rooms[16].zone = "铁掌峰"
      region.rooms[16].id = 2234
      region.rooms[16].links = {}
        region.rooms[16].links.out = {}
          region.rooms[16].links.out.to = 2233
          region.rooms[16].links.out.con = ""
      region.rooms[16].exits = "out"
      region.rooms[16].desc = "    这是一间很大的客房，陈设十分简陋。靠墙放了十几张小木床，不少客人正和衣而卧，满屋子都是呼呼的打酣声。西边有张床是空的，你蹑手蹑脚地走了过去。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly tzf;sd;s;s;sd;sd;se;e;ne;ne;n"
      region.rooms[17].name = "道路"
      region.rooms[17].zone = "铁掌峰"
      region.rooms[17].id = 2235
      region.rooms[17].links = {}
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 2231
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.ne = {}
          region.rooms[17].links.ne.to = 778
          region.rooms[17].links.ne.con = ""
      region.rooms[17].exits = "south|northeast"
      region.rooms[17].desc = "    你走在湘鄂交界的道路上，偶尔会有人骑着马匆匆而过。这里已经是湖南地界，往东北进入湖北境内。南边是一个小镇。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly tzf;e"
      region.rooms[18].name = "走廊"
      region.rooms[18].zone = "铁掌峰"
      region.rooms[18].id = 2236
      region.rooms[18].links = {}
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 2238
          region.rooms[18].links.e.con = ""
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 2219
          region.rooms[18].links.w.con = ""
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 2237
          region.rooms[18].links.n.con = ""
      region.rooms[18].exits = "east|north|west"
      region.rooms[18].desc = "    你走在一条走廊上。北面的屋内传来阵阵金属的声音。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly tzf;e;n"
      region.rooms[19].name = "兵器室"
      region.rooms[19].zone = "铁掌峰"
      region.rooms[19].id = 2237
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 2236
          region.rooms[19].links.s.con = ""
      region.rooms[19].exits = "south"
      region.rooms[19].desc = "    铁掌帮虽是以掌法、轻功著称，但帮中仍存有大量的兵器。以供武功不够的帮众使用。屋内两侧排列的都是兵器架，上面刀、枪、剑、戟、斧、钺、钩、叉应有尽有。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly tzf;e;e"
      region.rooms[20].name = "走廊"
      region.rooms[20].zone = "铁掌峰"
      region.rooms[20].id = 2238
      region.rooms[20].links = {}
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 2236
          region.rooms[20].links.w.con = ""
      region.rooms[20].exits = "west"
      region.rooms[20].desc = "    你走在一条走廊上。北面似乎有个黑暗的小屋，还隐隐传来一些酣声。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly tzf;w"
      region.rooms[21].name = "走廊"
      region.rooms[21].zone = "铁掌峰"
      region.rooms[21].id = 2239
      region.rooms[21].links = {}
        region.rooms[21].links.e = {}
          region.rooms[21].links.e.to = 2219
          region.rooms[21].links.e.con = ""
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 2241
          region.rooms[21].links.w.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 2240
          region.rooms[21].links.n.con = ""
      region.rooms[21].exits = "north|east|west"
      region.rooms[21].desc = "    你走在一条走廊上，北面似乎有翻书的哗哗声。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly tzf;w;n"
      region.rooms[22].name = "铁掌书屋"
      region.rooms[22].zone = "铁掌峰"
      region.rooms[22].id = 2240
      region.rooms[22].links = {}
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 2239
          region.rooms[22].links.s.con = ""
      region.rooms[22].exits = "south"
      region.rooms[22].desc = "    这里是铁掌帮放基本武学秘籍的地方，靠墙是一排书架，里面堆着铁掌帮历代搜刮的书。最近有人上山找茬，所以很少有人会来书房看书，书架上堆满了灰尘。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly tzf;w;w"
      region.rooms[23].name = "走廊"
      region.rooms[23].zone = "铁掌峰"
      region.rooms[23].id = 2241
      region.rooms[23].links = {}
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 2239
          region.rooms[23].links.e.con = ""
        region.rooms[23].links.n = {}
          region.rooms[23].links.n.to = 2242
          region.rooms[23].links.n.con = ""
      region.rooms[23].exits = "east|north"
      region.rooms[23].desc = "    你走在一条走廊上。北面传来阵阵饭菜的香味。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly tzf;w;w;n"
      region.rooms[24].name = "厨房"
      region.rooms[24].zone = "铁掌峰"
      region.rooms[24].id = 2242
      region.rooms[24].links = {}
        region.rooms[24].links.s = {}
          region.rooms[24].links.s.to = 2241
          region.rooms[24].links.s.con = ""
      region.rooms[24].exits = "south"
      region.rooms[24].desc = "    这里是铁掌帮的厨房。正面是一个大炉灶，几乎占去了一半的房间。灶上留有很多火眼，可同时做很多种菜。几位帮中高薪聘来的厨子正在 来回忙碌着。整间屋内弥漫着各种饭菜的香味，闻了让人垂涎欲滴。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly tzf;n"
      region.rooms[25].name = "后厢房"
      region.rooms[25].zone = "铁掌峰"
      region.rooms[25].id = 2243
      region.rooms[25].links = {}
        region.rooms[25].links.s = {}
          region.rooms[25].links.s.to = 2219
          region.rooms[25].links.s.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 2244
          region.rooms[25].links.n.con = ""
      region.rooms[25].exits = "south|north"
      region.rooms[25].desc = "    这是大厅后面的一个小房间，虽然也是岩石砌成，但布置的非常舒适。四壁用挂毯遮住，不露一点石壁的痕迹。屋内转圈摆放了一些椅子，上面铺着厚厚的软垫，坐上去一定很舒适。这里是帮主处理帮中日常事务的 地方。后面通向后花院。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly tzf;n;n"
      region.rooms[26].name = "后花园"
      region.rooms[26].zone = "铁掌峰"
      region.rooms[26].id = 2244
      region.rooms[26].links = {}
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 2245
          region.rooms[26].links.e.con = ""
        region.rooms[26].links.w = {}
          region.rooms[26].links.w.to = 2246
          region.rooms[26].links.w.con = ""
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 2243
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.n = {}
          region.rooms[26].links.n.to = 2247
          region.rooms[26].links.n.con = ""
      region.rooms[26].exits = "south|east|north|west"
      region.rooms[26].desc = "    这是一处环境优雅的花园。只见乔松修竹，苍翠蔽天，层峦奇岫  ，静窈幽深。西面有一座假山，东面是大片的花圃。北面是通往山上的路。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly tzf;n;n;e"
      region.rooms[27].name = "花圃"
      region.rooms[27].zone = "铁掌峰"
      region.rooms[27].id = 2245
      region.rooms[27].links = {}
        region.rooms[27].links.w = {}
          region.rooms[27].links.w.to = 2244
          region.rooms[27].links.w.con = ""
      region.rooms[27].exits = "west"
      region.rooms[27].desc = "    只见这里摆满了茉莉、素馨、麝香藤、朱槿、玉桂、红蕉，都是 夏日盛开的香花。院墙上又挂了枷木兰、真腊龙诞等香珠，但觉馨意袭人， 清芬满园。园中桌上放着几盆新藕、甜瓜、枇杷、等鲜果，椅子上丢着一把 蒲扇，看来是帮主休息的地方。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly tzf;n;n;w"
      region.rooms[28].name = "假山"
      region.rooms[28].zone = "铁掌峰"
      region.rooms[28].id = 2246
      region.rooms[28].links = {}
        region.rooms[28].links.e = {}
          region.rooms[28].links.e.to = 2244
          region.rooms[28].links.e.con = ""
      region.rooms[28].exits = "east"
      region.rooms[28].desc = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly tzf;n;n;n"
      region.rooms[29].name = "山路"
      region.rooms[29].zone = "铁掌峰"
      region.rooms[29].id = 2247
      region.rooms[29].links = {}
        region.rooms[29].links.s = {}
          region.rooms[29].links.s.to = 2244
          region.rooms[29].links.s.con = ""
        region.rooms[29].links.nu = {}
          region.rooms[29].links.nu.to = 2248
          region.rooms[29].links.nu.con = ""
      region.rooms[29].exits = "south|northup"
      region.rooms[29].desc = "    你走在一条崎岖的山路上，道旁山峰壁立，长草过腰，中间一条羊肠小路，仅容一人勉强过去。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly tzf;n;n;n;nu"
      region.rooms[30].name = "山路"
      region.rooms[30].zone = "铁掌峰"
      region.rooms[30].id = 2248
      region.rooms[30].links = {}
        region.rooms[30].links.sd = {}
          region.rooms[30].links.sd.to = 2247
          region.rooms[30].links.sd.con = ""
        region.rooms[30].links.nu = {}
          region.rooms[30].links.nu.to = 2249
          region.rooms[30].links.nu.con = ""
      region.rooms[30].exits = "northup|southdown"
      region.rooms[30].desc = "    你走在一条崎岖的山路上，道旁山峰壁立，长草过腰，中间一条羊肠小路，仅容一人勉强过去。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly tzf;n;n;n;nu;nu"
      region.rooms[31].name = "山间平台"
      region.rooms[31].zone = "铁掌峰"
      region.rooms[31].id = 2249
      region.rooms[31].links = {}
        region.rooms[31].links.ne = {}
          region.rooms[31].links.ne.to = 2258
          region.rooms[31].links.ne.con = ""
        region.rooms[31].links.sd = {}
          region.rooms[31].links.sd.to = 2248
          region.rooms[31].links.sd.con = ""
        region.rooms[31].links.wu = {}
          region.rooms[31].links.wu.to = 2250
          region.rooms[31].links.wu.con = ""
        region.rooms[31].links.nu = {}
          region.rooms[31].links.nu.to = 2261
          region.rooms[31].links.nu.con = ""
        region.rooms[31].links.eu = {}
          region.rooms[31].links.eu.to = 2254
          region.rooms[31].links.eu.con = ""
        region.rooms[31].links.nw = {}
          region.rooms[31].links.nw.to = 2276
          region.rooms[31].links.nw.con = ""
      region.rooms[31].exits = "eastup|northup|southdown|westup|northwest|northeast"
      region.rooms[31].desc = "    这里是山间的一块平地。山势在这里开始分支，矗立在面前的有五座高耸入云的山峰，行似人的五指，“铁掌山”之名由此而得。五峰虽同处此山，但拇指峰之雄伟，食指峰之险峻，中指峰之高耸，无名峰之奇丽，小指峰之秀美，则各有特色，各擅胜场。在平台一侧的大石上，刻着一副地图(ditu)。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly tzf;n;n;n;nu;nu;wu"
      region.rooms[32].name = "石板路"
      region.rooms[32].zone = "铁掌峰"
      region.rooms[32].id = 2250
      region.rooms[32].links = {}
        region.rooms[32].links.ed = {}
          region.rooms[32].links.ed.to = 2249
          region.rooms[32].links.ed.con = ""
        region.rooms[32].links.wu = {}
          region.rooms[32].links.wu.to = 2251
          region.rooms[32].links.wu.con = ""
      region.rooms[32].exits = "westup|eastdown"
      region.rooms[32].desc = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly tzf;n;n;n;nu;nu;wu;wu"
      region.rooms[33].name = "石板路"
      region.rooms[33].zone = "铁掌峰"
      region.rooms[33].id = 2251
      region.rooms[33].links = {}
        region.rooms[33].links.ed = {}
          region.rooms[33].links.ed.to = 2250
          region.rooms[33].links.ed.con = ""
        region.rooms[33].links.wu = {}
          region.rooms[33].links.wu.to = 2252
          region.rooms[33].links.wu.con = ""
      region.rooms[33].exits = "westup|eastdown"
      region.rooms[33].desc = "    你走在一条石板铺成的小路上，两旁是高大的垂柳，虽在骄阳似 火的夏日，依旧凉爽怡人。因为小指峰风光秀美，游人较多，因此这里的路 也修砌的很好。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly tzf;n;n;n;nu;nu;wu;wu;wu"
      region.rooms[34].name = "瀑布"
      region.rooms[34].zone = "铁掌峰"
      region.rooms[34].id = 2252
      region.rooms[34].links = {}
        region.rooms[34].links.ed = {}
          region.rooms[34].links.ed.to = 2251
          region.rooms[34].links.ed.con = ""
        region.rooms[34].links.nu = {}
          region.rooms[34].links.nu.to = 2253
          region.rooms[34].links.nu.con = ""
      region.rooms[34].exits = "eastdown|northup"
      region.rooms[34].desc = "    山路行到这里，忽听远处传来隐隐水声，转过一道山梁，只见一 道白龙似的大瀑布从对面双峰之间奔腾而下，空山寂寂，那水声在山谷中激 荡回想，声势甚是惊人。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly tzf;n;n;n;nu;nu;wu;wu;wu;nu"
      region.rooms[35].name = "小指峰"
      region.rooms[35].zone = "铁掌峰"
      region.rooms[35].id = 2253
      region.rooms[35].links = {}
        region.rooms[35].links.sd = {}
          region.rooms[35].links.sd.to = 2252
          region.rooms[35].links.sd.con = ""
      region.rooms[35].exits = "southdown"
      region.rooms[35].desc = "    你已登上了小指峰的峰顶。纵目远眺，但见远处四峰已淹没在浓 浓的迷雾之中。这里的高度恰在云雾之中，你只能看清身前几米的景物。渐渐的，你的衣服已被水气沁湿，凉风袭来，冻得你瑟瑟发抖。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly tzf;n;n;n;nu;nu;eu"
      region.rooms[36].name = "碎石路"
      region.rooms[36].zone = "铁掌峰"
      region.rooms[36].id = 2254
      region.rooms[36].links = {}
        region.rooms[36].links.wd = {}
          region.rooms[36].links.wd.to = 2249
          region.rooms[36].links.wd.con = ""
        region.rooms[36].links.eu = {}
          region.rooms[36].links.eu.to = 2255
          region.rooms[36].links.eu.con = ""
      region.rooms[36].exits = "eastup|westdown"
      region.rooms[36].desc = "    你走在一条用碎石铺成的小路上。两旁山势低缓，长满了翠绿的毛竹，阵阵微风吹过，耳旁便响起一片沙沙声。"
    region.rooms[37] = {}
      region.rooms[37].path = "fly tzf;n;n;n;nu;nu;eu;eu"
      region.rooms[37].name = "碎石路"
      region.rooms[37].zone = "铁掌峰"
      region.rooms[37].id = 2255
      region.rooms[37].links = {}
        region.rooms[37].links.wd = {}
          region.rooms[37].links.wd.to = 2254
          region.rooms[37].links.wd.con = ""
        region.rooms[37].links.eu = {}
          region.rooms[37].links.eu.to = 2256
          region.rooms[37].links.eu.con = ""
      region.rooms[37].exits = "eastup|westdown"
      region.rooms[37].desc = "    你走在一条用碎石铺成的小路上。两旁山势低缓，长满了翠绿的毛竹，阵阵微风吹过，耳旁便响起一片沙沙声。"
    region.rooms[38] = {}
      region.rooms[38].path = "fly tzf;n;n;n;nu;nu;eu;eu;eu"
      region.rooms[38].name = "碎石路"
      region.rooms[38].zone = "铁掌峰"
      region.rooms[38].id = 2256
      region.rooms[38].links = {}
        region.rooms[38].links.wd = {}
          region.rooms[38].links.wd.to = 2255
          region.rooms[38].links.wd.con = ""
        region.rooms[38].links.nu = {}
          region.rooms[38].links.nu.to = 2257
          region.rooms[38].links.nu.con = ""
      region.rooms[38].exits = "northup|westdown"
      region.rooms[38].desc = "    你走在一条用碎石铺成的小路上。两旁山势低缓，长满了翠绿的毛竹，阵阵微风吹过，耳旁便响起一片沙沙声。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly tzf;n;n;n;nu;nu;eu;eu;eu;nu"
      region.rooms[39].name = "拇指峰"
      region.rooms[39].zone = "铁掌峰"
      region.rooms[39].id = 2257
      region.rooms[39].links = {}
        region.rooms[39].links.sd = {}
          region.rooms[39].links.sd.to = 2256
          region.rooms[39].links.sd.con = ""
      region.rooms[39].exits = "southdown"
      region.rooms[39].desc = "    拇指峰是铁掌五峰中最为低矮的一峰，名为峰，实则只是一座较高的石山罢了。峰顶到处是又大又圆的岩石，在日晒雨淋下，被风蚀得十分光滑。在岩石的缝隙中，长出许多松树，其中一棵尤其引人注目。这棵松名为--并蒂松(song)，乃同根而生，于距地一米高处，忽分为二。这两根树干同粗同高，均长得高大挺拔，枝叶茂盛，尤如兄弟一般，因此又名--兄弟松。"
    region.rooms[40] = {}
      region.rooms[40].path = "fly tzf;n;n;n;nu;nu;ne"
      region.rooms[40].name = "山谷"
      region.rooms[40].zone = "铁掌峰"
      region.rooms[40].id = 2258
      region.rooms[40].links = {}
        region.rooms[40].links.ne = {}
          region.rooms[40].links.ne.to = 2259
          region.rooms[40].links.ne.con = ""
        region.rooms[40].links.sw = {}
          region.rooms[40].links.sw.to = 2249
          region.rooms[40].links.sw.con = ""
      region.rooms[40].exits = "northeast|southwest"
      region.rooms[40].desc = "    你走在一条狭窄的山谷之中，两旁山峰壁立，直插云霄。鸟鸣猿 啼之声，回荡在寂静的空谷之中。"
    region.rooms[41] = {}
      region.rooms[41].path = "fly tzf;n;n;n;nu;nu;ne;ne"
      region.rooms[41].name = "山谷"
      region.rooms[41].zone = "铁掌峰"
      region.rooms[41].id = 2259
      region.rooms[41].links = {}
        region.rooms[41].links.ne = {}
          region.rooms[41].links.ne.to = 2260
          region.rooms[41].links.ne.con = ""
        region.rooms[41].links.sw = {}
          region.rooms[41].links.sw.to = 2258
          region.rooms[41].links.sw.con = ""
      region.rooms[41].exits = "northeast|southwest"
      region.rooms[41].desc = "    你走在一条狭窄的山谷之中，两旁山峰壁立，直插云霄。鸟鸣猿 啼之声，回荡在寂静的空谷之中。"
    region.rooms[42] = {}
      region.rooms[42].path = "fly tzf;n;n;n;nu;nu;ne;ne;ne"
      region.rooms[42].name = "绝壁"
      region.rooms[42].zone = "铁掌峰"
      region.rooms[42].id = 2260
      region.rooms[42].links = {}
        region.rooms[42].links.sw = {}
          region.rooms[42].links.sw.to = 2259
          region.rooms[42].links.sw.con = ""
      region.rooms[42].exits = "southwest"
      region.rooms[42].desc = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly tzf;n;n;n;nu;nu;nu"
      region.rooms[43].name = "山路"
      region.rooms[43].zone = "铁掌峰"
      region.rooms[43].id = 2261
      region.rooms[43].links = {}
        region.rooms[43].links.sd = {}
          region.rooms[43].links.sd.to = 2249
          region.rooms[43].links.sd.con = ""
        region.rooms[43].links.nu = {}
          region.rooms[43].links.nu.to = 2262
          region.rooms[43].links.nu.con = ""
      region.rooms[43].exits = "northup|southdown"
      region.rooms[43].desc = "    你走在一条崎岖的山路上，道旁山峰壁立，长草过腰，中间一条羊肠小路，仅容一人勉强过去。"
    region.rooms[44] = {}
      region.rooms[44].path = "fly tzf;n;n;n;nu;nu;nu;nu"
      region.rooms[44].name = "山路"
      region.rooms[44].zone = "铁掌峰"
      region.rooms[44].id = 2262
      region.rooms[44].links = {}
        region.rooms[44].links.sd = {}
          region.rooms[44].links.sd.to = 2261
          region.rooms[44].links.sd.con = ""
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 2263
          region.rooms[44].links.n.con = ""
      region.rooms[44].exits = "north|southdown"
      region.rooms[44].desc = "    你走在一条崎岖的山路上，道旁山峰壁立，长草过腰，中间一条羊肠小路，仅容一人勉强过去。前面有一片茂密的松林。路旁的石壁上刻着几个大字(dazi)。"
    region.rooms[45] = {}
      region.rooms[45].path = "fly tzf;n;n;n;nu;nu;nu;nu;n"
      region.rooms[45].name = "松树林"
      region.rooms[45].zone = "铁掌峰"
      region.rooms[45].id = 2263
      region.rooms[45].links = {}
        region.rooms[45].links.e = {}
          region.rooms[45].links.e.to = 2264
          region.rooms[45].links.e.con = ""
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 2262
          region.rooms[45].links.s.con = ""
        region.rooms[45].links.w = {}
          region.rooms[45].links.w.to = 2263
          region.rooms[45].links.w.con = ""
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 2263
          region.rooms[45].links.n.con = ""
      region.rooms[45].exits = "south|north|east|west"
      region.rooms[45].desc = "    你走进一片黑压压的松树林，这里的松树枝繁叶茂，树冠相叠，遮天蔽日。几素阳光从树梢间照射下来，在淡淡的雾气中，形成条条白色的光柱，煞是好看。你走着走着，忽然发现自己已迷失在这片松林中，找不到出去的路了。"
    region.rooms[46] = {}
      region.rooms[46].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e"
      region.rooms[46].name = "松树林"
      region.rooms[46].zone = "铁掌峰"
      region.rooms[46].id = 2264
      region.rooms[46].links = {}
        region.rooms[46].links.e = {}
          region.rooms[46].links.e.to = 2264
          region.rooms[46].links.e.con = ""
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 2264
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.w = {}
          region.rooms[46].links.w.to = 2263
          region.rooms[46].links.w.con = ""
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 2265
          region.rooms[46].links.n.con = ""
      region.rooms[46].exits = "south|east|north|west"
      region.rooms[46].desc = "    你走进一片黑压压的松树林，这里的松树枝繁叶茂，树冠相叠，遮天蔽日。几素阳光从树梢间照射下来，在淡淡的雾气中，形成条条白色的光柱，煞是好看。你走着走着，忽然发现自己已迷失在这片松林中，找不到出去的路了。"
    region.rooms[47] = {}
      region.rooms[47].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n"
      region.rooms[47].name = "松树林"
      region.rooms[47].zone = "铁掌峰"
      region.rooms[47].id = 2265
      region.rooms[47].links = {}
        region.rooms[47].links.e = {}
          region.rooms[47].links.e.to = 2265
          region.rooms[47].links.e.con = ""
        region.rooms[47].links.w = {}
          region.rooms[47].links.w.to = 2266
          region.rooms[47].links.w.con = ""
        region.rooms[47].links.s = {}
          region.rooms[47].links.s.to = 2264
          region.rooms[47].links.s.con = ""
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 2265
          region.rooms[47].links.n.con = ""
      region.rooms[47].exits = "south|north|east|west"
      region.rooms[47].desc = "    你走进一片黑压压的松树林，这里的松树枝繁叶茂，树冠相叠，遮天蔽日。几素阳光从树梢间照射下来，在淡淡的雾气中，形成条条白色的光柱，煞是好看。你走着走着，忽然发现自己已迷失在这片松林中，找不到出去的路了。"
    region.rooms[48] = {}
      region.rooms[48].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w"
      region.rooms[48].name = "松树林"
      region.rooms[48].zone = "铁掌峰"
      region.rooms[48].id = 2266
      region.rooms[48].links = {}
        region.rooms[48].links.e = {}
          region.rooms[48].links.e.to = 2265
          region.rooms[48].links.e.con = ""
        region.rooms[48].links.w = {}
          region.rooms[48].links.w.to = 2266
          region.rooms[48].links.w.con = ""
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 2266
          region.rooms[48].links.s.con = ""
        region.rooms[48].links.n = {}
          region.rooms[48].links.n.to = 2267
          region.rooms[48].links.n.con = ""
      region.rooms[48].exits = "south|east|north|west"
      region.rooms[48].desc = "    你走进一片黑压压的松树林，这里的松树枝繁叶茂，树冠相叠，遮天蔽日。几素阳光从树梢间照射下来，在淡淡的雾气中，形成条条白色的光柱，煞是好看。你走着走着，忽然发现自己已迷失在这片松林中，找不到出去的路了。"
    region.rooms[49] = {}
      region.rooms[49].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n"
      region.rooms[49].name = "松树林"
      region.rooms[49].zone = "铁掌峰"
      region.rooms[49].id = 2267
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 2267
          region.rooms[49].links.e.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 2266
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 2267
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.n = {}
          region.rooms[49].links.n.to = 2268
          region.rooms[49].links.n.con = ""
      region.rooms[49].exits = "south|north|east|west"
      region.rooms[49].desc = "    你走进一片黑压压的松树林，这里的松树枝繁叶茂，树冠相叠，遮天蔽日。几素阳光从树梢间照射下来，在淡淡的雾气中，形成条条白色的光柱，煞是好看。你走着走着，忽然发现自己已迷失在这片松林中，找不到出去的路了。"
    region.rooms[50] = {}
      region.rooms[50].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n;n"
      region.rooms[50].name = "第二指节"
      region.rooms[50].zone = "铁掌峰"
      region.rooms[50].id = 2268
      region.rooms[50].links = {}
        region.rooms[50].links.nu = {}
          region.rooms[50].links.nu.to = 2269
          region.rooms[50].links.nu.con = ""
        region.rooms[50].links.s = {}
          region.rooms[50].links.s.to = 2267
          region.rooms[50].links.s.con = ""
        region.rooms[50].links.enter = {}
          region.rooms[50].links.enter.to = 2272
          region.rooms[50].links.enter.con = ""
      region.rooms[50].exits = "south|enter|northup"
      region.rooms[50].desc = "    这里已到了中指峰的半山腰了，由于铁掌山排列得象手指一样， 每座山峰又分三截，就如手指的指节一般，因此这里正是位于第二指节的位置。这里离峰顶已近，透过淡淡的云雾，似已可以看到山路的尽头了。左前方二十于丈处，黑黝黝的似有一个洞穴(dong)，洞口砌以玉石，修建得极是齐整。"
    region.rooms[51] = {}
      region.rooms[51].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n;n;nu"
      region.rooms[51].name = "山路"
      region.rooms[51].zone = "铁掌峰"
      region.rooms[51].id = 2269
      region.rooms[51].links = {}
        region.rooms[51].links.sd = {}
          region.rooms[51].links.sd.to = 2268
          region.rooms[51].links.sd.con = ""
        region.rooms[51].links.nu = {}
          region.rooms[51].links.nu.to = 2270
          region.rooms[51].links.nu.con = ""
      region.rooms[51].exits = "northup|southdown"
      region.rooms[51].desc = "    你走在一条崎岖的山路上，道旁山峰壁立，长草过腰，中间一条羊肠小路，仅容一人勉强过去。"
    region.rooms[52] = {}
      region.rooms[52].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n;n;nu;nu"
      region.rooms[52].name = "山路"
      region.rooms[52].zone = "铁掌峰"
      region.rooms[52].id = 2270
      region.rooms[52].links = {}
        region.rooms[52].links.sd = {}
          region.rooms[52].links.sd.to = 2269
          region.rooms[52].links.sd.con = ""
        region.rooms[52].links.nu = {}
          region.rooms[52].links.nu.to = 2271
          region.rooms[52].links.nu.con = ""
      region.rooms[52].exits = "northup|southdown"
      region.rooms[52].desc = "    你走在一条崎岖的山路上，道旁山峰壁立，长草过腰，中间一条羊肠小路，仅容一人勉强过去。"
    region.rooms[53] = {}
      region.rooms[53].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n;n;nu;nu;nu"
      region.rooms[53].name = "中指峰"
      region.rooms[53].zone = "铁掌峰"
      region.rooms[53].id = 2271
      region.rooms[53].links = {}
        region.rooms[53].links.sd = {}
          region.rooms[53].links.sd.to = 2270
          region.rooms[53].links.sd.con = ""
      region.rooms[53].exits = "southdown"
      region.rooms[53].desc = "    这里就是铁掌山的最高峰--中指峰。由于山势太高，峰顶仍存有大量的积雪，白雪皑皑，在阳光的照射下，泛起一片耀眼的银光。纵目远眺，湘西几百里景色尽收眼底，泸溪，辰溪如两条玉带，从山下缓缓流过。远处那条白色的亮线，就是湘西的大江--沅江。"
    region.rooms[54] = {}
      region.rooms[54].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n;n;enter"
      region.rooms[54].name = "山洞"
      region.rooms[54].zone = "铁掌峰"
      region.rooms[54].id = 2272
      region.rooms[54].links = {}
        region.rooms[54].links.enter = {}
          region.rooms[54].links.enter.to = 2273
          region.rooms[54].links.enter.con = ""
        region.rooms[54].links.out = {}
          region.rooms[54].links.out.to = 2268
          region.rooms[54].links.out.con = ""
      region.rooms[54].exits = "enter|out"
      region.rooms[54].desc = "    一个黑漆漆的山洞，黑沉沉的一眼望不到底。两侧的石壁上生满的苔藓，摸起来又湿又滑。这石洞似乎是人工开凿的，从四周的石壁上仍能看出斧凿的痕迹。你站在这里，一股恐惧由然而生，似乎身体随时都会被这片黑暗吞噬掉。"
    region.rooms[55] = {}
      region.rooms[55].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n;n;enter;enter"
      region.rooms[55].name = "山洞"
      region.rooms[55].zone = "铁掌峰"
      region.rooms[55].id = 2273
      region.rooms[55].links = {}
        region.rooms[55].links.enter = {}
          region.rooms[55].links.enter.to = 2274
          region.rooms[55].links.enter.con = ""
        region.rooms[55].links.out = {}
          region.rooms[55].links.out.to = 2272
          region.rooms[55].links.out.con = ""
      region.rooms[55].exits = "enter|out"
      region.rooms[55].desc = "    一个黑漆漆的山洞，黑沉沉的一眼望不到底。两侧的石壁上生满的苔藓，摸起来又湿又滑。这石洞似乎是人工开凿的，从四周的石壁上仍能看出斧凿的痕迹。你站在这里，一股恐惧由然而生，似乎身体随时都会被这片黑暗吞噬掉。"
    region.rooms[56] = {}
      region.rooms[56].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n;n;enter;enter;enter"
      region.rooms[56].name = "山洞"
      region.rooms[56].zone = "铁掌峰"
      region.rooms[56].id = 2274
      region.rooms[56].links = {}
        region.rooms[56].links.enter = {}
          region.rooms[56].links.enter.to = 2275
          region.rooms[56].links.enter.con = ""
        region.rooms[56].links.out = {}
          region.rooms[56].links.out.to = 2273
          region.rooms[56].links.out.con = ""
      region.rooms[56].exits = "enter|out"
      region.rooms[56].desc = "    一个黑漆漆的山洞，黑沉沉的一眼望不到底。两侧的石壁上生满的苔藓，摸起来又湿又滑。这石洞似乎是人工开凿的，从四周的石壁上仍能看出斧凿的痕迹。你站在这里，一股恐惧由然而生，似乎身体随时都会被这片黑暗吞噬掉。"
    region.rooms[57] = {}
      region.rooms[57].path = "fly tzf;n;n;n;nu;nu;nu;nu;n;e;n;w;n;n;enter;enter;enter;enter"
      region.rooms[57].name = "天然洞穴"
      region.rooms[57].zone = "铁掌峰"
      region.rooms[57].id = 2275
      region.rooms[57].links = {}
        region.rooms[57].links.out = {}
          region.rooms[57].links.out.to = 2274
          region.rooms[57].links.out.con = ""
      region.rooms[57].exits = "out"
      region.rooms[57].desc = "    这石洞系天然生成，较之外面人工开凿的石室大了十来倍。放眼望去，洞内共有十余具骸骨，或做或卧，神态各有不同，有的骸骨散开在地，有的却仍具完好人形，更有些骨坛灵位之属。每具骸骨之旁都放着兵刃，暗器，用具，珍宝等物。洞口处立着一座石碑(bei)。"
    region.rooms[58] = {}
      region.rooms[58].path = "fly tzf;n;n;n;nu;nu;nw"
      region.rooms[58].name = "荒草路"
      region.rooms[58].zone = "铁掌峰"
      region.rooms[58].id = 2276
      region.rooms[58].links = {}
        region.rooms[58].links.nw = {}
          region.rooms[58].links.nw.to = 2277
          region.rooms[58].links.nw.con = ""
        region.rooms[58].links.se = {}
          region.rooms[58].links.se.to = 2249
          region.rooms[58].links.se.con = ""
      region.rooms[58].exits = "northwest|southeast"
      region.rooms[58].desc = "    你走一条荒芜的小路上，两旁荒草齐膝，荆棘遍地，似乎罕有人 至。山石壁立，遮天蔽日，鸟兽全无，四周笼罩在一片阴暗之中，使这里看起来格外深隧幽静。"
    region.rooms[59] = {}
      region.rooms[59].path = "fly tzf;n;n;n;nu;nu;nw;nw"
      region.rooms[59].name = "荒草路"
      region.rooms[59].zone = "铁掌峰"
      region.rooms[59].id = 2277
      region.rooms[59].links = {}
        region.rooms[59].links.nw = {}
          region.rooms[59].links.nw.to = 2278
          region.rooms[59].links.nw.con = ""
        region.rooms[59].links.se = {}
          region.rooms[59].links.se.to = 2276
          region.rooms[59].links.se.con = ""
      region.rooms[59].exits = "northwest|southeast"
      region.rooms[59].desc = "    你走一条荒芜的小路上，两旁荒草齐膝，荆棘遍地，似乎罕有人至。山石壁立，遮天蔽日，鸟兽全无，四周笼罩在一片阴暗之中，使这里看起来格外深隧幽静。"
    region.rooms[60] = {}
      region.rooms[60].path = "fly tzf;n;n;n;nu;nu;nw;nw;nw"
      region.rooms[60].name = "荒草路"
      region.rooms[60].zone = "铁掌峰"
      region.rooms[60].id = 2278
      region.rooms[60].links = {}
        region.rooms[60].links.nu = {}
          region.rooms[60].links.nu.to = 2279
          region.rooms[60].links.nu.con = ""
        region.rooms[60].links.se = {}
          region.rooms[60].links.se.to = 2277
          region.rooms[60].links.se.con = ""
      region.rooms[60].exits = "northup|southeast"
      region.rooms[60].desc = "    你走一条荒芜的小路上，两旁荒草齐膝，荆棘遍地，似乎罕有人 至。山石壁立，遮天蔽日，鸟兽全无，四周笼罩在一片阴暗之中，使这里看起来格外深隧幽静。"
    region.rooms[61] = {}
      region.rooms[61].path = "fly tzf;n;n;n;nu;nu;nw;nw;nw;nu"
      region.rooms[61].name = "荒草路"
      region.rooms[61].zone = "铁掌峰"
      region.rooms[61].id = 2279
      region.rooms[61].links = {}
        region.rooms[61].links.sd = {}
          region.rooms[61].links.sd.to = 2278
          region.rooms[61].links.sd.con = ""
        region.rooms[61].links.nu = {}
          region.rooms[61].links.nu.to = 2280
          region.rooms[61].links.nu.con = ""
      region.rooms[61].exits = "northup|southdown"
      region.rooms[61].desc = "    你走一条荒芜的小路上，两旁荒草齐膝，荆棘遍地，似乎罕有人 至。山石壁立，遮天蔽日，鸟兽全无，四周笼罩在一片阴暗之中，使这里看起来格外深隧幽静。"
    region.rooms[62] = {}
      region.rooms[62].path = "fly tzf;n;n;n;nu;nu;nw;nw;nw;nu;nu"
      region.rooms[62].name = "无名峰"
      region.rooms[62].zone = "铁掌峰"
      region.rooms[62].id = 2280
      region.rooms[62].links = {}
        region.rooms[62].links.sd = {}
          region.rooms[62].links.sd.to = 2279
          region.rooms[62].links.sd.con = ""
        region.rooms[62].links["move bei;enter"] = {}
          region.rooms[62].links["move bei;enter"].to = 2281
          region.rooms[62].links["move bei;enter"].con = ""
      region.rooms[62].exits = "southdown"
      region.rooms[62].desc = "    跨过路上的荆棘和荒草，你终于登上了无名峰的峰顶。由于这里 地处五峰之中，四周有其它山峰阻挡，因此风势很小，常年笼罩在一片云雾之中。峰顶长满了齐腰的荒草，怪石嶙峋，一片荒凉景色。在峰顶的正中，赫然矗立着一座岩石砌就的坟墓，坟墓的前面立着一块一人多高的花岗岩的 墓碑(bei)。"
    region.rooms[63] = {}
      region.rooms[63].path = "fly tzf;n;n;n;nu;nu;nw;nw;nw;nu;nu;move bei;enter"
      region.rooms[63].name = "石阶"
      region.rooms[63].zone = "铁掌峰"
      region.rooms[63].id = 2281
      region.rooms[63].links = {}
        region.rooms[63].links.ed = {}
          region.rooms[63].links.ed.to = 2282
          region.rooms[63].links.ed.con = ""
        region.rooms[63].links.out = {}
          region.rooms[63].links.out.to = 2280
          region.rooms[63].links.out.con = ""
      region.rooms[63].exits = "eastdown|out"
      region.rooms[63].desc = "    一排石阶盘旋而下，消失在浓浓的黑暗中。石阶上长满的绿色的 青苔，滑不留脚。远处黑暗的尽头似乎有点昏黄的光亮。"
    region.rooms[64] = {}
      region.rooms[64].path = "fly tzf;n;n;n;nu;nu;nw;nw;nw;nu;nu;move bei;enter;ed"
      region.rooms[64].name = "石阶"
      region.rooms[64].zone = "铁掌峰"
      region.rooms[64].id = 2282
      region.rooms[64].links = {}
        region.rooms[64].links.nd = {}
          region.rooms[64].links.nd.to = 2283
          region.rooms[64].links.nd.con = ""
        region.rooms[64].links.wu = {}
          region.rooms[64].links.wu.to = 2281
          region.rooms[64].links.wu.con = ""
      region.rooms[64].exits = "westup|northdown"
      region.rooms[64].desc = "    一排石阶盘旋而下，消失在浓浓的黑暗中。石阶上长满的绿色的 青苔，滑不留脚。远处黑暗的尽头似乎有点昏黄的光亮。"
    region.rooms[65] = {}
      region.rooms[65].path = "fly tzf;n;n;n;nu;nu;nw;nw;nw;nu;nu;move bei;enter;ed;nd"
      region.rooms[65].name = "石阶"
      region.rooms[65].zone = "铁掌峰"
      region.rooms[65].id = 2283
      region.rooms[65].links = {}
        region.rooms[65].links.wd = {}
          region.rooms[65].links.wd.to = 2284
          region.rooms[65].links.wd.con = ""
        region.rooms[65].links.su = {}
          region.rooms[65].links.su.to = 2282
          region.rooms[65].links.su.con = ""
      region.rooms[65].exits = "southup|westdown"
      region.rooms[65].desc = "    一排石阶盘旋而下，消失在浓浓的黑暗中。石阶上长满的绿色的 青苔，滑不留脚。远处黑暗的尽头似乎有点昏黄的光亮。"
    region.rooms[66] = {}
      region.rooms[66].path = "fly tzf;n;n;n;nu;nu;nw;nw;nw;nu;nu;move bei;enter;ed;nd;wd"
      region.rooms[66].name = "石室"
      region.rooms[66].zone = "铁掌峰"
      region.rooms[66].id = 2284
      region.rooms[66].links = {}
        region.rooms[66].links.eu = {}
          region.rooms[66].links.eu.to = 2283
          region.rooms[66].links.eu.con = ""
      region.rooms[66].exits = "eastup"
      region.rooms[66].desc = "    这是一间在山腹中凿成的小石屋，中间有一座石桌，桌上摆放着一盏油灯，散发出暗淡昏黄的光亮。屋内一角的地上，铺着很多干草，上面坐着一个人。长发垂下，遮去面容，看不出多大年纪，身上穿着一件又脏又破的黑衣，说不出的诡异神秘。"
  region.center = 2219
return region