local region = {}
  region.cmd = "fly wds"
  region.name = "武当山"
  region.id = "wds"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne;e;se;e;n;n"
      region.rooms[1].name = "青石大道"
      region.rooms[1].zone = "扬州|武当山|归云庄1"
      region.rooms[1].id = 65
      region.rooms[1].desc = "    你走在一条青石大道上，北边隐约可见到扬州城的城墙。此处往东南望去，可以看到一个市镇。"
      region.rooms[1].exits = "south|north|southeast"
      region.rooms[1].links = {}
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 64
          region.rooms[1].links.n.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 66
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.se = {}
          region.rooms[1].links.se.to = 2626
          region.rooms[1].links.se.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne;e;se;e;n"
      region.rooms[2].name = "青石大道"
      region.rooms[2].zone = "扬州|武当山"
      region.rooms[2].id = 66
      region.rooms[2].desc = "    你走在一条青石大道上，四周静悄悄的。"
      region.rooms[2].exits = "south|north"
      region.rooms[2].links = {}
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 462
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 65
          region.rooms[2].links.n.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne;e;se;e"
      region.rooms[3].name = "青石大道"
      region.rooms[3].zone = "衡阳|武当山"
      region.rooms[3].id = 462
      region.rooms[3].desc = "    你走在一条青石大道上，四周静悄悄的。西边是一条大道，东边是好大的一片树林。往南还有一条大道，掩映在密密的树林中。"
      region.rooms[3].exits = "north|east|southup|west"
      region.rooms[3].links = {}
        region.rooms[3].links.su = {}
          region.rooms[3].links.su.to = 461
          region.rooms[3].links.su.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 777
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 66
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne;e;se"
      region.rooms[4].name = "青石大道"
      region.rooms[4].zone = "襄阳|武当山"
      region.rooms[4].id = 777
      region.rooms[4].desc = "    你走在一条青石大道上，四周静悄悄的。四周是浓密的树林，阴森森的十分怕人。西北方就是陕鄂边界了。北边却是一片草地。"
      region.rooms[4].exits = "south|east|north|northwest"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 462
          region.rooms[4].links.e.con = ""
        region.rooms[4].links.nw = {}
          region.rooms[4].links.nw.to = 1743
          region.rooms[4].links.nw.con = ""
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 2979
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 773
          region.rooms[4].links.n.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;sw"
      region.rooms[5].name = "大道"
      region.rooms[5].zone = "峨眉山|武当山"
      region.rooms[5].id = 1739
      region.rooms[5].desc = "    你走在一条黄土大道上，不时地有人挂剑跨马匆匆而过。东北通向武当。"
      region.rooms[5].exits = "northeast|southwest"
      region.rooms[5].links = {}
        region.rooms[5].links.ne = {}
          region.rooms[5].links.ne.to = 1740
          region.rooms[5].links.ne.con = ""
        region.rooms[5].links.sw = {}
          region.rooms[5].links.sw.to = 1738
          region.rooms[5].links.sw.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw"
      region.rooms[6].name = "三不管"
      region.rooms[6].zone = "武当山"
      region.rooms[6].id = 1740
      region.rooms[6].desc = "    这里是四川、湖北与陕西的交界，俗称三不管。小土路的两旁有疏疏落落的农舍耕田，几只牛羊正在吃草。路上行人很少，都匆匆赶路。"
      region.rooms[6].exits = "east|southeast|southwest"
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 1741
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.sw = {}
          region.rooms[6].links.sw.to = 1739
          region.rooms[6].links.sw.con = ""
        region.rooms[6].links.se = {}
          region.rooms[6].links.se.to = 1745
          region.rooms[6].links.se.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e"
      region.rooms[7].name = "小路"
      region.rooms[7].zone = "武当山"
      region.rooms[7].id = 1741
      region.rooms[7].desc = "    这里是陕西境内。一条静悄悄的黄土路，两旁有些小土屋，疏疏落落的。但路上行人很少，都行色匆匆向前赶路。"
      region.rooms[7].exits = "northeast|west"
      region.rooms[7].links = {}
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 1740
          region.rooms[7].links.w.con = ""
        region.rooms[7].links.ne = {}
          region.rooms[7].links.ne.to = 1742
          region.rooms[7].links.ne.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne"
      region.rooms[8].name = "小路"
      region.rooms[8].zone = "武当山"
      region.rooms[8].id = 1742
      region.rooms[8].desc = "    这里一条静悄悄的黄土路，两旁有些小土屋，疏疏落落的。路上行人很少，都行色匆匆向前赶路。"
      region.rooms[8].exits = "east|southwest"
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 1743
          region.rooms[8].links.e.con = ""
        region.rooms[8].links.sw = {}
          region.rooms[8].links.sw.to = 1741
          region.rooms[8].links.sw.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne;e"
      region.rooms[9].name = "小路"
      region.rooms[9].zone = "武当山"
      region.rooms[9].id = 1743
      region.rooms[9].desc = "    这里是陕西境内的一条静悄悄的黄土路，两旁有些小土屋，疏疏落落的。路上行人很少，都行色匆匆地向前赶路。"
      region.rooms[9].exits = "south|southeast|west"
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 1742
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 1744
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.se = {}
          region.rooms[9].links.se.to = 777
          region.rooms[9].links.se.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne;e;s"
      region.rooms[10].name = "小土屋"
      region.rooms[10].zone = "武当山"
      region.rooms[10].id = 1744
      region.rooms[10].desc = "    这是一间小土屋，看样子是一户农家的房子。屋里简单地摆着些家具，墙角里堆着些农具。炕上坐着一个老婆婆和一个小孩，见有人冲进来，都神色紧张地望着你。"
      region.rooms[10].exits = "north"
      region.rooms[10].links = {}
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 1743
          region.rooms[10].links.n.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n"
      region.rooms[11].name = "黄土路"
      region.rooms[11].zone = "武当山"
      region.rooms[11].id = 1745
      region.rooms[11].desc = "    你走在一条尘土飞扬的黄土路上，两旁是阴森森的树林。这里是湖北境界，据说经常有土匪出没，不可久留。向东南去可至湖南。"
      region.rooms[11].exits = "south|northwest|southeast"
      region.rooms[11].links = {}
        region.rooms[11].links.nw = {}
          region.rooms[11].links.nw.to = 1740
          region.rooms[11].links.nw.con = ""
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 1746
          region.rooms[11].links.s.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e"
      region.rooms[12].name = "黄土路"
      region.rooms[12].zone = "武当山"
      region.rooms[12].id = 1746
      region.rooms[12].desc = "    你走在一条尘土飞扬的黄土路上，两旁是阴森森的树林。这里是湖北境界，据说经常有土匪出没，不可久留。南边一条小道，通向密林深处。"
      region.rooms[12].exits = "north|southup|west"
      region.rooms[12].links = {}
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 1745
          region.rooms[12].links.n.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 1750
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.su = {}
          region.rooms[12].links.su.to = 1747
          region.rooms[12].links.su.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;su"
      region.rooms[13].name = "林中小路"
      region.rooms[13].zone = "武当山"
      region.rooms[13].id = 1747
      region.rooms[13].desc = "    你走在一条僻静的林中小路上，两旁是阴森森的树林。只见左右前后，到处都是铺天盖地的松树林。几十丈高的大松树簇在一块，密实的枝叶象一蓬蓬巨伞般伸向天空，把阳光遮得丝毫也无。据说这里经常有土匪出没，不可久留。边上有个小山洞(dong)。"
      region.rooms[13].exits = "south|northdown"
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 1748
          region.rooms[13].links.s.con = ""
        region.rooms[13].links.nd = {}
          region.rooms[13].links.nd.to = 1746
          region.rooms[13].links.nd.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;su;s"
      region.rooms[14].name = "林中小路"
      region.rooms[14].zone = "武当山"
      region.rooms[14].id = 1748
      region.rooms[14].desc = "    你走在一条僻静的林中小路上，两旁是阴森森的树林。只见左右前后，到处都是铺天盖地的松树林。几十丈高的大松树簇在一块，密实的枝叶象一蓬蓬巨伞般伸向天空，把阳光遮得丝毫也无。据说这里经常有土匪出没，不可久留。"
      region.rooms[14].exits = "north|east"
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 1749
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 1747
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;su;s;e"
      region.rooms[15].name = "林中小路"
      region.rooms[15].zone = "武当山"
      region.rooms[15].id = 1749
      region.rooms[15].desc = "    你走在一条僻静的林中小路上，两旁是阴森森的树林。只见左右前后，到处都是铺天盖地的松树林。几十丈高的大松树簇在一块，密实的枝叶象一蓬蓬巨伞般伸向天空，把阳光遮得丝毫也无。据说这里经常有土匪出没，不可久留。"
      region.rooms[15].exits = "west"
      region.rooms[15].links = {}
        region.rooms[15].links.w = {}
          region.rooms[15].links.w.to = 1748
          region.rooms[15].links.w.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e"
      region.rooms[16].name = "松林小路"
      region.rooms[16].zone = "武当山"
      region.rooms[16].id = 1750
      region.rooms[16].desc = "    这是山脚松林中的小路，两边长满参天的红松树，只能看见一线天空。路旁有道士在奋力砍树。西边通向密林深处，东边可回大道。"
      region.rooms[16].exits = "east|west"
      region.rooms[16].links = {}
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 1746
          region.rooms[16].links.e.con = ""
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 1751
          region.rooms[16].links.w.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed"
      region.rooms[17].name = "松林小路"
      region.rooms[17].zone = "武当山"
      region.rooms[17].id = 1751
      region.rooms[17].desc = "    这是山脚松林中的小路，两边长满参天的红松树，只能看见一线天空。路旁有道士在奋力砍树。东边可回大道。    路边有个石碑(shibei)，很多游客在围那里。原来西边上去就是名镇天下的解剑岩了，"
      region.rooms[17].exits = "south|westup|north|east"
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 1750
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 1752
          region.rooms[17].links.n.con = ""
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 1754
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.wu = {}
          region.rooms[17].links.wu.to = 1756
          region.rooms[17].links.wu.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;n"
      region.rooms[18].name = "松林"
      region.rooms[18].zone = "武当山"
      region.rooms[18].id = 1752
      region.rooms[18].desc = "    这是松林深处，暗无天日，朦胧中只感觉到左右前后到处都是树影。地上有一两个死人骷髅，发着绿荧荧的磷光。你惊骇之间，一脚踩在钢针般的松针上！"
      region.rooms[18].exits = "south|north"
      region.rooms[18].links = {}
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 1751
          region.rooms[18].links.s.con = ""
        region.rooms[18].links.n = {}
          region.rooms[18].links.n.to = 1753
          region.rooms[18].links.n.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;n;n"
      region.rooms[19].name = "松林"
      region.rooms[19].zone = "武当山"
      region.rooms[19].id = 1753
      region.rooms[19].desc = "    这是松林深处，暗无天日，朦胧中只感觉到左右前后到处都是树影。地上有一两个死人骷髅，发着绿荧荧的磷光。你惊骇之间，一脚踩在钢针般的松针上！"
      region.rooms[19].exits = "south"
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 1752
          region.rooms[19].links.s.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;s"
      region.rooms[20].name = "松林"
      region.rooms[20].zone = "武当山"
      region.rooms[20].id = 1754
      region.rooms[20].desc = "    这是松林深处，暗无天日，朦胧中只感觉到左右前后到处都是树影。地上有一两个死人骷髅，发着绿荧荧的磷光。你惊骇之间，一脚踩在钢针般的松针上！"
      region.rooms[20].exits = "south|north"
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 1755
          region.rooms[20].links.s.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 1751
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;s;s"
      region.rooms[21].name = "松林"
      region.rooms[21].zone = "武当山"
      region.rooms[21].id = 1755
      region.rooms[21].desc = "    这是松林深处，暗无天日，朦胧中只感觉到左右前后到处都是树影。地上有一两个死人骷髅，发着绿荧荧的磷光。你惊骇之间，一脚踩在钢针般的松针上！"
      region.rooms[21].exits = "north"
      region.rooms[21].links = {}
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 1754
          region.rooms[21].links.n.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed"
      region.rooms[22].name = "解剑岩"
      region.rooms[22].zone = "武当山"
      region.rooms[22].id = 1756
      region.rooms[22].desc = "    这是武林中极负盛名的武当解剑岩，岩下解剑池水明澈照人。武林人士经此都自觉解剑，以示对武当派的尊敬。千百年来，概无例外。"
      region.rooms[22].exits = "westup|eastdown"
      region.rooms[22].links = {}
        region.rooms[22].links.ed = {}
          region.rooms[22].links.ed.to = 1751
          region.rooms[22].links.ed.con = ""
        region.rooms[22].links.wu = {}
          region.rooms[22].links.wu.to = 1757
          region.rooms[22].links.wu.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e"
      region.rooms[23].name = "松林小路"
      region.rooms[23].zone = "武当山"
      region.rooms[23].id = 1757
      region.rooms[23].desc = "    这是山脚松林中的小路，两边长满参天的红松树，只能看见一线天空。路旁有道士在奋力砍树。西边通向武当山门，东边可通往解剑岩。"
      region.rooms[23].exits = "eastdown|west"
      region.rooms[23].links = {}
        region.rooms[23].links.ed = {}
          region.rooms[23].links.ed.to = 1756
          region.rooms[23].links.ed.con = ""
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 1758
          region.rooms[23].links.w.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd"
      region.rooms[24].name = "玄岳门"
      region.rooms[24].zone = "武当山"
      region.rooms[24].id = 1758
      region.rooms[24].desc = "    你的面前是一座林木繁茂的高山，几座山峰在云雾中隐约可见，一条石阶向山上延伸，走着几个进香客。一个四柱三间五楼式的石坊跨山而建，正面镌有“治世玄岳”四个大字，原来这就是天下闻名的武当山。武当山一名太和山，为七十二福地之一，有二十七峰、三十六岩、二十四涧、五台、五井、三潭、三天门、三洞天和一福地，百里内密树森罗，蔽日参天，景物幽绝。"
      region.rooms[24].exits = "east|southup"
      region.rooms[24].links = {}
        region.rooms[24].links.e = {}
          region.rooms[24].links.e.to = 1757
          region.rooms[24].links.e.con = ""
        region.rooms[24].links.su = {}
          region.rooms[24].links.su.to = 1759
          region.rooms[24].links.su.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd"
      region.rooms[25].name = "石阶"
      region.rooms[25].zone = "武当山"
      region.rooms[25].id = 1759
      region.rooms[25].desc = "    你走在一条坚实的石阶上，不时地有进香客从你的身边走过。一边是峭壁，一边是悬崖，抬头隐约可见笼罩在云雾中的天柱峰，听着流水淙淙，令人心旷神怡。"
      region.rooms[25].exits = "southup|northdown"
      region.rooms[25].links = {}
        region.rooms[25].links.nd = {}
          region.rooms[25].links.nd.to = 1758
          region.rooms[25].links.nd.con = ""
        region.rooms[25].links.su = {}
          region.rooms[25].links.su.to = 1760
          region.rooms[25].links.su.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd"
      region.rooms[26].name = "遇真宫"
      region.rooms[26].zone = "武当山"
      region.rooms[26].id = 1760
      region.rooms[26].desc = "    这里是进入武当山的第一道宫宇遇真宫，宽敞无比，可容千人食宿，是进香客的一大歇脚处。三丰真人曾在此结庵修炼，因此宫中供着张三丰真人像。由于张真人闭关已久，外人不知其是否仍在人间，民间传说他已得道仙逝，立像膜拜。"
      region.rooms[26].exits = "southup|northdown"
      region.rooms[26].links = {}
        region.rooms[26].links.nd = {}
          region.rooms[26].links.nd.to = 1759
          region.rooms[26].links.nd.con = ""
        region.rooms[26].links.su = {}
          region.rooms[26].links.su.to = 1761
          region.rooms[26].links.su.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd"
      region.rooms[27].name = "武当柏林"
      region.rooms[27].zone = "武当山"
      region.rooms[27].id = 1761
      region.rooms[27].desc = "    你穿行在一片茂密的柏林中，阴森郁翠，怪石嶙峋，草深没人。不时地有兔子从你的身边飞跑而过。"
      region.rooms[27].exits = "southup|northdown"
      region.rooms[27].links = {}
        region.rooms[27].links.nd = {}
          region.rooms[27].links.nd.to = 1760
          region.rooms[27].links.nd.con = ""
        region.rooms[27].links.su = {}
          region.rooms[27].links.su.to = 1762
          region.rooms[27].links.su.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu"
      region.rooms[28].name = "好汉坡"
      region.rooms[28].zone = "武当山"
      region.rooms[28].id = 1762
      region.rooms[28].desc = "    此处连绵十几里山势陡峭，名为好汉坡，山路两旁种满了细竹，翠色横空景象怡人，不知不觉让你忘记了爬坡的疲劳。坡顶有一座回龙观，是展望岳顶的最佳去处，但见天柱峰青紫插天，如在眼前，而相去实际上还有五十里。"
      region.rooms[28].exits = "southdown|northdown"
      region.rooms[28].links = {}
        region.rooms[28].links.sd = {}
          region.rooms[28].links.sd.to = 1763
          region.rooms[28].links.sd.con = ""
        region.rooms[28].links.nd = {}
          region.rooms[28].links.nd.to = 1761
          region.rooms[28].links.nd.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly wds;n;nd;nd;nd;nd;nu;nd"
      region.rooms[29].name = "山路"
      region.rooms[29].zone = "武当山"
      region.rooms[29].id = 1763
      region.rooms[29].desc = "    你走在登山的路径上，路的左右各有一条大铁链，象两条长蛇向山上山下蜿蜒爬去。满眼是乔木夹道，如行于绿幕中。"
      region.rooms[29].exits = "east|northup|southup"
      region.rooms[29].links = {}
        region.rooms[29].links.nu = {}
          region.rooms[29].links.nu.to = 1762
          region.rooms[29].links.nu.con = ""
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 1764
          region.rooms[29].links.e.con = ""
        region.rooms[29].links.su = {}
          region.rooms[29].links.su.to = 1765
          region.rooms[29].links.su.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly wds;n;nd;nd;nd;nd;nu;nd;e"
      region.rooms[30].name = "磨针井"
      region.rooms[30].zone = "武当山"
      region.rooms[30].id = 1764
      region.rooms[30].desc = "    相传当年真武进山修炼，日久思归，偶遇一老妇持铁杵研磨。问磨杵为何？答以磨针。又问铁杵岂能磨针？答云功到自然成。真武由此醒悟，终于修炼成仙。后人因建磨针井道观以为纪念。殿前立大铁杵一根，殿旁有老母亭，亭正中有井(jing)。"
      region.rooms[30].exits = "west"
      region.rooms[30].links = {}
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 1763
          region.rooms[30].links.w.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly wds;n;nd;nd;nd;nd;nu"
      region.rooms[31].name = "太子坡"
      region.rooms[31].zone = "武当山"
      region.rooms[31].id = 1765
      region.rooms[31].desc = "    此处地处坡陀之隘，形势险要，相传净乐国太子(少年真武)入山修道时，曾在此留住读书，故名叫太子坡，好象一朵出水芙蓉，涌出绿波，瓣萼历历可数。远处峰回路转，忽明忽灭，尽在云雾之中。"
      region.rooms[31].exits = "east|southdown|northdown"
      region.rooms[31].links = {}
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 1766
          region.rooms[31].links.e.con = ""
        region.rooms[31].links.nd = {}
          region.rooms[31].links.nd.to = 1763
          region.rooms[31].links.nd.con = ""
        region.rooms[31].links.sd = {}
          region.rooms[31].links.sd.to = 1767
          region.rooms[31].links.sd.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly wds;n;nd;nd;nd;nd;nu;e"
      region.rooms[32].name = "复真观五层楼"
      region.rooms[32].zone = "武当山"
      region.rooms[32].id = 1766
      region.rooms[32].desc = "    复真观五层楼构造奇特，其间有十二根梁枋交叉重叠，下面仅用一柱支撑，即有名的“一柱十二梁”。在这里俯瞰群山，烟云迷离，远望金顶，一柱擎天，为观景胜地。"
      region.rooms[32].exits = "west"
      region.rooms[32].links = {}
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 1765
          region.rooms[32].links.w.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly wds;n;nd;nd;nd;nd"
      region.rooms[33].name = "石梁"
      region.rooms[33].zone = "武当山"
      region.rooms[33].id = 1767
      region.rooms[33].desc = "    你走入山坞中，有一道石梁跨溪而建，这里是九渡涧的下流，各岭之水均在此交汇，景色极佳。附近设有许多小吃店，游人至此，大多小住歇歇脚力。再往上就是陡峭的十八盘了。"
      region.rooms[33].exits = "east|northup|southup"
      region.rooms[33].links = {}
        region.rooms[33].links.nu = {}
          region.rooms[33].links.nu.to = 1765
          region.rooms[33].links.nu.con = ""
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 1768
          region.rooms[33].links.e.con = ""
        region.rooms[33].links.su = {}
          region.rooms[33].links.su.to = 1769
          region.rooms[33].links.su.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly wds;n;nd;nd;nd;nd;e"
      region.rooms[34].name = "小吃店"
      region.rooms[34].zone = "武当山"
      region.rooms[34].id = 1768
      region.rooms[34].desc = "    这里是石梁边的一间小吃店，卖些简单的饮食，专门赚那些游客的钱。"
      region.rooms[34].exits = "west"
      region.rooms[34].links = {}
        region.rooms[34].links.w = {}
          region.rooms[34].links.w.to = 1767
          region.rooms[34].links.w.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly wds;n;nd;nd;nd"
      region.rooms[35].name = "十八盘"
      region.rooms[35].zone = "武当山"
      region.rooms[35].id = 1769
      region.rooms[35].desc = "    这是一个很大的斜坡，俗称十八盘，大石阶一级一级笔直而上，颇费脚力。这里坡坡有神，拐拐有祠，往上十里之后即是灵霄宫。"
      region.rooms[35].exits = "southup|northdown"
      region.rooms[35].links = {}
        region.rooms[35].links.nd = {}
          region.rooms[35].links.nd.to = 1767
          region.rooms[35].links.nd.con = ""
        region.rooms[35].links.su = {}
          region.rooms[35].links.su.to = 1770
          region.rooms[35].links.su.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly wds;n;nd;nd"
      region.rooms[36].name = "石阶"
      region.rooms[36].zone = "武当山"
      region.rooms[36].id = 1770
      region.rooms[36].desc = "    你走在一条坚实的石阶上，不时地有进香客从你的身边走过。一边是峭壁，一边是悬崖，抬头隐约可见笼罩在云雾中的天柱峰，听着流水淙淙，令人心旷神怡。北边是一座牌坊。"
      region.rooms[36].exits = "southup|northdown"
      region.rooms[36].links = {}
        region.rooms[36].links.nd = {}
          region.rooms[36].links.nd.to = 1769
          region.rooms[36].links.nd.con = ""
        region.rooms[36].links.su = {}
          region.rooms[36].links.su.to = 1771
          region.rooms[36].links.su.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly wds;n;nd"
      region.rooms[37].name = "紫霄宫大门"
      region.rooms[37].zone = "武当山"
      region.rooms[37].id = 1771
      region.rooms[37].desc = "    你已走到了展旗峰下，前面就是武当山最为宏大的宫宇紫霄宫了。殿宇依山而筑，高低错落有致。周围古木森森，翠竹成林，景色清幽。这里是武当师徒的主要活动场所。"
      region.rooms[37].exits = "southup|northdown"
      region.rooms[37].links = {}
        region.rooms[37].links.nd = {}
          region.rooms[37].links.nd.to = 1770
          region.rooms[37].links.nd.con = ""
        region.rooms[37].links.su = {}
          region.rooms[37].links.su.to = 1772
          region.rooms[37].links.su.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly wds;n"
      region.rooms[38].name = "武当广场"
      region.rooms[38].zone = "武当山"
      region.rooms[38].id = 1772
      region.rooms[38].desc = "    这是一个由大石板铺成的广场，是武当弟子学习武功和互相切磋的地点。周围种满了梧桐树，一到秋天就是满地的落叶。一个年纪轻轻的道童正在打扫。南边是灵霄宫三清殿。"
      region.rooms[38].exits = "south|east|eastdown|northdown"
      region.rooms[38].links = {}
        region.rooms[38].links.ed = {}
          region.rooms[38].links.ed.to = 1773
          region.rooms[38].links.ed.con = ""
        region.rooms[38].links.nd = {}
          region.rooms[38].links.nd.to = 1771
          region.rooms[38].links.nd.con = ""
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 1792
          region.rooms[38].links.s.con = ""
        region.rooms[38].links.e = {}
          region.rooms[38].links.e.to = 1807
          region.rooms[38].links.e.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly wds;n;ed"
      region.rooms[39].name = "石阶"
      region.rooms[39].zone = "武当山"
      region.rooms[39].id = 1773
      region.rooms[39].desc = "    这是一条宽大坚实的石阶路，不时地有进香客和游人从你的身边走过。抬头西望，雄伟的三清殿顶浮现在香烟袅绕之中，巍峨壮观；东边一条石阶通往山下，隐约可见远处桃花片片，赏心悦目。"
      region.rooms[39].exits = "westup|east"
      region.rooms[39].links = {}
        region.rooms[39].links.e = {}
          region.rooms[39].links.e.to = 1774
          region.rooms[39].links.e.con = ""
        region.rooms[39].links.wu = {}
          region.rooms[39].links.wu.to = 1772
          region.rooms[39].links.wu.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly wds;n;ed;e"
      region.rooms[40].name = "石阶"
      region.rooms[40].zone = "武当山"
      region.rooms[40].id = 1774
      region.rooms[40].desc = "    这是一条宽大坚实的石阶路，不时地有进香客和游人从你的身边走过。抬头西望，雄伟的三清殿顶浮现在香烟袅绕之中，巍峨壮观；东边一条石阶通往山下，隐约可见远处桃花片片，赏心悦目。"
      region.rooms[40].exits = "east|west"
      region.rooms[40].links = {}
        region.rooms[40].links.w = {}
          region.rooms[40].links.w.to = 1773
          region.rooms[40].links.w.con = ""
        region.rooms[40].links.e = {}
          region.rooms[40].links.e.to = 1775
          region.rooms[40].links.e.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly wds;n;ed;e;e"
      region.rooms[41].name = "石阶"
      region.rooms[41].zone = "武当山"
      region.rooms[41].id = 1775
      region.rooms[41].desc = "    这是一条宽大坚实的石阶路，不时地有进香客和游人从你的身边走过。抬头西望，雄伟的三清殿顶浮现在香烟袅绕之中，巍峨壮观；东边一条石阶通往山下，隐约可见远处桃花片片，赏心悦目。"
      region.rooms[41].exits = "eastdown|west"
      region.rooms[41].links = {}
        region.rooms[41].links.w = {}
          region.rooms[41].links.w.to = 1774
          region.rooms[41].links.w.con = ""
        region.rooms[41].links.ed = {}
          region.rooms[41].links.ed.to = 1776
          region.rooms[41].links.ed.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly wds;n;ed;e;e;ed"
      region.rooms[42].name = "崎岖山路"
      region.rooms[42].zone = "武当山"
      region.rooms[42].id = 1776
      region.rooms[42].desc = "    你走在一条崎岖狭隘的山路上，一边是峭壁，一边是悬崖。高高的天柱峰(feng)笼罩在云雾中，隐约可见。可是身旁的进香客和游人都仔细地町着自己的脚下，不敢抬头望一眼，惟恐一不小心摔下去。更有强人趁机打劫，行人无不噤声闭气，只求快点赶路。"
      region.rooms[42].exits = "westup|southdown"
      region.rooms[42].links = {}
        region.rooms[42].links.sd = {}
          region.rooms[42].links.sd.to = 1777
          region.rooms[42].links.sd.con = ""
        region.rooms[42].links.wu = {}
          region.rooms[42].links.wu.to = 1775
          region.rooms[42].links.wu.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly wds;n;ed;e;e;ed;sd"
      region.rooms[43].name = "崎岖山路"
      region.rooms[43].zone = "武当山"
      region.rooms[43].id = 1777
      region.rooms[43].desc = "    你走在一条崎岖狭窄的山路上，一边是峭壁，一边是悬崖，高高的天柱峰(feng)在云雾中隐约可见。身旁的进香客和游人都仔细地盯着自己的脚下，不敢抬头望一眼，惟恐一不小心摔下去。更有强人趁机打劫，行人无不噤声闭气，只求快点赶路。"
      region.rooms[43].exits = "eastdown|northup"
      region.rooms[43].links = {}
        region.rooms[43].links.nu = {}
          region.rooms[43].links.nu.to = 1776
          region.rooms[43].links.nu.con = ""
        region.rooms[43].links.ed = {}
          region.rooms[43].links.ed.to = 1778
          region.rooms[43].links.ed.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly wds;n;ed;e;e;ed;sd;ed"
      region.rooms[44].name = "崎岖山路"
      region.rooms[44].zone = "武当山"
      region.rooms[44].id = 1778
      region.rooms[44].desc = "    你走在一条崎岖狭隘的山路上，一边是峭壁，一边是悬崖。高高的天柱峰(feng)笼罩在云雾中，隐约可见。可是身旁的进香客和游人都仔细地町着自己的脚下，不敢抬头望一眼，惟恐一不小心摔下去。更有强人趁机打劫，行人无不噤声闭气，只求快点赶路。"
      region.rooms[44].exits = "westup|southdown"
      region.rooms[44].links = {}
        region.rooms[44].links.sd = {}
          region.rooms[44].links.sd.to = 1779
          region.rooms[44].links.sd.con = ""
        region.rooms[44].links.wu = {}
          region.rooms[44].links.wu.to = 1777
          region.rooms[44].links.wu.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly wds;n;ed;e;e;ed;sd;ed;sd"
      region.rooms[45].name = "崎岖山路"
      region.rooms[45].zone = "武当山"
      region.rooms[45].id = 1779
      region.rooms[45].desc = "    你走在一条崎岖狭隘的山路上，一边是峭壁，一边是悬崖。高高的天柱峰(feng)笼罩在云雾中，隐约可见。可是身旁的进香客和游人都仔细地町着自己的脚下，不敢抬头望一眼，惟恐一不小心摔下去。更有强人趁机打劫，行人无不噤声闭气，只求快点赶路。"
      region.rooms[45].exits = "eastdown|northup"
      region.rooms[45].links = {}
        region.rooms[45].links.nu = {}
          region.rooms[45].links.nu.to = 1778
          region.rooms[45].links.nu.con = ""
        region.rooms[45].links.ed = {}
          region.rooms[45].links.ed.to = 1780
          region.rooms[45].links.ed.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed"
      region.rooms[46].name = "桃园小路"
      region.rooms[46].zone = "武当山"
      region.rooms[46].id = 1780
      region.rooms[46].desc = "    眼前豁然开朗，你轻松地走在桃园边的小路上。两边是桃树林，树上盛开着粉红的桃花，红云一片，望不到边。不时有蜜蜂「嗡嗡」地飞过，消失在在花丛中；几只猴子在树上互相追逐着，叽叽喳喳地争抢桃子。这是武当山脚，西边有条陡峭的山路，通向山顶。"
      region.rooms[46].exits = "south|westup|north|east"
      region.rooms[46].links = {}
        region.rooms[46].links.e = {}
          region.rooms[46].links.e.to = 1783
          region.rooms[46].links.e.con = ""
        region.rooms[46].links.wu = {}
          region.rooms[46].links.wu.to = 1779
          region.rooms[46].links.wu.con = ""
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 1781
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 1782
          region.rooms[46].links.n.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;s"
      region.rooms[47].name = "桃园小路"
      region.rooms[47].zone = "武当山"
      region.rooms[47].id = 1781
      region.rooms[47].desc = "    眼前豁然开朗，你轻松地走在桃园边的小路上。路上落英缤纷，一边是桃树林，盛开着粉红的桃花，红云一片，望不到边。还可以看见蜜蜂「嗡嗡」地在花间飞上飞下忙个不停，间或传来猿猴的叽咋声。这儿是武当山脚，南边是条环山的黄土路。"
      region.rooms[47].exits = "north"
      region.rooms[47].links = {}
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 1780
          region.rooms[47].links.n.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;n"
      region.rooms[48].name = "桃园小路"
      region.rooms[48].zone = "武当山"
      region.rooms[48].id = 1782
      region.rooms[48].desc = "    眼前豁然开朗，你轻松地走在桃园边的小路上。路上落英缤纷，一边是桃树林，盛开着粉红的桃花，红云一片，望不到边。还可以看见蜜蜂「嗡嗡」地在花间飞上飞下忙个不停，间或传来猿猴的叽咋声。这儿是武当山脚，北边是条环山的黄土路。"
      region.rooms[48].exits = "south"
      region.rooms[48].links = {}
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 1780
          region.rooms[48].links.s.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e"
      region.rooms[49].name = "桃园小路"
      region.rooms[49].zone = "武当山"
      region.rooms[49].id = 1783
      region.rooms[49].desc = "    眼前豁然开朗，你轻松地走在桃园边的小路上。两边是桃树林，树上盛开着粉红的桃花，红云一片，望不到边。不时有蜜蜂「嗡嗡」地飞过，消失在在花丛中；几只猴子在树上互相追逐着，叽叽喳喳地争抢桃子。"
      region.rooms[49].exits = "east|west"
      region.rooms[49].links = {}
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 1780
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 1784
          region.rooms[49].links.e.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e;e"
      region.rooms[50].name = "桃园小路"
      region.rooms[50].zone = "武当山"
      region.rooms[50].id = 1784
      region.rooms[50].desc = "    眼前豁然开朗，你轻松地走在桃园边的小路上。两边是桃树林，树上盛开着粉红的桃花，红云一片，望不到边。不时有蜜蜂「嗡嗡」地飞过，消失在在花丛中；几只猴子在树上互相追逐着，叽叽喳喳地争抢桃子。南北方向是通向两个桃园的入口。"
      region.rooms[50].exits = "south|north|east|west"
      region.rooms[50].links = {}
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 1787
          region.rooms[50].links.e.con = ""
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 1783
          region.rooms[50].links.w.con = ""
        region.rooms[50].links.s = {}
          region.rooms[50].links.s.to = 1786
          region.rooms[50].links.s.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 1785
          region.rooms[50].links.n.con = ""
    region.rooms[51] = {}
      region.rooms[51].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e;e;n"
      region.rooms[51].name = "桃园篱笆"
      region.rooms[51].zone = "武当山"
      region.rooms[51].id = 1785
      region.rooms[51].desc = "    你走在一条通往桃树林深处的小道上，前面有个篱笆门(fence)。"
      region.rooms[51].exits = "south"
      region.rooms[51].links = {}
        region.rooms[51].links.s = {}
          region.rooms[51].links.s.to = 1784
          region.rooms[51].links.s.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e;e;s"
      region.rooms[52].name = "桃园木门"
      region.rooms[52].zone = "武当山"
      region.rooms[52].id = 1786
      region.rooms[52].desc = "    你走在一条通往桃树林深处的小道上，前面有个桃木门(door)。"
      region.rooms[52].exits = "north"
      region.rooms[52].links = {}
        region.rooms[52].links.n = {}
          region.rooms[52].links.n.to = 1784
          region.rooms[52].links.n.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e;e;e"
      region.rooms[53].name = "桃园小路"
      region.rooms[53].zone = "武当山"
      region.rooms[53].id = 1787
      region.rooms[53].desc = "    眼前豁然开朗，你轻松地走在桃园边的小路上。两边是桃树林，树上盛开着粉红的桃花，红云一片，望不到边。不时有蜜蜂「嗡嗡」地飞过，消失在在花丛中；几只猴子在树上互相追逐着，叽叽喳喳地争抢桃子。"
      region.rooms[53].exits = "east|west"
      region.rooms[53].links = {}
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 1784
          region.rooms[53].links.w.con = ""
        region.rooms[53].links.e = {}
          region.rooms[53].links.e.to = 1788
          region.rooms[53].links.e.con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e;e;e;e"
      region.rooms[54].name = "桃园小路"
      region.rooms[54].zone = "武当山"
      region.rooms[54].id = 1788
      region.rooms[54].desc = "    眼前豁然开朗，你轻松地走在桃园边的小路上。路上落英缤纷，两边是桃树林，盛开着粉红的桃花，红云一片，望不到边。你仔细一看，原来桃树丛中有一株及其古怪的茶树，上面长满了茶叶。"
      region.rooms[54].exits = "east|west"
      region.rooms[54].links = {}
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 1787
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 1789
          region.rooms[54].links.e.con = ""
    region.rooms[55] = {}
      region.rooms[55].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e;e;e;e;e"
      region.rooms[55].name = "桃园"
      region.rooms[55].zone = "武当山"
      region.rooms[55].id = 1789
      region.rooms[55].desc = "    眼前豁然开朗，你轻松地走在桃园的小路上。两边是桃树林(tree)，树上盛开着粉红的桃花，红云一片，望不到边。不时有蜜蜂「嗡嗡」地飞过，消失在在花丛中；几只猴子在树上互相追逐着，叽叽喳喳地争抢桃子。远处是高高的天柱峰(feng)。"
      region.rooms[55].exits = "east|west"
      region.rooms[55].links = {}
        region.rooms[55].links.w = {}
          region.rooms[55].links.w.to = 1788
          region.rooms[55].links.w.con = ""
        region.rooms[55].links.e = {}
          region.rooms[55].links.e.to = 1790
          region.rooms[55].links.e.con = ""
    region.rooms[56] = {}
      region.rooms[56].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e;e;e;e;e;e"
      region.rooms[56].name = "果园小路"
      region.rooms[56].zone = "武当山"
      region.rooms[56].id = 1790
      region.rooms[56].desc = "    眼前豁然开朗，你轻松地走在果园边的小路上。路上落英缤纷，两边是桃树林，盛开着粉红的桃花，红云一片，望不到边。还可以看蜜蜂「嗡嗡」地在花间飞上飞下忙个不停，间或传来猿猴的叽咋声。"
      region.rooms[56].exits = "east|west"
      region.rooms[56].links = {}
        region.rooms[56].links.w = {}
          region.rooms[56].links.w.to = 1789
          region.rooms[56].links.w.con = ""
        region.rooms[56].links.e = {}
          region.rooms[56].links.e.to = 1791
          region.rooms[56].links.e.con = ""
    region.rooms[57] = {}
      region.rooms[57].path = "fly wds;n;ed;e;e;ed;sd;ed;sd;ed;e;e;e;e;e;e;e"
      region.rooms[57].name = "果园"
      region.rooms[57].zone = "武当山"
      region.rooms[57].id = 1791
      region.rooms[57].desc = "    你轻松地走进果园。园中落英缤纷，两边是桃树林，盛开着粉红的桃花，红云一片，望不到边。中间却是一株冠盖数亩的大树(tree)，遮住地面好大一片绿荫。"
      region.rooms[57].exits = "west"
      region.rooms[57].links = {}
        region.rooms[57].links.w = {}
          region.rooms[57].links.w.to = 1790
          region.rooms[57].links.w.con = ""
    region.rooms[58] = {}
      region.rooms[58].path = "fly wds"
      region.rooms[58].name = "三清殿"
      region.rooms[58].zone = "武当山"
      region.rooms[58].id = 1792
      region.rooms[58].desc = "    这里是凌霄宫的三清殿，是武当派会客的地点。供着元始天尊、太上道君和天上老君的神像，香案上香烟缭绕。靠墙放着几张太师椅，地上放着几个蒲团。东西两侧是走廊，北边是练武的广场，南边是后院。"
      region.rooms[58].exits = "south|east|north|west"
      region.rooms[58].links = {}
        region.rooms[58].links.e = {}
          region.rooms[58].links.e.to = 1803
          region.rooms[58].links.e.con = ""
        region.rooms[58].links.s = {}
          region.rooms[58].links.s.to = 1793
          region.rooms[58].links.s.con = ""
        region.rooms[58].links.w = {}
          region.rooms[58].links.w.to = 1797
          region.rooms[58].links.w.con = ""
        region.rooms[58].links.n = {}
          region.rooms[58].links.n.to = 1772
          region.rooms[58].links.n.con = ""
    region.rooms[59] = {}
      region.rooms[59].path = "fly wds;s"
      region.rooms[59].name = "后院"
      region.rooms[59].zone = "武当山"
      region.rooms[59].id = 1793
      region.rooms[59].desc = "    这里是后院，北面是三清殿，南面是一个圆形的门洞，有一条小路通往后山。"
      region.rooms[59].exits = "south|north"
      region.rooms[59].links = {}
        region.rooms[59].links.s = {}
          region.rooms[59].links.s.to = 1794
          region.rooms[59].links.s.con = ""
        region.rooms[59].links.n = {}
          region.rooms[59].links.n.to = 1792
          region.rooms[59].links.n.con = ""
    region.rooms[60] = {}
      region.rooms[60].path = "fly wds;s;s"
      region.rooms[60].name = "林间小径"
      region.rooms[60].zone = "武当山"
      region.rooms[60].id = 1794
      region.rooms[60].desc = "    你走在一条小径上，两旁种满了竹子，修篁森森，绿荫满地，除了竹叶声和鸟鸣声，听不到别的动静。"
      region.rooms[60].exits = "south|north"
      region.rooms[60].links = {}
        region.rooms[60].links.s = {}
          region.rooms[60].links.s.to = 1795
          region.rooms[60].links.s.con = ""
        region.rooms[60].links.n = {}
          region.rooms[60].links.n.to = 1793
          region.rooms[60].links.n.con = ""
    region.rooms[61] = {}
      region.rooms[61].path = "fly wds;s;s;s"
      region.rooms[61].name = "林间小径"
      region.rooms[61].zone = "武当山"
      region.rooms[61].id = 1795
      region.rooms[61].desc = "    你走在一条小径上，两旁种满了竹子，修篁森森，绿荫满地，除了竹叶声和鸟鸣声，听不到别的动静。南面似乎有一座简陋的小院。"
      region.rooms[61].exits = "south|north"
      region.rooms[61].links = {}
        region.rooms[61].links.s = {}
          region.rooms[61].links.s.to = 1796
          region.rooms[61].links.s.con = ""
        region.rooms[61].links.n = {}
          region.rooms[61].links.n.to = 1794
          region.rooms[61].links.n.con = ""
    region.rooms[62] = {}
      region.rooms[62].path = "fly wds;s;s;s;s"
      region.rooms[62].name = "后山小院"
      region.rooms[62].zone = "武当山"
      region.rooms[62].id = 1796
      region.rooms[62].desc = "    这是后山的一座小院，布置简简单单，除了一床、一桌、一椅、一蒲团，再也没有别的什物。比较引人注目的是墙上挂着一把剑。这里就是武当开山祖师张三丰的练功所在。"
      region.rooms[62].exits = "north"
      region.rooms[62].links = {}
        region.rooms[62].links.n = {}
          region.rooms[62].links.n.to = 1795
          region.rooms[62].links.n.con = ""
    region.rooms[63] = {}
      region.rooms[63].path = "fly wds;w"
      region.rooms[63].name = "西厢走廊"
      region.rooms[63].zone = "武当山"
      region.rooms[63].id = 1797
      region.rooms[63].desc = "    你走在一条走廊上，东边是大殿，北边是一座楼阁。西面楼上传来阵阵打斗声。"
      region.rooms[63].exits = "south|westup|east|northup"
      region.rooms[63].links = {}
        region.rooms[63].links.e = {}
          region.rooms[63].links.e.to = 1792
          region.rooms[63].links.e.con = ""
        region.rooms[63].links.nu = {}
          region.rooms[63].links.nu.to = 1798
          region.rooms[63].links.nu.con = ""
        region.rooms[63].links.s = {}
          region.rooms[63].links.s.to = 1799
          region.rooms[63].links.s.con = ""
        region.rooms[63].links.wu = {}
          region.rooms[63].links.wu.to = 1800
          region.rooms[63].links.wu.con = ""
    region.rooms[64] = {}
      region.rooms[64].path = "fly wds;w;nu"
      region.rooms[64].name = "藏经阁"
      region.rooms[64].zone = "武当山"
      region.rooms[64].id = 1798
      region.rooms[64].desc = "    这里是藏经阁，靠墙是一排书架，摆满了道教的典籍。中央有一个长方形的大桌子，上面也堆满了书。一个道童正在整理书籍。"
      region.rooms[64].exits = "southdown"
      region.rooms[64].links = {}
        region.rooms[64].links.sd = {}
          region.rooms[64].links.sd.to = 1797
          region.rooms[64].links.sd.con = ""
    region.rooms[65] = {}
      region.rooms[65].path = "fly wds;w;s"
      region.rooms[65].name = "药剂室"
      region.rooms[65].zone = "武当山"
      region.rooms[65].id = 1799
      region.rooms[65].desc = "    这里是武当派制药、配药的地方。这间房间本来很大，只是被前后左右堆放的药柜药箱挤的显得小多了。药柜已经很陈旧了，不过是用上好的南海沉香木做成的，据说用这种木材做成的柜子用来储藏东西不会遭虫蛀。一位道长站在这里，武当派的弟子可以向他申请采药和炼丹的任务。(ask zhangyao about job)"
      region.rooms[65].exits = "south|north"
      region.rooms[65].links = {}
        region.rooms[65].links.n = {}
          region.rooms[65].links.n.to = 1797
          region.rooms[65].links.n.con = ""
    region.rooms[66] = {}
      region.rooms[66].path = "fly wds;w;wu"
      region.rooms[66].name = "操练房"
      region.rooms[66].zone = "武当山"
      region.rooms[66].id = 1800
      region.rooms[66].desc = "    这是二楼操练房上，四面八方都是打斗声，武当弟子来去匆匆。"
      region.rooms[66].exits = "south|north|eastdown"
      region.rooms[66].links = {}
        region.rooms[66].links.ed = {}
          region.rooms[66].links.ed.to = 1797
          region.rooms[66].links.ed.con = ""
        region.rooms[66].links.s = {}
          region.rooms[66].links.s.to = 1802
          region.rooms[66].links.s.con = ""
        region.rooms[66].links.n = {}
          region.rooms[66].links.n.to = 1801
          region.rooms[66].links.n.con = ""
    region.rooms[67] = {}
      region.rooms[67].path = "fly wds;w;wu;n"
      region.rooms[67].name = "北间操练房"
      region.rooms[67].zone = "武当山"
      region.rooms[67].id = 1801
      region.rooms[67].desc = "    这里摆满了大刀长剑、沙袋绑腿等，是武当弟子日常练功的地方。"
      region.rooms[67].exits = "south"
      region.rooms[67].links = {}
        region.rooms[67].links.s = {}
          region.rooms[67].links.s.to = 1800
          region.rooms[67].links.s.con = ""
    region.rooms[68] = {}
      region.rooms[68].path = "fly wds;w;wu;s"
      region.rooms[68].name = "南间操练房"
      region.rooms[68].zone = "武当山"
      region.rooms[68].id = 1802
      region.rooms[68].desc = "    这里摆满了大刀长剑、沙袋绑腿等，是武当弟子日常练功的地方。"
      region.rooms[68].exits = "north"
      region.rooms[68].links = {}
        region.rooms[68].links.n = {}
          region.rooms[68].links.n.to = 1800
          region.rooms[68].links.n.con = ""
    region.rooms[69] = {}
      region.rooms[69].path = "fly wds;e"
      region.rooms[69].name = "东厢走廊"
      region.rooms[69].zone = "武当山"
      region.rooms[69].id = 1803
      region.rooms[69].desc = "    你走在一条走廊上，东边有几间雅室，人来人往很热闹。西边是大殿。"
      region.rooms[69].exits = "east|west"
      region.rooms[69].links = {}
        region.rooms[69].links.w = {}
          region.rooms[69].links.w.to = 1792
          region.rooms[69].links.w.con = ""
        region.rooms[69].links.e = {}
          region.rooms[69].links.e.to = 1804
          region.rooms[69].links.e.con = ""
    region.rooms[70] = {}
      region.rooms[70].path = "fly wds;e;e"
      region.rooms[70].name = "东厢走廊"
      region.rooms[70].zone = "武当山"
      region.rooms[70].id = 1804
      region.rooms[70].desc = "    你走在一条走廊上，隐约可以听到东边传来呼吸声，似乎有人正在那里练功，北边有一扇门（men），好象是虚掩着。南边是间竹子扎就的屋子，十分的素雅，里面飘出一阵阵的茶香，有人轻声细语地不知说那些什么，引得女孩子＂吃吃＂笑出声来。"
      region.rooms[70].exits = "south|east|west"
      region.rooms[70].links = {}
        region.rooms[70].links.e = {}
          region.rooms[70].links.e.to = 1806
          region.rooms[70].links.e.con = ""
        region.rooms[70].links.s = {}
          region.rooms[70].links.s.to = 1805
          region.rooms[70].links.s.con = ""
        region.rooms[70].links.w = {}
          region.rooms[70].links.w.to = 1803
          region.rooms[70].links.w.con = ""
    region.rooms[71] = {}
      region.rooms[71].path = "fly wds;e;e;s"
      region.rooms[71].name = "茶室"
      region.rooms[71].zone = "武当山"
      region.rooms[71].id = 1805
      region.rooms[71].desc = "    满屋的果香和茶香，沁人心脾。山西面的茶农们因感激武当弟子保护他们免受土匪的骚乱和官府的苛捐杂税，每年开春采茶季节，总要送来上好的茶叶。这茶叶由少女在三更至日出间采摘，并放在怀中用体温焙制，得天地精华，汇处子体香，故名＂女儿香＂，据说喝了能提精补神，十分珍贵。屋里四周得体地摆着些桌子(table)和椅子(chair)，坐满了武当的男女弟子。南边有扇窗子(window)，景色宜人。"
      region.rooms[71].exits = "north"
      region.rooms[71].links = {}
        region.rooms[71].links.n = {}
          region.rooms[71].links.n.to = 1804
          region.rooms[71].links.n.con = ""
    region.rooms[72] = {}
      region.rooms[72].path = "fly wds;e;e;e"
      region.rooms[72].name = "练功房"
      region.rooms[72].zone = "武当山"
      region.rooms[72].id = 1806
      region.rooms[72].desc = "    这里是练功房，地下凌乱地放着几个蒲团，几位武当弟子正盘膝坐在上面打坐。"
      region.rooms[72].exits = "west"
      region.rooms[72].links = {}
        region.rooms[72].links.w = {}
          region.rooms[72].links.w.to = 1804
          region.rooms[72].links.w.con = ""
    region.rooms[73] = {}
      region.rooms[73].path = "fly wds;n;e"
      region.rooms[73].name = "山路"
      region.rooms[73].zone = "武当山"
      region.rooms[73].id = 1807
      region.rooms[73].desc = "    你走在登山的路径上，路的左右各有一条大铁链，象两条长蛇向山上山下蜿蜒爬去。满眼是乔木夹道，如行于绿幕中。"
      region.rooms[73].exits = "east|west"
      region.rooms[73].links = {}
        region.rooms[73].links.w = {}
          region.rooms[73].links.w.to = 1772
          region.rooms[73].links.w.con = ""
        region.rooms[73].links.e = {}
          region.rooms[73].links.e.to = 1808
          region.rooms[73].links.e.con = ""
    region.rooms[74] = {}
      region.rooms[74].path = "fly wds;n;e;e"
      region.rooms[74].name = "山路"
      region.rooms[74].zone = "武当山"
      region.rooms[74].id = 1808
      region.rooms[74].desc = "    你走在登山的路径上，路的左右各有一条大铁链，象两条长蛇向山上山下蜿蜒爬去。满眼是乔木夹道，如行于绿幕中。"
      region.rooms[74].exits = "southup|west"
      region.rooms[74].links = {}
        region.rooms[74].links.w = {}
          region.rooms[74].links.w.to = 1807
          region.rooms[74].links.w.con = ""
        region.rooms[74].links.su = {}
          region.rooms[74].links.su.to = 1809
          region.rooms[74].links.su.con = ""
    region.rooms[75] = {}
      region.rooms[75].path = "fly wds;n;e;e;su"
      region.rooms[75].name = "山路"
      region.rooms[75].zone = "武当山"
      region.rooms[75].id = 1809
      region.rooms[75].desc = "    你走在登山的路径上，路的左右各有一条大铁链，象两条长蛇向山上山下蜿蜒爬去。满眼是乔木夹道，如行于绿幕中。"
      region.rooms[75].exits = "southup|northdown"
      region.rooms[75].links = {}
        region.rooms[75].links.nd = {}
          region.rooms[75].links.nd.to = 1808
          region.rooms[75].links.nd.con = ""
        region.rooms[75].links.su = {}
          region.rooms[75].links.su.to = 1810
          region.rooms[75].links.su.con = ""
    region.rooms[76] = {}
      region.rooms[76].path = "fly wds;n;e;e;su;su"
      region.rooms[76].name = "太子岩"
      region.rooms[76].zone = "武当山"
      region.rooms[76].id = 1810
      region.rooms[76].desc = "    这里是群山环抱中的太子岩，岩上有一块三清石和一座太子亭。"
      region.rooms[76].exits = "southdown|northdown"
      region.rooms[76].links = {}
        region.rooms[76].links.sd = {}
          region.rooms[76].links.sd.to = 1811
          region.rooms[76].links.sd.con = ""
        region.rooms[76].links.nd = {}
          region.rooms[76].links.nd.to = 1809
          region.rooms[76].links.nd.con = ""
    region.rooms[77] = {}
      region.rooms[77].path = "fly wds;n;e;e;su;su;sd"
      region.rooms[77].name = "榔梅园外"
      region.rooms[77].zone = "武当山"
      region.rooms[77].id = 1811
      region.rooms[77].desc = "    这里种满了榔梅树，花色深浅一如桃花，蒂垂丝作海棠状。榔和梅本是山中的两种树，相传有一天玄武帝把梅枝插在榔干上，久而复合，成此异种。据说榔梅果核不可以带出武当山，违者必遭不昌。"
      region.rooms[77].exits = "westup|enter|northup|southup"
      region.rooms[77].links = {}
        region.rooms[77].links.nu = {}
          region.rooms[77].links.nu.to = 1810
          region.rooms[77].links.nu.con = ""
        region.rooms[77].links.wu = {}
          region.rooms[77].links.wu.to = 1812
          region.rooms[77].links.wu.con = ""
        region.rooms[77].links.enter = {}
          region.rooms[77].links.enter.to = 1816
          region.rooms[77].links.enter.con = ""
        region.rooms[77].links.su = {}
          region.rooms[77].links.su.to = 1817
          region.rooms[77].links.su.con = ""
    region.rooms[78] = {}
      region.rooms[78].path = "fly wds;n;e;e;su;su;sd;wu"
      region.rooms[78].name = "南岩峰"
      region.rooms[78].zone = "武当山"
      region.rooms[78].id = 1812
      region.rooms[78].desc = "    这里是武当三十六岩之最，松树翳天，木石争奇，峭壁万仞。在悬崖之半筑有一宫宇，下临深渊，工程浩大。宫前有一石柱，自峭壁上横出。"
      region.rooms[78].exits = "eastdown|southdown|west"
      region.rooms[78].links = {}
        region.rooms[78].links.ed = {}
          region.rooms[78].links.ed.to = 1811
          region.rooms[78].links.ed.con = ""
        region.rooms[78].links.w = {}
          region.rooms[78].links.w.to = 1813
          region.rooms[78].links.w.con = ""
        region.rooms[78].links.sd = {}
          region.rooms[78].links.sd.to = 1814
          region.rooms[78].links.sd.con = ""
    region.rooms[79] = {}
      region.rooms[79].path = "fly wds;n;e;e;su;su;sd;wu;w"
      region.rooms[79].name = "舍身崖"
      region.rooms[79].zone = "武当山"
      region.rooms[79].id = 1813
      region.rooms[79].desc = "    这是一处险峻的悬崖峭壁，相传真武帝在此舍身得道。崖上立有铁栅栏，防止有人自杀步真武帝的后尘。"
      region.rooms[79].exits = "east"
      region.rooms[79].links = {}
        region.rooms[79].links.e = {}
          region.rooms[79].links.e.to = 1812
          region.rooms[79].links.e.con = ""
    region.rooms[80] = {}
      region.rooms[80].path = "fly wds;n;e;e;su;su;sd;wu;sd"
      region.rooms[80].name = "石柱"
      region.rooms[80].zone = "武当山"
      region.rooms[80].id = 1814
      region.rooms[80].desc = "    这是南岩宫前的一根石柱，雕成龙形，自峭壁上横出，犹如飞龙在天。龙首刻一香炉，在此上香称为“上龙头香”，是香客的最大心愿。石柱仅粗如屋梁，旁无扶栏，前有白云缭绕，下有万丈深渊，稍一失足，即尸骨无存。"
      region.rooms[80].exits = "enter|northup"
      region.rooms[80].links = {}
        region.rooms[80].links.nu = {}
          region.rooms[80].links.nu.to = 1812
          region.rooms[80].links.nu.con = ""
        region.rooms[80].links.enter = {}
          region.rooms[80].links.enter.to = 1815
          region.rooms[80].links.enter.con = ""
    region.rooms[81] = {}
      region.rooms[81].path = "fly wds;n;e;e;su;su;sd;wu;sd;enter"
      region.rooms[81].name = "南岩宫"
      region.rooms[81].zone = "武当山"
      region.rooms[81].id = 1815
      region.rooms[81].desc = "    这里是就是南岩宫。此宫半卧悬崖之下。殿内三清坐像金光闪闪，气宇轩昂。殿内天井处芳草迷径，百卉争妍。    有几个装束醒目的武当三代弟子从这匆匆走过。    南面高台就是真武剑阵。叛师或半路投师者珍重。"
      region.rooms[81].exits = "southup|out"
      region.rooms[81].links = {}
        region.rooms[81].links["move xiang;d"] = {}
          region.rooms[81].links["move xiang;d"].to = 2105
          region.rooms[81].links["move xiang;d"].con = ""
        region.rooms[81].links.out = {}
          region.rooms[81].links.out.to = 1814
          region.rooms[81].links.out.con = ""
    region.rooms[82] = {}
      region.rooms[82].path = "fly wds;n;e;e;su;su;sd;enter"
      region.rooms[82].name = "榔梅园"
      region.rooms[82].zone = "武当山"
      region.rooms[82].id = 1816
      region.rooms[82].desc = "    眼前豁然开朗，你轻松地走在榔梅园的小路上。两边是桃树林(tree)，树上盛开着粉红的桃花，红云一片，望不到边。不时有蜜蜂「嗡嗡」地飞过，消失在在花丛中；几只猴子在树上互相追逐着，叽叽喳喳地争抢桃子。远处是高高的天柱峰(feng)。"
      region.rooms[82].exits = "out"
      region.rooms[82].links = {}
        region.rooms[82].links.out = {}
          region.rooms[82].links.out.to = 1811
          region.rooms[82].links.out.con = ""
    region.rooms[83] = {}
      region.rooms[83].path = "fly wds;n;e;e;su;su;sd;su"
      region.rooms[83].name = "乌鸦岭"
      region.rooms[83].zone = "武当山"
      region.rooms[83].id = 1817
      region.rooms[83].desc = "    这是一狭长的脊岭，两侧悬削，一无所傍，但见白云朵朵，冉冉而过，山风拂拂，阵阵袭来。数百只乌鸦正翱翔云际，黑白分明，蔚成奇观。"
      region.rooms[83].exits = "southup|northdown"
      region.rooms[83].links = {}
        region.rooms[83].links.nd = {}
          region.rooms[83].links.nd.to = 1811
          region.rooms[83].links.nd.con = ""
        region.rooms[83].links.su = {}
          region.rooms[83].links.su.to = 1818
          region.rooms[83].links.su.con = ""
    region.rooms[84] = {}
      region.rooms[84].path = "fly wds;n;e;e;su;su;sd;su;su"
      region.rooms[84].name = "三老峰"
      region.rooms[84].zone = "武当山"
      region.rooms[84].id = 1818
      region.rooms[84].desc = "    只见三座奇峰突兀，惊险无比，行人多不敢放胆在此玩赏风景。"
      region.rooms[84].exits = "southup|northdown"
      region.rooms[84].links = {}
        region.rooms[84].links.nd = {}
          region.rooms[84].links.nd.to = 1817
          region.rooms[84].links.nd.con = ""
        region.rooms[84].links.su = {}
          region.rooms[84].links.su.to = 1819
          region.rooms[84].links.su.con = ""
    region.rooms[85] = {}
      region.rooms[85].path = "fly wds;n;e;e;su;su;sd;su;su;su"
      region.rooms[85].name = "五老峰"
      region.rooms[85].zone = "武当山"
      region.rooms[85].id = 1819
      region.rooms[85].desc = "    只见五座奇峰突兀，惊险无比，行人多不敢放胆在此玩赏风景。"
      region.rooms[85].exits = "southup|northdown"
      region.rooms[85].links = {}
        region.rooms[85].links.nd = {}
          region.rooms[85].links.nd.to = 1818
          region.rooms[85].links.nd.con = ""
        region.rooms[85].links.su = {}
          region.rooms[85].links.su.to = 1820
          region.rooms[85].links.su.con = ""
    region.rooms[86] = {}
      region.rooms[86].path = "fly wds;n;e;e;su;su;sd;su;su;su;su"
      region.rooms[86].name = "虎头岩"
      region.rooms[86].zone = "武当山"
      region.rooms[86].id = 1820
      region.rooms[86].desc = "    一块巨大的岩石看上去好象一个虎头正张大了血盆大口咆哮，虎身隐藏在草木丛中。"
      region.rooms[86].exits = "southup|northdown"
      region.rooms[86].links = {}
        region.rooms[86].links.nd = {}
          region.rooms[86].links.nd.to = 1819
          region.rooms[86].links.nd.con = ""
        region.rooms[86].links.su = {}
          region.rooms[86].links.su.to = 1821
          region.rooms[86].links.su.con = ""
    region.rooms[87] = {}
      region.rooms[87].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su"
      region.rooms[87].name = "朝天宫"
      region.rooms[87].zone = "武当山"
      region.rooms[87].id = 1821
      region.rooms[87].desc = "    这里已近武当绝顶，只见石梯直耸，危蹬高悬，两旁辅以索链、铁拦勾连。"
      region.rooms[87].exits = "south|northdown"
      region.rooms[87].links = {}
        region.rooms[87].links.s = {}
          region.rooms[87].links.s.to = 1822
          region.rooms[87].links.s.con = ""
        region.rooms[87].links.nd = {}
          region.rooms[87].links.nd.to = 1820
          region.rooms[87].links.nd.con = ""
    region.rooms[88] = {}
      region.rooms[88].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su;s"
      region.rooms[88].name = "会仙桥"
      region.rooms[88].zone = "武当山"
      region.rooms[88].id = 1822
      region.rooms[88].desc = "    这里地势稍平，一道山涧缓缓流过，一座窄窄的木桥横在涧上，只溶一人经过。"
      region.rooms[88].exits = "south|north"
      region.rooms[88].links = {}
        region.rooms[88].links.s = {}
          region.rooms[88].links.s.to = 1823
          region.rooms[88].links.s.con = ""
        region.rooms[88].links.n = {}
          region.rooms[88].links.n.to = 1821
          region.rooms[88].links.n.con = ""
    region.rooms[89] = {}
      region.rooms[89].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su;s;s"
      region.rooms[89].name = "头天门"
      region.rooms[89].zone = "武当山"
      region.rooms[89].id = 1823
      region.rooms[89].desc = "    只见有石梯无数通往山巅，一座石坊上写着“头天门”三个大字，这是攀登武当绝顶天柱峰的起点。"
      region.rooms[89].exits = "north|southup"
      region.rooms[89].links = {}
        region.rooms[89].links.n = {}
          region.rooms[89].links.n.to = 1822
          region.rooms[89].links.n.con = ""
        region.rooms[89].links.su = {}
          region.rooms[89].links.su.to = 1824
          region.rooms[89].links.su.con = ""
    region.rooms[90] = {}
      region.rooms[90].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su;s;s;su"
      region.rooms[90].name = "二天门"
      region.rooms[90].zone = "武当山"
      region.rooms[90].id = 1824
      region.rooms[90].desc = "    这里是“二天门”，金光灿灿的金顶就在眼前了。"
      region.rooms[90].exits = "southup|northdown"
      region.rooms[90].links = {}
        region.rooms[90].links.nd = {}
          region.rooms[90].links.nd.to = 1823
          region.rooms[90].links.nd.con = ""
        region.rooms[90].links.su = {}
          region.rooms[90].links.su.to = 1825
          region.rooms[90].links.su.con = ""
    region.rooms[91] = {}
      region.rooms[91].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su;s;s;su;su"
      region.rooms[91].name = "三天门"
      region.rooms[91].zone = "武当山"
      region.rooms[91].id = 1825
      region.rooms[91].desc = "    这里是登山石阶的尽头“三天门”，再往上走就是武当绝顶了。"
      region.rooms[91].exits = "southup|northdown"
      region.rooms[91].links = {}
        region.rooms[91].links.nd = {}
          region.rooms[91].links.nd.to = 1824
          region.rooms[91].links.nd.con = ""
        region.rooms[91].links.su = {}
          region.rooms[91].links.su.to = 1826
          region.rooms[91].links.su.con = ""
    region.rooms[92] = {}
      region.rooms[92].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su;s;s;su;su;su"
      region.rooms[92].name = "金顶"
      region.rooms[92].zone = "武当山"
      region.rooms[92].id = 1826
      region.rooms[92].desc = "    你感到寒意阵阵袭来，原来你已到了武当山的主峰天柱峰的绝顶。前面的金殿由铜铸成，镀以黄金，每当旭日临空，整个殿宇金光闪闪，故名金顶。天柱峰高高独立于群峰之上，东西壁立二山，名叫蜡烛峰，中壁立一山似香炉，名香炉峰，万山千壑，隐隐下伏。"
      region.rooms[92].exits = "south|northdown|west"
      region.rooms[92].links = {}
        region.rooms[92].links.nd = {}
          region.rooms[92].links.nd.to = 1825
          region.rooms[92].links.nd.con = ""
        region.rooms[92].links.s = {}
          region.rooms[92].links.s.to = 1828
          region.rooms[92].links.s.con = ""
        region.rooms[92].links.w = {}
          region.rooms[92].links.w.to = 1827
          region.rooms[92].links.w.con = ""
    region.rooms[93] = {}
      region.rooms[93].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su;s;s;su;su;su;w"
      region.rooms[93].name = "十二莲台"
      region.rooms[93].zone = "武当山"
      region.rooms[93].id = 1827
      region.rooms[93].desc = "    这里是武当绝顶的十二莲台，台与台之间以曲栏相连，雕刻精美，是远眺的最佳所在。站立此台四眺，宛如身在千叶宝莲之上，千峰万壑都在脚下。往西可望到七百里外的华山，东望则汉水如练，襄、樊一带尽收眼底。"
      region.rooms[93].exits = "east"
      region.rooms[93].links = {}
        region.rooms[93].links.e = {}
          region.rooms[93].links.e.to = 1826
          region.rooms[93].links.e.con = ""
    region.rooms[94] = {}
      region.rooms[94].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su;s;s;su;su;su;s"
      region.rooms[94].name = "紫金城"
      region.rooms[94].zone = "武当山"
      region.rooms[94].id = 1828
      region.rooms[94].desc = "    这是守护金殿的紫金城墙，周长三里，城墙由花岗石依山势砌成，东西北城门均面临绝壁，南门为上下路口，气势壮观。"
      region.rooms[94].exits = "south|north"
      region.rooms[94].links = {}
        region.rooms[94].links.s = {}
          region.rooms[94].links.s.to = 1829
          region.rooms[94].links.s.con = ""
        region.rooms[94].links.n = {}
          region.rooms[94].links.n.to = 1826
          region.rooms[94].links.n.con = ""
    region.rooms[95] = {}
      region.rooms[95].path = "fly wds;n;e;e;su;su;sd;su;su;su;su;su;s;s;su;su;su;s;s"
      region.rooms[95].name = "金殿"
      region.rooms[95].zone = "武当山"
      region.rooms[95].id = 1829
      region.rooms[95].desc = "    金殿中间供着真武大帝铜像，披发跣足，体态丰满；左右有金童玉女侍立，虔诚恭敬；水、火二将，威武庄严。殿前供器皆为铜铸。殿宇和殿内铜像、供桌铆焊一体，构件精确，技巧高超。"
      region.rooms[95].exits = "north"
      region.rooms[95].links = {}
        region.rooms[95].links.n = {}
          region.rooms[95].links.n.to = 1828
          region.rooms[95].links.n.con = ""
    region.rooms[96] = {}
      region.rooms[96].path = "fly wds;n;e;e;su;su;sd;wu;sd;enter;move xiang;d"
      region.rooms[96].name = "南岩宫地下室"
      region.rooms[96].zone = "武当山"
      region.rooms[96].id = 2105
      region.rooms[96].links = {}
        region.rooms[96].links.s = {}
          region.rooms[96].links.s.to = 2107
          region.rooms[96].links.s.con = ""
        region.rooms[96].links.u = {}
          region.rooms[96].links.u.to = 1815
          region.rooms[96].links.u.con = ""
        region.rooms[96].links.e = {}
          region.rooms[96].links.e.to = 2106
          region.rooms[96].links.e.con = ""
        region.rooms[96].links.w = {}
          region.rooms[96].links.w.to = 2108
          region.rooms[96].links.w.con = ""
        region.rooms[96].links.n = {}
          region.rooms[96].links.n.to = 2109
          region.rooms[96].links.n.con = ""
      region.rooms[96].exits = "up|south|north|east|west"
      region.rooms[96].desc = "    这是一个干燥洁净的地下室，四壁用光滑的大理石砌就，十数支松明照得这里通明透亮。"
    region.rooms[97] = {}
      region.rooms[97].path = "fly wds;n;e;e;su;su;sd;wu;sd;enter;move xiang;d;e"
      region.rooms[97].name = "南岩迷宫"
      region.rooms[97].zone = "武当山"
      region.rooms[97].id = 2106
      region.rooms[97].links = {}
        region.rooms[97].links.ne = {}
          region.rooms[97].links.ne.to = 2107
          region.rooms[97].links.ne.con = ""
        region.rooms[97].links.nw = {}
          region.rooms[97].links.nw.to = 2109
          region.rooms[97].links.nw.con = ""
        region.rooms[97].links.s = {}
          region.rooms[97].links.s.to = 2108
          region.rooms[97].links.s.con = ""
        region.rooms[97].links.se = {}
          region.rooms[97].links.se.to = 2105
          region.rooms[97].links.se.con = ""
        region.rooms[97].links.e = {}
          region.rooms[97].links.e.to = 2106
          region.rooms[97].links.e.con = ""
        region.rooms[97].links.sw = {}
          region.rooms[97].links.sw.to = 2108
          region.rooms[97].links.sw.con = ""
        region.rooms[97].links.w = {}
          region.rooms[97].links.w.to = 2107
          region.rooms[97].links.w.con = ""
        region.rooms[97].links.n = {}
          region.rooms[97].links.n.to = 2109
          region.rooms[97].links.n.con = ""
      region.rooms[97].exits = "north|southwest|south|northwest|east|southeast|northeast|west"
      region.rooms[97].desc = "    你现在南岩宫地下密室中，高挂的腕粗的油烛照得满堂透亮。但周围静谧如夜，除了烛火闪烁的风声外，你什么也听不见。这里只有你一个人。你脚下缓缓而动，全神戒备，没有人能帮助你。"
    region.rooms[98] = {}
      region.rooms[98].path = "fly wds;n;e;e;su;su;sd;wu;sd;enter;move xiang;d;s"
      region.rooms[98].name = "南岩迷宫"
      region.rooms[98].zone = "武当山"
      region.rooms[98].id = 2107
      region.rooms[98].links = {}
        region.rooms[98].links.ne = {}
          region.rooms[98].links.ne.to = 2105
          region.rooms[98].links.ne.con = ""
        region.rooms[98].links.nw = {}
          region.rooms[98].links.nw.to = 2109
          region.rooms[98].links.nw.con = ""
        region.rooms[98].links.s = {}
          region.rooms[98].links.s.to = 2108
          region.rooms[98].links.s.con = ""
        region.rooms[98].links.se = {}
          region.rooms[98].links.se.to = 2106
          region.rooms[98].links.se.con = ""
        region.rooms[98].links.e = {}
          region.rooms[98].links.e.to = 2106
          region.rooms[98].links.e.con = ""
        region.rooms[98].links.sw = {}
          region.rooms[98].links.sw.to = 2108
          region.rooms[98].links.sw.con = ""
        region.rooms[98].links.w = {}
          region.rooms[98].links.w.to = 2107
          region.rooms[98].links.w.con = ""
        region.rooms[98].links.n = {}
          region.rooms[98].links.n.to = 2105
          region.rooms[98].links.n.con = ""
      region.rooms[98].exits = "north|southwest|south|northwest|east|southeast|northeast|west"
      region.rooms[98].desc = "    你现在南岩宫地下密室中，高挂的腕粗的油烛照得满堂透亮。但周围静谧如夜，除了烛火闪烁的风声外，你什么也听不见。这里只有你一个人。你脚下缓缓而动，全神戒备，没有人能帮助你。"
    region.rooms[99] = {}
      region.rooms[99].path = "fly wds;n;e;e;su;su;sd;wu;sd;enter;move xiang;d;w"
      region.rooms[99].name = "南岩迷宫"
      region.rooms[99].zone = "武当山"
      region.rooms[99].id = 2108
      region.rooms[99].links = {}
        region.rooms[99].links.ne = {}
          region.rooms[99].links.ne.to = 2107
          region.rooms[99].links.ne.con = ""
        region.rooms[99].links.nw = {}
          region.rooms[99].links.nw.to = 2109
          region.rooms[99].links.nw.con = ""
        region.rooms[99].links.s = {}
          region.rooms[99].links.s.to = 2108
          region.rooms[99].links.s.con = ""
        region.rooms[99].links.se = {}
          region.rooms[99].links.se.to = 2106
          region.rooms[99].links.se.con = ""
        region.rooms[99].links.e = {}
          region.rooms[99].links.e.to = 2106
          region.rooms[99].links.e.con = ""
        region.rooms[99].links.sw = {}
          region.rooms[99].links.sw.to = 2105
          region.rooms[99].links.sw.con = ""
        region.rooms[99].links.w = {}
          region.rooms[99].links.w.to = 2107
          region.rooms[99].links.w.con = ""
        region.rooms[99].links.n = {}
          region.rooms[99].links.n.to = 2109
          region.rooms[99].links.n.con = ""
      region.rooms[99].exits = "north|southwest|south|northwest|east|southeast|northeast|west"
      region.rooms[99].desc = "    你现在南岩宫地下密室中，高挂的腕粗的油烛照得满堂透亮。但周围静谧如夜，除了烛火闪烁的风声外，你什么也听不见。这里只有你一个人。你脚下缓缓而动，全神戒备，没有人能帮助你。"
    region.rooms[100] = {}
      region.rooms[100].path = "fly wds;n;e;e;su;su;sd;wu;sd;enter;move xiang;d;n"
      region.rooms[100].name = "南岩迷宫"
      region.rooms[100].zone = "武当山"
      region.rooms[100].id = 2109
      region.rooms[100].links = {}
        region.rooms[100].links.ne = {}
          region.rooms[100].links.ne.to = 2107
          region.rooms[100].links.ne.con = ""
        region.rooms[100].links.nw = {}
          region.rooms[100].links.nw.to = 2105
          region.rooms[100].links.nw.con = ""
        region.rooms[100].links.s = {}
          region.rooms[100].links.s.to = 2108
          region.rooms[100].links.s.con = ""
        region.rooms[100].links.se = {}
          region.rooms[100].links.se.to = 2106
          region.rooms[100].links.se.con = ""
        region.rooms[100].links.e = {}
          region.rooms[100].links.e.to = 2106
          region.rooms[100].links.e.con = ""
        region.rooms[100].links.sw = {}
          region.rooms[100].links.sw.to = 2108
          region.rooms[100].links.sw.con = ""
        region.rooms[100].links.w = {}
          region.rooms[100].links.w.to = 2107
          region.rooms[100].links.w.con = ""
        region.rooms[100].links.n = {}
          region.rooms[100].links.n.to = 2109
          region.rooms[100].links.n.con = ""
      region.rooms[100].exits = "north|southwest|south|northwest|east|southeast|northeast|west"
      region.rooms[100].desc = "    你现在南岩宫地下密室中，高挂的腕粗的油烛照得满堂透亮。但周围静谧如夜，除了烛火闪烁的风声外，你什么也听不见。这里只有你一个人。你脚下缓缓而动，全神戒备，没有人能帮助你。"
    region.rooms[101] = {}
      region.rooms[101].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne;e;se;s"
      region.rooms[101].name = "荆州郊外"
      region.rooms[101].zone = "武当山|襄阳"
      region.rooms[101].id = 2979
      region.rooms[101].desc = "    这里是荆州郊外，四周静悄悄的。四周是浓密的树林，阴森森的十分怕人。北边是一条青石大道，东南边有一处废园。"
      region.rooms[101].exits = "north|southeast"
      region.rooms[101].links = {}
        region.rooms[101].links.n = {}
          region.rooms[101].links.n.to = 777
          region.rooms[101].links.n.con = ""
        region.rooms[101].links.se = {}
          region.rooms[101].links.se.to = 2980
          region.rooms[101].links.se.con = ""
    region.rooms[102] = {}
      region.rooms[102].path = "fly wds;n;nd;nd;nd;nd;nu;nd;nu;nd;nd;nd;nd;e;ed;ed;e;e;n;nw;e;ne;e;se;s;se"
      region.rooms[102].name = "废园"
      region.rooms[102].zone = "武当山|襄阳"
      region.rooms[102].id = 2980
      region.rooms[102].desc = "    荆州废园离万家不远。当日丁典逝世、杀周圻、杀耿天霸、杀马大鸣，都是在这废园之中，但此时，只见荒草如故，遍地瓦砾如故。院子里那株老梅之旁，一个土堆上也长满了荒草，如果不是旁边立着的石板刻着“义兄丁典、义嫂凌霜华之墓 狄云立”，任谁也想不到这就是丁典和凌小姐的衣冠冢之所在。"
      region.rooms[102].exits = "northwest"
      region.rooms[102].links = {}
        region.rooms[102].links.nw = {}
          region.rooms[102].links.nw.to = 2979
          region.rooms[102].links.nw.con = ""
  region.center = 1792
return region