local region = {}
  region.cmd = "fly ws"
  region.name = "华山"
  region.id = "ws"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;nd;nd;nw"
      region.rooms[1].name = "华山脚下"
      region.rooms[1].zone = "华山村|华山"
      region.rooms[1].id = 2348
      region.rooms[1].desc = "    西岳华山，巍然耸立于陕西省华阴县城南。它北瞰黄河，南连秦岭，五座山峰高低错落，各据一方，其间又有一段若断若续的山岭相连，疏密有度，神韵天成，远远望去，状若巨朵青莲，外围诸峰如莲瓣，中间三峰似莲蕊，因此山便因'花'得名，取名华山。又因其西临少华山，故华山又称太华。它素有「奇峰天下第一山」之称，西面是小村。北是玉泉院。"
      region.rooms[1].exits = "north|southeast|west"
      region.rooms[1].links = {}
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 2350
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 2349
          region.rooms[1].links.n.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;nd;nd;nw;n"
      region.rooms[2].name = "玉泉院"
      region.rooms[2].zone = "华山村|华山"
      region.rooms[2].id = 2349
      region.rooms[2].desc = "    这里因屋后的玉泉而得名，是宋代陈希夷隐居的地方。周围生着十二株大龙藤，夭矫多姿，枝干中空，就如飞龙相似，相传是希夷先生陈抟老祖所植。院内绿荫蔽日，泉石如画，流水萦回，回廊曲折。院中有清泉一股，泉水甘冽，传与山顶镇岳宫玉井相通，故名玉泉，玉泉院因此得名。"
      region.rooms[2].exits = "south"
      region.rooms[2].links = {}
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 2348
          region.rooms[2].links.s.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly ws"
      region.rooms[3].name = "玉女峰"
      region.rooms[3].zone = "华山"
      region.rooms[3].id = 2628
      region.rooms[3].desc = "    这里是华山的中峰，玉女峰。传说春秋时隐士萧史善吹洞箫，箫声引动了秦穆公女儿弄玉的爱慕，抛弃了宫廷生活，跟萧史来此隐居，故称玉女峰。这里地势略为平缓，不似其它四峰般险峻，江湖上赫赫有名的华山剑派就在此处。西边有所小小的庙宇，那就是玉女祠了。北面稀稀落落有十几间房子，是华山派的地方，闲杂游客最好别往那里去。"
      region.rooms[3].exits = "north|southdown|northeast|west|westdown"
      region.rooms[3].links = {}
        region.rooms[3].links.ne = {}
          region.rooms[3].links.ne.to = 2630
          region.rooms[3].links.ne.con = ""
        region.rooms[3].links.sd = {}
          region.rooms[3].links.sd.to = 2659
          region.rooms[3].links.sd.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 2629
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.wd = {}
          region.rooms[3].links.wd.to = 2666
          region.rooms[3].links.wd.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 2633
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly ws;w"
      region.rooms[4].name = "玉女祠"
      region.rooms[4].zone = "华山"
      region.rooms[4].id = 2629
      region.rooms[4].desc = "    玉女祠里供奉的到底是哪位玉女，有许多不同的说法，现在所能看到的只一尊呆板的石像。祠中大石上有一处深陷，凹处积水清碧，这是玉女的洗脸盆，碧水终年不干。"
      region.rooms[4].exits = "east"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 2628
          region.rooms[4].links.e.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly ws;ne"
      region.rooms[5].name = "小山路"
      region.rooms[5].zone = "华山"
      region.rooms[5].id = 2630
      region.rooms[5].desc = "    这里是华山的一条小山路，地势较为平缓，不似其它地方那么险峻。你走在这里，四周静悄悄的，你就象走进了一个世外桃源。"
      region.rooms[5].exits = "northeast|southwest"
      region.rooms[5].links = {}
        region.rooms[5].links.ne = {}
          region.rooms[5].links.ne.to = 2631
          region.rooms[5].links.ne.con = ""
        region.rooms[5].links.sw = {}
          region.rooms[5].links.sw.to = 2628
          region.rooms[5].links.sw.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly ws;ne;ne"
      region.rooms[6].name = "小山路"
      region.rooms[6].zone = "华山"
      region.rooms[6].id = 2631
      region.rooms[6].desc = "    这里是华山的一条小山路，地势较为平缓，不似其它地方那么险峻。你走在这里，四周静悄悄的，你就象走进了一个世外桃源。东面好象有一扇竹门(men)。"
      region.rooms[6].exits = "southwest"
      region.rooms[6].links = {}
        region.rooms[6].links["push men;e"] = {}
          region.rooms[6].links["push men;e"].to = 2632
          region.rooms[6].links["push men;e"].con = ""
        region.rooms[6].links.sw = {}
          region.rooms[6].links.sw.to = 2630
          region.rooms[6].links.sw.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly ws;ne;ne;push men;e"
      region.rooms[7].name = "华山小筑"
      region.rooms[7].zone = "华山"
      region.rooms[7].id = 2632
      region.rooms[7].desc = "    这是间整洁的厢房，因门窗常闭着，光线很昏暗。房里别无他物，只有中间放着一张收拾得舒舒服服的大床，看着就让人想睡觉。"
      region.rooms[7].exits = "west"
      region.rooms[7].links = {}
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 2631
          region.rooms[7].links.w.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly ws;n"
      region.rooms[8].name = "练武场"
      region.rooms[8].zone = "华山"
      region.rooms[8].id = 2633
      region.rooms[8].desc = "    这里是华山派的练武场，场上立这几个木人，东边是兵器库，西边是个小店。通常有许多华山派弟子在此习武练剑。北边的房屋门上挂着一块匾，上书「群仙观」，西北方似乎有条小道通往山上。"
      region.rooms[8].exits = "south|east|north|northwest|west"
      region.rooms[8].links = {}
        region.rooms[8].links.nw = {}
          region.rooms[8].links.nw.to = 2651
          region.rooms[8].links.nw.con = ""
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 2634
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 2628
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 2635
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly ws;n;w"
      region.rooms[9].name = "山顶小店"
      region.rooms[9].zone = "华山"
      region.rooms[9].id = 2634
      region.rooms[9].desc = "    这里是华山山顶的一间小店，卖些简单的饮食，专门赚那些游客的钱。"
      region.rooms[9].exits = "east"
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 2633
          region.rooms[9].links.e.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly ws;n;n"
      region.rooms[10].name = "群仙观"
      region.rooms[10].zone = "华山"
      region.rooms[10].id = 2635
      region.rooms[10].desc = "    这里是华山派历来之根本重地，墙上挂着华山派历代掌门人的画像，华山派一切重大礼仪都在这里举行。这里也是华山弟子讲武习剑之地。北边就是华山掌门岳不群的居所「有所不为轩」。"
      region.rooms[10].exits = "south|north"
      region.rooms[10].links = {}
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 2633
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 2636
          region.rooms[10].links.n.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly ws;n;n;n"
      region.rooms[11].name = "有所不为轩"
      region.rooms[11].zone = "华山"
      region.rooms[11].id = 2636
      region.rooms[11].desc = "    这是华山掌门岳不群的居所「有所不为轩」，此处是前厅，厅上挂着「正气堂」三字匾额。厅中很宽敞，却没什么摆设，靠墙放着两把交椅，这里是岳不群议事、授徒的地方，后面是寝室。"
      region.rooms[11].exits = "south|east|north|west"
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 2637
          region.rooms[11].links.e.con = ""
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 2635
          region.rooms[11].links.s.con = ""
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 2639
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 2638
          region.rooms[11].links.n.con = "k1:陆大有"
    region.rooms[12] = {}
      region.rooms[12].path = "fly ws;n;n;n;e"
      region.rooms[12].name = "偏厅"
      region.rooms[12].zone = "华山"
      region.rooms[12].id = 2637
      region.rooms[12].desc = "    偏厅里供奉着华山历代祖师的神位。正中神案的墙上是华山派开山祖师风祖师的画象。画象神情清隽，非常传神。神案上香炉里插着三柱清香，香烟袅袅上升，散发着一股檀香味。西面有扇门通往外面的正厅。"
      region.rooms[12].exits = "west"
      region.rooms[12].links = {}
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 2636
          region.rooms[12].links.w.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly ws;n;n;n;|!k1:陆大有:n|"
      region.rooms[13].name = "寝室"
      region.rooms[13].zone = "华山"
      region.rooms[13].id = 2638
      region.rooms[13].desc = "    这里是岳不群的寝室，岳不群在江湖上人称「君子剑」，他虽为一大派掌门，可他的卧室却布置的很简单。除了一张床，几只箱子，墙角有张化妆台，只有靠墙一张红木书桌(desk)还显得略有气派。"
      region.rooms[13].exits = "south"
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 2636
          region.rooms[13].links.s.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly ws;n;n;n;w"
      region.rooms[14].name = "花园"
      region.rooms[14].zone = "华山"
      region.rooms[14].id = 2639
      region.rooms[14].desc = "    这是一个园子，庭院清幽，异种花卉甚是不少。百花争放，山石古拙，杨柳垂清，苍松翠竹，景致煞是宜人。清澈的溪流旁耸立着一座小亭子，潺潺溪水向西南流去。东面通往有所不为轩，北面是一条长廊，西边小屋传出阵阵香味，引得你真想去看看。"
      region.rooms[14].exits = "south|north|east|west|southwest"
      region.rooms[14].links = {}
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 2641
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 2636
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.sw = {}
          region.rooms[14].links.sw.to = 2642
          region.rooms[14].links.sw.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 2640
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 2645
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly ws;n;n;n;w;w"
      region.rooms[15].name = "厨房"
      region.rooms[15].zone = "华山"
      region.rooms[15].id = 2640
      region.rooms[15].desc = "    这是华山派的厨房，一位华山小师妹正在烧饭。整个房间弥漫着饭菜香。你可以向小师妹要(serve) 些吃的喝的。墙上贴着一张启事(note)。"
      region.rooms[15].exits = "east"
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 2639
          region.rooms[15].links.e.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly ws;n;n;n;w;s"
      region.rooms[16].name = "华山书房"
      region.rooms[16].zone = "华山"
      region.rooms[16].id = 2641
      region.rooms[16].desc = "    这里是华山派的书房，靠墙是一排书架，里面堆着乱七八糟的一大堆书，最近老有人上山寻事，都很久没人整理书房了，要找啥书都很麻烦。右侧有张书桌，桌上四宝俱备。"
      region.rooms[16].exits = "north"
      region.rooms[16].links = {}
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 2639
          region.rooms[16].links.n.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly ws;n;n;n;w;sw"
      region.rooms[17].name = "后院"
      region.rooms[17].zone = "华山"
      region.rooms[17].id = 2642
      region.rooms[17].desc = "    这里是华山派的后院，里面是华山弟子的居室和练功房。华山派总所倚山而建，地势险峻，往东便是悬崖。西面是另一个小花院，有假山小池，景色怡人，颇有江南林园的特色。"
      region.rooms[17].exits = "east|northeast|west"
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 2643
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 2644
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.ne = {}
          region.rooms[17].links.ne.to = 2639
          region.rooms[17].links.ne.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly ws;n;n;n;w;sw;e"
      region.rooms[18].name = "悬崖"
      region.rooms[18].zone = "华山"
      region.rooms[18].id = 2643
      region.rooms[18].desc = "    这是华山上悬崖上的一片平台，地势险恶。平台旁便是万丈深渊，低头望下，只见一天云海。华山弟子多在此练剑打坐，借天时地势，勤练武功。平时华山掌门也在此指点及考教门下弟子。"
      region.rooms[18].exits = "west"
      region.rooms[18].links = {}
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 2642
          region.rooms[18].links.w.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly ws;n;n;n;w;sw;w"
      region.rooms[19].name = "假山小池"
      region.rooms[19].zone = "华山"
      region.rooms[19].id = 2644
      region.rooms[19].desc = "    这是另一个小园子，里头有个小池塘。四周布有假山，增添林园美景。下雨时雨水落入溪塘中，清脆的水珠声有如玉珠落盘般悦耳。水气朦胧中抬头西望，只见远处苍山如黛，若隐若现，雨景妙趣无穷。"
      region.rooms[19].exits = "east"
      region.rooms[19].links = {}
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 2642
          region.rooms[19].links.e.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly ws;n;n;n;w;n"
      region.rooms[20].name = "长廊"
      region.rooms[20].zone = "华山"
      region.rooms[20].id = 2645
      region.rooms[20].desc = "    你走在长廊上只见红栏碧瓦，雕梁画栋，廊外风吹翠竹，细吟阵阵，看来华山派气派果然不凡。西面是岳夫人的居室。"
      region.rooms[20].exits = "south|north|west"
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 2639
          region.rooms[20].links.s.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 2646
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 2647
          region.rooms[20].links.n.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly ws;n;n;n;w;n;w"
      region.rooms[21].name = "居室"
      region.rooms[21].zone = "华山"
      region.rooms[21].id = 2646
      region.rooms[21].desc = "    这里是岳夫人的寝室，岳夫人在江湖上人称「淑女剑」，为人极有骨气，她的居室却相当朴素，床椅之外，靠窗(window)处有个梳妆台(tai)，墙上挂着一口宝剑(sword)， 蛇皮吞口看来很是锋利。"
      region.rooms[21].exits = "east"
      region.rooms[21].links = {}
        region.rooms[21].links.e = {}
          region.rooms[21].links.e.to = 2645
          region.rooms[21].links.e.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly ws;n;n;n;w;n;n"
      region.rooms[22].name = "松树林"
      region.rooms[22].zone = "华山"
      region.rooms[22].id = 2647
      region.rooms[22].desc = "    这是一片松树林。几丈高的松树密密麻麻，遮得不见天日。地上落满松针，有不知名的野兔偷偷逃过。四周一片寂静。"
      region.rooms[22].exits = "south|east|north|west"
      region.rooms[22].links = {}
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 2650
          region.rooms[22].links.e.con = ""
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 2645
          region.rooms[22].links.s.con = ""
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 2649
          region.rooms[22].links.w.con = ""
        region.rooms[22].links.n = {}
          region.rooms[22].links.n.to = 2648
          region.rooms[22].links.n.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly ws;n;n;n;w;n;n;n"
      region.rooms[23].name = "松树林"
      region.rooms[23].zone = "华山"
      region.rooms[23].id = 2648
      region.rooms[23].desc = "    这是一片松树林。几丈高的松树密密麻麻，遮得不见天日。地上落满松针，有不知名的野兔偷偷逃过。四周一片寂静。"
      region.rooms[23].exits = "south|east|north|west"
      region.rooms[23].links = {}
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 2649
          region.rooms[23].links.e.con = ""
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 2649
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 2650
          region.rooms[23].links.s.con = ""
        region.rooms[23].links.n = {}
          region.rooms[23].links.n.to = 2649
          region.rooms[23].links.n.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly ws;n;n;n;w;n;n;w"
      region.rooms[24].name = "松树林"
      region.rooms[24].zone = "华山"
      region.rooms[24].id = 2649
      region.rooms[24].desc = "    这是一片松树林。几丈高的松树密密麻麻，遮得不见天日。地上落满松针，有不知名的野兔偷偷逃过。四周一片寂静。"
      region.rooms[24].exits = "south|east|north|west"
      region.rooms[24].links = {}
        region.rooms[24].links.e = {}
          region.rooms[24].links.e.to = 2650
          region.rooms[24].links.e.con = ""
        region.rooms[24].links.s = {}
          region.rooms[24].links.s.to = 2648
          region.rooms[24].links.s.con = ""
        region.rooms[24].links.w = {}
          region.rooms[24].links.w.to = 2650
          region.rooms[24].links.w.con = ""
        region.rooms[24].links.n = {}
          region.rooms[24].links.n.to = 2650
          region.rooms[24].links.n.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly ws;n;n;n;w;n;n;e"
      region.rooms[25].name = "松树林"
      region.rooms[25].zone = "华山"
      region.rooms[25].id = 2650
      region.rooms[25].desc = "    这是一片松树林。几丈高的松树密密麻麻，遮得不见天日。地上落满松针，有不知名的野兔偷偷逃过。四周一片寂静。"
      region.rooms[25].exits = "south|east|north|west"
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 2647
          region.rooms[25].links.e.con = ""
        region.rooms[25].links.s = {}
          region.rooms[25].links.s.to = 2649
          region.rooms[25].links.s.con = ""
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 2649
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 2650
          region.rooms[25].links.n.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly ws;n;nw"
      region.rooms[26].name = "朝阳峰小路"
      region.rooms[26].zone = "华山"
      region.rooms[26].id = 2651
      region.rooms[26].desc = "    这里是朝阳峰小路，山势陡峭，两边下临深谷，一不小心都会掉了下去。"
      region.rooms[26].exits = "southeast|northeast"
      region.rooms[26].links = {}
        region.rooms[26].links.ne = {}
          region.rooms[26].links.ne.to = 2652
          region.rooms[26].links.ne.con = ""
        region.rooms[26].links.se = {}
          region.rooms[26].links.se.to = 2633
          region.rooms[26].links.se.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly ws;n;nw;ne"
      region.rooms[27].name = "朝阳峰小路"
      region.rooms[27].zone = "华山"
      region.rooms[27].id = 2652
      region.rooms[27].desc = "    这里是朝阳峰小路，山势陡峭，两边下临深谷，一不小心都会掉了下去。西面有一条小路，长草没径。"
      region.rooms[27].exits = "westup|eastup|southwest"
      region.rooms[27].links = {}
        region.rooms[27].links.sw = {}
          region.rooms[27].links.sw.to = 2651
          region.rooms[27].links.sw.con = ""
        region.rooms[27].links.eu = {}
          region.rooms[27].links.eu.to = 2653
          region.rooms[27].links.eu.con = "k1:施戴子"
        region.rooms[27].links.wu = {}
          region.rooms[27].links.wu.to = 2654
          region.rooms[27].links.wu.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly ws;n;nw;ne;|!k1:施戴子:eu|"
      region.rooms[28].name = "朝阳峰"
      region.rooms[28].zone = "华山"
      region.rooms[28].id = 2653
      region.rooms[28].desc = "    这里就是华山的东峰，也称朝阳峰，是华山看日出的绝佳处。於此俯瞰，黄河隐显东迤如带，南望小孤峰背倚山河。小孤峰上有一小亭，覆以铁瓦，亭中有铁棋盘一局，那就是华山著名的“博台”了。东壁悬崖上，更有一个巨型掌印，相传为「河神巨灵」劈山时所留下的，李白诗中“巨灵咆哮劈两山，洪波喷流射东海”就是指这个上古传说。"
      region.rooms[28].exits = "westdown"
      region.rooms[28].links = {}
        region.rooms[28].links.wd = {}
          region.rooms[28].links.wd.to = 2652
          region.rooms[28].links.wd.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly ws;n;nw;ne;wu"
      region.rooms[29].name = "紫气台"
      region.rooms[29].zone = "华山"
      region.rooms[29].id = 2654
      region.rooms[29].desc = "    紫气台终年云遮雾掩，迷蒙不见天日，更为怪异的是：没逢下雨天，山谷之中就隐隐有紫气出现。"
      region.rooms[29].exits = "eastdown|down"
      region.rooms[29].links = {}
        region.rooms[29].links.ed = {}
          region.rooms[29].links.ed.to = 2652
          region.rooms[29].links.ed.con = ""
        region.rooms[29].links.d = {}
          region.rooms[29].links.d.to = 2655
          region.rooms[29].links.d.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly ws;n;nw;ne;wu;d"
      region.rooms[30].name = "山壁"
      region.rooms[30].zone = "华山"
      region.rooms[30].id = 2655
      region.rooms[30].desc = "    这里是华山绝壁上的山壁。山壁似乎有个山洞(dong)。你向下一望，只见脚下雾气一团团的随风飘过，绝峰险岭，却不看见地。转头向洞里张望，黑沉沉的看不清楚，只觉得洞穴很深。洞口甚小，那是钻不进去。"
      region.rooms[30].exits = "up"
      region.rooms[30].links = {}
        region.rooms[30].links.u = {}
          region.rooms[30].links.u.to = 2654
          region.rooms[30].links.u.con = ""
        region.rooms[30].links["break dong;enter"] = {}
          region.rooms[30].links["break dong;enter"].to = 2656
          region.rooms[30].links["break dong;enter"].con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly ws;n;nw;ne;wu;d;break dong;enter"
      region.rooms[31].name = "甬道"
      region.rooms[31].zone = "华山"
      region.rooms[31].id = 2656
      region.rooms[31].desc = "    你慢慢爬了进去，见是这里是一条狭窄的天生甬道，其实是山腹内的一条裂缝，爬了十多丈远，甬道渐高，再前进丈余，已可站直。你挺一挺腰，向前走去。"
      region.rooms[31].exits = "east|out"
      region.rooms[31].links = {}
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 2657
          region.rooms[31].links.e.con = ""
        region.rooms[31].links.out = {}
          region.rooms[31].links.out.to = 2655
          region.rooms[31].links.out.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly ws;n;nw;ne;wu;d;break dong;enter;e"
      region.rooms[32].name = "甬道"
      region.rooms[32].zone = "华山"
      region.rooms[32].id = 2657
      region.rooms[32].desc = "    甬道忽然转弯，走了两三丈远，前面豁然空阔，出现一个洞穴，便如是座石室。"
      region.rooms[32].exits = "north|west"
      region.rooms[32].links = {}
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 2656
          region.rooms[32].links.w.con = ""
        region.rooms[32].links.n = {}
          region.rooms[32].links.n.to = 2658
          region.rooms[32].links.n.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly ws;n;nw;ne;wu;d;break dong;enter;e;n"
      region.rooms[33].name = "山洞"
      region.rooms[33].zone = "华山"
      region.rooms[33].id = 2658
      region.rooms[33].desc = "    对面石壁上斜倚着一副骷髅骨，身上衣服已烂了七八成，那骷髅骨宛然尚可见到是个人形。见石室中别无其他可怖事物。骷髅前面横七竖八的放着十几把金蛇锥，石壁上有几百幅用利器刻成的简陋人形(map) 。图形尽处，石壁上出现了十六个字(word)，也是以利器所刻。十六字之旁，有个剑柄凸出在石壁之上，似是一把剑插入了石壁，直至剑柄。"
      region.rooms[33].exits = "south"
      region.rooms[33].links = {}
        region.rooms[33].links.s = {}
          region.rooms[33].links.s.to = 2657
          region.rooms[33].links.s.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly ws;sd"
      region.rooms[34].name = "玉女峰山路"
      region.rooms[34].zone = "华山"
      region.rooms[34].id = 2659
      region.rooms[34].desc = "    这里是玉女峰后山的一条山路。路边长满了翠竹，每当微风拂过，竹叶便沙沙作响，显得分外的幽静。"
      region.rooms[34].exits = "northup|southup"
      region.rooms[34].links = {}
        region.rooms[34].links.nu = {}
          region.rooms[34].links.nu.to = 2628
          region.rooms[34].links.nu.con = ""
        region.rooms[34].links.su = {}
          region.rooms[34].links.su.to = 2660
          region.rooms[34].links.su.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly ws;sd;su"
      region.rooms[35].name = "玉女峰山路"
      region.rooms[35].zone = "华山"
      region.rooms[35].id = 2660
      region.rooms[35].desc = "    这里是玉女峰后山的一条山路。路边长满了翠竹，每当微风拂过，竹叶便沙沙作响，显得分外的幽静。"
      region.rooms[35].exits = "northdown|southup"
      region.rooms[35].links = {}
        region.rooms[35].links.nd = {}
          region.rooms[35].links.nd.to = 2659
          region.rooms[35].links.nd.con = ""
        region.rooms[35].links.su = {}
          region.rooms[35].links.su.to = 2661
          region.rooms[35].links.su.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly ws;sd;su;su"
      region.rooms[36].name = "思过崖"
      region.rooms[36].zone = "华山"
      region.rooms[36].id = 2661
      region.rooms[36].desc = "    这是华山的思过崖。危崖上有个山洞，是华山派历代弟子犯规后囚禁受罚之所。崖上光秃秃的寸草不生，更无一株树木。这危崖自来自来相传是玉女发钗上的一颗珍珠，当年华山派的祖师以此危崖为惩罚弟子之所，主要是此处无草无木，无虫无鸟，受罚的弟子在面壁思过之时，不致为外物所扰，心有旁鹜。"
      region.rooms[36].exits = "enter|northdown"
      region.rooms[36].links = {}
        region.rooms[36].links.enter = {}
          region.rooms[36].links.enter.to = 2662
          region.rooms[36].links.enter.con = ""
        region.rooms[36].links.nd = {}
          region.rooms[36].links.nd.to = 2660
          region.rooms[36].links.nd.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly ws;sd;su;su;enter"
      region.rooms[37].name = "山洞"
      region.rooms[37].zone = "华山"
      region.rooms[37].id = 2662
      region.rooms[37].desc = "    山洞内有块光溜溜的大石，不知道曾有多少华山派的前辈在此思过面壁，以致这块大石竟被坐得滑溜。石壁(wall)左侧刻着「风清扬」三个大字，是以利器所刻，笔划苍劲，深有半寸。这三字刻得劲力非凡，想必其人武功一定十分了得。"
      region.rooms[37].exits = "out"
      region.rooms[37].links = {}
        region.rooms[37].links.enter = {}
          region.rooms[37].links.enter.con = "hsbreak:"
          region.rooms[37].links.enter.to = 2663
          region.rooms[37].links.enter.block = "y"
        region.rooms[37].links.out = {}
          region.rooms[37].links.out.to = 2661
          region.rooms[37].links.out.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly ws;sd;su;su;enter;|!hsbreak::enter|"
      region.rooms[38].name = "密洞"
      region.rooms[38].zone = "华山"
      region.rooms[38].id = 2663
      region.rooms[38].desc = "    这是一个毫不起眼的山洞，但是里面的石壁上却画满了五岳剑派所有已经失传的精妙绝招。花岗岩石壁(wall)上很多小人，全是用利器刻制，想见当初运力之人内力十分深厚。"
      region.rooms[38].exits = "westup|out"
      region.rooms[38].links = {}
        region.rooms[38].links.out = {}
          region.rooms[38].links.out.to = 2662
          region.rooms[38].links.out.con = ""
        region.rooms[38].links.wu = {}
          region.rooms[38].links.wu.to = 2664
          region.rooms[38].links.wu.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly ws;sd;su;su;enter;|!hsbreak::enter|;wu"
      region.rooms[39].name = "长空栈道"
      region.rooms[39].zone = "华山"
      region.rooms[39].id = 2664
      region.rooms[39].desc = "    栈道以铁斜插，上覆青石板，宽不足八寸。上乃绝壁，下亦绝壁。挽索登其上，只听山风呼啸，林涛怒吼。远处偶传一两声禽鸣兽嘶，更使人毛骨悚然。踏上悬空的栈道，紧攀铁索，屏息静气，缓步挪动，才能过去。"
      region.rooms[39].exits = "westup|eastdown"
      region.rooms[39].links = {}
        region.rooms[39].links.ed = {}
          region.rooms[39].links.ed.to = 2663
          region.rooms[39].links.ed.con = ""
        region.rooms[39].links.wu = {}
          region.rooms[39].links.wu.to = 2665
          region.rooms[39].links.wu.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly ws;sd;su;su;enter;|!hsbreak::enter|;wu;wu"
      region.rooms[40].name = "落雁峰"
      region.rooms[40].zone = "华山"
      region.rooms[40].id = 2665
      region.rooms[40].desc = "    南峰又名落雁峰，是华山最高峰。峰头题刻极多，如“太华峰头”、“竣极于天”、“袖拂天星”等，极言华岳之高。环顾四周，皆在足下。寇准诗赞曰：只有天在上，更无山与齐；举头红日近，回首白云低。传说五代时候的隐士陈抟就隐居在这里。宋太祖曾经下诏征他出山作官，他便在这里写下谢诏表说：“一片野心都被白云锁住，九重宠诏休教丹凤衔来”，表示不愿出山做官。"
      region.rooms[40].exits = "eastdown"
      region.rooms[40].links = {}
        region.rooms[40].links.ed = {}
          region.rooms[40].links.ed.to = 2664
          region.rooms[40].links.ed.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly ws;wd"
      region.rooms[41].name = "镇岳宫"
      region.rooms[41].zone = "华山"
      region.rooms[41].id = 2666
      region.rooms[41].desc = "    镇岳宫倚壁而构，四边松林蔽日，景色幽美。宫前有玉井(jing)，相传井中曾生千叶白莲。这里地势略为平坦，上、下山的游客多在此稍作休息再继续前行。附近有几间简陋的旅社，欲登东峰观日出者，大都于头晚歇息于此。"
      region.rooms[41].exits = "eastup|northdown|southwest"
      region.rooms[41].links = {}
        region.rooms[41].links.eu = {}
          region.rooms[41].links.eu.to = 2628
          region.rooms[41].links.eu.con = "k1:高根明"
        region.rooms[41].links.sw = {}
          region.rooms[41].links.sw.to = 2667
          region.rooms[41].links.sw.con = ""
        region.rooms[41].links.nd = {}
          region.rooms[41].links.nd.to = 2675
          region.rooms[41].links.nd.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly ws;wd;sw"
      region.rooms[42].name = "莲花峰小路"
      region.rooms[42].zone = "华山"
      region.rooms[42].id = 2667
      region.rooms[42].desc = "    小路通往莲花峰，周围静静悄悄，微闻蝉鸣。四望密林幽谷，让人胆寒。"
      region.rooms[42].exits = "westup|northeast"
      region.rooms[42].links = {}
        region.rooms[42].links.ne = {}
          region.rooms[42].links.ne.to = 2666
          region.rooms[42].links.ne.con = ""
        region.rooms[42].links.wu = {}
          region.rooms[42].links.wu.to = 2668
          region.rooms[42].links.wu.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly ws;wd;sw;wu"
      region.rooms[43].name = "莲花峰小路"
      region.rooms[43].zone = "华山"
      region.rooms[43].id = 2668
      region.rooms[43].desc = "    小路通往莲花峰，周围静静悄悄，微闻蝉鸣。四望密林幽谷，让人胆寒。"
      region.rooms[43].exits = "westup|eastdown"
      region.rooms[43].links = {}
        region.rooms[43].links.ed = {}
          region.rooms[43].links.ed.to = 2667
          region.rooms[43].links.ed.con = ""
        region.rooms[43].links.wu = {}
          region.rooms[43].links.wu.to = 2669
          region.rooms[43].links.wu.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly ws;wd;sw;wu;wu"
      region.rooms[44].name = "沉香劈山处"
      region.rooms[44].zone = "华山"
      region.rooms[44].id = 2669
      region.rooms[44].desc = "    传说华山三圣母爱上了一个叫刘彦昌的书生，结为夫妇，其兄二郎神反对他们结合，将她压在华山下，她的儿子沉香长大后用斧子劈开华山，救出了母亲。旁边有一块中间裂开的大石，象用斧子劈开的一般，叫做斧劈石。传说就是沉香劈山救母的地方。"
      region.rooms[44].exits = "westup|eastdown"
      region.rooms[44].links = {}
        region.rooms[44].links.ed = {}
          region.rooms[44].links.ed.to = 2668
          region.rooms[44].links.ed.con = ""
        region.rooms[44].links.wu = {}
          region.rooms[44].links.wu.to = 2670
          region.rooms[44].links.wu.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly ws;wd;sw;wu;wu;wu"
      region.rooms[45].name = "莲花峰顶"
      region.rooms[45].zone = "华山"
      region.rooms[45].id = 2670
      region.rooms[45].desc = "    太华西峰－又名莲花峰，也叫芙蓉峰，峰顶有一块巨石，状如莲花，覆盖崖巅。该处由此得名。这里悬崖陡峭，壁立千仞，登临远眺，秦川莽莽，渭、洛二水盘屈如带。峰顶有石名“摘星石”，取“手可摘星辰”之意，以状西峰之高。"
      region.rooms[45].exits = "south|north|east|eastdown|west"
      region.rooms[45].links = {}
        region.rooms[45].links.ed = {}
          region.rooms[45].links.ed.to = 2669
          region.rooms[45].links.ed.con = ""
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 2672
          region.rooms[45].links.s.con = ""
        region.rooms[45].links.e = {}
          region.rooms[45].links.e.to = 2674
          region.rooms[45].links.e.con = ""
        region.rooms[45].links.w = {}
          region.rooms[45].links.w.to = 2673
          region.rooms[45].links.w.con = ""
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 2671
          region.rooms[45].links.n.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly ws;wd;sw;wu;wu;wu;n"
      region.rooms[46].name = "莲花峰顶"
      region.rooms[46].zone = "华山"
      region.rooms[46].id = 2671
      region.rooms[46].desc = "    太华西峰－又名莲花峰，也叫芙蓉峰，峰顶有一块巨石，状如莲花，覆盖崖巅。该处由此得名。这里悬崖陡峭，壁立千仞，登临远眺，秦川莽莽，渭、洛二水盘屈如带。峰顶有石名“摘星石”，取“手可摘星辰”之意，以状西峰之高。"
      region.rooms[46].exits = "south|southeast|southwest"
      region.rooms[46].links = {}
        region.rooms[46].links.sw = {}
          region.rooms[46].links.sw.to = 2673
          region.rooms[46].links.sw.con = ""
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 2670
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.se = {}
          region.rooms[46].links.se.to = 2674
          region.rooms[46].links.se.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly ws;wd;sw;wu;wu;wu;s"
      region.rooms[47].name = "莲花峰顶"
      region.rooms[47].zone = "华山"
      region.rooms[47].id = 2672
      region.rooms[47].desc = "    太华西峰－又名莲花峰，也叫芙蓉峰，峰顶有一块巨石，状如莲花，覆盖崖巅。该处由此得名。这里悬崖陡峭，壁立千仞，登临远眺，秦川莽莽，渭、洛二水盘屈如带。峰顶有石名“摘星石”，取“手可摘星辰”之意，以状西峰之高。"
      region.rooms[47].exits = "northwest|north|northeast"
      region.rooms[47].links = {}
        region.rooms[47].links.ne = {}
          region.rooms[47].links.ne.to = 2674
          region.rooms[47].links.ne.con = ""
        region.rooms[47].links.nw = {}
          region.rooms[47].links.nw.to = 2673
          region.rooms[47].links.nw.con = ""
        region.rooms[47].links.n = {}
          region.rooms[47].links.n.to = 2670
          region.rooms[47].links.n.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "fly ws;wd;sw;wu;wu;wu;w"
      region.rooms[48].name = "莲花峰顶"
      region.rooms[48].zone = "华山"
      region.rooms[48].id = 2673
      region.rooms[48].desc = "    太华西峰－又名莲花峰，也叫芙蓉峰，峰顶有一块巨石，状如莲花，覆盖崖巅。该处由此得名。这里悬崖陡峭，壁立千仞，登临远眺，秦川莽莽，渭、洛二水盘屈如带。峰顶有石名“摘星石”，取“手可摘星辰”之意，以状西峰之高。"
      region.rooms[48].exits = "east|southeast|northeast"
      region.rooms[48].links = {}
        region.rooms[48].links.ne = {}
          region.rooms[48].links.ne.to = 2671
          region.rooms[48].links.ne.con = ""
        region.rooms[48].links.e = {}
          region.rooms[48].links.e.to = 2670
          region.rooms[48].links.e.con = ""
        region.rooms[48].links.se = {}
          region.rooms[48].links.se.to = 2672
          region.rooms[48].links.se.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly ws;wd;sw;wu;wu;wu;e"
      region.rooms[49].name = "莲花峰顶"
      region.rooms[49].zone = "华山"
      region.rooms[49].id = 2674
      region.rooms[49].desc = "    太华西峰－又名莲花峰，也叫芙蓉峰，峰顶有一块巨石，状如莲花，覆盖崖巅。该处由此得名。这里悬崖陡峭，壁立千仞，登临远眺，秦川莽莽，渭、洛二水盘屈如带。峰顶有石名“摘星石”，取“手可摘星辰”之意，以状西峰之高。"
      region.rooms[49].exits = "northwest|west|southwest"
      region.rooms[49].links = {}
        region.rooms[49].links.sw = {}
          region.rooms[49].links.sw.to = 2672
          region.rooms[49].links.sw.con = ""
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 2670
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.nw = {}
          region.rooms[49].links.nw.to = 2671
          region.rooms[49].links.nw.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly ws;wd;nd"
      region.rooms[50].name = "金锁关"
      region.rooms[50].zone = "华山"
      region.rooms[50].id = 2675
      region.rooms[50].desc = "    金锁关山势形如一把锁，下面是一片开阔地，两旁是高耸入云的峭壁，中间一条羊肠小道。真是一夫当关，万夫莫开。"
      region.rooms[50].exits = "northdown|southup"
      region.rooms[50].links = {}
        region.rooms[50].links.su = {}
          region.rooms[50].links.su.to = 2666
          region.rooms[50].links.su.con = ""
        region.rooms[50].links.nd = {}
          region.rooms[50].links.nd.to = 2676
          region.rooms[50].links.nd.con = ""
    region.rooms[51] = {}
      region.rooms[51].path = "fly ws;wd;nd;nd"
      region.rooms[51].name = "上天梯"
      region.rooms[51].zone = "华山"
      region.rooms[51].id = 2676
      region.rooms[51].desc = "    此处绝险，必须面壁挽索，贴身探足前进，步不登高，故名\"上天梯\"。北面是下山的路，往南面是金锁关。西面上去可以通达北峰云台峰。"
      region.rooms[51].exits = "westup|northdown|southup"
      region.rooms[51].links = {}
        region.rooms[51].links.nd = {}
          region.rooms[51].links.nd.to = 2681
          region.rooms[51].links.nd.con = ""
        region.rooms[51].links.su = {}
          region.rooms[51].links.su.to = 2675
          region.rooms[51].links.su.con = ""
        region.rooms[51].links.wu = {}
          region.rooms[51].links.wu.to = 2677
          region.rooms[51].links.wu.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "fly ws;wd;nd;nd;wu"
      region.rooms[52].name = "苍龙岭"
      region.rooms[52].zone = "华山"
      region.rooms[52].id = 2677
      region.rooms[52].desc = "    华山五峰中最惊险的是北峰，北峰之上最陡峭的则是苍龙岭。此岭高约百米，宽仅一米，而登山之路则在其山脊之上，两侧脊坡光滑挺拔，其下悬崖深邃，云涛隐伏，岭体蜿蜒逶迤，体青背黑，如苍龙腾空，故有是名。岭侧有一石碑(shibei)。    从这里往东是下山的路，再往南是上其它四峰的路，西面是华山极险处之一，叫做“舍身崖”。"
      region.rooms[52].exits = "westup|eastdown|northup"
      region.rooms[52].links = {}
        region.rooms[52].links.ed = {}
          region.rooms[52].links.ed.to = 2676
          region.rooms[52].links.ed.con = ""
        region.rooms[52].links.nu = {}
          region.rooms[52].links.nu.to = 2678
          region.rooms[52].links.nu.con = ""
        region.rooms[52].links.wu = {}
          region.rooms[52].links.wu.to = 2679
          region.rooms[52].links.wu.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "fly ws;wd;nd;nd;wu;nu"
      region.rooms[53].name = "云台峰"
      region.rooms[53].zone = "华山"
      region.rooms[53].id = 2678
      region.rooms[53].desc = "    太华北峰又名云台峰，它和南面的诸峰连成一条崎岖的长岭，构成了一条鱼椎脊似的登峰天梯。香炉峰和梁张峰拱立左右，峥嵘兀突。云台四面都是悬崖绝壁，十分险峻。峰顶建有真武宫，朝南通道上立着石牌楼两座，高镶“北峰顶”三字。"
      region.rooms[53].exits = "southdown"
      region.rooms[53].links = {}
        region.rooms[53].links.sd = {}
          region.rooms[53].links.sd.to = 2677
          region.rooms[53].links.sd.con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "fly ws;wd;nd;nd;wu;wu"
      region.rooms[54].name = "舍身崖"
      region.rooms[54].zone = "华山|逍遥林1"
      region.rooms[54].id = 2679
      region.rooms[54].links = {}
        region.rooms[54].links.ed = {}
          region.rooms[54].links.ed.to = 2677
          region.rooms[54].links.ed.con = ""
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 2680
          region.rooms[54].links.w.con = ""
      region.rooms[54].exits = "eastdown|west"
      region.rooms[54].desc = "    这是一段极窄极险的山崖，四周云雾飞绕，下面渊深无底。如不小心，一失足掉下去，只怕连骨头都找不到。边上有个小山洞(dong)。"
    region.rooms[55] = {}
      region.rooms[55].path = "fly ws;wd;nd;nd;wu;wu;w"
      region.rooms[55].name = "瀑布"
      region.rooms[55].zone = "华山|逍遥林1"
      region.rooms[55].id = 2680
      region.rooms[55].links = {}
        region.rooms[55].links.e = {}
          region.rooms[55].links.e.to = 2679
          region.rooms[55].links.e.con = ""
        region.rooms[55].links["jump down"] = {}
          region.rooms[55].links["jump down"].to = 2759
          region.rooms[55].links["jump down"].con = "xyjump:"
		  region.rooms[55].links["jump down"].block = "y"
      region.rooms[55].exits = "east"
      region.rooms[55].desc = "    你猛听得水声响亮，轰轰隆隆，便如潮水大至一般，抬头一看，只见一条大瀑布，犹如银河倒悬，从高崖上直泻下来。下面是万丈深渊，云雾弥漫，望不到尽头。。。。"
    region.rooms[56] = {}
      region.rooms[56].path = "fly ws;wd;nd;nd;nd"
      region.rooms[56].name = "猢狲愁"
      region.rooms[56].zone = "华山"
      region.rooms[56].id = 2681
      region.rooms[56].desc = "    前面又是一处十分陡峭的山岭，上面有四只铁猿，盘踞台畔，据说以前从华山水帘洞出来的猿猴，每到这里就要返回去，连它们也感到难于超越，此岭因而得名。"
      region.rooms[56].exits = "southup|northdown"
      region.rooms[56].links = {}
        region.rooms[56].links.su = {}
          region.rooms[56].links.su.to = 2676
          region.rooms[56].links.su.con = ""
        region.rooms[56].links.nd = {}
          region.rooms[56].links.nd.to = 2682
          region.rooms[56].links.nd.con = ""
    region.rooms[57] = {}
      region.rooms[57].path = "fly ws;wd;nd;nd;nd;nd"
      region.rooms[57].name = "老君沟"
      region.rooms[57].zone = "华山"
      region.rooms[57].id = 2682
      region.rooms[57].desc = "    爬过两个要命的悬崖，可在这里稍作歇息。老君沟是一条半里多长的山沟，相传为太上老君到此，见无路可通，因而套上大青牛用铁犁犁出了这条沟作为登山通道。"
      region.rooms[57].exits = "southup|westdown"
      region.rooms[57].links = {}
        region.rooms[57].links.wd = {}
          region.rooms[57].links.wd.to = 2683
          region.rooms[57].links.wd.con = ""
        region.rooms[57].links.su = {}
          region.rooms[57].links.su.to = 2681
          region.rooms[57].links.su.con = ""
    region.rooms[58] = {}
      region.rooms[58].path = "fly ws;wd;nd;nd;nd;nd;wd"
      region.rooms[58].name = "平心石"
      region.rooms[58].zone = "华山"
      region.rooms[58].id = 2683
      region.rooms[58].desc = "    百尺峡尽头，两边岩崖势欲相合，中夹两块巨石，前边一块刻有“惊心石”三字。过此回望，石上刻有“平心石”三字，示人们以险境已经过去，已进入平安之途了。顿时心情至此一舒。"
      region.rooms[58].exits = "eastup|westdown"
      region.rooms[58].links = {}
        region.rooms[58].links.wd = {}
          region.rooms[58].links.wd.to = 2684
          region.rooms[58].links.wd.con = ""
        region.rooms[58].links.eu = {}
          region.rooms[58].links.eu.to = 2682
          region.rooms[58].links.eu.con = ""
    region.rooms[59] = {}
      region.rooms[59].path = "fly ws;wd;nd;nd;nd;nd;wd;wd"
      region.rooms[59].name = "百尺峡"
      region.rooms[59].zone = "华山"
      region.rooms[59].id = 2684
      region.rooms[59].desc = "    走过千尺幢，前面又见另一要命的百尺峡，百尺峡不似千尺幢般险峻，但亦十分陡峭，岩壁两侧设有铁索以作扶拦。百尺峡又称百丈崖，是一座壁立千仞的悬崖。崖底到上面的最低的垭口处约百尺，故有是名。"
      region.rooms[59].exits = "eastup|northdown"
      region.rooms[59].links = {}
        region.rooms[59].links.eu = {}
          region.rooms[59].links.eu.to = 2683
          region.rooms[59].links.eu.con = ""
        region.rooms[59].links.nd = {}
          region.rooms[59].links.nd.to = 2685
          region.rooms[59].links.nd.con = ""
    region.rooms[60] = {}
      region.rooms[60].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd"
      region.rooms[60].name = "千尺幢"
      region.rooms[60].zone = "华山"
      region.rooms[60].id = 2685
      region.rooms[60].desc = "    前面有一斜如天垂石梯的山阶，这就是赫赫有名的千尺幢，千尺幢是依一陡峭岩脊的裂缝开凿而成，斜度约七十度，高约二十米，仅容一人上落。抬头仅见一线天光，两旁岩壁陡峭，尽头是个仅能容身的方形石洞，俗称“天井”，天井旁的危崖上刻有“太华咽喉”的题刻。"
      region.rooms[60].exits = "southup|westdown"
      region.rooms[60].links = {}
        region.rooms[60].links.wd = {}
          region.rooms[60].links.wd.to = 2686
          region.rooms[60].links.wd.con = ""
        region.rooms[60].links.su = {}
          region.rooms[60].links.su.to = 2684
          region.rooms[60].links.su.con = ""
    region.rooms[61] = {}
      region.rooms[61].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd"
      region.rooms[61].name = "回心石"
      region.rooms[61].zone = "华山"
      region.rooms[61].id = 2686
      region.rooms[61].desc = "    从青柯坪沿石阶上山，山路到此而尽，前面山势险恶，石崖间仅有窄窄的石阶犹如天梯耸立，两边铁链斜悬，令人不寒而栗，不敢前行。北壁下大石当路，此石因此叫做回心石，再上去山道奇险，游客至此，就该回头了。"
      region.rooms[61].exits = "eastup|westdown"
      region.rooms[61].links = {}
        region.rooms[61].links.wd = {}
          region.rooms[61].links.wd.to = 2687
          region.rooms[61].links.wd.con = ""
        region.rooms[61].links.eu = {}
          region.rooms[61].links.eu.to = 2685
          region.rooms[61].links.eu.con = ""
    region.rooms[62] = {}
      region.rooms[62].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd"
      region.rooms[62].name = "青柯坪"
      region.rooms[62].zone = "华山"
      region.rooms[62].id = 2687
      region.rooms[62].desc = "    走过崎岖的十八盘，穿过云门，就到了青柯坪。青柯坪是一山间盆地，地势略为平坦。从这里开始，上山的路都是由原地凿出的石阶。远远望见一个小小石亭，便是赌棋亭了。"
      region.rooms[62].exits = "eastup|southup|northdown"
      region.rooms[62].links = {}
        region.rooms[62].links.eu = {}
          region.rooms[62].links.eu.to = 2686
          region.rooms[62].links.eu.con = ""
        region.rooms[62].links.nd = {}
          region.rooms[62].links.nd.to = 2688
          region.rooms[62].links.nd.con = ""
        region.rooms[62].links.su = {}
          region.rooms[62].links.su.to = 2691
          region.rooms[62].links.su.con = ""
    region.rooms[63] = {}
      region.rooms[63].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;nd"
      region.rooms[63].name = "云门"
      region.rooms[63].zone = "华山"
      region.rooms[63].id = 2688
      region.rooms[63].desc = "    过莎萝坪，是华山十八盘。十八盘的尽处就是“云门”了。这里刻着“仙境”、“天下第一名山”等石刻。云门之内的小盆地就是青柯坪。"
      region.rooms[63].exits = "southup|northdown"
      region.rooms[63].links = {}
        region.rooms[63].links.su = {}
          region.rooms[63].links.su.to = 2687
          region.rooms[63].links.su.con = ""
        region.rooms[63].links.nd = {}
          region.rooms[63].links.nd.to = 2689
          region.rooms[63].links.nd.con = ""
    region.rooms[64] = {}
      region.rooms[64].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;nd;nd"
      region.rooms[64].name = "莎萝坪"
      region.rooms[64].zone = "华山"
      region.rooms[64].id = 2689
      region.rooms[64].desc = "    沿着玉泉，踏过累累石涧，由山径迤逦而上，就来到了莎萝坪。从这里山路开始陡峭，南面一条迂回盘旋的山道，称作「十八盘」，通往山上。"
      region.rooms[64].exits = "northwest|southup|northeast"
      region.rooms[64].links = {}
        region.rooms[64].links.ne = {}
          region.rooms[64].links.ne.to = 2690
          region.rooms[64].links.ne.con = ""
        region.rooms[64].links.nw = {}
          region.rooms[64].links.nw.to = 2348
          region.rooms[64].links.nw.con = ""
        region.rooms[64].links.su = {}
          region.rooms[64].links.su.to = 2688
          region.rooms[64].links.su.con = ""
    region.rooms[65] = {}
      region.rooms[65].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;nd;nd;ne"
      region.rooms[65].name = "山洪瀑布"
      region.rooms[65].zone = "华山"
      region.rooms[65].id = 2690
      region.rooms[65].desc = "    这里是一处峡谷，每年雨季山洪爆发时就形成了一处蔚为壮观的瀑布。传说当年神雕侠杨过就是在这里练成绝世的玄铁剑法的。现在人去谷空，只剩下空寥的山谷和奔腾的洪水(hongshui)。"
      region.rooms[65].exits = "southwest"
      region.rooms[65].links = {}
        region.rooms[65].links.sw = {}
          region.rooms[65].links.sw.to = 2689
          region.rooms[65].links.sw.con = ""
    region.rooms[66] = {}
      region.rooms[66].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;su"
      region.rooms[66].name = "石阶"
      region.rooms[66].zone = "华山"
      region.rooms[66].id = 2691
      region.rooms[66].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。"
      region.rooms[66].exits = "westup|northdown"
      region.rooms[66].links = {}
        region.rooms[66].links.nd = {}
          region.rooms[66].links.nd.to = 2687
          region.rooms[66].links.nd.con = ""
        region.rooms[66].links.wu = {}
          region.rooms[66].links.wu.to = 2692
          region.rooms[66].links.wu.con = ""
    region.rooms[67] = {}
      region.rooms[67].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;su;wu"
      region.rooms[67].name = "石阶"
      region.rooms[67].zone = "华山"
      region.rooms[67].id = 2692
      region.rooms[67].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。"
      region.rooms[67].exits = "eastdown|southup"
      region.rooms[67].links = {}
        region.rooms[67].links.ed = {}
          region.rooms[67].links.ed.to = 2691
          region.rooms[67].links.ed.con = ""
        region.rooms[67].links.su = {}
          region.rooms[67].links.su.to = 2693
          region.rooms[67].links.su.con = ""
    region.rooms[68] = {}
      region.rooms[68].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;su;wu;su"
      region.rooms[68].name = "石阶"
      region.rooms[68].zone = "华山"
      region.rooms[68].id = 2693
      region.rooms[68].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。"
      region.rooms[68].exits = "westup|northdown"
      region.rooms[68].links = {}
        region.rooms[68].links.nd = {}
          region.rooms[68].links.nd.to = 2692
          region.rooms[68].links.nd.con = ""
        region.rooms[68].links.wu = {}
          region.rooms[68].links.wu.to = 2694
          region.rooms[68].links.wu.con = ""
    region.rooms[69] = {}
      region.rooms[69].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;su;wu;su;wu"
      region.rooms[69].name = "石阶"
      region.rooms[69].zone = "华山"
      region.rooms[69].id = 2694
      region.rooms[69].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。再往上便是赌棋亭了。"
      region.rooms[69].exits = "eastdown|southup"
      region.rooms[69].links = {}
        region.rooms[69].links.ed = {}
          region.rooms[69].links.ed.to = 2693
          region.rooms[69].links.ed.con = ""
        region.rooms[69].links.su = {}
          region.rooms[69].links.su.to = 2695
          region.rooms[69].links.su.con = ""
    region.rooms[70] = {}
      region.rooms[70].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;su;wu;su;wu;su"
      region.rooms[70].name = "赌棋亭"
      region.rooms[70].zone = "华山"
      region.rooms[70].id = 2695
      region.rooms[70].desc = "    这里是一个小小石亭，相传宋太祖与华夷先生曾弈棋于此，将华山作为赌注，宋太祖输了，从此华山上的土地就不须缴纳钱粮。"
      region.rooms[70].exits = "south|northdown|west"
      region.rooms[70].links = {}
        region.rooms[70].links.nd = {}
          region.rooms[70].links.nd.to = 2694
          region.rooms[70].links.nd.con = ""
        region.rooms[70].links.w = {}
          region.rooms[70].links.w.to = 2696
          region.rooms[70].links.w.con = ""
        region.rooms[70].links.s = {}
          region.rooms[70].links.s.to = 2697
          region.rooms[70].links.s.con = ""
    region.rooms[71] = {}
      region.rooms[71].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;su;wu;su;wu;su;w"
      region.rooms[71].name = "茅庐"
      region.rooms[71].zone = "华山"
      region.rooms[71].id = 2696
      region.rooms[71].desc = "    依亭而建的一间小小茅庐。木桑喜欢下棋，便在这赌棋亭旁搭了一间茅庐做居处。"
      region.rooms[71].exits = "east"
      region.rooms[71].links = {}
        region.rooms[71].links.e = {}
          region.rooms[71].links.e.to = 2695
          region.rooms[71].links.e.con = ""
    region.rooms[72] = {}
      region.rooms[72].path = "fly ws;wd;nd;nd;nd;nd;wd;wd;nd;wd;wd;su;wu;su;wu;su;s"
      region.rooms[72].name = "小厅"
      region.rooms[72].zone = "华山"
      region.rooms[72].id = 2697
      region.rooms[72].desc = "    小厅里供奉着铁剑门历代祖师的神位。神案之上供奉着三清祖师。香炉里插着三柱清香，香烟袅袅上升，散发着一股檀香味。一位黄衫女尼正端坐在蒲团上。"
      region.rooms[72].exits = "north"
      region.rooms[72].links = {}
        region.rooms[72].links.n = {}
          region.rooms[72].links.n.to = 2695
          region.rooms[72].links.n.con = ""
  region.center = 2628
return region