local region = {}
  region.cmd = "fly xi"
  region.name = "襄阳"
  region.id = "xi"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly xi;e;e;n;n;n;w;w;n;n;n;n;n;e"
      region.rooms[1].name = "关洛道"
      region.rooms[1].zone = "扬州|襄阳"
      region.rooms[1].id = 116
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 114
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 715
          region.rooms[1].links.w.con = ""
      region.rooms[1].exits = "east|west"
      region.rooms[1].desc = "    这是一条宽阔笔直的官道，足可容得下十马并驰。往东通向脂粉之都的扬州，往西则直达长安城。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly xi;e;e;n;n;n;w;w;n;n;n;n;n"
      region.rooms[2].name = "函谷关"
      region.rooms[2].zone = "襄阳|长安"
      region.rooms[2].id = 715
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 116
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 716
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 834
          region.rooms[2].links.w.con = ""
      region.rooms[2].exits = "south|east|west"
      region.rooms[2].desc = "    这里就是古函古关。它东起崤山，西接潼津，关设谷中。当年强秦一隅之地，制关东六国而不敢稍动，最后横扫天下，就是因为它据此，进可攻，退可守，乃天下形胜之处。老子西出化胡，也是在此留下两册道德经，千载以下，后人仍研读不尽。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly xi;e;e;n;n;n;w;w;n;n;n;n"
      region.rooms[3].name = "草地"
      region.rooms[3].zone = "襄阳"
      region.rooms[3].id = 716
      region.rooms[3].desc = "    这是襄阳城外的草地。正对北城门的是蒙古四王子忽必烈的大帐。蒙古兵进犯以来，这里的百姓全进城了，蒙古兵驰骋来去，以为牧场，尘土飞扬，甚是嚣张。"
      region.rooms[3].exits = "south|north"
      region.rooms[3].links = {}
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 717
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 715
          region.rooms[3].links.n.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly xi;e;e;n;n;n;w;w;n;n;n"
      region.rooms[4].name = "玄武外门"
      region.rooms[4].zone = "襄阳"
      region.rooms[4].id = 717
      region.rooms[4].desc = "    这里是襄阳城的北城门，只见城门上方是三个大字。                      玄武门近年来蒙古屡次侵犯襄阳城，故这儿把守相当严密，一些官兵们正在盘查要离襄阳城的人。两边是很大的草地。"
      region.rooms[4].exits = "south|east|north|west"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 718
          region.rooms[4].links.e.con = ""
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 719
          region.rooms[4].links.w.con = ""
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 720
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 716
          region.rooms[4].links.n.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly xi;e;e;n;n;n;w;w;n;n;n;e"
      region.rooms[5].name = "草地"
      region.rooms[5].zone = "襄阳"
      region.rooms[5].id = 718
      region.rooms[5].desc = "    这是襄阳城外的草地。蒙古兵进犯以来，这里的百姓全进城了，蒙古兵驰骋来去，以为牧场，尘土飞扬，甚是嚣张。"
      region.rooms[5].exits = "west"
      region.rooms[5].links = {}
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 717
          region.rooms[5].links.w.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly xi;e;e;n;n;n;w;w;n;n;n;w"
      region.rooms[6].name = "草地"
      region.rooms[6].zone = "襄阳"
      region.rooms[6].id = 719
      region.rooms[6].desc = "    这是襄阳城外的草地。蒙古兵进犯以来，这里的百姓全进城了，蒙古兵驰骋来去，以为牧场，尘土飞扬，甚是嚣张。"
      region.rooms[6].exits = "east"
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 717
          region.rooms[6].links.e.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly xi;e;e;n;n;n;w;w;n;n"
      region.rooms[7].name = "玄武内门"
      region.rooms[7].zone = "襄阳"
      region.rooms[7].id = 720
      region.rooms[7].desc = "    这里是襄阳城的北城门的内城门，只见城门上方是三个大字。                      玄武门近年来蒙古屡次侵犯襄阳城，故这儿把守相当严密，一些官兵们正在盘查要离襄阳城的人。两边是上城头的石阶，向南进入城区。"
      region.rooms[7].exits = "south|westup|north|eastup"
      region.rooms[7].links = {}
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 717
          region.rooms[7].links.n.con = ""
        region.rooms[7].links.eu = {}
          region.rooms[7].links.eu.to = 833
          region.rooms[7].links.eu.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 721
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.wu = {}
          region.rooms[7].links.wu.to = 802
          region.rooms[7].links.wu.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly xi;e;e;n;n;n;w;w;n"
      region.rooms[8].name = "北大街"
      region.rooms[8].zone = "襄阳"
      region.rooms[8].id = 721
      region.rooms[8].desc = "    这是一条宽阔的青石街道，向南北两头延伸。北面是玄武内门，南边显得很繁忙。东边是一茶馆，一面上书“茶”的招幡在风中轻轻地摇曳着，一股股茶香扑面而来。西面是襄阳城的北兵营，隐隐能听见里面传来的操练声。"
      region.rooms[8].exits = "south|north|east|west"
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 722
          region.rooms[8].links.e.con = ""
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 723
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 724
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 720
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly xi;e;e;n;n;n;w;w;n;e"
      region.rooms[9].name = "茶馆"
      region.rooms[9].zone = "襄阳"
      region.rooms[9].id = 722
      region.rooms[9].desc = "    你一走进来，就闻到一股茶香沁入心脾，精神为之一爽。几张八仙桌一字排开，坐满了客人，或高声谈论战局，或交头接耳元兵势大。你要想打听什么，恐怕不是时候。"
      region.rooms[9].exits = "west"
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 721
          region.rooms[9].links.w.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly xi;e;e;n;n;n;w;w;n;w"
      region.rooms[10].name = "兵营"
      region.rooms[10].zone = "襄阳"
      region.rooms[10].id = 723
      region.rooms[10].desc = "    这里是兵营，密密麻麻到处都是官兵，有的在武将的指挥下列队操练，有的独自在练功，有的坐着、躺着正在休息。南墙下坐着主帅，不动声色地寻视着四周。看到你进来，他们全都向你瞪大眼睛盯着你。"
      region.rooms[10].exits = "east"
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 721
          region.rooms[10].links.e.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly xi;e;e;n;n;n;w;w"
      region.rooms[11].name = "丁字街口"
      region.rooms[11].zone = "襄阳"
      region.rooms[11].id = 724
      region.rooms[11].desc = "    这里是襄阳城北部的丁字街口。向北一直通向玄武门，东面和西面是一条笔直的青石大街，通向城内。南面是一堵上盖红色琉璃瓦的高墙，里面是襄阳安抚使吕文德的府邸。"
      region.rooms[11].exits = "north|east|west"
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 800
          region.rooms[11].links.e.con = ""
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 725
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 721
          region.rooms[11].links.n.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly xi;w;w;n;n;n;e"
      region.rooms[12].name = "北内大街"
      region.rooms[12].zone = "襄阳"
      region.rooms[12].id = 725
      region.rooms[12].desc = "    这是一条用青石铺就的大道。只见北面是一条铺面很大的杂货铺，听说里面能买到许多东西。向东就是丁字街口，西面也是一个大街口，你好象看到一条大街通向南面。南面是一堵上盖红色琉璃瓦的高墙，里面是襄阳安抚使吕文德安排给他的布衣客卿、人称郭大侠郭靖的府邸。"
      region.rooms[12].exits = "north|east|west"
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 724
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 727
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 726
          region.rooms[12].links.n.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly xi;w;w;n;n;n;e;n"
      region.rooms[13].name = "新罗坊"
      region.rooms[13].zone = "襄阳"
      region.rooms[13].id = 726
      region.rooms[13].desc = "    新罗坊，顾名思义是给新罗人住的地方，不过其实现在新罗已经被高丽所灭掉，这里应该叫做高丽坊的。可是大家已经习惯了，于是便还这么叫。这里住着许多高丽商人，也有些高丽的使臣进东京城路过襄阳，便也住在这里。这里的高丽商人总有很多很好的货物，大家都喜欢来买，于是这里就非常的热闹了。"
      region.rooms[13].exits = "south"
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 725
          region.rooms[13].links.s.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly xi;w;w;n;n;n"
      region.rooms[14].name = "大街口"
      region.rooms[14].zone = "襄阳"
      region.rooms[14].id = 727
      region.rooms[14].desc = "    因为这儿是十字街口，所以非常热闹。小商小贩们在向行人吆喝着，兜售他们的商品。虽然襄阳饱受蒙古军侵扰，但这儿看不出人们有丝毫的紧张，好象他们已司空见惯、习以为常了。北面和西面是胡同，许多襄阳城的老百姓住在里面，东面和南面是青石铺就的大街。"
      region.rooms[14].exits = "south|north|east|west"
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 725
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 729
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 730
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 728
          region.rooms[14].links.n.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly xi;w;w;n;n;n;n"
      region.rooms[15].name = "胡同"
      region.rooms[15].zone = "襄阳"
      region.rooms[15].id = 728
      region.rooms[15].desc = "    这里是襄阳城内老百姓的居住区。只见胡同两边是有些小店面，有米行、小杂货铺等。一些居民从这里进进出出。"
      region.rooms[15].exits = "south"
      region.rooms[15].links = {}
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 727
          region.rooms[15].links.s.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly xi;w;w;n;n;n;w"
      region.rooms[16].name = "胡同"
      region.rooms[16].zone = "襄阳"
      region.rooms[16].id = 729
      region.rooms[16].desc = "    这里是襄阳城内老百姓的居住区。只见胡同两边是有些小店面，有米行、小杂货铺等。一些居民从这里进进出出。"
      region.rooms[16].exits = "east"
      region.rooms[16].links = {}
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 727
          region.rooms[16].links.e.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly xi;w;w;n;n"
      region.rooms[17].name = "西内大街"
      region.rooms[17].zone = "襄阳"
      region.rooms[17].id = 730
      region.rooms[17].desc = "    这是一条青石铺就的大街。北面是十字街口。隐隐地能望见南面是一座很高的彩楼，东面是一堵盖着红色琉璃瓦的高墙，里面是郭府大院。西面是襄阳城内新开的一家书店，听说里面能买到很好的书。"
      region.rooms[17].exits = "south|north|west"
      region.rooms[17].links = {}
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 732
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 731
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 727
          region.rooms[17].links.n.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly xi;w;w;n;n;w"
      region.rooms[18].name = "书店"
      region.rooms[18].zone = "襄阳"
      region.rooms[18].id = 731
      region.rooms[18].desc = "    这里的老板刚从南阳搬来，听说以前他曾在嵩山少林寺出过家，后不知什么原因又还了俗，专门卖书为生。只见书店面积很大，以前曾是一座勾栏。"
      region.rooms[18].exits = "east"
      region.rooms[18].links = {}
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 730
          region.rooms[18].links.e.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly xi;w;w;n"
      region.rooms[19].name = "西内大街"
      region.rooms[19].zone = "襄阳"
      region.rooms[19].id = 732
      region.rooms[19].desc = "    这是一条青石铺就的大街。隐隐地能望见南面是一座很高的彩楼，东面是一堵盖着红色琉璃瓦的高墙，里面是郭府大院。西面是襄阳城老字号的客店，北面是青石铺的大街。"
      region.rooms[19].exits = "south|north|west"
      region.rooms[19].links = {}
        region.rooms[19].links.s = {}
          region.rooms[19].links.s.to = 734
          region.rooms[19].links.s.con = ""
        region.rooms[19].links.w = {}
          region.rooms[19].links.w.to = 733
          region.rooms[19].links.w.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 730
          region.rooms[19].links.n.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly xi;w;w;n;w"
      region.rooms[20].name = "襄阳客栈"
      region.rooms[20].zone = "襄阳"
      region.rooms[20].id = 733
      region.rooms[20].desc = "    这是一家对江湖人士来说很有名气的客栈。人们到襄阳来一般都住在这里，一是便宜，二能听到江湖上的许多事情。近年来，襄阳退敌数十次，南来北往的人们经过襄阳更是打尖在这儿，顺便拜访一下郭靖等侠衣之士。"
      region.rooms[20].exits = "east"
      region.rooms[20].links = {}
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 732
          region.rooms[20].links.e.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly xi;w;w"
      region.rooms[21].name = "西大街"
      region.rooms[21].zone = "襄阳"
      region.rooms[21].id = 734
      region.rooms[21].desc = "    这儿是很大的十字街口，北边是西内大街，南面是一座彩楼，楼前高高的挂着一方大匾，上面用正楷写着“聚义馆”，落款“朱子柳”。东边通向中央广场，西面可达白虎门。"
      region.rooms[21].exits = "south|north|east|west"
      region.rooms[21].links = {}
        region.rooms[21].links.e = {}
          region.rooms[21].links.e.to = 747
          region.rooms[21].links.e.con = ""
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 735
          region.rooms[21].links.s.con = ""
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 742
          region.rooms[21].links.w.con = ""
        region.rooms[21].links.n = {}
          region.rooms[21].links.n.to = 732
          region.rooms[21].links.n.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly xi;w;w;s"
      region.rooms[22].name = "大院"
      region.rooms[22].zone = "襄阳"
      region.rooms[22].id = 735
      region.rooms[22].desc = "    这里是襄阳安抚使按照郭靖、黄蓉的意思建的用来安置各地前来效力的义士的地方。南面是一条长长的通廊，东西两边是练武场。"
      region.rooms[22].exits = "south|north|east|west"
      region.rooms[22].links = {}
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 736
          region.rooms[22].links.e.con = ""
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 737
          region.rooms[22].links.w.con = ""
        region.rooms[22].links.s = {}
          region.rooms[22].links.s.to = 738
          region.rooms[22].links.s.con = ""
        region.rooms[22].links.n = {}
          region.rooms[22].links.n.to = 734
          region.rooms[22].links.n.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly xi;w;w;s;e"
      region.rooms[23].name = "练功场"
      region.rooms[23].zone = "襄阳"
      region.rooms[23].id = 736
      region.rooms[23].desc = "    这里是聚义馆中用来练功的地方。有几个人正在专心致致地练武，有几个手持兵器，在互相拆招。身法灵动，犹如穿花蝴蝶一般，你不禁看花了眼，别的人则坐在地上的蒲团上苦练内力。"
      region.rooms[23].exits = "west"
      region.rooms[23].links = {}
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 735
          region.rooms[23].links.w.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly xi;w;w;s;w"
      region.rooms[24].name = "练功场"
      region.rooms[24].zone = "襄阳"
      region.rooms[24].id = 737
      region.rooms[24].desc = "    这里是聚义馆中用来练功的地方。有几个人正在专心致致地练武，有几个手持兵器，在互相拆招。身法灵动，犹如穿花蝴蝶一般，你不禁看花了眼，别的人则坐在地上的蒲团上苦练内力。"
      region.rooms[24].exits = "east"
      region.rooms[24].links = {}
        region.rooms[24].links.e = {}
          region.rooms[24].links.e.to = 735
          region.rooms[24].links.e.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly xi;w;w;s;s"
      region.rooms[25].name = "水上走廊"
      region.rooms[25].zone = "襄阳"
      region.rooms[25].id = 738
      region.rooms[25].desc = "    这时一条笔直的走廊，廊下是一湖池水。湖水映着长长垂柳，碧绿清澈，你能看见一些鱼在游来游去。南面就是一个大花园，圆内东西两侧各有一排厢房。"
      region.rooms[25].exits = "south|north"
      region.rooms[25].links = {}
        region.rooms[25].links.s = {}
          region.rooms[25].links.s.to = 739
          region.rooms[25].links.s.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 735
          region.rooms[25].links.n.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly xi;w;w;s;s;s"
      region.rooms[26].name = "花园"
      region.rooms[26].zone = "襄阳"
      region.rooms[26].id = 739
      region.rooms[26].desc = "    这是聚义馆的大花园。园内种着各种各样的花草，清风吹来，你能闻到股股花香。园内东西两侧各有一排厢房，北面是一湖池水，水上架着走廊，直通西大街。南面是馆内厨房，东南方向有一间物品房。"
      region.rooms[26].exits = "south|north|east|southeast|west"
      region.rooms[26].links = {}
        region.rooms[26].links.n = {}
          region.rooms[26].links.n.to = 738
          region.rooms[26].links.n.con = ""
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 740
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.se = {}
          region.rooms[26].links.se.to = 741
          region.rooms[26].links.se.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly xi;w;w;s;s;s;s"
      region.rooms[27].name = "厨房"
      region.rooms[27].zone = "襄阳"
      region.rooms[27].id = 740
      region.rooms[27].desc = "    这儿是聚义馆的厨房，一般只有白天有几个烧饭师傅在烧火做饭，供应（serve）伙食，到了晚上就看你的运气了。"
      region.rooms[27].exits = "north"
      region.rooms[27].links = {}
        region.rooms[27].links.n = {}
          region.rooms[27].links.n.to = 739
          region.rooms[27].links.n.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly xi;w;w;s;s;s;se"
      region.rooms[28].name = "物品房"
      region.rooms[28].zone = "襄阳"
      region.rooms[28].id = 741
      region.rooms[28].desc = "    这是聚义馆的堆放各种各样物品的房间。郭靖的二弟子武修文正在这儿负责向有任务的新手分发各种物品。"
      region.rooms[28].exits = "northwest"
      region.rooms[28].links = {}
        region.rooms[28].links.nw = {}
          region.rooms[28].links.nw.to = 739
          region.rooms[28].links.nw.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly xi;w;w;w"
      region.rooms[29].name = "西大街"
      region.rooms[29].zone = "襄阳"
      region.rooms[29].id = 742
      region.rooms[29].desc = "    这是一条宽阔的青石街道，向东西两头延伸。西面是白虎内门，东边是一个大十字街口，只见人来人往，络绎不绝。南边是大校场。北面是襄阳城的西兵营，隐隐能听见里面传来的宋兵的操练声。"
      region.rooms[29].exits = "south|north|east|west"
      region.rooms[29].links = {}
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 734
          region.rooms[29].links.e.con = ""
        region.rooms[29].links.s = {}
          region.rooms[29].links.s.to = 744
          region.rooms[29].links.s.con = ""
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 745
          region.rooms[29].links.w.con = ""
        region.rooms[29].links.n = {}
          region.rooms[29].links.n.to = 743
          region.rooms[29].links.n.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly xi;w;w;w;n"
      region.rooms[30].name = "兵营"
      region.rooms[30].zone = "襄阳"
      region.rooms[30].id = 743
      region.rooms[30].desc = "    这里是兵营，密密麻麻到处都是官兵，有的在武将的指挥下列队操练，有的独自在练功，有的坐着、躺着正在休息。南墙下坐着主帅，不动声色地寻视着四周。看到你进来，他们全都向你瞪大眼睛盯着你。"
      region.rooms[30].exits = "south"
      region.rooms[30].links = {}
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 742
          region.rooms[30].links.s.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly xi;w;w;w;s"
      region.rooms[31].name = "大校场"
      region.rooms[31].zone = "襄阳"
      region.rooms[31].id = 744
      region.rooms[31].desc = "    这是襄阳守军用来校阅军士的地方。只见校场正中巍巍搭着一座高台，台南排列着千余张椅子板凳。台前竖着两根旗杆，旗杆顶上有着硕大的旗斗。校场里聚集着数百个四袋以上的丐帮弟子。他们都是来竞选新任丐帮帮主的。"
      region.rooms[31].exits = "north"
      region.rooms[31].links = {}
        region.rooms[31].links.n = {}
          region.rooms[31].links.n.to = 742
          region.rooms[31].links.n.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly xi;w;w;w;w"
      region.rooms[32].name = "白虎内门"
      region.rooms[32].zone = "襄阳"
      region.rooms[32].id = 745
      region.rooms[32].desc = "    这里是襄阳城的西城门的内城门，只见城门上方是三个大字。                      白虎门近年来蒙古屡次侵犯襄阳城，故这儿把守相当严密，一些官兵们正在盘查要离襄阳城的人。两边是上城头的石阶，向东进入城区。"
      region.rooms[32].exits = "east|northup|southup|west"
      region.rooms[32].links = {}
        region.rooms[32].links.nu = {}
          region.rooms[32].links.nu.to = 809
          region.rooms[32].links.nu.con = ""
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 742
          region.rooms[32].links.e.con = ""
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 746
          region.rooms[32].links.w.con = ""
        region.rooms[32].links.su = {}
          region.rooms[32].links.su.to = 810
          region.rooms[32].links.su.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly xi;w;w;w;w;w"
      region.rooms[33].name = "白虎外门"
      region.rooms[33].zone = "襄阳"
      region.rooms[33].id = 746
      region.rooms[33].desc = "    这里是襄阳城的西城门，只见城门上方是三个大字。                      白虎门近年来蒙古屡次侵犯襄阳城，故这儿把守相当严密，一些官兵们正在盘查要离襄阳城的人。两边是很大的草地。"
      region.rooms[33].exits = "east"
      region.rooms[33].links = {}
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 745
          region.rooms[33].links.e.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly xi;w"
      region.rooms[34].name = "西大街"
      region.rooms[34].zone = "襄阳"
      region.rooms[34].id = 747
      region.rooms[34].desc = "    这是一条宽阔的青石板街道，向东西两头延伸。西边是一个大十字街口。东面是襄阳的中央广场，北边是人称郭大侠郭靖的府邸大门，不时地有人从那里进进出出。南面是一家当铺，听说里面常能买到你所需的东西。"
      region.rooms[34].exits = "south|north|east|west"
      region.rooms[34].links = {}
        region.rooms[34].links.e = {}
          region.rooms[34].links.e.to = 756
          region.rooms[34].links.e.con = ""
        region.rooms[34].links.s = {}
          region.rooms[34].links.s.to = 748
          region.rooms[34].links.s.con = ""
        region.rooms[34].links.w = {}
          region.rooms[34].links.w.to = 734
          region.rooms[34].links.w.con = ""
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 749
          region.rooms[34].links.n.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly xi;w;s"
      region.rooms[35].name = "当铺"
      region.rooms[35].zone = "襄阳"
      region.rooms[35].id = 748
      region.rooms[35].desc = "    这是家远近闻名的当铺，三开间的门面，一块写着『邱航当铺』四个金字的黑匾，足足七尺高的紫檀木的柜台被磨得光可照人，你一进去就有一种压抑和悲怅的感觉，柜台后的老板邱航头也不抬的只顾拨拉着算盘，柜台上方挂着一块花木牌子(paizi) 。据街坊们说铁面当铺给的价还不算最坏，并且从不问货的来处，除了活人什么都收，所以生意很不错。"
      region.rooms[35].exits = "north"
      region.rooms[35].links = {}
        region.rooms[35].links.n = {}
          region.rooms[35].links.n.to = 747
          region.rooms[35].links.n.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly xi;w;n"
      region.rooms[36].name = "郭府大门"
      region.rooms[36].zone = "襄阳"
      region.rooms[36].id = 749
      region.rooms[36].desc = "    一座建筑古朴的大宅院出现在你的眼前。只见门楼高挑，上书两个大字                     郭   府    全真教第二代弟子耶律齐和几个家丁站在门前接待前来保卫襄阳的各方义士。"
      region.rooms[36].exits = "south|north"
      region.rooms[36].links = {}
        region.rooms[36].links.s = {}
          region.rooms[36].links.s.to = 747
          region.rooms[36].links.s.con = ""
        region.rooms[36].links.n = {}
          region.rooms[36].links.n.to = 750
          region.rooms[36].links.n.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly xi;w;n;n"
      region.rooms[37].name = "郭府大院"
      region.rooms[37].zone = "襄阳"
      region.rooms[37].id = 750
      region.rooms[37].desc = "    这里是郭府的大院，当面一堵宽阔的白玉照壁，上书“忠心报国”四个大字，地下是一色的青砖铺地，四周种了几棵大树，有几个仆役正在院中洒扫，北面是郭府的客厅,。"
      region.rooms[37].exits = "south|north"
      region.rooms[37].links = {}
        region.rooms[37].links.s = {}
          region.rooms[37].links.s.to = 749
          region.rooms[37].links.s.con = ""
        region.rooms[37].links.n = {}
          region.rooms[37].links.n.to = 751
          region.rooms[37].links.n.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly xi;w;n;n;n"
      region.rooms[38].name = "郭府客厅"
      region.rooms[38].zone = "襄阳"
      region.rooms[38].id = 751
      region.rooms[38].desc = "    这里是郭府的客厅。厅虽不大，却布置的挺雅致。东壁悬挂着四幅屏条，绘的是梅兰菊竹四种花卉；西壁悬挂的是春夏秋冬。内厅居中的是一张八仙桌。桌上端放着一套茶具，两旁摆放着四张檀香椅，显得极为古朴。厅角各摆放着一盆牡丹花，似乎给这里带来一丝暖意。北壁内墙的神龛供奉岳飞的画像，上面是一条横幅，上书“还我河山”。"
      region.rooms[38].exits = "south|north"
      region.rooms[38].links = {}
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 750
          region.rooms[38].links.s.con = ""
        region.rooms[38].links.n = {}
          region.rooms[38].links.n.to = 752
          region.rooms[38].links.n.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly xi;w;n;n;n;n"
      region.rooms[39].name = "郭府后花园"
      region.rooms[39].zone = "襄阳"
      region.rooms[39].id = 752
      region.rooms[39].desc = "    这里是郭府的后花园，园内假山林立，西边种着一些青竹，东边是几棵枝叶茂盛的木笔花树。你一走进来，就闻到一阵阵清新的、淡淡的花香。"
      region.rooms[39].exits = "south|north|east|west"
      region.rooms[39].links = {}
        region.rooms[39].links.e = {}
          region.rooms[39].links.e.to = 754
          region.rooms[39].links.e.con = ""
        region.rooms[39].links.s = {}
          region.rooms[39].links.s.to = 751
          region.rooms[39].links.s.con = ""
        region.rooms[39].links.w = {}
          region.rooms[39].links.w.to = 755
          region.rooms[39].links.w.con = ""
        region.rooms[39].links.n = {}
          region.rooms[39].links.n.to = 753
          region.rooms[39].links.n.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly xi;w;n;n;n;n;n"
      region.rooms[40].name = "书房"
      region.rooms[40].zone = "襄阳"
      region.rooms[40].id = 753
      region.rooms[40].desc = "    这是郭靖的书房。右边是书架，上面陈列着道家和儒家的一些典籍，却没有一本与武学有关的书。左边靠窗的地方摆着一张木桌，上面放着笔墨纸砚，边上放着几本书，摆放得整整齐齐，搽拭得一尘不染，阁里到处被打扫得一尘不染，窗明几净，可以看到外面松竹掩映，时有微风入户，门后桌上还燃着一炉檀香，氲氲的香气轻轻横散，使人俗念尽消，心情完全平静下来。"
      region.rooms[40].exits = "south"
      region.rooms[40].links = {}
        region.rooms[40].links.s = {}
          region.rooms[40].links.s.to = 752
          region.rooms[40].links.s.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly xi;w;n;n;n;n;e"
      region.rooms[41].name = "卧室"
      region.rooms[41].zone = "襄阳"
      region.rooms[41].id = 754
      region.rooms[41].desc = "    这里就是郭靖和黄蓉的卧室。屋子里的陈设很简单。门的左边有一张软床。床上的被褥被叠得整整齐齐。床头正对的地方摆着一张梳妆台。桌上摆着一个光亮的铜镜，铜镜旁边的花瓶里，有一束百合花，正在散发出淡淡的幽香。里边放着两张木椅，中间是一茶几，上面摆着一盆山茶花。"
      region.rooms[41].exits = "west"
      region.rooms[41].links = {}
        region.rooms[41].links.w = {}
          region.rooms[41].links.w.to = 752
          region.rooms[41].links.w.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly xi;w;n;n;n;n;w"
      region.rooms[42].name = "客房"
      region.rooms[42].zone = "襄阳"
      region.rooms[42].id = 755
      region.rooms[42].desc = "    这里是郭府客人们的住处，整整齐齐的一排平房。门的左右两边各是一张床，床上的被褥被叠得整整齐齐。床头正对的地方摆着一张桌子，旁边还放着一张椅子。桌上整齐地放着文房四宝，旁边还放着几本书。地上摆着一盆牡丹花，一丝清香萦绕房中。因为郭靖是当今的大英雄，所以江湖上有不少豪杰每年都来拜访他。"
      region.rooms[42].exits = "east"
      region.rooms[42].links = {}
        region.rooms[42].links.e = {}
          region.rooms[42].links.e.to = 752
          region.rooms[42].links.e.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly xi"
      region.rooms[43].name = "中央广场"
      region.rooms[43].zone = "襄阳"
      region.rooms[43].id = 756
      region.rooms[43].desc = "    这里是襄阳的中央广场，铺着青石地面。东面通向青龙门，西面通向白虎门，南面直达朱雀门，远远地你可看到北面是襄阳安抚使衙门。近年来蒙古大军屡次攻打襄阳，官府为防止蒙古奸细混杂进来，已经不允许人们在此聚集。只见一队官兵在此往来巡逻，你还是快离开吧。"
      region.rooms[43].exits = "south|north|east|west"
      region.rooms[43].links = {}
        region.rooms[43].links.e = {}
          region.rooms[43].links.e.to = 779
          region.rooms[43].links.e.con = ""
        region.rooms[43].links.w = {}
          region.rooms[43].links.w.to = 747
          region.rooms[43].links.w.con = ""
        region.rooms[43].links.s = {}
          region.rooms[43].links.s.to = 759
          region.rooms[43].links.s.con = ""
        region.rooms[43].links.n = {}
          region.rooms[43].links.n.to = 757
          region.rooms[43].links.n.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly xi;n"
      region.rooms[44].name = "安抚府牌楼"
      region.rooms[44].zone = "襄阳"
      region.rooms[44].id = 757
      region.rooms[44].desc = "    这里是安抚使府前的一座牌楼，高达二丈，由黄玉制成，和东面的将军府屋顶的琉璃瓦在阳光的照耀下黄白掩映，金碧辉煌，令人目为之眩，感觉分外巍峨庄严。你抬头望去，但见牌楼上四个大金字“安抚使府”。牌楼下站着两派手那刀枪的宋兵，紧紧盯着每一个靠近这儿的人。北面就是安抚府大院了。南面就是襄阳的中央广场。"
      region.rooms[44].exits = "south|north"
      region.rooms[44].links = {}
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 756
          region.rooms[44].links.s.con = ""
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 758
          region.rooms[44].links.n.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly xi;n;n"
      region.rooms[45].name = "安抚使衙门"
      region.rooms[45].zone = "襄阳"
      region.rooms[45].id = 758
      region.rooms[45].desc = "    这是安抚使衙门的大门，铜皮包门似乎极为沉重，上面有两个明晃晃的铜环；大门紧闭，里面却传出一阵阵嬉笑声，和门口的肃杀很不协调。想来这个安抚使大人的日子还是过得蛮滋润的。"
      region.rooms[45].exits = "south"
      region.rooms[45].links = {}
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 757
          region.rooms[45].links.s.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly xi;s"
      region.rooms[46].name = "南大街"
      region.rooms[46].zone = "襄阳"
      region.rooms[46].id = 759
      region.rooms[46].desc = "    这是一条宽阔的青石板街道，向南北两头延伸。南边就是朱雀门，北面是中央广场，西面是钱庄，东面是襄阳城内的唯一一家学堂。虽然襄阳战火不断，你仍能听到学堂里传来学生们朗朗地读书声。"
      region.rooms[46].exits = "south|north|east|west"
      region.rooms[46].links = {}
        region.rooms[46].links.e = {}
          region.rooms[46].links.e.to = 761
          region.rooms[46].links.e.con = ""
        region.rooms[46].links.w = {}
          region.rooms[46].links.w.to = 760
          region.rooms[46].links.w.con = ""
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 762
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 756
          region.rooms[46].links.n.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly xi;s;w"
      region.rooms[47].name = "钱庄"
      region.rooms[47].zone = "襄阳"
      region.rooms[47].id = 760
      region.rooms[47].desc = "    这里是襄阳的钱庄，因为这里商业相当发达，各地的商号都和这里有银钱来往。钱庄里有很多人在存取钱，也有人在兑换银两。看着这么多的钱财滚来滚去，真是让人眼馋啊。但眼下大敌当前，全城一致抵御元兵。钱庄的业务由华山弟子接管，支援大侠郭靖和郭夫人。墙上贴着一个牌子(paizi)。"
      region.rooms[47].exits = "east"
      region.rooms[47].links = {}
        region.rooms[47].links.e = {}
          region.rooms[47].links.e.to = 759
          region.rooms[47].links.e.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "fly xi;s;e"
      region.rooms[48].name = "学堂"
      region.rooms[48].zone = "襄阳"
      region.rooms[48].id = 761
      region.rooms[48].desc = "    这里是襄阳的学堂，窗明几净，一尘不染。一位庄重严肃的老先生坐在太师椅上讲学。在他的两侧坐满了求学的学生。一张古意盎然的书案放在老先生的前面，案上摆着几本翻开了的线装书籍。"
      region.rooms[48].exits = "west"
      region.rooms[48].links = {}
        region.rooms[48].links.w = {}
          region.rooms[48].links.w.to = 759
          region.rooms[48].links.w.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly xi;s;s"
      region.rooms[49].name = "南大街"
      region.rooms[49].zone = "襄阳"
      region.rooms[49].id = 762
      region.rooms[49].desc = "    这里是襄阳城里的繁华地段，虽然久经战火，但在郭靖等人的保卫下，襄阳的老百姓过着非常安安稳稳的生活。西边是襄阳城内最大的一家赌场。东边是一座两层的楼阁，挂着“酒”的招帘，门额上悬挂一方横匾，上书“觅香楼”三字。一阵阵酒肉香味扑鼻而来。"
      region.rooms[49].exits = "south|north|east|west"
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 764
          region.rooms[49].links.e.con = ""
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 763
          region.rooms[49].links.w.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 765
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.n = {}
          region.rooms[49].links.n.to = 759
          region.rooms[49].links.n.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly xi;s;s;w"
      region.rooms[50].name = "赌场"
      region.rooms[50].zone = "襄阳"
      region.rooms[50].id = 763
      region.rooms[50].desc = "    这里本是襄阳最大的赌场。可是大战当前，为免守军军心动摇、军纪败坏，郭大侠早已下令关闭了赌场。门可罗雀的大院，可以想象当时的规模，闲置破败的赌具，也不知道在无声地诉说什么。"
      region.rooms[50].exits = "east"
      region.rooms[50].links = {}
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 762
          region.rooms[50].links.e.con = ""
    region.rooms[51] = {}
      region.rooms[51].path = "fly xi;s;s;e"
      region.rooms[51].name = "觅香楼"
      region.rooms[51].zone = "襄阳"
      region.rooms[51].id = 764
      region.rooms[51].desc = "    襄阳城里没有不知道“觅香楼”的。虽是抗战时期，来往公务却多，饭后谈资也富，生意反见兴隆。楼下布置简易，顾客多是匆匆的行人，买点包子、鸡腿、米酒就赶路去了。楼上是雅座。抗战期间，厉行节约，不许挥霍，就没啥生意，只好关了。"
      region.rooms[51].exits = "west"
      region.rooms[51].links = {}
        region.rooms[51].links.w = {}
          region.rooms[51].links.w.to = 762
          region.rooms[51].links.w.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "fly xi;s;s;s"
      region.rooms[52].name = "南大街"
      region.rooms[52].zone = "襄阳"
      region.rooms[52].id = 765
      region.rooms[52].desc = "    这里是襄阳城南大街的南头。南面就是朱雀内门，北边非常热闹。东边是为襄阳城守军打制铠甲武器的兵器铺。十余年来，由于蒙古军的侵犯，叮叮当当的打铁声音就一直响个不停。西面是襄阳城的南兵营，隐隐能听见里面传来的兵士们的操练声。"
      region.rooms[52].exits = "south|north|east|west"
      region.rooms[52].links = {}
        region.rooms[52].links.e = {}
          region.rooms[52].links.e.to = 767
          region.rooms[52].links.e.con = ""
        region.rooms[52].links.w = {}
          region.rooms[52].links.w.to = 766
          region.rooms[52].links.w.con = ""
        region.rooms[52].links.s = {}
          region.rooms[52].links.s.to = 769
          region.rooms[52].links.s.con = ""
        region.rooms[52].links.n = {}
          region.rooms[52].links.n.to = 762
          region.rooms[52].links.n.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "fly xi;s;s;s;w"
      region.rooms[53].name = "兵营"
      region.rooms[53].zone = "襄阳"
      region.rooms[53].id = 766
      region.rooms[53].desc = "    这里是兵营，密密麻麻到处都是官兵，有的在武将的指挥下列队操练，有的独自在练功，有的坐着、躺着正在休息。南墙下坐着主帅，不动声色地寻视着四周。看到你进来，他们全都向你瞪大眼睛盯着你。"
      region.rooms[53].exits = "east"
      region.rooms[53].links = {}
        region.rooms[53].links.e = {}
          region.rooms[53].links.e.to = 765
          region.rooms[53].links.e.con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "fly xi;s;s;s;e"
      region.rooms[54].name = "兵器铺"
      region.rooms[54].zone = "襄阳"
      region.rooms[54].id = 767
      region.rooms[54].desc = "    这里原来是一家极其简陋的铁匠铺。近年来蒙古大军屡次进犯襄阳，这家铁匠铺被官府征用，作为官办作坊。目前规模很大，一般用来为襄阳守军打造铠甲、兵器等，近来因襄阳需筹备守城物资，奉郭夫人之命也生产一些铁钎、铁锤、伐木斧头等。只见几十个铁匠正叮叮当当地忙个不停。"
      region.rooms[54].exits = "east|west"
      region.rooms[54].links = {}
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 765
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 768
          region.rooms[54].links.e.con = ""
    region.rooms[55] = {}
      region.rooms[55].path = "fly xi;s;s;s;e;e"
      region.rooms[55].name = "仓库"
      region.rooms[55].zone = "襄阳"
      region.rooms[55].id = 768
      region.rooms[55].desc = "    这里是一间很大的仓库，里边有许多间储藏室，你可以在这里存放矿石等材料。"
      region.rooms[55].exits = "west"
      region.rooms[55].links = {}
        region.rooms[55].links.w = {}
          region.rooms[55].links.w.to = 767
          region.rooms[55].links.w.con = ""
    region.rooms[56] = {}
      region.rooms[56].path = "fly xi;s;s;s;s"
      region.rooms[56].name = "朱雀内门"
      region.rooms[56].zone = "襄阳"
      region.rooms[56].id = 769
      region.rooms[56].desc = "    这里是襄阳城的南城门的内城门，只见城门上方是三个大字。                      朱雀门近年来蒙古屡次侵犯襄阳城，故这儿把守相当严密，一些官兵们正在盘查要离襄阳城的人。两边是上城头的石阶，向北进入城区。"
      region.rooms[56].exits = "south|westup|north|eastup"
      region.rooms[56].links = {}
        region.rooms[56].links.n = {}
          region.rooms[56].links.n.to = 765
          region.rooms[56].links.n.con = ""
        region.rooms[56].links.eu = {}
          region.rooms[56].links.eu.to = 818
          region.rooms[56].links.eu.con = ""
        region.rooms[56].links.s = {}
          region.rooms[56].links.s.to = 770
          region.rooms[56].links.s.con = ""
        region.rooms[56].links.wu = {}
          region.rooms[56].links.wu.to = 817
          region.rooms[56].links.wu.con = ""
    region.rooms[57] = {}
      region.rooms[57].path = "fly xi;s;s;s;s;s"
      region.rooms[57].name = "朱雀外门"
      region.rooms[57].zone = "襄阳"
      region.rooms[57].id = 770
      region.rooms[57].desc = "    这里是襄阳城的南城门，只见城门上方是三个大字。                      朱雀门近年来蒙古屡次侵犯襄阳城，故这儿把守相当严密，一些官兵们正在盘查要离襄阳城的人。两边是很大的草地。"
      region.rooms[57].exits = "south|north|east|west"
      region.rooms[57].links = {}
        region.rooms[57].links.e = {}
          region.rooms[57].links.e.to = 771
          region.rooms[57].links.e.con = ""
        region.rooms[57].links.w = {}
          region.rooms[57].links.w.to = 772
          region.rooms[57].links.w.con = ""
        region.rooms[57].links.s = {}
          region.rooms[57].links.s.to = 773
          region.rooms[57].links.s.con = ""
        region.rooms[57].links.n = {}
          region.rooms[57].links.n.to = 769
          region.rooms[57].links.n.con = ""
    region.rooms[58] = {}
      region.rooms[58].path = "fly xi;s;s;s;s;s;e"
      region.rooms[58].name = "草地"
      region.rooms[58].zone = "襄阳"
      region.rooms[58].id = 771
      region.rooms[58].desc = "    这是襄阳城外的草地。蒙古兵进犯以来，这里的百姓全进城了，这里几十里都没了人烟。"
      region.rooms[58].exits = "west"
      region.rooms[58].links = {}
        region.rooms[58].links.w = {}
          region.rooms[58].links.w.to = 770
          region.rooms[58].links.w.con = ""
    region.rooms[59] = {}
      region.rooms[59].path = "fly xi;s;s;s;s;s;w"
      region.rooms[59].name = "草地"
      region.rooms[59].zone = "襄阳"
      region.rooms[59].id = 772
      region.rooms[59].desc = "    这是襄阳城外的草地。蒙古兵进犯以来，这里的百姓全进城了，这里几十里都没了人烟。"
      region.rooms[59].exits = "east"
      region.rooms[59].links = {}
        region.rooms[59].links.e = {}
          region.rooms[59].links.e.to = 770
          region.rooms[59].links.e.con = ""
    region.rooms[60] = {}
      region.rooms[60].path = "fly xi;s;s;s;s;s;s"
      region.rooms[60].name = "草地"
      region.rooms[60].zone = "襄阳"
      region.rooms[60].id = 773
      region.rooms[60].desc = "    这是襄阳城外的草地。蒙古兵进犯以来，这里的百姓全进城了，虽然蒙古兵没来到南门，但肃杀氛围丝毫不减。"
      region.rooms[60].exits = "south|east|north|west"
      region.rooms[60].links = {}
        region.rooms[60].links.e = {}
          region.rooms[60].links.e.to = 774
          region.rooms[60].links.e.con = ""
        region.rooms[60].links.s = {}
          region.rooms[60].links.s.to = 777
          region.rooms[60].links.s.con = ""
        region.rooms[60].links.w = {}
          region.rooms[60].links.w.to = 778
          region.rooms[60].links.w.con = ""
        region.rooms[60].links.n = {}
          region.rooms[60].links.n.to = 770
          region.rooms[60].links.n.con = ""
    region.rooms[61] = {}
      region.rooms[61].path = "fly xi;s;s;s;s;s;s;e"
      region.rooms[61].name = "矿山"
      region.rooms[61].zone = "襄阳"
      region.rooms[61].id = 774
      region.rooms[61].desc = "    这儿是一座荒无人烟的矿山！山间和地面上能看到好多好多的矿脉，矿藏极为丰富！据说这儿可以挖出一些制造护具用的好矿石。我想你应该来试试！"
      region.rooms[61].exits = "east|west"
      region.rooms[61].links = {}
        region.rooms[61].links.w = {}
          region.rooms[61].links.w.to = 773
          region.rooms[61].links.w.con = ""
        region.rooms[61].links.e = {}
          region.rooms[61].links.e.to = 775
          region.rooms[61].links.e.con = ""
    region.rooms[62] = {}
      region.rooms[62].path = "fly xi;s;s;s;s;s;s;e;e"
      region.rooms[62].name = "矿山"
      region.rooms[62].zone = "襄阳"
      region.rooms[62].id = 775
      region.rooms[62].desc = "    这儿是一座荒无人烟的矿山！山间和地面上能看到好多好多的矿脉，矿藏极为丰富！据说这儿可以挖出一些制造护具用的好矿石。我想你应该来试试！"
      region.rooms[62].exits = "east|west"
      region.rooms[62].links = {}
        region.rooms[62].links.w = {}
          region.rooms[62].links.w.to = 774
          region.rooms[62].links.w.con = ""
        region.rooms[62].links.e = {}
          region.rooms[62].links.e.to = 776
          region.rooms[62].links.e.con = ""
    region.rooms[63] = {}
      region.rooms[63].path = "fly xi;s;s;s;s;s;s;e;e;e"
      region.rooms[63].name = "矿山"
      region.rooms[63].zone = "襄阳"
      region.rooms[63].id = 776
      region.rooms[63].desc = "    这儿是一座荒无人烟的矿山！山间和地面上能看到好多好多的矿脉，矿藏极为丰富！据说这儿可以挖出一些制造护具用的好矿石。我想你应该来试试！"
      region.rooms[63].exits = "west"
      region.rooms[63].links = {}
        region.rooms[63].links.w = {}
          region.rooms[63].links.w.to = 775
          region.rooms[63].links.w.con = ""
    region.rooms[64] = {}
      region.rooms[64].path = "fly xi;s;s;s;s;s;s;s"
      region.rooms[64].name = "青石大道"
      region.rooms[64].zone = "襄阳|武当山"
      region.rooms[64].id = 777
      region.rooms[64].desc = "    你走在一条青石大道上，四周静悄悄的。四周是浓密的树林，阴森森的十分怕人。西北方就是陕鄂边界了。北边却是一片草地。"
      region.rooms[64].exits = "south|east|north|northwest"
      region.rooms[64].links = {}
        region.rooms[64].links.e = {}
          region.rooms[64].links.e.to = 462
          region.rooms[64].links.e.con = ""
        region.rooms[64].links.nw = {}
          region.rooms[64].links.nw.to = 1743
          region.rooms[64].links.nw.con = ""
        region.rooms[64].links.s = {}
          region.rooms[64].links.s.to = 2979
          region.rooms[64].links.s.con = ""
        region.rooms[64].links.n = {}
          region.rooms[64].links.n.to = 773
          region.rooms[64].links.n.con = ""
    region.rooms[65] = {}
      region.rooms[65].path = "fly xi;s;s;s;s;s;s;w"
      region.rooms[65].name = "道路"
      region.rooms[65].zone = "襄阳"
      region.rooms[65].id = 778
      region.rooms[65].desc = "    你走在湘鄂交界的道路上，偶尔会有人骑着马匆匆而过。这里已经是湖南地界，往北进入湖北境内。"
      region.rooms[65].exits = "east|southwest"
      region.rooms[65].links = {}
        region.rooms[65].links.e = {}
          region.rooms[65].links.e.to = 773
          region.rooms[65].links.e.con = ""
    region.rooms[66] = {}
      region.rooms[66].path = "fly xi;e"
      region.rooms[66].name = "东大街"
      region.rooms[66].zone = "襄阳"
      region.rooms[66].id = 779
      region.rooms[66].desc = "    这是一条宽阔的青石板街道，向东西两头延伸。东边是一个大十字街口。西面是襄阳的中央广场，北边是襄阳守城大将王坚的府邸大门，只见那儿守备森严，闲杂人等一般是不能接近的。南面飘来一缕缕的药香，噢，原来是一家药铺。"
      region.rooms[66].exits = "south|north|east|west"
      region.rooms[66].links = {}
        region.rooms[66].links.e = {}
          region.rooms[66].links.e.to = 784
          region.rooms[66].links.e.con = ""
        region.rooms[66].links.w = {}
          region.rooms[66].links.w.to = 756
          region.rooms[66].links.w.con = ""
        region.rooms[66].links.s = {}
          region.rooms[66].links.s.to = 783
          region.rooms[66].links.s.con = ""
        region.rooms[66].links.n = {}
          region.rooms[66].links.n.to = 780
          region.rooms[66].links.n.con = ""
    region.rooms[67] = {}
      region.rooms[67].path = "fly xi;e;n"
      region.rooms[67].name = "将军府大门"
      region.rooms[67].zone = "襄阳"
      region.rooms[67].id = 780
      region.rooms[67].desc = "    这是将军府的大门，门板不知是以什么材料制成，看上去黝黑一片，似乎极为沉重，上面有两个擦得晶亮的铜环；在大门的正上面有个夹着一个高大的木牌坊，上书「将军府」三个大字，字迹娟秀飘逸，只是有些模糊了，想必是岁月留下的痕迹。门内有一株老柏，生得苍劲挺拔，枝叶茂密。门前东西两边各肃立着两个腰配大刀的宋兵。"
      region.rooms[67].exits = "south|north"
      region.rooms[67].links = {}
        region.rooms[67].links.s = {}
          region.rooms[67].links.s.to = 779
          region.rooms[67].links.s.con = ""
        region.rooms[67].links.n = {}
          region.rooms[67].links.n.to = 781
          region.rooms[67].links.n.con = "k1:宋兵"
    region.rooms[68] = {}
      region.rooms[68].path = "fly xi;e;n;|!k1:宋兵:n|"
      region.rooms[68].name = "将军府大院"
      region.rooms[68].zone = "襄阳"
      region.rooms[68].id = 781
      region.rooms[68].desc = "    这里是将军府的大院，只见大理石铺就的地面一尘不染，两个衣着光鲜的小丫鬟认真的在擦洗两边的栏杆和柱子，不时有值班的卫士走过来。向里望去，可以看到将军府的大堂。"
      region.rooms[68].exits = "south|north"
      region.rooms[68].links = {}
        region.rooms[68].links.s = {}
          region.rooms[68].links.s.to = 780
          region.rooms[68].links.s.con = ""
        region.rooms[68].links.n = {}
          region.rooms[68].links.n.to = 782
          region.rooms[68].links.n.con = ""
    region.rooms[69] = {}
      region.rooms[69].path = "fly xi;e;n;|!k1:宋兵:n|;n"
      region.rooms[69].name = "将军府大堂"
      region.rooms[69].zone = "襄阳"
      region.rooms[69].id = 782
      region.rooms[69].desc = "    这里是将军府的大堂，公案后端坐着一个威猛的将军，但一脸疲惫，看来征战刚归的模样。大堂两边摆着兵器架，架上锋刃仍留血迹，映着架后的战旗，分外耀眼。两班将佐，虽征尘未洗，但斗志昂扬，甚是雄壮。"
      region.rooms[69].exits = "south"
      region.rooms[69].links = {}
        region.rooms[69].links.s = {}
          region.rooms[69].links.s.to = 781
          region.rooms[69].links.s.con = ""
    region.rooms[70] = {}
      region.rooms[70].path = "fly xi;e;s"
      region.rooms[70].name = "药铺"
      region.rooms[70].zone = "襄阳"
      region.rooms[70].id = 783
      region.rooms[70].desc = "    药铺不大，却异常的整洁；正面是柜台，柜台后面是个大柜子几百个小抽屉上一一用红纸标着药材的名称；靠近屋顶的墙上悬着一块黑底金字的匾额，写着“妙手回春”。地下几个伙计正在分拣刚刚收购来的草药。东边一张小矮桌儿，上面放着笔墨纸砚，桌后坐着一位老郎中。一股刺鼻药味充满了整个房间。"
      region.rooms[70].exits = "north"
      region.rooms[70].links = {}
        region.rooms[70].links.n = {}
          region.rooms[70].links.n.to = 779
          region.rooms[70].links.n.con = ""
    region.rooms[71] = {}
      region.rooms[71].path = "fly xi;e;e"
      region.rooms[71].name = "东大街"
      region.rooms[71].zone = "襄阳"
      region.rooms[71].id = 784
      region.rooms[71].desc = "    这儿是很大的十字街口，北边是东内大街，南面是一条街道，听说有钱人一般都住在里面，东面通向襄阳城的青龙门，向西可到达中央广场。"
      region.rooms[71].exits = "south|north|east|west"
      region.rooms[71].links = {}
        region.rooms[71].links.e = {}
          region.rooms[71].links.e.to = 788
          region.rooms[71].links.e.con = ""
        region.rooms[71].links.s = {}
          region.rooms[71].links.s.to = 785
          region.rooms[71].links.s.con = ""
        region.rooms[71].links.w = {}
          region.rooms[71].links.w.to = 779
          region.rooms[71].links.w.con = ""
        region.rooms[71].links.n = {}
          region.rooms[71].links.n.to = 793
          region.rooms[71].links.n.con = ""
    region.rooms[72] = {}
      region.rooms[72].path = "fly xi;e;e;s"
      region.rooms[72].name = "街道"
      region.rooms[72].zone = "襄阳"
      region.rooms[72].id = 785
      region.rooms[72].desc = "    这里是襄阳城内有钱人的居住区。街道两旁是一些豪华的住宅，虽然襄阳历经战乱，但还有许多有钱人没搬走，为坚守襄阳城出钱出力。"
      region.rooms[72].exits = "north|east|west"
      region.rooms[72].links = {}
        region.rooms[72].links.e = {}
          region.rooms[72].links.e.to = 786
          region.rooms[72].links.e.con = ""
        region.rooms[72].links.w = {}
          region.rooms[72].links.w.to = 787
          region.rooms[72].links.w.con = ""
        region.rooms[72].links.n = {}
          region.rooms[72].links.n.to = 784
          region.rooms[72].links.n.con = ""
    region.rooms[73] = {}
      region.rooms[73].path = "fly xi;e;e;s;e"
      region.rooms[73].name = "民居"
      region.rooms[73].zone = "襄阳"
      region.rooms[73].id = 786
      region.rooms[73].desc = "    这是一家比较有钱人的住房，房子主人正在家里忙这忙那，看见你进来，急忙站起身向你打招呼。"
      region.rooms[73].exits = "west"
      region.rooms[73].links = {}
        region.rooms[73].links.w = {}
          region.rooms[73].links.w.to = 785
          region.rooms[73].links.w.con = ""
    region.rooms[74] = {}
      region.rooms[74].path = "fly xi;e;e;s;w"
      region.rooms[74].name = "民居"
      region.rooms[74].zone = "襄阳"
      region.rooms[74].id = 787
      region.rooms[74].desc = "    这是一家比较有钱人的住房，房子主人正在家里忙这忙那，看见你进来，急忙站起身向你打招呼。"
      region.rooms[74].exits = "east"
      region.rooms[74].links = {}
        region.rooms[74].links.e = {}
          region.rooms[74].links.e.to = 785
          region.rooms[74].links.e.con = ""
    region.rooms[75] = {}
      region.rooms[75].path = "fly xi;e;e;e"
      region.rooms[75].name = "东大街"
      region.rooms[75].zone = "襄阳"
      region.rooms[75].id = 788
      region.rooms[75].desc = "    这是一条宽阔的青石街道，向东西两头延伸。东面是青龙内门，南边是木匠铺，锯木声、刨木声声声入耳。北面是襄阳城的东兵营，隐隐能听见里面传来宋兵的操练声。西边是一个十字街口，只见人来人往、络绎不绝。"
      region.rooms[75].exits = "south|north|east|west"
      region.rooms[75].links = {}
        region.rooms[75].links.e = {}
          region.rooms[75].links.e.to = 791
          region.rooms[75].links.e.con = ""
        region.rooms[75].links.s = {}
          region.rooms[75].links.s.to = 789
          region.rooms[75].links.s.con = ""
        region.rooms[75].links.w = {}
          region.rooms[75].links.w.to = 784
          region.rooms[75].links.w.con = ""
        region.rooms[75].links.n = {}
          region.rooms[75].links.n.to = 790
          region.rooms[75].links.n.con = ""
    region.rooms[76] = {}
      region.rooms[76].path = "fly xi;e;e;e;s"
      region.rooms[76].name = "木匠铺"
      region.rooms[76].zone = "襄阳"
      region.rooms[76].id = 789
      region.rooms[76].desc = "    这是一家简陋的木匠铺，一个中年木匠正蹲在地上钉东西。值此乱世，木匠们也只好制作些刀枪棍棒什么的以养家糊口。地上和墙角凌乱地堆放着一些木剑，木刀，木棍什么的，还有几件象锯子，刨子一类的木匠工具。"
      region.rooms[76].exits = "north"
      region.rooms[76].links = {}
        region.rooms[76].links.n = {}
          region.rooms[76].links.n.to = 788
          region.rooms[76].links.n.con = ""
    region.rooms[77] = {}
      region.rooms[77].path = "fly xi;e;e;e;n"
      region.rooms[77].name = "兵营"
      region.rooms[77].zone = "襄阳"
      region.rooms[77].id = 790
      region.rooms[77].desc = "    这里是兵营，密密麻麻到处都是官兵，有的在武将的指挥下列队操练，有的独自在练功，有的坐着、躺着正在休息。南墙下坐着主帅，不动声色地寻视着四周。看到你进来，他们全都向你瞪大眼睛盯着你。"
      region.rooms[77].exits = "south"
      region.rooms[77].links = {}
        region.rooms[77].links.s = {}
          region.rooms[77].links.s.to = 788
          region.rooms[77].links.s.con = ""
    region.rooms[78] = {}
      region.rooms[78].path = "fly xi;e;e;e;e"
      region.rooms[78].name = "青龙内门"
      region.rooms[78].zone = "襄阳"
      region.rooms[78].id = 791
      region.rooms[78].desc = "    这里是襄阳城的东城门的内城门，只见城门上方是三个大字。                      青龙门近年来蒙古屡次侵犯襄阳城，故这儿把守相当严密，一些官兵们正在盘查要离襄阳城的人。两边是上城头的石阶，向西进入城区。"
      region.rooms[78].exits = "east|northup|southup|west"
      region.rooms[78].links = {}
        region.rooms[78].links.nu = {}
          region.rooms[78].links.nu.to = 826
          region.rooms[78].links.nu.con = ""
        region.rooms[78].links.e = {}
          region.rooms[78].links.e.to = 792
          region.rooms[78].links.e.con = ""
        region.rooms[78].links.w = {}
          region.rooms[78].links.w.to = 788
          region.rooms[78].links.w.con = ""
        region.rooms[78].links.su = {}
          region.rooms[78].links.su.to = 825
          region.rooms[78].links.su.con = ""
    region.rooms[79] = {}
      region.rooms[79].path = "fly xi;e;e;e;e;e"
      region.rooms[79].name = "青龙外门"
      region.rooms[79].zone = "襄阳"
      region.rooms[79].id = 792
      region.rooms[79].desc = "    这里是襄阳城的东城门，只见城门上方是三个大字。                      青龙门近年来蒙古屡次侵犯襄阳城，故这儿把守相当严密，一些官兵们正在盘查要离襄阳城的人。两边是很大的草地。"
      region.rooms[79].exits = "west"
      region.rooms[79].links = {}
        region.rooms[79].links.w = {}
          region.rooms[79].links.w.to = 791
          region.rooms[79].links.w.con = ""
    region.rooms[80] = {}
      region.rooms[80].path = "fly xi;e;e;n"
      region.rooms[80].name = "东内大街"
      region.rooms[80].zone = "襄阳"
      region.rooms[80].id = 793
      region.rooms[80].desc = "    这是一条青石铺就的大街。西面是一堵盖着红色琉璃瓦的高墙，里面是襄阳守城大将王坚的府邸大院。东面是是一座镖局，北面是用青石铺的大街道。南面是一个大的十字街道，只见人来人往，非常热闹。"
      region.rooms[80].exits = "south|north|east"
      region.rooms[80].links = {}
        region.rooms[80].links.e = {}
          region.rooms[80].links.e.to = 794
          region.rooms[80].links.e.con = ""
        region.rooms[80].links.s = {}
          region.rooms[80].links.s.to = 784
          region.rooms[80].links.s.con = ""
        region.rooms[80].links.n = {}
          region.rooms[80].links.n.to = 795
          region.rooms[80].links.n.con = ""
    region.rooms[81] = {}
      region.rooms[81].path = "fly xi;e;e;n;e"
      region.rooms[81].name = "长风镖局"
      region.rooms[81].zone = "襄阳"
      region.rooms[81].id = 794
      region.rooms[81].desc = "    你来到一座结构宏伟的建筑前，左右石坛上各插着一根两丈多高的旗杆，杆上青旗飘扬。右首旗子用金线绣着一头张牙舞爪的狮子，狮子上头有一只蝙蝠飞翔。左首旗子上写着“长风镖局襄阳分号”八个黑字，银钩铁划，刚劲非凡。入口排着两条长凳，几名镖头坐着把守。"
      region.rooms[81].exits = "west"
      region.rooms[81].links = {}
        region.rooms[81].links.w = {}
          region.rooms[81].links.w.to = 793
          region.rooms[81].links.w.con = ""
    region.rooms[82] = {}
      region.rooms[82].path = "fly xi;e;e;n;n"
      region.rooms[82].name = "东内大街"
      region.rooms[82].zone = "襄阳"
      region.rooms[82].id = 795
      region.rooms[82].desc = "    这是一条青石铺就的大街。西面是一堵盖着红色琉璃瓦的高墙，里面是襄阳守城大将王坚的府邸大院。东面是忠烈祠，因为十余年来，为保卫襄阳、抵抗蒙古军的侵略而牺牲的人特别多，前往上香祭奠的人络绎不绝。北面是一个十字街道，只见人来人往，非常热闹，南面是用青石铺的街道。"
      region.rooms[82].exits = "south|north|east"
      region.rooms[82].links = {}
        region.rooms[82].links.e = {}
          region.rooms[82].links.e.to = 796
          region.rooms[82].links.e.con = ""
        region.rooms[82].links.s = {}
          region.rooms[82].links.s.to = 793
          region.rooms[82].links.s.con = ""
        region.rooms[82].links.n = {}
          region.rooms[82].links.n.to = 797
          region.rooms[82].links.n.con = ""
    region.rooms[83] = {}
      region.rooms[83].path = "fly xi;e;e;n;n;e"
      region.rooms[83].name = "忠烈祠"
      region.rooms[83].zone = "襄阳"
      region.rooms[83].id = 796
      region.rooms[83].desc = "    这里是襄阳城的忠烈祠，十余年来为保卫襄阳而牺牲的烈士遗骨都安葬在这里，每个有爱国心的好汉到这都会来祭奠一下忠魂。"
      region.rooms[83].exits = "west"
      region.rooms[83].links = {}
        region.rooms[83].links.w = {}
          region.rooms[83].links.w.to = 795
          region.rooms[83].links.w.con = ""
    region.rooms[84] = {}
      region.rooms[84].path = "fly xi;e;e;n;n;n"
      region.rooms[84].name = "大街口"
      region.rooms[84].zone = "襄阳"
      region.rooms[84].id = 797
      region.rooms[84].desc = "    因为这儿是十字街口，所以非常热闹。小商小贩们在向行人吆喝着，兜售他们的商品。虽然襄阳饱受蒙古军侵扰，但这儿看不出人们有丝毫的紧张，好象他们已司空见惯、习以为常了。北面和东面是小弄，许多襄阳城的老百姓住在里面，南面和西面是青石铺就的大街。"
      region.rooms[84].exits = "south|north|east|west"
      region.rooms[84].links = {}
        region.rooms[84].links.e = {}
          region.rooms[84].links.e.to = 798
          region.rooms[84].links.e.con = ""
        region.rooms[84].links.s = {}
          region.rooms[84].links.s.to = 795
          region.rooms[84].links.s.con = ""
        region.rooms[84].links.w = {}
          region.rooms[84].links.w.to = 800
          region.rooms[84].links.w.con = ""
        region.rooms[84].links.n = {}
          region.rooms[84].links.n.to = 799
          region.rooms[84].links.n.con = ""
    region.rooms[85] = {}
      region.rooms[85].path = "fly xi;e;e;n;n;n;e"
      region.rooms[85].name = "胡同"
      region.rooms[85].zone = "襄阳"
      region.rooms[85].id = 798
      region.rooms[85].desc = "    这里是襄阳城内老百姓的居住区。只见小弄两边是有些小店面，有米行、小杂货铺等。一些居民从这里进进出出。"
      region.rooms[85].exits = "west"
      region.rooms[85].links = {}
        region.rooms[85].links.w = {}
          region.rooms[85].links.w.to = 797
          region.rooms[85].links.w.con = ""
    region.rooms[86] = {}
      region.rooms[86].path = "fly xi;e;e;n;n;n;n"
      region.rooms[86].name = "胡同"
      region.rooms[86].zone = "襄阳"
      region.rooms[86].id = 799
      region.rooms[86].desc = "    这里是襄阳城内老百姓的居住区。只见小弄两边是有些小店面，有米行、小杂货铺等。一些居民从这里进进出出。"
      region.rooms[86].exits = "south"
      region.rooms[86].links = {}
        region.rooms[86].links.s = {}
          region.rooms[86].links.s.to = 797
          region.rooms[86].links.s.con = ""
    region.rooms[87] = {}
      region.rooms[87].path = "fly xi;e;e;n;n;n;w"
      region.rooms[87].name = "北内大街"
      region.rooms[87].zone = "襄阳"
      region.rooms[87].id = 800
      region.rooms[87].desc = "    这是一条用青石铺就的大道。只见北面不时的有马车飞奔而出，噢，北面是车行。向西就是丁字街口，东面也是一个大街口，你好象看到一条大街通向南面。南面是一堵上盖红色琉璃瓦的高墙，里面是襄阳守城大将王坚的府邸。"
      region.rooms[87].exits = "north|east|west"
      region.rooms[87].links = {}
        region.rooms[87].links.e = {}
          region.rooms[87].links.e.to = 797
          region.rooms[87].links.e.con = ""
        region.rooms[87].links.w = {}
          region.rooms[87].links.w.to = 724
          region.rooms[87].links.w.con = ""
        region.rooms[87].links.n = {}
          region.rooms[87].links.n.to = 801
          region.rooms[87].links.n.con = ""
    region.rooms[88] = {}
      region.rooms[88].path = "fly xi;e;e;n;n;n;w;n"
      region.rooms[88].name = "马厩"
      region.rooms[88].zone = "襄阳"
      region.rooms[88].id = 801
      region.rooms[88].desc = "    这里是襄阳城内唯一一家车马行。你可花钱租辆马车到各个地方去，能节约不少体力。近来因为郭夫人----黄蓉正在组织人力四处搜集防城材料，马夫积极响应，免费提供推车来运送各种防城材料。    西边马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。"
      region.rooms[88].exits = "south"
      region.rooms[88].links = {}
        region.rooms[88].links.s = {}
          region.rooms[88].links.s.to = 800
          region.rooms[88].links.s.con = ""
    region.rooms[89] = {}
      region.rooms[89].path = "fly xi;e;e;n;n;n;w;w;n;n;wu"
      region.rooms[89].name = "石阶"
      region.rooms[89].zone = "襄阳"
      region.rooms[89].id = 802
      region.rooms[89].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[89].exits = "westup|eastdown"
      region.rooms[89].links = {}
        region.rooms[89].links.ed = {}
          region.rooms[89].links.ed.to = 720
          region.rooms[89].links.ed.con = ""
        region.rooms[89].links.wu = {}
          region.rooms[89].links.wu.to = 803
          region.rooms[89].links.wu.con = ""
    region.rooms[90] = {}
      region.rooms[90].path = "fly xi;e;e;n;n;n;w;w;n;n;wu;wu"
      region.rooms[90].name = "石阶"
      region.rooms[90].zone = "襄阳"
      region.rooms[90].id = 803
      region.rooms[90].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[90].exits = "westup|eastdown"
      region.rooms[90].links = {}
        region.rooms[90].links.ed = {}
          region.rooms[90].links.ed.to = 802
          region.rooms[90].links.ed.con = ""
        region.rooms[90].links.wu = {}
          region.rooms[90].links.wu.to = 804
          region.rooms[90].links.wu.con = ""
    region.rooms[91] = {}
      region.rooms[91].path = "fly xi;w;w;w;w;nu;nu;nu;nu;ne;ed"
      region.rooms[91].name = "石阶"
      region.rooms[91].zone = "襄阳"
      region.rooms[91].id = 804
      region.rooms[91].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[91].exits = "westup|eastdown"
      region.rooms[91].links = {}
        region.rooms[91].links.ed = {}
          region.rooms[91].links.ed.to = 803
          region.rooms[91].links.ed.con = ""
        region.rooms[91].links.wu = {}
          region.rooms[91].links.wu.to = 805
          region.rooms[91].links.wu.con = ""
    region.rooms[92] = {}
      region.rooms[92].path = "fly xi;w;w;w;w;nu;nu;nu;nu;ne"
      region.rooms[92].name = "北城头"
      region.rooms[92].zone = "襄阳"
      region.rooms[92].id = 805
      region.rooms[92].desc = "    这里是襄阳的北城头。一些宋兵正在城头巡逻，一个牙将正在这儿负责接受各种守城材料，一些弓箭手正拈弓搭箭紧盯着城下的动静。"
      region.rooms[92].exits = "eastdown|southwest"
      region.rooms[92].links = {}
        region.rooms[92].links.ed = {}
          region.rooms[92].links.ed.to = 804
          region.rooms[92].links.ed.con = ""
        region.rooms[92].links.sw = {}
          region.rooms[92].links.sw.to = 806
          region.rooms[92].links.sw.con = ""
    region.rooms[93] = {}
      region.rooms[93].path = "fly xi;w;w;w;w;nu;nu;nu;nu"
      region.rooms[93].name = "西城头"
      region.rooms[93].zone = "襄阳"
      region.rooms[93].id = 806
      region.rooms[93].desc = "    这里是襄阳的西城头。一些宋兵正在城头巡逻，一个牙将正在这儿负责接受各种守城材料，一些弓箭手正拈弓搭箭紧盯着城下的动静。"
      region.rooms[93].exits = "southdown|northeast"
      region.rooms[93].links = {}
        region.rooms[93].links.ne = {}
          region.rooms[93].links.ne.to = 805
          region.rooms[93].links.ne.con = ""
        region.rooms[93].links.sd = {}
          region.rooms[93].links.sd.to = 807
          region.rooms[93].links.sd.con = ""
    region.rooms[94] = {}
      region.rooms[94].path = "fly xi;w;w;w;w;nu;nu;nu"
      region.rooms[94].name = "石阶"
      region.rooms[94].zone = "襄阳"
      region.rooms[94].id = 807
      region.rooms[94].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[94].exits = "northup|southdown"
      region.rooms[94].links = {}
        region.rooms[94].links.nu = {}
          region.rooms[94].links.nu.to = 806
          region.rooms[94].links.nu.con = ""
        region.rooms[94].links.sd = {}
          region.rooms[94].links.sd.to = 808
          region.rooms[94].links.sd.con = ""
    region.rooms[95] = {}
      region.rooms[95].path = "fly xi;w;w;w;w;nu;nu"
      region.rooms[95].name = "石阶"
      region.rooms[95].zone = "襄阳"
      region.rooms[95].id = 808
      region.rooms[95].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[95].exits = "northup|southdown"
      region.rooms[95].links = {}
        region.rooms[95].links.nu = {}
          region.rooms[95].links.nu.to = 807
          region.rooms[95].links.nu.con = ""
        region.rooms[95].links.sd = {}
          region.rooms[95].links.sd.to = 809
          region.rooms[95].links.sd.con = ""
    region.rooms[96] = {}
      region.rooms[96].path = "fly xi;w;w;w;w;nu"
      region.rooms[96].name = "石阶"
      region.rooms[96].zone = "襄阳"
      region.rooms[96].id = 809
      region.rooms[96].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[96].exits = "northup|southdown"
      region.rooms[96].links = {}
        region.rooms[96].links.nu = {}
          region.rooms[96].links.nu.to = 808
          region.rooms[96].links.nu.con = ""
        region.rooms[96].links.sd = {}
          region.rooms[96].links.sd.to = 745
          region.rooms[96].links.sd.con = ""
    region.rooms[97] = {}
      region.rooms[97].path = "fly xi;w;w;w;w;su"
      region.rooms[97].name = "石阶"
      region.rooms[97].zone = "襄阳"
      region.rooms[97].id = 810
      region.rooms[97].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[97].exits = "northdown|southup"
      region.rooms[97].links = {}
        region.rooms[97].links.nd = {}
          region.rooms[97].links.nd.to = 745
          region.rooms[97].links.nd.con = ""
        region.rooms[97].links.su = {}
          region.rooms[97].links.su.to = 811
          region.rooms[97].links.su.con = ""
    region.rooms[98] = {}
      region.rooms[98].path = "fly xi;w;w;w;w;su;su"
      region.rooms[98].name = "石阶"
      region.rooms[98].zone = "襄阳"
      region.rooms[98].id = 811
      region.rooms[98].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[98].exits = "northdown|southup"
      region.rooms[98].links = {}
        region.rooms[98].links.su = {}
          region.rooms[98].links.su.to = 812
          region.rooms[98].links.su.con = ""
        region.rooms[98].links.nd = {}
          region.rooms[98].links.nd.to = 810
          region.rooms[98].links.nd.con = ""
    region.rooms[99] = {}
      region.rooms[99].path = "fly xi;w;w;w;w;su;su;su"
      region.rooms[99].name = "石阶"
      region.rooms[99].zone = "襄阳"
      region.rooms[99].id = 812
      region.rooms[99].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[99].exits = "northdown|southup"
      region.rooms[99].links = {}
        region.rooms[99].links.nd = {}
          region.rooms[99].links.nd.to = 811
          region.rooms[99].links.nd.con = ""
        region.rooms[99].links.su = {}
          region.rooms[99].links.su.to = 813
          region.rooms[99].links.su.con = ""
    region.rooms[100] = {}
      region.rooms[100].path = "fly xi;w;w;w;w;su;su;su;su"
      region.rooms[100].name = "西城头"
      region.rooms[100].zone = "襄阳"
      region.rooms[100].id = 813
      region.rooms[100].desc = "    这里是襄阳的西城头。一些宋兵正在城头巡逻，一个牙将正在这儿负责接受各种守城材料，一些弓箭手正拈弓搭箭紧盯着城下的动静。"
      region.rooms[100].exits = "southeast|northdown"
      region.rooms[100].links = {}
        region.rooms[100].links.nd = {}
          region.rooms[100].links.nd.to = 812
          region.rooms[100].links.nd.con = ""
        region.rooms[100].links.se = {}
          region.rooms[100].links.se.to = 814
          region.rooms[100].links.se.con = ""
    region.rooms[101] = {}
      region.rooms[101].path = "fly xi;s;s;s;s;wu;wu;wu;wu"
      region.rooms[101].name = "南城头"
      region.rooms[101].zone = "襄阳"
      region.rooms[101].id = 814
      region.rooms[101].desc = "    这里是襄阳的南城头。一些宋兵正在城头巡逻，一个牙将正在这儿负责接受各种守城材料，一些弓箭手正拈弓搭箭紧盯着城下的动静。"
      region.rooms[101].exits = "northwest|eastdown"
      region.rooms[101].links = {}
        region.rooms[101].links.nw = {}
          region.rooms[101].links.nw.to = 813
          region.rooms[101].links.nw.con = ""
        region.rooms[101].links.ed = {}
          region.rooms[101].links.ed.to = 815
          region.rooms[101].links.ed.con = ""
    region.rooms[102] = {}
      region.rooms[102].path = "fly xi;s;s;s;s;wu;wu;wu"
      region.rooms[102].name = "石阶"
      region.rooms[102].zone = "襄阳"
      region.rooms[102].id = 815
      region.rooms[102].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[102].exits = "westup|eastdown"
      region.rooms[102].links = {}
        region.rooms[102].links.ed = {}
          region.rooms[102].links.ed.to = 816
          region.rooms[102].links.ed.con = ""
        region.rooms[102].links.wu = {}
          region.rooms[102].links.wu.to = 814
          region.rooms[102].links.wu.con = ""
    region.rooms[103] = {}
      region.rooms[103].path = "fly xi;s;s;s;s;wu;wu"
      region.rooms[103].name = "石阶"
      region.rooms[103].zone = "襄阳"
      region.rooms[103].id = 816
      region.rooms[103].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[103].exits = "westup|eastdown"
      region.rooms[103].links = {}
        region.rooms[103].links.ed = {}
          region.rooms[103].links.ed.to = 817
          region.rooms[103].links.ed.con = ""
        region.rooms[103].links.wu = {}
          region.rooms[103].links.wu.to = 815
          region.rooms[103].links.wu.con = ""
    region.rooms[104] = {}
      region.rooms[104].path = "fly xi;s;s;s;s;wu"
      region.rooms[104].name = "石阶"
      region.rooms[104].zone = "襄阳"
      region.rooms[104].id = 817
      region.rooms[104].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[104].exits = "westup|eastdown"
      region.rooms[104].links = {}
        region.rooms[104].links.ed = {}
          region.rooms[104].links.ed.to = 769
          region.rooms[104].links.ed.con = ""
        region.rooms[104].links.wu = {}
          region.rooms[104].links.wu.to = 816
          region.rooms[104].links.wu.con = ""
    region.rooms[105] = {}
      region.rooms[105].path = "fly xi;s;s;s;s;eu"
      region.rooms[105].name = "石阶"
      region.rooms[105].zone = "襄阳"
      region.rooms[105].id = 818
      region.rooms[105].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[105].exits = "eastup|westdown"
      region.rooms[105].links = {}
        region.rooms[105].links.wd = {}
          region.rooms[105].links.wd.to = 769
          region.rooms[105].links.wd.con = ""
        region.rooms[105].links.eu = {}
          region.rooms[105].links.eu.to = 819
          region.rooms[105].links.eu.con = ""
    region.rooms[106] = {}
      region.rooms[106].path = "fly xi;s;s;s;s;eu;eu"
      region.rooms[106].name = "石阶"
      region.rooms[106].zone = "襄阳"
      region.rooms[106].id = 819
      region.rooms[106].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[106].exits = "eastup|westdown"
      region.rooms[106].links = {}
        region.rooms[106].links.wd = {}
          region.rooms[106].links.wd.to = 818
          region.rooms[106].links.wd.con = ""
        region.rooms[106].links.eu = {}
          region.rooms[106].links.eu.to = 820
          region.rooms[106].links.eu.con = ""
    region.rooms[107] = {}
      region.rooms[107].path = "fly xi;s;s;s;s;eu;eu;eu"
      region.rooms[107].name = "石阶"
      region.rooms[107].zone = "襄阳"
      region.rooms[107].id = 820
      region.rooms[107].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[107].exits = "eastup|westdown"
      region.rooms[107].links = {}
        region.rooms[107].links.wd = {}
          region.rooms[107].links.wd.to = 819
          region.rooms[107].links.wd.con = ""
        region.rooms[107].links.eu = {}
          region.rooms[107].links.eu.to = 821
          region.rooms[107].links.eu.con = ""
    region.rooms[108] = {}
      region.rooms[108].path = "fly xi;s;s;s;s;eu;eu;eu;eu"
      region.rooms[108].name = "南城头"
      region.rooms[108].zone = "襄阳"
      region.rooms[108].id = 821
      region.rooms[108].desc = "    这里是襄阳的南城头。一些宋兵正在城头巡逻，一个牙将正在这儿负责接受各种守城材料，一些弓箭手正拈弓搭箭紧盯着城下的动静。"
      region.rooms[108].exits = "northeast|westdown"
      region.rooms[108].links = {}
        region.rooms[108].links.wd = {}
          region.rooms[108].links.wd.to = 820
          region.rooms[108].links.wd.con = ""
        region.rooms[108].links.ne = {}
          region.rooms[108].links.ne.to = 822
          region.rooms[108].links.ne.con = ""
    region.rooms[109] = {}
      region.rooms[109].path = "fly xi;e;e;e;e;su;su;su;su"
      region.rooms[109].name = "东城头"
      region.rooms[109].zone = "襄阳"
      region.rooms[109].id = 822
      region.rooms[109].desc = "    这里是襄阳的东城头。一些宋兵正在城头巡逻，一个牙将正在这儿负责接受各种守城材料，一些弓箭手正拈弓搭箭紧盯着城下的动静。"
      region.rooms[109].exits = "northdown|southwest"
      region.rooms[109].links = {}
        region.rooms[109].links.sw = {}
          region.rooms[109].links.sw.to = 821
          region.rooms[109].links.sw.con = ""
        region.rooms[109].links.nd = {}
          region.rooms[109].links.nd.to = 823
          region.rooms[109].links.nd.con = ""
    region.rooms[110] = {}
      region.rooms[110].path = "fly xi;e;e;e;e;su;su;su"
      region.rooms[110].name = "石阶"
      region.rooms[110].zone = "襄阳"
      region.rooms[110].id = 823
      region.rooms[110].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[110].exits = "northdown|southup"
      region.rooms[110].links = {}
        region.rooms[110].links.su = {}
          region.rooms[110].links.su.to = 822
          region.rooms[110].links.su.con = ""
        region.rooms[110].links.nd = {}
          region.rooms[110].links.nd.to = 824
          region.rooms[110].links.nd.con = ""
    region.rooms[111] = {}
      region.rooms[111].path = "fly xi;e;e;e;e;su;su"
      region.rooms[111].name = "石阶"
      region.rooms[111].zone = "襄阳"
      region.rooms[111].id = 824
      region.rooms[111].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[111].exits = "northdown|southup"
      region.rooms[111].links = {}
        region.rooms[111].links.su = {}
          region.rooms[111].links.su.to = 823
          region.rooms[111].links.su.con = ""
        region.rooms[111].links.nd = {}
          region.rooms[111].links.nd.to = 825
          region.rooms[111].links.nd.con = ""
    region.rooms[112] = {}
      region.rooms[112].path = "fly xi;e;e;e;e;su"
      region.rooms[112].name = "石阶"
      region.rooms[112].zone = "襄阳"
      region.rooms[112].id = 825
      region.rooms[112].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[112].exits = "northdown|southup"
      region.rooms[112].links = {}
        region.rooms[112].links.su = {}
          region.rooms[112].links.su.to = 824
          region.rooms[112].links.su.con = ""
        region.rooms[112].links.nd = {}
          region.rooms[112].links.nd.to = 791
          region.rooms[112].links.nd.con = ""
    region.rooms[113] = {}
      region.rooms[113].path = "fly xi;e;e;e;e;nu"
      region.rooms[113].name = "石阶"
      region.rooms[113].zone = "襄阳"
      region.rooms[113].id = 826
      region.rooms[113].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[113].exits = "northup|southdown"
      region.rooms[113].links = {}
        region.rooms[113].links.sd = {}
          region.rooms[113].links.sd.to = 791
          region.rooms[113].links.sd.con = ""
        region.rooms[113].links.nu = {}
          region.rooms[113].links.nu.to = 827
          region.rooms[113].links.nu.con = ""
    region.rooms[114] = {}
      region.rooms[114].path = "fly xi;e;e;e;e;nu;nu"
      region.rooms[114].name = "石阶"
      region.rooms[114].zone = "襄阳"
      region.rooms[114].id = 827
      region.rooms[114].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[114].exits = "northup|southdown"
      region.rooms[114].links = {}
        region.rooms[114].links.sd = {}
          region.rooms[114].links.sd.to = 826
          region.rooms[114].links.sd.con = ""
        region.rooms[114].links.nu = {}
          region.rooms[114].links.nu.to = 828
          region.rooms[114].links.nu.con = ""
    region.rooms[115] = {}
      region.rooms[115].path = "fly xi;e;e;e;e;nu;nu;nu"
      region.rooms[115].name = "石阶"
      region.rooms[115].zone = "襄阳"
      region.rooms[115].id = 828
      region.rooms[115].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[115].exits = "northup|southdown"
      region.rooms[115].links = {}
        region.rooms[115].links.sd = {}
          region.rooms[115].links.sd.to = 827
          region.rooms[115].links.sd.con = ""
        region.rooms[115].links.nu = {}
          region.rooms[115].links.nu.to = 829
          region.rooms[115].links.nu.con = ""
    region.rooms[116] = {}
      region.rooms[116].path = "fly xi;e;e;e;e;nu;nu;nu;nu"
      region.rooms[116].name = "东城头"
      region.rooms[116].zone = "襄阳"
      region.rooms[116].id = 829
      region.rooms[116].desc = "    这里是襄阳的东城头。一些宋兵正在城头巡逻，一个牙将正在这儿负责接受各种守城材料，一些弓箭手正拈弓搭箭紧盯着城下的动静。"
      region.rooms[116].exits = "northwest|southdown"
      region.rooms[116].links = {}
        region.rooms[116].links.sd = {}
          region.rooms[116].links.sd.to = 828
          region.rooms[116].links.sd.con = ""
        region.rooms[116].links.nw = {}
          region.rooms[116].links.nw.to = 830
          region.rooms[116].links.nw.con = ""
    region.rooms[117] = {}
      region.rooms[117].path = "fly xi;e;e;e;e;nu;nu;nu;nu;nw"
      region.rooms[117].name = "北城头"
      region.rooms[117].zone = "襄阳"
      region.rooms[117].id = 830
      region.rooms[117].desc = "    这里是襄阳的北城头。一些宋兵正在城头巡逻，一个牙将正在这儿负责接受各种守城材料，一些弓箭手正拈弓搭箭紧盯着城下的动静。"
      region.rooms[117].exits = "southeast|westdown"
      region.rooms[117].links = {}
        region.rooms[117].links.wd = {}
          region.rooms[117].links.wd.to = 831
          region.rooms[117].links.wd.con = ""
        region.rooms[117].links.se = {}
          region.rooms[117].links.se.to = 829
          region.rooms[117].links.se.con = ""
    region.rooms[118] = {}
      region.rooms[118].path = "fly xi;e;e;e;e;nu;nu;nu;nu;nw;wd"
      region.rooms[118].name = "石阶"
      region.rooms[118].zone = "襄阳"
      region.rooms[118].id = 831
      region.rooms[118].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[118].exits = "eastup|westdown"
      region.rooms[118].links = {}
        region.rooms[118].links.wd = {}
          region.rooms[118].links.wd.to = 832
          region.rooms[118].links.wd.con = ""
        region.rooms[118].links.eu = {}
          region.rooms[118].links.eu.to = 830
          region.rooms[118].links.eu.con = ""
    region.rooms[119] = {}
      region.rooms[119].path = "fly xi;e;e;e;e;nu;nu;nu;nu;nw;wd;wd"
      region.rooms[119].name = "石阶"
      region.rooms[119].zone = "襄阳"
      region.rooms[119].id = 832
      region.rooms[119].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[119].exits = "eastup|westdown"
      region.rooms[119].links = {}
        region.rooms[119].links.wd = {}
          region.rooms[119].links.wd.to = 833
          region.rooms[119].links.wd.con = ""
        region.rooms[119].links.eu = {}
          region.rooms[119].links.eu.to = 831
          region.rooms[119].links.eu.con = ""
    region.rooms[120] = {}
      region.rooms[120].path = "fly xi;e;e;n;n;n;w;w;n;n;eu"
      region.rooms[120].name = "石阶"
      region.rooms[120].zone = "襄阳"
      region.rooms[120].id = 833
      region.rooms[120].desc = "    这是登向城头的石阶，因为城墙很高，所以很陡。石阶两侧有可供拉车上下的斜坡道。"
      region.rooms[120].exits = "eastup|westdown"
      region.rooms[120].links = {}
        region.rooms[120].links.wd = {}
          region.rooms[120].links.wd.to = 720
          region.rooms[120].links.wd.con = ""
        region.rooms[120].links.eu = {}
          region.rooms[120].links.eu.to = 832
          region.rooms[120].links.eu.con = ""
    region.rooms[121] = {}
      region.rooms[121].path = "fly xi;s;s;s;s;s;s;s;s"
      region.rooms[121].name = "荆州郊外"
      region.rooms[121].zone = "武当山|襄阳"
      region.rooms[121].id = 2979
      region.rooms[121].desc = "    这里是荆州郊外，四周静悄悄的。四周是浓密的树林，阴森森的十分怕人。北边是一条青石大道，东南边有一处废园。"
      region.rooms[121].exits = "north|southeast"
      region.rooms[121].links = {}
        region.rooms[121].links.n = {}
          region.rooms[121].links.n.to = 777
          region.rooms[121].links.n.con = ""
        region.rooms[121].links.se = {}
          region.rooms[121].links.se.to = 2980
          region.rooms[121].links.se.con = ""
    region.rooms[122] = {}
      region.rooms[122].path = "fly xi;s;s;s;s;s;s;s;s;se"
      region.rooms[122].name = "废园"
      region.rooms[122].zone = "武当山|襄阳"
      region.rooms[122].id = 2980
      region.rooms[122].desc = "    荆州废园离万家不远。当日丁典逝世、杀周圻、杀耿天霸、杀马大鸣，都是在这废园之中，但此时，只见荒草如故，遍地瓦砾如故。院子里那株老梅之旁，一个土堆上也长满了荒草，如果不是旁边立着的石板刻着“义兄丁典、义嫂凌霜华之墓 狄云立”，任谁也想不到这就是丁典和凌小姐的衣冠冢之所在。"
      region.rooms[122].exits = "northwest"
      region.rooms[122].links = {}
        region.rooms[122].links.nw = {}
          region.rooms[122].links.nw.to = 2979
          region.rooms[122].links.nw.con = ""
  region.center = 756
return region