local region = {}
  region.cmd = "fly fs;n;w;s;s;s;w"
  region.name = "侠客岛"
  region.id = "xkd"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly fs;n;w;s;s;s;w;e;n"
      region.rooms[1].name = "平原小路"
      region.rooms[1].zone = "佛山|侠客岛"
      region.rooms[1].id = 419
      region.rooms[1].links = {}
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 420
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 418
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "south|north"
      region.rooms[1].desc = "    你走在珠江三角洲的平原小路上。此处向称鱼米之乡，有花果之都美誉，物产丰饶，民风淳朴。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly fs;n;w;s;s;s;w;e"
      region.rooms[2].name = "南海渔村"
      region.rooms[2].zone = "佛山|侠客岛"
      region.rooms[2].id = 420
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 421
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 423
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 419
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "east|north|west"
      region.rooms[2].desc = "    这是南海沿岸的偏僻小村，稀稀落落的几户人家。空地上晾着几顶渔网。南面就是波涛浩淼的南海了。向西走好象还有个渔港。东面是小村的沙滩晒网场。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly fs;n;w;s;s;s;w;e;e"
      region.rooms[3].name = "渔村晒网场"
      region.rooms[3].zone = "佛山|侠客岛"
      region.rooms[3].id = 421
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 420
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 422
          region.rooms[3].links.n.con = ""
      region.rooms[3].exits = "north|west"
      region.rooms[3].desc = "    小村不大，却有个好大的晒网场。几个小孩在场中无忧地玩耍，声音喧闹。靠南海边上，有个渔夫面向大海，悠然垂钓。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly fs;n;w;s;s;s;w;e;e;n"
      region.rooms[4].name = "渔村小屋"
      region.rooms[4].zone = "佛山|侠客岛"
      region.rooms[4].id = 422
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 421
          region.rooms[4].links.s.con = ""
      region.rooms[4].exits = "south"
      region.rooms[4].desc = "    小村的渔民小屋十分简陋，几乎没什么家当，壁上挂满了早用旧了的渔具。大概大人都出海了，只有一个小孩在屋里，看到你进来一脸惊惶。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly fs;n;w;s;s;s;w"
      region.rooms[5].name = "渔港"
      region.rooms[5].zone = "佛山|侠客岛"
      region.rooms[5].id = 423
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 420
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.hi = {}
          region.rooms[5].links.hi.to = 2778
          region.rooms[5].links.hi.con = "a:give shan pai to shi zhe"
      region.rooms[5].exits = "east"
      region.rooms[5].desc = "    这里是个小小渔港。南面海面漂浮着几艘小船，抬眼望，海天相连，无边无际。海鸥掠过浪尖，悠悠翩然。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|"
      region.rooms[6].name = "海滩"
      region.rooms[6].zone = "侠客岛"
      region.rooms[6].id = 2778
      region.rooms[6].links = {}
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 2779
          region.rooms[6].links.s.con = ""
      region.rooms[6].exits = "south"
      region.rooms[6].desc = "    这里就是侠客岛了。北边是一望无际的大海；往南则是一片树林。岛上的空气似乎非常新鲜，咸湿的海风中带着一股花香，这是好大的一片沙滩，东首石崖下停着四十多艘大小的船只(boat)。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s"
      region.rooms[7].name = "小路"
      region.rooms[7].zone = "侠客岛"
      region.rooms[7].id = 2779
      region.rooms[7].links = {}
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 2780
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 2778
          region.rooms[7].links.n.con = ""
      region.rooms[7].exits = "south|north"
      region.rooms[7].desc = "    这是一条弯弯曲曲的小路，通向侠客岛的迎客大厅。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s"
      region.rooms[8].name = "树林"
      region.rooms[8].zone = "侠客岛"
      region.rooms[8].id = 2780
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 2781
          region.rooms[8].links.e.con = ""
      region.rooms[8].exits = "south|north|east|southeast|northeast|west"
      region.rooms[8].desc = "    这是一片茂密的树林，好象被人设计了一种阵，一走进来，你仿佛迷失了方向。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e"
      region.rooms[9].name = "树林"
      region.rooms[9].zone = "侠客岛"
      region.rooms[9].id = 2781
      region.rooms[9].links = {}
        region.rooms[9].links.se = {}
          region.rooms[9].links.se.to = 2782
          region.rooms[9].links.se.con = ""
      region.rooms[9].exits = "south|north|east|southeast|northeast|west"
      region.rooms[9].desc = "    这是一片茂密的树林，好象被人设计了一种阵，一走进来，你仿佛迷失了方向。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se"
      region.rooms[10].name = "树林"
      region.rooms[10].zone = "侠客岛"
      region.rooms[10].id = 2782
      region.rooms[10].links = {}
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 2783
          region.rooms[10].links.w.con = ""
      region.rooms[10].exits = "south|northwest|north|east|southeast|west"
      region.rooms[10].desc = "    这是一片茂密的树林，好象被人设计了一种阵，一走进来，你仿佛迷失了方向。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w"
      region.rooms[11].name = "树林"
      region.rooms[11].zone = "侠客岛"
      region.rooms[11].id = 2783
      region.rooms[11].links = {}
        region.rooms[11].links.nw = {}
          region.rooms[11].links.nw.to = 2784
          region.rooms[11].links.nw.con = ""
      region.rooms[11].exits = "south|northwest|north|east|southeast|west"
      region.rooms[11].desc = "    这是一片茂密的树林，好象被人设计了一种阵，一走进来，你仿佛迷失了方向。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw"
      region.rooms[12].name = "树林"
      region.rooms[12].zone = "侠客岛"
      region.rooms[12].id = 2784
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 2785
          region.rooms[12].links.e.con = ""
      region.rooms[12].exits = "south|northwest|north|east|southeast|west"
      region.rooms[12].desc = "    这是一片茂密的树林，好象被人设计了一种阵，一走进来，你仿佛迷失了方向。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e"
      region.rooms[13].name = "树林"
      region.rooms[13].zone = "侠客岛"
      region.rooms[13].id = 2785
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 2786
          region.rooms[13].links.s.con = ""
      region.rooms[13].exits = "south|northwest|north|east|southeast|west"
      region.rooms[13].desc = "    这是一片茂密的树林，好象被人设计了一种阵,一走进来，你仿佛迷失了方向。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s"
      region.rooms[14].name = "树林"
      region.rooms[14].zone = "侠客岛"
      region.rooms[14].id = 2786
      region.rooms[14].links = {}
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 2787
          region.rooms[14].links.s.con = ""
        region.rooms[14].links.n = {}
          region.rooms[14].links.n.to = 2785
          region.rooms[14].links.n.con = ""
      region.rooms[14].exits = "south|north"
      region.rooms[14].desc = "    终于走出了树林，你不禁长长的松了口气。和煦的阳光照在你的身上，使你感到无比的温暖。南边是一座高耸的石山，山上郁郁苍苍，生满树木。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s"
      region.rooms[15].name = "山门"
      region.rooms[15].zone = "侠客岛"
      region.rooms[15].id = 2787
      region.rooms[15].links = {}
        region.rooms[15].links.su = {}
          region.rooms[15].links.su.to = 2788
          region.rooms[15].links.su.con = ""
        region.rooms[15].links.n = {}
          region.rooms[15].links.n.to = 2786
          region.rooms[15].links.n.con = ""
      region.rooms[15].exits = "north|southup"
      region.rooms[15].desc = "    你的面前是一座林木繁茂的高山，几座山峰在云雾中隐约可见，一条山径向山上延伸，不时有几个江湖好汉从你身边走过，他们都是到侠客岛来专研武功的。石壁上刻着三个大字 \"侠客岛\" ，这就是江湖上传闻的侠客岛。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su"
      region.rooms[16].name = "山路"
      region.rooms[16].zone = "侠客岛"
      region.rooms[16].id = 2788
      region.rooms[16].links = {}
        region.rooms[16].links.su = {}
          region.rooms[16].links.su.to = 2789
          region.rooms[16].links.su.con = ""
        region.rooms[16].links.nd = {}
          region.rooms[16].links.nd.to = 2787
          region.rooms[16].links.nd.con = ""
      region.rooms[16].exits = "northdown|southup"
      region.rooms[16].desc = "    走在青石铺成的小路上，脚步十分轻捷。两旁都是密林，枝叶遮天蔽日，阴沉沉的很不舒服。林中鸟雀叽喳，与呼呼的风声混成一片。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su"
      region.rooms[17].name = "山路"
      region.rooms[17].zone = "侠客岛"
      region.rooms[17].id = 2789
      region.rooms[17].links = {}
        region.rooms[17].links.su = {}
          region.rooms[17].links.su.to = 2790
          region.rooms[17].links.su.con = ""
        region.rooms[17].links.nd = {}
          region.rooms[17].links.nd.to = 2788
          region.rooms[17].links.nd.con = ""
      region.rooms[17].exits = "northdown|southup"
      region.rooms[17].desc = "    小路曲曲折折地通向山顶，脚步声惊起一群飞鸟，扑簌簌地消失在空中。空气中却有些腥气，路边草丛间不时传来沙沙的轻响，可能是毒蛇，还是快点离开的好。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su"
      region.rooms[18].name = "山路"
      region.rooms[18].zone = "侠客岛"
      region.rooms[18].id = 2790
      region.rooms[18].links = {}
        region.rooms[18].links.su = {}
          region.rooms[18].links.su.to = 2791
          region.rooms[18].links.su.con = ""
        region.rooms[18].links.nd = {}
          region.rooms[18].links.nd.to = 2789
          region.rooms[18].links.nd.con = ""
      region.rooms[18].exits = "southup|northdown"
      region.rooms[18].desc = "    这是通往山顶的小路，路旁杂草丛生，夹杂着一些不知名的野花。四周静悄悄地没有人声。你深深吸口气，一阵山野的芬芳直入心扉。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su"
      region.rooms[19].name = "山路"
      region.rooms[19].zone = "侠客岛"
      region.rooms[19].id = 2791
      region.rooms[19].links = {}
        region.rooms[19].links.sd = {}
          region.rooms[19].links.sd.to = 2792
          region.rooms[19].links.sd.con = ""
        region.rooms[19].links.nd = {}
          region.rooms[19].links.nd.to = 2790
          region.rooms[19].links.nd.con = ""
      region.rooms[19].exits = "southdown|northdown"
      region.rooms[19].desc = "    你走在一条岩石嶙峋的山道上，左临深涧，涧水缓急，激石有声。右边是悬崖，抬头隐约可见笼罩在云雾中的山峰，一路沿着山潼渐行渐高。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd"
      region.rooms[20].name = "瀑布"
      region.rooms[20].zone = "侠客岛"
      region.rooms[20].id = 2792
      region.rooms[20].links = {}
        region.rooms[20].links.nu = {}
          region.rooms[20].links.nu.to = 2791
          region.rooms[20].links.nu.con = ""
        region.rooms[20].links.sd = {}
          region.rooms[20].links.sd.to = 2793
          region.rooms[20].links.sd.con = ""
        region.rooms[20].links["jump pubu"] = {}
          region.rooms[20].links["jump pubu"].to = 2831
          region.rooms[20].links["jump pubu"].con = ""
      region.rooms[20].exits = "northup|southdown"
      region.rooms[20].desc = "    你猛听得水声响亮，轰轰隆隆，便如潮水大至一般，抬头一看，只见一条大瀑布(pubu)，犹如银河倒悬，从高崖上直泻下来下面是万丈悬崖(xuanya)，云雾弥漫，望不到尽头!!!"
    region.rooms[21] = {}
      region.rooms[21].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd"
      region.rooms[21].name = "望梅亭"
      region.rooms[21].zone = "侠客岛"
      region.rooms[21].id = 2793
      region.rooms[21].links = {}
        region.rooms[21].links.e = {}
          region.rooms[21].links.e.to = 2794
          region.rooms[21].links.e.con = ""
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 2817
          region.rooms[21].links.s.con = ""
        region.rooms[21].links.nu = {}
          region.rooms[21].links.nu.to = 2792
          region.rooms[21].links.nu.con = ""
      region.rooms[21].exits = "south|east|northup"
      region.rooms[21].desc = "    这是一座比较古朴的小亭，似乎常有人打扫(saodi)。“望梅亭”三字则是木岛主的亲笔，亭虽小却透着一股优雅的气息，与侠客岛的武人气息相互映忖，显得别有格调。望梅亭正对着一个大瀑布，但瀑布的声音传到这里却不震耳，反而令人觉得格外的清爽!亭的西面是一条小土路。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;e"
      region.rooms[22].name = "土路"
      region.rooms[22].zone = "侠客岛"
      region.rooms[22].id = 2794
      region.rooms[22].links = {}
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 2793
          region.rooms[22].links.w.con = ""
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 2795
          region.rooms[22].links.e.con = ""
      region.rooms[22].exits = "east|west"
      region.rooms[22].desc = "    这是一段窄窄的土路，东边是一块草地，西面则是一座小亭子，这里隐约可以听到瀑布的水响。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;e;e"
      region.rooms[23].name = "土路"
      region.rooms[23].zone = "侠客岛"
      region.rooms[23].id = 2795
      region.rooms[23].links = {}
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 2794
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 2796
          region.rooms[23].links.e.con = ""
      region.rooms[23].exits = "east|west"
      region.rooms[23].desc = "    这是一段窄窄的土路，东边是一块草地，西面则是一座小亭子，这里隐约可以听到瀑布的水响。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;e;e;e"
      region.rooms[24].name = "草地"
      region.rooms[24].zone = "侠客岛"
      region.rooms[24].id = 2796
      region.rooms[24].links = {}
        region.rooms[24].links.w = {}
          region.rooms[24].links.w.to = 2795
          region.rooms[24].links.w.con = ""
        region.rooms[24].links.e = {}
          region.rooms[24].links.e.to = 2797
          region.rooms[24].links.e.con = ""
      region.rooms[24].exits = "east|west"
      region.rooms[24].desc = "    这里是一遍绿茵茵的草地，像是一方绿色的毯子铺在地上。草丛中开着一些不知名的小花，有红的、黄的，还有紫的。花瓣上、草叶上的露珠闪着晶莹的光。草地上好象还有些有用的药草。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;e;e;e;e"
      region.rooms[25].name = "山脚下"
      region.rooms[25].zone = "侠客岛"
      region.rooms[25].id = 2797
      region.rooms[25].links = {}
        region.rooms[25].links.su = {}
          region.rooms[25].links.su.to = 2812
          region.rooms[25].links.su.con = ""
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 2796
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 2798
          region.rooms[25].links.n.con = ""
      region.rooms[25].exits = "north|southup|west"
      region.rooms[25].desc = "    这里是侠客岛上的一座小山的山脚，从这里望去，只见小山虽小却颇陡峻，悬崖峭壁颇多。附近好象有些有用的药草。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;e;e;e;e;n"
      region.rooms[26].name = "小路"
      region.rooms[26].zone = "侠客岛"
      region.rooms[26].id = 2798
      region.rooms[26].links = {}
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 2797
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 2799
          region.rooms[26].links.e.con = ""
      region.rooms[26].exits = "south|east"
      region.rooms[26].desc = "    这是一条弯弯曲曲的小路，南面是一座小山，东面则是海边的礁石堆。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;e;e;e;e;n;e"
      region.rooms[27].name = "礁石"
      region.rooms[27].zone = "侠客岛"
      region.rooms[27].id = 2799
      region.rooms[27].links = {}
        region.rooms[27].links.nw = {}
          region.rooms[27].links.nw.to = 2811
          region.rooms[27].links.nw.con = ""
        region.rooms[27].links.s = {}
          region.rooms[27].links.s.to = 2800
          region.rooms[27].links.s.con = ""
        region.rooms[27].links.w = {}
          region.rooms[27].links.w.to = 2798
          region.rooms[27].links.w.con = ""
      region.rooms[27].exits = "south|northwest|west"
      region.rooms[27].desc = "    这里是海边礁石堆，四周都是大大小小的岩石，看起来这里相当危险，附近的海面还漂着几根烂木头，好象曾经是渔船的部件。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;e;e;e;e;n;e;s"
      region.rooms[28].name = "礁石"
      region.rooms[28].zone = "侠客岛"
      region.rooms[28].id = 2800
      region.rooms[28].links = {}
        region.rooms[28].links.eu = {}
          region.rooms[28].links.eu.to = 2801
          region.rooms[28].links.eu.con = ""
        region.rooms[28].links.s = {}
          region.rooms[28].links.s.to = 2802
          region.rooms[28].links.s.con = ""
        region.rooms[28].links.n = {}
          region.rooms[28].links.n.to = 2799
          region.rooms[28].links.n.con = ""
      region.rooms[28].exits = "south|north|eastup"
      region.rooms[28].desc = "    这里是海边礁石堆，四周都是大大小小的岩石，看起来这里相当危险，附近的海面还漂着几根烂木头，好象曾经是渔船的部件。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;e;e;e;e;n;e;s;eu"
      region.rooms[29].name = "大礁石"
      region.rooms[29].zone = "侠客岛"
      region.rooms[29].id = 2801
      region.rooms[29].links = {}
        region.rooms[29].links.wd = {}
          region.rooms[29].links.wd.to = 2800
          region.rooms[29].links.wd.con = ""
      region.rooms[29].exits = "westdown"
      region.rooms[29].desc = "    这块礁石特别大，很适合在此垂钓(chuidiao)。这里已有好几人坐此垂钓，看他们的收获颇丰富。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;s;s;e;e;ne"
      region.rooms[30].name = "礁石"
      region.rooms[30].zone = "侠客岛"
      region.rooms[30].id = 2802
      region.rooms[30].links = {}
        region.rooms[30].links.sw = {}
          region.rooms[30].links.sw.to = 2803
          region.rooms[30].links.sw.con = ""
        region.rooms[30].links.n = {}
          region.rooms[30].links.n.to = 2800
          region.rooms[30].links.n.con = ""
      region.rooms[30].exits = "north|southwest"
      region.rooms[30].desc = "    这里是海边礁石堆，四周都是大大小小的岩石，看起来这里相当危险，附近的海面还漂着几根烂木头，好象曾经是渔船的部件。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;s;s;e;e"
      region.rooms[31].name = "沙滩"
      region.rooms[31].zone = "侠客岛"
      region.rooms[31].id = 2803
      region.rooms[31].links = {}
        region.rooms[31].links.ne = {}
          region.rooms[31].links.ne.to = 2802
          region.rooms[31].links.ne.con = ""
        region.rooms[31].links.w = {}
          region.rooms[31].links.w.to = 2804
          region.rooms[31].links.w.con = ""
      region.rooms[31].exits = "northeast|west"
      region.rooms[31].desc = "    这里是侠客岛的沙滩，你可以看到几只海鸥在空中悠闲的飞翔，远远地可以望见几艘渔船，在海面上若隐若现。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;s;s;e"
      region.rooms[32].name = "沙滩"
      region.rooms[32].zone = "侠客岛"
      region.rooms[32].id = 2804
      region.rooms[32].links = {}
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 2803
          region.rooms[32].links.e.con = ""
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 2805
          region.rooms[32].links.w.con = ""
      region.rooms[32].exits = "east|west"
      region.rooms[32].desc = "    这里是侠客岛的沙滩，你可以看到几只海鸥在空中悠闲的飞翔，远远地可以望见几艘渔船，在海面上若隐若现。海边停着几艘破旧的渔船，好象需要修理(repair)。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;s;s"
      region.rooms[33].name = "海滩"
      region.rooms[33].zone = "侠客岛"
      region.rooms[33].id = 2805
      region.rooms[33].links = {}
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 2804
          region.rooms[33].links.e.con = ""
        region.rooms[33].links.nw = {}
          region.rooms[33].links.nw.to = 2806
          region.rooms[33].links.nw.con = ""
        region.rooms[33].links.n = {}
          region.rooms[33].links.n.to = 2830
          region.rooms[33].links.n.con = ""
      region.rooms[33].exits = "northwest|east|north"
      region.rooms[33].desc = "    这里就是侠客岛了。南边是一望无际的大海；往北则是侠客岛的迎客大厅。岛上的空气似乎非常新鲜，咸湿的海风中带着一股花香，这是好大的一片沙滩，东首石崖下停着四十多艘大小的船只(boat)。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;w;s"
      region.rooms[34].name = "海边"
      region.rooms[34].zone = "侠客岛"
      region.rooms[34].id = 2806
      region.rooms[34].links = {}
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 2807
          region.rooms[34].links.n.con = ""
        region.rooms[34].links.se = {}
          region.rooms[34].links.se.to = 2805
          region.rooms[34].links.se.con = ""
      region.rooms[34].exits = "north|enter|southeast"
      region.rooms[34].desc = "    这里是侠客岛的海边，朝着大陆方向，偶尔你可以看见远远的海面上有几艘大船驶过。坐在海边的石头上，你不禁在想，我什么时候到那块大陆上见识一下心目中的英雄。这里是出海打鱼的地方，有几艘渔船停泊在这。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;w"
      region.rooms[35].name = "海边"
      region.rooms[35].zone = "侠客岛"
      region.rooms[35].id = 2807
      region.rooms[35].links = {}
        region.rooms[35].links.e = {}
          region.rooms[35].links.e.to = 2817
          region.rooms[35].links.e.con = ""
        region.rooms[35].links.s = {}
          region.rooms[35].links.s.to = 2806
          region.rooms[35].links.s.con = ""
        region.rooms[35].links.n = {}
          region.rooms[35].links.n.to = 2808
          region.rooms[35].links.n.con = ""
      region.rooms[35].exits = "south|east|north|enter"
      region.rooms[35].desc = "    这里是侠客岛的海边，朝着大陆方向，偶尔你可以看见远远的海面上有几艘大船驶过。坐在海边的石头上，你不禁在想，我什么时候到那块大陆上见识一下心目中的英雄。这里是出海打鱼的地方，有几艘渔船停泊在这。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;w;n"
      region.rooms[36].name = "海边"
      region.rooms[36].zone = "侠客岛"
      region.rooms[36].id = 2808
      region.rooms[36].links = {}
        region.rooms[36].links.s = {}
          region.rooms[36].links.s.to = 2807
          region.rooms[36].links.s.con = ""
        region.rooms[36].links.ne = {}
          region.rooms[36].links.ne.to = 2809
          region.rooms[36].links.ne.con = ""
      region.rooms[36].exits = "south|enter|northeast"
      region.rooms[36].desc = "    这里是侠客岛的海边，朝着大陆方向，偶尔你可以看见远远的海面上有几艘大船驶过。坐在海边的石头上，你不禁在想，我什么时候到那块大陆上见识一下心目中的英雄。这里是出海打鱼的地方，有几艘渔船停泊在这。"
    region.rooms[37] = {}
      region.rooms[37].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;w;n;ne"
      region.rooms[37].name = "沙滩"
      region.rooms[37].zone = "侠客岛"
      region.rooms[37].id = 2809
      region.rooms[37].links = {}
        region.rooms[37].links.e = {}
          region.rooms[37].links.e.to = 2810
          region.rooms[37].links.e.con = ""
        region.rooms[37].links.sw = {}
          region.rooms[37].links.sw.to = 2808
          region.rooms[37].links.sw.con = ""
      region.rooms[37].exits = "east|southwest"
      region.rooms[37].desc = "    这里是侠客岛的沙滩，你可以看到几只海鸥在空中悠闲的飞翔，远远地可以望见几艘渔船，在海面上若隐若现。"
    region.rooms[38] = {}
      region.rooms[38].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;w;n;ne;e"
      region.rooms[38].name = "沙滩"
      region.rooms[38].zone = "侠客岛"
      region.rooms[38].id = 2810
      region.rooms[38].links = {}
        region.rooms[38].links.w = {}
          region.rooms[38].links.w.to = 2809
          region.rooms[38].links.w.con = ""
        region.rooms[38].links.e = {}
          region.rooms[38].links.e.to = 2811
          region.rooms[38].links.e.con = ""
      region.rooms[38].exits = "east|west"
      region.rooms[38].desc = "    这里是侠客岛的沙滩，你可以看到几只海鸥在空中悠闲的飞翔，远远地可以望见几艘渔船，在海面上若隐若现。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;w;n;ne;e;e"
      region.rooms[39].name = "沙滩"
      region.rooms[39].zone = "侠客岛"
      region.rooms[39].id = 2811
      region.rooms[39].links = {}
        region.rooms[39].links.w = {}
          region.rooms[39].links.w.to = 2810
          region.rooms[39].links.w.con = ""
        region.rooms[39].links.se = {}
          region.rooms[39].links.se.to = 2799
          region.rooms[39].links.se.con = ""
      region.rooms[39].exits = "southeast|west"
      region.rooms[39].desc = "    这里是侠客岛的沙滩，你可以看到几只海鸥在空中悠闲的飞翔，远远地可以望见几艘渔船，在海面上若隐若现。"
    region.rooms[40] = {}
      region.rooms[40].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;eu;eu;ed"
      region.rooms[40].name = "山路"
      region.rooms[40].zone = "侠客岛"
      region.rooms[40].id = 2812
      region.rooms[40].links = {}
        region.rooms[40].links.wu = {}
          region.rooms[40].links.wu.to = 2813
          region.rooms[40].links.wu.con = ""
        region.rooms[40].links.nd = {}
          region.rooms[40].links.nd.to = 2797
          region.rooms[40].links.nd.con = ""
      region.rooms[40].exits = "westup|northdown"
      region.rooms[40].desc = "    这是通往山顶的小路，路旁杂草丛生，夹杂着一些不知名的野花。这里看来需要修一修了(xiulu)。四周静悄悄地没有人声。你深深吸口气，一阵山野的芬芳直入心扉。"
    region.rooms[41] = {}
      region.rooms[41].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;eu;eu"
      region.rooms[41].name = "山顶"
      region.rooms[41].zone = "侠客岛"
      region.rooms[41].id = 2813
      region.rooms[41].links = {}
        region.rooms[41].links.ed = {}
          region.rooms[41].links.ed.to = 2812
          region.rooms[41].links.ed.con = ""
        region.rooms[41].links.sd = {}
          region.rooms[41].links.sd.to = 2814
          region.rooms[41].links.sd.con = ""
        region.rooms[41].links.wd = {}
          region.rooms[41].links.wd.to = 2816
          region.rooms[41].links.wd.con = ""
      region.rooms[41].exits = "eastdown|southdown|westdown"
      region.rooms[41].desc = "    这里是侠客岛的一座小山的山顶，四周静悄悄地没有人声。远处，你可以望见另一座山上匹练似挂着一条大瀑布。"
    region.rooms[42] = {}
      region.rooms[42].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;eu;eu;sd"
      region.rooms[42].name = "野林"
      region.rooms[42].zone = "侠客岛"
      region.rooms[42].id = 2814
      region.rooms[42].links = {}
        region.rooms[42].links.nu = {}
          region.rooms[42].links.nu.to = 2813
          region.rooms[42].links.nu.con = ""
        region.rooms[42].links.s = {}
          region.rooms[42].links.s.to = 2815
          region.rooms[42].links.s.con = ""
      region.rooms[42].exits = "south|northup"
      region.rooms[42].desc = "    这里人迹罕至，侠客岛的弟子们通常都不会来这个地方，正因为如此，听说很多仰慕侠客的初出道的少年豪杰们常在此地失踪。但是这里柴木(kanchai)很多。"
    region.rooms[43] = {}
      region.rooms[43].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;eu;eu;sd;s"
      region.rooms[43].name = "海盗窝"
      region.rooms[43].zone = "侠客岛"
      region.rooms[43].id = 2815
      region.rooms[43].links = {}
        region.rooms[43].links.n = {}
          region.rooms[43].links.n.to = 2814
          region.rooms[43].links.n.con = ""
      region.rooms[43].exits = "north"
      region.rooms[43].desc = "    这里乌七八糟的，象是有人居住。边上站着两个彪形大汉正虎视眈眈的盯着你，准备向你下手。哇！你吓了一跳，侠客岛上居然有这么一个海盗窝，赶快离开这里吧！"
    region.rooms[44] = {}
      region.rooms[44].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;eu"
      region.rooms[44].name = "山路"
      region.rooms[44].zone = "侠客岛"
      region.rooms[44].id = 2816
      region.rooms[44].links = {}
        region.rooms[44].links.wd = {}
          region.rooms[44].links.wd.to = 2817
          region.rooms[44].links.wd.con = ""
        region.rooms[44].links.eu = {}
          region.rooms[44].links.eu.to = 2813
          region.rooms[44].links.eu.con = ""
      region.rooms[44].exits = "eastup|westdown"
      region.rooms[44].desc = "    这是通往山顶的小路，路旁杂草丛生，夹杂着一些不知名的野花。这里看来需要修一修了(xiulu)。四周静悄悄地没有人声。你深深吸口气，一阵山野的芬芳直入心扉。"
    region.rooms[45] = {}
      region.rooms[45].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s"
      region.rooms[45].name = "小路"
      region.rooms[45].zone = "侠客岛"
      region.rooms[45].id = 2817
      region.rooms[45].links = {}
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 2818
          region.rooms[45].links.s.con = ""
        region.rooms[45].links.eu = {}
          region.rooms[45].links.eu.to = 2816
          region.rooms[45].links.eu.con = ""
        region.rooms[45].links.w = {}
          region.rooms[45].links.w.to = 2807
          region.rooms[45].links.w.con = ""
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 2793
          region.rooms[45].links.n.con = ""
      region.rooms[45].exits = "south|north|eastup|west"
      region.rooms[45].desc = "    这是一条弯弯曲曲的小路，往南是迎客厅，北面是一座小亭东面是一段山路。"
    region.rooms[46] = {}
      region.rooms[46].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s"
      region.rooms[46].name = "迎客厅"
      region.rooms[46].zone = "侠客岛"
      region.rooms[46].id = 2818
      region.rooms[46].links = {}
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 2830
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.e = {}
          region.rooms[46].links.e.to = 2822
          region.rooms[46].links.e.con = ""
        region.rooms[46].links.u = {}
          region.rooms[46].links.u.to = 2819
          region.rooms[46].links.u.con = ""
        region.rooms[46].links.w = {}
          region.rooms[46].links.w.to = 2826
          region.rooms[46].links.w.con = ""
        region.rooms[46].links.n = {}
          region.rooms[46].links.n.to = 2817
          region.rooms[46].links.n.con = ""
      region.rooms[46].exits = "up|south|east|north|west"
      region.rooms[46].desc = "    这里是侠客岛的迎客大厅，装饰的简单却庄重，来这里的不是江湖上的大人物，就是慕侠客之名而来的年轻少年。两位岛主与众位掌们，高手在研究留在石壁上的神秘武功暂时不见客，但吩咐侠客岛弟子好好招待客人。岛主的得意弟子张三正在接待众人。"
    region.rooms[47] = {}
      region.rooms[47].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;u"
      region.rooms[47].name = "迎客厅二楼"
      region.rooms[47].zone = "侠客岛"
      region.rooms[47].id = 2819
      region.rooms[47].links = {}
        region.rooms[47].links.e = {}
          region.rooms[47].links.e.to = 2820
          region.rooms[47].links.e.con = ""
        region.rooms[47].links.d = {}
          region.rooms[47].links.d.to = 2818
          region.rooms[47].links.d.con = ""
        region.rooms[47].links.u = {}
          region.rooms[47].links.u.to = 2821
          region.rooms[47].links.u.con = ""
      region.rooms[47].exits = "up|east|down"
      region.rooms[47].desc = "    这里是侠客岛的迎客厅二楼，从这里可以眺望海面，阵阵海风吹来，空气格外清新。大厅中央站着一个人，脸色阴沉。东边是工具房。"
    region.rooms[48] = {}
      region.rooms[48].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;u;e"
      region.rooms[48].name = "工具房"
      region.rooms[48].zone = "侠客岛"
      region.rooms[48].id = 2820
      region.rooms[48].links = {}
        region.rooms[48].links.w = {}
          region.rooms[48].links.w.to = 2819
          region.rooms[48].links.w.con = ""
      region.rooms[48].exits = "west"
      region.rooms[48].desc = "    这是工具房，边上站着一个老头，来侠客岛工作的人可以在这领到所需的工具。"
    region.rooms[49] = {}
      region.rooms[49].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;u;u"
      region.rooms[49].name = "迎客厅三楼"
      region.rooms[49].zone = "侠客岛"
      region.rooms[49].id = 2821
      region.rooms[49].links = {}
        region.rooms[49].links.d = {}
          region.rooms[49].links.d.to = 2819
          region.rooms[49].links.d.con = ""
      region.rooms[49].exits = "down"
      region.rooms[49].desc = "    这里是迎客厅的三楼，进门口有一个小案桌，上面垒着一堆书 (shu)，记录了侠客行老玩家们写的这个泥塘过去的一些故事。你可以依号阅读(yuedu)。"
    region.rooms[50] = {}
      region.rooms[50].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;e"
      region.rooms[50].name = "东走廊"
      region.rooms[50].zone = "侠客岛"
      region.rooms[50].id = 2822
      region.rooms[50].links = {}
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 2825
          region.rooms[50].links.e.con = ""
        region.rooms[50].links.s = {}
          region.rooms[50].links.s.to = 2824
          region.rooms[50].links.s.con = ""
        region.rooms[50].links.w = {}
          region.rooms[50].links.w.to = 2818
          region.rooms[50].links.w.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 2823
          region.rooms[50].links.n.con = ""
      region.rooms[50].exits = "south|east|north|west"
      region.rooms[50].desc = "    这时一条笔直的走廊，廊下是一湖池水。湖水映着长长垂柳，碧绿清澈，你能看见一些鱼在游来游去。南面是一个书塾，北面是一个钱庄，东边则是一个大习武场。"
    region.rooms[51] = {}
      region.rooms[51].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;e;n"
      region.rooms[51].name = "钱庄"
      region.rooms[51].zone = "侠客岛"
      region.rooms[51].id = 2823
      region.rooms[51].links = {}
        region.rooms[51].links.s = {}
          region.rooms[51].links.s.to = 2822
          region.rooms[51].links.s.con = ""
      region.rooms[51].exits = "south"
      region.rooms[51].desc = "    这是一家老字号的钱庄，已有几百年的历史，在全国各地都有分店。它发行的银票信誉非常好，通行全国。    在对面的墙上挂了块牌子(paizi)。"
    region.rooms[52] = {}
      region.rooms[52].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;e;s"
      region.rooms[52].name = "书斋"
      region.rooms[52].zone = "侠客岛"
      region.rooms[52].id = 2824
      region.rooms[52].links = {}
        region.rooms[52].links.n = {}
          region.rooms[52].links.n.to = 2822
          region.rooms[52].links.n.con = ""
      region.rooms[52].exits = "north"
      region.rooms[52].desc = "    这里是侠客岛的书斋，窗明几净，一尘不染，是侠客岛弟子读书写字的地方。在这讲学的是岛主特地请来的大学者程颐先生。一张古意盎然的书案放在程先生的前面，案上摆着几本翻开了的线装书籍。在讲堂前左壁嵌着一条学规(xuegui)。"
    region.rooms[53] = {}
      region.rooms[53].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;e;e"
      region.rooms[53].name = "东武场"
      region.rooms[53].zone = "侠客岛"
      region.rooms[53].id = 2825
      region.rooms[53].links = {}
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 2822
          region.rooms[53].links.w.con = ""
      region.rooms[53].exits = "west"
      region.rooms[53].desc = "    这里就是侠客岛弟子的习武场所，正面墙上写着四个大字：                                    止戈为武边上站者一个武师正教导众弟子习武，墙边还贴了张帖子(tiezi)。       "
    region.rooms[54] = {}
      region.rooms[54].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;w"
      region.rooms[54].name = "西走廊"
      region.rooms[54].zone = "侠客岛"
      region.rooms[54].id = 2826
      region.rooms[54].links = {}
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 2818
          region.rooms[54].links.e.con = ""
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 2829
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.s = {}
          region.rooms[54].links.s.to = 2828
          region.rooms[54].links.s.con = ""
        region.rooms[54].links.n = {}
          region.rooms[54].links.n.to = 2827
          region.rooms[54].links.n.con = ""
      region.rooms[54].exits = "south|east|north|west"
      region.rooms[54].desc = "    这时一条笔直的走廊，廊下是一湖池水。湖水映着长长垂柳，碧绿清澈，你能看见一些鱼在游来游去。南面是一个卧房，北面是一个饭堂，西边则是一个大习武场。"
    region.rooms[55] = {}
      region.rooms[55].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;w;n"
      region.rooms[55].name = "膳堂"
      region.rooms[55].zone = "侠客岛"
      region.rooms[55].id = 2827
      region.rooms[55].links = {}
        region.rooms[55].links.s = {}
          region.rooms[55].links.s.to = 2826
          region.rooms[55].links.s.con = ""
      region.rooms[55].exits = "south"
      region.rooms[55].desc = "    这儿是侠客岛的膳堂，一般只有白天有几个烧饭师傅在烧火做饭，供应（serve）伙食，到了晚上就看你的运气了。你也可以在这装些清水(fill)。"
    region.rooms[56] = {}
      region.rooms[56].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;w;s"
      region.rooms[56].name = "卧房"
      region.rooms[56].zone = "侠客岛"
      region.rooms[56].id = 2828
      region.rooms[56].links = {}
        region.rooms[56].links.n = {}
          region.rooms[56].links.n.to = 2826
          region.rooms[56].links.n.con = ""
      region.rooms[56].exits = "north"
      region.rooms[56].desc = "    这是间整洁的厢房，因门窗常闭着，光线很昏暗。房里别无他物，只有两边放着几张收拾得舒舒服服的大床，看着就让人想睡觉。"
    region.rooms[57] = {}
      region.rooms[57].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;w;w"
      region.rooms[57].name = "西武场"
      region.rooms[57].zone = "侠客岛"
      region.rooms[57].id = 2829
      region.rooms[57].links = {}
        region.rooms[57].links.e = {}
          region.rooms[57].links.e.to = 2826
          region.rooms[57].links.e.con = ""
      region.rooms[57].exits = "east"
      region.rooms[57].desc = "    这里就是侠客岛弟子的习武场所，正面墙上写着四个大字：                                    仁心为侠边上站者一个武师正教导众弟子习武，墙边还贴了张帖子(tiezi)。       "
    region.rooms[58] = {}
      region.rooms[58].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;sd;s;s;s"
      region.rooms[58].name = "小路"
      region.rooms[58].zone = "侠客岛"
      region.rooms[58].id = 2830
      region.rooms[58].links = {}
        region.rooms[58].links.s = {}
          region.rooms[58].links.s.to = 2805
          region.rooms[58].links.s.con = ""
        region.rooms[58].links.n = {}
          region.rooms[58].links.n.to = 2818
          region.rooms[58].links.n.con = ""
      region.rooms[58].exits = "south|north"
      region.rooms[58].desc = "    这是一条弯弯曲曲的小路，通向侠客岛的迎客大厅。"
    region.rooms[59] = {}
      region.rooms[59].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu"
      region.rooms[59].name = "甬道"
      region.rooms[59].zone = "侠客岛"
      region.rooms[59].id = 2831
      region.rooms[59].links = {}
        region.rooms[59].links.s = {}
          region.rooms[59].links.s.to = 2832
          region.rooms[59].links.s.con = ""
        region.rooms[59].links.out = {}
          region.rooms[59].links.out.to = 2792
          region.rooms[59].links.out.con = ""
      region.rooms[59].exits = "south|out"
      region.rooms[59].desc = "    这是一条长长的甬道，两边点着油灯，光线虽暗，却也可辨道路，外面隐约能听见瀑布的隆隆水声，洞口水花飞溅，地面甚是湿润。"
    region.rooms[60] = {}
      region.rooms[60].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s"
      region.rooms[60].name = "甬道"
      region.rooms[60].zone = "侠客岛"
      region.rooms[60].id = 2832
      region.rooms[60].links = {}
        region.rooms[60].links.s = {}
          region.rooms[60].links.s.to = 2833
          region.rooms[60].links.s.con = ""
        region.rooms[60].links.n = {}
          region.rooms[60].links.n.to = 2831
          region.rooms[60].links.n.con = ""
      region.rooms[60].exits = "south|north"
      region.rooms[60].desc = "    这是一条长长的甬道，两边点着油灯，光线虽暗，却也可辨道路，甬道依着山腹中天然洞穴修凿而成，此处开凿的豁然开朗，有很多的江湖豪杰在此休息。"
    region.rooms[61] = {}
      region.rooms[61].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s"
      region.rooms[61].name = "石洞"
      region.rooms[61].zone = "侠客岛"
      region.rooms[61].id = 2833
      region.rooms[61].links = {}
        region.rooms[61].links.e = {}
          region.rooms[61].links.e.to = 2842
          region.rooms[61].links.e.con = ""
        region.rooms[61].links.s = {}
          region.rooms[61].links.s.to = 2834
          region.rooms[61].links.s.con = ""
        region.rooms[61].links.n = {}
          region.rooms[61].links.n.to = 2832
          region.rooms[61].links.n.con = ""
      region.rooms[61].exits = "south|north|east"
      region.rooms[61].desc = "    这是一个石洞，也不知走了多久，只觉越走越低，洞中出现了流水之声，淙淙争争，清脆悦耳，如击玉磬。"
    region.rooms[62] = {}
      region.rooms[62].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;s"
      region.rooms[62].name = "石洞"
      region.rooms[62].zone = "侠客岛"
      region.rooms[62].id = 2834
      region.rooms[62].links = {}
        region.rooms[62].links.s = {}
          region.rooms[62].links.s.to = 2835
          region.rooms[62].links.s.con = ""
        region.rooms[62].links.n = {}
          region.rooms[62].links.n.to = 2833
          region.rooms[62].links.n.con = ""
      region.rooms[62].exits = "south|north"
      region.rooms[62].desc = "    这是一个石洞，略显狭窄，仅容两人并肩而过。顶壁也甚是低矮，伸手便可触及。油灯晃动，在身后拉出长长的阴影。脚步踢嗒石洞彼端响起阵阵回声，感觉有些异样。"
    region.rooms[63] = {}
      region.rooms[63].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;s;s"
      region.rooms[63].name = "石洞"
      region.rooms[63].zone = "侠客岛"
      region.rooms[63].id = 2835
      region.rooms[63].links = {}
        region.rooms[63].links.w = {}
          region.rooms[63].links.w.to = 2836
          region.rooms[63].links.w.con = ""
        region.rooms[63].links.n = {}
          region.rooms[63].links.n.to = 2834
          region.rooms[63].links.n.con = ""
      region.rooms[63].exits = "north|west"
      region.rooms[63].desc = "    这是一个石洞，两旁是光滑的石壁，洞内干干净净，一尘不染却不见一人，洞内周围有灯球火把，把石洞照耀明亮非凡。"
    region.rooms[64] = {}
      region.rooms[64].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;s;s;w"
      region.rooms[64].name = "石洞"
      region.rooms[64].zone = "侠客岛"
      region.rooms[64].id = 2836
      region.rooms[64].links = {}
        region.rooms[64].links.e = {}
          region.rooms[64].links.e.to = 2835
          region.rooms[64].links.e.con = ""
        region.rooms[64].links.s = {}
          region.rooms[64].links.s.to = 2837
          region.rooms[64].links.s.con = "k1:弟子"
      region.rooms[64].exits = "south|east"
      region.rooms[64].desc = "    这是一个石洞，四周是光滑的石壁，石洞内干干净净，一尘不染。两旁点着火把，非常明亮。南面有一扇虚掩的石门(door)。"
    region.rooms[65] = {}
      region.rooms[65].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;s;s;w;|!k1:弟子:s|"
      region.rooms[65].name = "山路"
      region.rooms[65].zone = "侠客岛"
      region.rooms[65].id = 2837
      region.rooms[65].links = {}
        region.rooms[65].links.su = {}
          region.rooms[65].links.su.to = 2838
          region.rooms[65].links.su.con = ""
        region.rooms[65].links.n = {}
          region.rooms[65].links.n.to = 2836
          region.rooms[65].links.n.con = ""
      region.rooms[65].exits = "north|southup"
      region.rooms[65].desc = "    这是侠客岛的后山，你走在一条岩石嶙峋的山道上，这是通向侠客岛 \"望云台\" 的唯一路径，旁边是万丈悬崖，抬头隐约可见笼罩在云雾中的山峰，一条山路环山而行。"
    region.rooms[66] = {}
      region.rooms[66].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;s;s;w;|!k1:弟子:s|;su"
      region.rooms[66].name = "山路"
      region.rooms[66].zone = "侠客岛"
      region.rooms[66].id = 2838
      region.rooms[66].links = {}
        region.rooms[66].links.su = {}
          region.rooms[66].links.su.to = 2839
          region.rooms[66].links.su.con = ""
        region.rooms[66].links.nd = {}
          region.rooms[66].links.nd.to = 2837
          region.rooms[66].links.nd.con = ""
      region.rooms[66].exits = "northdown|southup"
      region.rooms[66].desc = "    你走在一条岩石嶙峋的山道上，这是通向侠客岛望云台的唯一路径，旁边是万丈悬崖，抬头隐约可见笼罩在云雾中的山峰，一条山路环山而行。"
    region.rooms[67] = {}
      region.rooms[67].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;s;s;w;|!k1:弟子:s|;su;su"
      region.rooms[67].name = "夹鳖石"
      region.rooms[67].zone = "侠客岛"
      region.rooms[67].id = 2839
      region.rooms[67].links = {}
        region.rooms[67].links.su = {}
          region.rooms[67].links.su.to = 2840
          region.rooms[67].links.su.con = ""
        region.rooms[67].links.nd = {}
          region.rooms[67].links.nd.to = 2838
          region.rooms[67].links.nd.con = ""
      region.rooms[67].exits = "northdown|southup"
      region.rooms[67].desc = "    这里便是夹鳖石。此处山势陡峭，行人到此无不心惊胆颤，不敢大声说话，只求平安过去。登山的人一个不小心，很容易便会跌堕到崖谷之中。"
    region.rooms[68] = {}
      region.rooms[68].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;s;s;w;|!k1:弟子:s|;su;su;su"
      region.rooms[68].name = "一线天"
      region.rooms[68].zone = "侠客岛"
      region.rooms[68].id = 2840
      region.rooms[68].links = {}
        region.rooms[68].links.su = {}
          region.rooms[68].links.su.to = 2841
          region.rooms[68].links.su.con = ""
        region.rooms[68].links.nd = {}
          region.rooms[68].links.nd.to = 2839
          region.rooms[68].links.nd.con = ""
      region.rooms[68].exits = "northdown|southup"
      region.rooms[68].desc = "    这里便是一线天。此处山势甚是陡峭，两旁都是无底的深渊，中间是一条近似九十度的坡形山路。行人到此无不心惊胆颤，只盯着自己的脚，生怕一不小心掉下深渊。"
    region.rooms[69] = {}
      region.rooms[69].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;s;s;w;|!k1:弟子:s|;su;su;su;su"
      region.rooms[69].name = "望云台"
      region.rooms[69].zone = "侠客岛"
      region.rooms[69].id = 2841
      region.rooms[69].links = {}
        region.rooms[69].links.nd = {}
          region.rooms[69].links.nd.to = 2840
          region.rooms[69].links.nd.con = ""
      region.rooms[69].exits = "northdown"
      region.rooms[69].desc = "    这里就是侠客岛最高的 \"望云台\" 。在这里你可以远望大海，运气好的时候还能看见一大奇景-- \"云海\" 。在石缝之间长着一颗松树，俗称 \"可怜松\" 。在松树周围还顽强的生长着几颗小草(cao)。"
    region.rooms[70] = {}
      region.rooms[70].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e"
      region.rooms[70].name = "洞门"
      region.rooms[70].zone = "侠客岛"
      region.rooms[70].id = 2842
      region.rooms[70].links = {}
        region.rooms[70].links.w = {}
          region.rooms[70].links.w.to = 2833
          region.rooms[70].links.w.con = ""
        region.rooms[70].links.enter = {}
          region.rooms[70].links.enter.to = 2843
          region.rooms[70].links.enter.con = ""
      region.rooms[70].exits = "enter|west"
      region.rooms[70].desc = "    你的面前突然一亮，眼前赫然出现一道玉石砌成的洞门，门额上雕有三个大字迎宾馆，两旁石粱雕龙刻凤，不知凝聚着多少名工巧匠的心血哇！更体现出主人的富有和奢侈。"
    region.rooms[71] = {}
      region.rooms[71].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter"
      region.rooms[71].name = "迎宾馆"
      region.rooms[71].zone = "侠客岛"
      region.rooms[71].id = 2843
      region.rooms[71].links = {}
        region.rooms[71].links.e = {}
          region.rooms[71].links.e.to = 2844
          region.rooms[71].links.e.con = ""
        region.rooms[71].links.s = {}
          region.rooms[71].links.s.to = 2846
          region.rooms[71].links.s.con = ""
        region.rooms[71].links.w = {}
          region.rooms[71].links.w.to = 2845
          region.rooms[71].links.w.con = ""
        region.rooms[71].links.out = {}
          region.rooms[71].links.out.to = 2842
          region.rooms[71].links.out.con = ""
      region.rooms[71].exits = "south|east|out|west"
      region.rooms[71].desc = "    这是一个石洞，地下的青石板铺得甚是整齐，两旁有一些木制家具，整个房间并无特殊之处，但收拾得干干净净，一尘不染。东面是一个小吃部，西面是休息室。"
    region.rooms[72] = {}
      region.rooms[72].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;e"
      region.rooms[72].name = "小吃店"
      region.rooms[72].zone = "侠客岛"
      region.rooms[72].id = 2844
      region.rooms[72].links = {}
        region.rooms[72].links.w = {}
          region.rooms[72].links.w.to = 2843
          region.rooms[72].links.w.con = ""
      region.rooms[72].exits = "west"
      region.rooms[72].desc = "    这个小吃店布置简易，空空的石壁什么也没有，但生意却很好。顾客多是匆匆的江湖人，买点包子、鸡腿、米酒就赶路去了。"
    region.rooms[73] = {}
      region.rooms[73].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;w"
      region.rooms[73].name = "休息室"
      region.rooms[73].zone = "侠客岛"
      region.rooms[73].id = 2845
      region.rooms[73].links = {}
        region.rooms[73].links.e = {}
          region.rooms[73].links.e.to = 2843
          region.rooms[73].links.e.con = ""
      region.rooms[73].exits = "east"
      region.rooms[73].desc = "    这是一间石洞，洞内中间摆着几张大床，几张桌子，看来是个休息的地方，室中光线柔和，使人更增睡意。"
    region.rooms[74] = {}
      region.rooms[74].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s"
      region.rooms[74].name = "石洞"
      region.rooms[74].zone = "侠客岛"
      region.rooms[74].id = 2846
      region.rooms[74].links = {}
        region.rooms[74].links.e = {}
          region.rooms[74].links.e.to = 2847
          region.rooms[74].links.e.con = ""
        region.rooms[74].links.s = {}
          region.rooms[74].links.s.to = 2846
          region.rooms[74].links.s.con = ""
        region.rooms[74].links.w = {}
          region.rooms[74].links.w.to = 2846
          region.rooms[74].links.w.con = ""
        region.rooms[74].links.n = {}
          region.rooms[74].links.n.to = 2843
          region.rooms[74].links.n.con = ""
      region.rooms[74].exits = "south|north|east|west"
      region.rooms[74].desc = "    这是一个石洞，四周点着八盏油灯，使得整个房间非常明亮。山洞中支路甚多，你可要小心，别走错了路。"
    region.rooms[75] = {}
      region.rooms[75].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e"
      region.rooms[75].name = "石洞"
      region.rooms[75].zone = "侠客岛"
      region.rooms[75].id = 2847
      region.rooms[75].links = {}
        region.rooms[75].links.e = {}
          region.rooms[75].links.e.to = 2847
          region.rooms[75].links.e.con = ""
        region.rooms[75].links.s = {}
          region.rooms[75].links.s.to = 2848
          region.rooms[75].links.s.con = ""
        region.rooms[75].links.w = {}
          region.rooms[75].links.w.to = 2847
          region.rooms[75].links.w.con = ""
        region.rooms[75].links.n = {}
          region.rooms[75].links.n.to = 2843
          region.rooms[75].links.n.con = ""
      region.rooms[75].exits = "south|north|east|west"
      region.rooms[75].desc = "    这是一个石洞，四周点着八盏油灯，使得整个房间非常明亮。山洞中支路甚多，你可要小心，别走错了路。"
    region.rooms[76] = {}
      region.rooms[76].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s"
      region.rooms[76].name = "石洞"
      region.rooms[76].zone = "侠客岛"
      region.rooms[76].id = 2848
      region.rooms[76].links = {}
        region.rooms[76].links.e = {}
          region.rooms[76].links.e.to = 2848
          region.rooms[76].links.e.con = ""
        region.rooms[76].links.w = {}
          region.rooms[76].links.w.to = 2849
          region.rooms[76].links.w.con = ""
        region.rooms[76].links.s = {}
          region.rooms[76].links.s.to = 2848
          region.rooms[76].links.s.con = ""
        region.rooms[76].links.n = {}
          region.rooms[76].links.n.to = 2843
          region.rooms[76].links.n.con = ""
      region.rooms[76].exits = "south|north|east|west"
      region.rooms[76].desc = "    这是一个石洞，四周点着八盏油灯，使得整个房间非常明亮。山洞中支路甚多，你可要小心，别走错了路。"
    region.rooms[77] = {}
      region.rooms[77].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w"
      region.rooms[77].name = "石洞"
      region.rooms[77].zone = "侠客岛"
      region.rooms[77].id = 2849
      region.rooms[77].links = {}
        region.rooms[77].links.e = {}
          region.rooms[77].links.e.to = 2849
          region.rooms[77].links.e.con = ""
        region.rooms[77].links.s = {}
          region.rooms[77].links.s.to = 2850
          region.rooms[77].links.s.con = ""
        region.rooms[77].links.w = {}
          region.rooms[77].links.w.to = 2849
          region.rooms[77].links.w.con = ""
        region.rooms[77].links.n = {}
          region.rooms[77].links.n.to = 2843
          region.rooms[77].links.n.con = ""
      region.rooms[77].exits = "south|north|east|west"
      region.rooms[77].desc = "    这是一个石洞，四周点着八盏油灯，使得整个房间非常明亮。山洞中支路甚多，你可要小心，别走错了路。"
    region.rooms[78] = {}
      region.rooms[78].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s"
      region.rooms[78].name = "大厅"
      region.rooms[78].zone = "侠客岛"
      region.rooms[78].id = 2850
      region.rooms[78].links = {}
        region.rooms[78].links.e = {}
          region.rooms[78].links.e.to = 2852
          region.rooms[78].links.e.con = ""
        region.rooms[78].links["push pingfeng;s"] = {}
          region.rooms[78].links["push pingfeng;s"].to = 2853
          region.rooms[78].links["push pingfeng;s"].con = ""
        region.rooms[78].links.w = {}
          region.rooms[78].links.w.to = 2851
          region.rooms[78].links.w.con = ""
        region.rooms[78].links.n = {}
          region.rooms[78].links.n.to = 2849
          region.rooms[78].links.n.con = ""
      region.rooms[78].exits = "east|north|west"
      region.rooms[78].desc = "    这是『侠客岛』的大厅，四周点满了牛油蜡烛，南面放着一个大屏风。洞内摆着一百来张桌子，宾客正络绎进来，数百名黄衣汉子穿索般来去，引导宾客入座。"
    region.rooms[79] = {}
      region.rooms[79].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;w"
      region.rooms[79].name = "武器库"
      region.rooms[79].zone = "侠客岛"
      region.rooms[79].id = 2851
      region.rooms[79].links = {}
        region.rooms[79].links.e = {}
          region.rooms[79].links.e.to = 2850
          region.rooms[79].links.e.con = ""
      region.rooms[79].exits = "east"
      region.rooms[79].desc = "    这里是侠客岛的武器库，架上摆满了各种武器，任由来岛的武士们挑选。"
    region.rooms[80] = {}
      region.rooms[80].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;e"
      region.rooms[80].name = "书房"
      region.rooms[80].zone = "侠客岛"
      region.rooms[80].id = 2852
      region.rooms[80].links = {}
        region.rooms[80].links.w = {}
          region.rooms[80].links.w.to = 2850
          region.rooms[80].links.w.con = ""
      region.rooms[80].exits = "west"
      region.rooms[80].desc = "    这里是书房，靠墙是一排书架，摆满了当今武林各个门派的武功密藉。石洞中间放着石桌和几个石凳，侠客岛龙木二岛主常常在这里读书。"
    region.rooms[81] = {}
      region.rooms[81].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s"
      region.rooms[81].name = "甬道"
      region.rooms[81].zone = "侠客岛"
      region.rooms[81].id = 2853
      region.rooms[81].links = {}
        region.rooms[81].links.s = {}
          region.rooms[81].links.s.to = 2854
          region.rooms[81].links.s.con = ""
        region.rooms[81].links.n = {}
          region.rooms[81].links.n.to = 2850
          region.rooms[81].links.n.con = ""
      region.rooms[81].exits = "south|north"
      region.rooms[81].desc = "    这里往来者甚多，多数是急匆匆武林人物，亦有不少青衣弟子。许多人都手持食物边走边吃，惟恐耽误了时间。几个衣衫褴褛的乞丐便在墙边鼾然入睡。一个小僮踮起脚尖，正在添加灯油。"
    region.rooms[82] = {}
      region.rooms[82].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s"
      region.rooms[82].name = "石门"
      region.rooms[82].zone = "侠客岛"
      region.rooms[82].id = 2854
      region.rooms[82].links = {}
        region.rooms[82].links.enter = {}
          region.rooms[82].links.enter.to = 2855
          region.rooms[82].links.enter.con = ""
        region.rooms[82].links.n = {}
          region.rooms[82].links.n.to = 2853
          region.rooms[82].links.n.con = ""
      region.rooms[82].exits = "north|enter"
      region.rooms[82].desc = "    这里已是甬道尽头，面前一道厚重的石门。门上刻着三个斗大的古篆：「侠客行」。年深日久，那笔划的凹下之处都积满了青苔，越发显得沧桑，你心中的敬意油然而生。    里面是一块大石壁，在石壁下好象有很多人。"
    region.rooms[83] = {}
      region.rooms[83].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter"
      region.rooms[83].name = "石壁"
      region.rooms[83].zone = "侠客岛"
      region.rooms[83].id = 2855
      region.rooms[83].links = {}
        region.rooms[83].links.e = {}
          region.rooms[83].links.e.to = 2856
          region.rooms[83].links.e.con = ""
        region.rooms[83].links.w = {}
          region.rooms[83].links.w.to = 2858
          region.rooms[83].links.w.con = ""
        region.rooms[83].links.s = {}
          region.rooms[83].links.s.to = 2857
          region.rooms[83].links.s.con = ""
        region.rooms[83].links.out = {}
          region.rooms[83].links.out.to = 2854
          region.rooms[83].links.out.con = ""
      region.rooms[83].exits = "south|east|out|west"
      region.rooms[83].desc = "    你的面前是块打磨光滑的大石壁(shibi)。 石壁边上点燃着八根大火把，照耀明亮。石室中已有十多人，有的注目凝思，有的打坐练功，有的毕目喃喃自语，更有几人在大声争辩。"
    region.rooms[84] = {}
      region.rooms[84].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;e"
      region.rooms[84].name = "武场"
      region.rooms[84].zone = "侠客岛"
      region.rooms[84].id = 2856
      region.rooms[84].links = {}
        region.rooms[84].links.w = {}
          region.rooms[84].links.w.to = 2855
          region.rooms[84].links.w.con = ""
      region.rooms[84].exits = "west"
      region.rooms[84].desc = "    这是一个宽大的石洞，足可以装下几百人，两旁放着十八般兵器。四周零散的放着许多椅子，中间一大块铺着猩红色的地毯，武士们可以在这比试武功。"
    region.rooms[85] = {}
      region.rooms[85].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;s"
      region.rooms[85].name = "石室"
      region.rooms[85].zone = "侠客岛"
      region.rooms[85].id = 2857
      region.rooms[85].links = {}
        region.rooms[85].links["move bed"] = {}
          region.rooms[85].links["move bed"].to = 2891
          region.rooms[85].links["move bed"].con = ""
        region.rooms[85].links.n = {}
          region.rooms[85].links.n.to = 2855
          region.rooms[85].links.n.con = ""
      region.rooms[85].exits = "north"
      region.rooms[85].desc = "    这里是一个很小的石室，比之外面的任何一个都要小很多，室中放着一些乱七八遭的家具，墙角边还有一张破烂的小床(bed) ，石室内满是灰尘，已经好久没人来过了，你是不是走错地方了呀。"
    region.rooms[86] = {}
      region.rooms[86].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w"
      region.rooms[86].name = "内厅"
      region.rooms[86].zone = "侠客岛"
      region.rooms[86].id = 2858
      region.rooms[86].links = {}
        region.rooms[86].links.enter = {}
          region.rooms[86].links.enter.to = 2861
          region.rooms[86].links.enter.con = ""
        region.rooms[86].links.e = {}
          region.rooms[86].links.e.to = 2855
          region.rooms[86].links.e.con = ""
        region.rooms[86].links.w = {}
          region.rooms[86].links.w.to = 2859
          region.rooms[86].links.w.con = ""
        region.rooms[86].links.n = {}
          region.rooms[86].links.n.to = 2860
          region.rooms[86].links.n.con = ""
      region.rooms[86].exits = "east|north|enter|west"
      region.rooms[86].desc = "    这是一个石洞，此洞硕大无朋，四周点满了火把，把整个大厅照耀得十分明亮，中间放着很多石桌和石凳，有很多的江湖人物在石室在参悟武功之余，在这里休息一会。"
    region.rooms[87] = {}
      region.rooms[87].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;w"
      region.rooms[87].name = "茶室"
      region.rooms[87].zone = "侠客岛"
      region.rooms[87].id = 2859
      region.rooms[87].links = {}
        region.rooms[87].links.e = {}
          region.rooms[87].links.e.to = 2858
          region.rooms[87].links.e.con = ""
      region.rooms[87].exits = "east"
      region.rooms[87].desc = "    这是一个石洞，三枝红烛照耀得全洞明亮。洞内坐满了人，一个童子忙前忙后，满屋的果香和茶香，沁人心脾。屋里四周得体地摆着些桌子(table)和椅子(chair)。"
    region.rooms[88] = {}
      region.rooms[88].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;n"
      region.rooms[88].name = "休息室"
      region.rooms[88].zone = "侠客岛"
      region.rooms[88].id = 2860
      region.rooms[88].links = {}
        region.rooms[88].links.s = {}
          region.rooms[88].links.s.to = 2858
          region.rooms[88].links.s.con = ""
      region.rooms[88].exits = "south"
      region.rooms[88].desc = "    这是一间石洞，洞内中间摆着几张大床，几张桌子，看来是个休息的地方，室中光线柔和，使人更增睡意。"
    region.rooms[89] = {}
      region.rooms[89].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter"
      region.rooms[89].name = "石洞"
      region.rooms[89].zone = "侠客岛"
      region.rooms[89].id = 2861
      region.rooms[89].links = {}
        region.rooms[89].links.enter = {}
          region.rooms[89].links.enter.to = 2866
          region.rooms[89].links.enter.con = ""
        region.rooms[89].links.s = {}
          region.rooms[89].links.s.to = 2864
          region.rooms[89].links.s.con = ""
        region.rooms[89].links.out = {}
          region.rooms[89].links.out.to = 2858
          region.rooms[89].links.out.con = ""
        region.rooms[89].links.e = {}
          region.rooms[89].links.e.to = 2862
          region.rooms[89].links.e.con = ""
        region.rooms[89].links.w = {}
          region.rooms[89].links.w.to = 2863
          region.rooms[89].links.w.con = ""
        region.rooms[89].links.n = {}
          region.rooms[89].links.n.to = 2865
          region.rooms[89].links.n.con = ""
      region.rooms[89].exits = "south|east|north|enter|west|out"
      region.rooms[89].desc = "    这里依次是六个石洞，各自通向四句诗的石室。后人研习「侠客行」武功，悟出六句总纲，也分别刻在这里。此洞一色青布帷幔，侍立的弟子均是青衣长剑。正面壁上，粗隶刻着前四句诗的总纲「一剑飞鸿」。"
    region.rooms[90] = {}
      region.rooms[90].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;e"
      region.rooms[90].name = "石室"
      region.rooms[90].zone = "侠客岛"
      region.rooms[90].id = 2862
      region.rooms[90].links = {}
        region.rooms[90].links.w = {}
          region.rooms[90].links.w.to = 2861
          region.rooms[90].links.w.con = ""
      region.rooms[90].exits = "west"
      region.rooms[90].desc = "    洞中风声劲急，数道身影正在洞中迅速异常地奔跑，直带得满室生风。一人身法轻灵飘逸，另一人则古朴稳健，更有一人无甚特异之处，却也十分迅捷。几人奔跑中兀自不停争论，而语气甚是平静。旁边石壁(wall)上也是有图有字。"
    region.rooms[91] = {}
      region.rooms[91].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;w"
      region.rooms[91].name = "石室"
      region.rooms[91].zone = "侠客岛"
      region.rooms[91].id = 2863
      region.rooms[91].links = {}
        region.rooms[91].links.e = {}
          region.rooms[91].links.e.to = 2861
          region.rooms[91].links.e.con = ""
      region.rooms[91].exits = "east"
      region.rooms[91].desc = "    此洞中仍是较为拥挤。有几人脚踏北斗七星方位，或正或逆地行走；一名老者端坐于北极星位闭目打坐，头顶隐隐透出丝丝白气另有两个黄衫女子并肩而立，在石壁(wall)上指指点点。"
    region.rooms[92] = {}
      region.rooms[92].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;s"
      region.rooms[92].name = "石室"
      region.rooms[92].zone = "侠客岛"
      region.rooms[92].id = 2864
      region.rooms[92].links = {}
        region.rooms[92].links.n = {}
          region.rooms[92].links.n.to = 2861
          region.rooms[92].links.n.con = ""
      region.rooms[92].exits = "north"
      region.rooms[92].desc = "    进入第二间石室，只觉眼前一花，端的是剑气纵横。数人各持长剑，正在捉对较量，兵刃撞击，铮铮不绝。地上遗弃着几柄长短不一的断剑，墙上也有些兵器劈砍的斑痕。旁边有两位老者正在争论着什麽。石壁(wall)上有若干字迹。"
    region.rooms[93] = {}
      region.rooms[93].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;n"
      region.rooms[93].name = "石室"
      region.rooms[93].zone = "侠客岛"
      region.rooms[93].id = 2865
      region.rooms[93].links = {}
        region.rooms[93].links.s = {}
          region.rooms[93].links.s.to = 2861
          region.rooms[93].links.s.con = ""
      region.rooms[93].exits = "south"
      region.rooms[93].desc = "    这是第一间石室。不少人走来走去，已经颇为拥挤。那些人有的注目凝思，有的打坐练功，有的闭目喃喃自语，更有的正在大声争辩。东面是块打磨光滑的大石壁(wall)，石壁旁点燃着火把，把整间石室照耀得白昼相仿。"
    region.rooms[94] = {}
      region.rooms[94].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter"
      region.rooms[94].name = "石洞"
      region.rooms[94].zone = "侠客岛"
      region.rooms[94].id = 2866
      region.rooms[94].links = {}
        region.rooms[94].links.enter = {}
          region.rooms[94].links.enter.to = 2871
          region.rooms[94].links.enter.con = ""
        region.rooms[94].links.s = {}
          region.rooms[94].links.s.to = 2869
          region.rooms[94].links.s.con = ""
        region.rooms[94].links.out = {}
          region.rooms[94].links.out.to = 2861
          region.rooms[94].links.out.con = ""
        region.rooms[94].links.e = {}
          region.rooms[94].links.e.to = 2867
          region.rooms[94].links.e.con = ""
        region.rooms[94].links.w = {}
          region.rooms[94].links.w.to = 2868
          region.rooms[94].links.w.con = ""
        region.rooms[94].links.n = {}
          region.rooms[94].links.n.to = 2870
          region.rooms[94].links.n.con = ""
      region.rooms[94].exits = "south|east|north|enter|west|out"
      region.rooms[94].desc = "    此洞通向第二组石室。洞中水声淙淙，右面恰巧一道山泉流过。中间四个草书大字深入石壁「飘渺烟云」，两侧均是蓝色帷幔环绕。几名蓝衣弟子侍立。"
    region.rooms[95] = {}
      region.rooms[95].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;e"
      region.rooms[95].name = "石室"
      region.rooms[95].zone = "侠客岛"
      region.rooms[95].id = 2867
      region.rooms[95].links = {}
        region.rooms[95].links.w = {}
          region.rooms[95].links.w.to = 2866
          region.rooms[95].links.w.con = ""
      region.rooms[95].exits = "west"
      region.rooms[95].desc = "    这里亦有数人研习武功。几名女子都显得颇有心得，面色凝重地对照着石壁(wall)练习步法，旁边的两个白衣青年却满脸迷惑，似乎未窥门径。"
    region.rooms[96] = {}
      region.rooms[96].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;w"
      region.rooms[96].name = "石室"
      region.rooms[96].zone = "侠客岛"
      region.rooms[96].id = 2868
      region.rooms[96].links = {}
        region.rooms[96].links.e = {}
          region.rooms[96].links.e.to = 2866
          region.rooms[96].links.e.con = ""
      region.rooms[96].exits = "east"
      region.rooms[96].desc = "    石洞正中，一位白眉僧人和一位青袍之人正比试武功。一对男女在旁边并肩奔行，趋退之际，步法配合甚是和谐。另有一人神色不屑地站在墙角，边指点石壁(wall)，边指摘众人的招式。"
    region.rooms[97] = {}
      region.rooms[97].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;s"
      region.rooms[97].name = "石室"
      region.rooms[97].zone = "侠客岛"
      region.rooms[97].id = 2869
      region.rooms[97].links = {}
        region.rooms[97].links.n = {}
          region.rooms[97].links.n.to = 2866
          region.rooms[97].links.n.con = ""
      region.rooms[97].exits = "north"
      region.rooms[97].desc = "    这间石室中却恰巧无人观看图谱，端的是冷冷清清，隔壁传来隐隐的喧嚣。墙上火把静静地燃烧着，偶尔发出轻微的毕驳之声，空中有阵阵松脂的气味，石壁(wall)也被熏黑了几处。"
    region.rooms[98] = {}
      region.rooms[98].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;n"
      region.rooms[98].name = "石室"
      region.rooms[98].zone = "侠客岛"
      region.rooms[98].id = 2870
      region.rooms[98].links = {}
        region.rooms[98].links.s = {}
          region.rooms[98].links.s.to = 2866
          region.rooms[98].links.s.con = ""
      region.rooms[98].exits = "south"
      region.rooms[98].desc = "    一位仙风道骨的老者正和一位高大的西域人切磋武功，两人均是虚持空剑，招式忽快忽慢，阵阵劲风将室内得火把激荡得明暗不定，石壁(wall)上图案亦是班驳陆离。"
    region.rooms[99] = {}
      region.rooms[99].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter"
      region.rooms[99].name = "石洞"
      region.rooms[99].zone = "侠客岛"
      region.rooms[99].id = 2871
      region.rooms[99].links = {}
        region.rooms[99].links.enter = {}
          region.rooms[99].links.enter.to = 2876
          region.rooms[99].links.enter.con = ""
        region.rooms[99].links.s = {}
          region.rooms[99].links.s.to = 2874
          region.rooms[99].links.s.con = ""
        region.rooms[99].links.out = {}
          region.rooms[99].links.out.to = 2866
          region.rooms[99].links.out.con = ""
        region.rooms[99].links.e = {}
          region.rooms[99].links.e.to = 2872
          region.rooms[99].links.e.con = ""
        region.rooms[99].links.w = {}
          region.rooms[99].links.w.to = 2873
          region.rooms[99].links.w.con = ""
        region.rooms[99].links.n = {}
          region.rooms[99].links.n.to = 2875
          region.rooms[99].links.n.con = ""
      region.rooms[99].exits = "south|east|north|enter|west|out"
      region.rooms[99].desc = "    迎面可见四个行书大字「水银泻地」，极具神韵。洞中陈设奢华，洁白的大理石砖，汉白玉栏杆。几个香炉烟雾缭绕，白衣婢女垂手侍立，依稀是豪门内宅一般。"
    region.rooms[100] = {}
      region.rooms[100].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;e"
      region.rooms[100].name = "石室"
      region.rooms[100].zone = "侠客岛"
      region.rooms[100].id = 2872
      region.rooms[100].links = {}
        region.rooms[100].links.w = {}
          region.rooms[100].links.w.to = 2871
          region.rooms[100].links.w.con = ""
      region.rooms[100].exits = "west"
      region.rooms[100].desc = "    进门便觉得室中潮气极重，呼吸不畅，想来是深入山腹之故。数人也是或坐或立，默不做声地各自研习武功,火把却不知为何少了几支，石壁(wall)上投下了大片阴影。"
    region.rooms[101] = {}
      region.rooms[101].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;w"
      region.rooms[101].name = "石室"
      region.rooms[101].zone = "侠客岛"
      region.rooms[101].id = 2873
      region.rooms[101].links = {}
        region.rooms[101].links.e = {}
          region.rooms[101].links.e.to = 2871
          region.rooms[101].links.e.con = ""
      region.rooms[101].exits = "east"
      region.rooms[101].desc = "    大约是刀法仅绘于此石室之故，这里层层叠叠站了不少人。刀光霍霍，一名藏僧手持大环刀，呼喝之声不绝，与三个少年正斗得走马灯相仿。其中绿衣的少年背靠石壁(wall)，似乎极是吃力。"
    region.rooms[102] = {}
      region.rooms[102].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;s"
      region.rooms[102].name = "石室"
      region.rooms[102].zone = "侠客岛"
      region.rooms[102].id = 2874
      region.rooms[102].links = {}
        region.rooms[102].links.n = {}
          region.rooms[102].links.n.to = 2871
          region.rooms[102].links.n.con = ""
      region.rooms[102].exits = "north"
      region.rooms[102].desc = "    这里却也安静。右面地上一人横卧，似是过度疲倦，已经沉沉睡去。一个布衣男子袖手而立，呆呆地望着石壁(wall)出神他身旁站着一位美貌少妇。旁边的火把将要燃尽，摇曳不定。地上横七竖八丢弃了一些破损的兵刃。"
    region.rooms[103] = {}
      region.rooms[103].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;n"
      region.rooms[103].name = "石室"
      region.rooms[103].zone = "侠客岛"
      region.rooms[103].id = 2875
      region.rooms[103].links = {}
        region.rooms[103].links.s = {}
          region.rooms[103].links.s.to = 2871
          region.rooms[103].links.s.con = ""
      region.rooms[103].exits = "south"
      region.rooms[103].desc = "    这里是石洞深处，较为气闷。此石室内甚是安静，一名虬髯大汉和一名道士相对而立，正在缓缓地推手。一人站在远处墙角，将墙上的火把取下来擎在手中，紧盯着石壁(wall)，鼻子似乎已经贴了上去。"
    region.rooms[104] = {}
      region.rooms[104].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter"
      region.rooms[104].name = "石洞"
      region.rooms[104].zone = "侠客岛"
      region.rooms[104].id = 2876
      region.rooms[104].links = {}
        region.rooms[104].links.enter = {}
          region.rooms[104].links.enter.to = 2881
          region.rooms[104].links.enter.con = ""
        region.rooms[104].links.s = {}
          region.rooms[104].links.s.to = 2879
          region.rooms[104].links.s.con = ""
        region.rooms[104].links.out = {}
          region.rooms[104].links.out.to = 2871
          region.rooms[104].links.out.con = ""
        region.rooms[104].links.e = {}
          region.rooms[104].links.e.to = 2877
          region.rooms[104].links.e.con = ""
        region.rooms[104].links.w = {}
          region.rooms[104].links.w.to = 2878
          region.rooms[104].links.w.con = ""
        region.rooms[104].links.n = {}
          region.rooms[104].links.n.to = 2880
          region.rooms[104].links.n.con = ""
      region.rooms[104].exits = "south|east|north|enter|west|out"
      region.rooms[104].desc = "    此洞气氛却又大不相同，却似来到火焰山一般。只见一色红布帷幔，八支粗大的红烛分列四角。一旁站立的是虬髯大汉，各佩弯刀，刀柄上红樱低垂。正中大字是雄健的魏碑体：「烈焰豪情」。"
    region.rooms[105] = {}
      region.rooms[105].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;e"
      region.rooms[105].name = "石室"
      region.rooms[105].zone = "侠客岛"
      region.rooms[105].id = 2877
      region.rooms[105].links = {}
        region.rooms[105].links.w = {}
          region.rooms[105].links.w.to = 2876
          region.rooms[105].links.w.con = ""
      region.rooms[105].exits = "west"
      region.rooms[105].desc = "    这里酒气浓重，地上抛弃了不少酒袋或葫芦。东侧两人说话已经含糊不清，兀自向嘴里不停倒酒，踉跄地模仿石壁(wall)上的图案。距二人丈许外一个女子掩鼻而立，面带厌恶之色。"
    region.rooms[106] = {}
      region.rooms[106].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;w"
      region.rooms[106].name = "石室"
      region.rooms[106].zone = "侠客岛"
      region.rooms[106].id = 2878
      region.rooms[106].links = {}
        region.rooms[106].links.e = {}
          region.rooms[106].links.e.to = 2876
          region.rooms[106].links.e.con = ""
      region.rooms[106].exits = "east"
      region.rooms[106].desc = "    进门便听得急促的呼吸之声。只见一人面向石壁(wall)而坐，肩头耸动，喘息连连，似是练功到了紧要关头。另一名大汉双掌按在前人的后心，头顶也是白气氤氲。"
    region.rooms[107] = {}
      region.rooms[107].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;s"
      region.rooms[107].name = "石室"
      region.rooms[107].zone = "侠客岛"
      region.rooms[107].id = 2879
      region.rooms[107].links = {}
        region.rooms[107].links.n = {}
          region.rooms[107].links.n.to = 2876
          region.rooms[107].links.n.con = ""
      region.rooms[107].exits = "north"
      region.rooms[107].desc = "    这里光线黯淡，水珠时而从头顶的石壁上滴下，略略有些霉气把石室照得明亮。壁上刻得有图有字。右侧一位老乞丐正在对着独自石壁(wall)练拳，拳劲十足。"
    region.rooms[108] = {}
      region.rooms[108].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;n"
      region.rooms[108].name = "石室"
      region.rooms[108].zone = "侠客岛"
      region.rooms[108].id = 2880
      region.rooms[108].links = {}
        region.rooms[108].links.s = {}
          region.rooms[108].links.s.to = 2876
          region.rooms[108].links.s.con = ""
      region.rooms[108].exits = "south"
      region.rooms[108].desc = "    石室正中三人席地而坐，各自闭目吐纳，隐然是天地人三才的阵势。一个书生手持几根短竹，在地下来回摆弄，似乎正在占卜。偶尔抬头望望石壁(wall)，若有所悟。"
    region.rooms[109] = {}
      region.rooms[109].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter"
      region.rooms[109].name = "石洞"
      region.rooms[109].zone = "侠客岛"
      region.rooms[109].id = 2881
      region.rooms[109].links = {}
        region.rooms[109].links.enter = {}
          region.rooms[109].links.enter.to = 2886
          region.rooms[109].links.enter.con = ""
        region.rooms[109].links.s = {}
          region.rooms[109].links.s.to = 2884
          region.rooms[109].links.s.con = ""
        region.rooms[109].links.out = {}
          region.rooms[109].links.out.to = 2876
          region.rooms[109].links.out.con = ""
        region.rooms[109].links.e = {}
          region.rooms[109].links.e.to = 2882
          region.rooms[109].links.e.con = ""
        region.rooms[109].links.w = {}
          region.rooms[109].links.w.to = 2883
          region.rooms[109].links.w.con = ""
        region.rooms[109].links.n = {}
          region.rooms[109].links.n.to = 2885
          region.rooms[109].links.n.con = ""
      region.rooms[109].exits = "south|east|north|enter|west|out"
      region.rooms[109].desc = "    进洞便觉脚下有些不同，原来特意垫了半尺厚的黄土，不知有什麽妙用。正面也是刻着这四句的总纲：「落花残阳」，却是笔致圆润，似出女子之手。周围帘幕低垂，一色淡黄。"
    region.rooms[110] = {}
      region.rooms[110].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;e"
      region.rooms[110].name = "石室"
      region.rooms[110].zone = "侠客岛"
      region.rooms[110].id = 2882
      region.rooms[110].links = {}
        region.rooms[110].links.w = {}
          region.rooms[110].links.w.to = 2881
          region.rooms[110].links.w.con = ""
      region.rooms[110].exits = "west"
      region.rooms[110].desc = "    这里极为低矮，身材稍高之人便要低头。室内仅余西北角一支火把，其余的均已燃为灰烬，在昏暗的光线中，仅有一人盘膝而坐，对照石壁(wall)比划着。只见掌指交替，繁杂无比。"
    region.rooms[111] = {}
      region.rooms[111].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;w"
      region.rooms[111].name = "石室"
      region.rooms[111].zone = "侠客岛"
      region.rooms[111].id = 2883
      region.rooms[111].links = {}
        region.rooms[111].links.e = {}
          region.rooms[111].links.e.to = 2881
          region.rooms[111].links.e.con = ""
      region.rooms[111].exits = "east"
      region.rooms[111].desc = "    进得门来，便觉阵阵有形无质的气浪逼人，功力稍差之人似乎要站立不稳。几位老者正在场中互较内功，身上衣衫高高蓬起。几名旁观者均背靠石壁(wall)而立，神色紧张。"
    region.rooms[112] = {}
      region.rooms[112].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;s"
      region.rooms[112].name = "石室"
      region.rooms[112].zone = "侠客岛"
      region.rooms[112].id = 2884
      region.rooms[112].links = {}
        region.rooms[112].links.n = {}
          region.rooms[112].links.n.to = 2881
          region.rooms[112].links.n.con = ""
      region.rooms[112].exits = "north"
      region.rooms[112].desc = "    石室之中平平无奇，也是数人切磋武功，或指点石壁(wall)相互辩论。偶尔众人默然，便听到头顶传来潺潺的水声，想必此处乃是溪流之下。脚下石砖上遍布青苔，若不小心便要滑倒。"
    region.rooms[113] = {}
      region.rooms[113].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;n"
      region.rooms[113].name = "石室"
      region.rooms[113].zone = "侠客岛"
      region.rooms[113].id = 2885
      region.rooms[113].links = {}
        region.rooms[113].links.s = {}
          region.rooms[113].links.s.to = 2881
          region.rooms[113].links.s.con = ""
      region.rooms[113].exits = "south"
      region.rooms[113].desc = "    这里铿锵之声不绝，一个身材矮小的汉子手持黄金棍，与使蛾眉刺的少妇双战一个瘦子。那瘦子在一片黄光中身形晃动，丝毫不落下风。兵刃劲风激荡之下，火把也熄灭了两支。石壁(wall)上的图谱隐约可见。"
    region.rooms[114] = {}
      region.rooms[114].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;enter"
      region.rooms[114].name = "石洞"
      region.rooms[114].zone = "侠客岛"
      region.rooms[114].id = 2886
      region.rooms[114].links = {}
        region.rooms[114].links.s = {}
          region.rooms[114].links.s.to = 2889
          region.rooms[114].links.s.con = ""
        region.rooms[114].links.out = {}
          region.rooms[114].links.out.to = 2881
          region.rooms[114].links.out.con = ""
        region.rooms[114].links.e = {}
          region.rooms[114].links.e.to = 2887
          region.rooms[114].links.e.con = ""
        region.rooms[114].links.w = {}
          region.rooms[114].links.w.to = 2888
          region.rooms[114].links.w.con = ""
        region.rooms[114].links.n = {}
          region.rooms[114].links.n.to = 2890
          region.rooms[114].links.n.con = ""
      region.rooms[114].exits = "south|east|north|west|out"
      region.rooms[114].desc = "    眼前烛光黯淡，四周未见任何装饰，光秃粗糙的石壁上四字小篆，正是最后一句总纲：「天人归真」，下面又有一行小字(xiaozi)。几张石桌石凳随意地摆放着，似是杂乱无章，又似内藏玄机。"
    region.rooms[115] = {}
      region.rooms[115].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;enter;e"
      region.rooms[115].name = "石室"
      region.rooms[115].zone = "侠客岛"
      region.rooms[115].id = 2887
      region.rooms[115].links = {}
        region.rooms[115].links.w = {}
          region.rooms[115].links.w.to = 2886
          region.rooms[115].links.w.con = ""
      region.rooms[115].exits = "west"
      region.rooms[115].desc = "    石室中有三个蒲团，仅正中蒲团坐有一人，正与一个面色焦黄的女子对掌。那女子似是行有余力，尚有闲暇不时瞟一眼石壁(wall)，空着的左手也在虚拟作势。一个书生手持笔墨，在地下随写随抹，摇头晃脑地很是得意。"
    region.rooms[116] = {}
      region.rooms[116].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;enter;w"
      region.rooms[116].name = "石室"
      region.rooms[116].zone = "侠客岛"
      region.rooms[116].id = 2888
      region.rooms[116].links = {}
        region.rooms[116].links.e = {}
          region.rooms[116].links.e.to = 2886
          region.rooms[116].links.e.con = ""
      region.rooms[116].exits = "east"
      region.rooms[116].desc = "    这里火光昏暗，只见那龙岛主与木岛主盘膝坐在锦垫之上，面对石壁(wall)，凝神苦思。此石室已是山腹最深处，却宽阔高大，足可容下近百人。洞中火把亦是其他洞的二三倍之多。"
    region.rooms[117] = {}
      region.rooms[117].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;enter;s"
      region.rooms[117].name = "石室"
      region.rooms[117].zone = "侠客岛"
      region.rooms[117].id = 2889
      region.rooms[117].links = {}
        region.rooms[117].links.n = {}
          region.rooms[117].links.n.to = 2886
          region.rooms[117].links.n.con = ""
      region.rooms[117].exits = "north"
      region.rooms[117].desc = "    只听劈啪之声不断，两个长脸汉子各持齐眉棍，正自印证武功。一旁的两人却是默不作声，以指作棍，在空中虚点虚刺。一名少女斜倚石壁(wall)，甚是疲倦，右侧长衫男子端着一盘点心，神色关注。"
    region.rooms[118] = {}
      region.rooms[118].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;w;enter;enter;enter;enter;enter;enter;n"
      region.rooms[118].name = "石室"
      region.rooms[118].zone = "侠客岛"
      region.rooms[118].id = 2890
      region.rooms[118].links = {}
        region.rooms[118].links.s = {}
          region.rooms[118].links.s.to = 2886
          region.rooms[118].links.s.con = ""
      region.rooms[118].exits = "south"
      region.rooms[118].desc = "    进门便觉精神一振，原来上方有一尺许见方的通风孔，不似其他石室那般气闷。一抹阳光从孔中透入，投在对面的石壁(wall)上。隐隐也能听见外面的鸟雀叽嚓飞过，令人片刻间神游物外。"
    region.rooms[119] = {}
      region.rooms[119].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;s;move bed"
      region.rooms[119].name = "秘密通道"
      region.rooms[119].zone = "侠客岛"
      region.rooms[119].id = 2891
      region.rooms[119].links = {}
        region.rooms[119].links.e = {}
          region.rooms[119].links.e.to = 2892
          region.rooms[119].links.e.con = ""
        region.rooms[119].links.w = {}
          region.rooms[119].links.w.to = 2891
          region.rooms[119].links.w.con = ""
        region.rooms[119].links.s = {}
          region.rooms[119].links.s.to = 2891
          region.rooms[119].links.s.con = ""
        region.rooms[119].links.n = {}
          region.rooms[119].links.n.to = 2891
          region.rooms[119].links.n.con = ""
      region.rooms[119].exits = "south|east|north|west"
      region.rooms[119].desc = "    这是一条很长的秘密通道，也许好久没人来过了，密道中充满了一种潮湿的气味，隐约可以感觉到四周是冰冷的石壁，你什么也看不见，只可以靠摸索着前进。"
    region.rooms[120] = {}
      region.rooms[120].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;s;move bed;e"
      region.rooms[120].name = "秘密通道"
      region.rooms[120].zone = "侠客岛"
      region.rooms[120].id = 2892
      region.rooms[120].links = {}
        region.rooms[120].links.e = {}
          region.rooms[120].links.e.to = 2892
          region.rooms[120].links.e.con = ""
        region.rooms[120].links.s = {}
          region.rooms[120].links.s.to = 2893
          region.rooms[120].links.s.con = ""
        region.rooms[120].links.w = {}
          region.rooms[120].links.w.to = 2891
          region.rooms[120].links.w.con = ""
        region.rooms[120].links.n = {}
          region.rooms[120].links.n.to = 2892
          region.rooms[120].links.n.con = ""
      region.rooms[120].exits = "south|north|east|west"
      region.rooms[120].desc = "    这是一条很长的秘密通道，也许好久没人来过了，密道中充满了一种潮湿的气味，隐约可以感觉到四周是冰冷的石壁，你什么也看不见，只可以靠摸索着前进。"
    region.rooms[121] = {}
      region.rooms[121].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;s;move bed;e;s"
      region.rooms[121].name = "秘密通道"
      region.rooms[121].zone = "侠客岛"
      region.rooms[121].id = 2893
      region.rooms[121].links = {}
        region.rooms[121].links.e = {}
          region.rooms[121].links.e.to = 2893
          region.rooms[121].links.e.con = ""
        region.rooms[121].links.w = {}
          region.rooms[121].links.w.to = 2894
          region.rooms[121].links.w.con = ""
        region.rooms[121].links.s = {}
          region.rooms[121].links.s.to = 2893
          region.rooms[121].links.s.con = ""
        region.rooms[121].links.n = {}
          region.rooms[121].links.n.to = 2892
          region.rooms[121].links.n.con = ""
      region.rooms[121].exits = "south|east|north|west"
      region.rooms[121].desc = "    这是一条很长的秘密通道，也许好久没人来过了，密道中充满了一种潮湿的气味，隐约可以感觉到四周是冰冷的石壁，你什么也看不见，只可以靠摸索着前进。"
    region.rooms[122] = {}
      region.rooms[122].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;s;move bed;e;s;w"
      region.rooms[122].name = "密道"
      region.rooms[122].zone = "侠客岛"
      region.rooms[122].id = 2894
      region.rooms[122].links = {}
        region.rooms[122].links.e = {}
          region.rooms[122].links.e.to = 2893
          region.rooms[122].links.e.con = ""
        region.rooms[122].links["break men;w"] = {}
          region.rooms[122].links["break men;w"].to = 2895
          region.rooms[122].links["break men;w"].con = ""
      region.rooms[122].exits = "east"
      region.rooms[122].desc = "    这是一条很长的秘密通道，四周是坚硬的石壁，你什么也看不见，只能摸索前进。突然你走到了路的尽头，这是个死路，你还是回去吧。"
    region.rooms[123] = {}
      region.rooms[123].path = "fly fs;n;w;s;s;s;w;|!a:give shan pai to shi zhe:hi|;s;s;e;se;w;nw;e;s;s;su;su;su;su;sd;jump pubu;s;s;e;enter;s;e;s;w;s;push pingfeng;s;s;enter;s;move bed;e;s;w;break men;w"
      region.rooms[123].name = "秘密通道"
      region.rooms[123].zone = "侠客岛"
      region.rooms[123].id = 2895
      region.rooms[123].links = {}
        region.rooms[123].links.e = {}
          region.rooms[123].links.e.to = 2894
          region.rooms[123].links.e.con = ""
        region.rooms[123].links.out = {}
          region.rooms[123].links.out.to = 2858
          region.rooms[123].links.out.con = ""
      region.rooms[123].exits = "east|out"
      region.rooms[123].desc = "    这是一个石室，隐约可以感觉到四周是冰冷而坚硬的石壁，地上和角落都是灰尘，大概好久没人来过了。"
  region.center = 423
return region