local region = {}
  region.cmd = "fly hy;n;w;w;w;w"
  region.name = "侠客岛1"
  region.id = "xkd1"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly hy;n;w;w;w;w"
      region.rooms[1].name = "树林"
      region.rooms[1].zone = "侠客岛1"
      region.rooms[1].id = 2896
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 441
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 2898
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 2897
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 2896
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "south|north|east|west"
      region.rooms[1].desc = "    这里是茂密的森林。四周都是数不清的长草，一股阴森恐怖的气氛。远处不时传来野兽的嚎叫，你实在不想在这里多留。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly hy;n;w;w;w;w;s"
      region.rooms[2].name = "树林"
      region.rooms[2].zone = "侠客岛1"
      region.rooms[2].id = 2897
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 2896
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 2897
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 2897
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 2902
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "south|north|east|west"
      region.rooms[2].desc = "    这里是茂密的森林。四周都是数不清的长草，一股阴森恐怖的气氛。远处不时传来野兽的嚎叫，你实在不想在这里多留。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly hy;n;w;w;w;w;w"
      region.rooms[3].name = "山路"
      region.rooms[3].zone = "侠客岛1"
      region.rooms[3].id = 2898
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 2896
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 2899
          region.rooms[3].links.s.con = ""
      region.rooms[3].exits = "south|east"
      region.rooms[3].desc = "    这是一条山路，两旁是茂盛的森林，有一个女孩在这眼望南边发呆，南边就是摩天崖了，一股阴森恐怖的气氛随之而来，你不禁告诉自己，还是快走吧。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly hy;n;w;w;w;w;w;s"
      region.rooms[4].name = "崖底"
      region.rooms[4].zone = "侠客岛1"
      region.rooms[4].id = 2899
      region.rooms[4].links = {}
        region.rooms[4].links["climb lian"] = {}
          region.rooms[4].links["climb lian"].to = 2900
          region.rooms[4].links["climb lian"].con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 2898
          region.rooms[4].links.n.con = ""
      region.rooms[4].exits = "north"
      region.rooms[4].desc = "    你的面前是一座比直的山峰，高若千丈，峰顶在云雾中隐约可见，山峰光秃秃的，更无置手足处，山峰垂下一条铁链(lian)，仔细一看，铁链并无锈迹，似乎有人用它爬上爬下."
    region.rooms[5] = {}
      region.rooms[5].path = "fly hy;n;w;w;w;w;w;s;climb lian"
      region.rooms[5].name = "大厅"
      region.rooms[5].zone = "侠客岛1"
      region.rooms[5].id = 2900
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 2901
          region.rooms[5].links.e.con = "k1:谢烟客"
        region.rooms[5].links.d = {}
          region.rooms[5].links.d.to = 2899
          region.rooms[5].links.d.con = ""
      region.rooms[5].exits = "east|down"
      region.rooms[5].desc = "    这就是摩天崖了。上面光秃秃的，连一棵小树也没有，峰顶到也十分开阔，但身周云雾缭绕，当真是置身云端之中，使人心惊肉跳。东面有一个小木屋，门边立着一块青白色石碑(bei)。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly hy;n;w;w;w;w;w;s;climb lian;[k1:谢烟客]e"
      region.rooms[6].name = "木屋"
      region.rooms[6].zone = "侠客岛1"
      region.rooms[6].id = 2901
      region.rooms[6].links = {}
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 2900
          region.rooms[6].links.w.con = ""
      region.rooms[6].exits = "west"
      region.rooms[6].desc = "    这里是一个很小的木屋，室中放着一些乱七八遭的家具，墙角边还有一张破烂的小床，有一个英俊的少年在屋内走来走去，似乎有什么心事，不时的发出几声长叹...... "
    region.rooms[7] = {}
      region.rooms[7].path = "fly hy;n;w;w;w;w;s;n"
      region.rooms[7].name = "树林"
      region.rooms[7].zone = "侠客岛1"
      region.rooms[7].id = 2902
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 2897
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 2903
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 2902
          region.rooms[7].links.w.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 2902
          region.rooms[7].links.n.con = ""
      region.rooms[7].exits = "south|north|east|west"
      region.rooms[7].desc = "    这里是茂密的森林。四周都是数不清的长草，一股阴森恐怖的气氛。远处不时传来野兽的嚎叫，你实在不想在这里多留。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly hy;n;w;w;w;w;s;n;s"
      region.rooms[8].name = "树林"
      region.rooms[8].zone = "侠客岛1"
      region.rooms[8].id = 2903
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 2902
          region.rooms[8].links.e.con = ""
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 2905
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 2903
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 2904
          region.rooms[8].links.n.con = ""
      region.rooms[8].exits = "south|north|east|west"
      region.rooms[8].desc = "    这里是茂密的森林。四周都是数不清的长草，一股阴森恐怖的气氛。远处不时传来野兽的嚎叫，你实在不想在这里多留。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly hy;n;w;w;w;w;s;n;s;n"
      region.rooms[9].name = "树林"
      region.rooms[9].zone = "侠客岛1"
      region.rooms[9].id = 2904
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 2903
          region.rooms[9].links.e.con = ""
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 2903
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 2903
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 2903
          region.rooms[9].links.n.con = ""
      region.rooms[9].exits = "south|north|east|west"
      region.rooms[9].desc = "    这里是森林中的一块小平地。长草没胫，野花浪漫，四周都是密密的森林。时不时传来阵阵野兽嘶叫，飞鸟啼鸣。西南有一高崖突兀而起，极是险峻。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly hy;n;w;w;w;w;s;n;s;w"
      region.rooms[10].name = "树林"
      region.rooms[10].zone = "侠客岛1"
      region.rooms[10].id = 2905
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 2903
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 2905
          region.rooms[10].links.w.con = ""
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 2905
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 2905
          region.rooms[10].links.n.con = ""
      region.rooms[10].exits = "south|north|east|west"
      region.rooms[10].desc = "    这里是茂密的森林。四周都是数不清的长草，一股阴森恐怖的气氛。远处不时传来野兽的嚎叫，你实在不想在这里多留。"
  region.center = 2896

return region
