local region = {}
  region.cmd = "fly xs"
  region.name = "雪山寺"
  region.id = "xs"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly xs"
      region.rooms[1].name = "雪山寺山门"
      region.rooms[1].zone = "雪山寺"
      region.rooms[1].id = 2110
      region.rooms[1].links = {}
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 2111
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "north|eastdown"
      region.rooms[1].desc = "    这里是大轮寺的山门，门前是络绎不绝的进香朝圣的信徒，有的甚至来自乌丝藏西南的波丝。山门(gate)前站了个手持法器的葛伦布在维持秩序，东方是一条青石板铺成的山路。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly xs;n"
      region.rooms[2].name = "广场"
      region.rooms[2].zone = "雪山寺"
      region.rooms[2].id = 2111
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 2112
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 2114
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 2110
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 2119
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "south|north|east|west"
      region.rooms[2].desc = "    这里是雪山寺内的广场。广场石埕铺就，黄土垫砌，平整而坚实。广场的北面就是依山而建的雪山寺大殿。往西是块练武场，南面是山门。寺内有一些手持僧棍的僧兵在巡逻。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly xs;n;e"
      region.rooms[3].name = "小院"
      region.rooms[3].zone = "雪山寺"
      region.rooms[3].id = 2112
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 2111
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 2113
          region.rooms[3].links.n.con = ""
      region.rooms[3].exits = "north|west"
      region.rooms[3].desc = "    这里是寺内的小院，收拾的相当干净利索。来来往往的香客和喇嘛，一边在暗示着雪山寺香火之盛，一边也好象在表示喇嘛的口福也真不坏。因为北边就是个厨房。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly xs;n;e;n"
      region.rooms[4].name = "厨房"
      region.rooms[4].zone = "雪山寺"
      region.rooms[4].id = 2113
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 2112
          region.rooms[4].links.s.con = ""
      region.rooms[4].exits = "south"
      region.rooms[4].desc = "    这里是雪山寺的厨房，新来的僧人可以在此打杂。房中醒目的位置有一块牌子（paizi）。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly xs;n;w"
      region.rooms[5].name = "练武场"
      region.rooms[5].zone = "雪山寺"
      region.rooms[5].id = 2114
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 2111
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 2115
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 2116
          region.rooms[5].links.n.con = ""
      region.rooms[5].exits = "south|north|east|west"
      region.rooms[5].desc = "    这里是雪山寺练武场，树着好多木桩和沙袋，僧人们日常均在此习武。东边是广场，西边有个小库房，南边一大片开阔地，就是雪山闻名海内的祭坛了。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly xs;n;w;w"
      region.rooms[6].name = "库房"
      region.rooms[6].zone = "雪山寺"
      region.rooms[6].id = 2115
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 2114
          region.rooms[6].links.e.con = ""
      region.rooms[6].exits = "east"
      region.rooms[6].desc = "    这里是练武场旁边的小库房，房里密不通风，只有一丝光线从屋檐小缝中投射进来。房中有些备用的武器，都是雪山弟子日常练功需要用到的兵器。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly xs;n;w;n"
      region.rooms[7].name = "后院"
      region.rooms[7].zone = "雪山寺"
      region.rooms[7].id = 2116
      region.rooms[7].links = {}
        region.rooms[7].links.ed = {}
          region.rooms[7].links.ed.to = 2118
          region.rooms[7].links.ed.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 2114
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 2117
          region.rooms[7].links.n.con = ""
      region.rooms[7].exits = "south|north|eastdown"
      region.rooms[7].desc = "    这里是雪山寺的后院，后院不大，栽了几株参天雪松，在白晃晃的雪山背景下，竟是飘然出世的心动。南边是练武场，北边是后门。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly xs;n;w;n;n"
      region.rooms[8].name = "后门"
      region.rooms[8].zone = "雪山寺"
      region.rooms[8].id = 2117
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 2116
          region.rooms[8].links.s.con = ""
      region.rooms[8].exits = "south"
      region.rooms[8].desc = "    这是雪山寺的后门。一片破落而萧索模样。喇嘛们香火也足，花用也大。这是后门，虽然未免寒酸，可也总可以掖着。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly xs;n;w;n;ed"
      region.rooms[9].name = "地牢"
      region.rooms[9].zone = "雪山寺"
      region.rooms[9].id = 2118
      region.rooms[9].links = {}
        region.rooms[9].links.wu = {}
          region.rooms[9].links.wu.to = 2116
          region.rooms[9].links.wu.con = ""
      region.rooms[9].exits = "westup"
      region.rooms[9].desc = "    这是一个阴暗、潮湿的牢房。你感到奇怪的是怎麽会不时听到一点怪声却怎么也找不到人呢? "
    region.rooms[10] = {}
      region.rooms[10].path = "fly xs;n;n"
      region.rooms[10].name = "大殿"
      region.rooms[10].zone = "雪山寺"
      region.rooms[10].id = 2119
      region.rooms[10].links = {}
        region.rooms[10].links.e = {}
          region.rooms[10].links.e.to = 2120
          region.rooms[10].links.e.con = ""
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 2111
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 2121
          region.rooms[10].links.w.con = ""
      region.rooms[10].exits = "south|east|west"
      region.rooms[10].desc = "    这里是雪山寺的大殿，中央供奉着佛祖塑像。僧人们在念着经文。远来的香客们在这里虔诚地膜拜。大殿两侧都是侧殿。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly xs;n;n;e"
      region.rooms[11].name = "侧殿"
      region.rooms[11].zone = "雪山寺"
      region.rooms[11].id = 2120
      region.rooms[11].links = {}
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 2119
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.u = {}
          region.rooms[11].links.u.to = 2126
          region.rooms[11].links.u.con = ""
      region.rooms[11].exits = "up|west"
      region.rooms[11].desc = "    这里是雪山寺的东侧殿。殿内有神态各异的十八罗汉塑像，金旒玉镶，很是庄严。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly xs;n;n;w"
      region.rooms[12].name = "侧殿"
      region.rooms[12].zone = "雪山寺"
      region.rooms[12].id = 2121
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 2119
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.u = {}
          region.rooms[12].links.u.to = 2122
          region.rooms[12].links.u.con = ""
      region.rooms[12].exits = "up|east"
      region.rooms[12].desc = "    这里是雪山寺的西侧殿。墙壁上描绘着佛祖传道的故事，佛祖手拈金花宝相庄严。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly xs;n;n;w;u"
      region.rooms[13].name = "走廊"
      region.rooms[13].zone = "雪山寺"
      region.rooms[13].id = 2122
      region.rooms[13].links = {}
        region.rooms[13].links.e = {}
          region.rooms[13].links.e.to = 2123
          region.rooms[13].links.e.con = ""
        region.rooms[13].links.d = {}
          region.rooms[13].links.d.to = 2121
          region.rooms[13].links.d.con = ""
        region.rooms[13].links.eu = {}
          region.rooms[13].links.eu.to = 2128
          region.rooms[13].links.eu.con = ""
      region.rooms[13].exits = "east|eastup|down"
      region.rooms[13].desc = "    这里是雪山寺内的走廊。这里有点幽暗，天花板上有一些不知道确切含义的雕刻，墙壁上则是很通俗的佛经故事壁画了。壁上点着几碗大海灯照明。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly xs;n;n;e;u;w"
      region.rooms[14].name = "大厅"
      region.rooms[14].zone = "雪山寺"
      region.rooms[14].id = 2123
      region.rooms[14].links = {}
        region.rooms[14].links.ne = {}
          region.rooms[14].links.ne.to = 2127
          region.rooms[14].links.ne.con = ""
        region.rooms[14].links.se = {}
          region.rooms[14].links.se.to = 2125
          region.rooms[14].links.se.con = ""
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 2126
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.nw = {}
          region.rooms[14].links.nw.to = 2124
          region.rooms[14].links.nw.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 2122
          region.rooms[14].links.w.con = ""
      region.rooms[14].exits = "northwest|east|southeast|northeast|west"
      region.rooms[14].desc = "    这里是寺内的大厅，几位有道的高僧在高声辩论。看来正在引经据典，争斗机锋。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly xs;n;n;e;u;w;nw"
      region.rooms[15].name = "雪山藏经室"
      region.rooms[15].zone = "雪山寺"
      region.rooms[15].id = 2124
      region.rooms[15].links = {}
        region.rooms[15].links.se = {}
          region.rooms[15].links.se.to = 2123
          region.rooms[15].links.se.con = ""
      region.rooms[15].exits = "southeast"
      region.rooms[15].desc = "    这里是雪山寺的藏经室，靠墙是一排书架，摆满了各种拳谱、书籍。大多是当年掌门人鸠摩智翻译的佛经和从少林寺取来的武学典籍。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly xs;n;n;e;u;w;se"
      region.rooms[16].name = "藏经阁"
      region.rooms[16].zone = "雪山寺"
      region.rooms[16].id = 2125
      region.rooms[16].links = {}
        region.rooms[16].links.nw = {}
          region.rooms[16].links.nw.to = 2123
          region.rooms[16].links.nw.con = ""
      region.rooms[16].exits = "northwest"
      region.rooms[16].desc = "    这里是雪山寺的藏经之处。书架上林林总总都是梵文典籍。你一个字也看不懂。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly xs;n;n;e;u"
      region.rooms[17].name = "走廊"
      region.rooms[17].zone = "雪山寺"
      region.rooms[17].id = 2126
      region.rooms[17].links = {}
        region.rooms[17].links.d = {}
          region.rooms[17].links.d.to = 2120
          region.rooms[17].links.d.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 2123
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.wu = {}
          region.rooms[17].links.wu.to = 2128
          region.rooms[17].links.wu.con = ""
      region.rooms[17].exits = "westup|west|down"
      region.rooms[17].desc = "    这里是雪山寺内的走廊。这里有点幽暗，天花板上有一些不知道确切含义的雕刻，墙壁上则是很通俗的佛经故事壁画了。壁上点着几碗大海灯照明。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly xs;n;n;e;u;w;ne"
      region.rooms[18].name = "禅室"
      region.rooms[18].zone = "雪山寺"
      region.rooms[18].id = 2127
      region.rooms[18].links = {}
        region.rooms[18].links.sw = {}
          region.rooms[18].links.sw.to = 2123
          region.rooms[18].links.sw.con = ""
      region.rooms[18].exits = "southwest"
      region.rooms[18].desc = "    这里是僧人门参禅打坐的地方。侧壁一列禅床让人看了就想到该想的事。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly xs;n;n;e;u;wu"
      region.rooms[19].name = "走廊"
      region.rooms[19].zone = "雪山寺"
      region.rooms[19].id = 2128
      region.rooms[19].links = {}
        region.rooms[19].links.ed = {}
          region.rooms[19].links.ed.to = 2126
          region.rooms[19].links.ed.con = ""
        region.rooms[19].links.wd = {}
          region.rooms[19].links.wd.to = 2122
          region.rooms[19].links.wd.con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 2129
          region.rooms[19].links.n.con = ""
      region.rooms[19].exits = "north|eastdown|westdown"
      region.rooms[19].desc = "    这里是雪山寺内的走廊。这里有点幽暗，天花板上有一些不知道确切含义的雕刻，墙壁上则是很通俗的佛经故事壁画了。壁上点着几碗大海灯照明。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly xs;n;n;e;u;wu;n"
      region.rooms[20].name = "内殿"
      region.rooms[20].zone = "雪山寺"
      region.rooms[20].id = 2129
      region.rooms[20].links = {}
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 2130
          region.rooms[20].links.e.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 2131
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 2128
          region.rooms[20].links.s.con = ""
        region.rooms[20].links.n = {}
          region.rooms[20].links.n.to = 2133
          region.rooms[20].links.n.con = ""
      region.rooms[20].exits = "south|north|east|west"
      region.rooms[20].desc = "    这里是雪山寺的内殿，也是掌门人见客的地方。雪山寺的掌门人、大轮明王、吐蕃国师鸠摩智是西域一代高僧，也是西域不世出的武林宗师。他驻锡本寺后，雪山寺方声名远播。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly xs;n;n;e;u;wu;n;e"
      region.rooms[21].name = "天台"
      region.rooms[21].zone = "雪山寺"
      region.rooms[21].id = 2130
      region.rooms[21].links = {}
        region.rooms[21].links.w = {}
          region.rooms[21].links.w.to = 2129
          region.rooms[21].links.w.con = ""
      region.rooms[21].exits = "west"
      region.rooms[21].desc = "    这里是雪山寺的高处。北边可见雄伟的大雪山，南边可以俯瞰美丽如镜的圣湖。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly xs;n;n;e;u;wu;n;w"
      region.rooms[22].name = "密道"
      region.rooms[22].zone = "雪山寺"
      region.rooms[22].id = 2131
      region.rooms[22].links = {}
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 2129
          region.rooms[22].links.e.con = ""
        region.rooms[22].links.n = {}
          region.rooms[22].links.n.to = 2132
          region.rooms[22].links.n.con = ""
      region.rooms[22].exits = "east|north"
      region.rooms[22].desc = "    这是一条狭窄的暗道。阴森可怕，到处积满了灰尘，结满了蛛网，也不知道通往何处。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly xs;n;n;e;u;wu;n;w;n"
      region.rooms[23].name = "密室"
      region.rooms[23].zone = "雪山寺"
      region.rooms[23].id = 2132
      region.rooms[23].links = {}
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 2131
          region.rooms[23].links.s.con = ""
        region.rooms[23].links.d = {}
          region.rooms[23].links.d.to = 40
          region.rooms[23].links.d.con = ""
      region.rooms[23].exits = "south|down"
      region.rooms[23].desc = "    这是一条小房间。什么东西都没有。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly xs;n;n;e;u;wu;n;n"
      region.rooms[24].name = "后殿"
      region.rooms[24].zone = "雪山寺"
      region.rooms[24].id = 2133
      region.rooms[24].links = {}
        region.rooms[24].links.s = {}
          region.rooms[24].links.s.to = 2129
          region.rooms[24].links.s.con = ""
      region.rooms[24].exits = "south"
      region.rooms[24].desc = "    这里是雪山寺的后殿，也是雪山弟子闭门练功的地方。殿内是一些练功的蒲团和木人，还有一些吊挂着的沙袋和直竖的木桩。"
  region.center = 2110
return region