local region = {}
  region.cmd = "fly yzw"
  region.name = "燕子坞"
  region.id = "yzw"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly yzw"
      region.rooms[1].name = "燕子坞"
      region.rooms[1].zone = "燕子坞"
      region.rooms[1].id = 2456
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 2464
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 2457
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 2465
          region.rooms[1].links.s.con = ""
      region.rooms[1].exits = "south|east|west"
      region.rooms[1].desc = "    燕子坞是幕容氏世居之地, 幕容氏乃夕日大燕国的后裔, 后来日见式微, 但其弟子却一心一意想光复大燕。其武功见长于以彼之道, 还施彼身, 端的十分厉害。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly yzw;w"
      region.rooms[2].name = "后院"
      region.rooms[2].zone = "燕子坞"
      region.rooms[2].id = 2457
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 2456
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 2458
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 2460
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "east|north|west"
      region.rooms[2].desc = "    这是水榭的后院，院中假山水石，无一不透出江南别具一格的风格。只见东西各有一道半月型的小门。东边就是举世闻名的燕子坞了。西面是一座通向湖中小岛的木桥，南面是岸边，可以坐船出太湖。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly yzw;w;w"
      region.rooms[3].name = "木桥"
      region.rooms[3].zone = "燕子坞"
      region.rooms[3].id = 2458
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 2457
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 2459
          region.rooms[3].links.w.con = ""
      region.rooms[3].exits = "east|west"
      region.rooms[3].desc = "    这是通往湖中小亭的木桥，从这望去湖面碧波荡漾，景色宜人。木桥的扶手上雕刻着一尊尊小木头狮子，让人爱不释手。木桥往西面走能够看到一座湖中小亭。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly yzw;w;w;w"
      region.rooms[4].name = "碧水亭"
      region.rooms[4].zone = "燕子坞"
      region.rooms[4].id = 2459
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 2458
          region.rooms[4].links.e.con = ""
      region.rooms[4].exits = "east"
      region.rooms[4].desc = "    这是湖中的一个小亭子，从这望去，可以看到整个湖面的景色,令人心旷神怡。亭子壁上刻画着江南水乡的宜人风景，令人产生无限遐想。亭上有一根梁（liang)。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly yzw;w;n"
      region.rooms[5].name = "听香水榭"
      region.rooms[5].zone = "燕子坞"
      region.rooms[5].id = 2460
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 2462
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 2457
          region.rooms[5].links.s.con = "aw:3:fealty 光复大燕"
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 2461
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 2463
          region.rooms[5].links.n.con = ""
      region.rooms[5].exits = "south|east|north|west"
      region.rooms[5].desc = "    这间房舍小巧玲珑, 颇为精雅。小舍匾额上写着\"听香水榭\"四个大字, 笔致颇为潇洒。东边是一条小路，不知是通往哪里的。再往前走，就到了\"燕子坞\"。南边是水榭的后院。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly yzw;w;n;w"
      region.rooms[6].name = "岸边"
      region.rooms[6].zone = "燕子坞"
      region.rooms[6].id = 2461
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 2460
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.out = {}
          region.rooms[6].links.out.to = 2498
          region.rooms[6].links.out.con = "a:yell boat"
      region.rooms[6].exits = "east"
      region.rooms[6].desc = "    从这里乘船可以到达曼佗罗山庄，一位上了年纪的老船夫正在岸边休息，你可以呼喊一声(yell)，船家就会摆船过来。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly yzw;w;n;e"
      region.rooms[7].name = "岸边"
      region.rooms[7].zone = "燕子坞"
      region.rooms[7].id = 2462
      region.rooms[7].links = {}
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 2460
          region.rooms[7].links.w.con = ""
      region.rooms[7].exits = "west"
      region.rooms[7].desc = "    这里是慕容家的家仆和丫鬟出入太湖的水上码头，只见人们来来往往，一个个风尘仆仆，码头边的老船夫见到你走过来，马上笑呵呵的迎了上去。湖面(humian)上有几只小舟正在游弋。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly yzw;w;n;n"
      region.rooms[8].name = "岸边"
      region.rooms[8].zone = "燕子坞"
      region.rooms[8].id = 2463
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 2460
          region.rooms[8].links.s.con = ""
      region.rooms[8].exits = "south"
      region.rooms[8].desc = "    远远看去，只见一个小洲上八九间房间，其中两间是楼房。阁宇中隐约露出一个牌坊「听香水榭」。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly yzw;e"
      region.rooms[9].name = "练武场"
      region.rooms[9].zone = "燕子坞"
      region.rooms[9].id = 2464
      region.rooms[9].links = {}
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 2456
          region.rooms[9].links.w.con = ""
      region.rooms[9].exits = "west"
      region.rooms[9].desc = "    这里是练武场，慕容家的弟子、家丁在这里练习武功，在练武场的一角，有一个专门用来练武的木桩(zhuang)，许多弟子都围在这里练功。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly yzw;s"
      region.rooms[10].name = "小径"
      region.rooms[10].zone = "燕子坞"
      region.rooms[10].id = 2465
      region.rooms[10].links = {}
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 2466
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 2456
          region.rooms[10].links.n.con = ""
      region.rooms[10].exits = "south|north"
      region.rooms[10].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，南面是燕子坞的大厅，专门接待来慕容的各路英雄豪杰。伸。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly yzw;s;s"
      region.rooms[11].name = "大厅"
      region.rooms[11].zone = "燕子坞"
      region.rooms[11].id = 2466
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 2471
          region.rooms[11].links.e.con = ""
        region.rooms[11].links.w = {}
          region.rooms[11].links.w.to = 2469
          region.rooms[11].links.w.con = ""
        region.rooms[11].links.s = {}
          region.rooms[11].links.s.to = 2467
          region.rooms[11].links.s.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 2465
          region.rooms[11].links.n.con = ""
      region.rooms[11].exits = "south|east|north|west"
      region.rooms[11].desc = "    大厅中陈设简朴, 无什摆设, 正堂上挂着许多人物字画, 都是容氏祖先的遗迹, 用来表示对先人的尊敬。大厅的东边是书房,西边是局室，南面是后厅。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly yzw;s;s;s"
      region.rooms[12].name = "后厅"
      region.rooms[12].zone = "燕子坞"
      region.rooms[12].id = 2467
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 2477
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 2480
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 2468
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 2466
          region.rooms[12].links.n.con = ""
      region.rooms[12].exits = "south|north|east|west"
      region.rooms[12].desc = "    这里是慕容家里商议事情的地方，不是慕容弟子最好不要到这里来。在后堂正中摆放着一个香案，上面摆放着一个灵位牌子(paizi)，在正中墙上挂着一幅百鸟朝奉图，边墙上挂着一口宝剑。东西两面各是一间厢房，南面是内堂。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly yzw;s;s;s;s"
      region.rooms[13].name = "内堂"
      region.rooms[13].zone = "燕子坞"
      region.rooms[13].id = 2468
      region.rooms[13].links = {}
        region.rooms[13].links.e = {}
          region.rooms[13].links.e.to = 2485
          region.rooms[13].links.e.con = ""
        region.rooms[13].links.w = {}
          region.rooms[13].links.w.to = 2484
          region.rooms[13].links.w.con = ""
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 2467
          region.rooms[13].links.n.con = ""
      region.rooms[13].exits = "east|north|west"
      region.rooms[13].desc = "    这里是燕子坞的内堂，里面是平时慕容家眷呆的地方，丫鬟和婢女们在这里伺候着慕容一家。墙面上挂着一幅五寿图，房梁是用上好的楠木作的。屋子中间放着一张八仙桌，桌子上摆着水蜜桃和荔枝。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly yzw;s;s;w"
      region.rooms[14].name = "局室"
      region.rooms[14].zone = "燕子坞"
      region.rooms[14].id = 2469
      region.rooms[14].links = {}
        region.rooms[14].links.e = {}
          region.rooms[14].links.e.to = 2466
          region.rooms[14].links.e.con = ""
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 2470
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 2480
          region.rooms[14].links.s.con = ""
      region.rooms[14].exits = "south|east|west"
      region.rooms[14].desc = "    这是大家平时休闲起居的地方, 里面放着一具古筝, 一张棋桌, 上面的棋错综复杂, 令人百思不得其解。局室的东面是大厅，西面是一条长廊，南面是一间厢房。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly yzw;s;s;w;w"
      region.rooms[15].name = "长廊"
      region.rooms[15].zone = "燕子坞"
      region.rooms[15].id = 2470
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 2469
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 2481
          region.rooms[15].links.s.con = ""
      region.rooms[15].exits = "south|east"
      region.rooms[15].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。长廊东面是书房，南面是长廊的延伸。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly yzw;s;s;e"
      region.rooms[16].name = "书房"
      region.rooms[16].zone = "燕子坞"
      region.rooms[16].id = 2471
      region.rooms[16].links = {}
        region.rooms[16].links.s = {}
          region.rooms[16].links.s.to = 2477
          region.rooms[16].links.s.con = ""
        region.rooms[16].links["sit chair;zhuan"] = {}
          region.rooms[16].links["sit chair;zhuan"].to = 2474
          region.rooms[16].links["sit chair;zhuan"].con = ""
        region.rooms[16].links.e = {}
          region.rooms[16].links.e.to = 2472
          region.rooms[16].links.e.con = ""
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 2466
          region.rooms[16].links.w.con = ""
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 2476
          region.rooms[16].links.n.con = ""
      region.rooms[16].exits = "south|east|north|west"
      region.rooms[16].desc = "    这里是燕子坞的书房, 天下武功皆荟粹与此, 包罗万象, 屋子南边是一把坐椅,四周全是一排排高大的书架。好好学习, 必可成为一代高手。墙角摆着一个大柜子(cabinet)，显得很不自然。书房的东面是一条长廊，西面是大厅，南面是一间厢房。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly yzw;s;s;e;e"
      region.rooms[17].name = "长廊"
      region.rooms[17].zone = "燕子坞"
      region.rooms[17].id = 2472
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 2473
          region.rooms[17].links.e.con = "k1:"
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 2471
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 2478
          region.rooms[17].links.s.con = ""
      region.rooms[17].exits = "south|east|west"
      region.rooms[17].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。长廊西面是书房，南面是长廊的延伸。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly yzw;s;s;e;e;|!k1::e|"
      region.rooms[18].name = "厨房"
      region.rooms[18].zone = "燕子坞"
      region.rooms[18].id = 2473
      region.rooms[18].links = {}
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 2472
          region.rooms[18].links.w.con = ""
      region.rooms[18].exits = "west"
      region.rooms[18].desc = "    这是一间小厨房, 虽然不大, 但是锅碗瓢盆, 油盐酱醋, 到很奇全。灶台上堆满了新鲜瓜果蔬菜, 活鱼活虾, 不仅不脏不乱, 还十分干净整齐。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly yzw;s;s;e;sit chair;zhuan"
      region.rooms[19].name = "夹壁"
      region.rooms[19].zone = "燕子坞"
      region.rooms[19].id = 2474
      region.rooms[19].links = {}
        region.rooms[19].links["push shujia"] = {}
          region.rooms[19].links["push shujia"].to = 2471
          region.rooms[19].links["push shujia"].con = ""
        region.rooms[19].links.n = {}
          region.rooms[19].links.n.to = 2475
          region.rooms[19].links.n.con = ""
      region.rooms[19].exits = "north"
      region.rooms[19].desc = "    这是书架后面的一道夹壁，要用力推开书架的后面。才有可能出去。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly yzw;s;s;e;sit chair;zhuan;n"
      region.rooms[20].name = "还施水阁"
      region.rooms[20].zone = "燕子坞"
      region.rooms[20].id = 2475
      region.rooms[20].links = {}
        region.rooms[20].links.s = {}
          region.rooms[20].links.s.to = 2474
          region.rooms[20].links.s.con = ""
      region.rooms[20].exits = "south"
      region.rooms[20].desc = "    这就是举世闻名的姑苏慕容的还施水阁，这里据说有很多武林人事向往以久的武功。只见墙上有一个书架子(shujia)，上面摆满了各种武籍。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly yzw;s;s;e;n"
      region.rooms[21].name = "私塾"
      region.rooms[21].zone = "燕子坞"
      region.rooms[21].id = 2476
      region.rooms[21].links = {}
        region.rooms[21].links.s = {}
          region.rooms[21].links.s.to = 2471
          region.rooms[21].links.s.con = ""
      region.rooms[21].exits = "south"
      region.rooms[21].desc = "    这里是慕容家里的书堂，为了让家里的孩子能够得到很好的教育，慕容家特意聘请了一位私塾先生来讲课。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly yzw;s;s;e;s"
      region.rooms[22].name = "厢房"
      region.rooms[22].zone = "燕子坞"
      region.rooms[22].id = 2477
      region.rooms[22].links = {}
        region.rooms[22].links.e = {}
          region.rooms[22].links.e.to = 2478
          region.rooms[22].links.e.con = ""
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 2467
          region.rooms[22].links.w.con = ""
        region.rooms[22].links.n = {}
          region.rooms[22].links.n.to = 2471
          region.rooms[22].links.n.con = ""
      region.rooms[22].exits = "north|east|west"
      region.rooms[22].desc = "    这是一间厢房, 里面摆设简单, 只有一张床, 一张书桌和一把椅子。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly yzw;s;s;e;s;e"
      region.rooms[23].name = "长廊"
      region.rooms[23].zone = "燕子坞"
      region.rooms[23].id = 2478
      region.rooms[23].links = {}
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 2479
          region.rooms[23].links.e.con = ""
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 2486
          region.rooms[23].links.s.con = ""
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 2477
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.n = {}
          region.rooms[23].links.n.to = 2472
          region.rooms[23].links.n.con = ""
      region.rooms[23].exits = "south|east|north|west"
      region.rooms[23].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。长廊西面是厢房，南面和东面是长廊的延伸。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly yzw;s;s;e;s;e;e"
      region.rooms[24].name = "长廊"
      region.rooms[24].zone = "燕子坞"
      region.rooms[24].id = 2479
      region.rooms[24].links = {}
        region.rooms[24].links.w = {}
          region.rooms[24].links.w.to = 2478
          region.rooms[24].links.w.con = ""
        region.rooms[24].links.s = {}
          region.rooms[24].links.s.to = 2493
          region.rooms[24].links.s.con = ""
      region.rooms[24].exits = "south|west"
      region.rooms[24].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，南面是一座圆形小门。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly yzw;s;s;w;s"
      region.rooms[25].name = "厢房"
      region.rooms[25].zone = "燕子坞"
      region.rooms[25].id = 2480
      region.rooms[25].links = {}
        region.rooms[25].links.e = {}
          region.rooms[25].links.e.to = 2467
          region.rooms[25].links.e.con = ""
        region.rooms[25].links.w = {}
          region.rooms[25].links.w.to = 2481
          region.rooms[25].links.w.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 2469
          region.rooms[25].links.n.con = ""
      region.rooms[25].exits = "north|east|west"
      region.rooms[25].desc = "    这是一间厢房, 里面摆设简单, 只有一张床, 一张书桌和一把椅子。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly yzw;s;s;w;w;s"
      region.rooms[26].name = "长廊"
      region.rooms[26].zone = "燕子坞"
      region.rooms[26].id = 2481
      region.rooms[26].links = {}
        region.rooms[26].links.e = {}
          region.rooms[26].links.e.to = 2480
          region.rooms[26].links.e.con = ""
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 2483
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.w = {}
          region.rooms[26].links.w.to = 2482
          region.rooms[26].links.w.con = ""
        region.rooms[26].links.n = {}
          region.rooms[26].links.n.to = 2470
          region.rooms[26].links.n.con = ""
      region.rooms[26].exits = "south|north|east|west"
      region.rooms[26].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。长廊东面是厢房，南面和西面是长廊的延伸。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly yzw;s;s;w;w;s;w"
      region.rooms[27].name = "长廊"
      region.rooms[27].zone = "燕子坞"
      region.rooms[27].id = 2482
      region.rooms[27].links = {}
        region.rooms[27].links.e = {}
          region.rooms[27].links.e.to = 2481
          region.rooms[27].links.e.con = ""
        region.rooms[27].links.s = {}
          region.rooms[27].links.s.to = 2487
          region.rooms[27].links.s.con = ""
      region.rooms[27].exits = "south|east"
      region.rooms[27].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，南面是一座圆形小门。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly yzw;s;s;w;w;s;s"
      region.rooms[28].name = "长廊"
      region.rooms[28].zone = "燕子坞"
      region.rooms[28].id = 2483
      region.rooms[28].links = {}
        region.rooms[28].links.e = {}
          region.rooms[28].links.e.to = 2484
          region.rooms[28].links.e.con = ""
        region.rooms[28].links.n = {}
          region.rooms[28].links.n.to = 2481
          region.rooms[28].links.n.con = ""
      region.rooms[28].exits = "north|east"
      region.rooms[28].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。长廊东面是静音阁。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly yzw;s;s;s;s;w"
      region.rooms[29].name = "静音阁"
      region.rooms[29].zone = "燕子坞"
      region.rooms[29].id = 2484
      region.rooms[29].links = {}
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 2468
          region.rooms[29].links.e.con = ""
        region.rooms[29].links.w = {}
          region.rooms[29].links.w.to = 2483
          region.rooms[29].links.w.con = ""
        region.rooms[29].links.s = {}
          region.rooms[29].links.s.to = 2489
          region.rooms[29].links.s.con = ""
      region.rooms[29].exits = "south|east|west"
      region.rooms[29].desc = "    这里是修身养性的好场所，这里静悄悄的，没有主人的吩咐，谁也不能够随便出入这里，在墙上挂着一幅图。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly yzw;s;s;s;s;e"
      region.rooms[30].name = "赏月斋"
      region.rooms[30].zone = "燕子坞"
      region.rooms[30].id = 2485
      region.rooms[30].links = {}
        region.rooms[30].links.e = {}
          region.rooms[30].links.e.to = 2486
          region.rooms[30].links.e.con = ""
        region.rooms[30].links.w = {}
          region.rooms[30].links.w.to = 2468
          region.rooms[30].links.w.con = ""
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 2491
          region.rooms[30].links.s.con = ""
      region.rooms[30].exits = "south|east|west"
      region.rooms[30].desc = "    赏月斋是为慕容家每到中秋之夜而建造的。里面富丽堂皇，瓜果应有尽有，旁边有丫鬟伺候着，每到赏月之时，一家老小都在这里赏月，在赏月的同时，也念念不忘复兴大燕的使命。西面是内堂，东面和南面是一条长廊。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly yzw;s;s;e;s;e;s"
      region.rooms[31].name = "长廊"
      region.rooms[31].zone = "燕子坞"
      region.rooms[31].id = 2486
      region.rooms[31].links = {}
        region.rooms[31].links.w = {}
          region.rooms[31].links.w.to = 2485
          region.rooms[31].links.w.con = ""
        region.rooms[31].links.n = {}
          region.rooms[31].links.n.to = 2478
          region.rooms[31].links.n.con = ""
      region.rooms[31].exits = "north|west"
      region.rooms[31].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。长廊西面是赏月斋。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly yzw;s;s;w;w;s;w;s"
      region.rooms[32].name = "小门"
      region.rooms[32].zone = "燕子坞"
      region.rooms[32].id = 2487
      region.rooms[32].links = {}
        region.rooms[32].links.s = {}
          region.rooms[32].links.s.to = 2488
          region.rooms[32].links.s.con = ""
        region.rooms[32].links.n = {}
          region.rooms[32].links.n.to = 2482
          region.rooms[32].links.n.con = ""
      region.rooms[32].exits = "south|north"
      region.rooms[32].desc = "    这里是一道圆形小门，小门的南面是一条长廊，长廊里面人来人往，所有的人都在忙着自己的事情。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly yzw;s;s;s;s;w;s;w"
      region.rooms[33].name = "长廊"
      region.rooms[33].zone = "燕子坞"
      region.rooms[33].id = 2488
      region.rooms[33].links = {}
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 2489
          region.rooms[33].links.e.con = ""
        region.rooms[33].links.n = {}
          region.rooms[33].links.n.to = 2487
          region.rooms[33].links.n.con = ""
      region.rooms[33].exits = "north|east"
      region.rooms[33].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情。东面是长廊的延伸。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly yzw;s;s;s;s;w;s"
      region.rooms[34].name = "长廊"
      region.rooms[34].zone = "燕子坞"
      region.rooms[34].id = 2489
      region.rooms[34].links = {}
        region.rooms[34].links.e = {}
          region.rooms[34].links.e.to = 2490
          region.rooms[34].links.e.con = ""
        region.rooms[34].links.w = {}
          region.rooms[34].links.w.to = 2488
          region.rooms[34].links.w.con = ""
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 2484
          region.rooms[34].links.n.con = ""
      region.rooms[34].exits = "north|east|west"
      region.rooms[34].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情。西面是长廊的延伸，北面是静音阁。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly yzw;s;s;s;s;e;s;w"
      region.rooms[35].name = "长廊"
      region.rooms[35].zone = "燕子坞"
      region.rooms[35].id = 2490
      region.rooms[35].links = {}
        region.rooms[35].links.w = {}
          region.rooms[35].links.w.to = 2489
          region.rooms[35].links.w.con = ""
        region.rooms[35].links.e = {}
          region.rooms[35].links.e.to = 2491
          region.rooms[35].links.e.con = ""
      region.rooms[35].exits = "east|west"
      region.rooms[35].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情。西面是长廊的延伸。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly yzw;s;s;s;s;e;s"
      region.rooms[36].name = "长廊"
      region.rooms[36].zone = "燕子坞"
      region.rooms[36].id = 2491
      region.rooms[36].links = {}
        region.rooms[36].links.e = {}
          region.rooms[36].links.e.to = 2492
          region.rooms[36].links.e.con = ""
        region.rooms[36].links.w = {}
          region.rooms[36].links.w.to = 2490
          region.rooms[36].links.w.con = ""
        region.rooms[36].links.n = {}
          region.rooms[36].links.n.to = 2485
          region.rooms[36].links.n.con = ""
      region.rooms[36].exits = "north|east|west"
      region.rooms[36].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情。西面是长廊的延伸，北面是赏月斋。"
    region.rooms[37] = {}
      region.rooms[37].path = "fly yzw;s;s;s;s;e;s;e"
      region.rooms[37].name = "长廊"
      region.rooms[37].zone = "燕子坞"
      region.rooms[37].id = 2492
      region.rooms[37].links = {}
        region.rooms[37].links.e = {}
          region.rooms[37].links.e.to = 2494
          region.rooms[37].links.e.con = ""
        region.rooms[37].links.w = {}
          region.rooms[37].links.w.to = 2491
          region.rooms[37].links.w.con = ""
        region.rooms[37].links.n = {}
          region.rooms[37].links.n.to = 2493
          region.rooms[37].links.n.con = ""
      region.rooms[37].exits = "north|east|west"
      region.rooms[37].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情。西面是长廊的延伸，东面是一条小径。"
    region.rooms[38] = {}
      region.rooms[38].path = "fly yzw;s;s;e;s;e;e;s"
      region.rooms[38].name = "小门"
      region.rooms[38].zone = "燕子坞"
      region.rooms[38].id = 2493
      region.rooms[38].links = {}
        region.rooms[38].links.s = {}
          region.rooms[38].links.s.to = 2492
          region.rooms[38].links.s.con = ""
        region.rooms[38].links.n = {}
          region.rooms[38].links.n.to = 2479
          region.rooms[38].links.n.con = ""
      region.rooms[38].exits = "south|north"
      region.rooms[38].desc = "    这里是一道圆形小门，小门的南面是一条长廊，长廊里面人来人往，所有的人都在忙着自己的事情。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly yzw;s;s;s;s;e;s;e;e"
      region.rooms[39].name = "小径"
      region.rooms[39].zone = "燕子坞"
      region.rooms[39].id = 2494
      region.rooms[39].links = {}
        region.rooms[39].links.w = {}
          region.rooms[39].links.w.to = 2492
          region.rooms[39].links.w.con = ""
        region.rooms[39].links.e = {}
          region.rooms[39].links.e.to = 2495
          region.rooms[39].links.e.con = ""
      region.rooms[39].exits = "east|west"
      region.rooms[39].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，东面是小径的延伸。"
    region.rooms[40] = {}
      region.rooms[40].path = "fly yzw;s;s;s;s;e;s;e;e;e"
      region.rooms[40].name = "小径"
      region.rooms[40].zone = "燕子坞"
      region.rooms[40].id = 2495
      region.rooms[40].links = {}
        region.rooms[40].links.e = {}
          region.rooms[40].links.e.to = 2497
          region.rooms[40].links.e.con = ""
        region.rooms[40].links.w = {}
          region.rooms[40].links.w.to = 2494
          region.rooms[40].links.w.con = ""
        region.rooms[40].links.n = {}
          region.rooms[40].links.n.to = 2496
          region.rooms[40].links.n.con = ""
      region.rooms[40].exits = "north|east|west"
      region.rooms[40].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，东面是一座小坟。"
    region.rooms[41] = {}
      region.rooms[41].path = "fly yzw;s;s;s;s;e;s;e;e;e;n"
      region.rooms[41].name = "观星台"
      region.rooms[41].zone = "燕子坞"
      region.rooms[41].id = 2496
      region.rooms[41].links = {}
        region.rooms[41].links.s = {}
          region.rooms[41].links.s.to = 2495
          region.rooms[41].links.s.con = ""
      region.rooms[41].exits = "south"
      region.rooms[41].desc = "    这里是小径旁树丛中央的一个大平台。平台呈圆形，地上按二十八宿的方位排布着一些木桩，其中一根最北边的木桩(zhuang)显得格外的粗壮。平台四周树丛掩映，傍晚的阳光难以穿透树叶的缝隙，使树丛看起来有些阴森。远处不知谁家的炊烟正在袅袅升起，是晚餐时分了。"
    region.rooms[42] = {}
      region.rooms[42].path = "fly yzw;s;s;s;s;e;s;e;e;e;e"
      region.rooms[42].name = "坟场"
      region.rooms[42].zone = "燕子坞"
      region.rooms[42].id = 2497
      region.rooms[42].links = {}
        region.rooms[42].links.w = {}
          region.rooms[42].links.w.to = 2495
          region.rooms[42].links.w.con = ""
      region.rooms[42].exits = "west"
      region.rooms[42].desc = "    这里是慕容氏的坟场, 慕容氏死后都要被安葬这里,世世代代, 无一例外。每到清明时分, 慕容后裔都要在这里祭祖。场中一座新坟格外引人住目, 那是慕容复之父慕容博之墓。"
    region.rooms[43] = {}
      region.rooms[43].path = "fly yzw;w;n;w;|!a:yell boat:out|"
      region.rooms[43].name = "岸边"
      region.rooms[43].zone = "燕子坞"
      region.rooms[43].id = 2498
      region.rooms[43].links = {}
        region.rooms[43].links.out = {}
          region.rooms[43].links.out.to = 2551
          region.rooms[43].links.out.con = "a:qu xiaozhu"
		  region.rooms[43].links.out.block = "y"
        region.rooms[43].links.n = {}
          region.rooms[43].links.n.to = 2499
          region.rooms[43].links.n.con = ""
      region.rooms[43].exits = "north"
      region.rooms[43].desc = "    这是曼佗罗山庄的一个小码头，从这里上船可以到达慕容世家的领地，武林中的英雄豪杰们都十分仰慕闻名天下的燕子坞，因为那里是无人不知无人不晓的“以彼之道，还施彼身”的发源地，而慕容世家一代就是住在那里。岸边有一位老船夫，专门载着去燕子坞的武林人士，他一见你走过来，不敢怠慢，带着笑脸连忙迎上前去。在岸边有一块牌子(paizi)。"
    region.rooms[44] = {}
      region.rooms[44].path = "fly yzw;w;n;w;|!a:yell boat:out|;n"
      region.rooms[44].name = "小径"
      region.rooms[44].zone = "燕子坞"
      region.rooms[44].id = 2499
      region.rooms[44].links = {}
        region.rooms[44].links.s = {}
          region.rooms[44].links.s.to = 2546
          region.rooms[44].links.s.con = ""
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 2500
          region.rooms[44].links.n.con = ""
      region.rooms[44].exits = "south|north"
      region.rooms[44].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，南面是小径的延伸。"
    region.rooms[45] = {}
      region.rooms[45].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n"
      region.rooms[45].name = "庄门"
      region.rooms[45].zone = "燕子坞"
      region.rooms[45].id = 2500
      region.rooms[45].links = {}
        region.rooms[45].links.e = {}
          region.rooms[45].links.e.to = 2507
          region.rooms[45].links.e.con = ""
        region.rooms[45].links.w = {}
          region.rooms[45].links.w.to = 2506
          region.rooms[45].links.w.con = ""
        region.rooms[45].links.s = {}
          region.rooms[45].links.s.to = 2499
          region.rooms[45].links.s.con = ""
        region.rooms[45].links.n = {}
          region.rooms[45].links.n.to = 2501
          region.rooms[45].links.n.con = ""
      region.rooms[45].exits = "south|north|east|west"
      region.rooms[45].desc = "    你转过一丛茂密的花丛, 猛然间, 只见一座红檐绿瓦, 小巧玲珑的庄院矗利在灿澜的花丛中。庄门大匾上赫然写着「曼陀罗山庄」五个金光闪闪的大字。"
    region.rooms[46] = {}
      region.rooms[46].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;n"
      region.rooms[46].name = "花丛中"
      region.rooms[46].zone = "燕子坞"
      region.rooms[46].id = 2501
      region.rooms[46].links = {}
        region.rooms[46].links.e = {}
          region.rooms[46].links.e.to = 2502
          region.rooms[46].links.e.con = ""
        region.rooms[46].links.s = {}
          region.rooms[46].links.s.to = 2500
          region.rooms[46].links.s.con = ""
        region.rooms[46].links.w = {}
          region.rooms[46].links.w.to = 2503
          region.rooms[46].links.w.con = ""
      region.rooms[46].exits = "south|east|west"
      region.rooms[46].desc = "    你信步观赏, 只见花林中除山茶花外更无别样花卉, 连最常见的牵牛花,月月红, 蔷薇之类也是一朵都无。走出数十丈后, 只见山茶品种渐多, 偶而也有一两本还算不错, 却也栽种不得其法。南面就是庄门了。"
    region.rooms[47] = {}
      region.rooms[47].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;n;e"
      region.rooms[47].name = "花丛中"
      region.rooms[47].zone = "燕子坞"
      region.rooms[47].id = 2502
      region.rooms[47].links = {}
        region.rooms[47].links.w = {}
          region.rooms[47].links.w.to = 2501
          region.rooms[47].links.w.con = ""
      region.rooms[47].exits = "west"
      region.rooms[47].desc = "    你信步观赏, 只见花林中除山茶花外更无别样花卉, 连最常见的牵牛花,月月红, 蔷薇之类也是一朵都无。走出数十丈后, 只见山茶品种渐多, 偶而也有一两本还算不错, 却也栽种不得其法。"
    region.rooms[48] = {}
      region.rooms[48].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;w;n"
      region.rooms[48].name = "岸边"
      region.rooms[48].zone = "燕子坞"
      region.rooms[48].id = 2503
      region.rooms[48].links = {}
        region.rooms[48].links.e = {}
          region.rooms[48].links.e.to = 2501
          region.rooms[48].links.e.con = ""
        region.rooms[48].links.w = {}
          region.rooms[48].links.w.to = 2504
          region.rooms[48].links.w.con = ""
        region.rooms[48].links.s = {}
          region.rooms[48].links.s.to = 2506
          region.rooms[48].links.s.con = ""
      region.rooms[48].exits = "south|east|west"
      region.rooms[48].desc = "    从小舟下来，你踏上了小岛的岸边，只见三面全是花的世界。落第秀才，十八学士，十三太保，八仙过海，风尘三侠等数种名贵的茶花萦绕在你的周围，你已经身陷花丛中，如果不仔细的辨别方向，很难能够走出去。"
    region.rooms[49] = {}
      region.rooms[49].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;w;w;n"
      region.rooms[49].name = "花丛中"
      region.rooms[49].zone = "燕子坞"
      region.rooms[49].id = 2504
      region.rooms[49].links = {}
        region.rooms[49].links.e = {}
          region.rooms[49].links.e.to = 2503
          region.rooms[49].links.e.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 2505
          region.rooms[49].links.s.con = ""
      region.rooms[49].exits = "south|east"
      region.rooms[49].desc = "    你信步观赏, 只见花林中除山茶花外更无别样花卉, 连最常见的牵牛花,月月红, 蔷薇之类也是一朵都无。走出数十丈后, 只见山茶品种渐多, 偶而也有一两本还算不错, 却也栽种不得其法。"
    region.rooms[50] = {}
      region.rooms[50].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;w;w"
      region.rooms[50].name = "花丛中"
      region.rooms[50].zone = "燕子坞"
      region.rooms[50].id = 2505
      region.rooms[50].links = {}
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 2506
          region.rooms[50].links.e.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 2504
          region.rooms[50].links.n.con = ""
      region.rooms[50].exits = "east|north"
      region.rooms[50].desc = "    你信步观赏, 只见花林中除山茶花外更无别样花卉, 连最常见的牵牛花,月月红, 蔷薇之类也是一朵都无。走出数十丈后, 只见山茶品种渐多, 偶而也有一两本还算不错, 却也栽种不得其法。"
    region.rooms[51] = {}
      region.rooms[51].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;w"
      region.rooms[51].name = "花丛中"
      region.rooms[51].zone = "燕子坞"
      region.rooms[51].id = 2506
      region.rooms[51].links = {}
        region.rooms[51].links.e = {}
          region.rooms[51].links.e.to = 2500
          region.rooms[51].links.e.con = ""
        region.rooms[51].links.w = {}
          region.rooms[51].links.w.to = 2505
          region.rooms[51].links.w.con = ""
        region.rooms[51].links.n = {}
          region.rooms[51].links.n.to = 2503
          region.rooms[51].links.n.con = ""
      region.rooms[51].exits = "east|north|west"
      region.rooms[51].desc = "    你信步观赏, 只见花林中除山茶花外更无别样花卉, 连最常见的牵牛花,月月红, 蔷薇之类也是一朵都无。走出数十丈后, 只见山茶品种渐多, 偶而也有一两本还算不错, 却也栽种不得其法。东面就是庄门了。"
    region.rooms[52] = {}
      region.rooms[52].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e"
      region.rooms[52].name = "前院"
      region.rooms[52].zone = "燕子坞"
      region.rooms[52].id = 2507
      region.rooms[52].links = {}
        region.rooms[52].links.e = {}
          region.rooms[52].links.e.to = 2508
          region.rooms[52].links.e.con = ""
        region.rooms[52].links.w = {}
          region.rooms[52].links.w.to = 2500
          region.rooms[52].links.w.con = ""
        region.rooms[52].links.s = {}
          region.rooms[52].links.s.to = 2525
          region.rooms[52].links.s.con = ""
      region.rooms[52].exits = "south|east|west"
      region.rooms[52].desc = "    这里是曼陀罗山庄的前院, 只见一个个丫环, 卑女人来人往穿梭不息, 而且个个不法轻灵, 显然武功不弱！院子的东面是一个小石桥，南面是一条长廊。往西走就到了庄门。"
    region.rooms[53] = {}
      region.rooms[53].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e"
      region.rooms[53].name = "小石桥"
      region.rooms[53].zone = "燕子坞"
      region.rooms[53].id = 2508
      region.rooms[53].links = {}
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 2507
          region.rooms[53].links.w.con = ""
        region.rooms[53].links.e = {}
          region.rooms[53].links.e.to = 2509
          region.rooms[53].links.e.con = ""
      region.rooms[53].exits = "east|west"
      region.rooms[53].desc = "    这是一座小小的白石拱桥。桥下碧绿的湖水正荡着微波。石桥的东面是一条鹅卵石铺成的小径，西面是曼佗罗山庄的前院。"
    region.rooms[54] = {}
      region.rooms[54].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e"
      region.rooms[54].name = "小径"
      region.rooms[54].zone = "燕子坞"
      region.rooms[54].id = 2509
      region.rooms[54].links = {}
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 2510
          region.rooms[54].links.e.con = ""
        region.rooms[54].links.s = {}
          region.rooms[54].links.s.to = 2527
          region.rooms[54].links.s.con = ""
        region.rooms[54].links.w = {}
          region.rooms[54].links.w.to = 2508
          region.rooms[54].links.w.con = ""
        region.rooms[54].links.n = {}
          region.rooms[54].links.n.to = 2516
          region.rooms[54].links.n.con = ""
      region.rooms[54].exits = "south|north|east|west"
      region.rooms[54].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，往北面看去是一片柳树林，南面是一条长廊。东面是小径的延伸。"
    region.rooms[55] = {}
      region.rooms[55].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e"
      region.rooms[55].name = "小径"
      region.rooms[55].zone = "燕子坞"
      region.rooms[55].id = 2510
      region.rooms[55].links = {}
        region.rooms[55].links.e = {}
          region.rooms[55].links.e.to = 2511
          region.rooms[55].links.e.con = ""
        region.rooms[55].links.s = {}
          region.rooms[55].links.s.to = 2517
          region.rooms[55].links.s.con = ""
        region.rooms[55].links.w = {}
          region.rooms[55].links.w.to = 2509
          region.rooms[55].links.w.con = ""
        region.rooms[55].links.n = {}
          region.rooms[55].links.n.to = 2514
          region.rooms[55].links.n.con = ""
      region.rooms[55].exits = "south|north|east|west"
      region.rooms[55].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，往北面看去是一片柳树林，南面和东面是小径的延伸。"
    region.rooms[56] = {}
      region.rooms[56].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e"
      region.rooms[56].name = "小径"
      region.rooms[56].zone = "燕子坞"
      region.rooms[56].id = 2511
      region.rooms[56].links = {}
        region.rooms[56].links.e = {}
          region.rooms[56].links.e.to = 2512
          region.rooms[56].links.e.con = ""
        region.rooms[56].links.s = {}
          region.rooms[56].links.s.to = 2522
          region.rooms[56].links.s.con = ""
        region.rooms[56].links.w = {}
          region.rooms[56].links.w.to = 2510
          region.rooms[56].links.w.con = ""
        region.rooms[56].links.n = {}
          region.rooms[56].links.n.to = 2513
          region.rooms[56].links.n.con = ""
      region.rooms[56].exits = "south|north|east|west"
      region.rooms[56].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，往北面看去是一片柳树林，东面是一座小水池，南面是一条长廊。"
    region.rooms[57] = {}
      region.rooms[57].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;e"
      region.rooms[57].name = "水池"
      region.rooms[57].zone = "燕子坞"
      region.rooms[57].id = 2512
      region.rooms[57].links = {}
        region.rooms[57].links.w = {}
          region.rooms[57].links.w.to = 2511
          region.rooms[57].links.w.con = ""
      region.rooms[57].exits = "west"
      region.rooms[57].desc = "    这是一大水池。一阵微风吹过，水中菏叶随风在水面上漂浮, 水面(mian)碧波涌起，妙不可言。水池中央有一座假山，其中的石洞是很多的，使人忍不住想探个究竟。"
    region.rooms[58] = {}
      region.rooms[58].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;n"
      region.rooms[58].name = "柳树林"
      region.rooms[58].zone = "燕子坞"
      region.rooms[58].id = 2513
      region.rooms[58].links = {}
        region.rooms[58].links.s = {}
          region.rooms[58].links.s.to = 2511
          region.rooms[58].links.s.con = ""
        region.rooms[58].links.w = {}
          region.rooms[58].links.w.to = 2514
          region.rooms[58].links.w.con = ""
      region.rooms[58].exits = "south|west"
      region.rooms[58].desc = "    这是一片碧绿的柳树林，一片碧绿的颜色，柳树看上去枝叶茂盛，树上几只小鸟唧唧喳喳的叫个不停，柳条随着微风轻轻摆动。"
    region.rooms[59] = {}
      region.rooms[59].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;n"
      region.rooms[59].name = "柳树林"
      region.rooms[59].zone = "燕子坞"
      region.rooms[59].id = 2514
      region.rooms[59].links = {}
        region.rooms[59].links.e = {}
          region.rooms[59].links.e.to = 2513
          region.rooms[59].links.e.con = ""
        region.rooms[59].links.s = {}
          region.rooms[59].links.s.to = 2510
          region.rooms[59].links.s.con = ""
        region.rooms[59].links.w = {}
          region.rooms[59].links.w.to = 2516
          region.rooms[59].links.w.con = ""
        region.rooms[59].links.n = {}
          region.rooms[59].links.n.to = 2515
          region.rooms[59].links.n.con = ""
      region.rooms[59].exits = "south|north|east|west"
      region.rooms[59].desc = "    这是一片碧绿的柳树林，一片碧绿的颜色，柳树看上去枝叶茂盛，树上几只小鸟唧唧喳喳的叫个不停，柳条随着微风轻轻摆动。"
    region.rooms[60] = {}
      region.rooms[60].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;n;n"
      region.rooms[60].name = "柳树林"
      region.rooms[60].zone = "燕子坞"
      region.rooms[60].id = 2515
      region.rooms[60].links = {}
        region.rooms[60].links.s = {}
          region.rooms[60].links.s.to = 2514
          region.rooms[60].links.s.con = ""
      region.rooms[60].exits = "south"
      region.rooms[60].desc = "    这是一片碧绿的柳树林，草地中间有两棵大树(tree)，看上去枝叶茂盛，树上几只小鸟唧唧喳喳的叫个不停。"
    region.rooms[61] = {}
      region.rooms[61].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;n"
      region.rooms[61].name = "柳树林"
      region.rooms[61].zone = "燕子坞"
      region.rooms[61].id = 2516
      region.rooms[61].links = {}
        region.rooms[61].links.e = {}
          region.rooms[61].links.e.to = 2514
          region.rooms[61].links.e.con = ""
        region.rooms[61].links.s = {}
          region.rooms[61].links.s.to = 2509
          region.rooms[61].links.s.con = ""
      region.rooms[61].exits = "south|east"
      region.rooms[61].desc = "    这是一片碧绿的柳树林，一片碧绿的颜色，柳树看上去枝叶茂盛，树上几只小鸟唧唧喳喳的叫个不停，柳条随着微风轻轻摆动。"
    region.rooms[62] = {}
      region.rooms[62].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;s"
      region.rooms[62].name = "小径"
      region.rooms[62].zone = "燕子坞"
      region.rooms[62].id = 2517
      region.rooms[62].links = {}
        region.rooms[62].links.s = {}
          region.rooms[62].links.s.to = 2518
          region.rooms[62].links.s.con = ""
        region.rooms[62].links.n = {}
          region.rooms[62].links.n.to = 2510
          region.rooms[62].links.n.con = ""
      region.rooms[62].exits = "south|north"
      region.rooms[62].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，往北面看去是一片柳树林，南面是后院，北面是一条小径。"
    region.rooms[63] = {}
      region.rooms[63].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;s;s"
      region.rooms[63].name = "后院"
      region.rooms[63].zone = "燕子坞"
      region.rooms[63].id = 2518
      region.rooms[63].links = {}
        region.rooms[63].links.e = {}
          region.rooms[63].links.e.to = 2519
          region.rooms[63].links.e.con = ""
        region.rooms[63].links.s = {}
          region.rooms[63].links.s.to = 2532
          region.rooms[63].links.s.con = ""
        region.rooms[63].links.w = {}
          region.rooms[63].links.w.to = 2528
          region.rooms[63].links.w.con = ""
        region.rooms[63].links.n = {}
          region.rooms[63].links.n.to = 2517
          region.rooms[63].links.n.con = ""
      region.rooms[63].exits = "south|north|east|west"
      region.rooms[63].desc = "    穿过一个半月形的拱门, 你来到一座小楼之前。小楼檐下一块匾额, 写着: \"云锦楼\" 三个墨绿毫字, 楼下前后左右种的都是茶花。但这些茶花都不过是三四流货色, 和这精致的楼阁亭榭相比, 未免不衬。左右面是一条长廊，南面是云锦楼。"
    region.rooms[64] = {}
      region.rooms[64].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s"
      region.rooms[64].name = "长廊"
      region.rooms[64].zone = "燕子坞"
      region.rooms[64].id = 2519
      region.rooms[64].links = {}
        region.rooms[64].links.e = {}
          region.rooms[64].links.e.to = 2520
          region.rooms[64].links.e.con = ""
        region.rooms[64].links.s = {}
          region.rooms[64].links.s.to = 2533
          region.rooms[64].links.s.con = ""
        region.rooms[64].links.w = {}
          region.rooms[64].links.w.to = 2518
          region.rooms[64].links.w.con = ""
        region.rooms[64].links.n = {}
          region.rooms[64].links.n.to = 2522
          region.rooms[64].links.n.con = ""
      region.rooms[64].exits = "south|east|north|west"
      region.rooms[64].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，东面是长廊的延伸，南面是客厅，西面就是后院。"
    region.rooms[65] = {}
      region.rooms[65].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e"
      region.rooms[65].name = "长廊"
      region.rooms[65].zone = "燕子坞"
      region.rooms[65].id = 2520
      region.rooms[65].links = {}
        region.rooms[65].links.e = {}
          region.rooms[65].links.e.to = 2521
          region.rooms[65].links.e.con = "k1:"
        region.rooms[65].links.w = {}
          region.rooms[65].links.w.to = 2519
          region.rooms[65].links.w.con = ""
        region.rooms[65].links.s = {}
          region.rooms[65].links.s.to = 2534
          region.rooms[65].links.s.con = ""
      region.rooms[65].exits = "south|east|west"
      region.rooms[65].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，南面是长廊的延伸。"
    region.rooms[66] = {}
      region.rooms[66].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;|!k1::e|"
      region.rooms[66].name = "厨房"
      region.rooms[66].zone = "燕子坞"
      region.rooms[66].id = 2521
      region.rooms[66].links = {}
        region.rooms[66].links.w = {}
          region.rooms[66].links.w.to = 2520
          region.rooms[66].links.w.con = ""
      region.rooms[66].exits = "west"
      region.rooms[66].desc = "    这是一间小厨房, 虽然不大, 但是锅碗瓢盆, 油盐酱醋, 到很奇全。灶台上堆满了新鲜瓜果蔬菜, 活鱼活虾, 不仅不脏不乱, 还十分干净整齐。"
    region.rooms[67] = {}
      region.rooms[67].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s"
      region.rooms[67].name = "长廊"
      region.rooms[67].zone = "燕子坞"
      region.rooms[67].id = 2522
      region.rooms[67].links = {}
        region.rooms[67].links.e = {}
          region.rooms[67].links.e.to = 2523
          region.rooms[67].links.e.con = ""
        region.rooms[67].links.s = {}
          region.rooms[67].links.s.to = 2519
          region.rooms[67].links.s.con = ""
        region.rooms[67].links.n = {}
          region.rooms[67].links.n.to = 2511
          region.rooms[67].links.n.con = ""
      region.rooms[67].exits = "south|east|north"
      region.rooms[67].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。北面是一条小径，南面和东面是长廊的延伸。"
    region.rooms[68] = {}
      region.rooms[68].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;e"
      region.rooms[68].name = "长廊"
      region.rooms[68].zone = "燕子坞"
      region.rooms[68].id = 2523
      region.rooms[68].links = {}
        region.rooms[68].links.w = {}
          region.rooms[68].links.w.to = 2522
          region.rooms[68].links.w.con = ""
        region.rooms[68].links.eu = {}
          region.rooms[68].links.eu.to = 2524
          region.rooms[68].links.eu.con = ""
      region.rooms[68].exits = "eastup|west"
      region.rooms[68].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。东面是一座小亭子。"
    region.rooms[69] = {}
      region.rooms[69].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;e;eu"
      region.rooms[69].name = "亭子"
      region.rooms[69].zone = "燕子坞"
      region.rooms[69].id = 2524
      region.rooms[69].links = {}
        region.rooms[69].links.wd = {}
          region.rooms[69].links.wd.to = 2523
          region.rooms[69].links.wd.con = ""
      region.rooms[69].exits = "westdown"
      region.rooms[69].desc = "    这是个很小的亭子，但是能够看到几乎全部的景色，远处有一片樱桃园。湖中几条小舟在碧绿的湖面上往来穿梭，湖中有一座木桥通向湖中的亭子。在水池的假山上有一个黑乎乎的洞穴。 "
    region.rooms[70] = {}
      region.rooms[70].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;s"
      region.rooms[70].name = "长廊"
      region.rooms[70].zone = "燕子坞"
      region.rooms[70].id = 2525
      region.rooms[70].links = {}
        region.rooms[70].links.e = {}
          region.rooms[70].links.e.to = 2526
          region.rooms[70].links.e.con = ""
        region.rooms[70].links.n = {}
          region.rooms[70].links.n.to = 2507
          region.rooms[70].links.n.con = ""
      region.rooms[70].exits = "north|east"
      region.rooms[70].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。东面是长廊的延伸。"
    region.rooms[71] = {}
      region.rooms[71].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;s;e"
      region.rooms[71].name = "长廊"
      region.rooms[71].zone = "燕子坞"
      region.rooms[71].id = 2526
      region.rooms[71].links = {}
        region.rooms[71].links.w = {}
          region.rooms[71].links.w.to = 2525
          region.rooms[71].links.w.con = ""
        region.rooms[71].links.e = {}
          region.rooms[71].links.e.to = 2527
          region.rooms[71].links.e.con = ""
      region.rooms[71].exits = "east|west"
      region.rooms[71].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。东面是长廊的延伸。搁着长廊你可以看到北面的小石桥。"
    region.rooms[72] = {}
      region.rooms[72].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;s"
      region.rooms[72].name = "长廊"
      region.rooms[72].zone = "燕子坞"
      region.rooms[72].id = 2527
      region.rooms[72].links = {}
        region.rooms[72].links.w = {}
          region.rooms[72].links.w.to = 2526
          region.rooms[72].links.w.con = ""
        region.rooms[72].links.s = {}
          region.rooms[72].links.s.to = 2528
          region.rooms[72].links.s.con = ""
        region.rooms[72].links.n = {}
          region.rooms[72].links.n.to = 2509
          region.rooms[72].links.n.con = ""
      region.rooms[72].exits = "south|north|west"
      region.rooms[72].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。北面是一条小径，南面是长廊的延伸。"
    region.rooms[73] = {}
      region.rooms[73].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;s;s"
      region.rooms[73].name = "长廊"
      region.rooms[73].zone = "燕子坞"
      region.rooms[73].id = 2528
      region.rooms[73].links = {}
        region.rooms[73].links.e = {}
          region.rooms[73].links.e.to = 2518
          region.rooms[73].links.e.con = ""
        region.rooms[73].links.w = {}
          region.rooms[73].links.w.to = 2530
          region.rooms[73].links.w.con = ""
        region.rooms[73].links.s = {}
          region.rooms[73].links.s.to = 2529
          region.rooms[73].links.s.con = ""
        region.rooms[73].links.n = {}
          region.rooms[73].links.n.to = 2527
          region.rooms[73].links.n.con = ""
      region.rooms[73].exits = "south|east|north|west"
      region.rooms[73].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，不敢有一点怠慢。北西两面面是长廊的延伸，东面是后院，南面是一间厢房。 "
    region.rooms[74] = {}
      region.rooms[74].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;s;s;s"
      region.rooms[74].name = "厢房"
      region.rooms[74].zone = "燕子坞"
      region.rooms[74].id = 2529
      region.rooms[74].links = {}
        region.rooms[74].links.e = {}
          region.rooms[74].links.e.to = 2532
          region.rooms[74].links.e.con = ""
        region.rooms[74].links.w = {}
          region.rooms[74].links.w.to = 2531
          region.rooms[74].links.w.con = ""
        region.rooms[74].links.n = {}
          region.rooms[74].links.n.to = 2528
          region.rooms[74].links.n.con = ""
      region.rooms[74].exits = "north|east|west"
      region.rooms[74].desc = "    这是一间厢房, 里面摆设简单, 只有一张床, 一张书桌和一把椅子。"
    region.rooms[75] = {}
      region.rooms[75].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;s;s;w"
      region.rooms[75].name = "长廊"
      region.rooms[75].zone = "燕子坞"
      region.rooms[75].id = 2530
      region.rooms[75].links = {}
        region.rooms[75].links.e = {}
          region.rooms[75].links.e.to = 2528
          region.rooms[75].links.e.con = ""
        region.rooms[75].links.s = {}
          region.rooms[75].links.s.to = 2531
          region.rooms[75].links.s.con = ""
      region.rooms[75].exits = "south|east"
      region.rooms[75].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，南面是长廊的延伸。"
    region.rooms[76] = {}
      region.rooms[76].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;s;s;w;s"
      region.rooms[76].name = "长廊"
      region.rooms[76].zone = "燕子坞"
      region.rooms[76].id = 2531
      region.rooms[76].links = {}
        region.rooms[76].links.e = {}
          region.rooms[76].links.e.to = 2529
          region.rooms[76].links.e.con = ""
        region.rooms[76].links.s = {}
          region.rooms[76].links.s.to = 2540
          region.rooms[76].links.s.con = ""
        region.rooms[76].links.n = {}
          region.rooms[76].links.n.to = 2530
          region.rooms[76].links.n.con = ""
      region.rooms[76].exits = "south|north|east"
      region.rooms[76].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，东面是一间厢房，南面是长廊的延伸。"
    region.rooms[77] = {}
      region.rooms[77].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;s;s;s"
      region.rooms[77].name = "云锦楼"
      region.rooms[77].zone = "燕子坞"
      region.rooms[77].id = 2532
      region.rooms[77].links = {}
        region.rooms[77].links.e = {}
          region.rooms[77].links.e.to = 2533
          region.rooms[77].links.e.con = ""
        region.rooms[77].links.s = {}
          region.rooms[77].links.s.to = 2538
          region.rooms[77].links.s.con = ""
        region.rooms[77].links.w = {}
          region.rooms[77].links.w.to = 2529
          region.rooms[77].links.w.con = ""
        region.rooms[77].links.n = {}
          region.rooms[77].links.n.to = 2518
          region.rooms[77].links.n.con = ""
      region.rooms[77].exits = "up|south|north|east|west"
      region.rooms[77].desc = "    云锦楼陈设富丽, 一副中堂绘的是孔雀开屏,两边柱子上写了一幅对联(duilian)。东面是一间客厅，西面是厢房，往北面走是后院，南面是后花园。"
    region.rooms[78] = {}
      region.rooms[78].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;s"
      region.rooms[78].name = "客厅"
      region.rooms[78].zone = "燕子坞"
      region.rooms[78].id = 2533
      region.rooms[78].links = {}
        region.rooms[78].links.e = {}
          region.rooms[78].links.e.to = 2534
          region.rooms[78].links.e.con = ""
        region.rooms[78].links.w = {}
          region.rooms[78].links.w.to = 2532
          region.rooms[78].links.w.con = ""
        region.rooms[78].links.n = {}
          region.rooms[78].links.n.to = 2519
          region.rooms[78].links.n.con = ""
      region.rooms[78].exits = "north|east|west"
      region.rooms[78].desc = "    你走进这间小小的厅室, 看到里面放着一张紫檀木茶几和几张湘妃竹椅子，紫檀木的茶几上摆放着茶壶和几只白玉杯，专供客人饮用。你忍不住想坐在竹椅上，让疲惫的身心得到充分的休息。"
    region.rooms[79] = {}
      region.rooms[79].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;s"
      region.rooms[79].name = "长廊"
      region.rooms[79].zone = "燕子坞"
      region.rooms[79].id = 2534
      region.rooms[79].links = {}
        region.rooms[79].links.e = {}
          region.rooms[79].links.e.to = 2535
          region.rooms[79].links.e.con = "k1:丫鬟"
        region.rooms[79].links.s = {}
          region.rooms[79].links.s.to = 2536
          region.rooms[79].links.s.con = ""
        region.rooms[79].links.w = {}
          region.rooms[79].links.w.to = 2533
          region.rooms[79].links.w.con = ""
        region.rooms[79].links.n = {}
          region.rooms[79].links.n.to = 2520
          region.rooms[79].links.n.con = ""
      region.rooms[79].exits = "south|north|east|west"
      region.rooms[79].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，西面是一间客厅，南面是长廊的延伸。"
    region.rooms[80] = {}
      region.rooms[80].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;s;|!k1:丫鬟:e|"
      region.rooms[80].name = "闺房"
      region.rooms[80].zone = "燕子坞"
      region.rooms[80].id = 2535
      region.rooms[80].links = {}
        region.rooms[80].links.w = {}
          region.rooms[80].links.w.to = 2534
          region.rooms[80].links.w.con = ""
        region.rooms[80].links["jump window"] = {}
          region.rooms[80].links["jump window"].to = 2541
          region.rooms[80].links["jump window"].con = ""
      region.rooms[80].exits = "west"
      region.rooms[80].desc = "    这里是山庄庄主女儿的闺房，里面透着一股醉人的少女芳香，令你陶醉。在闺房的一角摆放着一张梳妆台，台上摆着一些女人用的胭脂粉和用来涂抹嘴唇的香粉，以及一瓶玉露。房屋的另一角摆放着一张闺床，一缕青纱低垂下来。墙上有一个窗户，一扇窗子(window)大敞着。"
    region.rooms[81] = {}
      region.rooms[81].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;s;s"
      region.rooms[81].name = "长廊"
      region.rooms[81].zone = "燕子坞"
      region.rooms[81].id = 2536
      region.rooms[81].links = {}
        region.rooms[81].links.w = {}
          region.rooms[81].links.w.to = 2537
          region.rooms[81].links.w.con = ""
        region.rooms[81].links.n = {}
          region.rooms[81].links.n.to = 2534
          region.rooms[81].links.n.con = ""
      region.rooms[81].exits = "north|west"
      region.rooms[81].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，西面是杂货室，北面是长廊的延伸。"
    region.rooms[82] = {}
      region.rooms[82].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;s;s;s;s;e"
      region.rooms[82].name = "杂货室"
      region.rooms[82].zone = "燕子坞"
      region.rooms[82].id = 2537
      region.rooms[82].links = {}
        region.rooms[82].links.e = {}
          region.rooms[82].links.e.to = 2536
          region.rooms[82].links.e.con = ""
        region.rooms[82].links.w = {}
          region.rooms[82].links.w.to = 2538
          region.rooms[82].links.w.con = ""
      region.rooms[82].exits = "east|west"
      region.rooms[82].desc = "    这里是曼佗罗山庄的杂货室，里面摆满了各种不用的旧物品，在杂货室的一角摆放着一个兵器架。"
    region.rooms[83] = {}
      region.rooms[83].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;s;s;s;s"
      region.rooms[83].name = "后花园"
      region.rooms[83].zone = "燕子坞"
      region.rooms[83].id = 2538
      region.rooms[83].links = {}
        region.rooms[83].links.e = {}
          region.rooms[83].links.e.to = 2537
          region.rooms[83].links.e.con = ""
        region.rooms[83].links.w = {}
          region.rooms[83].links.w.to = 2539
          region.rooms[83].links.w.con = ""
        region.rooms[83].links.n = {}
          region.rooms[83].links.n.to = 2532
          region.rooms[83].links.n.con = ""
      region.rooms[83].exits = "east|north|west"
      region.rooms[83].desc = "    后花园和庄中其它地方一样种满了山茶花, 参杂在假山巨石, 绿竹小溪中, 此所谓: `千呼万唤始出来, 犹报琵琶半遮面` 更增姿媚。 抬头望去, 只见藏书阁的窗户半开着,一根古藤蜒伸在墙上。一股清泉从假山上涌出，尝一口沁人心脾。"
    region.rooms[84] = {}
      region.rooms[84].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;s;s;s;s;w"
      region.rooms[84].name = "花肥房"
      region.rooms[84].zone = "燕子坞"
      region.rooms[84].id = 2539
      region.rooms[84].links = {}
        region.rooms[84].links.e = {}
          region.rooms[84].links.e.to = 2538
          region.rooms[84].links.e.con = ""
        region.rooms[84].links.w = {}
          region.rooms[84].links.w.to = 2540
          region.rooms[84].links.w.con = ""
      region.rooms[84].exits = "east|west"
      region.rooms[84].desc = "    石屋黑恫恫的, 只见一个人被绑在一根铁柱子上, 口里塞满了东西, 眼泪汪汪的, 却说不出话来。再看两旁时, 只见一个弓腰曲背的老婆子手里拿着一柄雪亮的长刀, 身旁一锅沸水, 煮得直冒热气。"
    region.rooms[85] = {}
      region.rooms[85].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;s;s;w;s;s"
      region.rooms[85].name = "长廊"
      region.rooms[85].zone = "燕子坞"
      region.rooms[85].id = 2540
      region.rooms[85].links = {}
        region.rooms[85].links.e = {}
          region.rooms[85].links.e.to = 2539
          region.rooms[85].links.e.con = ""
        region.rooms[85].links.n = {}
          region.rooms[85].links.n.to = 2531
          region.rooms[85].links.n.con = ""
      region.rooms[85].exits = "north|east"
      region.rooms[85].desc = "    这是一条长廊，上面画着江南秀美的工笔画。绿色的柱子朱红色的琉璃瓦，使得你不由得对江南艺术工匠的创造惊叹不已。在长廊里面，丫鬟、家丁们走来走去，都忙着自己的事情，东面是花肥房，北面是长廊的延伸。"
    region.rooms[86] = {}
      region.rooms[86].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;s;|!k1:丫鬟:e|;jump window"
      region.rooms[86].name = "樱桃园"
      region.rooms[86].zone = "燕子坞"
      region.rooms[86].id = 2541
      region.rooms[86].links = {}
        region.rooms[86].links.e = {}
          region.rooms[86].links.e.to = 2543
          region.rooms[86].links.e.con = ""
        region.rooms[86].links.s = {}
          region.rooms[86].links.s.to = 2542
          region.rooms[86].links.s.con = ""
        region.rooms[86].links.w = {}
          region.rooms[86].links.w.to = 2541
          region.rooms[86].links.w.con = ""
        region.rooms[86].links.n = {}
          region.rooms[86].links.n.to = 2541
          region.rooms[86].links.n.con = ""
      region.rooms[86].exits = "south|east|north|west"
      region.rooms[86].desc = "    这是一片樱桃园，树上开满了樱桃花。"
    region.rooms[87] = {}
      region.rooms[87].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;s;|!k1:丫鬟:e|;jump window;s"
      region.rooms[87].name = "娘缳玉洞"
      region.rooms[87].zone = "燕子坞"
      region.rooms[87].id = 2542
      region.rooms[87].links = {}
        region.rooms[87].links.n = {}
          region.rooms[87].links.n.to = 2544
          region.rooms[87].links.n.con = ""
      region.rooms[87].exits = "north"
      region.rooms[87].desc = "    这是曼佗罗山庄存放武功秘籍的地方，一排排书架上整齐的摆放着各种书籍。一位美丽的姑娘正在书架前研读武籍。"
    region.rooms[88] = {}
      region.rooms[88].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;s;|!k1:丫鬟:e|;jump window;e"
      region.rooms[88].name = "樱桃园"
      region.rooms[88].zone = "燕子坞"
      region.rooms[88].id = 2543
      region.rooms[88].links = {}
        region.rooms[88].links.e = {}
          region.rooms[88].links.e.to = 2544
          region.rooms[88].links.e.con = ""
        region.rooms[88].links.s = {}
          region.rooms[88].links.s.to = 2542
          region.rooms[88].links.s.con = ""
        region.rooms[88].links.w = {}
          region.rooms[88].links.w.to = 2543
          region.rooms[88].links.w.con = ""
        region.rooms[88].links.n = {}
          region.rooms[88].links.n.to = 2543
          region.rooms[88].links.n.con = ""
      region.rooms[88].exits = "south|east|north|west"
      region.rooms[88].desc = "    这是一片樱桃园，树上开满了樱桃花。"
    region.rooms[89] = {}
      region.rooms[89].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;s;|!k1:丫鬟:e|;jump window;e;e"
      region.rooms[89].name = "樱桃园"
      region.rooms[89].zone = "燕子坞"
      region.rooms[89].id = 2544
      region.rooms[89].links = {}
        region.rooms[89].links.w = {}
          region.rooms[89].links.w.to = 2543
          region.rooms[89].links.w.con = ""
        region.rooms[89].links.s = {}
          region.rooms[89].links.s.to = 2542
          region.rooms[89].links.s.con = ""
        region.rooms[89].links.n = {}
          region.rooms[89].links.n.to = 2545
          region.rooms[89].links.n.con = ""
      region.rooms[89].exits = "south|north|west"
      region.rooms[89].desc = "    这是一片樱桃园，树上开满了樱桃花。"
    region.rooms[90] = {}
      region.rooms[90].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;n;e;e;e;e;e;s;s;e;s;|!k1:丫鬟:e|;jump window;e;e;n"
      region.rooms[90].name = "秘道"
      region.rooms[90].zone = "燕子坞"
      region.rooms[90].id = 2545
      region.rooms[90].links = {}
        region.rooms[90].links.s = {}
          region.rooms[90].links.s.to = 2544
          region.rooms[90].links.s.con = ""
        region.rooms[90].links.n = {}
          region.rooms[90].links.n.to = 2538
          region.rooms[90].links.n.con = ""
      region.rooms[90].exits = "south|north"
      region.rooms[90].desc = "    这里土地潮湿，墙上有一束火把。"
    region.rooms[91] = {}
      region.rooms[91].path = "fly yzw;w;n;w;|!a:yell boat:out|;n;s"
      region.rooms[91].name = "小径"
      region.rooms[91].zone = "燕子坞"
      region.rooms[91].id = 2546
      region.rooms[91].links = {}
        region.rooms[91].links.s = {}
          region.rooms[91].links.s.to = 2498
          region.rooms[91].links.s.con = ""
        region.rooms[91].links.n = {}
          region.rooms[91].links.n.to = 2499
          region.rooms[91].links.n.con = ""
      region.rooms[91].exits = "south|north"
      region.rooms[91].desc = "    一条曲曲折折用鹅卵石铺成的小径, 路两旁绿柳成阴, 一处处山石花木点缀在其中。你走在石地上，啪嗒啪嗒的发出清脆的响声，北面是小径的延伸，南面就到了岸边。"
  region.center = 2456
return region