local region = {}
  region.cmd = "fly bj"
  region.name = "北京紫禁城"
  region.id = "zjc"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly bj"
      region.rooms[1].name = "天安门"
      region.rooms[1].zone = "北京紫禁城|北京"
      region.rooms[1].id = 962
      region.rooms[1].links = {}
        region.rooms[1].links.e = {}
          region.rooms[1].links.e.to = 982
          region.rooms[1].links.e.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 1095
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 983
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 963
          region.rooms[1].links.n.con = ""
      region.rooms[1].exits = "south|east|north|west"
      region.rooms[1].desc = "    这里就是天安门广场，灰色的城墙给人以庄严肃穆之感，再往北就是皇宫了。皇宫正门前有座小桥，一条护城河绕城而过。越过小桥向北望去，紫禁城的轮廓益发显得雄伟高大。一条笔直的大道横贯东西，东边是东长安街，西边是西长安街。南边是一条繁华的大道，从那往下有一座天桥，据说游人很多。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly bj;n"
      region.rooms[2].name = "小桥"
      region.rooms[2].zone = "北京紫禁城|北京"
      region.rooms[2].id = 963
      region.rooms[2].desc = "    这是一座破旧的石桥，桥下是护城河缓缓的流水。水看上去很清，据说曾有人在这里跳河(out)。这里是进皇宫正门的必经之路。"
      region.rooms[2].exits = "south|east|north|west"
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 964
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 962
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.w = {}
          region.rooms[2].links.w.to = 965
          region.rooms[2].links.w.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 966
          region.rooms[2].links.n.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly bj;n;e"
      region.rooms[3].name = "桥底东侧"
      region.rooms[3].zone = "北京紫禁城|北京"
      region.rooms[3].id = 964
      region.rooms[3].desc = "    这里是小桥东侧，一股寒风吹过，冷得你瑟瑟发抖，只想离开。"
      region.rooms[3].exits = "west"
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 963
          region.rooms[3].links.w.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly bj;n;w"
      region.rooms[4].name = "桥底西侧"
      region.rooms[4].zone = "北京紫禁城|北京"
      region.rooms[4].id = 965
      region.rooms[4].desc = "    这里是小桥西侧，一股寒风吹过，冷得你瑟瑟发抖，只想离开。"
      region.rooms[4].exits = "east"
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 963
          region.rooms[4].links.e.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly bj;n;n"
      region.rooms[5].name = "皇宫正门"
      region.rooms[5].zone = "北京紫禁城|北京"
      region.rooms[5].id = 966
      region.rooms[5].desc = "    这便是皇宫正门。巍峨雄伟的城墙上，'紫禁城'三个大字十分显眼，气势辉煌。一张镶金边的告示(gaoshi)贴在墙上，许多官兵立在两旁。"
      region.rooms[5].exits = "south|north"
      region.rooms[5].links = {}
        region.rooms[5].links.s = {}
          region.rooms[5].links.s.to = 963
          region.rooms[5].links.s.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 967
          region.rooms[5].links.n.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly bj;n;n;n"
      region.rooms[6].name = "清和殿"
      region.rooms[6].zone = "北京紫禁城"
      region.rooms[6].id = 967
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 968
          region.rooms[6].links.e.con = ""
        region.rooms[6].links.w = {}
          region.rooms[6].links.w.to = 969
          region.rooms[6].links.w.con = ""
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 966
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 973
          region.rooms[6].links.n.con = ""
      region.rooms[6].exits = "south|east|north|west"
      region.rooms[6].desc = "    这里是清和殿。西边是一条长长的走廊，通往后院。走廊上有几间卧房，那里是宫中太监的住所。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly bj;n;n;n;e"
      region.rooms[7].name = "御膳房"
      region.rooms[7].zone = "北京紫禁城"
      region.rooms[7].id = 968
      region.rooms[7].links = {}
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 967
          region.rooms[7].links.w.con = ""
      region.rooms[7].exits = "west"
      region.rooms[7].desc = "    皇宫里的膳食与平常民间的自然不同，这里就是负责皇上用膳的御膳房。你不禁想把这里的美味都尝一遍，可别忘了这可是皇宫啊。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly bj;n;n;n;w"
      region.rooms[8].name = "走廊"
      region.rooms[8].zone = "北京紫禁城"
      region.rooms[8].id = 969
      region.rooms[8].links = {}
        region.rooms[8].links.e = {}
          region.rooms[8].links.e.to = 967
          region.rooms[8].links.e.con = ""
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 972
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 971
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 970
          region.rooms[8].links.n.con = ""
      region.rooms[8].exits = "south|north|east|west"
      region.rooms[8].desc = "    这是一条走廊。房顶一侧支在西面的高墙上，另一侧则与东侧的清和殿屋顶相连。彩梁画栋，连顶棚也用彩漆绘满了各种飞天的图形，每幅精美的雕画似乎都在诉说一个娓娓动人的故事。往西通往后院，南北都有房间。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly bj;n;n;n;w;n"
      region.rooms[9].name = "房舍"
      region.rooms[9].zone = "北京紫禁城"
      region.rooms[9].id = 970
      region.rooms[9].links = {}
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 969
          region.rooms[9].links.s.con = ""
      region.rooms[9].exits = "south"
      region.rooms[9].desc = "    这里是一间小屋，一个太监正在这里休息。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly bj;n;n;n;w;s"
      region.rooms[10].name = "房舍"
      region.rooms[10].zone = "北京紫禁城"
      region.rooms[10].id = 971
      region.rooms[10].links = {}
        region.rooms[10].links.n = {}
          region.rooms[10].links.n.to = 969
          region.rooms[10].links.n.con = ""
      region.rooms[10].exits = "north"
      region.rooms[10].desc = "    这里是一间小屋，一个太监正在休息。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly bj;n;n;n;w;w"
      region.rooms[11].name = "清和殿后院"
      region.rooms[11].zone = "北京紫禁城"
      region.rooms[11].id = 972
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 969
          region.rooms[11].links.e.con = ""
      region.rooms[11].exits = "east"
      region.rooms[11].desc = "    这里是清和殿后院。院里种着些青菜。墙角有一口水井(well)。站在水井边往下看，只觉深不见底，井壁上满是滑溜溜的青苔。一个轱辘吊着一根长绳，绳端系着一个木桶。东边是一条走廊，通往清和殿。"
    region.rooms[12] = {}
      region.rooms[12].path = "fly bj;n;n;n;n"
      region.rooms[12].name = "厅廊"
      region.rooms[12].zone = "北京紫禁城"
      region.rooms[12].id = 973
      region.rooms[12].links = {}
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 976
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 967
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 974
          region.rooms[12].links.n.con = ""
      region.rooms[12].exits = "south|north|west"
      region.rooms[12].desc = "    飞檐雕栏的厅廊。两边是喜人的花草，站在这儿，隐约听得到后宫里嫔妃宫女们嬉笑的声音，宫里的人来来往往的，显得井井有条，看来宫里的规矩挺严的。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly bj;n;n;n;n;n"
      region.rooms[13].name = "厅廊"
      region.rooms[13].zone = "北京紫禁城"
      region.rooms[13].id = 974
      region.rooms[13].links = {}
        region.rooms[13].links.s = {}
          region.rooms[13].links.s.to = 973
          region.rooms[13].links.s.con = ""
        region.rooms[13].links.n = {}
          region.rooms[13].links.n.to = 975
          region.rooms[13].links.n.con = ""
      region.rooms[13].exits = "south|north"
      region.rooms[13].desc = "    飞檐雕栏的厅廊。两边是喜人的花草，站在这儿，隐约听得到后宫里嫔妃宫女们嬉笑的声音，宫里的人来来往往的，显得井井有条，看来宫里的规矩挺严的。有几个官员神情紧张地站在这儿，等着皇上召见。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly bj;n;n;n;n;n;n"
      region.rooms[14].name = "御书房"
      region.rooms[14].zone = "北京紫禁城"
      region.rooms[14].id = 975
      region.rooms[14].links = {}
        region.rooms[14].links.s = {}
          region.rooms[14].links.s.to = 974
          region.rooms[14].links.s.con = ""
      region.rooms[14].exits = "south"
      region.rooms[14].desc = "    皇上用功读书的御书房。四下齐整地排着几排书架，看来都是些名典巨著，你暗自道，原来皇上也读这么多书啊。书房正中有张精雕的檀香木桌，桌上摆着几本封面精美的帛书。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly bj;n;n;n;n;w"
      region.rooms[15].name = "厅廊"
      region.rooms[15].zone = "北京紫禁城"
      region.rooms[15].id = 976
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 973
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.n = {}
          region.rooms[15].links.n.to = 977
          region.rooms[15].links.n.con = ""
      region.rooms[15].exits = "east|north"
      region.rooms[15].desc = "    飞檐雕栏的厅廊。两边是喜人的花草，站在这儿，隐约听得到后宫里嫔妃宫女们嬉笑的声音，宫里的人来来往往的，显得井井有条，看来宫里的规矩挺严的。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly bj;n;n;n;n;w;n"
      region.rooms[16].name = "后花苑"
      region.rooms[16].zone = "北京紫禁城"
      region.rooms[16].id = 977
      region.rooms[16].links = {}
        region.rooms[16].links.w = {}
          region.rooms[16].links.w.to = 980
          region.rooms[16].links.w.con = ""
        region.rooms[16].links.s = {}
          region.rooms[16].links.s.to = 976
          region.rooms[16].links.s.con = ""
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 978
          region.rooms[16].links.n.con = ""
      region.rooms[16].exits = "south|north|west"
      region.rooms[16].desc = "    这里是皇上赏花的后花苑。平日里皇上时常会来这儿，和贵妃娘娘一起赏花品茗。所以，这儿是平常太监，侍卫不能来的。这里的宫女多是心灵手巧，精通花道的。放眼四顾，满目皆是似锦繁花，你仔细分辨,竟然品目齐全，大凡你想得的，甚至你想都不敢想的,这里都有了。你不经有些妒疾起皇帝老儿来。北边有一条小径通往一处寝宫。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly bj;n;n;n;n;w;n;n"
      region.rooms[17].name = "后花苑小径"
      region.rooms[17].zone = "北京紫禁城"
      region.rooms[17].id = 978
      region.rooms[17].links = {}
        region.rooms[17].links.s = {}
          region.rooms[17].links.s.to = 977
          region.rooms[17].links.s.con = ""
        region.rooms[17].links.n = {}
          region.rooms[17].links.n.to = 979
          region.rooms[17].links.n.con = ""
      region.rooms[17].exits = "south|north"
      region.rooms[17].desc = "    这里是皇上赏花的后花苑。平日里皇上时常会来这儿，和贵妃娘娘一起赏花品茗。所以，这儿是平常太监，侍卫不能来的。这里的宫女多是心灵手巧，精通花道的。放眼四顾，满目皆是似锦繁花，你仔细分辨,竟然品目齐全，大凡你想得的，甚至你想都不敢想的,这里都有了。你不经有些妒疾起皇帝老儿来。北边是一处寝宫。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly bj;n;n;n;n;w;n;n;n"
      region.rooms[18].name = "寝宫"
      region.rooms[18].zone = "北京紫禁城"
      region.rooms[18].id = 979
      region.rooms[18].links = {}
        region.rooms[18].links.s = {}
          region.rooms[18].links.s.to = 978
          region.rooms[18].links.s.con = ""
      region.rooms[18].exits = "south"
      region.rooms[18].desc = "    这里是一处寝宫，房里锦帏绣被，珠帘软帐，鹅黄色的地毡上织着大朵红色玫瑰，窗边桌上放着女子用的梳妆物品，到处是精巧的摆设。房子中有一座画着美人牡丹图的屏风(pingfeng)。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly bj;n;n;n;n;w;n;w"
      region.rooms[19].name = "后花苑"
      region.rooms[19].zone = "北京紫禁城"
      region.rooms[19].id = 980
      region.rooms[19].links = {}
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 977
          region.rooms[19].links.e.con = ""
        region.rooms[19].links.w = {}
          region.rooms[19].links.w.to = 981
          region.rooms[19].links.w.con = ""
      region.rooms[19].exits = "east|west"
      region.rooms[19].desc = "    这里是皇上赏花的后花苑。平日里皇上时常会来这儿，和贵妃娘娘一起赏花品茗。所以，这儿是平常太监，侍卫不能来的。这里的宫女多是心灵手巧，精通花道的。放眼四顾，满目皆是似锦繁花，你仔细分辨,竟然品目齐全，大凡你想得的，甚至你想都不敢想的,这里都有了。你不经有些妒疾起皇帝老儿来。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly bj;n;n;n;n;w;n;w;w"
      region.rooms[20].name = "马圈"
      region.rooms[20].zone = "北京紫禁城"
      region.rooms[20].id = 981
      region.rooms[20].links = {}
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 980
          region.rooms[20].links.e.con = ""
      region.rooms[20].exits = "east"
      region.rooms[20].desc = "    皇家马圈，自然是好马云集。一排排齐整的马厩，一匹匹英挺高头俊马，让你不由想起大草原上万马奔腾的壮伟景象。"
  region.center = 962
return region