local region = {}
  region.cmd = "fly wg;s;w;w;w;ne"
  region.name = "终南山"
  region.id = "zns"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly wg;|!hoteld:2:s|;w;w;w;ne"
      region.rooms[1].name = "山路"
      region.rooms[1].zone = "武功|终南山"
      region.rooms[1].id = 884
      region.rooms[1].desc = "    从武功西门出来，路势变急了，这是一条用石块铺成的山路。路两旁光秃秃的，没有什么树木，全是一块块的大石头。这条路好象通往前面的终南山上。北面有一个小村庄，村中正升起冉冉的炊烟。"
      region.rooms[1].exits = "eastup|northup|southwest"
      region.rooms[1].links = {}
        region.rooms[1].links.nu = {}
          region.rooms[1].links.nu.to = 885
          region.rooms[1].links.nu.con = ""
        region.rooms[1].links.sw = {}
          region.rooms[1].links.sw.to = 883
          region.rooms[1].links.sw.con = ""
        region.rooms[1].links.eu = {}
          region.rooms[1].links.eu.to = 1099
          region.rooms[1].links.eu.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu"
      region.rooms[2].name = "山路"
      region.rooms[2].zone = "终南山"
      region.rooms[2].id = 1099
      region.rooms[2].desc = "    一条山路弯弯曲曲地通向山上。北面的山上好象有一片柏树林，树林中隐隐露出亭子的一角，南面就是上山的路。"
      region.rooms[2].exits = "southeast|northeast|westdown"
      region.rooms[2].links = {}
        region.rooms[2].links.ne = {}
          region.rooms[2].links.ne.to = 1100
          region.rooms[2].links.ne.con = ""
        region.rooms[2].links.wd = {}
          region.rooms[2].links.wd.to = 884
          region.rooms[2].links.wd.con = ""
        region.rooms[2].links.se = {}
          region.rooms[2].links.se.to = 1107
          region.rooms[2].links.se.con = ""
    region.rooms[3] = {}
      region.rooms[3].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;ne"
      region.rooms[3].name = "山路"
      region.rooms[3].zone = "终南山"
      region.rooms[3].id = 1100
      region.rooms[3].desc = "    前面好象有一个大山谷，走到这里，树木多了些，全都是柏树。西面是一条弯曲的山路，隐藏在山间，要在夜里还真看不出来。"
      region.rooms[3].exits = "northup|southwest"
      region.rooms[3].links = {}
        region.rooms[3].links.nu = {}
          region.rooms[3].links.nu.to = 1101
          region.rooms[3].links.nu.con = ""
        region.rooms[3].links.sw = {}
          region.rooms[3].links.sw.to = 1099
          region.rooms[3].links.sw.con = ""
    region.rooms[4] = {}
      region.rooms[4].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;ne;nu"
      region.rooms[4].name = "翠屏谷"
      region.rooms[4].zone = "终南山"
      region.rooms[4].id = 1101
      region.rooms[4].desc = "    你的面前是一座形如屏风的大山壁，山壁上郁郁葱葱都是树，一眼看过去，全是一片翠绿色。这就是此地名叫翠屏谷的由来。从这里继续北上，就到了终南山上的柏树林了。"
      region.rooms[4].exits = "northup|southdown"
      region.rooms[4].links = {}
        region.rooms[4].links.sd = {}
          region.rooms[4].links.sd.to = 1100
          region.rooms[4].links.sd.con = ""
        region.rooms[4].links.nu = {}
          region.rooms[4].links.nu.to = 1102
          region.rooms[4].links.nu.con = ""
    region.rooms[5] = {}
      region.rooms[5].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;ne;nu;nu"
      region.rooms[5].name = "柏树林"
      region.rooms[5].zone = "终南山"
      region.rooms[5].id = 1102
      region.rooms[5].desc = "    绕过翠屏谷的山壁，眼前是一片大柏树林，想是由于山壁挡住了视线，在山下的山路上根本想不到这里的柏树竟会有这么密这么高。你踏进柏树林中，阳光全被头顶的树叶遮住了，越往树林深处，光线越是幽暗。"
      region.rooms[5].exits = "east|northup|southdown"
      region.rooms[5].links = {}
        region.rooms[5].links.nu = {}
          region.rooms[5].links.nu.to = 1103
          region.rooms[5].links.nu.con = ""
        region.rooms[5].links.sd = {}
          region.rooms[5].links.sd.to = 1101
          region.rooms[5].links.sd.con = ""
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 1106
          region.rooms[5].links.e.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;ne;nu;nu;nu"
      region.rooms[6].name = "柏树林"
      region.rooms[6].zone = "终南山"
      region.rooms[6].id = 1103
      region.rooms[6].desc = "    你走进了柏树林的深处，脚下踩着厚厚的落叶，松松软软。这里的光线非常阴暗，你几乎什么都看不清了。突然一只松鼠从你眼前的树枝上猛地跳了过去，吓了你一跳。"
      region.rooms[6].exits = "east|northup|southdown"
      region.rooms[6].links = {}
        region.rooms[6].links.nu = {}
          region.rooms[6].links.nu.to = 1104
          region.rooms[6].links.nu.con = ""
        region.rooms[6].links.sd = {}
          region.rooms[6].links.sd.to = 1102
          region.rooms[6].links.sd.con = ""
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 1105
          region.rooms[6].links.e.con = ""
    region.rooms[7] = {}
      region.rooms[7].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;ne;nu;nu;nu;nu"
      region.rooms[7].name = "翠屏峰顶"
      region.rooms[7].zone = "终南山"
      region.rooms[7].id = 1104
      region.rooms[7].desc = "    这里是翠屏峰的峰顶。翠屏峰是终南山的第一峰，也是最矮的一个山峰。悬崖边建有一个小亭子，你走进亭中凭拦远望，远处的山间白云漂浮缭绕，好象修筑着什么建筑，山景清丽，可惜被白云尽遮住了。几个游客也在亭中歇脚，正啧啧赞美着此地美景。"
      region.rooms[7].exits = "southdown"
      region.rooms[7].links = {}
        region.rooms[7].links.sd = {}
          region.rooms[7].links.sd.to = 1103
          region.rooms[7].links.sd.con = ""
    region.rooms[8] = {}
      region.rooms[8].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;ne;nu;nu;nu;e"
      region.rooms[8].name = "柏树林"
      region.rooms[8].zone = "终南山"
      region.rooms[8].id = 1105
      region.rooms[8].desc = "    这里是树林的边缘，光线亮的多了。参天的柏树也稀疏了很多。旁边有一丛灌木(frutex)杂生。灌木再往前，就是悬崖了。"
      region.rooms[8].exits = "southdown|west"
      region.rooms[8].links = {}
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 1103
          region.rooms[8].links.w.con = ""
        region.rooms[8].links.sd = {}
          region.rooms[8].links.sd.to = 1106
          region.rooms[8].links.sd.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;ne;nu;nu;e"
      region.rooms[9].name = "柏树林"
      region.rooms[9].zone = "终南山"
      region.rooms[9].id = 1106
      region.rooms[9].desc = "    你走进了柏树林的深处，脚下踩着厚厚的落叶，松松软软。这里的光线非常阴暗，你几乎什么都看不清了。突然一只松鼠从你眼前的树枝上猛地跳了过去，吓了你一跳。"
      region.rooms[9].exits = "northup|west"
      region.rooms[9].links = {}
        region.rooms[9].links.nu = {}
          region.rooms[9].links.nu.to = 1105
          region.rooms[9].links.nu.con = ""
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 1102
          region.rooms[9].links.w.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se"
      region.rooms[10].name = "山路"
      region.rooms[10].zone = "终南山"
      region.rooms[10].id = 1107
      region.rooms[10].desc = "    这里是山路的尽头，南面好象有一片小树林，折而向东，就是终南山的山脚了。"
      region.rooms[10].exits = "northwest|eastup"
      region.rooms[10].links = {}
        region.rooms[10].links.nw = {}
          region.rooms[10].links.nw.to = 1099
          region.rooms[10].links.nw.con = ""
        region.rooms[10].links.eu = {}
          region.rooms[10].links.eu.to = 1108
          region.rooms[10].links.eu.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu"
      region.rooms[11].name = "终南山脚"
      region.rooms[11].zone = "终南山"
      region.rooms[11].id = 1108
      region.rooms[11].desc = "    这里是终南山的山脚，终南山号称西北的第一山，以山势奇峻，环境清幽著称。这里的山势还很平缓，一道石阶蜿蜒通往山上。面前是一座高山，如同擎天一柱般插向天空，所以古人的诗句中有‘终南一柱’的说法。"
      region.rooms[11].exits = "north|westdown"
      region.rooms[11].links = {}
        region.rooms[11].links.wd = {}
          region.rooms[11].links.wd.to = 1107
          region.rooms[11].links.wd.con = ""
        region.rooms[11].links.n = {}
          region.rooms[11].links.n.to = 1109
          region.rooms[11].links.n.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n"
      region.rooms[12].name = "道路"
      region.rooms[12].zone = "终南山"
      region.rooms[12].id = 1109
      region.rooms[12].desc = "    此处位於终南山山脚。巍峨的终南山，自古以来就是历代名人游览的圣地。它西起甘肃的岐山，东至陕西的潼关，其间跨越十馀县，连绵八百馀里。素有万里终南山之称。往东可看见一座寺庙。往西是一条通往密林的幽静小路。往北可上终南山."
      region.rooms[12].exits = "south|east|northup|west"
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 1115
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 1110
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.s = {}
          region.rooms[12].links.s.to = 1108
          region.rooms[12].links.s.con = ""
        region.rooms[12].links.nu = {}
          region.rooms[12].links.nu.to = 1116
          region.rooms[12].links.nu.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;w"
      region.rooms[13].name = "山间小径"
      region.rooms[13].zone = "终南山"
      region.rooms[13].id = 1110
      region.rooms[13].desc = "    这是一条位於终南山脚，鲜为人知的小径。四周古木参天，树林苍翠，遍地山花，枝头啼鸟唱和不绝。往东可看到一条道路。往西北可通往山林深处。"
      region.rooms[13].exits = "northwest|east"
      region.rooms[13].links = {}
        region.rooms[13].links.e = {}
          region.rooms[13].links.e.to = 1109
          region.rooms[13].links.e.con = ""
        region.rooms[13].links.nw = {}
          region.rooms[13].links.nw.to = 1111
          region.rooms[13].links.nw.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;w;nw"
      region.rooms[14].name = "山间小径"
      region.rooms[14].zone = "终南山"
      region.rooms[14].id = 1111
      region.rooms[14].desc = "    这是一条位於终南山脚，鲜为人知的小径。四周古木参天，树林苍翠，遍地山花，枝头啼鸟唱和不绝。往西和东南可通往山林深处。"
      region.rooms[14].exits = "southeast|west"
      region.rooms[14].links = {}
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 1112
          region.rooms[14].links.w.con = ""
        region.rooms[14].links.se = {}
          region.rooms[14].links.se.to = 1110
          region.rooms[14].links.se.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;w;nw;w"
      region.rooms[15].name = "山间小径"
      region.rooms[15].zone = "终南山"
      region.rooms[15].id = 1112
      region.rooms[15].desc = "    这是一条位於终南山脚，鲜为人知的小径。四周古木参天，树林苍翠，遍地山花，枝头啼鸟唱和不绝。往南可看到一条小河。往东可通往山林深处。"
      region.rooms[15].exits = "south|east"
      region.rooms[15].links = {}
        region.rooms[15].links.e = {}
          region.rooms[15].links.e.to = 1111
          region.rooms[15].links.e.con = ""
        region.rooms[15].links.s = {}
          region.rooms[15].links.s.to = 1113
          region.rooms[15].links.s.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;w;nw;w;s"
      region.rooms[16].name = "小河边"
      region.rooms[16].zone = "终南山"
      region.rooms[16].id = 1113
      region.rooms[16].desc = "    此处位於终南山角一偏僻处，只见浓荫匝地，花光浮动，周围尽是参天古木，颇具幽静之美。不远处的小河由山洞(dong)中涌出的泉水所形成，淙淙的水声更让你觉得身心顺畅。往北可通往山林深处。往西可进入山洞中。"
      region.rooms[16].exits = "north|enter"
      region.rooms[16].links = {}
        region.rooms[16].links.enter = {}
          region.rooms[16].links.enter.to = 1114
          region.rooms[16].links.enter.con = ""
        region.rooms[16].links.n = {}
          region.rooms[16].links.n.to = 1112
          region.rooms[16].links.n.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;w;nw;w;s;enter"
      region.rooms[17].name = "山洞"
      region.rooms[17].zone = "终南山|古墓"
      region.rooms[17].id = 1114
      region.rooms[17].links = {}
        region.rooms[17].links.out = {}
          region.rooms[17].links.out.to = 1113
          region.rooms[17].links.out.con = ""
      region.rooms[17].exits = "westdown|out"
      region.rooms[17].desc = "    在这小山洞的深处，一股强大的水流自地上流出，形成一条小河流向洞外。如果想再进一步深入的话，就得要跳入水中了。往外可到小河边。往里就要潜水了。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;e"
      region.rooms[18].name = "普光寺"
      region.rooms[18].zone = "终南山"
      region.rooms[18].id = 1115
      region.rooms[18].desc = "    这是一个位於终南山下的小寺庙，庙门横额写着 \"普光寺\" 三个大字。由於此庙是上终南山的必经之路，大多数的游客都会在此落脚休息，也因此此处香火也颇为鼎盛。庙前的几株松树下，立着一块石碑(shibei)，几乎快被周围的长草给遮掩了。往西走是一条小路."
      region.rooms[18].exits = "west"
      region.rooms[18].links = {}
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 1109
          region.rooms[18].links.w.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu"
      region.rooms[19].name = "山路"
      region.rooms[19].zone = "终南山"
      region.rooms[19].id = 1116
      region.rooms[19].desc = "    这是一条非常崎岖难行的山路，一路蜿蜒盘山ㄦ上，沿途均是葱郁的古柏山林，蔚然森秀。在此处可眺望终南山的景色，只见山险岭峻，山川毓秀，往南下是一条道路。往北上走是一条蜿蜒的山路。"
      region.rooms[19].exits = "northup|southdown"
      region.rooms[19].links = {}
        region.rooms[19].links.sd = {}
          region.rooms[19].links.sd.to = 1109
          region.rooms[19].links.sd.con = ""
        region.rooms[19].links.nu = {}
          region.rooms[19].links.nu.to = 1117
          region.rooms[19].links.nu.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu"
      region.rooms[20].name = "山路"
      region.rooms[20].zone = "终南山"
      region.rooms[20].id = 1117
      region.rooms[20].desc = "    这是一条非常崎岖难行的山路，一路蜿蜒盘山ㄦ上，沿途均是葱郁的古柏山林，蔚然森秀。在此处可眺望终南山的景色，只见山险岭峻，山川毓秀。往北上走是金莲阁。往南走是崎岖的山路。"
      region.rooms[20].exits = "northup|southdown"
      region.rooms[20].links = {}
        region.rooms[20].links.sd = {}
          region.rooms[20].links.sd.to = 1116
          region.rooms[20].links.sd.con = ""
        region.rooms[20].links.nu = {}
          region.rooms[20].links.nu.to = 1118
          region.rooms[20].links.nu.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu"
      region.rooms[21].name = "金莲阁"
      region.rooms[21].zone = "终南山"
      region.rooms[21].id = 1118
      region.rooms[21].desc = "    这金莲阁位於终南山山腰间，形势颇为险要。金莲阁後有一口碗口粗的涌泉，泉水碧绿透明，香甜诱人，在当地颇为有名，不少人特别来此，只为了取这ㄦ的水来泡茶。那寺前的一块石碑(shibei)，刻了一收首王维的诗。往南看去是一条山路。往西走是一条蜿蜒的山路。"
      region.rooms[21].exits = "westup|southdown"
      region.rooms[21].links = {}
        region.rooms[21].links.sd = {}
          region.rooms[21].links.sd.to = 1117
          region.rooms[21].links.sd.con = ""
        region.rooms[21].links.wu = {}
          region.rooms[21].links.wu.to = 1119
          region.rooms[21].links.wu.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu"
      region.rooms[22].name = "山路"
      region.rooms[22].zone = "终南山"
      region.rooms[22].id = 1119
      region.rooms[22].desc = "    这是一条非常崎岖难行的山路，一路蜿蜒盘山ㄦ上，沿途均是葱郁的古柏山林，蔚然森秀。在此处可眺望终南山的景色，只见山险岭峻，山川毓秀，不少鸟ㄦ在枝头高声啼唱不绝。往东下是莲花寺。往西上是一条山路。"
      region.rooms[22].exits = "westup|eastdown"
      region.rooms[22].links = {}
        region.rooms[22].links.ed = {}
          region.rooms[22].links.ed.to = 1118
          region.rooms[22].links.ed.con = ""
        region.rooms[22].links.wu = {}
          region.rooms[22].links.wu.to = 1120
          region.rooms[22].links.wu.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu"
      region.rooms[23].name = "日月岩"
      region.rooms[23].zone = "终南山"
      region.rooms[23].id = 1120
      region.rooms[23].desc = "    一路过来，只见光秃秃的山路两旁，怪石林立，颇为吓人。尤其是前方不远处的两块巨石，左边的一块像月亮，右边的那块像太阳，夹道而立，便如一对门神，只留当中一条宽约一人多的小道，让人通过。往东下和北上走都是一条蜿蜒的山路。"
      region.rooms[23].exits = "eastdown|northup"
      region.rooms[23].links = {}
        region.rooms[23].links.ed = {}
          region.rooms[23].links.ed.to = 1119
          region.rooms[23].links.ed.con = ""
        region.rooms[23].links.nu = {}
          region.rooms[23].links.nu.to = 1121
          region.rooms[23].links.nu.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu"
      region.rooms[24].name = "山路"
      region.rooms[24].zone = "终南山"
      region.rooms[24].id = 1121
      region.rooms[24].desc = "    这是一条非常崎岖难行的山路，一路蜿蜒盘山ㄦ上，沿途均是葱郁的古柏山林，蔚然森秀。在此处可眺望终南山的景色，只见山险岭峻，山川毓秀，不少鸟ㄦ在枝头高声啼唱不绝。往南下是两块耸天而立的巨石。往北是一片蓊郁的山林。"
      region.rooms[24].exits = "northup|southdown"
      region.rooms[24].links = {}
        region.rooms[24].links.sd = {}
          region.rooms[24].links.sd.to = 1120
          region.rooms[24].links.sd.con = ""
        region.rooms[24].links.nu = {}
          region.rooms[24].links.nu.to = 1122
          region.rooms[24].links.nu.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu"
      region.rooms[25].name = "树林"
      region.rooms[25].zone = "终南山"
      region.rooms[25].id = 1122
      region.rooms[25].desc = "    这位於终南山间的一大片树林，生的颇为茂密。走在其间，只听得脚下沙沙的落叶声，四周昏昏暗暗的，不时几道日光穿过浓密的枝头，投射而下。偶而远处几声兽吼声，更添了一份神密感。往北和往南各有一条小径。"
      region.rooms[25].exits = "north|southdown"
      region.rooms[25].links = {}
        region.rooms[25].links.sd = {}
          region.rooms[25].links.sd.to = 1121
          region.rooms[25].links.sd.con = ""
        region.rooms[25].links.n = {}
          region.rooms[25].links.n.to = 1123
          region.rooms[25].links.n.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n"
      region.rooms[26].name = "抱子岩"
      region.rooms[26].zone = "终南山"
      region.rooms[26].id = 1123
      region.rooms[26].desc = "    一路过来，山路是越来越险。只见光秃秃的山路，左旁尽是怪石，而右则是万丈深渊，渺不见底。前方不远处的一块巨石，便是有名的抱子岩。再看几眼，觉那岩生得甚是奇怪，就如一个妇人抱着个孩子般，细心呵护。往南和西各是一片密林。"
      region.rooms[26].exits = "south|west"
      region.rooms[26].links = {}
        region.rooms[26].links.s = {}
          region.rooms[26].links.s.to = 1122
          region.rooms[26].links.s.con = ""
        region.rooms[26].links.w = {}
          region.rooms[26].links.w.to = 1124
          region.rooms[26].links.w.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w"
      region.rooms[27].name = "树林"
      region.rooms[27].zone = "终南山"
      region.rooms[27].id = 1124
      region.rooms[27].desc = "    这位於终南山间的一大片树林，生的颇为茂密。走在其间，只听得脚下沙沙的落叶声，四周昏昏暗暗的，不时几道日光穿过浓密的枝头，投射而下。偶而远处几声兽吼声，更添了一份神密感。往西北和往东各有一条小径。"
      region.rooms[27].exits = "east|northwest"
      region.rooms[27].links = {}
        region.rooms[27].links.e = {}
          region.rooms[27].links.e.to = 1123
          region.rooms[27].links.e.con = ""
        region.rooms[27].links.nw = {}
          region.rooms[27].links.nw.to = 1125
          region.rooms[27].links.nw.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw"
      region.rooms[28].name = "神禾原"
      region.rooms[28].zone = "终南山"
      region.rooms[28].id = 1125
      region.rooms[28].desc = "    此处位於终南山中部的翠华山附近。放眼望去，只见一片坦荡无垠的大平原，夹在群山之间。传说商朝末年，姜子牙率兵伐纣攻打长安时，粮草短缺，在此获神禾老汉之助，得米万斛，因此命名为神禾原。往东南和北上各是一片树林。往南是一处遗迹。"
      region.rooms[28].exits = "north|southeast|west"
      region.rooms[28].links = {}
        region.rooms[28].links.se = {}
          region.rooms[28].links.se.to = 1124
          region.rooms[28].links.se.con = ""
        region.rooms[28].links.w = {}
          region.rooms[28].links.w.to = 1126
          region.rooms[28].links.w.con = ""
        region.rooms[28].links.n = {}
          region.rooms[28].links.n.to = 1127
          region.rooms[28].links.n.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;w"
      region.rooms[29].name = "佛爷掌"
      region.rooms[29].zone = "终南山"
      region.rooms[29].id = 1126
      region.rooms[29].desc = "    只见此处颇为荒凉，是一处寺院的遗址。四周青松翠柏环绕，寺院的断垣残璧依稀可见，似乎还是一座不小的寺院。往北是一片平原。"
      region.rooms[29].exits = "east"
      region.rooms[29].links = {}
        region.rooms[29].links.e = {}
          region.rooms[29].links.e.to = 1125
          region.rooms[29].links.e.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n"
      region.rooms[30].name = "树林"
      region.rooms[30].zone = "终南山"
      region.rooms[30].id = 1127
      region.rooms[30].desc = "    这位於终南山间的一大片树林，生的颇为茂密。走在其间，只听得脚下沙沙的落叶声，四周昏昏暗暗的，不时几道日光穿过浓密的枝头，投射而下。偶而远处几声兽吼声，更添了一份神密感。往北、南、和东各有一条小径。"
      region.rooms[30].exits = "south|eastdown|northup"
      region.rooms[30].links = {}
        region.rooms[30].links.ed = {}
          region.rooms[30].links.ed.to = 1128
          region.rooms[30].links.ed.con = ""
        region.rooms[30].links.s = {}
          region.rooms[30].links.s.to = 1125
          region.rooms[30].links.s.con = ""
        region.rooms[30].links.nu = {}
          region.rooms[30].links.nu.to = 1129
          region.rooms[30].links.nu.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;ed"
      region.rooms[31].name = "黑凤洞"
      region.rooms[31].zone = "终南山"
      region.rooms[31].id = 1128
      region.rooms[31].desc = "    此处位於终南山脉东部的太阳山上。只见山峰直上直下，像刀切般的陡峭，只山腰上有一个碾盘子粗的石洞，不时冒出一股黑气，怪可怕的。往西是一片树林。"
      region.rooms[31].exits = "westup"
      region.rooms[31].links = {}
        region.rooms[31].links.wu = {}
          region.rooms[31].links.wu.to = 1127
          region.rooms[31].links.wu.con = ""
    region.rooms[32] = {}
      region.rooms[32].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu"
      region.rooms[32].name = "老妪岩"
      region.rooms[32].zone = "终南山"
      region.rooms[32].id = 1129
      region.rooms[32].desc = "    一路过来，山路是越来越险。只见一块大岩石挡在路中，自空凭临，宛似一个老妇弯腰俯视，但形状阴森可怖，令人望而生畏。不少游客在此驻足观看，往南是一片茂密的松林。往北上是一条陡峭的山路。"
      region.rooms[32].exits = "northup|southdown"
      region.rooms[32].links = {}
        region.rooms[32].links.sd = {}
          region.rooms[32].links.sd.to = 1127
          region.rooms[32].links.sd.con = ""
        region.rooms[32].links.nu = {}
          region.rooms[32].links.nu.to = 1130
          region.rooms[32].links.nu.con = ""
    region.rooms[33] = {}
      region.rooms[33].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu"
      region.rooms[33].name = "山道"
      region.rooms[33].zone = "终南山"
      region.rooms[33].id = 1130
      region.rooms[33].desc = "    此段山路是沿着峭壁而开凿出来的，特别崎岖难行。有时峭壁边必须面贴山璧，侧身而过。尤其当山凤吹来时，更需特别小心，不然一失足，就要掉进万丈深渊了。往北是一块广大的空地。往南下是一块巨岩。"
      region.rooms[33].exits = "northup|southdown"
      region.rooms[33].links = {}
        region.rooms[33].links.sd = {}
          region.rooms[33].links.sd.to = 1129
          region.rooms[33].links.sd.con = ""
        region.rooms[33].links.nu = {}
          region.rooms[33].links.nu.to = 1131
          region.rooms[33].links.nu.con = ""
    region.rooms[34] = {}
      region.rooms[34].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu"
      region.rooms[34].name = "大校场"
      region.rooms[34].zone = "终南山"
      region.rooms[34].id = 1131
      region.rooms[34].desc = "    这是一个位於终南山山腰的圆坪，四周群山环抱。山脚下有一座大池。每年腊月，全真派便於此地举行大校，以考察门下弟子在这一年间的进境。往南是一条崎岖的山道。往西是一条通往峰顶的山路。往北行便是重阳宫。这路边被疯长的野草掩盖了一个小洞（dong）。只见远处十馀幢道观屋宇疏疏落落的散处山间。"
      region.rooms[34].exits = "westup|northup|southdown"
      region.rooms[34].links = {}
        region.rooms[34].links.nu = {}
          region.rooms[34].links.nu.to = 1132
          region.rooms[34].links.nu.con = ""
        region.rooms[34].links.sd = {}
          region.rooms[34].links.sd.to = 1130
          region.rooms[34].links.sd.con = ""
        region.rooms[34].links.wu = {}
          region.rooms[34].links.wu.to = 1148
          region.rooms[34].links.wu.con = ""
    region.rooms[35] = {}
      region.rooms[35].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu"
      region.rooms[35].name = "石阶"
      region.rooms[35].zone = "终南山"
      region.rooms[35].id = 1132
      region.rooms[35].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。"
      region.rooms[35].exits = "northup|southdown"
      region.rooms[35].links = {}
        region.rooms[35].links.sd = {}
          region.rooms[35].links.sd.to = 1131
          region.rooms[35].links.sd.con = ""
        region.rooms[35].links.nu = {}
          region.rooms[35].links.nu.to = 1133
          region.rooms[35].links.nu.con = ""
    region.rooms[36] = {}
      region.rooms[36].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu"
      region.rooms[36].name = "石阶"
      region.rooms[36].zone = "终南山"
      region.rooms[36].id = 1133
      region.rooms[36].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。"
      region.rooms[36].exits = "southeast|southdown"
      region.rooms[36].links = {}
        region.rooms[36].links.sd = {}
          region.rooms[36].links.sd.to = 1132
          region.rooms[36].links.sd.con = ""
        region.rooms[36].links.se = {}
          region.rooms[36].links.se.to = 1134
          region.rooms[36].links.se.con = ""
    region.rooms[37] = {}
      region.rooms[37].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se"
      region.rooms[37].name = "石阶"
      region.rooms[37].zone = "终南山"
      region.rooms[37].id = 1134
      region.rooms[37].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。"
      region.rooms[37].exits = "northwest|eastup"
      region.rooms[37].links = {}
        region.rooms[37].links.nw = {}
          region.rooms[37].links.nw.to = 1133
          region.rooms[37].links.nw.con = ""
        region.rooms[37].links.eu = {}
          region.rooms[37].links.eu.to = 1135
          region.rooms[37].links.eu.con = ""
    region.rooms[38] = {}
      region.rooms[38].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu"
      region.rooms[38].name = "石阶"
      region.rooms[38].zone = "终南山"
      region.rooms[38].id = 1135
      region.rooms[38].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。"
      region.rooms[38].exits = "northup|southup|westdown"
      region.rooms[38].links = {}
        region.rooms[38].links.nu = {}
          region.rooms[38].links.nu.to = 1136
          region.rooms[38].links.nu.con = ""
        region.rooms[38].links.wd = {}
          region.rooms[38].links.wd.to = 1134
          region.rooms[38].links.wd.con = ""
        region.rooms[38].links.su = {}
          region.rooms[38].links.su.to = 1138
          region.rooms[38].links.su.con = ""
    region.rooms[39] = {}
      region.rooms[39].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;nu"
      region.rooms[39].name = "石阶"
      region.rooms[39].zone = "终南山"
      region.rooms[39].id = 1136
      region.rooms[39].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。"
      region.rooms[39].exits = "northup|southdown"
      region.rooms[39].links = {}
        region.rooms[39].links.sd = {}
          region.rooms[39].links.sd.to = 1135
          region.rooms[39].links.sd.con = ""
        region.rooms[39].links.nu = {}
          region.rooms[39].links.nu.to = 1137
          region.rooms[39].links.nu.con = ""
    region.rooms[40] = {}
      region.rooms[40].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;nu;nu"
      region.rooms[40].name = "半山亭"
      region.rooms[40].zone = "终南山"
      region.rooms[40].id = 1137
      region.rooms[40].desc = "    这里是半山腰的一个小凉亭，游客们爬山爬的累了，就转个弯到这里来坐一坐，歇一歇脚。从这里看下去，刚好可以看见翠屏峰的峰顶。"
      region.rooms[40].exits = "southdown"
      region.rooms[40].links = {}
        region.rooms[40].links.sd = {}
          region.rooms[40].links.sd.to = 1136
          region.rooms[40].links.sd.con = ""
    region.rooms[41] = {}
      region.rooms[41].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su"
      region.rooms[41].name = "试剑岩"
      region.rooms[41].zone = "终南山"
      region.rooms[41].id = 1138
      region.rooms[41].desc = "    石阶旁立着一块大岩石，上面斑斑驳驳的尽是砍伤。这块大岩石便是全真教的试剑岩，天下的英雄来到这里，望着先辈们练剑时在岩石上的砍痕，无不肃然起敬。"
      region.rooms[41].exits = "east|southup|northdown"
      region.rooms[41].links = {}
        region.rooms[41].links.e = {}
          region.rooms[41].links.e.to = 1142
          region.rooms[41].links.e.con = ""
        region.rooms[41].links.nd = {}
          region.rooms[41].links.nd.to = 1135
          region.rooms[41].links.nd.con = ""
        region.rooms[41].links.su = {}
          region.rooms[41].links.su.to = 1139
          region.rooms[41].links.su.con = ""
    region.rooms[42] = {}
      region.rooms[42].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su;su"
      region.rooms[42].name = "石阶"
      region.rooms[42].zone = "终南山"
      region.rooms[42].id = 1139
      region.rooms[42].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。"
      region.rooms[42].exits = "southup|northdown"
      region.rooms[42].links = {}
        region.rooms[42].links.nd = {}
          region.rooms[42].links.nd.to = 1138
          region.rooms[42].links.nd.con = ""
        region.rooms[42].links.su = {}
          region.rooms[42].links.su.to = 1140
          region.rooms[42].links.su.con = ""
    region.rooms[43] = {}
      region.rooms[43].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su;su;su"
      region.rooms[43].name = "石阶"
      region.rooms[43].zone = "终南山"
      region.rooms[43].id = 1140
      region.rooms[43].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。西面好象有一条小路。"
      region.rooms[43].exits = "south|northdown"
      region.rooms[43].links = {}
        region.rooms[43].links.s = {}
          region.rooms[43].links.s.to = 1141
          region.rooms[43].links.s.con = ""
        region.rooms[43].links.nd = {}
          region.rooms[43].links.nd.to = 1139
          region.rooms[43].links.nd.con = ""
    region.rooms[44] = {}
      region.rooms[44].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su;su;su;s"
      region.rooms[44].name = "观日台"
      region.rooms[44].zone = "终南山"
      region.rooms[44].id = 1141
      region.rooms[44].desc = "    这里是终南山上的观日台，不知哪朝哪代何人在这里修筑了这个平台，用来观瞻日出的美景。这里的山势非常陡峻，往下一看，悬崖壁立，脚下白云飘过，真不知身在何境。"
      region.rooms[44].exits = "north"
      region.rooms[44].links = {}
        region.rooms[44].links.n = {}
          region.rooms[44].links.n.to = 1140
          region.rooms[44].links.n.con = ""
    region.rooms[45] = {}
      region.rooms[45].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su;e"
      region.rooms[45].name = "教碑"
      region.rooms[45].zone = "终南山"
      region.rooms[45].id = 1142
      region.rooms[45].desc = "    这里是全真教的教碑所在地，路旁立着一块大碑(bei)。再往东走就是天下闻名的道家玄门正宗--全真教的大门了。北面有一条石阶，不知道通向哪里，往西是下山的路。"
      region.rooms[45].exits = "eastup|northup|west"
      region.rooms[45].links = {}
        region.rooms[45].links.nu = {}
          region.rooms[45].links.nu.to = 1143
          region.rooms[45].links.nu.con = ""
        region.rooms[45].links.eu = {}
          region.rooms[45].links.eu.to = 1147
          region.rooms[45].links.eu.con = ""
        region.rooms[45].links.w = {}
          region.rooms[45].links.w.to = 1138
          region.rooms[45].links.w.con = ""
    region.rooms[46] = {}
      region.rooms[46].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su;e;nu"
      region.rooms[46].name = "石阶"
      region.rooms[46].zone = "终南山"
      region.rooms[46].id = 1143
      region.rooms[46].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。"
      region.rooms[46].exits = "northup|southdown"
      region.rooms[46].links = {}
        region.rooms[46].links.sd = {}
          region.rooms[46].links.sd.to = 1142
          region.rooms[46].links.sd.con = ""
        region.rooms[46].links.nu = {}
          region.rooms[46].links.nu.to = 1144
          region.rooms[46].links.nu.con = ""
    region.rooms[47] = {}
      region.rooms[47].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su;e;nu;nu"
      region.rooms[47].name = "石阶"
      region.rooms[47].zone = "终南山"
      region.rooms[47].id = 1144
      region.rooms[47].desc = "    这是一条整齐的石板路，依山而建，随着山势的曲折蜿蜒曲折。由于山势陡了，当初修建这条石阶时肯定费了不小的功夫。走到这里，已经可以看见全真教重阳观的檐角了。"
      region.rooms[47].exits = "northup|southdown"
      region.rooms[47].links = {}
        region.rooms[47].links.sd = {}
          region.rooms[47].links.sd.to = 1143
          region.rooms[47].links.sd.con = ""
        region.rooms[47].links.nu = {}
          region.rooms[47].links.nu.to = 1145
          region.rooms[47].links.nu.con = ""
    region.rooms[48] = {}
      region.rooms[48].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su;e;nu;nu;nu"
      region.rooms[48].name = "访真桥"
      region.rooms[48].zone = "终南山"
      region.rooms[48].id = 1145
      region.rooms[48].desc = "    跨过石阶，眼前是一座石头砌成的小小拱桥。桥上栏杆上雕龙描凤，栩栩如生。这里的山势非常陡峻，往下一看，悬崖壁立，脚下白云飘过，真不知身在何境。"
      region.rooms[48].exits = "north|southdown"
      region.rooms[48].links = {}
        region.rooms[48].links.sd = {}
          region.rooms[48].links.sd.to = 1144
          region.rooms[48].links.sd.con = ""
        region.rooms[48].links.n = {}
          region.rooms[48].links.n.to = 1146
          region.rooms[48].links.n.con = ""
    region.rooms[49] = {}
      region.rooms[49].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;nu;nu;se;eu;su;e;nu;nu;nu;n"
      region.rooms[49].name = "遇真宫"
      region.rooms[49].zone = "终南山"
      region.rooms[49].id = 1146
      region.rooms[49].desc = "    这里是重阳宫以前的旧址，是王重阳王真人参悟大道之前清修的地方。后来手创全真教后，此地的布局实在太小，就将重阳宫迁到东面山上，将此地重新改名为遇真宫，以纪念得道之意。这里很久没有人来过了，桌椅上都积满了灰尘。"
      region.rooms[49].exits = "south"
      region.rooms[49].links = {}
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 1145
          region.rooms[49].links.s.con = ""
    region.rooms[50] = {}
      region.rooms[50].path = "fly qzj"
      region.rooms[50].name = "重阳宫大门"
      region.rooms[50].zone = "终南山|全真教"
      region.rooms[50].id = 1147
      region.rooms[50].links = {}
        region.rooms[50].links.wd = {}
          region.rooms[50].links.wd.to = 1142
          region.rooms[50].links.wd.con = ""
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 1194
          region.rooms[50].links.e.con = "knock gate"
      region.rooms[50].exits = "westdown"
      region.rooms[50].desc = "    你已走到了终南山半山腰，前面就是全真教的总部重阳宫了。殿宇依山而筑，高低错落有致。周围古木森森，翠竹成林，景色清幽。正前方黄墙碧瓦，飞檐翘檩，正中一道二丈来宽，三丈来高的朱红杉木包铜大门(gate)，气势不凡。门上挂着一块匾(bian)，门前的石柱上挂着一副对联(duilian)。"
    region.rooms[51] = {}
      region.rooms[51].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu"
      region.rooms[51].name = "山路"
      region.rooms[51].zone = "终南山"
      region.rooms[51].id = 1148
      region.rooms[51].desc = "    这是一条非常崎岖难行的山路，一路蜿蜒盘山ㄦ上，沿途均是葱郁的古柏山林，蔚然森秀。在此处可眺望终南山的景色，只见山险岭峻，山川毓秀，不少鸟ㄦ在枝头高声啼唱不绝。往北下是草堂寺。往西上是一条山路。往东是一块广大的空地。往西北通往后山下。"
      region.rooms[51].exits = "westup|northwest|eastdown|northdown"
      region.rooms[51].links = {}
        region.rooms[51].links.ed = {}
          region.rooms[51].links.ed.to = 1131
          region.rooms[51].links.ed.con = ""
        region.rooms[51].links.nd = {}
          region.rooms[51].links.nd.to = 1149
          region.rooms[51].links.nd.con = ""
        region.rooms[51].links.nw = {}
          region.rooms[51].links.nw.to = 1150
          region.rooms[51].links.nw.con = ""
        region.rooms[51].links.wu = {}
          region.rooms[51].links.wu.to = 1157
          region.rooms[51].links.wu.con = ""
    region.rooms[52] = {}
      region.rooms[52].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu;nd"
      region.rooms[52].name = "草堂寺"
      region.rooms[52].zone = "终南山"
      region.rooms[52].id = 1149
      region.rooms[52].desc = "    这是一座位於终南山北麓的小寺。寺院中的一口古井，名为烟雾井。因为每天清晨都会有一股巨大的烟雾，自井里袅袅升起，不少游客来此，就是为了一观此奇景。往南上是一条崎岖的山道。往北是一条阴森森的小径。"
      region.rooms[52].exits = "southup"
      region.rooms[52].links = {}
        region.rooms[52].links.su = {}
          region.rooms[52].links.su.to = 1148
          region.rooms[52].links.su.con = ""
    region.rooms[53] = {}
      region.rooms[53].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu;nw"
      region.rooms[53].name = "山道"
      region.rooms[53].zone = "终南山"
      region.rooms[53].id = 1150
      region.rooms[53].desc = "    此段山路是沿着峭壁而开凿出来的，特别崎岖难行。有时峭壁边必须面贴山璧，侧身而过。尤其当山凤吹来时，更需特别小心，不然一失足，就要掉进万丈深渊了。往东南是一块广大的空地。往北下通往后山脚，远远可以望见一个较大的湖。"
      region.rooms[53].exits = "southeast|northdown"
      region.rooms[53].links = {}
        region.rooms[53].links.se = {}
          region.rooms[53].links.se.to = 1148
          region.rooms[53].links.se.con = ""
        region.rooms[53].links.nd = {}
          region.rooms[53].links.nd.to = 1151
          region.rooms[53].links.nd.con = ""
    region.rooms[54] = {}
      region.rooms[54].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu;nw;nd"
      region.rooms[54].name = "山道"
      region.rooms[54].zone = "终南山"
      region.rooms[54].id = 1151
      region.rooms[54].desc = "    此段山路是沿着峭壁而开凿出来的，特别崎岖难行。有时峭壁边必须面贴山璧，侧身而过。尤其当山凤吹来时，更需特别小心，不然一失足，就要掉进万丈深渊了。往东南是一块广大的空地。往北下通往后山脚，远远可以望见一个较大的湖。"
      region.rooms[54].exits = "northdown|southup"
      region.rooms[54].links = {}
        region.rooms[54].links.su = {}
          region.rooms[54].links.su.to = 1150
          region.rooms[54].links.su.con = ""
        region.rooms[54].links.nd = {}
          region.rooms[54].links.nd.to = 1152
          region.rooms[54].links.nd.con = ""
    region.rooms[55] = {}
      region.rooms[55].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu;nw;nd;nd"
      region.rooms[55].name = "树林"
      region.rooms[55].zone = "终南山"
      region.rooms[55].id = 1152
      region.rooms[55].desc = "    这位於终南山间的一大片树林，生的颇为茂密。走在其间，只听得脚下沙沙的落叶声，四周昏昏暗暗的，不时几道日光穿过浓密的枝头，投射而下。偶而远处几声兽吼声，更添了一份神密感。往北、南各有一条小径。"
      region.rooms[55].exits = "north|southup"
      region.rooms[55].links = {}
        region.rooms[55].links.su = {}
          region.rooms[55].links.su.to = 1151
          region.rooms[55].links.su.con = ""
        region.rooms[55].links.n = {}
          region.rooms[55].links.n.to = 1153
          region.rooms[55].links.n.con = ""
    region.rooms[56] = {}
      region.rooms[56].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu;nw;nd;nd;n"
      region.rooms[56].name = "树林"
      region.rooms[56].zone = "终南山"
      region.rooms[56].id = 1153
      region.rooms[56].desc = "    这位於终南山间的一大片树林，生的颇为茂密。走在其间，只听得脚下沙沙的落叶声，四周昏昏暗暗的，不时几道日光穿过浓密的枝头，投射而下。偶而远处几声兽吼声，更添了一份神密感。往北、南各有一条小径。"
      region.rooms[56].exits = "south|northdown"
      region.rooms[56].links = {}
        region.rooms[56].links.s = {}
          region.rooms[56].links.s.to = 1152
          region.rooms[56].links.s.con = ""
        region.rooms[56].links.nd = {}
          region.rooms[56].links.nd.to = 1154
          region.rooms[56].links.nd.con = ""
    region.rooms[57] = {}
      region.rooms[57].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu;nw;nd;nd;n;nd"
      region.rooms[57].name = "树林"
      region.rooms[57].zone = "终南山"
      region.rooms[57].id = 1154
      region.rooms[57].desc = "    这位於终南山间的一大片树林，生的颇为茂密。走在其间，只听得脚下沙沙的落叶声，四周昏昏暗暗的，不时几道日光穿过浓密的枝头，投射而下。偶而远处几声兽吼声，更添了一份神密感。往北、南各有一条小径。"
      region.rooms[57].exits = "northdown|southup"
      region.rooms[57].links = {}
        region.rooms[57].links.su = {}
          region.rooms[57].links.su.to = 1153
          region.rooms[57].links.su.con = ""
        region.rooms[57].links.nd = {}
          region.rooms[57].links.nd.to = 1155
          region.rooms[57].links.nd.con = ""
    region.rooms[58] = {}
      region.rooms[58].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu;nw;nd;nd;n;nd;nd"
      region.rooms[58].name = "山道"
      region.rooms[58].zone = "终南山"
      region.rooms[58].id = 1155
      region.rooms[58].desc = "    此段山路是通往后山脚。往南上是一大片树林。往北下可以望见一个较大的湖。"
      region.rooms[58].exits = "northdown|southup"
      region.rooms[58].links = {}
        region.rooms[58].links.su = {}
          region.rooms[58].links.su.to = 1154
          region.rooms[58].links.su.con = ""
        region.rooms[58].links.nd = {}
          region.rooms[58].links.nd.to = 1156
          region.rooms[58].links.nd.con = ""
    region.rooms[59] = {}
      region.rooms[59].path = "fly wg;|!hoteld:2:s|;w;w;w;ne;eu;se;eu;n;nu;nu;nu;wu;wu;nu;nu;n;w;nw;n;nu;nu;nu;wu;nw;nd;nd;n;nd;nd;nd"
      region.rooms[59].name = "太乙池"
      region.rooms[59].zone = "终南山"
      region.rooms[59].id = 1156
      region.rooms[59].desc = "    你眼前出现一个山间湖泊，这就是著名的太乙池(chi)，传为唐天宝年间地震造成，四周高峰环列，池面碧波荡漾，山光水影，风景十分优美。"
      region.rooms[59].exits = "southup"
      region.rooms[59].links = {}
        region.rooms[59].links.su = {}
          region.rooms[59].links.su.to = 1155
          region.rooms[59].links.su.con = ""
    region.rooms[60] = {}
      region.rooms[60].path = "fly wm;e;s;s;enter dong;say 天堂有路你不走呀;d;c;ne;ne;out;wu;wu"
      region.rooms[60].name = "山路"
      region.rooms[60].zone = "终南山|古墓"
      region.rooms[60].id = 1157
      region.rooms[60].links = {}
        region.rooms[60].links.ed = {}
          region.rooms[60].links.ed.to = 1148
          region.rooms[60].links.ed.con = ""
        region.rooms[60].links.sd = {}
          region.rooms[60].links.sd.to = 1158
          region.rooms[60].links.sd.con = ""
        region.rooms[60].links.nu = {}
          region.rooms[60].links.nu.to = 1159
          region.rooms[60].links.nu.con = ""
      region.rooms[60].exits = "eastdown|northup|southdown"
      region.rooms[60].desc = "    这条山路盘终南山主峰而上，山路贴着石璧凿出，只容一人可过，形势极为险峻。往远处望去。群山环绕，列於脚下，百里美景尽收眼底，顿时令人豪气陡声，想要长啸一声。往东下和北上各是一条山路。往南下是白马潭。"
    region.rooms[61] = {}
      region.rooms[61].path = "fly wm;e;s;s;enter dong;say 天堂有路你不走呀;d;c;ne;ne;out;wu;wu;sd"
      region.rooms[61].name = "白马潭"
      region.rooms[61].zone = "终南山|古墓"
      region.rooms[61].id = 1158
      region.rooms[61].links = {}
        region.rooms[61].links.nu = {}
          region.rooms[61].links.nu.to = 1157
          region.rooms[61].links.nu.con = ""
      region.rooms[61].exits = "northup"
      region.rooms[61].desc = "    这个潭为於终南山主峰一带，一条名叫库峪河的上游。潭边有一块比三间房子还要大的白石头，这石头中间低两头高，石头的前半截伸在水里，後半截留在岸上。由伸在水中的那半截石头下面还不时冒出一串串白沫，老远看去活似一匹腾空欲飞的烈马，因此当地人都叫此潭为白马潭。往北是一条崎岖的山路。"
    region.rooms[62] = {}
      region.rooms[62].path = "fly wm;e;s;s;out;enter dong;say 天堂有路你不走呀;d;c;ne;ne;out;wu;wu;nu"
      region.rooms[62].name = "山路"
      region.rooms[62].zone = "终南山|古墓"
      region.rooms[62].id = 1159
      region.rooms[62].links = {}
        region.rooms[62].links.sd = {}
          region.rooms[62].links.sd.to = 1157
          region.rooms[62].links.sd.con = ""
        region.rooms[62].links.wu = {}
          region.rooms[62].links.wu.to = 1160
          region.rooms[62].links.wu.con = ""
      region.rooms[62].exits = "westup|southdown"
      region.rooms[62].desc = "    这条山路盘终南山主峰而上，山路贴着石璧凿出，只容一人可过，形势极为险峻。往远处望去。群山环绕，列於脚下，百里美景尽收眼底，顿时令人豪气陡声，想要长啸一声。往南下和西上各是一条山路。"
    region.rooms[63] = {}
      region.rooms[63].path = "fly gm;n;n;n;n;n;ne;ne;nd;n;n;nu;nu;wd;nd;ed"
      region.rooms[63].name = "山路"
      region.rooms[63].zone = "终南山|古墓"
      region.rooms[63].id = 1160
      region.rooms[63].links = {}
        region.rooms[63].links.ed = {}
          region.rooms[63].links.ed.to = 1159
          region.rooms[63].links.ed.con = ""
        region.rooms[63].links.wu = {}
          region.rooms[63].links.wu.to = 1161
          region.rooms[63].links.wu.con = ""
      region.rooms[63].exits = "westup|eastdown"
      region.rooms[63].desc = "    这条山路盘终南山主峰而上，山路贴着石璧凿出，只容一人可过，形势极为险峻。往远处望去。群山环绕，列於脚下，百里美景尽收眼底，顿时令人豪气陡声，想要长啸一声。往东下和西上各是一条山路。"
    region.rooms[64] = {}
      region.rooms[64].path = "fly gm;n;n;n;n;n;ne;ne;nd;n;n;nu;nu;wd;nd"
      region.rooms[64].name = "山路"
      region.rooms[64].zone = "终南山|古墓"
      region.rooms[64].id = 1161
      region.rooms[64].links = {}
        region.rooms[64].links.ed = {}
          region.rooms[64].links.ed.to = 1160
          region.rooms[64].links.ed.con = ""
        region.rooms[64].links.su = {}
          region.rooms[64].links.su.to = 1162
          region.rooms[64].links.su.con = ""
      region.rooms[64].exits = "eastdown|southup"
      region.rooms[64].desc = "    这条山路盘终南山主峰而上，山路贴着石璧凿出，只容一人可过，形势极为险峻。往远处望去。群山环绕，列於脚下，百里美景尽收眼底，顿时令人豪气陡声，想要长啸一声。往东下和南上各是一条山路。"
    region.rooms[65] = {}
      region.rooms[65].path = "fly gm;n;n;n;n;n;ne;ne;nd;n;n;nu;nu;wd"
      region.rooms[65].name = "山路"
      region.rooms[65].zone = "终南山|古墓"
      region.rooms[65].id = 1162
      region.rooms[65].links = {}
        region.rooms[65].links.eu = {}
          region.rooms[65].links.eu.to = 1163
          region.rooms[65].links.eu.con = ""
        region.rooms[65].links.nd = {}
          region.rooms[65].links.nd.to = 1161
          region.rooms[65].links.nd.con = ""
      region.rooms[65].exits = "eastup|northdown"
      region.rooms[65].desc = "    这条山路盘终南山主峰而上，山路贴着石璧凿出，只容一人可过，形势极为险峻。往远处望去。群山环绕，列於脚下，百里美景尽收眼底，顿时令人豪气陡声，想要长啸一声。往北下是一条山路。往东上就是终南山主峰。"
    region.rooms[66] = {}
      region.rooms[66].path = "fly gm;n;n;n;n;n;ne;ne;nd;n;n;nu;nu"
      region.rooms[66].name = "终南山主峰"
      region.rooms[66].zone = "终南山|古墓"
      region.rooms[66].id = 1163
      region.rooms[66].links = {}
        region.rooms[66].links.wd = {}
          region.rooms[66].links.wd.to = 1162
          region.rooms[66].links.wd.con = ""
        region.rooms[66].links.sd = {}
          region.rooms[66].links.sd.to = 1164
          region.rooms[66].links.sd.con = ""
      region.rooms[66].exits = "southdown|westdown"
      region.rooms[66].desc = "    此时你已身在终南山主峰，视野更为广阔。往低望去，群山尽皆匍匐在脚下。重阳宫的翠绿琉瓦在山腰处，晶莹生辉。只见不少殿宇散布於山坳间，景色颇为美妙。一块巨石 (shi)立在一旁，似乎刻了什麽东西。往西和南各是一条山路。"
    region.rooms[67] = {}
      region.rooms[67].path = "fly gm;n;n;n;n;n;ne;ne;nd;n;n;nu"
      region.rooms[67].name = "山路"
      region.rooms[67].zone = "终南山|古墓"
      region.rooms[67].id = 1164
      region.rooms[67].links = {}
        region.rooms[67].links.nu = {}
          region.rooms[67].links.nu.to = 1163
          region.rooms[67].links.nu.con = ""
        region.rooms[67].links.sd = {}
          region.rooms[67].links.sd.to = 1165
          region.rooms[67].links.sd.con = ""
      region.rooms[67].exits = "northup|southdown"
      region.rooms[67].desc = "    这条山路盘终南山主峰而上，山路贴着石璧凿出，只容一人可过，形势极为险峻。往远处望去。群山环绕，列於脚下，百里美景尽收眼底，顿时令人豪气陡声，想要长啸一声。往南下是一片空地。往北上就是终南山主峰。"
    region.rooms[68] = {}
      region.rooms[68].path = "fly gm;n;n;n;n;n;ne;ne;nd;n;n"
      region.rooms[68].name = "空地"
      region.rooms[68].zone = "终南山|古墓"
      region.rooms[68].id = 1165
      region.rooms[68].links = {}
        region.rooms[68].links.nu = {}
          region.rooms[68].links.nu.to = 1164
          region.rooms[68].links.nu.con = ""
        region.rooms[68].links.s = {}
          region.rooms[68].links.s.to = 1166
          region.rooms[68].links.s.con = ""
      region.rooms[68].exits = "south|northup|west"
      region.rooms[68].desc = "    这是终南山山腰处的一块空地，地势平坦。北面一条小路直攀山璧而上，通往是终南山主峰。南边和西边一大片密林，只闻阵阵琴声自林中传出。往北是一条山路。往南和西各有一条小径。"
  region.center = 884
return region