local region = {}
  region.cmd = "fly cs"
  region.name = "嵩山"
  region.id = "cs"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly bj;e;e;e;e;se;se;s;s;s"
      region.rooms[1].name = "大驿道"
      region.rooms[1].zone = "北京|嵩山"
      region.rooms[1].id = 1076
      region.rooms[1].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。马上的人个个身着劲装，衣甲鲜明，有的还随身佩带着刀剑。看来都是些些习武的江湖人。道路两旁是整整齐齐的杨树林。"
      region.rooms[1].exits = "south|north"
      region.rooms[1].links = {}
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 1077
          region.rooms[1].links.s.con = ""
        region.rooms[1].links.n = {}
          region.rooms[1].links.n.to = 1074
          region.rooms[1].links.n.con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "fly bj;e;e;e;e;se;se;s;s;s;s"
      region.rooms[2].name = "小道"
      region.rooms[2].zone = "北京|少林寺|嵩山"
      region.rooms[2].id = 1077
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 1078
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.s = {}
          region.rooms[2].links.s.to = 1079
          region.rooms[2].links.s.con = ""
        region.rooms[2].links.n = {}
          region.rooms[2].links.n.to = 1076
          region.rooms[2].links.n.con = ""
      region.rooms[2].exits = "south|north|east"
      region.rooms[2].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的、行商的、赶着大车的马夫、上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。东边就是大海之滨了。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly bj;e;e;e;e;se;se;s;s;s;s;e"
      region.rooms[3].name = "塘沽口"
      region.rooms[3].zone = "北京|少林寺|嵩山"
      region.rooms[3].id = 1078
      region.rooms[3].links = {}
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 1077
          region.rooms[3].links.w.con = ""
      region.rooms[3].exits = "west"
      region.rooms[3].desc = "    这里就是大海之滨，浪花拍打着礁石，发出阵阵响声，海面上一群群海鸥『欧欧..』地叫着，不时有鱼儿跃出海面，溅起层层的浪花。边上有艘大船(chuan)，船上坐着几个渔夫打扮的人，乘船可渡过大海到达海的另一端。西面过天津城就是北京了，东面是一望无际的大海。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s"
      region.rooms[4].name = "汝州城"
      region.rooms[4].zone = "北京|少林寺|嵩山"
      region.rooms[4].id = 1079
      region.rooms[4].links = {}
        region.rooms[4].links.s = {}
          region.rooms[4].links.s.to = 1081
          region.rooms[4].links.s.con = ""
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 1080
          region.rooms[4].links.w.con = ""
        region.rooms[4].links.n = {}
          region.rooms[4].links.n.to = 1077
          region.rooms[4].links.n.con = ""
      region.rooms[4].exits = "south|north|west"
      region.rooms[4].desc = "    汝州城是本府的大城，立来是兵家必争之地。故州治在此驻扎重兵，盘查南来北往的行人，并负责翦灭附近山上的草寇。城内一队队官兵来来去去，一派森严气象。再折向西，就是五岳之一的嵩山。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd;s;s;s"
      region.rooms[5].name = "太室阙"
      region.rooms[5].zone = "北京|嵩山|少林寺"
      region.rooms[5].id = 1080
      region.rooms[5].desc = "    嵩山古称方外，又称崇山，为五岳中的中岳，由太室少室二山沿绵而成。汉武帝时称 \"嵩高\" ，取自诗经 \"嵩岳维高，峻极于天\" ，道教以之为第六小洞天。阕高丈余，南面刻 \"中岳太室阳城\" 六字，篆文古朴，苍劲有力。向西就是去少室山少林寺的路。向北一里许便是中岳庙了。"
      region.rooms[5].exits = "east|north|west"
      region.rooms[5].links = {}
        region.rooms[5].links.e = {}
          region.rooms[5].links.e.to = 1079
          region.rooms[5].links.e.con = ""
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 1408
          region.rooms[5].links.w.con = ""
        region.rooms[5].links.n = {}
          region.rooms[5].links.n.to = 1385
          region.rooms[5].links.n.con = ""
    region.rooms[6] = {}
      region.rooms[6].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s"
      region.rooms[6].name = "大驿道"
      region.rooms[6].zone = "北京|少林寺|嵩山"
      region.rooms[6].id = 1081
      region.rooms[6].links = {}
        region.rooms[6].links.s = {}
          region.rooms[6].links.s.to = 1082
          region.rooms[6].links.s.con = ""
        region.rooms[6].links.n = {}
          region.rooms[6].links.n.to = 1079
          region.rooms[6].links.n.con = ""
      region.rooms[6].exits = "south|north"
      region.rooms[6].desc = "    你走在一条尘土飞扬的大驿道上。四周人来人往。挑担子的行商，赶着大车的马夫，上京赶考的书生，熙熙攘攘，非常热闹。不时还有两三骑快马从身边飞驰而过，扬起一路尘埃。道路两旁是整整齐齐的杨树林。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly bj;e;e;e;e;se;se;s;s;s;s;s;s;s"
      region.rooms[7].name = "南阳城"
      region.rooms[7].zone = "北京|少林寺|嵩山"
      region.rooms[7].id = 1082
      region.rooms[7].links = {}
        region.rooms[7].links.ne = {}
          region.rooms[7].links.ne.to = 1087
          region.rooms[7].links.ne.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 1086
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 1083
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.w = {}
          region.rooms[7].links.w.to = 1084
          region.rooms[7].links.w.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 1081
          region.rooms[7].links.n.con = ""
      region.rooms[7].exits = "south|east|north|northeast|west"
      region.rooms[7].desc = "    这里便是当年诸葛先生的故居。南阳城不大，因为地出要冲，南来北往的客人特别多，所以也五脏俱全，酒楼，客栈，马店，满城子都是。本地人口甚少，到处都是行色匆匆的江湖客人。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd;s;s"
      region.rooms[8].name = "天中阁"
      region.rooms[8].zone = "嵩山|少林寺"
      region.rooms[8].id = 1385
      region.rooms[8].desc = "    天中阁是中岳庙的大门，原称黄中阁。庙内有古柏三百余株，金石碑碣百余座。庙前石翁仲，雕制古朴。南面是嵩山的出口太室阙。"
      region.rooms[8].exits = "south|north"
      region.rooms[8].links = {}
        region.rooms[8].links.s = {}
          region.rooms[8].links.s.to = 1080
          region.rooms[8].links.s.con = ""
        region.rooms[8].links.n = {}
          region.rooms[8].links.n.to = 1386
          region.rooms[8].links.n.con = ""
    region.rooms[9] = {}
      region.rooms[9].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd;s"
      region.rooms[9].name = "崇圣门"
      region.rooms[9].zone = "嵩山"
      region.rooms[9].id = 1386
      region.rooms[9].desc = "    崇圣门前古神库有四座镇库铁人，高达丈许，振臂握拳，怒目挺胸，身姿雄健。向北就是中岳庙最大的殿宇中岳大殿了。"
      region.rooms[9].exits = "south|north"
      region.rooms[9].links = {}
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 1385
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 1387
          region.rooms[9].links.n.con = ""
    region.rooms[10] = {}
      region.rooms[10].path = "fly cs;sd;sd;sd;sd;sd;d;sw;sd"
      region.rooms[10].name = "中岳大殿"
      region.rooms[10].zone = "嵩山"
      region.rooms[10].id = 1387
      region.rooms[10].desc = "    大殿面阔九间，进深五间，重檐庑殿式屋顶，座落在七尺高的台基上，气势雄伟。大殿中供奉岳神天中王。"
      region.rooms[10].exits = "south|northup"
      region.rooms[10].links = {}
        region.rooms[10].links.s = {}
          region.rooms[10].links.s.to = 1386
          region.rooms[10].links.s.con = ""
        region.rooms[10].links.nu = {}
          region.rooms[10].links.nu.to = 1388
          region.rooms[10].links.nu.con = ""
    region.rooms[11] = {}
      region.rooms[11].path = "fly cs;sd;sd;sd;sd;sd;d;sw"
      region.rooms[11].name = "山道"
      region.rooms[11].zone = "嵩山"
      region.rooms[11].id = 1388
      region.rooms[11].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。左边通往启母石，右手是芦岩瀑布。"
      region.rooms[11].exits = "northwest|southdown|northeast"
      region.rooms[11].links = {}
        region.rooms[11].links.ne = {}
          region.rooms[11].links.ne.to = 1407
          region.rooms[11].links.ne.con = ""
        region.rooms[11].links.nw = {}
          region.rooms[11].links.nw.to = 1389
          region.rooms[11].links.nw.con = ""
        region.rooms[11].links.sd = {}
          region.rooms[11].links.sd.to = 1387
          region.rooms[11].links.sd.con = ""
    region.rooms[12] = {}
      region.rooms[12].path = "fly cs;sd;sd;sd;sd;sd;d;sw;nw"
      region.rooms[12].name = "启母石"
      region.rooms[12].zone = "嵩山"
      region.rooms[12].id = 1389
      region.rooms[12].desc = "    这里有一壁三丈巨石当道。相传大禹治水时要打通辕擐山，大禹化熊扒挖不止。禹妻涂山氏送饭时不慎撞破，失惊而逃，到此化石。其时涂山已有身孕，大禹追及唤子，巨石北裂一口，夏启呱呱落地。巨石因此唤作启母石。"
      region.rooms[12].exits = "northup|southeast|west"
      region.rooms[12].links = {}
        region.rooms[12].links.nu = {}
          region.rooms[12].links.nu.to = 1391
          region.rooms[12].links.nu.con = ""
        region.rooms[12].links.w = {}
          region.rooms[12].links.w.to = 1390
          region.rooms[12].links.w.con = ""
        region.rooms[12].links.se = {}
          region.rooms[12].links.se.to = 1388
          region.rooms[12].links.se.con = ""
    region.rooms[13] = {}
      region.rooms[13].path = "fly cs;sd;sd;sd;sd;sd;d;sw;nw;w"
      region.rooms[13].name = "启母阙"
      region.rooms[13].zone = "嵩山"
      region.rooms[13].id = 1390
      region.rooms[13].desc = "    启母阙在嵩山南麓万岁峰下，是汉代启母庙前的神道阙，和太室阙同为中岳汉三阙之一。"
      region.rooms[13].exits = "east"
      region.rooms[13].links = {}
        region.rooms[13].links.e = {}
          region.rooms[13].links.e.to = 1389
          region.rooms[13].links.e.con = ""
    region.rooms[14] = {}
      region.rooms[14].path = "fly cs;sd;sd;sd;sd;sd;d;sw;nw;nu"
      region.rooms[14].name = "山道"
      region.rooms[14].zone = "嵩山"
      region.rooms[14].id = 1391
      region.rooms[14].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。"
      region.rooms[14].exits = "northup|southdown"
      region.rooms[14].links = {}
        region.rooms[14].links.sd = {}
          region.rooms[14].links.sd.to = 1389
          region.rooms[14].links.sd.con = ""
        region.rooms[14].links.nu = {}
          region.rooms[14].links.nu.to = 1392
          region.rooms[14].links.nu.con = ""
    region.rooms[15] = {}
      region.rooms[15].path = "fly cs;sd;sd;sd;sd;sw;sd;se;sd;se"
      region.rooms[15].name = "嵩阳书院"
      region.rooms[15].zone = "嵩山"
      region.rooms[15].id = 1392
      region.rooms[15].desc = "    这里原是嵩阳寺。现在文化昌明，就改成了嵩阳书院，和睢阳书院，岳麓书院，白鹿书院合称天下 \"四大书院\" 。北宋程颢程颐曾在此讲学。院内有古柏三株，汉武帝巡游至此，册封为大将军，二将军，三将军。"
      region.rooms[15].exits = "northwest|southdown"
      region.rooms[15].links = {}
        region.rooms[15].links.sd = {}
          region.rooms[15].links.sd.to = 1391
          region.rooms[15].links.sd.con = ""
        region.rooms[15].links.nw = {}
          region.rooms[15].links.nw.to = 1393
          region.rooms[15].links.nw.con = ""
    region.rooms[16] = {}
      region.rooms[16].path = "fly cs;sd;sd;sd;sd;sw;sd;se;sd"
      region.rooms[16].name = "山道"
      region.rooms[16].zone = "嵩山"
      region.rooms[16].id = 1393
      region.rooms[16].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。"
      region.rooms[16].exits = "southeast|northup"
      region.rooms[16].links = {}
        region.rooms[16].links.nu = {}
          region.rooms[16].links.nu.to = 1394
          region.rooms[16].links.nu.con = ""
        region.rooms[16].links.se = {}
          region.rooms[16].links.se.to = 1392
          region.rooms[16].links.se.con = ""
    region.rooms[17] = {}
      region.rooms[17].path = "fly cs;sd;sd;sd;sd;sw;sd;se"
      region.rooms[17].name = "嵩岳寺"
      region.rooms[17].zone = "嵩山"
      region.rooms[17].id = 1394
      region.rooms[17].desc = "    这里原是北魏离宫。孝明帝舍为佛院，至隋方有今名，寺围阔大，僧舍连云。院内风动旌扬，松摇竹乱，别有一般清静。"
      region.rooms[17].exits = "northwest|southdown|west"
      region.rooms[17].links = {}
        region.rooms[17].links.sd = {}
          region.rooms[17].links.sd.to = 1393
          region.rooms[17].links.sd.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 1395
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.nw = {}
          region.rooms[17].links.nw.to = 1396
          region.rooms[17].links.nw.con = ""
    region.rooms[18] = {}
      region.rooms[18].path = "fly cs;sd;sd;sd;sd;sw;sd;se;w"
      region.rooms[18].name = "嵩岳寺塔"
      region.rooms[18].zone = "嵩山"
      region.rooms[18].id = 1395
      region.rooms[18].desc = "    嵩岳寺塔为密檐式砖塔，高达十余丈，外廓十二面，内室八方四门，十五层密檐塔刹向上收紧，优美绝伦。"
      region.rooms[18].exits = "east"
      region.rooms[18].links = {}
        region.rooms[18].links.e = {}
          region.rooms[18].links.e.to = 1394
          region.rooms[18].links.e.con = ""
    region.rooms[19] = {}
      region.rooms[19].path = "fly cs;sd;sd;sd;sd;sw;sd"
      region.rooms[19].name = "山道"
      region.rooms[19].zone = "嵩山"
      region.rooms[19].id = 1396
      region.rooms[19].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。"
      region.rooms[19].exits = "southeast|northup"
      region.rooms[19].links = {}
        region.rooms[19].links.nu = {}
          region.rooms[19].links.nu.to = 1397
          region.rooms[19].links.nu.con = ""
        region.rooms[19].links.se = {}
          region.rooms[19].links.se.to = 1394
          region.rooms[19].links.se.con = ""
    region.rooms[20] = {}
      region.rooms[20].path = "fly cs;sd;sd;sd;sd;sw"
      region.rooms[20].name = "法王寺"
      region.rooms[20].zone = "嵩山"
      region.rooms[20].id = 1397
      region.rooms[20].desc = "    法王寺在嵩山玉柱峰下，隐约于茂密松林中，此地素有 \"嵩山第一胜地\" 之称。"
      region.rooms[20].exits = "northup|southdown|northeast|west"
      region.rooms[20].links = {}
        region.rooms[20].links.nu = {}
          region.rooms[20].links.nu.to = 1399
          region.rooms[20].links.nu.con = ""
        region.rooms[20].links.w = {}
          region.rooms[20].links.w.to = 1398
          region.rooms[20].links.w.con = ""
        region.rooms[20].links.sd = {}
          region.rooms[20].links.sd.to = 1396
          region.rooms[20].links.sd.con = ""
        region.rooms[20].links.ne = {}
          region.rooms[20].links.ne.to = 1400
          region.rooms[20].links.ne.con = ""
    region.rooms[21] = {}
      region.rooms[21].path = "fly cs;sd;sd;sd;sd;sw;w"
      region.rooms[21].name = "月台"
      region.rooms[21].zone = "嵩山"
      region.rooms[21].id = 1398
      region.rooms[21].desc = "    这里是法王寺的月台。从月台东望，太室山峦高耸入云，寺东有双峰插云，中间阙如。因名 \"嵩门\" 。中秋佳节，明月自峰中升起，正当嵩门之中，银光洒满山谷，这就是登封八景之一的 \"嵩门待月\" 。"
      region.rooms[21].exits = "east"
      region.rooms[21].links = {}
        region.rooms[21].links.e = {}
          region.rooms[21].links.e.to = 1397
          region.rooms[21].links.e.con = ""
    region.rooms[22] = {}
      region.rooms[22].path = "fly cs;sd;sd;sd;sd;sw;nu"
      region.rooms[22].name = "塔院"
      region.rooms[22].zone = "嵩山"
      region.rooms[22].id = 1399
      region.rooms[22].desc = "    法王寺北山坡上，是法王寺塔院。院内有十五层密檐方塔，高近二十丈，造型优美。院内其它三座单檐墓塔，亦玲珑秀丽。"
      region.rooms[22].exits = "southdown"
      region.rooms[22].links = {}
        region.rooms[22].links.sd = {}
          region.rooms[22].links.sd.to = 1397
          region.rooms[22].links.sd.con = ""
    region.rooms[23] = {}
      region.rooms[23].path = "fly cs;sd;sd;sd;sd"
      region.rooms[23].name = "山道"
      region.rooms[23].zone = "嵩山"
      region.rooms[23].id = 1400
      region.rooms[23].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。"
      region.rooms[23].exits = "northup|southdown|southwest"
      region.rooms[23].links = {}
        region.rooms[23].links.nu = {}
          region.rooms[23].links.nu.to = 1401
          region.rooms[23].links.nu.con = ""
        region.rooms[23].links.sw = {}
          region.rooms[23].links.sw.to = 1397
          region.rooms[23].links.sw.con = ""
        region.rooms[23].links.sd = {}
          region.rooms[23].links.sd.to = 1406
          region.rooms[23].links.sd.con = ""
    region.rooms[24] = {}
      region.rooms[24].path = "fly cs;sd;sd;sd"
      region.rooms[24].name = "朝天门"
      region.rooms[24].zone = "嵩山"
      region.rooms[24].id = 1401
      region.rooms[24].desc = "    陡见双峰中断，天然出现一个门户，疾风从断绝处吹出，云雾随风扑面而至，这里就是朝天门了。"
      region.rooms[24].exits = "northup|southdown"
      region.rooms[24].links = {}
        region.rooms[24].links.sd = {}
          region.rooms[24].links.sd.to = 1400
          region.rooms[24].links.sd.con = ""
        region.rooms[24].links.nu = {}
          region.rooms[24].links.nu.to = 1402
          region.rooms[24].links.nu.con = ""
    region.rooms[25] = {}
      region.rooms[25].path = "fly cs;sd;sd"
      region.rooms[25].name = "山道"
      region.rooms[25].zone = "嵩山"
      region.rooms[25].id = 1402
      region.rooms[25].desc = "    你走在嵩山山道，青松翠柏，山风岚雾，时来飘荡。远望山下犬吠鸡啼，顿起仙凡之感。上面就是嵩山峻极禅院。"
      region.rooms[25].exits = "northup|southdown"
      region.rooms[25].links = {}
        region.rooms[25].links.sd = {}
          region.rooms[25].links.sd.to = 1401
          region.rooms[25].links.sd.con = ""
        region.rooms[25].links.nu = {}
          region.rooms[25].links.nu.to = 1403
          region.rooms[25].links.nu.con = ""
    region.rooms[26] = {}
      region.rooms[26].path = "fly cs;sd"
      region.rooms[26].name = "峻极禅院山门"
      region.rooms[26].zone = "嵩山"
      region.rooms[26].id = 1403
      region.rooms[26].desc = "    嵩山绝顶，古称 \"峻极\" 。这里是本是佛教大寺，但百年来却已成为嵩山派掌门人的住所。西上可以到达封禅台。"
      region.rooms[26].exits = "westup|northup|southdown"
      region.rooms[26].links = {}
        region.rooms[26].links.nu = {}
          region.rooms[26].links.nu.to = 1404
          region.rooms[26].links.nu.con = ""
        region.rooms[26].links.sd = {}
          region.rooms[26].links.sd.to = 1402
          region.rooms[26].links.sd.con = ""
        region.rooms[26].links.wu = {}
          region.rooms[26].links.wu.to = 1405
          region.rooms[26].links.wu.con = ""
    region.rooms[27] = {}
      region.rooms[27].path = "fly cs"
      region.rooms[27].name = "峻极禅院"
      region.rooms[27].zone = "嵩山"
      region.rooms[27].id = 1404
      region.rooms[27].desc = "    峻极禅院处嵩山绝顶，院中古柏森森，殿上并无佛像。院宇辽阔，可容千人。"
      region.rooms[27].exits = "southdown"
      region.rooms[27].links = {}
        region.rooms[27].links.sd = {}
          region.rooms[27].links.sd.to = 1403
          region.rooms[27].links.sd.con = ""
    region.rooms[28] = {}
      region.rooms[28].path = "fly cs;sd;wu"
      region.rooms[28].name = "封禅台"
      region.rooms[28].zone = "嵩山"
      region.rooms[28].id = 1405
      region.rooms[28].desc = "    峻极封禅台由大麻石所建，每块大石都凿得极是平整。地势甚为宽阔。这里独立天心，万峰在下，云开日朗，纤翳不生。极目北望，可遥见成皋玉门，黄河有如一线，西向隐隐见到洛阳伊阙，东南都是叠叠重山。"
      region.rooms[28].exits = "eastdown"
      region.rooms[28].links = {}
        region.rooms[28].links.ed = {}
          region.rooms[28].links.ed.to = 1403
          region.rooms[28].links.ed.con = ""
    region.rooms[29] = {}
      region.rooms[29].path = "fly cs;sd;sd;sd;sd;sd"
      region.rooms[29].name = "铁梁峡"
      region.rooms[29].zone = "嵩山"
      region.rooms[29].id = 1406
      region.rooms[29].desc = "    由此上山，山路越发险竣。铁梁峡右侧尽是怪石，而左边则为万仞深谷，渺不见底。隔着峡谷，青冈峰环抱青冈坪，向上是主峰的山路。"
      region.rooms[29].exits = "northup|down"
      region.rooms[29].links = {}
        region.rooms[29].links.nu = {}
          region.rooms[29].links.nu.to = 1400
          region.rooms[29].links.nu.con = ""
        region.rooms[29].links.d = {}
          region.rooms[29].links.d.to = 1407
          region.rooms[29].links.d.con = ""
    region.rooms[30] = {}
      region.rooms[30].path = "fly cs;sd;sd;sd;sd;sd;d"
      region.rooms[30].name = "芦岩瀑布"
      region.rooms[30].zone = "嵩山"
      region.rooms[30].id = 1407
      region.rooms[30].desc = "    忽听水声如雷，峭壁上两条玉龙直挂下来，双瀑并泄，屈曲回旋，飞跃奔逸，水花映日，淡淡冕生。    瀑布一侧有一小小芦岩寺，瀑布斜过就是胜观峰。瀑布之侧有路可上。"
      region.rooms[30].exits = "up|southwest"
      region.rooms[30].links = {}
        region.rooms[30].links.u = {}
          region.rooms[30].links.u.to = 1406
          region.rooms[30].links.u.con = ""
        region.rooms[30].links.sw = {}
          region.rooms[30].links.sw.to = 1388
          region.rooms[30].links.sw.con = ""
    region.rooms[31] = {}
      region.rooms[31].path = "fly sl;s;sd;sd;sd;wd;w;sd;sd;sd;ed;sd;sd"
      region.rooms[31].name = "石阶"
      region.rooms[31].zone = "少林寺|嵩山"
      region.rooms[31].id = 1408
      region.rooms[31].links = {}
        region.rooms[31].links.e = {}
          region.rooms[31].links.e.to = 1080
          region.rooms[31].links.e.con = ""
        region.rooms[31].links.w = {}
          region.rooms[31].links.w.to = 1409
          region.rooms[31].links.w.con = ""
        region.rooms[31].links.nu = {}
          region.rooms[31].links.nu.to = 1416
          region.rooms[31].links.nu.con = ""
      region.rooms[31].exits = "east|northup|west"
      region.rooms[31].desc = "    这里是嵩山南麓的少室山山脚。一条长长的石阶如同巨龙般蜿蜒而上，直没云端。嵩山群峰壁立，翠色满山，令人俯仰间顿生渺小之意。边上有几个叫卖的小贩和挑夫，似乎在嚷嚷着争吵些什么。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly sl;s;sd;sd;sd;wd;w;sd;sd;sd;ed;sd;sd;w"
      region.rooms[32].name = "山坡"
      region.rooms[32].zone = "少林寺|嵩山"
      region.rooms[32].id = 1409
      region.rooms[32].links = {}
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 1408
          region.rooms[32].links.e.con = ""
        region.rooms[32].links.nu = {}
          region.rooms[32].links.nu.to = 1410
          region.rooms[32].links.nu.con = ""
      region.rooms[32].exits = "east|northup"
      region.rooms[32].desc = "    这里是少室山之阳的一座山坡山坡上长满了艳红色的不知名的野花采密的蜂蝶们簇成一团团忙碌着。不时有几只好奇的小密蜂飞近来似乎对你这个不速之客感到极大的惊奇。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly sl;s;sd;sd;sd;wd;w;sd;sd;sd;ed;sd;sd;w;nu"
      region.rooms[33].name = "田埂边"
      region.rooms[33].zone = "少林寺|嵩山"
      region.rooms[33].id = 1410
      region.rooms[33].links = {}
        region.rooms[33].links.sd = {}
          region.rooms[33].links.sd.to = 1409
          region.rooms[33].links.sd.con = ""
        region.rooms[33].links.w = {}
          region.rooms[33].links.w.to = 1411
          region.rooms[33].links.w.con = ""
      region.rooms[33].exits = "southdown|west"
      region.rooms[33].desc = "    转过山坡只见几棵果实累累的大枣树孤零零地栽在田埂边，上面挂满了红熟的枣子，使人忍不住想摘下几颗尝尝。田里种着半熟的青稞麦。西首有三间简陋的土屋。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly sl;s;sd;sd;sd;wd;w;sd;sd;sd;ed;sd"
      region.rooms[34].name = "石阶"
      region.rooms[34].zone = "少林寺|嵩山"
      region.rooms[34].id = 1416
      region.rooms[34].links = {}
        region.rooms[34].links.sd = {}
          region.rooms[34].links.sd.to = 1408
          region.rooms[34].links.sd.con = ""
        region.rooms[34].links.nu = {}
          region.rooms[34].links.nu.to = 1417
          region.rooms[34].links.nu.con = ""
      region.rooms[34].exits = "northup|southdown"
      region.rooms[34].desc = "    长长的石阶往上依然看不到尽头。身边的山壁受着长年风雨的浸润，长出了薄薄的青苔。上面依稀有些刻凿的痕迹。有一行字特别清晰：“金刚伏邪魔，宝塔镇群妖”"
  region.center = 1404
return region