local region = {}
  region.cmd = "fly hz"
  region.name = "杭州"
  region.id = "hz"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "fly hz;|!hoteld::w|;n;n;n;n"
      region.rooms[1].name = "青石大道"
      region.rooms[1].zone = "嘉兴|杭州"
      region.rooms[1].id = 195
      region.rooms[1].links = {}
        region.rooms[1].links.ne = {}
          region.rooms[1].links.ne.to = 194
          region.rooms[1].links.ne.con = ""
        region.rooms[1].links.sw = {}
          region.rooms[1].links.sw.to = 281
          region.rooms[1].links.sw.con = ""
        region.rooms[1].links.w = {}
          region.rooms[1].links.w.to = 211
          region.rooms[1].links.w.con = ""
        region.rooms[1].links.s = {}
          region.rooms[1].links.s.to = 212
          region.rooms[1].links.s.con = ""
      region.rooms[1].exits = "south|northeast|west|southwest"
      region.rooms[1].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道延伸向西边。断桥在大道的西南边。南边则是另一条大道。"
    region.rooms[2] = {}
      region.rooms[2].path = "fly hz;|!hoteld::w|;n;n;n;n;w"
      region.rooms[2].name = "青石大道"
      region.rooms[2].zone = "杭州"
      region.rooms[2].id = 211
      region.rooms[2].links = {}
        region.rooms[2].links.e = {}
          region.rooms[2].links.e.to = 195
          region.rooms[2].links.e.con = ""
        region.rooms[2].links.sw = {}
          region.rooms[2].links.sw.to = 272
          region.rooms[2].links.sw.con = ""
        region.rooms[2].links.nu = {}
          region.rooms[2].links.nu.to = 293
          region.rooms[2].links.nu.con = ""
      region.rooms[2].exits = "east|northup|southwest"
      region.rooms[2].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道延伸向东边和西南边。朝北走便是上宝石山。"
    region.rooms[3] = {}
      region.rooms[3].path = "fly hz;|!hoteld::w|;n;n;n"
      region.rooms[3].name = "青石大道"
      region.rooms[3].zone = "杭州"
      region.rooms[3].id = 212
      region.rooms[3].links = {}
        region.rooms[3].links.e = {}
          region.rooms[3].links.e.to = 213
          region.rooms[3].links.e.con = ""
        region.rooms[3].links.s = {}
          region.rooms[3].links.s.to = 216
          region.rooms[3].links.s.con = ""
        region.rooms[3].links.w = {}
          region.rooms[3].links.w.to = 215
          region.rooms[3].links.w.con = ""
        region.rooms[3].links.n = {}
          region.rooms[3].links.n.to = 195
          region.rooms[3].links.n.con = ""
      region.rooms[3].exits = "south|east|north|west"
      region.rooms[3].desc = "    沿湖大道旁店铺林立，长街故朴，屋舍鳞次栉比，道上人来车往，一片太平热闹景象。街的东边是一座酒楼。"
    region.rooms[4] = {}
      region.rooms[4].path = "fly hz;|!hoteld::w|;n;n;n;e"
      region.rooms[4].name = "楼外楼"
      region.rooms[4].zone = "杭州"
      region.rooms[4].id = 213
      region.rooms[4].links = {}
        region.rooms[4].links.w = {}
          region.rooms[4].links.w.to = 212
          region.rooms[4].links.w.con = ""
        region.rooms[4].links.u = {}
          region.rooms[4].links.u.to = 214
          region.rooms[4].links.u.con = ""
      region.rooms[4].exits = "up|west"
      region.rooms[4].desc = "    提起“楼外楼”方圆百里无人不知。这里各式名菜是杭州一绝。来游湖的人们都一定会来这里尝尝。整个大堂闹哄哄的挤满了各式人等。店小儿跑来跑去，忙着招呼客人。墙上挂着价格牌子(paizi)。"
    region.rooms[5] = {}
      region.rooms[5].path = "fly hz;|!hoteld::w|;n;n;n;e;u"
      region.rooms[5].name = "相约轩"
      region.rooms[5].zone = "杭州"
      region.rooms[5].id = 214
      region.rooms[5].links = {}
        region.rooms[5].links.d = {}
          region.rooms[5].links.d.to = 213
          region.rooms[5].links.d.con = ""
      region.rooms[5].exits = "down"
      region.rooms[5].desc = "    楼外楼的相约轩，四面通窗。湖风拂面，淡淡生暖。远望苏堤一线，映波，锁澜，望山，压堤，东浦，跨虹六桥断续连沿，烟柳笼纱，流莺娇啼。近处白堤横亘湖上，堤上杨柳覆地，芳草寒茵如一段碧绸飘然湖面。室内一张精巧的小桌。桌上一纸精致的菜单(menu)。"
    region.rooms[6] = {}
      region.rooms[6].path = "fly hz;|!hoteld::w|;n;n;n;w"
      region.rooms[6].name = "红娘庄"
      region.rooms[6].zone = "杭州"
      region.rooms[6].id = 215
      region.rooms[6].links = {}
        region.rooms[6].links.e = {}
          region.rooms[6].links.e.to = 212
          region.rooms[6].links.e.con = ""
      region.rooms[6].exits = "east"
      region.rooms[6].desc = "    你现在正站在风光秀丽的西子湖畔的红娘庄里，临水凭窗，隔着碧绿的湖面，就是断桥了。红娘庄并不大，但这里却主天下之悲欢离合，成就所有天下有情人。"
    region.rooms[7] = {}
      region.rooms[7].path = "fly hz;|!hoteld::w|;n;n"
      region.rooms[7].name = "青石大道"
      region.rooms[7].zone = "杭州"
      region.rooms[7].id = 216
      region.rooms[7].links = {}
        region.rooms[7].links.e = {}
          region.rooms[7].links.e.to = 217
          region.rooms[7].links.e.con = ""
        region.rooms[7].links.s = {}
          region.rooms[7].links.s.to = 218
          region.rooms[7].links.s.con = ""
        region.rooms[7].links.n = {}
          region.rooms[7].links.n.to = 212
          region.rooms[7].links.n.con = ""
      region.rooms[7].exits = "south|east|north"
      region.rooms[7].desc = "    沿湖大道旁店铺林立，长街故朴，屋舍鳞次栉比，道上人来车往，一片太平热闹景象。街东边的一家店铺里传来叮叮当当的打铁声。"
    region.rooms[8] = {}
      region.rooms[8].path = "fly hz;|!hoteld::w|;n;n;e"
      region.rooms[8].name = "铁匠铺"
      region.rooms[8].zone = "杭州"
      region.rooms[8].id = 217
      region.rooms[8].links = {}
        region.rooms[8].links.w = {}
          region.rooms[8].links.w.to = 216
          region.rooms[8].links.w.con = ""
      region.rooms[8].exits = "west"
      region.rooms[8].desc = "    这是一家不小的打铁铺，店里摆了几座火炉，一位铁匠正在火炉旁满头大汗地打造东西。一位老者坐在边上。火炉边放着不少打好了的铁器。"
    region.rooms[9] = {}
      region.rooms[9].path = "fly hz;|!hoteld::w|;n"
      region.rooms[9].name = "青石大道"
      region.rooms[9].zone = "杭州"
      region.rooms[9].id = 218
      region.rooms[9].links = {}
        region.rooms[9].links.e = {}
          region.rooms[9].links.e.to = 219
          region.rooms[9].links.e.con = ""
        region.rooms[9].links.s = {}
          region.rooms[9].links.s.to = 221
          region.rooms[9].links.s.con = ""
        region.rooms[9].links.w = {}
          region.rooms[9].links.w.to = 220
          region.rooms[9].links.w.con = ""
        region.rooms[9].links.n = {}
          region.rooms[9].links.n.to = 216
          region.rooms[9].links.n.con = ""
      region.rooms[9].exits = "south|east|north|west"
      region.rooms[9].desc = "    沿湖大道旁店铺林立，长街故朴，屋舍鳞次栉比，道上人来车往，一片太平热闹景象。街东边是一古朴书院，书院里不时传来朗朗的笑声。"
    region.rooms[10] = {}
      region.rooms[10].path = "fly hz;|!hoteld::w|;n;e"
      region.rooms[10].name = "凤池书院"
      region.rooms[10].zone = "杭州"
      region.rooms[10].id = 219
      region.rooms[10].links = {}
        region.rooms[10].links.w = {}
          region.rooms[10].links.w.to = 218
          region.rooms[10].links.w.con = ""
      region.rooms[10].exits = "west"
      region.rooms[10].desc = "    书院正中有一匾“凤池书院”。书院里坐着两位老者，他们正在吟诗作对。他们身旁的桌上铺着宣纸和笔墨。"
    region.rooms[11] = {}
      region.rooms[11].path = "fly hz;|!hoteld::w|;n;w"
      region.rooms[11].name = "临安戏院"
      region.rooms[11].zone = "杭州"
      region.rooms[11].id = 220
      region.rooms[11].links = {}
        region.rooms[11].links.e = {}
          region.rooms[11].links.e.to = 218
          region.rooms[11].links.e.con = ""
      region.rooms[11].exits = "east"
      region.rooms[11].desc = "    这儿是临安最有名的大戏院，在全国各地也有很大的名气，由这个戏院组织的戏班子常常到各地去进行表演，非常的受好评。你可以在这儿向管事打听有关工作的事。（ask guan about job）"
    region.rooms[12] = {}
      region.rooms[12].path = "fly hz;|!hoteld::w|"
      region.rooms[12].name = "青石大道"
      region.rooms[12].zone = "杭州"
      region.rooms[12].id = 221
      region.rooms[12].links = {}
        region.rooms[12].links.e = {}
          region.rooms[12].links.e.to = 222
          region.rooms[12].links.e.con = ""
        region.rooms[12].links.sw = {}
          region.rooms[12].links.sw.to = 226
          region.rooms[12].links.sw.con = ""
        region.rooms[12].links.n = {}
          region.rooms[12].links.n.to = 218
          region.rooms[12].links.n.con = ""
      region.rooms[12].exits = "east|north|southwest"
      region.rooms[12].desc = "    沿湖大道旁店铺林立，长街故朴，屋舍鳞次栉比，道上人来车往，一片太平热闹景象。街东边有一家客店。"
    region.rooms[13] = {}
      region.rooms[13].path = "fly hz"
      region.rooms[13].name = "天外天客店"
      region.rooms[13].zone = "杭州"
      region.rooms[13].id = 222
      region.rooms[13].links = {}
        region.rooms[13].links.e = {}
          region.rooms[13].links.e.to = 223
          region.rooms[13].links.e.con = "hoteld:"
        region.rooms[13].links.w = {}
          region.rooms[13].links.w.to = 221
          region.rooms[13].links.w.con = "hoteld:"
        region.rooms[13].links.u = {}
          region.rooms[13].links.u.to = 224
          region.rooms[13].links.u.con = "hotelu:"
      region.rooms[13].exits = "up|east|west"
      region.rooms[13].desc = "    这是杭州最有名的客店，里面雕梁画壁，装饰有如宫殿，你可以在这里打听到各地的风土人情。店小二里里外外忙得团团转，接待着南腔北调的客人。墙上挂着一个牌子(paizi)。"
    region.rooms[14] = {}
      region.rooms[14].path = "fly hz;|!hoteld::e|"
      region.rooms[14].name = "马厩"
      region.rooms[14].zone = "杭州"
      region.rooms[14].id = 223
      region.rooms[14].links = {}
        region.rooms[14].links.w = {}
          region.rooms[14].links.w.to = 222
          region.rooms[14].links.w.con = ""
      region.rooms[14].exits = "west"
      region.rooms[14].desc = "    这是天外天客店后的马厩，常年供应新鲜草料。杭州自古号称天堂，杭州的客店汇集四海宾客。马夫们会把马牵到马厩好生照看，将它们喂饱饮足，再洗刷得干乾净净，一直伺候到客人上路。马厩雨檐下的烂木柱上钉着一块破木牌(paizi)。    马厩中堆放著几堆草料，正中有一口泔槽。"
    region.rooms[15] = {}
      region.rooms[15].path = "fly hz;|!hotelu::u|"
      region.rooms[15].name = "天外天客店二楼"
      region.rooms[15].zone = "杭州"
      region.rooms[15].id = 224
      region.rooms[15].links = {}
        region.rooms[15].links.enter = {}
          region.rooms[15].links.enter.to = 225
          region.rooms[15].links.enter.con = ""
        region.rooms[15].links.d = {}
          region.rooms[15].links.d.to = 222
          region.rooms[15].links.d.con = ""
      region.rooms[15].exits = "enter|down"
      region.rooms[15].desc = "    你正走在天外天客店二楼的走廊上，可以听到从客房里不时地呼呼的打酣声，一阵高过一阵。不时有睡意朦胧的旅客进进出出，到楼下的掌柜处付了钱再上来睡觉。"
    region.rooms[16] = {}
      region.rooms[16].path = "fly hz;|!hotelu::u|;enter"
      region.rooms[16].name = "天外天客店二楼"
      region.rooms[16].zone = "杭州"
      region.rooms[16].id = 225
      region.rooms[16].links = {}
        region.rooms[16].links.out = {}
          region.rooms[16].links.out.to = 224
          region.rooms[16].links.out.con = ""
      region.rooms[16].exits = "out"
      region.rooms[16].desc = "    天外天客店果然名不虚传，好大的一间客房，一张精致的床，窗外是美丽的西湖，无边的宜人景致。暖暖的风吹得你昏昏欲睡，这里正是睡觉的好地方。"
    region.rooms[17] = {}
      region.rooms[17].path = "fly hz;|!hoteld::w|;sw"
      region.rooms[17].name = "青石大道"
      region.rooms[17].zone = "杭州"
      region.rooms[17].id = 226
      region.rooms[17].links = {}
        region.rooms[17].links.e = {}
          region.rooms[17].links.e.to = 227
          region.rooms[17].links.e.con = ""
        region.rooms[17].links.sw = {}
          region.rooms[17].links.sw.to = 231
          region.rooms[17].links.sw.con = ""
        region.rooms[17].links.w = {}
          region.rooms[17].links.w.to = 228
          region.rooms[17].links.w.con = ""
        region.rooms[17].links.ne = {}
          region.rooms[17].links.ne.to = 221
          region.rooms[17].links.ne.con = ""
      region.rooms[17].exits = "east|northeast|west|southwest"
      region.rooms[17].desc = "    沿湖大道旁店铺林立，长街故朴，屋舍鳞次栉比，道上人来车往，一片太平热闹景象。西边有一花园，游人进进出出，十分热闹。东边是名医胡庆余开的药铺。"
    region.rooms[18] = {}
      region.rooms[18].path = "fly hz;|!hoteld::w|;sw;e"
      region.rooms[18].name = "胡庆余堂"
      region.rooms[18].zone = "杭州"
      region.rooms[18].id = 227
      region.rooms[18].links = {}
        region.rooms[18].links.w = {}
          region.rooms[18].links.w.to = 226
          region.rooms[18].links.w.con = ""
      region.rooms[18].exits = "west"
      region.rooms[18].desc = "    这是一家明净宽敞的药堂，後墙上是一个大药柜。几个伙计正忙着爬上爬下地从小抽屉里抓药。药柜前摆着一张桌子，桌旁一位老者正在为人把脉。他就是名医胡庆余。"
    region.rooms[19] = {}
      region.rooms[19].path = "fly hz;|!hoteld::w|;sw;w"
      region.rooms[19].name = "清波门"
      region.rooms[19].zone = "杭州"
      region.rooms[19].id = 228
      region.rooms[19].links = {}
        region.rooms[19].links.e = {}
          region.rooms[19].links.e.to = 226
          region.rooms[19].links.e.con = ""
        region.rooms[19].links.w = {}
          region.rooms[19].links.w.to = 229
          region.rooms[19].links.w.con = ""
      region.rooms[19].exits = "east|west"
      region.rooms[19].desc = "    园门口有一大门楼，大匾上刻着“清波门”。门楼下站着几个嬉嬉哈哈的少女，惹人坠步相观。在往西就进了聚景，往东便回到大路。"
    region.rooms[20] = {}
      region.rooms[20].path = "fly hz;|!hoteld::w|;sw;w;w"
      region.rooms[20].name = "聚景园"
      region.rooms[20].zone = "杭州"
      region.rooms[20].id = 229
      region.rooms[20].links = {}
        region.rooms[20].links.e = {}
          region.rooms[20].links.e.to = 228
          region.rooms[20].links.e.con = ""
        region.rooms[20].links.ne = {}
          region.rooms[20].links.ne.to = 230
          region.rooms[20].links.ne.con = ""
      region.rooms[20].exits = "east|northeast"
      region.rooms[20].desc = "    漫步园中，只见湖傍遍置垂柳。柳树丛中，种了不少碧桃。东风送暖之时，这里“杨柳千条拂面丝，绿烟金穗不胜吹”。诗人刘禹锡的“桃红李白皆夸好，须得垂杨相发挥”形容的恰到好处。东面是清波门，往东北便是柳浪桥。"
    region.rooms[21] = {}
      region.rooms[21].path = "fly hz;|!hoteld::w|;sw;w;w;ne"
      region.rooms[21].name = "柳浪桥"
      region.rooms[21].zone = "杭州"
      region.rooms[21].id = 230
      region.rooms[21].links = {}
        region.rooms[21].links.sw = {}
          region.rooms[21].links.sw.to = 229
          region.rooms[21].links.sw.con = ""
      region.rooms[21].exits = "southwest"
      region.rooms[21].desc = "    每当春至，站在桥上，沿湖垂柳在风中摇曳如翠浪翻空，黄莺在枝头迎春嬉戏，鸣声婉转，故得名“浪桥闻莺”。"
    region.rooms[22] = {}
      region.rooms[22].path = "fly hz;|!hoteld::w|;sw;sw"
      region.rooms[22].name = "青石大道"
      region.rooms[22].zone = "杭州"
      region.rooms[22].id = 231
      region.rooms[22].links = {}
        region.rooms[22].links.ne = {}
          region.rooms[22].links.ne.to = 226
          region.rooms[22].links.ne.con = ""
        region.rooms[22].links.sw = {}
          region.rooms[22].links.sw.to = 236
          region.rooms[22].links.sw.con = ""
        region.rooms[22].links.w = {}
          region.rooms[22].links.w.to = 232
          region.rooms[22].links.w.con = ""
      region.rooms[22].exits = "northeast|west|southwest"
      region.rooms[22].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。东北和西边各是一条大道。西南边是上玉皇山的山路。"
    region.rooms[23] = {}
      region.rooms[23].path = "fly hz;|!hoteld::w|;sw;sw;w"
      region.rooms[23].name = "青石大道"
      region.rooms[23].zone = "杭州"
      region.rooms[23].id = 232
      region.rooms[23].links = {}
        region.rooms[23].links.nu = {}
          region.rooms[23].links.nu.to = 235
          region.rooms[23].links.nu.con = ""
        region.rooms[23].links.s = {}
          region.rooms[23].links.s.to = 233
          region.rooms[23].links.s.con = ""
        region.rooms[23].links.w = {}
          region.rooms[23].links.w.to = 260
          region.rooms[23].links.w.con = ""
        region.rooms[23].links.e = {}
          region.rooms[23].links.e.to = 231
          region.rooms[23].links.e.con = ""
      region.rooms[23].exits = "south|east|northup|west"
      region.rooms[23].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。北边可上雷峰，南边是净慈寺。"
    region.rooms[24] = {}
      region.rooms[24].path = "fly hz;|!hoteld::w|;sw;sw;w;s"
      region.rooms[24].name = "净慈寺"
      region.rooms[24].zone = "杭州"
      region.rooms[24].id = 233
      region.rooms[24].links = {}
        region.rooms[24].links.enter = {}
          region.rooms[24].links.enter.to = 234
          region.rooms[24].links.enter.con = ""
        region.rooms[24].links.n = {}
          region.rooms[24].links.n.to = 232
          region.rooms[24].links.n.con = ""
      region.rooms[24].exits = "north|enter"
      region.rooms[24].desc = "    净慈寺，原名慧日永明院，又叫兴教寺。净慈寺面向西湖，後拥苍然挺秀的南屏山。往北就回到大道上。"
    region.rooms[25] = {}
      region.rooms[25].path = "fly hz;|!hoteld::w|;sw;sw;w;s;enter"
      region.rooms[25].name = "净慈寺"
      region.rooms[25].zone = "杭州"
      region.rooms[25].id = 234
      region.rooms[25].links = {}
        region.rooms[25].links.out = {}
          region.rooms[25].links.out.to = 233
          region.rooms[25].links.out.con = ""
      region.rooms[25].exits = "out"
      region.rooms[25].desc = "    净慈寺有前，中，後三殿，以中间的大雄宝殿最为壮观。大雄宝殿，外观两层，黄色琉璃瓦屋顶，特别显的精美宏伟。寺廊的钟声在苍烟暮霭中回荡，抑扬动听，这就是西湖十景之一“南屏晚钟”的来历。"
    region.rooms[26] = {}
      region.rooms[26].path = "fly hz;|!hoteld::w|;sw;sw;w;nu"
      region.rooms[26].name = "夕照山"
      region.rooms[26].zone = "杭州"
      region.rooms[26].id = 235
      region.rooms[26].links = {}
        region.rooms[26].links.sd = {}
          region.rooms[26].links.sd.to = 232
          region.rooms[26].links.sd.con = ""
      region.rooms[26].exits = "southdown"
      region.rooms[26].desc = "    夕照山上遍植栖树和红枫。每逢深秋，层林尽染，分外壮观。山顶有一座塔，雷峰塔。神话“白蛇传”中的白娘娘就是被法海禁锢在这座塔里。每当夕阳西下，彩云缭绕，塔影幢幢，这就是西湖十景之一的“雷峰夕照”。"
    region.rooms[27] = {}
      region.rooms[27].path = "fly hz;|!hoteld::w|;sw;sw;sw"
      region.rooms[27].name = "玉皇山脚"
      region.rooms[27].zone = "杭州"
      region.rooms[27].id = 236
      region.rooms[27].links = {}
        region.rooms[27].links.ne = {}
          region.rooms[27].links.ne.to = 231
          region.rooms[27].links.ne.con = ""
        region.rooms[27].links.wu = {}
          region.rooms[27].links.wu.to = 237
          region.rooms[27].links.wu.con = ""
      region.rooms[27].exits = "westup|northeast"
      region.rooms[27].desc = "    只见往上的山路曲折蜿延。山路旁有一座小六角亭，几个游人正在亭里歇脚。东北边是一条青石大道，往西是上山的路。"
    region.rooms[28] = {}
      region.rooms[28].path = "fly hz;|!hoteld::w|;sw;sw;sw;wu"
      region.rooms[28].name = "山路"
      region.rooms[28].zone = "杭州"
      region.rooms[28].id = 237
      region.rooms[28].links = {}
        region.rooms[28].links.ed = {}
          region.rooms[28].links.ed.to = 236
          region.rooms[28].links.ed.con = ""
        region.rooms[28].links.wu = {}
          region.rooms[28].links.wu.to = 238
          region.rooms[28].links.wu.con = ""
      region.rooms[28].exits = "westup|eastdown"
      region.rooms[28].desc = "    山路崎岖，曲折蜿延。四周林木苍翠，修竹茂密。山路旁是涵碧亭，在这里极目远眺，群山环湖尽收眼底。西边是上山的路，往东便是下山的路。"
    region.rooms[29] = {}
      region.rooms[29].path = "fly hz;|!hoteld::w|;sw;sw;sw;wu;wu"
      region.rooms[29].name = "玉皇山顶"
      region.rooms[29].zone = "杭州"
      region.rooms[29].id = 238
      region.rooms[29].links = {}
        region.rooms[29].links.ed = {}
          region.rooms[29].links.ed.to = 237
          region.rooms[29].links.ed.con = ""
        region.rooms[29].links.wd = {}
          region.rooms[29].links.wd.to = 239
          region.rooms[29].links.wd.con = ""
      region.rooms[29].exits = "eastdown|westdown"
      region.rooms[29].desc = "    登上玉皇山，俯瞰山下，可以看到“八卦田”。据说这是皇帝祭先农时亲耕的籍田。山顶有福星观，建於唐朝。廊宇旁有天一池和白石井，并建有望湖亭。东西两边各有一条下山的路。"
    region.rooms[30] = {}
      region.rooms[30].path = "fly hz;|!hoteld::w|;sw;sw;sw;wu;wu;wd"
      region.rooms[30].name = "山路"
      region.rooms[30].zone = "杭州"
      region.rooms[30].id = 239
      region.rooms[30].links = {}
        region.rooms[30].links.wd = {}
          region.rooms[30].links.wd.to = 240
          region.rooms[30].links.wd.con = ""
        region.rooms[30].links.eu = {}
          region.rooms[30].links.eu.to = 238
          region.rooms[30].links.eu.con = ""
      region.rooms[30].exits = "eastup|westdown"
      region.rooms[30].desc = "    山路崎岖，曲折蜿延。四周林木苍翠，修竹茂密。山路旁有一山洞，据说洞里有时会传出虎哮声，故名老虎洞。西边是下山的路，往东下山便到了山底。"
    region.rooms[31] = {}
      region.rooms[31].path = "fly hz;|!hoteld::w|;sw;sw;sw;wu;wu;wd;wd"
      region.rooms[31].name = "玉皇山"
      region.rooms[31].zone = "杭州"
      region.rooms[31].id = 240
      region.rooms[31].links = {}
        region.rooms[31].links.w = {}
          region.rooms[31].links.w.to = 241
          region.rooms[31].links.w.con = ""
        region.rooms[31].links.eu = {}
          region.rooms[31].links.eu.to = 239
          region.rooms[31].links.eu.con = ""
      region.rooms[31].exits = "eastup|west"
      region.rooms[31].desc = "    山脚有一座小亭，德意亭。不少游客登山前或下山後都在此小歇。山路蜿延往东向上。西边有一条大路。"
    region.rooms[32] = {}
      region.rooms[32].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s"
      region.rooms[32].name = "青石大道"
      region.rooms[32].zone = "杭州"
      region.rooms[32].id = 241
      region.rooms[32].links = {}
        region.rooms[32].links.e = {}
          region.rooms[32].links.e.to = 240
          region.rooms[32].links.e.con = ""
        region.rooms[32].links.s = {}
          region.rooms[32].links.s.to = 243
          region.rooms[32].links.s.con = ""
        region.rooms[32].links.w = {}
          region.rooms[32].links.w.to = 242
          region.rooms[32].links.w.con = ""
        region.rooms[32].links.n = {}
          region.rooms[32].links.n.to = 258
          region.rooms[32].links.n.con = ""
      region.rooms[32].exits = "south|east|north|west"
      region.rooms[32].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道伸向南北两边，往西是虎跑泉，往东是一条山路。"
    region.rooms[33] = {}
      region.rooms[33].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;w"
      region.rooms[33].name = "虎跑泉"
      region.rooms[33].zone = "杭州"
      region.rooms[33].id = 242
      region.rooms[33].links = {}
        region.rooms[33].links.e = {}
          region.rooms[33].links.e.to = 241
          region.rooms[33].links.e.con = ""
        region.rooms[33].links.sw = {}
          region.rooms[33].links.sw.to = 325
          region.rooms[33].links.sw.con = ""
      region.rooms[33].exits = "east|southwest"
      region.rooms[33].desc = "    只见泉水从沙岩中渗流而出，清澈见底。相传有位名叫性空的和尚深爱此山风景灵秀，便住了下来。後因水源奇缺，准备迁走。一夜，梦神告诉他说“南岳衡山童子泉，当遣二虎移来。”第二天，果然看见两只老虎跑地作穴，涌出泉水，所以定名为“虎跑泉”。"
    region.rooms[34] = {}
      region.rooms[34].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s"
      region.rooms[34].name = "钱塘江畔"
      region.rooms[34].zone = "杭州"
      region.rooms[34].id = 243
      region.rooms[34].links = {}
        region.rooms[34].links.wu = {}
          region.rooms[34].links.wu.to = 244
          region.rooms[34].links.wu.con = ""
        region.rooms[34].links.n = {}
          region.rooms[34].links.n.to = 241
          region.rooms[34].links.n.con = ""
      region.rooms[34].exits = "westup|north"
      region.rooms[34].desc = "    钱塘江，每年八月十八是观潮的好日子。“八月十八潮，壮观天下无”。潮水来时“远若素练横江，声如金鼓；近则亘如山岳，奋如雷霆”，刹那间，漫江沸腾，泼涛万顷，潮高丈馀，万马奔腾，真有“涛来势转雄，猎猎驾长风。雷震云霓里，山飞霜雪中”的壮丽气势。西上月轮山便到了六和塔。"
    region.rooms[35] = {}
      region.rooms[35].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu"
      region.rooms[35].name = "六和塔底"
      region.rooms[35].zone = "杭州"
      region.rooms[35].id = 244
      region.rooms[35].links = {}
        region.rooms[35].links.ed = {}
          region.rooms[35].links.ed.to = 243
          region.rooms[35].links.ed.con = ""
        region.rooms[35].links.enter = {}
          region.rooms[35].links.enter.to = 245
          region.rooms[35].links.enter.con = ""
      region.rooms[35].exits = "enter|eastdown"
      region.rooms[35].desc = "    爬上月轮山，便来到了六和塔之前。六和塔亦名六合塔，“六和”之名来之佛家的六种规约，“六合”就是“天，地，四方”的意思。这座八角塔有十三层，在它的飞檐翘角上括有一百零四只大铁铃。"
    region.rooms[36] = {}
      region.rooms[36].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter"
      region.rooms[36].name = "六和塔"
      region.rooms[36].zone = "杭州"
      region.rooms[36].id = 245
      region.rooms[36].links = {}
        region.rooms[36].links.u = {}
          region.rooms[36].links.u.to = 246
          region.rooms[36].links.u.con = "lht:245:246"
        region.rooms[36].links.out = {}
          region.rooms[36].links.out.to = 244
          region.rooms[36].links.out.con = ""
      region.rooms[36].exits = "up|out"
      region.rooms[36].desc = "    这里是六和塔的底层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[37] = {}
      region.rooms[37].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|"
      region.rooms[37].name = "六和塔"
      region.rooms[37].zone = "杭州"
      region.rooms[37].id = 246
	  region.rooms[37].nodig = true
      region.rooms[37].links = {}
        region.rooms[37].links.u = {}
          region.rooms[37].links.u.to = 247
          region.rooms[37].links.u.con = "lht:246:247"
        region.rooms[37].links.d = {}
          region.rooms[37].links.d.to = 245
          region.rooms[37].links.d.con = ""
      region.rooms[37].exits = "up|down"
      region.rooms[37].desc = "    这里是六和塔的二层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[38] = {}
      region.rooms[38].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|"
      region.rooms[38].name = "六和塔"
      region.rooms[38].zone = "杭州"
      region.rooms[38].id = 247
      region.rooms[38].nodig = true
	  region.rooms[38].links = {}
        region.rooms[38].links.u = {}
          region.rooms[38].links.u.to = 248
          region.rooms[38].links.u.con = "lht:247:248"
        region.rooms[38].links.d = {}
          region.rooms[38].links.d.to = 246
          region.rooms[38].links.d.con = ""
      region.rooms[38].exits = "up|down"
      region.rooms[38].desc = "    这里是六和塔的三层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[39] = {}
      region.rooms[39].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|"
      region.rooms[39].name = "六和塔"
      region.rooms[39].zone = "杭州"
      region.rooms[39].id = 248
	  region.rooms[39].nodig = true
      region.rooms[39].links = {}
        region.rooms[39].links.u = {}
          region.rooms[39].links.u.to = 249
          region.rooms[39].links.u.con = "lht:248:249"
        region.rooms[39].links.d = {}
          region.rooms[39].links.d.to = 247
          region.rooms[39].links.d.con = ""
      region.rooms[39].exits = "up|down"
      region.rooms[39].desc = "    这里是六和塔的四层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[40] = {}
      region.rooms[40].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|"
      region.rooms[40].name = "六和塔"
      region.rooms[40].zone = "杭州"
      region.rooms[40].id = 249
	  region.rooms[40].nodig = true
      region.rooms[40].links = {}
        region.rooms[40].links.u = {}
          region.rooms[40].links.u.to = 250
          region.rooms[40].links.u.con = "lht:249:250"
        region.rooms[40].links.d = {}
          region.rooms[40].links.d.to = 248
          region.rooms[40].links.d.con = ""
      region.rooms[40].exits = "up|down"
      region.rooms[40].desc = "    这里是六和塔的五层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[41] = {}
      region.rooms[41].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|;|!lht:249:250:u|"
      region.rooms[41].name = "六和塔"
      region.rooms[41].zone = "杭州"
      region.rooms[41].id = 250
	  region.rooms[41].nodig = true
      region.rooms[41].links = {}
        region.rooms[41].links.u = {}
          region.rooms[41].links.u.to = 251
          region.rooms[41].links.u.con = "lht:250:251"
        region.rooms[41].links.d = {}
          region.rooms[41].links.d.to = 249
          region.rooms[41].links.d.con = ""
      region.rooms[41].exits = "up|down"
      region.rooms[41].desc = "    这里是六和塔的六层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[42] = {}
      region.rooms[42].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|;|!lht:249:250:u|;!lht:250:251:u|"
      region.rooms[42].name = "六和塔"
      region.rooms[42].zone = "杭州"
      region.rooms[42].id = 251
	  region.rooms[42].nodig = true
      region.rooms[42].links = {}
        region.rooms[42].links.u = {}
          region.rooms[42].links.u.to = 252
          region.rooms[42].links.u.con = "lht:251:252"
        region.rooms[42].links.d = {}
          region.rooms[42].links.d.to = 250
          region.rooms[42].links.d.con = ""
      region.rooms[42].exits = "up|down"
      region.rooms[42].desc = "    这里是六和塔的七层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[43] = {}
      region.rooms[43].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|;|!lht:249:250:u|;!lht:250:251:u|;|!lht:251:252:u|"
      region.rooms[43].name = "六和塔"
      region.rooms[43].zone = "杭州"
      region.rooms[43].id = 252
	  region.rooms[43].nodig = true
      region.rooms[43].links = {}
        region.rooms[43].links.u = {}
          region.rooms[43].links.u.to = 253
          region.rooms[43].links.u.con = "lht:252:253"
        region.rooms[43].links.d = {}
          region.rooms[43].links.d.to = 251
          region.rooms[43].links.d.con = ""
      region.rooms[43].exits = "up|down"
      region.rooms[43].desc = "    这里是六和塔的八层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[44] = {}
      region.rooms[44].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|;|!lht:249:250:u|;!lht:250:251:u|;|!lht:251:252:u|;|!lht:252:253:u|"
      region.rooms[44].name = "六和塔"
      region.rooms[44].zone = "杭州"
      region.rooms[44].id = 253
	  region.rooms[44].nodig = true
      region.rooms[44].links = {}
        region.rooms[44].links.u = {}
          region.rooms[44].links.u.to = 254
          region.rooms[44].links.u.con = "lht:253:254"
        region.rooms[44].links.d = {}
          region.rooms[44].links.d.to = 252
          region.rooms[44].links.d.con = ""
      region.rooms[44].exits = "up|down"
      region.rooms[44].desc = "    这里是六和塔的九层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[45] = {}
      region.rooms[45].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|;|!lht:249:250:u|;!lht:250:251:u|;|!lht:251:252:u|;|!lht:252:253:u|;!lht:253:254:u|"
      region.rooms[45].name = "六和塔"
      region.rooms[45].zone = "杭州"
      region.rooms[45].id = 254
	  region.rooms[45].nodig = true
      region.rooms[45].links = {}
        region.rooms[45].links.u = {}
          region.rooms[45].links.u.to = 255
          region.rooms[45].links.u.con = "lht:254:255"
        region.rooms[45].links.d = {}
          region.rooms[45].links.d.to = 253
          region.rooms[45].links.d.con = ""
      region.rooms[45].exits = "up|down"
      region.rooms[45].desc = "    这里是六和塔的十层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[46] = {}
      region.rooms[46].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|;|!lht:249:250:u|;!lht:250:251:u|;|!lht:251:252:u|;|!lht:252:253:u|;!lht:253:254:u|;|!lht:254:255:u|"
      region.rooms[46].name = "六和塔"
      region.rooms[46].zone = "杭州"
      region.rooms[46].id = 255
	  region.rooms[46].nodig = true
      region.rooms[46].links = {}
        region.rooms[46].links.u = {}
          region.rooms[46].links.u.to = 256
          region.rooms[46].links.u.con = "lht:255:256"
        region.rooms[46].links.d = {}
          region.rooms[46].links.d.to = 254
          region.rooms[46].links.d.con = ""
      region.rooms[46].exits = "up|down"
      region.rooms[46].desc = "    这里是六和塔的十一层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[47] = {}
      region.rooms[47].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|;|!lht:249:250:u|;!lht:250:251:u|;|!lht:251:252:u|;|!lht:252:253:u|;!lht:253:254:u|;|!lht:254:255:u|;|!lht:255:256:u|"
      region.rooms[47].name = "六和塔"
      region.rooms[47].zone = "杭州"
      region.rooms[47].id = 256
	  region.rooms[47].nodig = true
      region.rooms[47].links = {}
        region.rooms[47].links.u = {}
          region.rooms[47].links.u.to = 257
          region.rooms[47].links.u.con = "lht:256:257"
        region.rooms[47].links.d = {}
          region.rooms[47].links.d.to = 255
          region.rooms[47].links.d.con = ""
      region.rooms[47].exits = "up|down"
      region.rooms[47].desc = "    这里是六和塔的十二层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。"
    region.rooms[48] = {}
      region.rooms[48].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;s;s;wu;enter;|!lht:245:246:u|;|!lht:246:247:u|;|!lht:247:248:u|;|!lht:248:249:u|;|!lht:249:250:u|;!lht:250:251:u|;|!lht:251:252:u|;|!lht:252:253:u|;!lht:253:254:u|;|!lht:254:255:u|;|!lht:256:257:u|"
      region.rooms[48].name = "六和塔"
      region.rooms[48].zone = "杭州"
      region.rooms[48].id = 257
	  region.rooms[48].nodig = true
      region.rooms[48].links = {}
        region.rooms[48].links.d = {}
          region.rooms[48].links.d.to = 256
          region.rooms[48].links.d.con = ""
      region.rooms[48].exits = "down"
      region.rooms[48].desc = "    这里是六和塔的十三层。窗(window)外是浓妆淡抹的西子湖，塔中玲珑八角，青砖砌地，雕栏飞檐间粘连了些许蛛网。这里是塔的最高处，往外望去，西湖美景尽收眼底。"
    region.rooms[49] = {}
      region.rooms[49].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw"
      region.rooms[49].name = "青石大道"
      region.rooms[49].zone = "杭州"
      region.rooms[49].id = 258
	  region.rooms[49].nodig = true
      region.rooms[49].links = {}
        region.rooms[49].links.ne = {}
          region.rooms[49].links.ne.to = 259
          region.rooms[49].links.ne.con = ""
        region.rooms[49].links.s = {}
          region.rooms[49].links.s.to = 241
          region.rooms[49].links.s.con = ""
        region.rooms[49].links.w = {}
          region.rooms[49].links.w.to = 294
          region.rooms[49].links.w.con = ""
      region.rooms[49].exits = "south|northeast|west"
      region.rooms[49].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道伸向东北和南两边，往西是石屋洞。"
    region.rooms[50] = {}
      region.rooms[50].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w"
      region.rooms[50].name = "青石大道"
      region.rooms[50].zone = "杭州"
      region.rooms[50].id = 259
      region.rooms[50].links = {}
        region.rooms[50].links.e = {}
          region.rooms[50].links.e.to = 260
          region.rooms[50].links.e.con = ""
        region.rooms[50].links.sw = {}
          region.rooms[50].links.sw.to = 258
          region.rooms[50].links.sw.con = ""
        region.rooms[50].links.n = {}
          region.rooms[50].links.n.to = 291
          region.rooms[50].links.n.con = ""
      region.rooms[50].exits = "east|north|southwest"
      region.rooms[50].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道伸向东和西南两边，往北是另一条大道。"
    region.rooms[51] = {}
      region.rooms[51].path = "fly hz;|!hoteld::w|;sw;sw;w;w"
      region.rooms[51].name = "青石大道"
      region.rooms[51].zone = "杭州"
      region.rooms[51].id = 260
      region.rooms[51].links = {}
        region.rooms[51].links.e = {}
          region.rooms[51].links.e.to = 232
          region.rooms[51].links.e.con = ""
        region.rooms[51].links.w = {}
          region.rooms[51].links.w.to = 259
          region.rooms[51].links.w.con = ""
        region.rooms[51].links.n = {}
          region.rooms[51].links.n.to = 261
          region.rooms[51].links.n.con = ""
      region.rooms[51].exits = "east|north|west"
      region.rooms[51].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道伸向东西两边，往北是苏堤。"
    region.rooms[52] = {}
      region.rooms[52].path = "fly hz;|!hoteld::w|;sw;sw;w;w;n"
      region.rooms[52].name = "苏堤"
      region.rooms[52].zone = "杭州"
      region.rooms[52].id = 261
      region.rooms[52].links = {}
        region.rooms[52].links.s = {}
          region.rooms[52].links.s.to = 260
          region.rooms[52].links.s.con = ""
        region.rooms[52].links.n = {}
          region.rooms[52].links.n.to = 262
          region.rooms[52].links.n.con = ""
      region.rooms[52].exits = "south|north"
      region.rooms[52].desc = "    苏堤是诗人苏东坡在主持浚深西湖时用湖泥和草筑成的。苏东坡曾有诗记述此事；“我在钱塘拓湖渌，大堤士女争昌丰。六桥横绝天汉上，北山始与南屏通。忽惊二十五万丈，老葑席卷苍烟空。”往南便是大道，北边是映波桥。映波桥乃苏堤六桥由至北南的第一座。"
    region.rooms[53] = {}
      region.rooms[53].path = "fly hz;|!hoteld::w|;sw;sw;w;w;n;n"
      region.rooms[53].name = "苏堤"
      region.rooms[53].zone = "杭州"
      region.rooms[53].id = 262
      region.rooms[53].links = {}
        region.rooms[53].links.s = {}
          region.rooms[53].links.s.to = 261
          region.rooms[53].links.s.con = ""
        region.rooms[53].links.w = {}
          region.rooms[53].links.w.to = 263
          region.rooms[53].links.w.con = ""
        region.rooms[53].links.n = {}
          region.rooms[53].links.n.to = 264
          region.rooms[53].links.n.con = ""
      region.rooms[53].exits = "south|north|west"
      region.rooms[53].desc = "    秋月之夜，月下观湖，满湖银波粼粼，阵阵微风，风中桂子飘香，令人为之心醉。堤边泊着小舟是送游客去三潭映月的。往西边是去花港，东面可见三潭映月遥立湖中，北边是锁澜桥，南面映波桥。"
    region.rooms[54] = {}
      region.rooms[54].path = "fly hz;|!hoteld::w|;sw;sw;w;w;n;n;w"
      region.rooms[54].name = "花港观鱼"
      region.rooms[54].zone = "杭州"
      region.rooms[54].id = 263
      region.rooms[54].links = {}
        region.rooms[54].links.e = {}
          region.rooms[54].links.e.to = 262
          region.rooms[54].links.e.con = ""
      region.rooms[54].exits = "east"
      region.rooms[54].desc = "    只见湖中有一小岛，一座曲桥横跨湖面。曲桥上人群熙攘，倚栏投饵。桥下红鱼，争食欢跳。谢觉哉游园时曾作诗一首“鱼国群粼乐有余，观鱼才觉我非鱼。虞诈两忘欣共处，鱼犹如此况人乎。”"
    region.rooms[55] = {}
      region.rooms[55].path = "fly hz;|!hoteld::w|;sw;sw;w;w;n;n;n"
      region.rooms[55].name = "苏堤"
      region.rooms[55].zone = "杭州"
      region.rooms[55].id = 264
      region.rooms[55].links = {}
        region.rooms[55].links.s = {}
          region.rooms[55].links.s.to = 262
          region.rooms[55].links.s.con = ""
        region.rooms[55].links.n = {}
          region.rooms[55].links.n.to = 265
          region.rooms[55].links.n.con = ""
      region.rooms[55].exits = "south|north"
      region.rooms[55].desc = "    每当盛夏，游客到此纷纷寻荫小息，堤上绿树交柯，鸣蝉噪鼓。北边是望山桥，南面锁澜桥。"
    region.rooms[56] = {}
      region.rooms[56].path = "fly hz;|!hoteld::w|;sw;sw;w;w;n;n;n;n"
      region.rooms[56].name = "苏堤"
      region.rooms[56].zone = "杭州"
      region.rooms[56].id = 265
      region.rooms[56].links = {}
        region.rooms[56].links.s = {}
          region.rooms[56].links.s.to = 264
          region.rooms[56].links.s.con = ""
        region.rooms[56].links.n = {}
          region.rooms[56].links.n.to = 266
          region.rooms[56].links.n.con = ""
      region.rooms[56].exits = "south|north"
      region.rooms[56].desc = "    春晓，漫步林荫道上，烟柳笼纱，雀鸟欢鸣，一片生机。苏堤春晓被列为西湖十景之首，果然名不虚传。北边是压堤桥，南面是望山桥。东面一片梅林，林后似乎有座院落，但看不真切。"
    region.rooms[57] = {}
      region.rooms[57].path = "fly hz;|!hoteld::w|;sw;sw;w;w;n;n;n;n;n"
      region.rooms[57].name = "苏堤"
      region.rooms[57].zone = "杭州"
      region.rooms[57].id = 266
      region.rooms[57].links = {}
        region.rooms[57].links.s = {}
          region.rooms[57].links.s.to = 265
          region.rooms[57].links.s.con = ""
        region.rooms[57].links.n = {}
          region.rooms[57].links.n.to = 267
          region.rooms[57].links.n.con = ""
      region.rooms[57].exits = "south|north"
      region.rooms[57].desc = "    寒冬，瑞雪霏霏中，不少游人踏雪观景。从堤上极目远眺，只见四周玉树琼林。北边是东浦桥，南面是压堤桥。"
    region.rooms[58] = {}
      region.rooms[58].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;s;s"
      region.rooms[58].name = "苏堤"
      region.rooms[58].zone = "杭州"
      region.rooms[58].id = 267
      region.rooms[58].links = {}
        region.rooms[58].links.s = {}
          region.rooms[58].links.s.to = 266
          region.rooms[58].links.s.con = ""
        region.rooms[58].links.w = {}
          region.rooms[58].links.w.to = 268
          region.rooms[58].links.w.con = ""
        region.rooms[58].links.n = {}
          region.rooms[58].links.n.to = 270
          region.rooms[58].links.n.con = ""
      region.rooms[58].exits = "south|north|west"
      region.rooms[58].desc = "    苏堤上，游客们有的林荫大道上漫步吟诗，高谈阔论；有的随机就石，临水而坐；有的伶立湖边，静享湖景。北边是跨虹桥，南面是东浦桥，西面是去曲园风荷。"
    region.rooms[59] = {}
      region.rooms[59].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;s;s;w"
      region.rooms[59].name = "曲院风荷"
      region.rooms[59].zone = "杭州"
      region.rooms[59].id = 268
      region.rooms[59].links = {}
        region.rooms[59].links.e = {}
          region.rooms[59].links.e.to = 267
          region.rooms[59].links.e.con = ""
        region.rooms[59].links.enter = {}
          region.rooms[59].links.enter.to = 269
          region.rooms[59].links.enter.con = ""
      region.rooms[59].exits = "east|enter"
      region.rooms[59].desc = "    跨过小拱桥，迎面有一亭院，旁边立着石碑，上题“曲院风荷。”往东是回苏堤。"
    region.rooms[60] = {}
      region.rooms[60].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;s;s;w;enter"
      region.rooms[60].name = "曲院风荷"
      region.rooms[60].zone = "杭州"
      region.rooms[60].id = 269
      region.rooms[60].links = {}
        region.rooms[60].links.out = {}
          region.rooms[60].links.out.to = 268
          region.rooms[60].links.out.con = ""
      region.rooms[60].exits = "out"
      region.rooms[60].desc = "    走进亭院，只见临湖一座小榭。柱上有一对联(duilian)。 依榭观湖，只见荷花满湖，茭荷深处，香远益清。杨万里曾有题咏“毕竟西湖六月中，风光不与四时同。接天莲叶无穷碧，映日荷花别样红”。"
    region.rooms[61] = {}
      region.rooms[61].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;s"
      region.rooms[61].name = "苏堤"
      region.rooms[61].zone = "杭州"
      region.rooms[61].id = 270
      region.rooms[61].links = {}
        region.rooms[61].links.s = {}
          region.rooms[61].links.s.to = 267
          region.rooms[61].links.s.con = ""
        region.rooms[61].links.n = {}
          region.rooms[61].links.n.to = 271
          region.rooms[61].links.n.con = ""
      region.rooms[61].exits = "south|north"
      region.rooms[61].desc = "    苏堤是诗人苏东坡在主持浚深西湖时用湖泥和草筑成的。苏东坡曾有诗记述此事；“我在钱塘拓湖渌，大堤士女争昌丰。六桥横绝天汉上，北山始与南屏通。忽惊二十五万丈，老葑席卷苍烟空。”往北便是大道，南边是跨虹桥。跨虹桥乃苏堤六桥由北至南的第一座。桥一边是岳湖，桥的另一边是西湖。"
    region.rooms[62] = {}
      region.rooms[62].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w"
      region.rooms[62].name = "青石大道"
      region.rooms[62].zone = "杭州"
      region.rooms[62].id = 271
      region.rooms[62].links = {}
        region.rooms[62].links.e = {}
          region.rooms[62].links.e.to = 272
          region.rooms[62].links.e.con = ""
        region.rooms[62].links.w = {}
          region.rooms[62].links.w.to = 285
          region.rooms[62].links.w.con = ""
        region.rooms[62].links.s = {}
          region.rooms[62].links.s.to = 270
          region.rooms[62].links.s.con = ""
        region.rooms[62].links.n = {}
          region.rooms[62].links.n.to = 283
          region.rooms[62].links.n.con = ""
      region.rooms[62].exits = "south|east|north|west"
      region.rooms[62].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道延伸向东西两边。南边则通往苏堤。北边是岳王庙。"
    region.rooms[63] = {}
      region.rooms[63].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw"
      region.rooms[63].name = "青石大道"
      region.rooms[63].zone = "杭州"
      region.rooms[63].id = 272
      region.rooms[63].links = {}
        region.rooms[63].links.ne = {}
          region.rooms[63].links.ne.to = 211
          region.rooms[63].links.ne.con = ""
        region.rooms[63].links.s = {}
          region.rooms[63].links.s.to = 275
          region.rooms[63].links.s.con = ""
        region.rooms[63].links.w = {}
          region.rooms[63].links.w.to = 271
          region.rooms[63].links.w.con = ""
        region.rooms[63].links.n = {}
          region.rooms[63].links.n.to = 273
          region.rooms[63].links.n.con = ""
      region.rooms[63].exits = "south|north|northeast|west"
      region.rooms[63].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。大道延伸向西边和东北边。朝北走便是上北山。南边则通往西泠桥。"
    region.rooms[64] = {}
      region.rooms[64].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;n"
      region.rooms[64].name = "山路"
      region.rooms[64].zone = "杭州"
      region.rooms[64].id = 273
      region.rooms[64].links = {}
        region.rooms[64].links.s = {}
          region.rooms[64].links.s.to = 272
          region.rooms[64].links.s.con = ""
        region.rooms[64].links.n = {}
          region.rooms[64].links.n.to = 274
          region.rooms[64].links.n.con = ""
      region.rooms[64].exits = "south|north"
      region.rooms[64].desc = "    山上林木茂密，就是炎夏这里还是清凉依旧。朝北走便到了黄龙洞。南边则是下山的路。"
    region.rooms[65] = {}
      region.rooms[65].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;n;n"
      region.rooms[65].name = "黄龙洞"
      region.rooms[65].zone = "杭州"
      region.rooms[65].id = 274
      region.rooms[65].links = {}
        region.rooms[65].links.s = {}
          region.rooms[65].links.s.to = 273
          region.rooms[65].links.s.con = ""
      region.rooms[65].exits = "south"
      region.rooms[65].desc = "    一进山门，松篁交翠，别有洞天。石壁陡削，苔痕常绿；回廊临之间有一小峰，上题：“有龙则灵”。"
    region.rooms[66] = {}
      region.rooms[66].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;s"
      region.rooms[66].name = "西泠桥"
      region.rooms[66].zone = "杭州"
      region.rooms[66].id = 275
      region.rooms[66].links = {}
        region.rooms[66].links.se = {}
          region.rooms[66].links.se.to = 276
          region.rooms[66].links.se.con = ""
        region.rooms[66].links.n = {}
          region.rooms[66].links.n.to = 272
          region.rooms[66].links.n.con = ""
      region.rooms[66].exits = "north|southeast"
      region.rooms[66].desc = "    西泠桥衔结孤山，跨过里西湖。桥的东南边是孤山。北边则是一条青石大道。"
    region.rooms[67] = {}
      region.rooms[67].path = "fly mz;open gate;s;s;s;ed"
      region.rooms[67].name = "孤山"
      region.rooms[67].zone = "杭州|梅庄"
      region.rooms[67].id = 276
      region.rooms[67].links = {}
        region.rooms[67].links.ne = {}
          region.rooms[67].links.ne.to = 278
          region.rooms[67].links.ne.con = ""
        region.rooms[67].links.wu = {}
          region.rooms[67].links.wu.to = 282
          region.rooms[67].links.wu.con = ""
        region.rooms[67].links.e = {}
          region.rooms[67].links.e.to = 279
          region.rooms[67].links.e.con = ""
        region.rooms[67].links.nw = {}
          region.rooms[67].links.nw.to = 275
          region.rooms[67].links.nw.con = ""
        region.rooms[67].links.su = {}
          region.rooms[67].links.su.to = 277
          region.rooms[67].links.su.con = ""
      region.rooms[67].exits = "westup|northwest|east|northeast|southup"
      region.rooms[67].desc = "    通过林荫道向前，迎面石壁上刻有“孤山”两个丹红大字。朝南拾级登山便是平台。东北边便是发鹤亭。东南边则是平湖秋月。西北边通往西泠桥。"
    region.rooms[68] = {}
      region.rooms[68].path = "fly hz;|!hoteld::w|;n;n;n;n;sw;w;sw;w;su"
      region.rooms[68].name = "观景台"
      region.rooms[68].zone = "杭州"
      region.rooms[68].id = 277
      region.rooms[68].links = {}
        region.rooms[68].links.nd = {}
          region.rooms[68].links.nd.to = 276
          region.rooms[68].links.nd.con = ""
      region.rooms[68].exits = "northdown"
      region.rooms[68].desc = "    平台北面有“西湖天下景”亭阁，亭柱两旁有一对联(duilian)。这里还有曲桥水池，临池有叠石假山，布置得高低参差，疏密有致。北边是下山的路。"
    region.rooms[69] = {}
      region.rooms[69].path = "fly hz;|!hoteld::w|;n;n;n;n;sw;w;sw;nw"
      region.rooms[69].name = "放鹤亭"
      region.rooms[69].zone = "杭州"
      region.rooms[69].id = 278
      region.rooms[69].links = {}
        region.rooms[69].links.se = {}
          region.rooms[69].links.se.to = 279
          region.rooms[69].links.se.con = ""
        region.rooms[69].links.sw = {}
          region.rooms[69].links.sw.to = 276
          region.rooms[69].links.sw.con = ""
      region.rooms[69].exits = "southeast|southwest"
      region.rooms[69].desc = "    亭四周种满了梅花。一到冬末春初，梅花盛放，蔚然可观。此亭是为了纪念北宋隐逸诗人林和靖而建。他酷爱梅花。“疏影横斜水清浅，暗香浮动月黄昏”就是他的咏梅名句。据传说，诗人还养鹤一只，取名：“鸣苯”每逢自己外出散步而恰有客人来访时，童子就开笼放鹤，诗人见鹤，便回家接客，故流传有“梅妻鹤子”的故事。朝东南走便是平湖秋月。西南边则是孤山。"
    region.rooms[70] = {}
      region.rooms[70].path = "fly hz;|!hoteld::w|;n;n;n;n;sw;w;sw"
      region.rooms[70].name = "平湖秋月"
      region.rooms[70].zone = "杭州"
      region.rooms[70].id = 279
      region.rooms[70].links = {}
        region.rooms[70].links.ne = {}
          region.rooms[70].links.ne.to = 280
          region.rooms[70].links.ne.con = ""
        region.rooms[70].links.w = {}
          region.rooms[70].links.w.to = 276
          region.rooms[70].links.w.con = ""
        region.rooms[70].links.nw = {}
          region.rooms[70].links.nw.to = 278
          region.rooms[70].links.nw.con = ""
      region.rooms[70].exits = "northwest|northeast|west"
      region.rooms[70].desc = "    平湖秋月三面临水，四面曲栏画廊，直挹波际。曾有“万顷湖平长似镜，四时月好最宜秋”的联句来描写这里秋夜时皓月当空的幽美景色。朝西北走便是放鹤亭。东北边则是白堤。西边就是孤山。"
    region.rooms[71] = {}
      region.rooms[71].path = "fly hz;|!hoteld::w|;n;n;n;n;sw;w"
      region.rooms[71].name = "白堤"
      region.rooms[71].zone = "杭州"
      region.rooms[71].id = 280
      region.rooms[71].links = {}
        region.rooms[71].links.e = {}
          region.rooms[71].links.e.to = 281
          region.rooms[71].links.e.con = ""
        region.rooms[71].links.sw = {}
          region.rooms[71].links.sw.to = 279
          region.rooms[71].links.sw.con = ""
      region.rooms[71].exits = "east|southwest"
      region.rooms[71].desc = "    白堤横旦湖上，把西湖分成里湖与外湖。堤上种满了杨柳，碧桃。每逢春至，“翩翩柳丝泛绿，树树桃颜带笑”。白居易曾有“乱花渐欲迷人眼，浅草才能没马蹄。最爱湖东行不足，绿杨荫里白沙堤。”来描述这里的景色。朝西南走过了锦带桥便是“平湖秋月”。东边则是断桥。"
    region.rooms[72] = {}
      region.rooms[72].path = "fly hz;|!hoteld::w|;n;n;n;n;sw"
      region.rooms[72].name = "断桥"
      region.rooms[72].zone = "杭州"
      region.rooms[72].id = 281
      region.rooms[72].links = {}
        region.rooms[72].links.w = {}
          region.rooms[72].links.w.to = 280
          region.rooms[72].links.w.con = ""
        region.rooms[72].links.ne = {}
          region.rooms[72].links.ne.to = 195
          region.rooms[72].links.ne.con = ""
      region.rooms[72].exits = "northeast|west"
      region.rooms[72].desc = "    断桥正好在外湖和里湖的分水点上。这里亭轩错落，掩映在绿树佳荫之下。“山明水秀轩扉启，落日渔歌过里湖”，就是描述这里傍晚的景色。在断桥上可浏览环湖诸山和湖中诸岛的风光。每当雪後，站在桥头，只见一切都被覆上白雪，玉琢银楼的湖山风貌就是西湖十景之一的“断桥残雪”。民间神话“白蛇传”中的白娘娘和许仙就在这里相会的。    过桥往西走便是白堤了。东北边可通往青石大道。"
    region.rooms[73] = {}
      region.rooms[73].path = "fly mz;open gate;s;s;s"
      region.rooms[73].name = "孤山石阶"
      region.rooms[73].zone = "杭州|梅庄"
      region.rooms[73].id = 282
      region.rooms[73].links = {}
        region.rooms[73].links.ed = {}
          region.rooms[73].links.ed.to = 276
          region.rooms[73].links.ed.con = ""
        region.rooms[73].links.n = {}
          region.rooms[73].links.n.to = 2741
          region.rooms[73].links.n.con = ""
      region.rooms[73].exits = "north|eastdown"
      region.rooms[73].desc = "    你向孤山边的石阶上行去，一路欣赏着湖边长曳的杨柳。不知不觉地转了几个弯，却见遍地都是梅树，老干横斜，枝叶茂密，想像初春梅花盛开之日，香雪如海，定然观赏不尽。"
    region.rooms[74] = {}
      region.rooms[74].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;n"
      region.rooms[74].name = "岳廊"
      region.rooms[74].zone = "杭州"
      region.rooms[74].id = 283
      region.rooms[74].links = {}
        region.rooms[74].links.s = {}
          region.rooms[74].links.s.to = 271
          region.rooms[74].links.s.con = ""
        region.rooms[74].links.n = {}
          region.rooms[74].links.n.to = 284
          region.rooms[74].links.n.con = ""
      region.rooms[74].exits = "south|north"
      region.rooms[74].desc = "    岳王庙的匾上是“心昭天日”四个大字。步入大殿，正中是岳飞的塑像，身後的匾上题着“还我河山”。北边的门通向岳坟，往南是出去的路。"
    region.rooms[75] = {}
      region.rooms[75].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;n;n"
      region.rooms[75].name = "岳坟"
      region.rooms[75].zone = "杭州"
      region.rooms[75].id = 284
      region.rooms[75].links = {}
        region.rooms[75].links.s = {}
          region.rooms[75].links.s.to = 283
          region.rooms[75].links.s.con = ""
      region.rooms[75].exits = "south"
      region.rooms[75].desc = "    墓道两旁有石虎，石羊，石马和三对翁仲。正中古柏交柯，便是岳飞的坟墓。墓碑刻着“宋岳鄂王墓”。 岳王墓的左面，便是岳飞之子岳云的墓，墓碑上刻着“宋继忠侯岳云之墓”.  在岳坟前面两边四个铁像(statue)。东首墙上有四个大字(word)。"
    region.rooms[76] = {}
      region.rooms[76].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w"
      region.rooms[76].name = "青石大道"
      region.rooms[76].zone = "杭州"
      region.rooms[76].id = 285
      region.rooms[76].links = {}
        region.rooms[76].links.e = {}
          region.rooms[76].links.e.to = 271
          region.rooms[76].links.e.con = ""
        region.rooms[76].links.sw = {}
          region.rooms[76].links.sw.to = 306
          region.rooms[76].links.sw.con = ""
        region.rooms[76].links.s = {}
          region.rooms[76].links.s.to = 287
          region.rooms[76].links.s.con = ""
        region.rooms[76].links.wu = {}
          region.rooms[76].links.wu.to = 286
          region.rooms[76].links.wu.con = ""
      region.rooms[76].exits = "south|westup|east|southwest"
      region.rooms[76].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。往西是去玉泉寺的路。大道则延伸向东边和西南边。"
    region.rooms[77] = {}
      region.rooms[77].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;wu"
      region.rooms[77].name = "玉泉"
      region.rooms[77].zone = "杭州"
      region.rooms[77].id = 286
      region.rooms[77].links = {}
        region.rooms[77].links.ed = {}
          region.rooms[77].links.ed.to = 285
          region.rooms[77].links.ed.con = ""
      region.rooms[77].exits = "eastdown"
      region.rooms[77].desc = "    玉泉寺建在玉泉山上，原名清涟寺。走进玉泉寺，只见这里有几个水池(pond)。朝东就是出寺下山的路。"
    region.rooms[78] = {}
      region.rooms[78].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;n;n;ne;n"
      region.rooms[78].name = "沿湖大道"
      region.rooms[78].zone = "杭州"
      region.rooms[78].id = 287
      region.rooms[78].links = {}
        region.rooms[78].links.s = {}
          region.rooms[78].links.s.to = 289
          region.rooms[78].links.s.con = ""
        region.rooms[78].links.w = {}
          region.rooms[78].links.w.to = 288
          region.rooms[78].links.w.con = ""
        region.rooms[78].links.n = {}
          region.rooms[78].links.n.to = 285
          region.rooms[78].links.n.con = ""
      region.rooms[78].exits = "south|north|west"
      region.rooms[78].desc = "    一条宽敞的大道上却游人稀少。原来这里沿路住着的都是达官贵人。本来风景秀丽之处，却显的一片萧瑟。路的西边是一座庄园，大道向南北延伸。"
    region.rooms[79] = {}
      region.rooms[79].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;n;n;ne;n;w"
      region.rooms[79].name = "郭庄"
      region.rooms[79].zone = "杭州"
      region.rooms[79].id = 288
      region.rooms[79].links = {}
        region.rooms[79].links.e = {}
          region.rooms[79].links.e.to = 287
          region.rooms[79].links.e.con = ""
      region.rooms[79].exits = "east"
      region.rooms[79].desc = "    庄园的大匾上是“郭庄”两个大字。大门(gate)紧闭，里面静悄悄的一点声音都没有。"
    region.rooms[80] = {}
      region.rooms[80].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;n;n;ne"
      region.rooms[80].name = "沿湖大道"
      region.rooms[80].zone = "杭州"
      region.rooms[80].id = 289
      region.rooms[80].links = {}
        region.rooms[80].links.sw = {}
          region.rooms[80].links.sw.to = 290
          region.rooms[80].links.sw.con = ""
        region.rooms[80].links.n = {}
          region.rooms[80].links.n.to = 287
          region.rooms[80].links.n.con = ""
      region.rooms[80].exits = "north|southwest"
      region.rooms[80].desc = "    一条宽敞的大道上却游人稀少。原来这里沿路住着的都是达官贵人。本来风景秀丽之处，却显的一片萧瑟。大道向西南和北延伸。"
    region.rooms[81] = {}
      region.rooms[81].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;n;n"
      region.rooms[81].name = "大路"
      region.rooms[81].zone = "杭州"
      region.rooms[81].id = 290
      region.rooms[81].links = {}
        region.rooms[81].links.ne = {}
          region.rooms[81].links.ne.to = 289
          region.rooms[81].links.ne.con = ""
        region.rooms[81].links.s = {}
          region.rooms[81].links.s.to = 291
          region.rooms[81].links.s.con = ""
      region.rooms[81].exits = "south|northeast"
      region.rooms[81].desc = "    路的东边是一座小山。山上郁郁葱葱，种满了树。山上本是一处观赏西湖的好地方，但却被丁财主占为私有。大路向东北和南延伸。"
    region.rooms[82] = {}
      region.rooms[82].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;n"
      region.rooms[82].name = "沿湖大道"
      region.rooms[82].zone = "杭州"
      region.rooms[82].id = 291
      region.rooms[82].links = {}
        region.rooms[82].links.s = {}
          region.rooms[82].links.s.to = 259
          region.rooms[82].links.s.con = ""
        region.rooms[82].links.w = {}
          region.rooms[82].links.w.to = 292
          region.rooms[82].links.w.con = ""
        region.rooms[82].links.n = {}
          region.rooms[82].links.n.to = 290
          region.rooms[82].links.n.con = ""
      region.rooms[82].exits = "south|north|west"
      region.rooms[82].desc = "    一条宽敞的大道上却游人稀少。原来这里沿路住着的都是达官贵人。本来风景秀丽之处，却显的一片萧瑟。路的西边是一座庄园，大道向南北延伸。"
    region.rooms[83] = {}
      region.rooms[83].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;n;w"
      region.rooms[83].name = "刘庄"
      region.rooms[83].zone = "杭州"
      region.rooms[83].id = 292
      region.rooms[83].links = {}
        region.rooms[83].links.e = {}
          region.rooms[83].links.e.to = 291
          region.rooms[83].links.e.con = ""
      region.rooms[83].exits = "east"
      region.rooms[83].desc = "    庄园的大匾上是“刘庄”两个大字。大门(gate)紧闭，里面静悄悄的一点声音都没有。"
    region.rooms[84] = {}
      region.rooms[84].path = "fly hz;|!hoteld::w|;n;n;n;n;w;nu"
      region.rooms[84].name = "宝石山"
      region.rooms[84].zone = "杭州"
      region.rooms[84].id = 293
      region.rooms[84].links = {}
        region.rooms[84].links.sd = {}
          region.rooms[84].links.sd.to = 211
          region.rooms[84].links.sd.con = ""
        region.rooms[84].links.nu = {}
          region.rooms[84].links.nu.to = 2965
          region.rooms[84].links.nu.con = ""
      region.rooms[84].exits = "northup|southdown"
      region.rooms[84].desc = "    宝石山不是很高，山上多奇峰怪石。山路旁有一座亭子“来凤亭”，亭前有块卵形大石，临空搁置在山巅，叫落星石，又称寿星石。再往北上就到了保淑塔，往南下便回到大道了。"
    region.rooms[85] = {}
      region.rooms[85].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w"
      region.rooms[85].name = "石屋洞"
      region.rooms[85].zone = "杭州"
      region.rooms[85].id = 294
      region.rooms[85].links = {}
        region.rooms[85].links.e = {}
          region.rooms[85].links.e.to = 258
          region.rooms[85].links.e.con = ""
        region.rooms[85].links.wu = {}
          region.rooms[85].links.wu.to = 295
          region.rooms[85].links.wu.con = ""
      region.rooms[85].exits = "westup|east"
      region.rooms[85].desc = "    山路旁是石屋洞。石屋洞，洞中有洞，洞洞相连。主洞高大宽敞，洁净明亮，上宽下窄，状如浮螺。西上便到了满觉陇；山路的尽头连着一条由北至南的大道。"
    region.rooms[86] = {}
      region.rooms[86].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu"
      region.rooms[86].name = "满觉陇"
      region.rooms[86].zone = "杭州"
      region.rooms[86].id = 295
      region.rooms[86].links = {}
        region.rooms[86].links.ed = {}
          region.rooms[86].links.ed.to = 294
          region.rooms[86].links.ed.con = ""
        region.rooms[86].links.wu = {}
          region.rooms[86].links.wu.to = 296
          region.rooms[86].links.wu.con = ""
      region.rooms[86].exits = "westup|eastdown"
      region.rooms[86].desc = "    山路旁有一个小村落，村落四周桂花成林。每当仲秋，桂花盛开，飘香数里。被称为“金雪世界”。西上是水乐洞，东下石屋洞。"
    region.rooms[87] = {}
      region.rooms[87].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu"
      region.rooms[87].name = "水乐洞"
      region.rooms[87].zone = "杭州"
      region.rooms[87].id = 296
      region.rooms[87].links = {}
        region.rooms[87].links.ed = {}
          region.rooms[87].links.ed.to = 295
          region.rooms[87].links.ed.con = ""
        region.rooms[87].links.wu = {}
          region.rooms[87].links.wu.to = 297
          region.rooms[87].links.wu.con = ""
      region.rooms[87].exits = "westup|eastdown"
      region.rooms[87].desc = "    水乐洞有两个洞口，洞的左口有股山泉从石缝中涌出。泉水声如金石，和谐悦耳。旁有“天然琴声”，“听无弦琴”等石刻字句。洞内两壁有很多钟乳石。往东是下山的路，西上便到了烟霞洞。"
    region.rooms[88] = {}
      region.rooms[88].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu"
      region.rooms[88].name = "烟霞洞"
      region.rooms[88].zone = "杭州"
      region.rooms[88].id = 297
      region.rooms[88].links = {}
        region.rooms[88].links.ed = {}
          region.rooms[88].links.ed.to = 296
          region.rooms[88].links.ed.con = ""
        region.rooms[88].links.w = {}
          region.rooms[88].links.w.to = 298
          region.rooms[88].links.w.con = ""
      region.rooms[88].exits = "eastdown|west"
      region.rooms[88].desc = "    据说站在山头，清晨观看山村缭绕炊烟，傍晚仰望蓝天彩霞，景色优美，故称“烟霞”。洞口两旁有精美的“观音”和“大势至菩萨”洞内两壁的天然岩穴里有各代的石刻。往东是下山的路。西边是去龙井。"
    region.rooms[89] = {}
      region.rooms[89].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w"
      region.rooms[89].name = "山路"
      region.rooms[89].zone = "杭州"
      region.rooms[89].id = 298
      region.rooms[89].links = {}
        region.rooms[89].links.e = {}
          region.rooms[89].links.e.to = 297
          region.rooms[89].links.e.con = ""
        region.rooms[89].links.wu = {}
          region.rooms[89].links.wu.to = 314
          region.rooms[89].links.wu.con = ""
        region.rooms[89].links.ne = {}
          region.rooms[89].links.ne.to = 301
          region.rooms[89].links.ne.con = ""
        region.rooms[89].links.n = {}
          region.rooms[89].links.n.to = 299
          region.rooms[89].links.n.con = ""
      region.rooms[89].exits = "westup|east|north|northeast"
      region.rooms[89].desc = "    走在小路上，只见漫山遍野都是绿油油的茶蓬。农家少女们在欢笑声中采茶。山路延伸向东西两边，北边就是龙井，东北边有一条土路。"
    region.rooms[90] = {}
      region.rooms[90].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w;n"
      region.rooms[90].name = "龙井"
      region.rooms[90].zone = "杭州"
      region.rooms[90].id = 299
      region.rooms[90].links = {}
        region.rooms[90].links.s = {}
          region.rooms[90].links.s.to = 298
          region.rooms[90].links.s.con = ""
        region.rooms[90].links.e = {}
          region.rooms[90].links.e.to = 300
          region.rooms[90].links.e.con = ""
      region.rooms[90].exits = "south|east"
      region.rooms[90].desc = "    只见井(jing)水澈可见底而且清冷异常。龙井原名龙泓涧，传说此井与海相通，其中必定有龙，祈祷必雨，故名“龙井”。苏东坡曾有诗“人言山佳水亦佳，下有万古蛟龙潭”。井旁建有茶室。往南便回大路。  蒙面人(Mengmian ren)"
    region.rooms[91] = {}
      region.rooms[91].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w;n;e"
      region.rooms[91].name = "茶室"
      region.rooms[91].zone = "杭州"
      region.rooms[91].id = 300
      region.rooms[91].links = {}
        region.rooms[91].links.w = {}
          region.rooms[91].links.w.to = 299
          region.rooms[91].links.w.con = ""
      region.rooms[91].exits = "west"
      region.rooms[91].desc = "    这里是龙井茶茶室。在这里可以品到最新鲜的龙井。"
    region.rooms[92] = {}
      region.rooms[92].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w;ne"
      region.rooms[92].name = "土路"
      region.rooms[92].zone = "杭州"
      region.rooms[92].id = 301
      region.rooms[92].links = {}
        region.rooms[92].links.ne = {}
          region.rooms[92].links.ne.to = 302
          region.rooms[92].links.ne.con = ""
        region.rooms[92].links.sw = {}
          region.rooms[92].links.sw.to = 298
          region.rooms[92].links.sw.con = ""
      region.rooms[92].exits = "northeast|southwest"
      region.rooms[92].desc = "    路旁一条小溪。溪水哗哗地流着，不时有鱼儿(fish)跃出水面。溪旁几各男孩正低着头专心在钓鱼。"
    region.rooms[93] = {}
      region.rooms[93].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w;ne;ne"
      region.rooms[93].name = "茅家埠"
      region.rooms[93].zone = "杭州"
      region.rooms[93].id = 302
      region.rooms[93].links = {}
        region.rooms[93].links.nu = {}
          region.rooms[93].links.nu.to = 303
          region.rooms[93].links.nu.con = ""
        region.rooms[93].links.sw = {}
          region.rooms[93].links.sw.to = 301
          region.rooms[93].links.sw.con = ""
      region.rooms[93].exits = "northup|southwest"
      region.rooms[93].desc = "    路两旁盖着几座小土房。房门口一位老大娘正在喂鸡，几个小孩正在追逐嬉戏。北边是上黄泥岭。南面是丁家山。"
    region.rooms[94] = {}
      region.rooms[94].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;su"
      region.rooms[94].name = "黄泥岭"
      region.rooms[94].zone = "杭州"
      region.rooms[94].id = 303
      region.rooms[94].links = {}
        region.rooms[94].links.sd = {}
          region.rooms[94].links.sd.to = 302
          region.rooms[94].links.sd.con = ""
        region.rooms[94].links.nd = {}
          region.rooms[94].links.nd.to = 304
          region.rooms[94].links.nd.con = ""
      region.rooms[94].exits = "southdown|northdown"
      region.rooms[94].desc = "    一条黄土路弯弯曲曲，四周非常的安静。偶而才看见些游人匆匆而过。南北分别是下山的路。"
    region.rooms[95] = {}
      region.rooms[95].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw"
      region.rooms[95].name = "青石大道"
      region.rooms[95].zone = "杭州"
      region.rooms[95].id = 304
      region.rooms[95].links = {}
        region.rooms[95].links.ne = {}
          region.rooms[95].links.ne.to = 305
          region.rooms[95].links.ne.con = ""
        region.rooms[95].links.sw = {}
          region.rooms[95].links.sw.to = 307
          region.rooms[95].links.sw.con = ""
        region.rooms[95].links.su = {}
          region.rooms[95].links.su.to = 303
          region.rooms[95].links.su.con = ""
      region.rooms[95].exits = "northeast|southup|southwest"
      region.rooms[95].desc = "    大道两边遍植青松，满目苍翠，偃盖如雪。被称为“九里雪松”。东北边是洪春桥。再向西南便到了灵隐寺。南边是一条土路。"
    region.rooms[96] = {}
      region.rooms[96].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s"
      region.rooms[96].name = "洪春桥"
      region.rooms[96].zone = "杭州"
      region.rooms[96].id = 305
      region.rooms[96].links = {}
        region.rooms[96].links.n = {}
          region.rooms[96].links.n.to = 306
          region.rooms[96].links.n.con = ""
        region.rooms[96].links.sw = {}
          region.rooms[96].links.sw.to = 304
          region.rooms[96].links.sw.con = ""
      region.rooms[96].exits = "north|southwest"
      region.rooms[96].desc = "    从这里可以看到西湖十景之一的双峰插云(scenery)。大道通向北边，再向西南是通往灵隐寺的路。"
    region.rooms[97] = {}
      region.rooms[97].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw"
      region.rooms[97].name = "青石大道"
      region.rooms[97].zone = "杭州"
      region.rooms[97].id = 306
      region.rooms[97].links = {}
        region.rooms[97].links.s = {}
          region.rooms[97].links.s.to = 305
          region.rooms[97].links.s.con = ""
        region.rooms[97].links.ne = {}
          region.rooms[97].links.ne.to = 285
          region.rooms[97].links.ne.con = ""
      region.rooms[97].exits = "south|northeast"
      region.rooms[97].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西湖。往南是洪春桥。大道则延伸向东北边。"
    region.rooms[98] = {}
      region.rooms[98].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw"
      region.rooms[98].name = "青石大道"
      region.rooms[98].zone = "杭州"
      region.rooms[98].id = 307
      region.rooms[98].links = {}
        region.rooms[98].links.ne = {}
          region.rooms[98].links.ne.to = 304
          region.rooms[98].links.ne.con = ""
        region.rooms[98].links.sw = {}
          region.rooms[98].links.sw.to = 315
          region.rooms[98].links.sw.con = ""
        region.rooms[98].links.su = {}
          region.rooms[98].links.su.to = 308
          region.rooms[98].links.su.con = ""
      region.rooms[98].exits = "northeast|southup|southwest"
      region.rooms[98].desc = "    大道上游人，或步行，或乘轿，或骑马。个个喜气洋洋的来游西边是灵隐寺和飞来峰。往南是上天竺。"
    region.rooms[99] = {}
      region.rooms[99].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;su"
      region.rooms[99].name = "山路"
      region.rooms[99].zone = "杭州"
      region.rooms[99].id = 308
      region.rooms[99].links = {}
        region.rooms[99].links.su = {}
          region.rooms[99].links.su.to = 309
          region.rooms[99].links.su.con = ""
        region.rooms[99].links.nd = {}
          region.rooms[99].links.nd.to = 307
          region.rooms[99].links.nd.con = ""
      region.rooms[99].exits = "northdown|southup"
      region.rooms[99].desc = "    一条被人走出来的山路，弯弯曲曲地向上延伸。走在山路上，只见两旁峰峦秀丽，景色怡人。不时有进香客擦肩而过。南上便到了下天竺。北下就是大道。"
    region.rooms[100] = {}
      region.rooms[100].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;su;su"
      region.rooms[100].name = "法镜寺"
      region.rooms[100].zone = "杭州"
      region.rooms[100].id = 309
      region.rooms[100].links = {}
        region.rooms[100].links.su = {}
          region.rooms[100].links.su.to = 310
          region.rooms[100].links.su.con = ""
        region.rooms[100].links.nd = {}
          region.rooms[100].links.nd.to = 308
          region.rooms[100].links.nd.con = ""
      region.rooms[100].exits = "northdown|southup"
      region.rooms[100].desc = "    法镜寺建在小溪旁，格外的幽雅。进香的游客不时的进进出出。南上往中天竺。朝北是下山的路。"
    region.rooms[101] = {}
      region.rooms[101].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;su;su;su"
      region.rooms[101].name = "山路"
      region.rooms[101].zone = "杭州"
      region.rooms[101].id = 310
      region.rooms[101].links = {}
        region.rooms[101].links.su = {}
          region.rooms[101].links.su.to = 311
          region.rooms[101].links.su.con = ""
        region.rooms[101].links.nd = {}
          region.rooms[101].links.nd.to = 309
          region.rooms[101].links.nd.con = ""
      region.rooms[101].exits = "northdown|southup"
      region.rooms[101].desc = "    走在这条不是很宽的山路上，只见两旁峰峦秀丽，景色怡人。一条小溪在路边潺潺流过，溪畔有一农家。山村小景，使人有退隐江湖之意。南上便到了中天竺。北下就是下天竺。"
    region.rooms[102] = {}
      region.rooms[102].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w;wu;wu;nd;nd"
      region.rooms[102].name = "法净寺"
      region.rooms[102].zone = "杭州"
      region.rooms[102].id = 311
      region.rooms[102].links = {}
        region.rooms[102].links.su = {}
          region.rooms[102].links.su.to = 312
          region.rooms[102].links.su.con = ""
        region.rooms[102].links.nd = {}
          region.rooms[102].links.nd.to = 310
          region.rooms[102].links.nd.con = ""
      region.rooms[102].exits = "northdown|southup"
      region.rooms[102].desc = "    法净寺依山而立，寺前小溪流水。进香的游客不时的进进出出。南上往上天竺。朝北是下山的路。"
    region.rooms[103] = {}
      region.rooms[103].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w;wu;wu;nd"
      region.rooms[103].name = "山路"
      region.rooms[103].zone = "杭州"
      region.rooms[103].id = 312
      region.rooms[103].links = {}
        region.rooms[103].links.su = {}
          region.rooms[103].links.su.to = 313
          region.rooms[103].links.su.con = ""
        region.rooms[103].links.nd = {}
          region.rooms[103].links.nd.to = 311
          region.rooms[103].links.nd.con = ""
      region.rooms[103].exits = "northdown|southup"
      region.rooms[103].desc = "    小溪横过山路，跨溪有一座小石桥。溪边农家小孩在嬉戏玩乐。                    南上便到了上天竺。北下就是中天竺。"
    region.rooms[104] = {}
      region.rooms[104].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w;wu;wu"
      region.rooms[104].name = "法喜寺"
      region.rooms[104].zone = "杭州"
      region.rooms[104].id = 313
      region.rooms[104].links = {}
        region.rooms[104].links.ed = {}
          region.rooms[104].links.ed.to = 314
          region.rooms[104].links.ed.con = ""
        region.rooms[104].links.nd = {}
          region.rooms[104].links.nd.to = 312
          region.rooms[104].links.nd.con = ""
      region.rooms[104].exits = "eastdown|northdown"
      region.rooms[104].desc = "    法喜寺是天竺三寺中最敞朗深幽的一座。进香的游客不时的进进出出。往东可达龙井，朝北是下山的路。"
    region.rooms[105] = {}
      region.rooms[105].path = "fly hz;|!hoteld::w|;sw;sw;w;w;w;sw;w;wu;wu;wu;w;wu"
      region.rooms[105].name = "山路"
      region.rooms[105].zone = "杭州"
      region.rooms[105].id = 314
      region.rooms[105].links = {}
        region.rooms[105].links.ed = {}
          region.rooms[105].links.ed.to = 298
          region.rooms[105].links.ed.con = ""
        region.rooms[105].links.wu = {}
          region.rooms[105].links.wu.to = 313
          region.rooms[105].links.wu.con = ""
      region.rooms[105].exits = "westup|eastdown"
      region.rooms[105].desc = "    走在这弯弯的小路上，看着沿途山峰云影，松竹青葱，岩石斑驳。不禁感到胸怀舒畅。西上便到了上天竺。东下就到了龙井。"
    region.rooms[106] = {}
      region.rooms[106].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw"
      region.rooms[106].name = "青石大道"
      region.rooms[106].zone = "杭州"
      region.rooms[106].id = 315
      region.rooms[106].links = {}
        region.rooms[106].links.ne = {}
          region.rooms[106].links.ne.to = 307
          region.rooms[106].links.ne.con = ""
        region.rooms[106].links.s = {}
          region.rooms[106].links.s.to = 320
          region.rooms[106].links.s.con = ""
        region.rooms[106].links.n = {}
          region.rooms[106].links.n.to = 316
          region.rooms[106].links.n.con = ""
      region.rooms[106].exits = "south|north|northeast"
      region.rooms[106].desc = "    大道上挤满了来灵隐寺上香和上飞来峰的游客。北边过了小溪就是灵隐寺了。南边是上飞来峰的路。"
    region.rooms[107] = {}
      region.rooms[107].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;n"
      region.rooms[107].name = "灵隐寺"
      region.rooms[107].zone = "杭州"
      region.rooms[107].id = 316
      region.rooms[107].links = {}
        region.rooms[107].links.s = {}
          region.rooms[107].links.s.to = 315
          region.rooms[107].links.s.con = ""
        region.rooms[107].links.enter = {}
          region.rooms[107].links.enter.to = 317
          region.rooms[107].links.enter.con = ""
      region.rooms[107].exits = "south|enter"
      region.rooms[107].desc = "    灵隐寺又名云林寺，寺前有清澈的小溪，溪旁建有冷泉亭和赫雷亭。天王殿举目可见，殿外有两座经幢。往南便回到大道。"
    region.rooms[108] = {}
      region.rooms[108].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;n;enter"
      region.rooms[108].name = "天王殿"
      region.rooms[108].zone = "杭州"
      region.rooms[108].id = 317
      region.rooms[108].links = {}
        region.rooms[108].links.n = {}
          region.rooms[108].links.n.to = 318
          region.rooms[108].links.n.con = ""
        region.rooms[108].links.out = {}
          region.rooms[108].links.out.to = 316
          region.rooms[108].links.out.con = ""
      region.rooms[108].exits = "north|out"
      region.rooms[108].desc = "    走进大殿，只见正面坐着袒胸露腹的弭勒佛，两旁是四大天王，後面是神态威严的韦驮菩萨。天王殿後面便是大雄宝殿。"
    region.rooms[109] = {}
      region.rooms[109].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;n;enter;n"
      region.rooms[109].name = "大雄宝殿"
      region.rooms[109].zone = "杭州"
      region.rooms[109].id = 318
      region.rooms[109].links = {}
        region.rooms[109].links.s = {}
          region.rooms[109].links.s.to = 317
          region.rooms[109].links.s.con = ""
        region.rooms[109].links.enter = {}
          region.rooms[109].links.enter.to = 319
          region.rooms[109].links.enter.con = ""
      region.rooms[109].exits = "south|enter"
      region.rooms[109].desc = "    天王殿後是另一座高达三十几米的大殿。匾上写着“大雄宝殿”。殿前有两座八角九层石塔。往南又进了天王殿。"
    region.rooms[110] = {}
      region.rooms[110].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;n;enter;n;enter"
      region.rooms[110].name = "大雄宝殿"
      region.rooms[110].zone = "杭州"
      region.rooms[110].id = 319
      region.rooms[110].links = {}
        region.rooms[110].links.out = {}
          region.rooms[110].links.out.to = 318
          region.rooms[110].links.out.con = ""
      region.rooms[110].exits = "out"
      region.rooms[110].desc = "    殿内正中一尊如来佛像，两旁塑有二十尊诸天的佛像，大殿後壁有五十三参海岛像，岛上有姿态各异的大小佛像一百五十个。"
    region.rooms[111] = {}
      region.rooms[111].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;s"
      region.rooms[111].name = "飞来峰"
      region.rooms[111].zone = "杭州"
      region.rooms[111].id = 320
      region.rooms[111].links = {}
        region.rooms[111].links.eu = {}
          region.rooms[111].links.eu.to = 323
          region.rooms[111].links.eu.con = ""
        region.rooms[111].links.wu = {}
          region.rooms[111].links.wu.to = 321
          region.rooms[111].links.wu.con = ""
        region.rooms[111].links.n = {}
          region.rooms[111].links.n.to = 315
          region.rooms[111].links.n.con = ""
      region.rooms[111].exits = "westup|north|eastup"
      region.rooms[111].desc = "    飞来峰又名灵鹫峰。延着盘山小道往上走，只见溪盘岩石壁间雕着一尊袒腹露胸，喜笑自若的弭勒佛。旁边是一座气魄胸伟的多闻天王。北边是下山的路。小路往上延伸向东西两边。"
    region.rooms[112] = {}
      region.rooms[112].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;s;wu"
      region.rooms[112].name = "龙泓洞"
      region.rooms[112].zone = "杭州"
      region.rooms[112].id = 321
      region.rooms[112].links = {}
        region.rooms[112].links.ed = {}
          region.rooms[112].links.ed.to = 320
          region.rooms[112].links.ed.con = ""
        region.rooms[112].links.nw = {}
          region.rooms[112].links.nw.to = 322
          region.rooms[112].links.nw.con = ""
      region.rooms[112].exits = "northwest|eastdown"
      region.rooms[112].desc = "    又叫通天洞。在洞口的岩壁上刻有姿态各异，一丈多高的佛像六尊。左下方有两组浮雕。前一组记述了唐僧取经的故事；後一组为白马驮经，刻有“竺法阑”，“聂摩腾”字样。东边是下山的路。小路往上延伸向西北。"
    region.rooms[113] = {}
      region.rooms[113].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;s;wu;nw"
      region.rooms[113].name = "射旭洞"
      region.rooms[113].zone = "杭州"
      region.rooms[113].id = 322
      region.rooms[113].links = {}
        region.rooms[113].links.se = {}
          region.rooms[113].links.se.to = 321
          region.rooms[113].links.se.con = ""
      region.rooms[113].exits = "southeast"
      region.rooms[113].desc = "    洞後侧穹顶上的石罅间可仰见一束天光，故又名“一线天”。东南边是下山的路。"
    region.rooms[114] = {}
      region.rooms[114].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;s;eu"
      region.rooms[114].name = "清林洞"
      region.rooms[114].zone = "杭州"
      region.rooms[114].id = 323
      region.rooms[114].links = {}
        region.rooms[114].links.wd = {}
          region.rooms[114].links.wd.to = 320
          region.rooms[114].links.wd.con = ""
        region.rooms[114].links.eu = {}
          region.rooms[114].links.eu.to = 324
          region.rooms[114].links.eu.con = ""
      region.rooms[114].exits = "eastup|westdown"
      region.rooms[114].desc = "    又叫老虎洞。只见靠右雕有弭陀，观音，大势至三尊小佛。洞口东侧壁上还刻着一组“庐舍那佛会”浮雕，它上刻花头龛，中间坐着释迦牟尼，左右分列文殊，普贤，还有天王佛像。西边是下山的路。小路往上延伸向东。"
    region.rooms[115] = {}
      region.rooms[115].path = "fly hz;|!hoteld::w|;n;n;n;n;w;sw;w;w;sw;s;sw;sw;sw;s;eu;eu"
      region.rooms[115].name = "翠微亭"
      region.rooms[115].zone = "杭州"
      region.rooms[115].id = 324
      region.rooms[115].links = {}
        region.rooms[115].links.wd = {}
          region.rooms[115].links.wd.to = 323
          region.rooms[115].links.wd.con = ""
      region.rooms[115].exits = "westdown"
      region.rooms[115].desc = "    翠微亭建在飞来峰的半山间，是名将韩世忠为纪念岳飞而建的。岳飞有“经年尘土满征衣，特特寻芳上翠微”的诗句，故亭名“翠微”。西边是下山的路。"
    region.rooms[116] = {}
      region.rooms[116].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;nu;n;ne"
      region.rooms[116].name = "丘陵野路"
      region.rooms[116].zone = "杭州|福州"
      region.rooms[116].id = 325
      region.rooms[116].links = {}
        region.rooms[116].links.ne = {}
          region.rooms[116].links.ne.to = 242
          region.rooms[116].links.ne.con = ""
        region.rooms[116].links.sw = {}
          region.rooms[116].links.sw.to = 326
          region.rooms[116].links.sw.con = ""
      region.rooms[116].exits = "northeast|southwest"
      region.rooms[116].desc = "    从浙江到福建的山路，不算太长，但有些难走。"
    region.rooms[117] = {}
      region.rooms[117].path = "fly fz;w;w;w;w;w;nw;nw;nu;nd;nu;n"
      region.rooms[117].name = "仙霞岭"
      region.rooms[117].zone = "杭州|福州"
      region.rooms[117].id = 326
      region.rooms[117].links = {}
        region.rooms[117].links.ne = {}
          region.rooms[117].links.ne.to = 325
          region.rooms[117].links.ne.con = ""
        region.rooms[117].links.s = {}
          region.rooms[117].links.s.to = 327
          region.rooms[117].links.s.con = ""
      region.rooms[117].exits = "south|northeast"
      region.rooms[117].desc = "    这里就是闽浙分水的仙霞岭。向阳的坡面郁郁葱葱，长满了长长的马尾松。沿途的山路十分难行，来往的口音也渐渐带有闽音，越来越难以辩识了。"
    region.rooms[118] = {}
      region.rooms[118].path = "fly hz;|!hoteld::w|;n;n;n;n;w;nu;nu"
      region.rooms[118].name = "保淑塔"
      region.rooms[118].zone = "杭州"
      region.rooms[118].id = 2965
      region.rooms[118].links = {}
        region.rooms[118].links.sd = {}
          region.rooms[118].links.sd.to = 293
          region.rooms[118].links.sd.con = ""
      region.rooms[118].exits = "southdown"
      region.rooms[118].desc = "    保淑塔姿态秀丽挺拔，塔基极小，却负荷了极高的塔身。传说吴越王钱弘淑奉召入京，久留未返，他大臣吴延爽为祝原其平安归来，而建此塔，故名保淑塔。往南是下山的路。"
  region.center = 222
return region