local region = {}
  region.cmd = "|!kl1::hi|"
  region.name = "昆仑山1"
  region.id = "kl1"
  region.rooms = {}
    region.rooms[1] = {}
      region.rooms[1].path = "|!kl1::hi|"
      region.rooms[1].name = "松树"
      region.rooms[1].zone = "昆仑山1"
      region.rooms[1].id = 3009
      region.rooms[1].desc = "    这是一株长于峭壁上的松树。向上而望，不能看见悬之上之物，刚才从上而跳下之时，回想起来你自不禁心悸，额头冷汗涔涔而下，一看四下形势，向上而攀援是绝不可能，脚下深不见底。便算到了底下，十之八九也是没有出路，唯有沿着山壁斜坡，慢慢的爬行出去。"
      region.rooms[1].exits = ""
      region.rooms[1].links = {}
        region.rooms[1].links["pa east"] = {}
          region.rooms[1].links["pa east"].to = 3011
          region.rooms[1].links["pa east"].con = ""
        region.rooms[1].links["pa west"] = {}
          region.rooms[1].links["pa west"].to = 3010
          region.rooms[1].links["pa west"].con = ""
    region.rooms[2] = {}
      region.rooms[2].path = "|!kl1::hi|;pa west"
      region.rooms[2].name = "悬崖"
      region.rooms[2].zone = "昆仑山1"
      region.rooms[2].id = 3010
      region.rooms[2].links = {}
        region.rooms[2].links["pa east"] = {}
          region.rooms[2].links["pa east"].to = 3009
          region.rooms[2].links["pa east"].con = ""
      region.rooms[2].exits = ""
      region.rooms[2].desc = "    你向西爬行，这边的山势十分凶险，直爬了半个时辰，眼前再无出路了。你不禁临崖浩叹，怔怔的呆了良久。"
    region.rooms[3] = {}
      region.rooms[3].path = "|!kl1::hi|;pa east"
      region.rooms[3].name = "雪山斜坡"
      region.rooms[3].zone = "昆仑山1"
      region.rooms[3].id = 3011
      region.rooms[3].links = {}
        region.rooms[3].links["pa east"] = {}
          region.rooms[3].links["pa east"].to = 3012
          region.rooms[3].links["pa east"].con = ""
        region.rooms[3].links["pa west"] = {}
          region.rooms[3].links["pa west"].to = 3009
          region.rooms[3].links["pa west"].con = ""
      region.rooms[3].exits = ""
      region.rooms[3].desc = "    你手脚着地，沿着雪山斜坡，一步一步向着有阳沅之处爬去，但此峭壁本就极陡，加上冻结冰雪，更是滑溜无比，一不小心则会滑跌。"
    region.rooms[4] = {}
      region.rooms[4].path = "|!kl1::hi|;pa east;pa east"
      region.rooms[4].name = "雪山斜坡"
      region.rooms[4].zone = "昆仑山1"
      region.rooms[4].id = 3012
      region.rooms[4].links = {}
        region.rooms[4].links.e = {}
          region.rooms[4].links.e.to = 3013
          region.rooms[4].links.e.con = ""
        region.rooms[4].links["pa west"] = {}
          region.rooms[4].links["pa west"].to = 3011
          region.rooms[4].links["pa west"].con = ""
      region.rooms[4].exits = ""
      region.rooms[4].desc = "    你手脚着地，沿着雪山斜坡，一步一步向着有阳沅之处爬去，但此峭壁本就极陡，加上冻结冰雪，更是滑溜无比，一不小心则会滑跌。"
    region.rooms[5] = {}
      region.rooms[5].path = "|!kl1::hi|;pa east;pa east;e"
      region.rooms[5].name = "大平台"
      region.rooms[5].zone = "昆仑山1"
      region.rooms[5].id = 3013
      region.rooms[5].desc = "    前面是一堵屏风也似的大山壁。眼前茫茫云海，更无去路，你竟是置身在一个三面皆空的极高平台上。那平台倒有十余丈方圆，可是半天临空，上既不得，下又不能，当真是死路一条。这大平台上白皑皑的都是冰雪，既无树林，更无野兽。唯有平台下有一株松树(tree)。    你向前滑出一步，但见左侧山壁黑黝黝的似乎有个洞穴，山壁侧黑黝黝似乎有个小山洞(dong)。"
      region.rooms[5].exits = "west"
      region.rooms[5].links = {}
        region.rooms[5].links.w = {}
          region.rooms[5].links.w.to = 3012
          region.rooms[5].links.w.con = ""
  region.center = 3009
return region